### ISSUE TITLE
Custom collections of futures

### ISSUE THREAD

**Issue by sdalton1** [StanfordLegion/legion#100]
I would like a structure that contains a collection of futures with similar behavior as FutureMap, such as wait_all_results and get_future(point). FutureMap does everything I want but does not allow adding individual futures, something like

FutureMap fm;
fm.add(my_future1);
fm.add(my_future2);
fm.wait_all_results();

Currently FutureMap is designated as the return value of an index space launch but I wanted to know if supporting a more general interface would be possible or if I should build my own class.

**Comment by lightsighter** [comment]
Adding this as an enhancement to consider going forward.

**Comment by streichler** [comment]
@lightsighter are you still considering this?  It seems like application-modifyable FutureMaps might be problematic in a dynamic control replication setting.

**Comment by lightsighter** [comment]
They are actually fine in a control replication setting as long as they all do the same thing. 

I'm going to close this issue since we now have the ability to create an ArgumentMap from a FutureMap and then modify the entries in it.
