### ISSUE TITLE
RFE: Optional flag for read-write privilege warning

### ISSUE THREAD

**Issue by alvarozamora** [StanfordLegion/legion#1000]
For context, I've been working on a fluid code written in regent. There are many test problems in the field whose initial conditions are represented analytically (some are as simple as two piecewise constant regions). For such initial conditions, it is simply more efficient to internally generate them after picking a mesh resolution and generating a mesh (in contrast to generating them externally, writing them to an hdf5 file (or otherwise) and then reading them into a regent program). Because these are problems with multiple scalar fields (e.g. density, momentum, energy), some which depend on each other, I need  read-write privileges to initialize them in one go in a way which matches the way variables are found in the literature. For example, for a ramped Kelvin-Helmholtz problem, I initialize via

```
elseif testProblem == 4 then

    var rho1 : double = 2.0
    var rho2 : double = 1.0

    var P : double = 2.0
    var vrel : double = 2.0
    var amp : double = 0.04
    var vb : double = 0.0

    var delta : double = 0.05

    for e in r_W do

      var Ramp : double = 1/(1 + cmath.exp(-2*(r_mesh[e].y - 0.25)/delta)) * 1/(1 + cmath.exp(-2*(0.75 - r_mesh[e].y)/delta))
      var vx : double = vb - vrel/2 + Ramp*(vrel)
      var rho : double = rho2 + Ramp*(rho1 - rho2)
      var vy : double = amp*cmath.sin(2*PI*r_mesh[e].x)

      r_W[e].rho = rho
      r_W[e].rhov[0] = rho*vx
      r_W[e].rhov[1] = rho*vy
      r_W[e].rhov[2] = 0
      r_W[e].rhoE = Cv*P/R + 0.5*(r_W[e].rhov[0]*r_W[e].rhov[0] + r_W[e].rhov[1]*r_W[e].rhov[1])/r_W[e].rho

    end
```

When I try running this for a sizable node count (e.g. 64 nodes with 2048 subregions), I get hundreds of megabytes of warnings dumped to my output file from all of the uninitialized regions I am initializing inside the program. I could very easily write e.g. `r_W[e].rhov[0]`  and `r_W[e].rhov[1]` in `r_W[e].rhoE` in terms of its principal components `rho`, `vx` and `vy`, but it would be nice to be able to turn off the warning once understanding there is really no issue. Thus I am requesting such a flag to be able to turn off this warning. Alternatively, there could be a max (e.g. 50) number of warnings after which the warning is suppressed, or the warning could simply enumerate the number of subregions that satisfied this warning criteria. I could be wrong but I imagine for many cases the entire region is uninitialized and just one warning per task would fit the bill.

Currently, I have a workaround in `/runtime/legion_tasks.cc` which simply turns off the warning:

```
#if 0
      else // Read-write usage is just a warning
        REPORT_LEGION_WARNING(LEGION_WARNING_UNINITIALIZED_USE,
                      "Region requirement %d of operation %s (UID %lld) in "
                      "parent task %s (UID %lld) is using uninitialized data "
                      "for field(s) %s of logical region (%d,%d,%d)", index, 
                      get_logging_name(), get_unique_op_id(),
                      parent_ctx->get_task_name(), parent_ctx->get_unique_id(),
                      field_string, handle.get_index_space().get_id(),
                      handle.get_field_space().get_id(), 
                      handle.get_tree_id())
#endif
```

**Comment by elliottslaughter** [comment]
Hi @alvarozamora,

A couple of things:

 1. If you want to silence this warning (and only this warning) today, the fastest way to do so is with a fill. You could do that with e.g.:

    ```
    fill(r_W.{rho, ...}, 0)
    ```

    It's still a bit of a pain because you have to list out the fields, but it works and will ensure you don't get this message any more.
 2. Another approach we've discussed in the past is `discard` privileges (#721). But that's not implemented right now and I think we still don't have complete agreement on the features/syntax.
 3. I think a flag to disable the warning is plausible but we'd need to get @lightsighter's feedback and would at any rate need to be implemented. We'd also have to decide whether to make a special case or attempt to make this general (i.e. so you could disable any set of warnings).
 4. I don't know about limiting the number of warnings, that may be possible if it's a purely local thing (i.e., every runtime will independently issue up to 50 warnings, or whatever).

CC @lightsighter for further thoughts.

**Comment by lightsighter** [comment]
With regards to (3): We already have such a flag: `-level runtime=5` will silence all warnings from the runtime. Alternatively if you are running for performance and worried about branching overhead, you can compile with the minimum logging level set to `LEVEL_ERROR`. 

With regards to (4): I don't really like things that disable warnings after a fixed number. How are users supposed to know which ones are important or not? There's also no way to selectively disable warnings currently, so I would rather just have them all on all the time, and if users don't want to see them, they have the switch needed to turn off all runtime warnings.

**Comment by lightsighter** [comment]
@opensdh @ipdemes  Moving our discussion about read-write privilege warnings to this issue since it is more appropriate here and avoids hijacking the primary purpose of #721.

I still believe the original proposal floated in #721 was much too complex and would add considerable runtime complexity while also taking power away from users to defined their own "ABI" for tasks. Thererefore I'm proposing something different.

I am willing to add a flag that users can put on a region requirement to silence the warnings associated with that region requirement. It will be the user's responsibility to annotate all the region requirements upon which they want to silence the warnings.

@elliottslaughter to comment on if/how he would expose this in Regent.

**Comment by elliottslaughter** [comment]
I guess I could add a Regent flag that could set this, but is that what people want? Or is the suggestion something else?

**Comment by opensdh** [comment]
I believe that FleCSI can avoid all the warnings we currently generate with this approach.  The "general" kind result from switching from one partition of a region to a larger partition, and we can track when such a resize has occurred.  The one other kind arises from an internal task that initialized a field with `READ_WRITE` permissions because it sometimes reused a prefix from a previous call.  Here, it was simpler to separate the first initialization and use `WRITE_DISCARD` for it.

Of course, absent the actual feature I can't be absolutely sure that all the warnings will be caught, but it looks simple enough.

**Comment by lightsighter** [comment]
Here is a merge request that adds support for a flag that you can add to a region requirement that will then suppress warnings associated with that region requirement:

https://gitlab.com/StanfordLegion/legion/-/merge_requests/1285

Note that this only suppresses warnings. If you have actual errors like doing read-only or reduce privileges on uninitialized data that will remain an error.

@elliottslaughter to see if/how he wants to use this in Regent. I suppose Regent could just add this flag to all region requirements with read-write privileges to make all the warnings that occur today go away.

**Comment by lightsighter** [comment]
Merge request 1285 is merged so closing this issue.
