### ISSUE TITLE
Realm: align CUDA hi-jack handling of zero-size allocation/free with CUDA runtime

### ISSUE THREAD

**Issue by MatthiasKohl** [StanfordLegion/legion#1001]
When calling `cudaMalloc(&ptr, 0);`, the CUDA run-time succeeds while the hi-jack fails because `cuMemAlloc` returns an error for `size==0`.

In any case, I believe the hi-jack should check for `size==0` in `cudaMalloc` and return a `nullptr` and succeed.
In `cudaFree`, either:
1. do not change anything: from my small tests, it looks like `cuMemFree` succeeds with a `nullptr` (although I'd check if this is documented somewhere)
2. check for `nullptr` and succeed.

I haven't tested this behavior with the other possible options for allocating memory such as host & managed.

**Comment by streichler** [comment]
This should be fixed with commit a30499a.  @MatthiasKohl can you confirm your use case is happier?

**Comment by MatthiasKohl** [comment]
@streichler : yes I have tested with the new commit, and it works as expected. I'll close this issue.
