### ISSUE TITLE
Selecting source instance for copy

### ISSUE THREAD

**Issue by jiazhihao** [StanfordLegion/legion#1002]
I encountered a performance issue when copying data for an index launch. I assume this is a mapper issue, but not sure which mapper API is related to it.

The use case is simple. The index launch has multiple tasks using the same logical region with read-only privilege. I have seen that Legion generates sequential copies instead of parallelizable copies when preparing physical instances for the logical region. More specifically, let's say the logical region has a valid instance on GPU_0, and the index launch assigns tasks to GPU_1 and GPU_2. Legion runtime generates two sequential copies (GPU_0->GPU_1, then GPU_1->GPU_2) instead of parallel copies (GPU_0->GPU_1, and GPU_0->GPU_2).

Which mapper API should be changed to fix the issue?

**Comment by lightsighter** [comment]
It will depend on the kind of operation that triggered the copies, but most likely it will be `select_task_sources`. All the API calls that handle selecting the source of the copies are named like `select_*_sources` for the different kinds of operations. If you leave the output of this mapper call empty, the runtime can do whatever it wants, and I guarantee you there is no intelligent logic in the runtime for this. It just picks the first instance it finds.

**Comment by manopapad** [comment]
Note that the order in which tasks are passed to the mapper will dictate what instances you can select for each (if T1 is mapped first then it will only see the instance on GPU0, then T2 will be able to use instances on both GPU0 and GPU1). Depending on the machine architecture, not every ordering will allow you to create the most efficient broadcast tree. You can try to work around this by changing the order of mapping in `select_tasks_to_map`, but [collective instances](https://github.com/StanfordLegion/legion/issues/546) is a much better solution to this problem, so I would just wait for that.

**Comment by lightsighter** [comment]
I think in this case though order will not matter and it's actually fairly simple. The instance on GPU 0 is valid from the start, and we just want all the tasks downstream to pull from it instead of pulling from each other.

**Comment by jiazhihao** [comment]
@lightsighter Should I set the `source_instances` field in `map_task` in order to tell Legion which source instance to copy from?
I see that field in the mapper interface but haven't found any mapper that actually set that field.

```
      struct MapTaskOutput {
        std::vector<std::vector<PhysicalInstance> > chosen_instances;
        std::vector<std::vector<PhysicalInstance> > source_instances;
        std::vector<Memory>                         output_targets;
        std::vector<LayoutConstraintSet>            output_constraints;
        std::set<unsigned>                          untracked_valid_regions;
        std::vector<Processor>                      target_procs;
        VariantID                                   chosen_variant; // = 0 
        TaskPriority                                task_priority;  // = 0
        TaskPriority                                profiling_priority;
        ProfilingRequest                            task_prof_requests;
        ProfilingRequest                            copy_prof_requests;
        bool                                        postmap_task; // = false
      };
```

**Comment by lightsighter** [comment]
I got this question from you too, but I don't see it anywhere on this page anymore.

> @lightsighter Should I set the source_instances field in map_task in order to tell Legion which source instance to copy from?
I see that field in the mapper interface but haven't found any mapper that actually set that field.

I'll answer it anyway. If you actually know the instance(s) you want to use as sources ahead of time without waiting for the call back to `select_task_sources` then you can fill them in direction in the `source_instances` member for `map_task`. That can reduce the analysis runtime because it effectively preempts potentially many callbacks to `select_task_sources`. That's strictly a performance optimization, but a good one if you know what the answer should be.

**Comment by streichler** [comment]
@jiazhihao are there any open questions here or can we close out this issue?
