### ISSUE TITLE
Sapling replacement/upgrade

### ISSUE THREAD

**Issue by manopapad** [StanfordLegion/legion#1018]
This issue is meant to document why we need to replace/upgrade sapling, and what people need the new system to be. This information will hopefully inform the next steps on this process. Please add your own usecases and comments.

Adding below information from a Slack discussion on 2021-02-12 (paraphrasing for readability):

@manopapad:
* I would like to have a system for development and small-scale performance debugging like what sapling is today, i.e. a small cluster with a couple GPUs per node.
* I would prefer it to be a bare-metal cluster (as opposed to container-based), as that allows for a much shorter code-debug cycle (if a required fix is early in the dockerfile that triggers a lengthy rebuild).
* We want to be able to freely ssh and gdb into our nodes, for collaborative debugging.
* This system would also serve as a well-known platform that everyone has access to, such that if a user can reproduce a bug on it, a developer can easily pick it up from there.
* CI and docker builds is another, separate usecase, that could potentially be served by a separate machine.
* I don’t think absolute performance is a priority; previous-gen hardware and ethernet are acceptable.
* I am not opposed to a job scheduler if it helps people not step on each other.

@elliottslaughter:
* Gates is still our best choice in terms of control.
    * Stanford CS IT would allow us to retain some amount of control of the server, which is important e.g. for being able to set up our Gitlab CI however we want (something we can't currently do even on our Sherlock nodes, despite "owning" them).
    * But it might still be better to do it ourselves if we can, since we do give up some freedom here.
 * I think it's nice to have common access to a central server that we can do anything to and give any access to, without having to jump through hoops. I think this is a big part of what keeps sapling alive despite being so old.
 * Personally I could live without all the nodes having GPUs though having at least some GPUs (and modern ones) would be nice.
 * I personally do not like having to do everything in Docker. You can use Docker as a stateful platform (e.g., manually apt-get install into a container), but Docker just isn't very ergonomic. It's easy to lose your containers, or forget where they are, there isn't clean separation between users etc.
 * It would be nice to have a beefier head node. I do a lot of builds on sapling and they'd go faster if the head node weren't so slow.
 * CI is a mostly separate issue, though we have run into trouble doing it in a "too controlled" environment, so maybe the best way to force it is to do it at the same time.
 * Performance matters for CI, at least to some extent. We have had trouble recently because Regent tests tend to be slow when we migrate off of Google Cloud.

@syamajala:
We need a sapling replacement because that's the only machine that everyone at SLAC has access to.

Rohan Yadav:
I find a setup like sapling easier to develop on compared to machines like sherlock that are managed by a job scheduler.

**Comment by lightsighter** [comment]
Echoing points about debugging: sapling is the only machine where I can attach gdb to frozen processes from other users and inspect what went wrong on in their code. I can also pretend to be users who have set up reproducers with complicated settings that would difficult for me to reproduce myself.

**Comment by elliottslaughter** [comment]
I think we basically did this, right? Should we close this?

**Comment by syamajala** [comment]
There was talk of upgrading ubuntu on the login node at some point.

**Comment by manopapad** [comment]
I would also like to see the slurm installation on the head node be compatible with the slurm installation on the compute nodes, so I don't have to do this https://github.com/stanfordhpccenter/soleil-x/blob/master/src/sapling_reload_modules.sh.
