### ISSUE TITLE
Fix the Inner Task Optimization

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#102]
The inner task optimization has an unknown but most likely fundamental flaw that needs to be discovered and fixed before we can re-enable it.

**Comment by lightsighter** [comment]
This might also be an issue with the compiler not properly abiding by the requirements of inner task semantics.  Waiting until issue 103 is resolved to confirm.

**Comment by magnatelee** [comment]
Issue #103 turned out to be spurious and the compiler was doing the right job (the compiler doesn't even emit code to retrieve accessors when the task is an inner task: https://github.com/StanfordLegion/legion/blob/master/language/src/regent/codegen.t#L5724-L5745).

**Comment by lightsighter** [comment]
After some investigation it looks like the inner task optimization is correct so I am re-enabling it and closing this issue for now.
