### ISSUE TITLE
Update make-based build for recent CUDA-aware GASNet

### ISSUE THREAD

**Issue by manopapad** [StanfordLegion/legion#1024]
I ran into the following linking error while building Legion in a CUDA- and Infiniband-enabled container:

```
mpicxx -o legion_python  main.cc.o     -L. -llegion -lrealm -lrt -lpthread -ldl -rdynamic -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib64/stubs -lcudart -lcuda -Xlinker -rpath=/usr/local/cuda/lib64 -L/opt/legate/install/gasnet/lib -lrt -lm -lgasnet-ibv-par -libverbs -L/lib -lmpi -lz
/usr/bin/ld: ./librealm.so: undefined reference to symbol 'cuDevicePrimaryCtxRelease'
```

This happens because GASNet references CUDA driver symbols not referenced by `librealm.so`, and thus not included when `-lcuda` is encountered. If we move the CUDA linking after GASNet it works:

```
mpicxx -o legion_python  main.cc.o     -L. -llegion -lrealm -lrt -lpthread -ldl -rdynamic -L/opt/legate/install/gasnet/lib -lrt -lm -lgasnet-ibv-par -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib64/stubs -lcudart -lcuda -libverbs -L/lib -lmpi -lz
```

The make-based flow should really be updated to include the GASNet-provided make snippet and use the CFLAGS/LDFLAGS defined there.

**Comment by lightsighter** [comment]
What is the "GASNet-provided make snippet"?

If can certainly move around the order of libraries on the link line so GASNet comes before CUDA. I want to make sure there is nothing else that needs to happen though to fix this.

**Comment by manopapad** [comment]
@streichler, could you provide more info on the GASNet-provided make snippets?

**Comment by streichler** [comment]
When GASNet is installed, there's a .mak file for each conduit/threading mode that can be included by the Legion makefile.
It lives at `$(GASNET)/$(CONDUIT)-conduit/$(CONDUIT)-par.mak` (we only care about the "par" threading mode), and it defines things like `GASNET_LIBS`, `GASNET_LDFLAGS`, and `GASNET_CXXFLAGS`.

**Comment by lightsighter** [comment]
@streichler So does that mean that I need to include that and then use `GASNET_CXXFLAGS` when compiling any Realm files? I think I know what to do with `GASNET_LIBS` and `GASNET_LDFLAGS`. Also, is this only for GASNet-EX or does this exist on older versions of GASNet also?

**Comment by streichler** [comment]
Actually, looking again at what's in CXXFLAGS, I'd probably skip those.  They bake in things like optimization settings.

This should work on any version of GASNet-1 or GASNet-EX that's supported by our helper build scripts (i.e. 1.30.0+).

**Comment by lightsighter** [comment]
There is a fix in master now for this with `5a45e8732b7`. Will merge it into control replication once it passes CI.

**Comment by lightsighter** [comment]
Fix merged into control replication. Assigning back to @manopapad to confirm.

**Comment by manopapad** [comment]
This change fixes my docker build.
