### ISSUE TITLE
Realm -- special use case:  environment variable parsing assumes main()-based entry path

### ISSUE THREAD

**Issue by pmccormick** [StanfordLegion/legion#1026]
When driving Realm initialization via code-generation (e.g., mid-stage of a compiler) it is desirable to utilize the `REALM_DEFAULT_ARGS` environment variable to control runtime behaviors.  However, the implementation currently assumes a valid path from main through the call stack (i.e., `argc >= 1`) and the leading part of the environment is cut off:

- `REALM_DEFAULT_ARGS="-ll:cpu 1 -ll:force_kthreads"` behaves as if `REALM_DEFAULT_ARGS="1 -ll:force_kthreads"` was specified.

I believe there are a few spots were `argc`-based logic fails when no command line is available (`argc == 0`, `argv` is empty).   A quick workaround is to supply a dummy argv[0] in the environment variable: 

- `REALM_DEFAULT_ARGS="a.out -ll:cpu 1 -ll:force_kthreads"`

**Comment by streichler** [comment]
With commit 9deddfd, both the `argc == 0` case and the `null pointers used for argc and argv` case should work.
