### ISSUE TITLE
How to launch task that is compiled separately?

### ISSUE THREAD

**Issue by GuanLuo** [StanfordLegion/legion#1027]
I wonder if the following use case is supported: the tasks are compiled separately (as shared library maybe?) and I know the function name, can my application load the shared library dynamically and run those tasks?

**Comment by lightsighter** [comment]
Yes, you can call `dlopen` on a shared object and as part of the loading for that library, dynamically register function pointers as tasks with the Legion runtime. Additionally, Legion provides special support for libraries by providing custom ID generation routines (e.g. `generate_library_task_ids`) which allow libraries to ensure that their tasks are assigned the same task ID even if the library is dlopen-ed on different nodes at different times. Pretty much all Legate libraries work this way on top of Legion, so its a very common idiom.

**Comment by lightsighter** [comment]
Closing out this issue. If you've got further questions, feel free to reopen the issue here or follow up with me on slack.
