### ISSUE TITLE
realm: invalid event handle error

### ISSUE THREAD

**Issue by bandokihiro** [StanfordLegion/legion#1031]
On 2 ranks, after a million iterations, I hit this error
```
[0 - 7f8a38022900] 1256.718650 {6}{realm}: invalid event handle: id=1
solver: /home/ihme/bandok/LeDGendTests/legion/runtime/realm/runtime_impl.cc:2236: Realm::EventImpl* Realm::RuntimeImpl::get_event_impl(Realm::Event): Assertion `0 && "invalid event handle"' failed.
```
I am on comit bf4405d2.
Attached are backtraces.
[gdb0.txt](https://github.com/StanfordLegion/legion/files/6142518/gdb0.txt)
[gdb1.txt](https://github.com/StanfordLegion/legion/files/6142519/gdb1.txt)

**Comment by lightsighter** [comment]
Run with `-lg:no_physical_tracing` and report what happens.

**Comment by bandokihiro** [comment]
It passed one million iterations without the error.

**Comment by lightsighter** [comment]
@streichler to give you a patch to assert whenever we try to advance a `NO_BARRIER`

When that crashes I will look at the backtrace.

**Comment by streichler** [comment]
Adding `assert(id);` before this line: https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/realm/event_impl.cc#L492
should do the trick.

**Comment by bandokihiro** [comment]
[gdb0.txt](https://github.com/StanfordLegion/legion/files/6151353/gdb0.txt)
[gdb1.txt](https://github.com/StanfordLegion/legion/files/6151354/gdb1.txt)

**Comment by lightsighter** [comment]
Backtraces without line numbers are not helpful.

**Comment by lightsighter** [comment]
If you can reproduce this on sapling with `-O2 -g` then send me process numbers for a frozen process instead.

**Comment by bandokihiro** [comment]
Sorry, I forgot `-g`. Please look at process `2806177` on `c0001`.

**Comment by bandokihiro** [comment]
I put the time limit to 24 hours on this job.

**Comment by lightsighter** [comment]
Pull `control_replication` and try again.

**Comment by bandokihiro** [comment]
Fixed. Thanks.
