### ISSUE TITLE
realm: missing OpenMP symbols

### ISSUE THREAD

**Issue by bandokihiro** [StanfordLegion/legion#1036]
I was trying to build my code using clang for debugging purposes (I wanted to use `-fsanitize=memory`). I found missing OpenMP symbols:
```
__kmpc_for_static_init_8u
__kmpc_end_reduce_nowait
__kmpc_for_static_fini
__kmpc_fork_call
__kmpc_reduce_nowait
```

**Comment by streichler** [comment]
All of those symbols should be there.  How are you building Legion?

**Comment by bandokihiro** [comment]
Argh... Turns out that changing the compiler with cmake-gui completely reset my set-up and the OpenMP option got disabled on the way. My bad. I got this error at runtime though
```
HELP!  __kmpc_fork_call called with argc == 21
solver: /home/kihiro/Softwares/legion/runtime/realm/openmp/openmp_api.cc:856: void __kmpc_fork_call(Realm::ident_t *, Realm::kmp_int32, Realm::kmpc_micro, ...): Assertion `0' failed.

```

**Comment by streichler** [comment]
I'll push a change to increase the argc limit for kmpc_fork_call later today.  (Unfortunately, the argc is based on the
number of variables captured by the omp loop, which isn't bounded, but I have to use switch-based dispatch for
portability.)

**Comment by streichler** [comment]
Limit increased to 32 with commit 99ce3b20.
