### ISSUE TITLE
Regent: Errors during executable linking on IBM Power 9 machine with LLVM 90

### ISSUE THREAD

**Issue by mariodirenzo** [StanfordLegion/legion#1038]
If I try to compile HTR on an IBM Power 9 machine (https://wiki.u-gov.it/confluence/display/SCAIUS/UG3.2%3A+MARCONI100+UserGuide) using LLVM 90 I get a lot of errors like
```
terra:(.text+0x227b1c): call to `legion_task_postamble' lacks nop, can't restore toc; recompile with -fPIC
terra:(.text+0x227b1c): unresolvable R_PPC64_REL24 against `legion_task_postamble'
/usr/bin/ld: final link failed: Bad value
```
when linking the executable.

If LLVM 60 is used, the linking is executed correctly.

**Comment by mariodirenzo** [comment]
For future reference, the error reproduces with the command `../regent.py embed_tasks.rg` executed in the folder `language/examples` of the legion repository

**Comment by manopapad** [comment]
Recording some comments on this from a Slack discussion.

It looks like we need to pass `-fPIC` when producing a `.o` file from a `.rg` file using `saveobj`. Unfortunately it doesn't seem straightforward to pass such flags to llvm when it compiles object files, i.e. here https://github.com/terralang/terra/blob/0636d05b56cadc5fd324b8346d42cacc4b491090/src/tllvmutil.cpp#L148-L179.

It might be possible to work around this by saving bitcode and then compiling with `llc`

**Comment by thiagotei** [comment]
Experienced the same problem with LLVM 11.0.1 in Power9 machine.

**Comment by elliottslaughter** [comment]
Can someone try to reproduce this again with LLVM 13? I am no longer able to replicate #939 on Summit with LLVM 13.

**Comment by elliottslaughter** [comment]
For what it's worth, I am no longer able to replicate the error with `./regent.py examples/embed_tasks.rg` with the same configuration I noted at https://github.com/StanfordLegion/legion/issues/939#issuecomment-1099526412.

**Comment by mariodirenzo** [comment]
I am not able to replicate this issue either with LLVM 13. Thanks for fixing this issue
