### ISSUE TITLE
Missing deserialization in index launch with reduction op

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#104]
When calling `execute_index_space(Context, const IndexLauncher, ReductionOpID)`, I have seen an assertion failing at legion_tasks.cc:6097:

    assert(result_size == reduction_op->sizeof_rhs);

I believe that this is the result of Legion failing to deserialize the result value which it is attempting to reduce. A brief debugger session showed that `result_size` was 12 while `reduction_op->sizeof_rhs` was 16. This would be consistent with result being serialized (the result contained an 8 byte size and a 4 byte payload) and `reduction_op->sizeof_rhs` being the in-memory representation (which uses a 8 byte pointer to payload and an 8 byte size).

**Comment by lightsighter** [comment]
I'm pretty sure this is an application bug.  I'm putting in some better error messages.  I really need a backtrace to know anything.

**Comment by lightsighter** [comment]
Fixed with https://github.com/StanfordLegion/legion/commit/c50219edcdbf395f25fb974517d644688eb07f10
