### ISSUE TITLE
Realm: GASNet-EX assertion fail

### ISSUE THREAD

**Issue by rupanshusoi** [StanfordLegion/legion#1040]
Circuit appears to fail non-deterministically with the following error on multi-node runs:

```legion/runtime/realm/gasnetex/gasnetex_internal.cc:1741: void Realm::XmitSrcDestPair::push_packets(bool, Realm::TimeLimit): Assertion `immediate_mode' failed.```

I'm using the `regent-index-launch-sc21` branch from GitLab and the [associated instructions](https://gitlab.com/StanfordLegion/legion/-/tree/regent-index-launch-sc21/language/sc21_scripts) to run and build on Piz Daint.

**Comment by streichler** [comment]
As discussed via email, let's try replacing that assert with:
```
assert(immediate_mode || (min_size > max_payload));
```

**Comment by streichler** [comment]
Can we re-test this in a build that includes commit 2c777969?  There may be other issues with Realm's use of the Aries conduit in the gasnetex code, but I think this particular issue should be fixed.

**Comment by elliottslaughter** [comment]
@rupanshusoi Is this still relevant?

**Comment by rupanshusoi** [comment]
No, closing.
