### ISSUE TITLE
Regent: Performance regression in CUDA codegen with LLVM 6 vs 3.8

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1041]
While running experiments for a paper recently I was in a position to directly compare LLVM 3.8 vs 6 CUDA codegen performance. I saw a performance regression of about 25-33% in two out of three apps, and a 5% increase in performance in one other. This issue is mostly to document the fact that the regression exists and to attempt make it as reproducible as possible.

I observed the following single-node results:

  * Circuit: 2.0 => 2.5 s (25% increase in running time)
  * Pennant: 2.4 => 3.2 s (33% increase in running time)
  * Stencil: 4.0 => 3.8 s (5% decrease in running time)

Best guess at the moment is that this is a result of #983. (Edit: I merged a change to fix the atomics, which addresses part but not all of this issue. The remaining issues have to be elsewhere.) One way or the other, it's tied to LLVM version.

Files and scripts to reproduce this configuration can be found at: https://gitlab.com/StanfordLegion/legion/-/tree/regent-index-launch-sc21/language/sc21_scripts

**Comment by elliottslaughter** [comment]
New results with LLVM 13 and `atomicrmw`:

  * Circuit: 1.9726 => 2.3988 seconds (1.22&times; relative execution time)
  * Stencil: 1.7562 => 1.695 seconds (0.97&times; relative execution time)
  * Pennant: 2.354 => 2.3342 seconds (0.99&times; relative execution time)

So basically parity on Stencil and Pennant and still behind on Circuit (though with a very marginally smaller gap).

**Comment by elliottslaughter** [comment]
I'm attaching the generated PTX code here.

  * [circuit_llvm3.8.txt](https://github.com/StanfordLegion/legion/files/8401359/circuit_llvm3.8.txt)
  * [circuit_llvm13.txt](https://github.com/StanfordLegion/legion/files/8401361/circuit_llvm13.txt)

One thing that immediately stands out to me is that the NVPTX output is *dramatically* longer. Like 30k lines vs less than 1k. I wonder if the LLVM inliner is doing its job or not.

Another thing I notice is that LLVM 3.8 / NVVM generates the instruction:

```
atom.global.add.f32 	%f7, [%rd39], %f5;
```

While LLVM 13 / NVPTX generates:

```
atom.add.f32 	%f2, [%rd1], %f1;
```

I'm no expert, but it maybe looks like NVPTX isn't able to determine that the pointer lives in global memory? If we're doing an address check on every atomic, maybe that's what's slowing us down (beyond general code bloat).

**Comment by elliottslaughter** [comment]
Ok, I found a hack to force the LLVM 13 to use `atom.global.add.f32` by casting the address space of the pointer through https://llvm.org/docs/NVPTXUsage.html#llvm-nvvm-ptr-gen-to-intrinsics .

  * [circuit_llvm13_global.log](https://github.com/StanfordLegion/legion/files/8401409/circuit_llvm13_global.log)

I am seeing the right instructions generated, but performance does not change.

I also see that Terra's CUDA path is running optimizations, so don't currently see anything wrong there either.

https://github.com/terralang/terra/blob/master/src/tcuda.cpp#L209-L212

**Comment by elliottslaughter** [comment]
I'm tracking the inliner issue as https://github.com/terralang/terra/issues/527. I've got a short reproducer so hopefully it won't be hard to find. LLVM itself seems to be working; it has to be something in Terra's `cudalib` code path.

**Comment by pmccormick** [comment]
I see something potentially related in some of our code -- we specifically had to "tickle" each GPU-bound function to get inlining to cooperate (e.g., in LLVM: `DeviceFn->addFnAttr(Attribute::AlwaysInline);`).  Not sure how that aligns with terra's codegen path but it seemed to resolve the issue for us.

**Comment by elliottslaughter** [comment]
Turns out you need to add the inliner to pass manager, something we were doing in Terra's standard optimization path that got missed in the migration to NVPTX.

https://github.com/terralang/terra/pull/528

**Comment by elliottslaughter** [comment]
I verified that https://github.com/terralang/terra/pull/528 fixes the inlining in the PTX output, but the performance does not change. I suspect that the CUDA driver was doing the inlining on its side. Still, I took the PR because it's plausible that there might be cases where there'd be a difference in inlining between LLVM and PTX, so it's better to have predictable behavior by keeping it under our control.

But that means the performance hasn't changed, so the issue has to be somewhere else.

**Comment by elliottslaughter** [comment]
Ok, I played with a bit of a hack today and confirmed that the rounding modes are in fact responsible for the performance gap. I did three replacements via regex directly on the PTX:

```
ptx = string.gsub(ptx, "add[.]rn[.]", "add.")
ptx = string.gsub(ptx, "sub[.]rn[.]", "sub.")
ptx = string.gsub(ptx, "mul[.]rn[.]", "mul.")
```

So if we can figure out how to generate those instructions with LLVM properly, we can probably get the performance back.

Having said that, the situation with rounding modes in LLVM is a bit weird. Here are the [instructions on rounding modes in LLVM](https://llvm.org/docs/LangRef.html#floating-point-environment). If you need anything other than the default (round-to-nearest) mode, they tell you go use [these special intrinsics](https://llvm.org/docs/LangRef.html#constrainedfp). So you have to completely rip out your floating point code generation, which is a pain. But worse, you have to do so in its entirety, because LLVM says that that normal and constrained floating point operations cannot be mixed.

I wonder if @pmccormick has had any experience with this because doing it "properly" seems like a pain.

**Comment by elliottslaughter** [comment]
I have also confirmed that the global vs generic atomics make no difference to performance. For posterity, I'm attaching the diff (now commented out) I used to do this, so I don't need to recreate it later if I turn out to want it again.

```diff
diff --git a/language/src/regent/cudahelper.t b/language/src/regent/cudahelper.t
index 21c75f11c..5cb23018a 100644
--- a/language/src/regent/cudahelper.t
+++ b/language/src/regent/cudahelper.t
@@ -529,7 +542,13 @@ function cudahelper.generate_atomic_update(op, typ)
       end
     end
     if opname then
+      -- local global_as = 1
+      -- local global_int8 = terralib.types.pointer(int8, global_as)
+      -- local global_typ = terralib.types.pointer(typ, global_as)
+      -- local to_global = terralib.intrinsic("llvm.nvvm.ptr.gen.to.global.p1i8.p0i8", {&int8} -> {global_int8})
       local terra atomic_op(addr : &typ, value : typ)
+        -- var gaddr = [global_typ](to_global([&int8](addr)))
+        -- return terralib.atomicrmw(opname, gaddr, value, {ordering = "monotonic"})
         return terralib.atomicrmw(opname, addr, value, {ordering = "monotonic"})
       end
       atomic_op:setinlined(true)
```

**Comment by elliottslaughter** [comment]
I've been playing around with [fast math](https://llvm.org/docs/LangRef.html#fastmath) as an alternative to rounding modes, and am able to confirm that I'm able to get additional improvement (beyond what I get without rounding modes) using fast math on Circuit. I've checked that the output uses `.rn.` on math instructions, but seems to have a higher percentage of `fma` instructions, which seems to explain the performance difference.

New results:

  * Circuit: 1.7276 seconds (was 1.9726, 0.88&times; relative execution time)
  * Stencil: 1.763 seconds (was 1.7562, 1.00&times; relative execution time)
  * Pennant: 2.328 seconds (was 2.354, 0.99&times; relative execution time)

So I'm guessing rounding modes enable some subset of optimizations that are enabled by fast math---rather than it being a hardware deficiency that the round-to-nearest mode is slow.

**Comment by elliottslaughter** [comment]
I verified that I get no additional performance improvement by adding the `.rn.` find-and-replace hack back in on top of my fast math change.

I also found this:

https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#floating-point-instructions__summary-of-floating-point-instructions

> If no rounding modifier is specified, default is `.rn` and instructions may be folded into a multiply-add.

Which seems to suggest that what's going on is the unspecified `.rn` is acting as a fast-math flag of sorts in the PTX semantics. I.e., it's not that the rounding mode `.rn` is slow (it's the default so we're getting it in either case), but it's that NVVM was emitting instructions in this mode that permitted additional multiply-adds to be fused. It's not clear that *any* LLVM rounding mode would result in this behavior, so we're probably better of investigating the corresponding fast math flags in LLVM.

**Comment by elliottslaughter** [comment]
Results with the fast-math flag `contract` (but no other fast-math flags), and no `.rn.` find-and-replace hack:

  * Circuit: 1.954 seconds (vs 1.9726, 0.99&times; relative execution time)

So I think that confirms that the impact of the PTX no-`.rn` instructions is equivalent to `contract.

**Comment by elliottslaughter** [comment]
Updated results with the new `fast-math` branch of Terra and `regent-fast-math` branch of Legion. Results are expected to be the same as my last update, just confirming this is true in the version where the fast-math flags are not hard-coded into Terra.

  * Circuit: 1.9562 seconds (vs. 1.954 in my last update; 1.9726 for LLVM 3.8)

I'm going to consider this now resolved for the three apps I've been testing: Circuit, Stencil and Pennant.

I still want to make sure some of our larger apps are not seeing regressions, just to make sure there's nothing else out there to worry about. I'm currently planning to ask for S3D and HTR to be tested.

**Comment by elliottslaughter** [comment]
Here are my instructions for the other apps I'd like to have checked:

I'd like to do a comparison of three configurations. Ideally, I want as direct a comparison as possible: same Legion/Regent, same GASNet, same Terra, and same application versions in all cases. The only variables I'd like to change are LLVM and (in one case) the Regent flags below. Otherwise it will be difficult to be 100% sure what's causing performance differences (if we see any).

  * LLVM 3.8
  * LLVM 13
  * LLVM 13 with the Regent flag `-ffast-math 1`

Note that when building, you must use an up-to-date copy of Terra. Either https://github.com/terralang/terra/tree/master or https://github.com/StanfordLegion/terra/tree/luajit2.1 are ok to use, but the Terra must be updated. Note that I've had issues with dirty builds not picking up my changes, so I recommend a clean build.

For Legion, please use the branch https://gitlab.com/StanfordLegion/legion/-/tree/regent-fast-math-dcr . This is needed to pick up the support for all the optimizations we need to match LLVM 3.8's performance.

For the application configuration: we don't need many nodes for this test. One or a couple nodes would be fine. I'm mainly concerned about the speed of the generated kernels, not the scaling (which should be orthogonal). The problem size should ideally be large enough to pick up any performance differences in the generated code, but the exact problem size doesn't matter.

Please run all tests on GPUs. The performance regressions I observed above were all GPU-related. You can also run CPU tests if you want, but I don't expect to see any issues with those tests.

Let me know if you have any questions.

**Comment by elliottslaughter** [comment]
Results from S3D, thanks to @syamajala:

> 4.13 seconds/timestep for llvm38, 4.09 with llvm13, and 4.06 with llvm13 -ffast-math

So all faster, though nothing dramatic (1-2%).

**Comment by elliottslaughter** [comment]
Initial results from HTR, thanks to @cmelone:

> LLVM 13: 464.983s  
> LLVM 13 w/ ffast: 462.334s  
> LLVM 3.8: 656.303s

However, I understand that something is going wrong with another solver test in LLVM 13.

**Comment by elliottslaughter** [comment]
I got these updated HTR results from @cmelone:

> Llvm38: 349.754s  
> Llvm13: 340.385s  
> Llvm13 w/ ffast: 344.919s

I understand that there was unrelated Realm regression that we worked around by backporting everything to an older Legion commit. This should be unrelated to LLVM/Terra/Regent.

**Comment by elliottslaughter** [comment]
I believe everything has been resolved. Closing.
