### ISSUE TITLE
legion-prof-rs: Bring Rust implementation of profiler up-to-date with current Legion file format format

### ISSUE THREAD

**Issue by ndrewtl** [StanfordLegion/legion#1044]
@elliottslaughter has begin work on a Rust version of `legion_prof.py` on branch `legion-prof-rs` on Gitlab. This branch was last updated in June 2020, and since then, the profile file format has been updated. As part of an effort to bring the Rust profiler to feature-parity with the existing code, I will add compatibility with present-day profiler inputs to the profiler

**Comment by ndrewtl** [comment]
I'm not sure if it's possible to assign-to-self here, but I'll be the one working on this

**Comment by elliottslaughter** [comment]
We did this a while ago.
