### ISSUE TITLE
Build failure when CXX=mpicxx

### ISSUE THREAD

**Issue by PHHargrove** [StanfordLegion/legion#1048]
When attempting to build current `stable` (0cf9ddd6) for GASNet's ibv-conduit, I have set `CXX=mpicxx` based on past practice.  However, I find that for this case and others using MPI, `runtime/runtime.mk` executes `export OMPI_CXX := $(CXX)`.  The result is that Open MPI recursively calls itself and fails spectacularly.

Now that I am aware of it, I will avoid triggering this behavior, and so this not a "big problem" for me.
However, @streichler suggested to me that it might be possible for `runtime.mk` to detect and avoid this case, and requested that I report this issue.

**Comment by lightsighter** [comment]
Would everyone be satisfied with simply detecting the case where we do a string compare against the value of `CXX` looking for `mpicxx` or do we want the solution to look through symbolic links and other such shenanigans to detect other names for MPI wrapped compilers?

**Comment by streichler** [comment]
given that the code in question is specific to openmpi, you should be able to detect an ompi wrapper by executing
```
$CXX -showme:compile
```
and checking the return code: 0 means it's an openmpi wrapper and non-zero means the argument wasn't recognized and it's probably not a wrapper.

**Comment by PHHargrove** [comment]
A string compare approach would need to deal with the fact that the compiler wrapper is installed under three names: `mpicxx`, `mpic++` and `mpiCC` (the last only on case-sensitive systems - not macOS).  So, I like Sean's suggestion to use `-showme:compile`.

**Comment by lightsighter** [comment]
Please test out this commit and see if it makes things better:
https://gitlab.com/StanfordLegion/legion/-/commit/a0b3e732065d4b7ffa420e9dc9f1722f5381bd07

**Comment by PHHargrove** [comment]
@lightsighter Our machine room is without power through Monday for site-wide utility work.  
I will try on Friday to find a system where I can test, but the original system is not available at the moment.  

The logic certainly _looks_ right to me for the case or Open MPI (which is what I am normally using).  
However, I've just now confirmed that, MPICH (and derivatives) use `-show`:
>        -show  - Use this option to learn how the underlying compiler is invoked, without actually running it.
So, you'll need 6 conditionals, not just the 3 you have now.

**Comment by elliottslaughter** [comment]
Could you also confirm the negative, that non-MPI compilers reject these flags? I'm pretty sure I've seen some compilers treat unknown flags as a warning before.

**Comment by PHHargrove** [comment]
@elliottslaughter I can confirm that g++ and clang++ on systems I use reject `-showme:compile` and `-show` as errors (not warnings).

```
$ g++-10 -showme:compile hello.cc >& /dev/null || echo CHOKED
CHOKED
$ g++-10 -show hello.cc >& /dev/null || echo CHOKED
CHOKED
$ clang++ -showme:compile hello.cc >& /dev/null || echo CHOKED
CHOKED
$ clang++ -show hello.cc >& /dev/null || echo CHOKED
CHOKED
```

The exception seems to be Intel's compiler:
```
$ icpc -showme:compile hello.cc && echo UNDESIRED PASS
icpc: command line warning #10006: ignoring unknown option '-showme:compile'
UNDESIRED PASS
$ icpc -show hello.cc && echo UNDESIRED PASS
icpc: command line warning #10006: ignoring unknown option '-show'
UNDESIRED PASS
```
A "trick" for that (something we use in configure probes) would be `__INTEL_POST_CFLAGS+=' -we10006'` to convert that warning to an error without requiring that `$(CXX)` be Intel's:
```
$ __INTEL_POST_CFLAGS+=' -we10006' icpc -showme:compile hello.cc >& /dev/null || echo CHOKED
CHOKED
$ __INTEL_POST_CFLAGS+=' -we10006' icpc -show hello.cc >& /dev/null || echo CHOKED
CHOKED
```

**Comment by lightsighter** [comment]
@PHHargrove Does Intel's compiler accept the `-Werror` flag and if it does will that convert the warning into an error?

**Comment by PHHargrove** [comment]
@lightsighter asks:
> Does Intel's compiler accept the -Werror flag and if it does will that convert the warning into an error?

Yes and no, respectively ☹️ :
```
$ icpc -Werror -show hello.cc && echo UNDESIRED PASS
icpc: command line warning #10006: ignoring unknown option '-show'
UNDESIRED PASS
```

**Comment by PHHargrove** [comment]
I can confirm that [a0b3e7320](https://gitlab.com/StanfordLegion/legion/-/commit/a0b3e732065d4b7ffa420e9dc9f1722f5381bd07) has resolved the problem on an Open MPI test system (where I *did* first reproduce the faulty behavior).

I have also identified an MPICH-based system where I can probably test when the logic is updated appropriately.

**Comment by lightsighter** [comment]
See if this works:

https://gitlab.com/StanfordLegion/legion/-/commit/30206c9d66636090051e38aaad806b9ead050443

**Comment by PHHargrove** [comment]
LGTM 👍 

With [a0b3e7320](https://gitlab.com/StanfordLegion/legion/-/commit/a0b3e732065d4b7ffa420e9dc9f1722f5381bd07) and    [30206c966](https://gitlab.com/StanfordLegion/legion/-/commit/30206c9d66636090051e38aaad806b9ead050443) both applied, I see success building the circuit example with REALM_NETWORKS=gasnetex and and InfiniBand on Open MPI + GNU and MPICH + Intel, having myself set CC=mpicc and CXX=mpicxx.

**Comment by lightsighter** [comment]
Closing the issue. We can reopen it if it comes up again in a different setting.
