### ISSUE TITLE
Tracing: Assertion `single_task_termination.exists()' failed

### ISSUE THREAD

**Issue by manopapad** [StanfordLegion/legion#1049]
[bug1049.tar.gz](https://github.com/StanfordLegion/legion/files/6275359/bug1049.tar.gz) compiled with latest control replication triggers the following assertion on 2 sapling nodes:

```
app.exec: /home/manolis/legion/runtime/legion/legion_tasks.cc:3400: virtual Legion::Internal::ApEvent Legion::Internal::SingleTask::get_memo_completion() const: Assertion `single_task_termination.exists()' failed.
```

**Comment by lightsighter** [comment]
Already know what this one is. @elliottslaughter reported it earlier this week. Will try to fix it by next week after GTC.

**Comment by lightsighter** [comment]
When I try to reproduce this bug, I see the following which @elliottslaughter seems to think is a Regent bug, so assigning to him for now:

```
mebauer@c0003:~/legion/language/bug1049$ mpirun -n 2 -H c0003,c0004 --bind-to none -x REALM_FREEZE_ON_ERROR -x LD_LIBRARY_PATH ./app.exec 
WARNING: 2 of 2 processes have HCAs believed to support ODP.  However, the
         corresponding software support was not found at configure time.
         Please see the README for GASNet's ibv-conduit for more info on ODP.
         To suppress this message set environment variable
         GASNET_ODP_VERBOSE=0 or reconfigure with --disable-ibv-odp
         (see ibv-conduit's README for more information).
[0 - 7f1090e59800]    0.229152 {4}{runtime}: Ignoring empty index task launch in task main (ID 6)
[0 - 7f1090e59800]    0.230042 {4}{runtime}: Ignoring empty index task launch in task main (ID 6)
[0 - 7f1090e59800]    0.230811 {4}{runtime}: Ignoring empty index task launch in task main (ID 6)
[0 - 7f1090e59800]    0.231471 {4}{runtime}: Ignoring empty index task launch in task main (ID 6)
[1 - 7f7ce2388800]    0.233607 {4}{runtime}: Ignoring empty index task launch in task main (ID 1)
[1 - 7f7ce2388800]    0.234601 {4}{runtime}: Ignoring empty index task launch in task main (ID 1)
[1 - 7f7ce2388800]    0.235228 {4}{runtime}: Ignoring empty index task launch in task main (ID 1)
[1 - 7f7ce2388800]    0.235831 {4}{runtime}: Ignoring empty index task launch in task main (ID 1)
assertion failed: missing future in task param
```

**Comment by elliottslaughter** [comment]
This seems to be suffering from the same issue as https://github.com/StanfordLegion/legion/issues/1039. I'll fix that first and then see if we can get back to the original problem in this issue.

**Comment by lightsighter** [comment]
The fixes applied for #1039 now make it so that this problem runs, but it also doesn't reproduce the issue anymore. I believe the issue is still there, but we need a new reproducer.

**Comment by lightsighter** [comment]
Actually, I think the change that fixes things and prevents the reproducer from happening are the improvements to the default mapper to shard things better. I could be wrong about that.

**Comment by elliottslaughter** [comment]
If you temporarily comment out:

https://gitlab.com/StanfordLegion/legion/-/blob/fdc018b7cb93769308baa60cad08f91d0e25e1c7/language/src/regent/codegen.t#L3660-3664

and

https://gitlab.com/StanfordLegion/legion/-/blob/fdc018b7cb93769308baa60cad08f91d0e25e1c7/language/src/regent/codegen.t#L3674-3678

Does it come back? I think your "default mapper" improvements might actually be in Regent's ability to properly tag individual task launches.

In particular with those commented out, all single task launches will (I believe) get sharded to node 0, and the default mapper might then try to farm them back out.

**Comment by lightsighter** [comment]
Nope, it's something else.

**Comment by elliottslaughter** [comment]
I'm not sure what to tell you. The last change to anything in `runtime/mappers` was in February. I don't see anything in Regent (aside from the single task point change) that would be relevant either. What else is relevant and has changed recently?

**Comment by lightsighter** [comment]
> The last change to anything in runtime/mappers was in February.

That's definitely not true in the control replication branch.

I can tell you exactly what causes this issue. We need an individual task launch inside of a trace capture that is remote mapped on a different node than the one it was originally sharded to. I'm fine if we can't reproduce it because I know what needs to be fixed, but you and Manolis want confirmation that it is fixed then we need a reproducer.

**Comment by elliottslaughter** [comment]
```
$ git log
commit 31cd8817a730e62fdcfd7d84af31aae43eb252ac (HEAD -> control_replication, origin/control_replication)
Merge: 866468b89 513d9edf9
Author: Mike Bauer <mike@lightsighter.org>
Date:   Tue Apr 13 16:35:31 2021 -0700

    legion: merge master into control replication and resolve conflicts

$ git log -- runtime/mappers
commit 5b38aa6e50471d5ed5dcaa784e9c235839e92bc3
Merge: cfabce18b 1fba7da55
Author: Mike Bauer <mike@lightsighter.org>
Date:   Fri Feb 12 17:38:56 2021 -0800

    Merge branch 'control_replication' into futureinst
```

**Comment by elliottslaughter** [comment]
I can give you the `bad_alloc` reproducer if you think that's relevant here.

**Comment by lightsighter** [comment]
If you can still reproduce the `std::bad_alloc` then I guarantee you that if you turn on assertions you will see the same assertion that was originally reported in this issue.

**Comment by elliottslaughter** [comment]
Ok, here's a binary and command that reproduces:

```
/scratch2/eslaught/regent-index-launch-sc21/language/stencil.run2_bug1049
```
```
$ mpirun -n 2 -npernode 1 -bind-to none -x LD_LIBRARY_PATH=$PWD ./stencil.noidx -nx $(( 1 * 1000 )) -ny $(( 2 * 1000 )) -ntx $(( 1 )) -nty $(( 2 )) -tsteps 50 -tprune 30 -hl:sched 1024 -ll:gpu 1 -ll:util 1 -ll:bgwork 2 -ll:csize 15000 -ll:fsize 15000  -ll:rsize 512 -ll:gsize 0 -dm:replicate 0 -dm:memoize
stencil.noidx: /scratch2/eslaught/regent-index-launch-sc21/runtime/legion/legion_tasks.cc:3406: virtual Legion::Internal::ApEvent Legion::Internal::SingleTask::get_memo_completion() const: Assertion `single_task_termination.exists()' failed. 
```

Note that if you want to replicate on a vanilla `control_replication`, I just pushed a commit that makes `-dm:replicate` an int rather than a bool flag. (Previously it was not possible to shut this flag off.)

**Comment by lightsighter** [comment]
Assigning back to @elliottslaughter and @manopapad as I believe that this is fixed.

**Comment by elliottslaughter** [comment]
Confirmed that, at least as far as the stencil/circuit reproducers are concerned, this has been fixed.

Leaving to @manopapad to decide whether we want to bother with the original reproducer or not.

**Comment by manopapad** [comment]
I'm happy to close the issue given that real regent programs are working.
