### ISSUE TITLE
Transform parameter in multiple partitions example.

### ISSUE THREAD

**Issue by MiZhangWhuer** [StanfordLegion/legion#1051]
Thanks for providing the nice tutorials. In the multiple partitions example, there is a structure Transform that is employed for create_partition_by_restriction function. 

  Transform<1,1> transform;
  transform[0][0] = block_size;
  Rect<1> extent(-2, block_size + 1);
  IndexPartition ghost_ip = 
    runtime->create_partition_by_restriction(ctx, is, color_is, transform, extent);

What's the meaning for transform and extent parameters?
Does is mean that the transform parameter represents the affine mapping from index space (is) to the partition space (color_is)?
The extend denotes the upper bounds of index space?

**Comment by lightsighter** [comment]
In order to determine the bounds of the subregions for each subspace in the partition being created, the runtime takes each point in the color space, applies the `transform` to the value of the point (standard matrix multiply), takes the new point coming out of the transform and adds it to both the `lo` and `hi` values of the `extent`, and that new rectangle defines the bounds of the subspace for that color in the created partition. The dimensionality of `extent` and the `M` dimension of the `transform` must be the same as the dimensionality of the `parent` index space being partitioned. The value `N` of the transform must be the same as the dimensionality of the color space. This way the transform takes in N-dimensional points from the color space and transforms them into M-dimensional points which can be added to the M-dimensional bounds in the `extent` to create the bounds in the `parent` index space.

**Comment by MiZhangWhuer** [comment]
> In order to determine the bounds of the subregions for each subspace in the partition being created, the runtime takes each point in the color space, applies the `transform` to the value of the point (standard matrix multiply), takes the new point coming out of the transform and adds it to both the `lo` and `hi` values of the `extent`, and that new rectangle defines the bounds of the subspace for that color in the created partition. The dimensionality of `extent` and the `M` dimension of the `transform` must be the same as the dimensionality of the `parent` index space being partitioned. The value `N` of the transform must be the same as the dimensionality of the color space. This way the transform takes in N-dimensional points from the color space and transforms them into M-dimensional points which can be added to the M-dimensional bounds in the `extent` to create the bounds in the `parent` index space.

Thanks for your replay. By the way, how to join your research group and making the contribution to the project? I knew that there is project call FlexFlow based the Legion. I've tried that and applied the parallel processing to tensor in general case. I plan to release the entire project by the end of this year and hope to find the way to keep track of the latest branch.

**Comment by lightsighter** [comment]
> By the way, how to join your research group and making the contribution to the project?

We're definitely open to people helping out with the project! The best way to start is looking through the issues list. You'll see that we've tagged some issues as "good first issue" or "help wanted":

https://github.com/StanfordLegion/legion/labels/good%20first%20issue
https://github.com/StanfordLegion/legion/labels/help%20wanted

See if there is anything that peaks your interest. If it does comment on the issue and the owner will definitely help guide you on a path to getting some code working to help address the issue and help answer questions when you have them when working on the issue. If there are any other issues that look interesting but don't have those tags we'll be glad to help you out with those as well, although they might be more challenging to address and require you to learn more of the system.

> I knew that there is project call FlexFlow based the Legion. I've tried that and applied the parallel processing to tensor in general case.

I think we'd be very interested in learning more about that. It sounds like you're building a tensor library on top of Legion which I'm sure many people in the group would be interested in. If you've got some early performance results that you would like to share or would like feedback on we can arrange for you to present at the Legion group meeting.

**Comment by MiZhangWhuer** [comment]
> > By the way, how to join your research group and making the contribution to the project?
> 
> We're definitely open to people helping out with the project! The best way to start is looking through the issues list. You'll see that we've tagged some issues as "good first issue" or "help wanted":
> 
> https://github.com/StanfordLegion/legion/labels/good%20first%20issue
> https://github.com/StanfordLegion/legion/labels/help%20wanted
> 
> See if there is anything that peaks your interest. If it does comment on the issue and the owner will definitely help guide you on a path to getting some code working to help address the issue and help answer questions when you have them when working on the issue. If there are any other issues that look interesting but don't have those tags we'll be glad to help you out with those as well, although they might be more challenging to address and require you to learn more of the system.
> 
> > I knew that there is project call FlexFlow based the Legion. I've tried that and applied the parallel processing to tensor in general case.
> 
> I think we'd be very interested in learning more about that. It sounds like you're building a tensor library on top of Legion which I'm sure many people in the group would be interested in. If you've got some early performance results that you would like to share or would like feedback on we can arrange for you to present at the Legion group meeting.

Thanks for your replay! It dramatically improve the performance of tensor distribution across multi-gpus. The throughput is approximately 4x time speed up compared with the original implementation. I'll finish the entire project by the end of this summer and will keep in contact with you as soon as the Python interface is ready. Again, thanks for sharing this great project and I think the project could benefit the community who are also interested in FPGA implementation. Is there any plan for the FPGA backend?

**Comment by alexaiken** [comment]
There is ongoing work on FPGA support in the Realm layer (the lowest level of Legion).  We don't know yet when that will be released, though.

Alex

________________________________

**Comment by lightsighter** [comment]
> Thanks for your replay! It dramatically improve the performance of tensor distribution across multi-gpus. The throughput is approximately 4x time speed up compared with the original implementation. I'll finish the entire project by the end of this summer and will keep in contact with you as soon as the Python interface is ready

You might also want to checkout Legate NumPy that was just released on top of Legion earlier this week:
https://github.com/nv-legate/legate.numpy
It provides a drop-in replacement for NumPy but also runs large distributed multi-dimensional array computations on top of Legion. You might find it helpful/inspirational in your tensor work.

> Is there any plan for the FPGA backend?
I agree with @alexaiken. It is still under development in a branch, although it is unclear when it will be merged into the master branch of the repository.

**Comment by MiZhangWhuer** [comment]
> > Thanks for your replay! It dramatically improve the performance of tensor distribution across multi-gpus. The throughput is approximately 4x time speed up compared with the original implementation. I'll finish the entire project by the end of this summer and will keep in contact with you as soon as the Python interface is ready
> 
> You might also want to checkout Legate NumPy that was just released on top of Legion earlier this week:
> https://github.com/nv-legate/legate.numpy
> It provides a drop-in replacement for NumPy but also runs large distributed multi-dimensional array computations on top of Legion. You might find it helpful/inspirational in your tensor work.
> 
> > Is there any plan for the FPGA backend?
> 
> I agree with @alexaiken. It is still under development in a branch, although it is unclear when it will be merged into the master branch of the repository.

Is there any preview link for the FPGA based branch?

**Comment by alexaiken** [comment]
We're not sharing the FPGA code yet.  We're really at the beginning of that work, but I wanted to let you know that it will happen.

Alex

________________________________

**Comment by elliottslaughter** [comment]
@MiZhangWhuer was your question answered? If so we can go ahead and close this issue. (If you have any further questions or issues, of course feel free to open a new issue.)

**Comment by MiZhangWhuer** [comment]
> @MiZhangWhuer was your question answered? If so we can go ahead and close this issue. (If you have any further questions or issues, of course feel free to open a new issue.)

Hi, thanks for your reply. My issue has been solved here. Close this issue!
