### ISSUE TITLE
Capture version information 

### ISSUE THREAD

**Issue by pmccormick** [StanfordLegion/legion#1056]
It would be nice to have a mechanism to "bake" a version number into a build of the runtime -- accessible via code or command line.  I've found a couple of cases where such info would be helpful vs. trying to backtrack to a tarball, git checkout, install path, spack (me) doing the wrong thing, etc.   

It would be extra nice to hook it into tarballs, git checkouts (+branches), and related details.  

An extra plus would be a way to capture build configuration settings so we can double check details for bug reports, validate details of reproducers, etc.   Perhaps even dumping the version info at the head of logs might prove to be helpful.

**Comment by lightsighter** [comment]
> It would be nice to have a mechanism to "bake" a version number into a build of the runtime 

This would probably be pretty easy to do assuming the "version number" is something like 21.03, 21.06, etc.

> It would be extra nice to hook it into tarballs, git checkouts (+branches), and related details.

Alternatively, we could have the build systems put the git hash into `legion_config.h` and `realm_config.h` so we can report that back. Any objections @elliottslaughter @streichler ?

> An extra plus would be a way to capture build configuration settings so we can double check details for bug reports, validate details of reproducers

Going to assign you @pmccormick to specify exactly what you want to be included for this.

**Comment by elliottslaughter** [comment]
I think `LEGION_VERSION_MAJOR` / `MINOR` / `PATCH` would be the standard way to do it, so that you can represent a three-part version number `X.Y.Z`.

The config headers seem like the best option, so that you can do build-time customization. (Not that I expect to actually use this capability.)

**Comment by lightsighter** [comment]
I think I'm against creating an alternative version scheme than the one we already have, which would mean:

`MAJOR` = year
`MINOR` = month
`PATCH` = git commit hash

**Comment by streichler** [comment]
I asm scoping out an approach based around the use of `git describe` to automatically name things relative to the last `legion-...` tag.  I was consciously avoiding any kind of major/minor/patch approach that would suggest we follow anything resembling semantic versioning.

@pmccormick can you confirm that your needs would be satisfied by a version _string_ (i.e. not a number) that can only be:
a) usefully read by a human (e.g. "oh, that's legion-21.03.0") or
b) string-compared to check if an application was built against headers that match the legion/realm it's linked to

**Comment by pmccormick** [comment]
Yep, as long as the details are traceable back to some state of the code at GitHub it should be just fine in either form. 

The ECP path looks to be headed in a direction where legion installs are to (supposedly?) be provided as part of the overall software stack at the facilities (this appears to be planned via Spack).  So, being able to cross-check details could be very helpful (in theory spack can help here but it would still be good to have our own sanity check).  

@lightsighter: based on the above, we might be able to leverage Spack to capture all the build parameters of a certain install so we know of any nuances that might introduce into runtime behaviors.  I'll explore it a bit more to see what's captured and if it is generally available to end users.

**Comment by streichler** [comment]
Version information is now compiled into Realm and Legion.  This takes the form of a string (e.g. "legion-21.06.0") rather than anything that can be compared (i.e. no semantic versioning here).  Compile-time defines `REALM_VERSION` and `LEGION_VERSION` are available as well as run-time calls `Realm::Runtime::get_library_version` and `Legion::Runtime::get_library_version`.
