### ISSUE TITLE
Remove Python 2 in CI?

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1060]
I discovered recently that Python 2 support has bitrotted to the point where I can no longer build a fresh set of Docker images for our CI from scratch. The issues seem to be pervasive: I can't upgrade setuptools, because it has become Python 3 only, and I can't upgrade pip (to see if it's smart enough to know what versions are compatible), because newer pip versions are Python 3 only.

Is it time to remove our Python 2 support, at least in CI? It seem to be causing more trouble than it's worth.

**Comment by lightsighter** [comment]
Python 2 is dead. It's time to let it go. We've moved on in Legate.

**Comment by elliottslaughter** [comment]
I've kicked this down the road for now by pinning all the versions of the packages we need so that they're compatible. But I still think at some point we should remove Python 2 entirely.

**Comment by elliottslaughter** [comment]
We no longer test Python 2 in CI. I suppose that we can start to remove the remaining Python 2 support as we have the time / interest.
