### ISSUE TITLE
Runtime build failure with CXX='g++ -std=c++2a' (std::allocator<void>::const_pointer no longer a type in C++20)

### ISSUE THREAD

**Issue by PHHargrove** [StanfordLegion/legion#1067]
I am using Legion stable at 0cf9ddd on Linux/x86_64
In addition to appropriate paths for LG_RT_DIR and GASNET_ROOT, I am using
REALM_NETWORKS=gasnetex CONDUIT=ibv
CXX='g++ -Wno-unused -std=c++2a'

With multiple GCC releases (10.1.0, 10.2.0, 10.3.0 and 11.1.0), I see the following failure when attempting to compile the circuit example:
```
In file included from /dev/shm/legion/runtime/legion/legion_utilities.h:26,
                 from /dev/shm/legion/runtime/legion/legion_spy.h:22,
                 from /dev/shm/legion/runtime/legion/runtime.h:21,
                 from /dev/shm/legion/runtime/legion/legion.cc:17:
/dev/shm/legion/runtime/legion/legion_allocation.h:432:62: error: �const_pointer� in �class std::allocator<void>� does not name a type
  432 |                               typename std::allocator<void>::const_pointer = 0)
      |                                                              ^~~~~~~~~~~~~
```

This is not present with GCC 9.3.0.  
Replacing `-std=c++2a` in my definition of `CXX` with `-std=c++17` also eliminates the problem.

A quick search found that `const_pointer` as a member type of `std::allocator` was [deprecated in C++17 and removed in C++20](https://en.cppreference.com/w/cpp/memory/allocator)

**Comment by lightsighter** [comment]
Fix is in the same branch that @streichler is using for fixes for #1066

**Comment by pmccormick** [comment]
> Fix is in the same branch that @streichler is using for fixes for #1066

Quick request for this fix to land in the control replication branch for flecsi use of clang 11 & 12 (i.e., available on both gitlab and github).

**Comment by lightsighter** [comment]
@streichler any updates on merging the cxx2a branch?

**Comment by streichler** [comment]
It is merged, but we have an error in CI testing (the one with icc) that's preventing it from being mirrored to github.

**Comment by elliottslaughter** [comment]
CI now runs C++ 20 on every commit. I think this is fixed?
