### ISSUE TITLE
Process ID in Legion logs

### ISSUE THREAD

**Issue by bandokihiro** [StanfordLegion/legion#1068]
It would be useful to be able to have the actuall process IDs for the files generated by `-logfile log_%.log` instead of the rank ID, for instance to identify a process that is doing something wrong when this can be inferred from the logs.

**Comment by bandokihiro** [comment]
Similarly, logging the hostname and the process ID in the logs at start-up would be useful for instance when running multiple ranks per node.

**Comment by elliottslaughter** [comment]
This is in the upcoming release.
