### ISSUE TITLE
Querying fields in a field space

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#107]
I would really like an API to allow me to query the fields in a field space. This would be useful, for example, inside the mapper, where assigning to `additional_fields` requires knowing the set of fields that are available. Currently, this has to be done with application-specific knowledge, which becomes error prone when adding or removing fields.

I realize this API will have consistency issues when allocating fields on multiple nodes. That is fine. The only fields I care about here are ones which were known at the time the operation itself was launched.

**Comment by lightsighter** [comment]
I'm not exactly sure what you want this API to look like.  Can you propose some functions?

**Comment by elliottslaughter** [comment]
For the purposes of the mapper, it's enough just to know the field IDs, so perhaps:

    std::set<FieldID> get_field_space_fields(Context ctx, FieldSpace handle);

or if you prefer the `MachineInterface` style of doing things:

    void get_field_space_fields(Context ctx, FieldSpace handle, std::set<FieldID> &fields);

Alternatively, you could create an iterator-style interface for them (to make it similar to index space iteration), but I'm not sure that has any real advantages over just returning a set of IDs.

**Comment by lightsighter** [comment]
Ok I will try to add this sometime this week.  It is a little weird because it will just be a sampling of the fields in the field space at that point in time and will be subject to change.

**Comment by elliottslaughter** [comment]
Still, if it's called inside the mapper, won't it be valid at least until the end of the mapper call?

**Comment by lightsighter** [comment]
No it won't.  Mapper calls are atomic with respect to each other (on the same mapper), but there is nothing that prevents tasks from running concurrently and mutating that allocated fields in the field space.

I pushed a change so you have this call available from both the runtime and mapper interfaces.  If everything looks good you can go ahead and close the issue.

**Comment by lightsighter** [comment]
Closing this issue since this is implemented and tested in the master branch.
