### ISSUE TITLE
Allocation failure on PizDaint

### ISSUE THREAD

**Issue by bandokihiro** [StanfordLegion/legion#1072]
A dummy legion program fails on Piz Daint when csize is set to 6000 but works at 5000. The node has ~64GB and setting rsize to high values doesn't lead to failure.
```
MemTotal:       65842332 kB

srun --cpu-bind=none /users/kbando/DG-Legion/build/tools/dummy_legion_program -logfile log_%.log -hdf5:forcerw -dm:memoize -ll:cpu 0 -ll:util 2 -ll:bgwork 2 -ll:csize 6000 -ll:rsize 0 -ll:onuma 0 -ll:ocpu 1 -ll:othr 1 -ll:show_rsrv

[0 - 2aaaaab1c3c0]    0.000000 {6}{malloc}: insufficient system memory: 6291456000 bytes needed (from -ll:csize)
srun: error: nid02356: task 0: Aborted (core dumped)
```
Someone had similar issues on another cluster with aries conduit (failure at csize much smaller than available memory). I don't know if it is related.

**Comment by elliottslaughter** [comment]
I had to start setting `GASNET_PHYSMEM_MAX` on my runs on Piz Daint (e.g., `export GASNET_PHYSMEM_MAX=16G`) to avoid this issue.

It may be a GASNet regression because I upgraded to version 2021.3.0 for the runs I was doing. I don't remember having this with older GASNet versions.

**Comment by bandokihiro** [comment]
Great, thanks! I also had it with 2020.11.0 but didn't officially report it when I first saw this.
