### ISSUE TITLE
Regent: Support function-call calling convention for Regent tasks

### ISSUE THREAD

**Issue by syamajala** [StanfordLegion/legion#1073]
It would be nice to be able to call Regent tasks as functions.

This would be useful for fusing tasks over fields in S3D for example.

**Comment by elliottslaughter** [comment]
This is now in master as of cc0e17479e443aa31372b7b436608ef74a9b1fd8. You can see some example codes here:

  * https://gitlab.com/StanfordLegion/legion/-/blob/master/language/tests/regent/run_pass/local_task.rg
  * https://gitlab.com/StanfordLegion/legion/-/blob/master/language/tests/regent/run_pass/local_task_projection.rg

It should work with both leaf and inner tasks. If you use `__demand(__cuda)`, it should also be smart enough to call the appropriate variant (CUDA from CUDA, CPU from CPU, OpenMP from OpenMP).

**Comment by elliottslaughter** [comment]
This should be fully working at this point. There were a couple glitches around mapper IDs/tags, but I think those have been sorted out now (post-21.06 release).
