### ISSUE TITLE
Regent: Don't jit cuda task ptx.

### ISSUE THREAD

**Issue by syamajala** [StanfordLegion/legion#1077]
Part of this may need to be fixed in terra, but we need a way to precompile ptx for cuda tasks to avoid long repetitive startup times.

**Comment by lightsighter** [comment]
And you profiled to make sure it was the Regent tasks that were adding all the extra time and not the Singe kernels?

**Comment by syamajala** [comment]
Yes I timed cuModuleLoadDataEx in Realm and it was taking a significant amount of time for the module containing the regent tasks and minimal time for the rest of the modules.
