### ISSUE TITLE
mappers: confusing interaction between `DefaultMapper::map_task` and `DefaultMapper::default_policy_select_target_processors`

### ISSUE THREAD

**Issue by rohany** [StanfordLegion/legion#1080]
The intention of `default_policy_select_target_processors` is so that users can easily override this function to pick a specific processor for a task. However, this can lead to potential performance problems or invalid mapping output. The problem is how `map_task` selects target memories for regions:
https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/mappers/default_mapper.cc#L1579

It uses `task.target_proc`, which can be different from the processors chosen in `default_policy_select_target_processor`. In my case, this led to a difficult to debug performance problem, where GPUs connected via nvlink were reading framebuffer memory from other GPUs. In a situation without nvlink, this could lead to invalid mapping output.

**Comment by manopapad** [comment]
Should be fixed with 4d3d7659

**Comment by rohany** [comment]
That commit does exactly the fix I used to get around this behavior.
