### ISSUE TITLE
Realm: Option to disable GPU registration of allocated system memory

### ISSUE THREAD

**Issue by manopapad** [StanfordLegion/legion#1081]
Realm by default tries to register the allocated system memory (`-ll:csize`, `-ll:nsize` etc.) with the GPU. The underlying CUDA operation (`cuMemHostRegister`) can take multiple minutes for large allocations (in the 100s of GB), so it would be nice to have a way to disable this.

**Comment by streichler** [comment]
@manopapad I'm thinking of adding a configuration option that would bound the maximum amount of memory that realm tries to register with CUDA, favoring dma's intermediate buffer memories over application memories.  Does that seem reasonable to you?

**Comment by manopapad** [comment]
That works for me.

**Comment by lightsighter** [comment]
To be fair, this is only slow because the underlying systems don't support huge pages for large memory allocations. With huge pages, the registration process is fast as expected. We should still have option to limit it, but in general running on systems with huge pages is the better answer.

**Comment by streichler** [comment]
Added with commit 84b19b8b.  Default threshold is 1GB, which is approximately instant on systems we've looked at, but it can be controlled with the `-cuda:hostreg` command-line option.
