### ISSUE TITLE
Fortran bindings fail stricter standard checks under GCC 10.x 

### ISSUE THREAD

**Issue by pmccormick** [StanfordLegion/legion#1093]
It looks like gfortran 10.X now adheres more closely to the Fortran 2018 specification -- this causes build errors for the Fortran bindings (see below).  A quick fix is to downgrade these errors to warnings with the command line flag `-fallow-invalid-boz`.  Obviously, in the longer term, it will be better to update the code to be compliant with the standard.

```
/tmp/pat/spack-stage/spack-stage-legion-21.03.0-6gqir4uf74wqhewca5m3uo2chlr3at6b/spack-src/runtime/legion/leg
            ion_f_types.f90:34:42:
     317    
     318       34 |   integer(c_int), parameter :: NO_ACCESS = Z'00000000'
     319          |                                          1
  >> 320    Error: BOZ literal constant at (1) is neither a data-stmt-constant nor an actual argument to INT, REAL, DBLE,
             or CMPLX intrinsic function [see '-fno-allow-invalid-boz']
     321    /tmp/pat/spack-stage/spack-stage-legion-21.03.0-6gqir4uf74wqhewca5m3uo2chlr3at6b/spack-src/runtime/legion/leg
            ion_f_types.f90:35:42:
     322    
     323       35 |   integer(c_int), parameter :: READ_PRIV = Z'00000001'
     324          |                                          1
  >> 325    Error: BOZ literal constant at (1) is neither a data-stmt-constant nor an actual argument to INT, REAL, DBLE,
             or CMPLX intrinsic function [see '-fno-allow-invalid-boz']
     326    /tmp/pat/spack-stage/spack-stage-legion-21.03.0-6gqir4uf74wqhewca5m3uo2chlr3at6b/spack-src/runtime/legion/leg
            ion_f_types.f90:36:42:
     327    
     328       36 |   integer(c_int), parameter :: READ_ONLY = Z'00000001'
     329          |                                          1
```

**Comment by eddy16112** [comment]
I pushed a fix for it. Please give a try, and I will merge it to the master once the CI is happy with it. 
https://gitlab.com/StanfordLegion/legion/-/commit/163794c35452515ffa1cf182baaa115b160e2452

**Comment by pmccormick** [comment]
> I pushed a fix for it. Please give a try, and I will merge it to the master once the CI is happy with it.
> https://gitlab.com/StanfordLegion/legion/-/commit/163794c35452515ffa1cf182baaa115b160e2452

Thanks @eddy16112.  All seems to be happy with this update.  

@streichler, can this fix land upstream over on GitHub (stable and CR branches) soon given that's where the spack package is pulling from?  (obviously assuming that CI will be happy)

**Comment by lightsighter** [comment]
These fixes are in the `master` and `control_replication` branches now. Probably will not make it to `stable` until the next release.

**Comment by streichler** [comment]
@pmccormick in addition to `master` and `control_replication`, these fixes should now be in the `stable` branch and the new `legion-21.06.0` tagged commit.
