### ISSUE TITLE
Legion: Application-driven inline task launches

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1101]
Currently a mapper can request that a task is executed inline. However, there may be situations where an application might want to request inline task launch (and therefore not leaving it up to a mapper decision). For example, if you wanted to execute an inline task launch inside of a leaf task, one would not want to leave it up to the mapper as to whether or not to execute the task inline.

This would presumably require modifying either the task registration or launcher to request inline execution. I don't think I have a preference, but it probably makes more sense in the launcher.

**Comment by elliottslaughter** [comment]
I should add: this is one possible way to implement https://github.com/StanfordLegion/legion/issues/1073.

**Comment by lightsighter** [comment]
How is this difference than "local function" tasks?

https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/legion.h#L1497-1505

**Comment by elliottslaughter** [comment]
The main difference is that I need to be able to include region requirements. However, my expectation is that all of the regions will already be mapped, and so the region requirements are "trivial" in the sense that they will always be a strict subset of the parent's existing region requirements and any existing instances of those regions are assumed to be sufficient.

**Comment by lightsighter** [comment]
What is the value add for the runtime being able to do this? It seems like if you're writing in C++ you should just be able to manually inline it. In the case of a compiler like Regent, it will be much more efficient for the compiler to inline it. You're just asking for runtime overhead by asking the runtime to inline a task without getting anything back in return. I'm just not seeing the value-add.

**Comment by elliottslaughter** [comment]
Regent's current task calling convention relies on certain runtime data structures that I cannot manufacture on my own. E.g., the `Task` object (that contains the task arguments). In implementing #1073 I need to either implement an entirely new calling convention (that was the original plan) or else figure out how to leverage Legion to help me fit the original one.

In principle there's no reason that the compiler can't do this, aside from time and effort to write and maintain two separate code paths in the compiler.

**Comment by lightsighter** [comment]
It's not very difficult to add to this to the runtime, but it just feels like an anti-feature. We definitely wouldn't recommend for anyone to use this in general. It's not really offering you anything.

**Comment by elliottslaughter** [comment]
Another direction I could go would be to modify the `Task` object myself. The inline call itself is not the hard part, the hard part is setting up all the arguments so that they're "similar enough" to what Regent is expecting to trick it into doing the right thing.

I see most `Task` fields are public, so as far as that goes, it's not an issue.

One issue is that there are no public `Task` constructors or copy constructors as far as I can tell. Maybe that's fine, but it would mean I'd need to reuse the parent task's `Task` object instead of creating a fresh one (or copy). I can make this work by saving the old values are restoring them (a bit like saving registers...) but it does seem a bit conceptually unclean.

What do you think? Would public constructors for `Task` open up too many opportunities for abuse?

**Comment by lightsighter** [comment]
> Another direction I could go would be to modify the Task object myself.

You can't modify the Task object you get from the runtime. It is actually a `const Task*` and points to a data structure that the runtime owns. Casting away the `const` and modifying the data structure yourself is unsafe and will likely break things.

> One issue is that there are no public Task constructors or copy constructors as far as I can tell. Maybe that's fine, but it would mean I'd need to reuse the parent task's Task object instead of creating a fresh one (or copy).

I don't think I would mind making the constructors of derived `Mappable` types public, especially so users can make their own copies or derived types if they want. Note that the `Task` does inherit from `Mappable` and there are a few virtual methods you would need to provide implementations to, but I think that is doable.

**Comment by elliottslaughter** [comment]
If you don't mind adding this, it seems like the fastest way to implement what I want for #1073.

**Comment by lightsighter** [comment]
All `Mappable` type default constructors are now public:

https://gitlab.com/StanfordLegion/legion/-/commit/7ddd8467a727f35ff37308b1463163d42d5f1988

**Comment by elliottslaughter** [comment]
Thanks, this resolves my need.
