### ISSUE TITLE
Python: legion_top.py -m mode does not support packages

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1103]
CPython supports running packages via the `-m` flag. I.e.:

```
python -m some_package
```

will work if you have a directory structure like `some_package/__main__.py` and the directory containing `some_package` is on `PYTHONPATH`.

We have some users who have noticed this discrepancy, and it would be good to make the implementation of `-m` in `legion_top.py` more robust so we support the same features as CPython.

**Comment by lightsighter** [comment]
I'm pretty sure I already added this and it was working for me with `pdb`.

https://gitlab.com/StanfordLegion/legion/-/blob/master/bindings/python/legion_top.py#L347-367

What modules are not working?

**Comment by elliottslaughter** [comment]
Right now we literally check for the module name plus `.py`:

https://gitlab.com/StanfordLegion/legion/-/blob/master/bindings/python/legion_top.py#L349

In the directory structure I mentioned above, the path to the "main" script in a package is `package_name/__main__.py`.

The module that's not working is an internal ExaFEL one so unfortunately can't be shared directly, but it should be trivial to come up with a reproducer if that would help.

**Comment by lightsighter** [comment]
I'm guessing you can fix this without me. :) The general support though for executing a module though is there.

**Comment by elliottslaughter** [comment]
The implementation isn't 100% trivial because it seems CPython imports the package before executing its `__main__` script. So we need to decide whether we want this package import to be global, or whether it should literally just be imported on the same node(s) that is (are) going to call `run_path` on `package/__main__.py`.

See this demo in CPython:

```
$ python3 -m asdf
in asdf.__init__, __name__ is 'asdf' and __package__ is 'asdf'
in asdf.__main__, __name__ is '__main__' and __package__ is 'asdf'
   and sys.args contains ['.../test_python_package/asdf/__main__.py']
   and asdf is in sys.modules? True
```

https://github.com/elliottslaughter/demo-python-package-import

Is it safe to call `import_global` from inside `legion_python_main`?

**Comment by elliottslaughter** [comment]
There's also some additional complexity that comes in when using nested packages:

https://stackoverflow.com/a/22250157/188046

**Comment by lightsighter** [comment]
> Is it safe to call import_global from inside legion_python_main?

It should be safe to call `import_global` from inside `legion_python_main`.

**Comment by elliottslaughter** [comment]
We fixed this a long time ago.
