### ISSUE TITLE
Realm: warn when user requests a logging level below what was compiled-in

### ISSUE THREAD

**Issue by manopapad** [StanfordLegion/legion#1110]
Happened to me when I tried using the `LoggingWrapper` with `-level mapper=2` on an application compiled with the Makefile template, https://github.com/StanfordLegion/legion/blob/stable/apps/Makefile.template, which sets `OUTPUT_LEVEL = LEVEL_PRINT` by default. It would have been nice to see a warning like "you asked for level 2 logging output on mapper, but Realm was compiled with minimum level 3", instead of thinking that my mapper was not being invoked, because I was seeing no output.

**Comment by streichler** [comment]
This made it into 21.06 with commit 9a6beee5.
