### ISSUE TITLE
Elide Futures and Future Maps When Unneeded in Regent

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#1117]
Legion supports eliding futures and future maps now if they are not needed by task launches. The Regent compiler should be able to determine whether futures and future maps are needed from the source code and set the appropriate flag on the launchers.

**Comment by elliottslaughter** [comment]
Is this in master or only in control_replication?

**Comment by lightsighter** [comment]
It's only in control replication. It needs the new future implementation that only exists there to work.

**Comment by lightsighter** [comment]
Although, we could do a poor-man's version of that in the C API for Regent so you can implement it in master.

**Comment by elliottslaughter** [comment]
If we could at least stub out the implementation in the C API, then I could do the implementation in master. I think the semantics of this are such that it doesn't actually need to do anything other than throw away the future if you didn't request it.

**Comment by lightsighter** [comment]
https://gitlab.com/StanfordLegion/legion/-/commit/7d98ef0429f47058014586c579ad697e30ba0619
