### ISSUE TITLE
How to create unified memory?

### ISSUE THREAD

**Issue by MiZhangWhuer** [StanfordLegion/legion#1127]
Thanks for sharing the tutorial code. I've a question when using Legion:
 How to deal with out of memory for GPU devices? Possible solution is allocating extra memory to CPU that can not be performed on GPU. Is there any guidance for implement the unified memory (virtual memory machinism) for Legion?

**Comment by manopapad** [comment]
If you get a failure from `(find_or_)create_physical_instance` in your mapper's `map_task` callback while trying to create physical instances for a GPU task, that means there is not enough memory available to reserve on the framebuffer. At that point you can instead place this instance on zero-copy memory (i.e. system memory that has been registered with the GPU), or decide to run your task on a CPU instead (assuming you have a variant that runs on CPUs).

There is currently no way to forcibly evict other instances on the framebuffer to make room for a new one, but see the discussion on https://github.com/StanfordLegion/legion/issues/909.

Another option is to preemptively ask the runtime to delay the mapping a GPU task, in the `select_tasks_to_map` mapper callback. You then need to resume mapping when you judge that enough memory has become available (use profiling requests to get notified of when tasks complete). There is some discussion to allow this "backtracking" to happen right when the physical instance allocation fails, but this is currently unsupported.

**Comment by elliottslaughter** [comment]
There is now a `-ll:msize` flag that allocates in UVM memory. It works with CUDA today and will work with HIP after https://gitlab.com/StanfordLegion/legion/-/merge_requests/443 has been merged.
