### ISSUE TITLE
legion: tasks using deferred buffers don't wait for future dependencies to complete before execution

### ISSUE THREAD

**Issue by rohany** [StanfordLegion/legion#1134]
Followup to discussion here: https://github.com/StanfordLegion/legion/issues/1123#issuecomment-900664381.

Here is some source code:
```c++
#include "legion.h"
#include <unistd.h>

using namespace Legion;
enum FieldIDs {
  FID_VAL,
};
enum TaskIDs {
  TID_TOP_LEVEL,
  TID_WORKER,
};

typedef ReductionAccessor<SumReduction<double>,true,1,coord_t,Realm::AffineAccessor<double,1,coord_t>> AccessorReducedouble2;

void worker(const Task* task, const std::vector<PhysicalRegion>& regions, Context ctx, Runtime* runtime) {
  auto workerIdx = *(int32_t*)task->args;
  std::cout << "starting worker " << workerIdx << std::endl;

  AccessorReducedouble2 acc(regions[0], FID_VAL, LEGION_REDOP_SUM_FLOAT64);

  double initVal = 0.f;
  DeferredBuffer<double, 1> buf(Memory::Kind::GPU_FB_MEM, DomainT<1>(Rect<1>(0, 50000000)), &initVal);
  double* inter = buf.ptr(0);

  usleep(500 * 1000);

  std::cout << "finishing worker " << workerIdx << std::endl;
}

void top_level_task(const Task* task, const std::vector<PhysicalRegion>& regions, Context ctx, Runtime* runtime) {
  auto fspace = runtime->create_field_space(ctx);
  Legion::FieldAllocator allocator = runtime->create_field_allocator(ctx, fspace);
  allocator.allocate_field(sizeof(double), FID_VAL);
  auto ispace = runtime->create_index_space(ctx, Rect<1>(0, 9));
  auto reg = runtime->create_logical_region(ctx, ispace, fspace);

  Future f;
  for (int i = 0; i < 10; i++) {
    int32_t idx = i;
    TaskLauncher launcher(TID_WORKER, TaskArgument(&idx, sizeof(int32_t)));
    launcher.add_region_requirement(RegionRequirement(reg, LEGION_REDOP_SUM_FLOAT64, SIMULTANEOUS, reg).add_field(FID_VAL));
    if (f.valid()) {
      launcher.add_future(f);
    }
    f = runtime->execute_task(ctx, launcher);
  }
}

int main(int argc, char** argv) {
  Runtime::set_top_level_task_id(TID_TOP_LEVEL);
  {
    TaskVariantRegistrar registrar(TID_TOP_LEVEL, "top_level");
    registrar.add_constraint(ProcessorConstraint(Processor::LOC_PROC));
    registrar.set_replicable();
    Runtime::preregister_task_variant<top_level_task>(registrar, "top_level");
  }
  {
    TaskVariantRegistrar registrar(TID_WORKER, "worker");
    registrar.add_constraint(ProcessorConstraint(Processor::TOC_PROC));
    registrar.set_leaf();
    Runtime::preregister_task_variant<worker>(registrar, "worker");
  }
  return Runtime::start(argc, argv);
}
```

I've compiled this on legion commit 3dac89847e8be99201a1768704639409dafb6401. It should be run with arguments `./bin/future-bug -ll:gpu 1 -ll:fsize 7000 -lg:eager_alloc_percentage 80` on a sapling gnode.

I expect this program to output
```
starting worker 0
finishing worker 0
starting worker 1
finishing worker 1
starting worker 2
finishing worker 2
starting worker 3
finishing worker 3
starting worker 4
finishing worker 4
starting worker 5
finishing worker 5
starting worker 6
finishing worker 6
starting worker 7
finishing worker 7
starting worker 8
finishing worker 8
starting worker 9
finishing worker 9
```
instead, I see this output like this:
```
starting worker 0
starting worker 1
starting worker 2
finishing worker 0
finishing worker 1
finishing worker 2
starting worker 3
starting worker 4
starting worker 5
finishing worker 3
finishing worker 4
finishing worker 5
starting worker 6
starting worker 7
starting worker 8
finishing worker 6
finishing worker 7
finishing worker 8
starting worker 9
finishing worker 9
```
which indicates the executions of these tasks are interleaved for some reason, when they should be executing serially, based on the future dependencies that they have.

This seems to be related to the fill that occurs for allocation of a deferred buffer with an initial value. If the deferred buffer allocation is changed to the constructor that does not initialize the data, then the problem does not occur. While the buffer is being filled, the dependent task starts executing, rather than waiting for the prior task to execute.

**Comment by lightsighter** [comment]
The runtime is also behaving normally here. Your futures don't have any payload in them so the runtime can safely break the dependence without impacting the functional nature of the computation. The only dependences that the runtime abides by are the ones where data must be passed to satisfy the dataflow of the program.

**Comment by rohany** [comment]
I see, thanks.

**Comment by lightsighter** [comment]
If you want you can bring this up in a future Legion meeting and see what the rest of the group thinks. I would be open to adding a separate struct on launchers for specifying "control" dependences if enough people support that idea.

**Comment by rohany** [comment]
I could bring it up if you think that either
1) this should be something people are allowed to do (i'm not sure about this, we both agree this is something the mapper should control)
2) there are potentially other use cases (I'm not sure about this either)

**Comment by lightsighter** [comment]
The ambiguity about the possibility of other use cases in addition to this one and the fact that you were surprised by the behavior suggests that this is worthy of discussion in a Legion meeting.
