### ISSUE TITLE
Realm: packet corruption with gasnet-ex layer

### ISSUE THREAD

**Issue by mariodirenzo** [StanfordLegion/legion#1141]
This issue keeps track of the packet corruption observed with HTR on Lassen.
The main symptom is this error (which seems to repro only in release mode)
```
[0 - 20004579f8b0]   48.809539 {6}{gex}: CRC MISMATCH: arg0=1057137026 header_size=112 payload_size=0 exp=0 act=68b02441
```
If the code is run with `-gex:cksum 0`, we hit this assertion
```
prometeo_CH4_26SpIonsMix.exec: /g/g92/direnzo1/legion/runtime/realm/gasnetex/gasnetex_internal.cc:4526: size_t Realm::GASNetEXInternal::handle_batch(gex_Rank_t, gex_AM_Arg_t, const void*, size_t, gex_AM_Arg_t*): Assertion `ofs <= data_bytes' failed.
```
The problem seems to go away with `-gex:batch 0` (though the code becomes much slower)

**Comment by rohany** [comment]
This looks like the same problems I am running into in https://github.com/StanfordLegion/legion/issues/1118! Hopefully the root cause is the same.

**Comment by rohany** [comment]
Hey Mario, try on this commit (https://gitlab.com/StanfordLegion/legion/-/commits/gex_debug_1) and see if your problem goes away

**Comment by rohany** [comment]
I haven't run into that before. @streichler will probably need backtraces

**Comment by elliottslaughter** [comment]
@mariodirenzo Can you run again and see if this issue still exists?

**Comment by mariodirenzo** [comment]
The issue seems fixed. Thanks
