### ISSUE TITLE
Legion: Pass arguments to operations other than tasks

### ISSUE THREAD

**Issue by magnatelee** [StanfordLegion/legion#1146]
Being able to pass arguments to operations like copies and fills would be helpful for libraries to use their domain specific abstractions in the mappers. For example, Legate mappers want to describe mapping decisions in terms of Legate stores, instead of logical regions and fields directly, and currently they can do this only for tasks by deserializing task arguments.

**Comment by lightsighter** [comment]
This is fixed with https://gitlab.com/StanfordLegion/legion/-/merge_requests/411

**Comment by lightsighter** [comment]
And up-streamed into control replication. Closing the issue.
