### ISSUE TITLE
legion_prof_rs missing tooltips on utility processors

### ISSUE THREAD

**Issue by syamajala** [StanfordLegion/legion#1147]
I am not getting tooltips when I hover over individual boxes on a utility processor in a legion profile generated using legion_prof_rs. 

There is an example here: http://sapling.stanford.edu/~seshu/s3d_hept/tmp24_0/run/legion_prof/?start=773044646.4106247&end=779229477.5153278&collapseAll=false&resolution=10

The orange boxes on utility processor 0 are missing tooltips. 

A profile log file is available here: http://sapling.stanford.edu/~seshu/s3d_hept/tmp24_0/run/prof_0.gz

**Comment by elliottslaughter** [comment]
Confirmed that the tooltip is missing in Rust but is there with Python.

```
pypy .../tools/legion_prof.py prof_0.gz -o legion_prof_py
legion_prof prof_0.gz -o legion_prof_rs
```

Exactly Legion version doesn't seem to matter, but I'm currently on d6240a8e0896baf37ecdb1213b5d7ae6743bfec6.

**Comment by syamajala** [comment]
@elliottslaughter this bug looks like its still there too...

**Comment by elliottslaughter** [comment]
Ok, will try to take a look at this next.

**Comment by elliottslaughter** [comment]
Is this issue still present on the most recent `master`? I just pushed changes that fix `legion_prof_ops.tsv` in Rust, which may be related.

If you need `control_replication`, maybe wait for that merge before testing.

**Comment by syamajala** [comment]
It works on the latest master.
