### ISSUE TITLE
Regent: should rescape/remit be lexically or dynamically scoped?

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1153]
Right now, `rescape`/`remit` are dynamically scoped. This means you can write code like:

```lua
import "regent"

function generate_remit()
  remit rquote end
end

task main()
  rescape
    generate_remit()
  end
end
regentlib.start(main)
```

Is this actually desirable? Should this generate an error?

**Comment by magnatelee** [comment]
I don't have a strong preference on this, but isn't Terra's escape/quote also dynamically scoped?

**Comment by thiagotei** [comment]
I also agree that in the last example dynamically scoped makes more sense.
