### ISSUE TITLE
OPENMP dynamic scheduling

### ISSUE THREAD

**Issue by albovoci** [StanfordLegion/legion#1154]
Hello,
I'm attempting to parallelize a loop in the following format:
`#ifdef REALM_USE_OPENMP`
`    #pragma omp parallel for schedule(dynamic)`
 `#endif`
 `for (std::size_t i=0; i<N; i++) {...}`
Compilation will fail with the following error:
`In function UpdateUsingHybridEulerFluxTask<(direction)0>::cpu_base_impl(UpdateUsingHybridEulerFluxTask<(direction)0>::Args const&, std::vector<Legion::PhysicalRegion, std::allocator<Legion::PhysicalRegion> > const&, std::vector<Legion::Future, std::allocator<Legion::Future> > const&, Legion::Internal::TaskContext*, Legion::Runtime*) [clone ._omp_fn.0]':`
`prometeo_rhs.cc:(.text+0xe957): undefined reference to "GOMP_loop_ull_dynamic_start'`
`prometeo_rhs.cc:(.text+0xea34): undefined reference to "GOMP_loop_ull_dynamic_next'`
`collect2: error: ld returned 1 exit status`

Is compatibility with dynamic scheduling compatible with Legion?
Thank you.

**Comment by albovoci** [comment]
Legion version legion-21.06.0-3075-gff44815 committed on 2021-09-24

**Comment by streichler** [comment]
@albovoci can you try cherry-picking this commit onto whatever legion branch you're using and see if it links properly (and works right): https://gitlab.com/StanfordLegion/legion/-/commit/57b560a696580e777150aae4adc806fcbf4af3d3

**Comment by albovoci** [comment]
@streichler Legion compiles just fine. However, I can't compile the code at all. It gives a very long list of errors. 
I don't understand most of it, but it seems some of the Legion functions are missing? Some example errors printed:
`prometeo_mapper.cc:(.text._ZN13SampleMapping15Tiling3DFunctorD2Ev[_ZN13SampleMapping15Tiling3DFunctorD5Ev]+0x8): undefined reference to `Legion::ShardingFunctor::~ShardingFunctor()'`
`undefined reference to `Legion::Future::get_buffer(Realm::Memory::Kind, unsigned long*, bool, bool, char const*) const'`

**Comment by streichler** [comment]
Which commit/branch of Legion are you trying to build against?  Do you remember which one you were using the last time it linked properly?

**Comment by albovoci** [comment]
Hi; sorry, my bad. I had a but in my configuration file, had to clean it up and rebuild. I got it to work (and its working correctly, at least as far as I can tell from my simulation outputs)!
