### ISSUE TITLE
legion_prof_rs: entered unreachable code

### ISSUE THREAD

**Issue by magnatelee** [StanfordLegion/legion#1161]
I hit `'internal error: entered unreachable code', src/state.rs:2035:17` when I passed [this log file](https://github.com/StanfordLegion/legion/files/7455421/prof_0.zip) to legion-prof-rs.

**Comment by elliottslaughter** [comment]
Sorry, the file doesn't parse anymore because the logger format changed. Any way to regenerate this?

**Comment by magnatelee** [comment]
@elliottslaughter I actually forgot how I got this log file, as it's long time ago. I'll close this issue for now.
