### ISSUE TITLE
Realm: gasnetex RMDA Put error

### ISSUE THREAD

**Issue by syamajala** [StanfordLegion/legion#1168]
My last round of testing gasnetex on Summit resulted in the following error:
```
mlx5: h50n15: got completion with error:
00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000
00000016 00000000 00000000 00000000
00000000 00005604 080011ba 08e96ad2
mlx5: h50n15: got completion with error:
@ 21> snd status=4 opcode=1 dst_node=22 dst_qp=0
00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000
00000016 00000000 00000000 00000000
00000000 00005604 08010cfe 08cabad3
@ 21> snd status=4 opcode=1 dst_node=22 dst_qp=3
*** FATAL ERROR (proc 21): in gasnetc_snd_reap() at gasnet/GASNet-2021.9.0/ibv-conduit/gasnet_core_sndrcv.c:843: aborting on reap of failed send
*** FATAL ERROR (proc 21): in gasnetc_snd_reap() at gasnet/GASNet-2021.9.0/ibv-conduit/gasnet_core_sndrcv.c:843: aborting on reap of failed send
```

According to the gasnet people status=4 opcode=1 means IBV_WC_LOC_PROT_ERR (local protection error) on a RDMA Put operation. 

I believe this still needs to be investigated on the Realm side. I have to do a run with a debug build of gasnetex using this branch: https://bitbucket.org/PHHargrove/gasnet-public/src/master/

Also I should note the work aronud for now is to run with `-gex:rmaput 0`

**Comment by streichler** [comment]
@syamajala has this one gone away too?
