### ISSUE TITLE
legion_prof.py physical instance tooltips

### ISSUE THREAD

**Issue by syamajala** [StanfordLegion/legion#1175]
When you have a physical instance with a lot of fields its not possible to see the tooltip. Maybe there could be a linebreak on the list of fields? Or just truncate the field list?

![2022-01-24-101129_3840x2160_scrot](https://user-images.githubusercontent.com/45757/150840244-3a672154-e0f0-44f4-99c3-3c1b57ee512a.png)

**Comment by elliottslaughter** [comment]
Sorry, I broke this when I implemented Rust, in order to keep things consistent. I'll look into adding this behavior back.

**Comment by elliottslaughter** [comment]
I'm testing a fix in `profiler-break-fields` in case you want to try it out. (I believe it should work for profiles from control replication.)

**Comment by syamajala** [comment]
the fix works for me, both rust and python profilers.

**Comment by elliottslaughter** [comment]
I pushed this to `master`. Will make it up to `control_replication` on the next merge; let me know if you need it earlier.
