### ISSUE TITLE
Tracing succeeds even when different regions are passed as arguments

### ISSUE THREAD

**Issue by joeythaman** [StanfordLegion/legion#1178]
I was working with tracing and testing out its functionalities and I wrote the following program expecting it to fail.  As you can see in this program every iteration of the outer loop calls abcd with a different partition region.  From my understanding of tracing, I would expect this to cause tracing to fall as a different region is used in abcd in every iteration.  However, when I run regent.py on this code, it succeeds and every element of input_lr has been set to 100 as would be expected without tracing.  Is this a bug or do I not understand how tracing works.  Thank you!

```
import "regent"

local c = terralib.includec("stdio.h")

fspace input {
  x : int
}

task abcd(input_lr : region(ispace(int1d), input))
where reads writes(input_lr.{x}) do
  for i in input_lr do
    input_lr[i].x += 1
  end
end

task main()
  var num_elements = 20
  var is = ispace(int1d, num_elements)
  var input_lr = region(is, input)

  var num_subregions = 10
  var ps = ispace(int1d, num_subregions)
  var p = partition(equal, input_lr, ps)

  
  for i = 0, num_subregions do
    __demand(__trace)
    for j = 0, 100 do
      abcd(p[i])
    end
  end

  for i in is do
      c.printf("%d\n",input_lr[i].x)
  end
end

regentlib.start(main)
```

**Comment by rohany** [comment]
Does it still work if you pass `-dm:memoize` as a command line argument to the program?

**Comment by joeythaman** [comment]
Yes even calling regent.py with -dm:memoize, it still works.

**Comment by joeythaman** [comment]
Also I am on the master branch on git commit a2ddc9613a41b0a6d16c72bf1b152c0c5f30f80b

**Comment by rohany** [comment]
Does it still work if you changed this loop (and have -dm:memoize):
```
  for i = 0, num_subregions do
    __demand(__trace)
    for j = 0, 100 do
      abcd(p[i])
    end
  end
```
to 
```
  for j = 0, 100 do
    __demand(__trace)
    for i in 0, num_subregions do
      abcd(p[i])
    end
  end
```

**Comment by joeythaman** [comment]
Yep it still works

**Comment by rohany** [comment]
I'm out of ideas, I'm not very familiar with tracing. @lightsighter or @magnatelee can you explain what's going on here?

**Comment by syamajala** [comment]
Im no expert either, but I think its because tracing depends on the physical instances not the subregions? Even though you are partitioning the region I guess the default mapper only makes 1 physical instance so it is able to replay the trace.

**Comment by rohany** [comment]
If that's the case, try running with `-dm:exact_region` and see if it breaks.

**Comment by joeythaman** [comment]
It's still seems to working with `-dm:exact_region`.  To be specific, I ran `./regent.py tests/regent/run_pass/tracing_test.rg -dm:memoize -dm:exact_region` and it ran as I would expect it to.

**Comment by lightsighter** [comment]
Safety checks for tracing are on the todo list in issue #407. For now there are no guardrails, so don't drive off the road.

**Comment by joeythaman** [comment]
Good to know.  Thank you!

**Comment by lightsighter** [comment]
In general though your expectation that is illegal to replay a trace with different region arguments is accurate. 

I'm going to close this issue since we've got it documented that having safety checks on trace replays is something we should do. If you feel like additional discussion is needed then you can reopen the issue.
