### ISSUE TITLE
NVIDIA CUDA Ampere architecture support for Regent

### ISSUE THREAD

**Issue by mariodirenzo** [StanfordLegion/legion#1184]
Hello, is there any plan to include Ampere among the CUDA architectures supported by Regent?
Is it sufficient to add the new architecture to this list to test it?
https://gitlab.com/StanfordLegion/legion/-/blob/control_replication/language/src/regent/cudahelper.t#L198-205

**Comment by magnatelee** [comment]
I believe we support ampere in regent: https://gitlab.com/StanfordLegion/legion/-/blob/control_replication/language/src/regent/cudahelper.t#L205 The prerequisite is to build terra with llvm 13.0, which is the version that supports ampere in nvptx.

**Comment by elliottslaughter** [comment]
@magnatelee I just added that line. :-)

I confirmed that we have a user who has been using Regent in *online* mode with LLVM 11. The patch I just sent in will (hopefully) enable offline mode as well. Waiting for @mariodirenzo to confirm.

**Comment by mariodirenzo** [comment]
The new patch, together with LLVM 11, solves the issue.
Thanks!
