### ISSUE TITLE
legion: O(n^2) loop in index space independence check 

### ISSUE THREAD

**Issue by rohany** [StanfordLegion/legion#1191]
Slack comment thread for context:

Mike: So we're definitely in this doubly nested loop which is O(N^2) in the number of rectangles in the two sparsity maps and the comment about putting an acceleration data structure here in the future is relevant:
https://gitlab.com/StanfordLegion/legion/-/blob/control_replication/runtime/legion/region_tree.inl#L1281-1330
That said, i would still ask you why each of the sparsity maps has more than 500K rectangles in them:
```
(gdb) p/x local_space
$16 = {
  bounds = {
    lo = {
      x = 0x0
    },
    hi = {
      x = 0xa7cb2f
    }
  },
  sparsity = {
    id = 0x3000000000000004
  }
}
(gdb) p/x other_space
$17 = {
  bounds = {
    lo = {
      x = 0x0
    },
    hi = {
      x = 0xa7cb2f
    }
  },
  sparsity = {
    id = 0x3000000000000001
  }
}
(gdb) p local_rects.size()
$18 = 551498
(gdb) p local_rects.size()
$19 = 551498
```
FWIW, this is all happening in 1-D which you can see from the bounds on the spaces

Mike:
My guess is that ultimately these two index spaces will compare equivalent, but we do have to do the full check of all the rectangles to ensure that so at least in this case we're effectively comparing every rectangle to every other one, with only minimal shortcuts and pruning, again that can be made faster, but understanding why a sparsity map has 500K rectangles is likely to get us to a fix sooner

Sean: 
you're just testing for equality of the index spaces?  if so, I can give you a IndexSpace<...>::contains(IndexSpace<...>) method which will still be blocking but will be O(N) instead of O(N^2) for a 1-D space, or you can use the existing IndexSpace<...>::compute_difference(...) which will be O(N) and run on a background thread, but will of course require you to deal with waiting on the event

**Comment by streichler** [comment]
@rohany you left out the part where I think you're claiming that there's no reason to be doing this test at all?  Can you remind me how that goes?

**Comment by rohany** [comment]
Ah yes. Here's the relevant code:

```
  LogicalPartition B2_crd_part = ...
  IndexPartition posSparsePartB2 = runtime->create_partition_by_preimage_range(ctx, B2_crd_index_part, B2_pos, B2_pos_parent, FID_RECT_1, runtime->get_index_partition_color_space_name(ctx, B2_crd_index_part));
  IndexPartition posIndexPartB2 = densifyPartition(ctx, runtime, get_index_space(B2_pos), posSparsePartB2);
  LogicalPartition posPartB2 = runtime->get_logical_partition(ctx, B2_pos, posIndexPartB2);
  LogicalPartition crdPartA2 = ...
  IndexPartition posSparsePartA2 = runtime->create_partition_by_preimage_range(ctx, crdPartA2.get_index_partition(), A2_pos, A2_pos_parent, FID_RECT_1, runtime->get_index_partition_color_space_name(ctx, crdPartA2.get_index_partition()));
  IndexPartition posIndexPartA2 = densifyPartition(ctx, runtime, get_index_space(A2_pos), posSparsePartA2);
  ```
Here, the expensive check occurs between posSparsePartB2 and posSparsePartA2. I never launch any tasks over either of these partitions and use them just to create the "dense" partitions posIndexPartB2 and posIndexPartA2 formed by taking the bounding boxes of each subregion in the sparse partitions. Since I never do anything else with those partitions, it feels like the expensive runtime check is unneeded.

**Comment by lightsighter** [comment]
Computing disjointness on partitions is extremely expensive so if you don't tell Legion the disjointess properties of your partition it will start computing it eagerly with the anticipation that you will need it later. The alternative of waiting until the disjointness information is needed often exposes huge latencies. If don't want the runtime to compute anything then tell it pessimistically that the partition is an aliased-incomplete partition and no computation will occur.

**Comment by rohany** [comment]
Awesome, confirming that this worked.

**Comment by lightsighter** [comment]
There is an acceleration data structure in there now. Pull and try it out. I can't promise it will be much faster, but congruence tests should now be O(N log M) where N and M are the number of rectangles in the sparsity maps and N <= M.

**Comment by rohany** [comment]
I'll try this out sometime, but it doesn't really block me anymore -- switching to telling the runtime `ALIASED_INCOMPLETE_PARTITION` was sufficient for my use cases, and means I don't pay any cost at all for it.

**Comment by lightsighter** [comment]
Assigning back to @rohany to confirm the fix.

**Comment by rohany** [comment]
Works fine now.
