### ISSUE TITLE
Bisecting on Summit

### ISSUE THREAD

**Issue by bandokihiro** [StanfordLegion/legion#1193]
I am bisecting through the commits to figure out when legion stopped working reliably on Summit. The first good commit is the parent tha originates from `control_replication` of `realm/fbpack_cr_ipc`. So far I have found 1c04fd08f86be2c08fd01a960a2c3e658a642e88 to be a first bad commit with 5b8870329da02f1fe6471786ea361f46d8223d2f being good. The bad commit's mode of failure was either a hang or some obscure error. Empirically trying to understand the backtraces, I think this has to do with futures. An example backtrace of an error that `LEGION_FREEZE_ON_ERROR=1` caught is this one:
[gdb.txt](https://github.com/StanfordLegion/legion/files/8056773/gdb.txt)

I am suspecting this not to be the root cause of issues I see with the most recent `control_replication` since it has a different mode of failure. My hypothesis is that `git bisect` put me first on a commit behind a fix to the above error.

**Comment by lightsighter** [comment]
These changes are from very long ago. The nature of the first bad commit you and the backtrace suggest an issue with the interaction between Realm and GASNet. I know that many such fixes have been put into Realm since last September. Are we sure they haven't been fixed by later commits? Are you working with Sean to resolve this or are you looking for more general help?

**Comment by bandokihiro** [comment]
@streichler is helping a lot in general. I started this binary search myself because there is a definitive issue on Summit. I am not the only one seeing it. Since I might need recent or new changes to the runtime, I didn't want to postpone figuring out the current issue too much. I am looking for general guidance. What you said seems to confirm my hypothesis, i.e. the (most recent and first) bad commit I identified happened to have a different issue that might be already fixed. But if the current issue was introduced before that fix, then binary searching becomes more difficult since I am not aware of all the issues and fixes and I would need to start cherry-pick commits here and there at each step of the bisection.

**Comment by bandokihiro** [comment]
Good idea, i'll try

**Comment by bandokihiro** [comment]
I used another workaround suggested by Sean. I used `-gex:rmaput 0`. This is now the newly identified commits:

`git bisect good 42b768e1` (commit on which realm/fbpack_cr_ipc is based)
`git bisect bad 63721caa` (most recent CR)
731c514db7256e0bc03dad6264d4f7de18b3a2aa good
38d9923729ee1121a0034f2a9eb17bd1dc8deef0 bad
```
solver: /ccs/home/bandok/Softwares/legion/runtime/realm/gasnetex/gasnetex_internal.cc:1668: void Realm::XmitSrcDestPair::push_packets(bool, Realm::TimeLimit): Assertion `ncomps > 0' failed.
solver: /ccs/home/bandok/Softwares/legion/runtime/realm/gasnetex/gasnetex_internal.cc:733: bool Realm::PendingCompletion::invoke_remote_completions(): Assertion `prev_count > 0' failed.
```
b84b060086443d7c1bcb6ec157f811424eecd556 bad
```
[4 - 200036f9f890]    1.538350 {5}{runtime}: [error 576] LEGION ERROR: Failed to allocate eager future buffer for task store_elem_volume_task (UID 664) because Visible to all processors on a node memory 1e00040000000001 is full. This is an eager allocation so you must adjust the percentage of this mememory dedicated for eager allocations with '-lg:eager_alloc_percentage' flag on the command line. (from file /ccs/home/bandok/Softwares/legion/runtime/legion/runtime.cc:10461)
```
9ef17bc67f20546b63e0c5e15083548476cb321c good
44e5ba69b8c6339fa18582325e57e8a0d6e3059a bad
```
*** Caught a fatal signal (proc 0): SIGSEGV(11)
e67a940283e9084fd7bd84953ac8f295174cfafc bad
ERROR:  One or more process (first noticed rank 0) terminated with signal 11 (core dumped)
```
45d99995f11633260fc48e43a02c8359c28730f9 good
e67a940283e9084fd7bd84953ac8f295174cfafc (first bad commit)

**Comment by bandokihiro** [comment]
Let me know if I need to fecth a backtrace for e67a940.

**Comment by bandokihiro** [comment]
The backtrace from e67a940283e9084fd7bd84953ac8f295174cfafc
[gdb.txt](https://github.com/StanfordLegion/legion/files/8064363/gdb.txt)

**Comment by streichler** [comment]
@bandokihiro I assume this was a SEGV?
@lightsighter here's the line where it's happening: https://github.com/StanfordLegion/legion/blob/e67a940283e9084fd7bd84953ac8f295174cfafc/runtime/legion/region_tree.cc#L10036

**Comment by lightsighter** [comment]
I can't say for certain but I'm pretty sure I fixed a bug like that several months ago. Without a reproducer it's going to be impossible to fix.

**Comment by bandokihiro** [comment]
a) failed 
[gdb.txt](https://github.com/StanfordLegion/legion/files/8064434/gdb.txt)

**Comment by lightsighter** [comment]
This just reeks of memory corruption. Errors are all over the place.

**Comment by lightsighter** [comment]
Are any of the errors reproducible?

**Comment by bandokihiro** [comment]
It reliably fails, I don't know if it is always for the same reason.

**Comment by lightsighter** [comment]
I mean does it fail with the same backtrace or the same few backtraces in the same place everytime on the same commit? I haven't seen a repeated backtrace yet.

**Comment by bandokihiro** [comment]
Probably not, I have seen all sort of failure modes. But the first bad commit always fails so far so I can generate a few backtraces with the same binaries if it helps.

**Comment by bandokihiro** [comment]
Also, ignore the first backtrace. This hang has been solved recently and I can bypass that with the gex flag.

**Comment by bandokihiro** [comment]
To summarize
- backtrace from e67a940283e9084fd7bd84953ac8f295174cfafc
- backtrace from 45d99995f11633260fc48e43a02c8359c28730f9 with realm changes 
- backtrace from 45d99995f11633260fc48e43a02c8359c28730f9 with legion changes

[gdb.txt](https://github.com/StanfordLegion/legion/files/8064495/gdb.txt)
[gdb_a.txt](https://github.com/StanfordLegion/legion/files/8064496/gdb_a.txt)
[gdb_b.txt](https://github.com/StanfordLegion/legion/files/8064497/gdb_b.txt)

**Comment by lightsighter** [comment]
And which of those are repeatable?

**Comment by bandokihiro** [comment]
I have only run once each for now.

**Comment by bandokihiro** [comment]
45d99995f11633260fc48e43a02c8359c28730f9 with realm changes from e67a940283e9084fd7bd84953ac8f295174cfafc (a) and fa7834d8 did not fail.

45d99995f11633260fc48e43a02c8359c28730f9 with legion changes from e67a940283e9084fd7bd84953ac8f295174cfafc (b) failed with the same backtrace so it is reproducible.

**Comment by bandokihiro** [comment]
(d) e67a940283e9084fd7bd84953ac8f295174cfafc with fa7834d8 failed like (b)

**Comment by lightsighter** [comment]
Ok, I remember the Legion bug. There's an issue with reference counting. In January, I overhauled the reference counting scheme for index space expressions including index spaces to keep them alive correctly in all circumstances, including those like this where a disjointness test lags the deletion of an index space. There's not going to be a way to back-port those changes as they were super-invasive all throughout the runtime.

**Comment by bandokihiro** [comment]
So what is the strategy moving forward? Can you point me to the first commit that fixed all these issues?

**Comment by lightsighter** [comment]
You'll at least need the commits in these merge requests:
https://gitlab.com/StanfordLegion/legion/-/merge_requests/419
https://gitlab.com/StanfordLegion/legion/-/merge_requests/420

**Comment by lightsighter** [comment]
I think that's all of them, but I might be wrong.

**Comment by bandokihiro** [comment]
Thanks to @streichler, this seems fixed. I am running in a while true loop my case several times just to be extra safe. The fix will be merged very soon into master. I'll leave this open for the rest of the week if someone wants to add something. But so far, it looks resolved.

**Comment by bandokihiro** [comment]
hanged after 15 runs on summit so I guess this is not quite over yet

**Comment by bandokihiro** [comment]
It seems that there is another bug that @streichler already fixed related to the use of more than 1 utility processor on Summit. The fixes are not merged yet. I'll let him comment as to when this will happen. So far 30 runs succeeded.

**Comment by bandokihiro** [comment]
Running a bigger case, the most recent CR + additional realm fixes fail with the following backtraces
[gdb0.txt](https://github.com/StanfordLegion/legion/files/8084517/gdb0.txt)
[gdb1.txt](https://github.com/StanfordLegion/legion/files/8084518/gdb1.txt)

**Comment by streichler** [comment]
Both ranks have a thread doing this:
```
#4  0x0000000010abef88 in Legion::Internal::Runtime::find_messenger (this=0x1ede0010, sid=4294967295) at /gpfs/alpine/scratch/bandok/csc335/Softwares/legion/runtime/legion/runtime.cc:20917
#5  0x0000000010ad3d70 in Legion::Internal::Runtime::send_equivalence_set_replication_update (this=<optimized out>, target=<optimized out>, rez=...) at /gpfs/alpine/scratch/bandok/csc335/Softwares/legion/runtime/legion/runtime.cc:22620
#6  0x00000000110eedbc in Legion::Internal::EquivalenceSet::broadcast_replicated_state_updates (this=0x20222c492940, mask=..., mapping=0x0, origin=<optimized out>, applied_events=..., need_lock=<optimized out>, perform_updates=<optimized out>) at /gpfs/alpine/scratch/bandok/csc335/Softwares/legion/runtime/legion/legion_analysis.cc:11788
#7  0x00000000110ef030 in Legion::Internal::EquivalenceSet::broadcast_replicated_state_updates (this=0x20222c492940, mask=..., mapping=0x0, origin=<optimized out>, applied_events=..., need_lock=<optimized out>, perform_updates=<optimized out>) at /gpfs/alpine/scratch/bandok/csc335/Softwares/legion/runtime/legion/legion_analysis.cc:11756
#8  0x00000000110ef4e4 in Legion::Internal::EquivalenceSet::handle_replication_update (derez=..., runtime=<optimized out>) at /gpfs/alpine/scratch/bandok/csc335/Softwares/legion/runtime/legion/legion_analysis.cc:16705
#9  0x0000000010a52524 in Legion::Internal::Runtime::handle_equivalence_set_replication_update (this=<optimized out>, derez=...) at /gpfs/alpine/scratch/bandok/csc335/Softwares/legion/runtime/legion/runtime.cc:24583
#10 0x0000000010b24b84 in Legion::Internal::VirtualChannel::handle_messages (this=0x2022000291d0, num_messages=<optimized out>, runtime=0x1ede0010, remote_address_space=<optimized out>, args=<optimized out>, arglen=<optimized out>) at /gpfs/alpine/scratch/bandok/csc335/Softwares/legion/runtime/legion/runtime.cc:12715
#11 0x0000000010b2545c in Legion::Internal::VirtualChannel::process_message (this=0x2022000291d0, args=<optimized out>, arglen=120, runtime=0x1ede0010, remote_address_space=<optimized out>) at /gpfs/alpine/scratch/bandok/csc335/Softwares/legion/runtime/legion/runtime.cc:11770
#12 0x0000000010b25848 in Legion::Internal::MessageManager::receive_message (this=<optimized out>, args=<error reading variable: value has been optimized out>, arglen=<optimized out>) at /gpfs/alpine/scratch/bandok/csc335/Softwares/legion/runtime/legion/runtime.cc:13203
#13 0x0000000010b258ac in Legion::Internal::Runtime::process_message_task (this=<optimized out>, args=0x200cb812e31c, arglen=<optimized out>) at /gpfs/alpine/scratch/bandok/csc335/Softwares/legion/runtime/legion/runtime.cc:25628
#14 0x0000000010b25b80 in Legion::Internal::Runtime::legion_runtime_task (args=0x200cb812e310, arglen=136, userdata=<optimized out>, userlen=<optimized out>, p=...) at /gpfs/alpine/scratch/bandok/csc335/Softwares/legion/runtime/legion/runtime.cc:31140
```
@lightsighter thoughts?

**Comment by lightsighter** [comment]
This code is also already been deleted in the collective instances branch, so has the same lifetime as the other issue: no more than a few weeks at most. If you want me to look at it I need a reproducer and even then I can't promise I'm going to take the time to fix it.

**Comment by bandokihiro** [comment]
fcced203e was found to be healthy in the sense that I have been able to run strong scaling tests on Summit from 1 to 32 nodes without issues. I will likely scale up in the near future and see if my application triggers any bug.
