### ISSUE TITLE
Implement fills directly on files

### ISSUE THREAD

**Issue by rauteric** [StanfordLegion/legion#1204]
When I try to write an array to a file using AttachLauncher, I get this error:

```
[0 - 7f50c40c8000]    0.435815 {6}{new_dma}: FATAL: multi-hop fill path found for 1e00000000000004 (serdez=0)
```
from [this file](https://github.com/StanfordLegion/legion/blob/stable/runtime/realm/transfer/transfer.cc#L3821) in Legion. This is due to fills directly on files not being fully implemented in Legion.

This problem was [reported](https://groups.google.com/g/legionusers/c/8N23kcm_MuQ/m/GFu4hKFnAgAJ) in the mailing list. This is an issue to track the progress.

**Comment by streichler** [comment]
Assigning to myself at least until I can delegate to somebody.  I'd need to look at the code a bit more to be sure, but I
think the right answer here is to support a multi-hop fill path as a general fallback.  It adds an extra memcpy (but these
are paths that aren't performance-critical) and avoids a bunch of per-channel code changes.

**Comment by streichler** [comment]
@rauteric I have a commit in a branch that hopefully fixes this.  Are you interested in giving it a try?

**Comment by rauteric** [comment]
Thanks @streichler, if you point me to the branch I can give it a try.

**Comment by rupanshusoi** [comment]
@streichler Has this been fixed? I'm also hitting this when trying to fill a logical region that immediately gets written to disk.

**Comment by streichler** [comment]
I'm pretty sure this was merged into the main branches quite a while ago.  @rupanshusoi what is the exact error message you're getting, and what version/commit of Legion are you using?

**Comment by rupanshusoi** [comment]
Ah I was just on an old branch. I don't hit this on the newest master, thanks!
