### ISSUE TITLE
Legion_USE_OpenMP cmake condition not exported

### ISSUE THREAD

**Issue by sumathil** [StanfordLegion/legion#1205]
I am trying to use a Legion CMake condition _Legion_USE_OpenMP_ similar to this [cmake condition](https://github.com/StanfordLegion/legion/blob/stable/CMakeLists.txt#L762-L764 ) to append the Legion OpenMP flags but looks like _Legion_USE_OpenMP_  condition is not being exported to its target.

**Comment by elliottslaughter** [comment]
If you're on `master`, please update to 479892991487885c3d704278eba5f414ab2cab57 and try again.

**Comment by elliottslaughter** [comment]
Please clone from our internal mirror here: https://gitlab.com/StanfordLegion/legion

**Comment by sumathil** [comment]
Thank you, it works now.
