### ISSUE TITLE
DefaultMapper map_must_epoch error

### ISSUE THREAD

**Issue by tpeach90** [StanfordLegion/legion#1212]
https://github.com/StanfordLegion/legion/blob/e1443112edaa574804b3b9d2a24803e937b127fd/runtime/mappers/default_mapper.cc#L3601-L3606

This is missing an `it3++`, I believe. It was causing a segfault while grouping tasks together.

**Comment by lightsighter** [comment]
@tpeach90 nice catch! I pushed a fix to out gitlab repo which will be mirrored here on github after it passes CI:

https://gitlab.com/StanfordLegion/legion/-/commit/10198bb8d023a4187780d76219b938507db7cc4a
