### ISSUE TITLE
HIP: legion_prof.py under reporting GPU task times

### ISSUE THREAD

**Issue by syamajala** [StanfordLegion/legion#1214]
legion_prof is currently under reporting GPU task execution times when using HIP. I manually added synchronization and timing code around hipKernelLaunchGGL within a GPU task and the time reported by that is always greater than what legion_prof reports. Building with `-DFORCE_GPU_STREAM_SYNCHRONIZE` the times seem to be closer to what my manual timing code reports.

**Comment by eddy16112** [comment]
Looks like the issue is only with S3D. I have tested circuit and saxpy, and the GPU task timing reported by legion_prof looks fine in both cases.

**Comment by syamajala** [comment]
Below are some plots comparing various profiling methods. Manual timing was measured in the following way:
```
  hipStreamSynchronize(hipGetTaskStream());                                                                            
  struct timeval start;                                                                                                
  gettimeofday(&start, NULL);                                                                                          
  hipLaunchKernelGGL(gpu_conductivity, grid, block, 0, hipGetTaskStream(), temp_array, mole_frac_array,                
                                                 mole_avg_array,                                                       
                                                 nx*ny, nx, nz, nx*ny*nz,                                              
                                                 conductivity);                                                        
  hipStreamSynchronize(hipGetTaskStream());                                                                            
  struct timeval stop;                                                                                                 
  gettimeofday(&stop, NULL);                                                                                           
  unsigned long duration = 1000000 * (stop.tv_sec - start.tv_sec) + (stop.tv_usec - start.tv_usec);                    
  printf("{'task': 'Conductivity', 'time': %lu}\n", duration);   
```

Comparing manual sync/timing with rocprof and legion prof for ammonia:
http://sapling.stanford.edu/~seshu/bomb/ammonia/crusher_manual_sync.html

We see legion_prof < manual time < rocprof 

Comparing manual sync/timing with rocprof and legion prof for hept:
http://sapling.stanford.edu/~seshu/bomb/hept/crusher_manual_sync.html

We see rocprof < legion_prof < manual time

Comparing legion_prof and rocprof with no synchronization for ammonia:
http://sapling.stanford.edu/~seshu/bomb/ammonia/crusher_no_sync.html

We see legion_prof < rocprof

Comparing legion_prof and rocprof with no synchronization for hept:
http://sapling.stanford.edu/~seshu/bomb/hept/crusher_no_sync.html

We see legion_prof < rocprof

**Comment by streichler** [comment]
both of those `gettimeofday` calls are in the same legion task body, right?  I'm really surprised that you can get legion_prof < manual, since legion_prof numbers are based on timers realm samples before the task body is called and after the task body returns.  What kind of CPU does crusher use?

**Comment by syamajala** [comment]
Yes, it is all within the same legion task body. Crusher uses AMD EPYC 7A53.

**Comment by syamajala** [comment]
Using Realm:current_time_in_microseconds() I made a timeline plot.

![2022-03-24-094817_1918x2110_scrot](https://user-images.githubusercontent.com/45757/159968320-66c61267-65e0-499e-88bc-3e5a2865c82c.png)

We can see legion_prof is recording start times a little later than the manual timing code. 

![2022-03-24-094721_1918x2110_scrot](https://user-images.githubusercontent.com/45757/159968408-53274c1c-e1bd-4c1b-b0ca-07f0711f8207.png)

The rocprof start times seem to be significantly later.

**Comment by lightsighter** [comment]
Are the rocprof times all equally "later" or do they vary across measurements? At least from this picture it looks like they are all equally later, suggesting that the relative timing is accurate, but that precision is "off" by some amount relative to the manual and legion prof timings. If rocprof is all off by some constant amount that should be easy enough to account for, you just can't mix timings from different timers.

**Comment by syamajala** [comment]
Received an update from OLCF today that AMD has acknowledged there is a bug in rocprof:
https://docs.olcf.ornl.gov/systems/crusher_quick_start_guide.html#olcfdev-842-inconsistent-timing-with-rocprof-timestamp-on

I think @seemamirch has been looking at legion_prof so I'm going to assign this to her.

**Comment by syamajala** [comment]
I think this problem is still there on the latest legion.

**Comment by elliottslaughter** [comment]
Would it be possible to get a new comparison between Legion Prof, `Realm::current_time_in_microseconds()` and rocprof? Or is there another way to debug this?

**Comment by seemamirch** [comment]
I ran a couple of experiments on circuit
1.  Manual mode (similar to above) versus legion prof timings -> http://sapling.stanford.edu/~seemah/hip_profile/circuit_default.html
2. Manual mode versus legion prof timings with callbacks enabled (-ll:hip_callbacks) -> http://sapling.stanford.edu/~seemah/hip_profile/circuit_callback.html
The timings match closely in 2.

**Comment by syamajala** [comment]
This issue goes away with rocm 5.2.0. With rocm 5.1.0 you need `-hip:callbacks` when profiling.

One thing to note with rocprof is that you can't collect performance counters when doing timing measurements. You need to do 2 separate runs and also you need to do multiple launches of kernels before you start getting consistent timing measurements. See this issue for more details:
https://docs.olcf.ornl.gov/systems/crusher_quick_start_guide.html#olcfdev-842-inconsistent-timing-with-rocprof-timestamp-on

**Comment by syamajala** [comment]
They have a patch for the rocprof issue and it might be in the 5.3 release.
