### ISSUE TITLE
Post-Task Execution taking longer spuriously

### ISSUE THREAD

**Issue by bandokihiro** [StanfordLegion/legion#1219]
I have a [profile](http://sapling.stanford.edu/~bandokihiro/Profile02/legion_prof) in which there is something that I don't understand. Most Post-Task execution utility tasks last O(10) us but sometimes they peak at O(1) ms. It sometimes happen when one of the utility is busy with a ProfTask in which case I would understand this as profiling overhead. But this also happens when there doesn't seem to be something interfering with it. For example, this profile, node 1, t=32980 ms has this behavior. The name of the task is cut but this is because I am on a fairly old Legion.

**Comment by lightsighter** [comment]
I don't think this is unusual. We put a lot of pressure on malloc with lots of dynamic allocations and frees and occasionally malloc needs to update its data structures for managing the heap. It usually takes it a few ms to do this. We've observed this on lots of different machines. If you want to experiment try swapping out dlmalloc for tcmalloc and see if it changes your profiles at all.

**Comment by bandokihiro** [comment]
Thanks, I just wanted confirmation that this is not unusual.
