### ISSUE TITLE
Legion: Tasks not executing on GPU when using multiple ranks/node

### ISSUE THREAD

**Issue by syamajala** [StanfordLegion/legion#1225]
When using multiple ranks/node tasks are only executing on CPU and not on GPU on the latest control_replication. According to @bandokihiro something seems to have changed in commit 3847f0c7. 

Doing a bisection myself I also confirmed I am no longer able to run tasks on GPU when using multiple ranks/node after that commit. Running 1 rank/node works.

**Comment by lightsighter** [comment]
This is a duplicate of #1220. Read this first:

https://github.com/StanfordLegion/legion/issues/1220#issuecomment-1082221791

Then talk to @bandokihiro about what you want the right answer to be. You're both complaining that you want it the opposite way of the other.
