### ISSUE TITLE
Profiler fails in process_results

### ISSUE THREAD

**Issue by DocSohl** [StanfordLegion/legion#123]
When attempting to profile on any configuration, at the end of execution, Legion triggers:
```
legion/runtime/legion/runtime.cc:13595: void LegionRuntime::HighLevel::Internal::process_profiling_task(LegionRuntime::HighLevel::Processor, const void*, size_t): Assertion `profiler != __null' failed.
```

Perhaps in a similar issue, profiling results fail to properly name tasks, instead labeling them like:
"unnamed_variant_7"

**Comment by magnatelee** [comment]
Commit 4a87df4 should fix this issue.
