### ISSUE TITLE
Regent: arglen mismatch with gasnetex

### ISSUE THREAD

**Issue by syamajala** [StanfordLegion/legion#1238]
When running the etprf mechanism in S3D with gasnetex on Perlmutter using 1 node, 4 ranks I'm hitting this assertion at runtime:
```
assertion failed: arglen mismatch <CalcVolumeTask> (single task)
```
From the regent compiler:
https://github.com/StanfordLegion/legion/blob/control_replication/language/src/regent/codegen.t#L10787-L10789

Switching back to gasnet1 everything works fine. 

@elliottslaughter suspects task arguments are getting corrupted.

**Comment by streichler** [comment]
Can we dump the task argument blob that's triggering the assert and see how corrupted it looks?
The gasnetex network layer includes packet-level checksums by default, so most of the path is 
protected from most forms of corruption.

**Comment by syamajala** [comment]
When I started adding print statements to debug this it started working...

**Comment by syamajala** [comment]
Seems to be gone with latest legion. I am able to run the ammonia mechanism up to 128 nodes on Perlmutter and etprf has run up to 24 nodes so far, rest of runs are in the queue. Gonna close this for now.
