### ISSUE TITLE
Legion: circuit warning

### ISSUE THREAD

**Issue by ZamanLantra** [StanfordLegion/legion#1241]
When using Avon cluster (https://warwick.ac.uk/research/rtp/sc/hpc/#avon) to run legion circuit, I am getting the below warning. I have attached the profiles of a run with 4 nodes with 4 cpus per node and the slurm script.

branch: control_replication

_WARNING: A significant number of long latency messages were detected during this run meaning that the network was likely congested and could be causing a significant performance degradation. We detected 4162 messages that took longer than 1000.00us to run, representing 18.57% of 22407 total messages. The longest latency message required 15312.80us to execute. Please report this case to the Legion developers along with an accompanying Legion Prof profile so we can better understand why the network is so congested._

[prof24_0.gz](https://github.com/StanfordLegion/legion/files/8546565/prof24_0.gz)
[prof24_1.gz](https://github.com/StanfordLegion/legion/files/8546566/prof24_1.gz)
[prof24_2.gz](https://github.com/StanfordLegion/legion/files/8546567/prof24_2.gz)
[prof24_3.gz](https://github.com/StanfordLegion/legion/files/8546568/prof24_3.gz)
[circuit_slurm.txt](https://github.com/StanfordLegion/legion/files/8546570/circuit_slurm.txt)

**Comment by lightsighter** [comment]
Can you say what kind of interconnect network the machine has? Also which GASNet conduit are you using to run on the machine?

**Comment by ZamanLantra** [comment]
I am using ibv conduit

**Comment by lightsighter** [comment]
I don't see anything especially unusual in the profile. Would you mind running a few more iterations of the simulation and seeing if the percentage of "slow" messages decreases?

**Comment by ZamanLantra** [comment]
Yes the warning disappeared for higher number of loops. 
I ran with the same config (with 2, 5, 10, 20, 50 loops) and 4162(18.57%), 2474(12.6%), 2962(8.9%) messages took longer than 1000.00us for 2, 5, 10 loops but the warning disappeared for 20 and 50 loops.
Thank you for the support!

**Comment by lightsighter** [comment]
Right, I think there are just some start-up overheads there that are getting ironed out. You could also try improving the latency handling of some of these messages here by adding some additional utility processors for Legion `-ll:util <N>`. That may improve the start-up responsiveness by handling more messages in parallel. Overall, I don't think there's anything to worry about here and we were just getting bit by a small sampling size.

**Comment by ZamanLantra** [comment]
As suggested, I will change the number of utility processors and see (and will close this issue). Thank you for your time in analysing this
