### ISSUE TITLE
Parts of the installation process are inconsistent

### ISSUE THREAD

**Issue by waynee95** [StanfordLegion/legion#1242]
While installing regent I found a few inconsistencies in the installation process. 

1. The prerequisites listed on http://regent-lang.org/install/ seem to differ compared to the ones listed on https://github.com/StanfordLegion/legion/tree/stable/language#prerequisites

2. The `circuit.rg` file is not present anymore https://github.com/StanfordLegion/legion/tree/stable/language#running

**Comment by elliottslaughter** [comment]
Thanks for reporting this.

For now, stick to the instructions at http://regent-lang.org/install/ . The repo is out of date in this case.

The Circuit example can be found under `examples/circuit_sparse.rg`.

**Comment by elliottslaughter** [comment]
I've updated http://regent-lang.org/install/ and https://gitlab.com/StanfordLegion/legion/-/blob/master/language/README.md. Please check the new instructions and let me know if you have any issues.

It'll take a while for our GitHub mirror to sync from Gitlab (and `stable` won't update until our next release anyway), but your original link should update eventually.

**Comment by waynee95** [comment]
Following the updated instructions, everything worked fine and I can execute the examples! Thanks for clearing that up. I will close this.
