### ISSUE TITLE
Floating point exception in  DefaultMapper::decompose_index_space line 1080 on master 

### ISSUE THREAD

**Issue by gshipman** [StanfordLegion/legion#125]
I'll preface with "I'm not sure if this is a bug or my misuse of Legion" 

I'm hitting a divide by zero error in the default mapper in decompose_index_space. This is in a version of pennant which I've added hdf_attach operations to. 

Here is where the exception is: 
```
Process 94303 stopped
* thread #5: tid = 0x243e3d, 0x0000000106e64207 pennant`LegionRuntime::HighLevel::DefaultMapper::decompose_index_space(domain=0x00007fd50e0000c4, targets=size=0, splitting_factor=2, slices=size=0) + 551 at default_mapper.cc:1083, stop reason = EXC_ARITHMETIC (code=EXC_I386_DIV, subcode=0x0)
    frame #0: 0x0000000106e64207 pennant`LegionRuntime::HighLevel::DefaultMapper::decompose_index_space(domain=0x00007fd50e0000c4, targets=size=0, splitting_factor=2, slices=size=0) + 551 at default_mapper.cc:1083
   1080	          num_chunks = num_elmts;
   1081	        // Number of elements per chunk rounded up
   1082	        // which works because we know that rectangles are contiguous
-> 1083	        unsigned lower_bound = num_elmts/num_chunks;
   1084	        unsigned upper_bound = lower_bound+1;
   1085	        unsigned number_small = num_chunks - (num_elmts % num_chunks);
   1086	        unsigned index = 0;
```
A bit more debug info: 
```
(lldb) p num_elmts
(unsigned int) $1 = 4
(lldb) p num_chunks
(unsigned int) $2 = 0
(lldb) p splitting_factor 
(unsigned int) $7 = 2
(lldb) p targets
(const std::__1::vector<Realm::Processor, std::__1::allocator<Realm::Processor> >) $8 = size=0 {}
```
It seems odd that the the targets processor vector is empty. 

Note that this error only occurs when I'm attempting an index space launch of "write_launcher"  in pennant:src/legion_io.cc:264 
I'm using a 1D domain for the index launch with 4 domain points in it. The unstructured index space on which I am launching is partitioned with 4 colors by looping over the points in the index space and adding them to a Coloring using points.insert(ptr..)  see pennant:src/Mesh.cc:268. 

You can find my pennant code in the hierarchy-io branch here: 
https://github.com/gshipman/pennant-legion.git

**Comment by lightsighter** [comment]
Well the problem here is 'num_chunks==0', which suggests a bad mapper implementation.  Did you register this task as an I/O processor and forget to tell the runtime to create any I/O processors?

**Comment by gshipman** [comment]
I don't believe so. I am using map_locally = true in my select_task_options. Here is the mapper I'm using: 

```c++
include "legion.h"
#include "default_mapper.h"

using namespace std;
using namespace LegionRuntime::HighLevel;


MyMapper::MyMapper(
        Machine m,
        HighLevelRuntime *rt,
        Processor p)
        : DefaultMapper(m, rt, p) {}


bool MyMapper::map_task(Task *task)
{
    DefaultMapper::map_task(task);
    for (unsigned idx = 0; idx < task->regions.size(); idx++)
    {
        // use max blocking factor => SOA
        task->regions[idx].blocking_factor = task->regions[idx].max_blocking_factor;
    }
    // Report successful mapping results
    return true;
}

void MyMapper::select_task_options(LegionRuntime::HighLevel::Task *task) {
  task->map_locally = true;
  return; 
}
bool MyMapper::rank_copy_targets(
        const Mappable *mappable,
        LogicalRegion rebuild_region,
        const set<Memory> &current_instances,
        bool complete,
        size_t max_blocking_factor,
        set<Memory> &to_reuse,
        vector<Memory> &to_create,
        bool &create_one,
        size_t &blocking_factor)
{
    DefaultMapper::rank_copy_targets(mappable,
            rebuild_region,
            current_instances,
            complete,
            max_blocking_factor,
            to_reuse,
            to_create,
            create_one, blocking_factor);
    // use max blocking factor => SOA
    blocking_factor = max_blocking_factor;
    // return true => use composite instances
#ifdef SHARED_LOWLEVEL
    return false;
#else
    return true;
#endif

```

**Comment by lightsighter** [comment]
What kind of processor is the 'write_launcher' task registered to run on?

**Comment by magnatelee** [comment]
I looked at the code and found that you never registered the 'copy_values_task' to the runtime. After adding a call to function 'PersistentRegion_init' in main, I got this fix and hit another issue, which I guess is an application issue. 

Given this said, I still think the runtime (or at least the default mapper) should have told you that there is no task registered for the task id you requested to launch. I'll try to add some meaningful error messages.

**Comment by magnatelee** [comment]
Galen, could you try the fix that I mentioned above and see if the issue vanishes (and close this issue if so)?

**Comment by gshipman** [comment]
I'll give this a run tonight. I must have missed this in porting over the legion_io bits into the pennant code. Thanks so much for digging into this.

**Comment by magnatelee** [comment]
No problem. I pushed a fix for the mapper so that you can see the following error message instead of hitting some assertion in the runtime:

[0 - 70000018c000] {5}{default_mapper}: Mapper unable to find variant for task unnamed_task_4 (Task ID 4, UID 7959)
Assertion failed: (false), function select_task_variant, file /Users/wclee/Workspace/stanford/projects/legion//runtime/mappers/default_mapper.cc, line 452.

This basically tells you that you haven't registered any variants for Task ID 4.

**Comment by gshipman** [comment]
Closing this issue, my mistake for not registering the task. Thanks for the help.
