### ISSUE TITLE
HIP: GPU fills broken with multi-byte values on multi-dimensional regions

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1253]
HIP GPU fills appear to be broken with the following configuration:

 * Fill value of size > 1 byte
 * Region with > 1 dimension
 * May also require the region to be sparse

The symptom is that the fill is done as a 1-byte fill instead of the full value. So a fill with `0x12345678` will result in the region containing `0x78787878` (repeated) for a 4-byte fill.

Reproducer:

```lua
import "regent"

local format = require("std/format")

__demand(__cuda)
task gpu_dummy(r : region(ispace(int3d), int))
where reads writes(r) do end

task dummy(r : region(ispace(int3d), int))
where reads writes(r) do
  for e in r do
    format.println("dummy got: r[{}] = {}", e, r[e])
  end
end

task write_partitions(s : region(ispace(int1d), rect3d))
where reads writes(s) do
  s[0] = rect3d { int3d { 0, 0, 0 }, int3d { 1, 1, 1 } }
  s[1] = rect3d { int3d { 2, 2, 2 }, int3d { 3, 3, 3 } }
  s[2] = rect3d { int3d { 4, 4, 4 }, int3d { 5, 5, 5 } }
  s[3] = rect3d { int3d { 6, 6, 6 }, int3d { 7, 7, 7 } }
end

__demand(__inner)
task toplevel()
  var r = region(ispace(int3d, {8, 8, 8}), int)
  fill(r, 2)
  var s = region(ispace(int1d, 4), rect3d)
  write_partitions(s)
  var s_p = partition(equal, s, ispace(int1d, 2))
  var r_p = image(disjoint, r, s_p, s)
  __demand(__index_launch)
  for c in r_p.colors do
    gpu_dummy(r_p[c])
  end
  __demand(__index_launch)
  for c in r_p.colors do
    dummy(r_p[c])
  end
end
regentlib.start(toplevel)
```

**Comment by streichler** [comment]
@elliottslaughter are you able to test whether this works for CUDA?  Much of the HIP code is a copy/paste from the corresponding CUDA code.

**Comment by elliottslaughter** [comment]
The test that originally failed is one that passes on CUDA. However, I think it would be prudent to write a more comprehensive GPU fill test to make sure we're checking all the cases, since there may be some corner cases in CUDA too.

**Comment by seemamirch** [comment]
This doesn’t look right - https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/realm/hip/hip_module.cc#L881

**Comment by eddy16112** [comment]
> This doesn’t look right - https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/realm/hip/hip_module.cc#L881

This piece of code is no longer used for fill operations. The fill for this example is here https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/realm/hip/hip_internal.cc#L853-881 The code is slightly different from CUDA, because HIP does not have specific 2D memset for 16 and 32 bytes, so we fall back to use the 8 bytes 2D memset, but I did not see where is the problem. 

@elliottslaughter will the code work on NVIDIA GPU with `HIP_TARGET=CUDA`, if so, I can take a look at it because I do not have a access to AMD GPUs now.

**Comment by streichler** [comment]
The else case only seems to be using the first byte to fill: https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/realm/hip/hip_internal.cc#L875-879

**Comment by eddy16112** [comment]
> The else case only seems to be using the first byte to fill: https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/realm/hip/hip_internal.cc#L875-879

Right, I can not just fall back to use the 8 bytes 2D memset. Can I use the regular `cudaMemset2D(void * devPtr, size_t pitch, int value, size_t | width, size_t height)` to do the 32 bit memset? Looks like from the API, the value type is int.

**Comment by streichler** [comment]
Nope:
>value
>- Value to set for each byte of specified memory

You may need to do the thing that the CUDA path does for some 3d cases: do a 1D memset32 and then log(rows) 2d memcopies for the other rows (this is usually better than a separate memset32 for each row)

**Comment by eddy16112** [comment]
> You may need to do the thing that the CUDA path does for some 3d cases: do a 1D memset32 and then log(rows) 2d memcopies for the other rows (this is usually better than a separate memset32 for each row)
I think I can just fall back to use the default path for this case
https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/realm/hip/hip_internal.cc#L886

By the way, why the 32 bit 2D memset is only available in the driver API?

**Comment by elliottslaughter** [comment]
This has been fixed in master (thanks @eddy16112) and we now have a comprehensive test for GPU fills that covers sparse 1, 2 and 3-dimensional regions with 1, 2, 4 and 8 byte fields.
