### ISSUE TITLE
Regent: HIP crashes with ROCm 5.x

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1255]
I'm splitting this off from #1224 since the main support has now merged.

There are crashes that occur when upgrading to ROCm 5.x. Currently undebugged, but I did notice some similarities in the description of https://docs.amd.com/bundle/ROCm-Release-Notes-v5.1/page/Known_Issues_in_This_Release.html#d456e16 so this may potentially be an AMD issue. Probably not worth worrying about too much until ROCm 5.2.0 lands.

**Comment by elliottslaughter** [comment]
Unfortunately we may not be at the end of this. We saw [CI](https://code.olcf.ornl.gov/ci/csc335/dev/legion/-/pipelines/770) [failures](https://code.olcf.ornl.gov/ci/csc335/dev/legion/-/pipelines/771) that seems to indicate the problem is still there (or perhaps something new).

**Comment by elliottslaughter** [comment]
Reverting also caused a [failure](https://code.olcf.ornl.gov/ci/csc335/dev/legion/-/jobs/2722) so now I'm just confused.

**Comment by eddy16112** [comment]
Looks like the crash is inside the gasnet?

**Comment by elliottslaughter** [comment]
My understanding is that the errors in https://github.com/StanfordLegion/legion/issues/1255#issuecomment-1178271662 simply indicate that a rank failed; i.e., these are secondary failures.

I've been told that https://github.com/StanfordLegion/legion/issues/1255#issuecomment-1178347575 is more up in the air: the problem might be in GASNet or it could be another secondary failure like the first one.

**Comment by eddy16112** [comment]
Is the failure with ROCm 4 non-deterministic? I noticed the regent_cmake did not fail.

**Comment by elliottslaughter** [comment]
I'm not sure what happened, but our Make CI appears to be happy with ROCm 5.4.3, so I'm going to close this.
