### ISSUE TITLE
when DEBUG=0 and -DNDEBUG is passed, warnings (which are cast to errors) occur

### ISSUE THREAD

**Issue by tjcorona** [StanfordLegion/legion#126]
Not a critical issue, but for timing tests it will be important to build with release settings. Here are the warnings:

```
legion/runtime/legion/legion_ops.cc:8354:5: warning:
      control reaches end of non-void function [-Wreturn-type]
    }
    ^
```

```
legion/runtime/realm/timers.cc:135:9: warning:
      unused variable 'ret' [-Wunused-variable]
    int ret = pthread_key_create(&thread_timer_key,thread_timer_free);
        ^
```

**Comment by lightsighter** [comment]
Which branch is this on?  I don't see the line numbers aligning with either 'master' or the 'stable' branches.

**Comment by streichler** [comment]
I've cleaned up a whole pile of these in a0f5a8b61d03a1bb1f51e761d60559aafb5a60ac.  That said, we strongly discourage turning off all the asserts in the runtime code.
