### ISSUE TITLE
Specific GASNet version for Legion

### ISSUE THREAD

**Issue by JulienLoiseau** [StanfordLegion/legion#1272]
The current build system for Legion builds the `master` of GASNet for all versions of Legion. 
This is a problem for performance testing and reproductibility. 
A specific version of Legion should builds with a specific version of GASNet. 

Could we add support for this in the Legion's CMake? 

@streichler @pmccormick @opensdh

**Comment by elliottslaughter** [comment]
Are you referring to pinning the version of Legion's GASNet configuration repo (https://github.com/StanfordLegion/gasnet) or the version of GASNet?

Legion appears to support setting both of these.

 * Set the GASNet configuration repo to a specific commit ID: https://github.com/StanfordLegion/legion/blob/master/CMakeLists.txt#L445
 * Set the GASNet version: https://github.com/StanfordLegion/legion/blob/master/CMakeLists.txt#L449

If you're referring to building GASNet yourself (as opposed to using Legion's CMake to build GASNet automatically), you're already in control of what version to build.

**Comment by elliottslaughter** [comment]
Ok, so this is basically asking Legion to do the version pinning instead of asking the user to do it. I guess that's reasonable. It does mean managing the GASNet version in two places (once in StanfordLegion/gasnet and once in StanfordLegion/legion).

**Comment by elliottslaughter** [comment]
We pin the GASNet config commit in our CMake build. That then implies that we pin the default GASNet version. I think this is sufficient?
