### ISSUE TITLE
HTR failing on 64 nodes in Legion::Internal::SingleTaskTree::unpack_collective

### ISSUE THREAD

**Issue by ct-williams** [StanfordLegion/legion#1278]
I have been trying to run a 64-node simulation on Lassen using HTR and Legion commit 1a75d7b6ef4a515b78105a632c137123246ed1df, but I have been encountering the following assertion failure: ` void Legion::Deserializer::deserialize(T&) [with T = long unsigned int]: Assertion (index+sizeof(T)) <= total_bytes failed.` This issue seems only to occur for jobs run on a larger number of nodes, as this same setup runs without issue at smaller scale. Included below are backtraces collected when running HTR with `DEBUG=1`

[bt614.tar.gz](https://github.com/StanfordLegion/legion/files/8911312/bt614.tar.gz)

**Comment by lightsighter** [comment]
Can you run with `-lg:safe_ctrlrepl 1`? Also report the values of `index` and `total_bytes` from the assertion if you can.

**Comment by ct-williams** [comment]
I re-ran the case with `-lg:safe_ctrlrepl 1` and received the following error message: `error [67] LEGION ERROR: Invalid mapper output from invocation of 'map_task' on mapper prometeo_mapper. Mapper specified instance that does not meet region requirement 0 for task Add1DAveragesZ (ID 204717). The index space for the instance has insufficient space for the requested logical region. (from file LEGION_LASSEN/runtime/legion/legion_tasks.cc.3104)`

**Comment by lightsighter** [comment]
Did you just turn on `-lg:safe_mapper` also? @mariodirenzo for visibility.

**Comment by ct-williams** [comment]
As a quick update, I ran this same simulation on a smaller number of nodes (8), and the job also failed. However, when using the `-lg:inorder` flag, it runs without issue.

**Comment by lightsighter** [comment]
Did you also run with `-lg:safe_mapper` and `-lg:safe_ctrlrepl 1` on the smaller number of nodes? What are the values of `index` and `total_bytes` when it fails?

**Comment by ct-williams** [comment]
Here is a summary of some results I've obtained from varying the flags: 

**On 8 Nodes:**
Legion in release mode and with `CC_FLAGS="-g -O0"` ----> `prometeo_AirMix.exec: /g/g15/cwill/LEGION_LASSEN/runtime/realm/transfer/transfer.cc:1765: void Realm::TransferDomainIndexSpace<N, T>::count_fragments(Realm::RegionInstance, const std::vector<int>&, const std::vector<int>&, const std::vector<long unsigned int>&, std::vector<long unsigned int>&) const [with int N = 3; T = long long int]: Assertion layout_piece != 0' failed.`

Legion is release mode and with `CC_FLAGS="-g -O0`, with `-lg:inorder `----> No Error

Legion is release mode and with` CC_FLAGS="-g -O0"`  and with `-lg:safe_mapper -lg:safe_ctrlrepl 1` ---->  `[1 - 20006870f8b0]  409.203824 {5}{runtime}: [error 67] LEGION ERROR: Invalid mapper output from invocation of 'map_task' on mapper prometeo_mapper. Mapper specified instance that does not meet region requirement 0 for task Add1DAveragesZ (ID 19069). The index space for the instance has insufficient space for the requested logical region. (from file /g/g15/cwill/LEGION_LASSEN/runtime/legion/legion_tasks.cc:3104)`

**On 64 Nodes:**
Legion is release mode and with `CC_FLAGS="-g -O0"` with `-lg:inorder` ----> No Error

**Comment by lightsighter** [comment]
This error: `Assertion layout_piece != 0' failed.` is a direct consequence of this error: `The index space for the instance has insufficient space for the requested logical region.` it's just that we don't do the checks for the bad mapper output in release mode and without the `-lg:safe_mapper` flag, so you don't get a nice error message, but instead you get the error message from Realm when it tries to do the copy. I'm very confident that this is an actual issue with the Prometo mapper that @mariodirenzo should look at.

Are you unable to reproduce the original issue with the deserialization?

**Comment by mariodirenzo** [comment]
I've been trying to reproduce the mapper error at a lower scale without success.
Moreover, I am confident that the mapper is trying to map the region requirement on a region that should be large enough to cover the index space of the region requirement.
Considering that the error disappears when the code is executed with `-lg:inorder` is there any chance that the task is executed ahead of time when the dependent partitioning work that determines the region requirement 0 is not done yet?

**Comment by lightsighter** [comment]
The more likely cause is a race between your mapper finishing the mapping of the task and and the garbage collector reclaiming the instance. You have to make sure you acquire all the instances for the mapping of a task before returning from the `map_task` mapper call, otherwise the instances might be collected by some other task mapping in parallel. It's entirely possible that the reason there is not enough space is because the instance has been reclaimed.

**Comment by lightsighter** [comment]
I'm also pretty confident that the error is real, because Realm is detecting exactly the same thing when it goes to do the copy to the instance later. Both Legion and Realm have done independent analyses and come to the same conclusion.

**Comment by mariodirenzo** [comment]
The implementation of `map_task ` that we are currently using is the one in the default mapper, therefore, if this check is implemented in that mapper, we are already checking for the validity of the instance.
The current logic in the mapper is to create a single instance that lasts for the entire calculation and that covers all the region requirements. This instance is never garbage collected during the calculation.
I also think that @ct-williams (correct me if I am wrong) is encountering the issue during the initialisation, which makes the garbage collection hypothesis less luckily to happen.

**Comment by lightsighter** [comment]
Another possibility is that out-of-order mapping without `-lg:inorder` is causing your mapper to create different sets of instances with different shapes depending on the order that tasks map, and some instance gets made in the `-lg:inorder` case is big enough, but because of out-of-order mapping without `-lg:inorder` then you never end up making the larger instance. I'd actually bet that this is the most likely scenario.

> The implementation of map_task that we are currently using is the one in the default mapper, therefore, if this check is implemented in that mapper, we are already checking for the validity of the instance.

This check is implemented in Legion. It's entirely possible there is a bug in the default mapper too.

> covers all the region requirements.

I'm betting that the logic that determines "all of the region requirements" is not right.

**Comment by mariodirenzo** [comment]
@ct-williams has given me a 4 nodes setup that should reproduce the issue. I'll try it on sapling and let you know what happens

**Comment by lightsighter** [comment]
Let's start by seeing if we can get a detailed Legion Spy log of a failing run and see if it validates or not.

**Comment by mariodirenzo** [comment]
The legion spy logs produced by a failing execution pass the logical and physical analysis.
However, I have noticed that inserting execution fences in between the operations that produce the "bad" partition prevents reproducing the error. I am still working on narrowing down the minimum number of fences needed to obtain the correct subregions

**Comment by lightsighter** [comment]
Can you attach the logs here just so we can see what the program is doing?

> However, I have noticed that inserting execution fences in between the operations that produce the "bad" partition prevents reproducing the error. 

I suspect a Realm bug, and separating out the different dependent partitioning operations prevents Realm from seeing a bunch of dependent partitioning operations all at the same time and prevents the bug from manifesting.
