### ISSUE TITLE
Request to make Realm startup printf into a debug or log message

### ISSUE THREAD

**Issue by abpoms** [StanfordLegion/legion#128]
On startup of Legion (and thus Realm), there is currently an unavoidable printf related to GASNet pinned memory. Would it be possible to make this printf into a log or debug message so that it can be optionally toggled?

The printf is here:
https://github.com/StanfordLegion/legion/blob/master/runtime/activemsg.cc#L2117-L2121

I'd submit a PR but I'm not sure what method you all would like to use to control it.

**Comment by streichler** [comment]
Yeah, I'll take care of this.  It should go through the logging interface, but I'll need to make sure the interface has been configured by this point.

**Comment by abpoms** [comment]
Yeah, was unsure if the logging infrastructure was set up at that point. Thanks!

**Comment by streichler** [comment]
Turns out it is, so it's an easy fix (4ffdb3f94b33fd42da3015de0d7b00cad5555746).
