### ISSUE TITLE
Scaling error has wrong text

### ISSUE THREAD

**Issue by DocSohl** [StanfordLegion/legion#129]
When scaling a Legion application to 2048 nodes, the following error is encountered:
`ERROR: Launched 2048 nodes, but runtime is configured for at most 1024 nodes. Update the 'MAX_NUM_NODES' macro in legion_types.h`

However, the MAX_NUM_NODES macro appears to be in [legion_config.h](https://github.com/StanfordLegion/legion/blob/master/runtime/legion/legion_config.h#L51) instead.

**Comment by streichler** [comment]
Should be fixed with 4c8c490d337076fb486eb3875bf6adc1f8222d4a.
