### ISSUE TITLE
Regent: Cross product returning incorrect subregions in leaf task

### ISSUE THREAD

**Issue by syamajala** [StanfordLegion/legion#1291]
I'm seeing the following when using nested partitions in Regent:

```
INIT: RANK COLOR: 0 0 0 SUBRANK COLOR: 0 Lo: 0 0 0 Hi: 63 63 31 Vol: 131072
INIT: RANK COLOR: 0 0 0 SUBRANK COLOR: 1 Lo: 0 0 32 Hi: 63 63 63 Vol: 131072
LEAF COLOR: 0 0 0 0 Lo: 0 0 0 Hi: 1 63 63
LEAF COLOR: 0 0 0 1 Lo: 62 0 0 Hi: 63 63 63
```

The leaf task seems to be getting launched over a different set of subregions than what the init partition task creating the nested partition returns. 

There is a reproducer here: /scratch2/seshu/linalg_test/test3.rg

First: `source /scratch2/seshu/linalg_test/env.sh`
then run: `regent.py test3.rg -ll:cpu 2 -logfile run_%.log`

Note: requires a regent built with MAX_DIM=4. 

There is a legion_spy log file here: `/scratch2/seshu/linalg_test/run_0.log` and the region tree is available here: `/scratch2/seshu/linalg_test/trees.txt`

**Comment by elliottslaughter** [comment]
This should (hopefully) be fixed in master; there was an issue in getting the correct color for the imported cross products.

**Comment by syamajala** [comment]
This is fixed.
