### ISSUE TITLE
Automated C++ formatting in Realm

### ISSUE THREAD

**Issue by apryakhin** [StanfordLegion/legion#1293]
Filing a Github issue based on our offline discussion with @streichler.

Today, C++ in Realm has a specific coding style which is maintained manually. It does not go though any automated formatting tool such as clang-format. As the number of contributors grow, we need to find a way to standardize the C++ format across the Realm codebase. It should help us to maintain its quality bar...readability, consistency..etc

The main goals are:
- Make C++ style to be consistent
- Make C++ style to be maintained automatically
- Make C++ style to be verified automatically through the CI for every PR

As the first step, I plan to create a separate Legion branch with the suggested C++ style (based on the clang-format file). I believe it will go through several iterations based on the community feedback until we reach some consensus. The next step will consist of getting the automation done, making sure there are no conflicts between the long-living branches.

**Comment by elliottslaughter** [comment]
There will be conflicts, but those can be resolved automatically if you're willing to use git filter-branch. I used this when Terra switched to auto-formatting and it worked well.

(Note: I am suggesting this for Realm branches only, not ones with Legion changes only, such as `control_replication`. I think the technique should be feasible to do on a branch by branch basis.)

Let me know if you want any more details and I'd be happy to share what I know.

**Comment by lightsighter** [comment]
I think we're going to want to have different style files for the Legion and Realm directories. I can make the style file for Legion based on the standards that I'd like to see in the Legion repo, but I have no interest in forcing my choices on the Realm code.

**Comment by elliottslaughter** [comment]
We've had automated formatting of Realm for a while now.
