### ISSUE TITLE
HIP: debug printfs in Realm module

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1294]
E.g.: https://gitlab.com/StanfordLegion/legion/-/blob/02e6f81bd9605bed64c7d58e1a3c5614012307e3/runtime/realm/hip/hip_internal.cc#L953

Just want to check with @eddy16112 to make sure these can be removed.

**Comment by eddy16112** [comment]
Yes, they can be removed. I believe there are some more printfs. I will push a fix to remove them.

**Comment by eddy16112** [comment]
I removed all the printfs in the hip module, and also removed the experimental dlopen code that I implemented before, here is the commits https://gitlab.com/StanfordLegion/legion/-/commits/hipcleanup
@elliottslaughter let me know if there are any other cleanups needed.

**Comment by elliottslaughter** [comment]
Looks good to me, thanks.

**Comment by eddy16112** [comment]
I have pushed the changes to the master branch.

**Comment by elliottslaughter** [comment]
Thanks!
