### ISSUE TITLE
Reductions missing close

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#130]
I'm seeing a bug which I'm fairly sure is a missing copy or close op when doing a reduction to a disjoint partition followed by a read to an aliased partition. I've got a test case where the only variable is the privilege used (RW or reduce), and when I use reductions, one of the variables clearly comes out zero.

The test below demonstrates this. You can use the `USE_REDUCTIONS` environment variable to control which privilege to use:

    # on master branch
    USE_REDUCTIONS=0 ./regent.py tests/regent/run_pass/region_reduce_aliased.rg
    USE_REDUCTIONS=1 ./regent.py tests/regent/run_pass/region_reduce_aliased.rg

Test case source: [tests/regent/run_pass/region_reduce_aliased.rg](https://github.com/StanfordLegion/legion/blob/master/language/tests/regent/run_pass/region_reduce_aliased.rg)

I'm attaching output and Legion Spy logs from correct (RW) and incorrect (reduce) runs. Notably, Legion Spy reports mapping errors in the reduce case (and no errors in the RW case):

    ERROR: Failed to compute mapping dependence between index 0 of inc_ba (ID: 4) and index 2 of avg_ac (ID: 5) (type: true)
      First Requirement:
        Logical Partition Requirement (1,1,1)
          Fields: 101
        Privilege: REDUCE with Reduction Op 103
        Coherence: EXCLUSIVE
      Second Requirement:
        Logical Partition Requirement (2,1,1)
          Fields: 101
        Privilege: READ-ONLY
        Coherence: EXCLUSIVE

Output RW (correct): [out_rw.txt](https://github.com/StanfordLegion/legion/files/155923/out_rw.txt)
Output reduce (incorrect): [out_red.txt](https://github.com/StanfordLegion/legion/files/155924/out_red.txt)
Spy RW (correct): [spy_rw.txt](https://github.com/StanfordLegion/legion/files/155925/spy_rw.txt)
Spy reduce (incorrect): [spy_red.txt](https://github.com/StanfordLegion/legion/files/155926/spy_red.txt)

**Comment by lightsighter** [comment]
@magnatelee Pinging you just so you are aware of it.  You might want to make sure that legion spy is reporting the right error and that everything aligns with your formal semantics.

**Comment by magnatelee** [comment]
The logical analysis in Legion Spy hasn't been changed (I haven't pushed my
version), so it is not related to what I'm doing now. Given that said, I'll
double check my version.
