### ISSUE TITLE
Error compiling Legion on Lassen (master branch)

### ISSUE THREAD

**Issue by ct-williams** [StanfordLegion/legion#1303]
When trying to compile Legion (master branch) on Lassen, I am encountering the following issue: 

`error: 'template<unsigned int MAX> void Legion::Deserializer::deserialize(PPCBitMask<MAX>&)' cannot be overloaded` 
`inline void deserialize(PPCTLBitMask<MAX> &mask);`

Both control_replication and stable are compiling without any errors, though.

**Comment by lightsighter** [comment]
Please pull and try again.

**Comment by ct-williams** [comment]
It now compiles without issue - thanks for the help!
