### ISSUE TITLE
Default mapper overwrites task SpecializedConstraints

### ISSUE THREAD

**Issue by mariodirenzo** [StanfordLegion/legion#1313]
The current behavior of the default mapper is to overwrite `SpecializedConstraint` that might be registered with some region requirements of a task.
In particular, the calls https://gitlab.com/StanfordLegion/legion/-/blob/control_replication/runtime/mappers/default_mapper.cc#L1905 and https://gitlab.com/StanfordLegion/legion/-/blob/control_replication/runtime/mappers/default_mapper.cc#L1926 take the `LayoutConstraintSet` that is associated with a task and, unless it has a specific set of fields, overwrite its  `SpecializedConstraint` with a `SpecializedConstraint()` at https://gitlab.com/StanfordLegion/legion/-/blob/control_replication/runtime/mappers/default_mapper.cc#L2184.

If a user has specified anything other than a standard affine layout constraint, this behavior will generate an unsafe mapping decision that is going to be captured by `-lg:safe_mapper`.

**Comment by elliottslaughter** [comment]
@mariodirenzo Can you try #1248? If that addresses your use case, we could go ahead and take that.

**Comment by mariodirenzo** [comment]
I actually have a very similar patch that works for me. I think that merging either #1248 or the following will fix the issue.

```
diff --git a/runtime/mappers/default_mapper.cc b/runtime/mappers/default_mapper.cc
index 23fcd73..4aff7a0 100644
--- a/runtime/mappers/default_mapper.cc
+++ b/runtime/mappers/default_mapper.cc
@@ -2173,16 +2173,20 @@ namespace Legion {
       {
         // Make reduction fold instances
         constraints.add_constraint(SpecializedConstraint(
-                            LEGION_AFFINE_REDUCTION_SPECIALIZE, req.redop))
-          .add_constraint(MemoryConstraint(target_memory.kind()));
+                            LEGION_AFFINE_REDUCTION_SPECIALIZE, req.redop));
+        if (not constraints.memory_constraint.has_kind)
+          constraints.add_constraint(MemoryConstraint(target_memory.kind()));
       }
       else
       {
         // Our base default mapper will try to make instances of containing
         // all fields (in any order) laid out in SOA format to encourage
         // maximum re-use by any tasks which use subsets of the fields
-        constraints.add_constraint(SpecializedConstraint())
-          .add_constraint(MemoryConstraint(target_memory.kind()));
+        if (constraints.specialized_constraint.kind == LEGION_NO_SPECIALIZE)
+          constraints.add_constraint(SpecializedConstraint());
+
+        if (not constraints.memory_constraint.has_kind)
+          constraints.add_constraint(MemoryConstraint(target_memory.kind()));

         if (constraints.field_constraint.field_set.size() == 0)
         {
```

**Comment by elliottslaughter** [comment]
Thanks, merged!
