### ISSUE TITLE
Multi-dimensional equal partitioning splits only 1d

### ISSUE THREAD

**Issue by ClProsser** [StanfordLegion/legion#1325]
I'm currently trying to create a parallel version of a 3d stencil using Legion and C++. Based on my tests, `runtime->create_equal_partition` only splits on the first dimension, even if the color space is multi-dimensional. 

**Detailed description**:
I'm trying to use `runtime->create_equal_partition` to split my grid into subregions - each axis may have a different amount of subregions. Thus, based on the Partitioning tutorial, I first create 3d typed index spaces for the 3d grid and 3d color bounds, obtain a typed logical region for the grid, create the typed partitioning using `runtime->create_equal_partition` and obtain a typed logical partition. Once this is done, I start tasks using an `IndexLauncher`, which simply prints its region bounds:

```c++
void print_task(const Task *task,
                const std::vector<PhysicalRegion> &regions,
                Context ctx, Runtime *runtime)
{
    Rect<3> boundaries = runtime->get_index_space_domain(
        ctx, regions[0].get_logical_region().get_index_space());

    std::ostringstream oss;
    oss << "x-axis: [LO: " << boundaries.lo[0] << " | HI: " << boundaries.hi[0] << " ], ";
    oss << "y-axis: [LO: " << boundaries.lo[1] << " | HI: " << boundaries.hi[1] << " ], ";
    oss << "z-axis: [LO: " << boundaries.lo[2] << " | HI: " << boundaries.hi[2] << " ]";
    oss << std::endl;

    std::cout << "Task " << task->get_task_name() << " executing with region: " << oss.str();
}
```

For debugging purposes, I print the grid index space (`grid_is`) and color index space (`color_is`) domains.

Assuming that I want two subregions on the z-axis, my `color_is` domain is: `<0,0,0>..<0,0,1>,dense`. The output of the program is:
```
> LEGION_BACKTRACE=1 LEGION_FREEZE_ON_ERROR=1 ./equal_partitioning_bug -lg:partcheck -lg:spy -logfile spy_%.log
grid_is DOMAIN: IS:<0,0,0>..<5,2,2>,dense
color_is DOMAIN: IS:<0,0,0>..<0,0,1>,dense
color_ip COLOR SPACE: <0,0,4294967296>..<0,4294968065,140584050024640>,7fdc1ca4f560
Task print_task executing with region:x-axis: [LO: 0 | HI: 2 ], y-axis: [LO: 0 | HI: 2 ], z-axis: [LO: 0 | HI: 2 ]
Task print_task executing with region:x-axis: [LO: 3 | HI: 5 ], y-axis: [LO: 0 | HI: 2 ], z-axis: [LO: 0 | HI: 2 ]
```
[spy_0.log](https://github.com/StanfordLegion/legion/files/9562820/spy_0.log)
Which states that the partitioning happened, but on the x-axis, not on the z-axis.

Increasing the total number of subregions such that it exceeds the number of layers (i.e. indices on the x-axis) but not the number of subregions axis-wise, results in the right amount of tasks launched. Some tasks receive regions that have indices with `lo > hi`. This probably happens as this function (wrongly) partitions only on the x-axis. 

```
> LEGION_BACKTRACE=1 LEGION_FREEZE_ON_ERROR=1 ./equal_partitioning_bug -lg:partcheck -lg:spy -logfile spy_%.log
grid_is DOMAIN: IS:<0,0,0>..<5,2,2>,dense
color_is DOMAIN: IS:<0,0,0>..<0,2,2>,dense
color_ip COLOR SPACE: <0,0,8589934594>..<0,4294968065,140401536110784>,7fb19df7f560
Task print_task executing with region: x-axis: [LO: 0 | HI: -1 ], y-axis: [LO: 0 | HI: 2 ], z-axis: [LO: 0 | HI: 2 ]
Task print_task executing with region: x-axis: [LO: 2 | HI: 1 ], y-axis: [LO: 0 | HI: 2 ], z-axis: [LO: 0 | HI: 2 ]
Task print_task executing with region: x-axis: [LO: 4 | HI: 3 ], y-axis: [LO: 0 | HI: 2 ], z-axis: [LO: 0 | HI: 2 ]
Task print_task executing with region: x-axis: [LO: 0 | HI: 0 ], y-axis: [LO: 0 | HI: 2 ], z-axis: [LO: 0 | HI: 2 ]
Task print_task executing with region: x-axis: [LO: 1 | HI: 1 ], y-axis: [LO: 0 | HI: 2 ], z-axis: [LO: 0 | HI: 2 ]
Task print_task executing with region: x-axis: [LO: 2 | HI: 2 ], y-axis: [LO: 0 | HI: 2 ], z-axis: [LO: 0 | HI: 2 ]
Task print_task executing with region: x-axis: [LO: 3 | HI: 3 ], y-axis: [LO: 0 | HI: 2 ], z-axis: [LO: 0 | HI: 2 ]
Task print_task executing with region: x-axis: [LO: 4 | HI: 4 ], y-axis: [LO: 0 | HI: 2 ], z-axis: [LO: 0 | HI: 2 ]
Task print_task executing with region: x-axis: [LO: 5 | HI: 5 ], y-axis: [LO: 0 | HI: 2 ], z-axis: [LO: 0 | HI: 2 ]
```
[spy_0.log](https://github.com/StanfordLegion/legion/files/9562886/spy_0.log)

Did I make a mistake / is `runtime->create_equal_partition` only intended for partitioning on one axis? 

To solve this problem, I used `runtime->create_partition_by_domain` and created my domain explicitly. 

**Expected behavior**: If the provided color index space is multi-dimensional, `runtime->create_equal_partition` should split axis-wise. 

**Reproduction**: I created a simplified version of my program to reproduce the unexpected behavior. 

[equal_partitioning_bug.zip](https://github.com/StanfordLegion/legion/files/9562912/equal_partitioning_bug.zip)

Would be great if you could help me with this finding.
Thanks :)

**Comment by streichler** [comment]
The `create_equal_partitions` call is for when you just need a certain number of subregions and do not
really care exactly how they're shaped.  For multi-dimensional regions, there's no precise definition of
"equal" that would make everybody happy, so Legion and Realm choose a definition with a relatively
easy/fast implementation (i.e. splitting as equally as possible along only the first dimension).

If you have a particular shape in mind for your multi-dimensional subregions, the call you probably want
is `create_partition_by_blockify`: https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/legion.h#L5046-5068
Using `create_partition_by_domain` can work as well, but it's more work for you and then more work for
Legion to verify the correctness/completeness/disjointness of the resulting partition.

**Comment by ClProsser** [comment]
Hi @streichler,

thanks for your answer; this clarifies a lot. It would be great if this limitation could be added to the documentation (i.e. that `runtime->create_equal_partition` splits only along the first dimension), as this was pretty misleading for me and probably for other users as well. 

I tried to use `runtime->create_partition_by_blockify` prior to my implementation using `runtime->create_partition_by_domain`, but this did not work at all (either the resulting blocks didn't have the provided shape or the region bounds did not include all indices). However, I can't exclude mistakes made on my side (as sadly only a few examples using `runtime->create_partition_by_blockify` exist). 

Equal partitioning among multiple axes would probably be a good feature, especially if one considers physics simulations

**Comment by lightsighter** [comment]
> It would be great if this limitation could be added to the documentation

I added a comment to the doxygen for this method here: https://gitlab.com/StanfordLegion/legion/-/commit/744874cf50793f6cd1f49048229705bfec224b4a

> However, I can't exclude mistakes made on my side (as sadly only a few examples using runtime->create_partition_by_blockify exist).

I recommend `create_partition_by_restriction` instead as it is the more general form of `create_partition_by_blockify`, The `create_partition_by_blockify` call is really just a special case for backwards compatibility of a bunch of older applications and compilers. Is the documentation for `create_partition_by_restriction` clear? If not what would questions do you have and how would you improve it?

**Comment by ClProsser** [comment]
Hi @lightsighter,
> I added a comment to the doxygen for this method here: [...]

Thank you
> The `create_partition_by_blockify` call is really just a special case for backwards compatibility of a bunch of older applications and compilers

Good to know that this is the intention, maybe this could be added to the docs as well (to prevent new applications to use this function).   

> Is the documentation for `create_partition_by_restriction` clear? 

How would you implement a multi-dimensional equal partitioning given the number of subregions per axis? I tried to calculate the block size (using ceiling, which implies that the last block could have fewer points). This is similar to the multiple partitions tutorial but for 3d. 
*Note*: the code assumes that grid_start is (0,0,0).  
```c++
COORD_T tileSizeX = (grid_end[0] + num_subregions[0] - 1) / num_subregions[0];
COORD_T tileSizeY = (grid_end[1] + num_subregions[1] - 1) / num_subregions[1];
COORD_T tileSizeZ = (grid_end[2] + num_subregions[2] - 1) / num_subregions[2];
```
Then, I constructed the transform matrix and the extent (the padding should be 0 on each axis). Here, I probably made the mistake yielding my questionable output. 
```
Transform<3,3, COORD_T> transform;
transform[0][0] = tileSizeX;
transform[1][1] = tileSizeY;
transform[2][2] = tileSizeZ;
Rect<3> extent(Point<3, COORD_T>{0,0,0}, Point<3, COORD_T>{tileSizeX, tileSizeY, tileSizeZ});
```
Finally, I called the function like this: `runtime->create_partition_by_restriction<3, 3, COORD_T>(ctx, grid_is, color_is, transform, extent)`. This results in output like this (the print function is equal to my initially provided example):
```
Task print_task executing with region: x-axis: [LO: 10 | HI: 5 ], y-axis: [LO: 1 | HI: 2 ], z-axis: [LO: 140381560245907 | HI: 2 ]
Task print_task executing with region: x-axis: [LO: 13 | HI: 5 ], y-axis: [LO: 140380804720641 | HI: 2 ], z-axis: [LO: 280762364964499 | HI: 2 ]
Task print_task executing with region: x-axis: [LO: 140381561673376 | HI: 5 ], y-axis: [LO: 0 | HI: 1 ], z-axis: [LO: 1 | HI: 2 ]
Task print_task executing with region: x-axis: [LO: 140381561673379 | HI: 5 ], y-axis: [LO: 140380804720640 | HI: 2 ], z-axis: [LO: 140380804718593 | HI: 2 ]
Task print_task executing with region: x-axis: [LO: 140381561673386 | HI: 5 ], y-axis: [LO: 1 | HI: 2 ], z-axis: [LO: 140381560245908 | HI: 2 ]
Task print_task executing with region: x-axis: [LO: 140381561673389 | HI: 5 ], y-axis: [LO: 140380804720641 | HI: 2 ], z-axis: [LO: 280762364964500 | HI: 2 
```
>  [...] how would you improve it?

A tutorial including 3d partitioning would be great - sadly most tutorials and examples use 1d only. 

Thanks for your help.

**Comment by lightsighter** [comment]
> Good to know that this is the intention, maybe this could be added to the docs as well (to prevent new applications to use this function).

It's already there ;)
https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/legion.h#L5206-5209

> How would you implement a multi-dimensional equal partitioning given the number of subregions per axis? I tried to calculate the block size (using ceiling, which implies that the last block could have fewer points). This is similar to the multiple partitions tutorial but for 3d.

```
Transform<3,3, COORD_T> transform;
transform[0][0] = tileSizeX;
transform[1][1] = tileSizeY;
transform[2][2] = tileSizeZ;
Rect<3> extent(Point<3, COORD_T>{0,0,0}, Point<3, COORD_T>{tileSizeX, tileSizeY, tileSizeZ});
```

This code looks right with one exception. The `Transform` type is imported directly from Realm:
https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/legion/legion_domain.h
and the Realm type has no default constructor, so your off-diagonal elements are not being initialized. Valgrind will almost certainly complain about reads of uninitialized data, so the problem is most likely just garbage data being passed into the runtime.

> A tutorial including 3d partitioning would be great - sadly most tutorials and examples use 1d only.

Note general 3d partitioning is hard because it is not obvious how to determine for the number of subregions you want in each of the x, y, and z dimensions given a total number of subregions to create. If the answer is for the user to give us the number of subregions in each dimension, we can do that, because that is just the `partition_by_blockify` call.

**Comment by ClProsser** [comment]
Thanks for your answer.
> [...] and the Realm type has no default constructor, so your off-diagonal elements are not being initialized

I already assumed this (I did not confirm this using Valgrind or similar) - initializing off-diagonal elements with value 0 (or 1) results in non disjoint partition errors:

```
grid_is DOMAIN: IS:<0,0,0>..<5,2,2>,dense
color_is DOMAIN: IS:<0,0,0>..<1,1,1>,dense
color_ip COLOR SPACE: <0,0,0>..<1,1,1>
[0 - 7fd38231a800]    0.088006 {5}{runtime}: [error 304] LEGION ERROR: Non disjoint partition selected for writing region requirement 0 of task print_task.  All projection partitions which are not read-only and not reduce must be disjoint (from file /mnt/e/legion/runtime/legion/legion_tasks.cc:1443)
For more information see:
http://legion.stanford.edu/messages/error_code.html#error_code_304
```

Do you see any other reasons why this is wrong?
Here is a slightly modified version of my initial example (apparently, the name is not accurate (anymore)):
[equal_partitioning_bug.zip](https://github.com/StanfordLegion/legion/files/9612004/equal_partitioning_bug.zip)


> If the answer is for the user to give us the number of subregions in each dimension, we can do that, because that is just the partition_by_blockify call

Thanks for this note. I tried to use `create_partition_by_blockify` earlier but failed. This was probably caused by the fact that I assumed that the `blocking_factor` equals the number of subregions per axis. I just noticed that this assumption was wrong, as the blocking factor equals the maximum blocksize per axis. 

For completion, using this snippet works (i.e. it creates a multi-dimensional equal partitioning, given the number of subregions per axis):
```c++
COORD_T tileSizeX = (grid_end[0] + num_subregions[0] - 1) / num_subregions[0];
COORD_T tileSizeY = (grid_end[1] + num_subregions[1] - 1) / num_subregions[1];
COORD_T tileSizeZ = (grid_end[2] + num_subregions[2] - 1) / num_subregions[2];
    
runtime->create_partition_by_blockify<3, COORD_T>(ctx, grid_is, Point<3, COORD_T>{tileSizeX, tileSizeY, tileSizeZ});
```

I'm still curious what causes the errors with `runtime->create_partition_by_restriction`, would be great if you have another hint.

**Comment by lightsighter** [comment]
> Do you see any other reasons why this is wrong?

Legion Spy is always helpful with these kinds of problems. Attached is an index space tree showing the partition that you created. Very clearly you can see that subspaces 5 and 7 and bounds and therefore the partition is aliased. You're not allowed to do an index space task launch where the point tasks use overlapping subregions with writing privileges because that implies that they would need to be executed in a serial manner, but there is no obvious serial manner from an index space task launch where all the tasks are supposed to be non-interfering. (Note: there is an exception for this if you implement an `inverse` method on the projection functor that you use to tell the runtime the ordering of the point tasks, but that is not the behavior that you want here I think.)

[index_space_graph.pdf](https://github.com/StanfordLegion/legion/files/9644766/index_space_graph.pdf)

Looking at your code, I'm pretty sure you want zeros on your non-diagonal elements, and not ones. Also you need to make your `extent` inclusive and not exclusive. The path below computes a tiled partition that works for me.

```
--- equal_partitioning_bug.cc   2022-09-21 02:24:14.000000000 -0700
+++ equal_partitioning_bug_fixes.cc     2022-09-26 02:11:49.000000000 -0700
@@ -33,18 +33,18 @@
 
     Transform<3, 3, COORD_T> transform;
     transform[0][0] = tileSizeX;
-    transform[0][1] = 1;
-    transform[0][2] = 1;
+    transform[0][1] = 0;
+    transform[0][2] = 0;
 
-    transform[1][0] = 1;
+    transform[1][0] = 0;
     transform[1][1] = tileSizeY;
-    transform[1][2] = 1;
+    transform[1][2] = 0;
 
-    transform[2][0] = 1;
-    transform[2][1] = 1;
+    transform[2][0] = 0;
+    transform[2][1] = 0;
     transform[2][2] = tileSizeZ;
 
-    Rect<3> extent(Point<3, COORD_T>{0, 0, 0}, Point<3, COORD_T>{tileSizeX, tileSizeY, tileSizeZ});
+    Rect<3> extent(Point<3, COORD_T>{0, 0, 0}, Point<3, COORD_T>{tileSizeX-1, tileSizeY-1, tileSizeZ-1});
 
     return runtime->create_partition_by_restriction<3, 3, COORD_T>(ctx, grid_is, color_is, transform, extent);
 }
```

**Comment by ClProsser** [comment]
> Legion Spy is always helpful with these kinds of problems. Attached is an index space tree showing the partition that you created.

While I used Legion Spy in this case, I haven't checked every available flag yet. Thanks for your hint, your graph (which was generated with the `-r` flag) is definitely useful and clearly shows the overlaps. 

The code you provided with zeros on off-diagonal points and an inclusive extent solves my problem. The result is the one expected, i.e. the same as with `create_partition_by_blockify`. 

Thanks for your time :)
