### ISSUE TITLE
CMake: Compilation error of legion_redop.cu with -std=c++17

### ISSUE THREAD

**Issue by eddy16112** [StanfordLegion/legion#1356]
When compiling Legion with `-std=c++17`, I hit the following errors:
```
(base) wwu@g0004:/scratch2/wwu/legion-hip/build$ /usr/local/cuda-11.1/bin/nvcc /scratch2/wwu/legion-hip/runtime/legion/legion_redop.cu -c -o /scratch2/wwu/legion-hip/build/runtime/CMakeFiles/cuda_compile_1.dir/legion/./cuda_compile_1_generated_legion_redop.cu.o -ccbin /usr/bin/cc -m64 -Xcompiler ,\"-std=c++17\",\"-march=native\",\"-g\" -Xcudafe --diag_suppress=boolean_controlling_expr_is_constant -gencode arch=compute_60,code=sm_60 -gencode arch=compute_60,code=compute_60 -I /scratch2/wwu/legion-hip/runtime -I /scratch2/wwu/legion-hip/build/runtime -Xcompiler -fPIC -g -DNVCC -I/usr/local/cuda-11.1/include
/usr/include/c++/9/bits/stl_pair.h(442): error: argument list for class template "std::pair" is missing

/usr/include/c++/9/bits/stl_pair.h(442): error: expected a ")"

/usr/include/c++/9/bits/stl_pair.h(442): error: template parameter "_T1" may not be redeclared in this scope

/usr/include/c++/9/bits/stl_pair.h(442): error: expected a ";"

/usr/include/c++/9/bits/basic_string.h(5992): error: argument list for class template "std::__cxx11::basic_string" is missing

/usr/include/c++/9/bits/basic_string.h(5992): error: expected a ")"

/usr/include/c++/9/bits/basic_string.h(5992): error: template parameter "_InputIterator" may not be redeclared in this scope

/usr/include/c++/9/bits/basic_string.h(5993): error: expected a ";"

/usr/include/c++/9/bits/basic_string.h(6000): error: argument list for class template "std::__cxx11::basic_string" is missing

/usr/include/c++/9/bits/basic_string.h(6000): error: expected a ")"

/usr/include/c++/9/bits/basic_string.h(6000): error: "basic_string_view" is not a function or static data member

/usr/include/c++/9/bits/basic_string.h(6006): error: argument list for class template "std::__cxx11::basic_string" is missing

/usr/include/c++/9/bits/basic_string.h(6006): error: expected a ")"

/usr/include/c++/9/bits/basic_string.h(6006): error: "basic_string_view" is not a function or static data member

/usr/include/c++/9/optional(1230): error: argument list for class template "std::optional" is missing

/usr/include/c++/9/optional(1230): error: template parameter "_Tp" may not be redeclared in this scope

/usr/include/c++/9/optional(1230): error: expected a ";"

/usr/include/c++/9/array(244): error: argument list for class template "std::array" is missing

/usr/include/c++/9/array(244): error: expected a ")"

/usr/include/c++/9/array(243): error: too many template parameters -- does not match previous declaration (declared
/usr/include/c++/9/optional(1230): here)

/usr/include/c++/9/array(245): error: expected a ";"
```

I also create a simple reproducer:
test_stl.cu
```
#include<utility>
```
compilation cmd:
```
nvcc test_stl.cu -c -o test_stl.cu.o -ccbin /usr/bin/gcc-8 -m64 -Xcompiler ,\"-std=c++17\",\"-march=native\",\"-g\"
```

A similar issue can be found here: https://forums.developer.nvidia.com/t/ubuntu-20-04-gcc-9-3-cuda-toolkit-11-3-not-a-supported-combination/193486/8
If we remove the `-Xcompiler`, then it compiles. However, `-Xcompiler` is automatically added by cmake.

**Comment by lightsighter** [comment]
@elliottslaughter Are we not testing c++17 with nvcc in the CI? Seems like this just a general issue with the cmake. @eddy16112 can you check with some of the other teams at NVIDIA for how they use cmake and work around this issue? I'm sure the thrust/cub people have a similar problem testing c++17 with cmake.

**Comment by elliottslaughter** [comment]
It does not appear that we have C++17 tests with CUDA:

https://gitlab.com/StanfordLegion/legion/-/blob/master/.gitlab-ci.yml#L1223-1281

Adding the tests is easy enough, but if we need new CUDA or GCC versions, we'll need to involve @streichler because I don't manage this machine.

**Comment by elliottslaughter** [comment]
@eddy16112 What CMake, CUDA, and GCC are you on? It may be that some combination of those fixes this issue.

**Comment by eddy16112** [comment]
I have been talked with @streichler about deprecating old packages in the CUDA CI image because the new Kokkos can not work with them. 
@elliottslaughter I am using cmake 3.16, CUDA 11.1 and GCC 9.4 on sapling.

**Comment by elliottslaughter** [comment]
Looks like the newest CMake is version 3.25.0. Does that fix it by any chance? https://github.com/Kitware/CMake/releases/tag/v3.25.0

Probably easier to upgrade CMake than any of our other dependencies.

**Comment by eddy16112** [comment]
> Looks like the newest CMake is version 3.25.0. Does that fix it by any chance? https://github.com/Kitware/CMake/releases/tag/v3.25.0
> 
> Probably easier to upgrade CMake than any of our other dependencies.

I tried CMake 3.25.0, but the error is not fixed. I took a closer look at the output of `make VERBOSE=1`, and found out the error came from this cmd line generated by CMake:
```
-Xcompiler ,\"-std=c++17\",\"-march=native\"
```
If we change it to the following line, then it works. 
```
-std=c++17 -Xcompiler ,\"-march=native\"
```

**Comment by elliottslaughter** [comment]
I guess we're passing `-std=c++17` via `CXXFLAGS`? Maybe we should stop doing that; I don't think it's how CMake is intended to be used.

I think CMake intends to you use [`CMAKE_CXX_STANDARD`](https://cmake.org/cmake/help/latest/variable/CMAKE_CXX_STANDARD.html), if we used that maybe this would go away.

**Comment by eddy16112** [comment]
Yeah, the `[CMAKE_CXX_STANDARD](https://cmake.org/cmake/help/latest/variable/CMAKE_CXX_STANDARD.html)` fixed the problem. Let me try to update the script for CI.

**Comment by eddy16112** [comment]
The bug has been fixed by this PR https://gitlab.com/StanfordLegion/legion/-/merge_requests/614, so I will close it.
