### ISSUE TITLE
Mapping Functions for Shim Mapper

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#136]
Respond to this issue with the list of mapping functions you care about from the old mapper interface and would like to have included in the shim mapper in the newmap branch.  I'll probably only implement functions with requests > 1.

For those that are curious, here is the new mapping interface in the 'newmap' branch.
https://github.com/StanfordLegion/legion/blob/newmap/runtime/legion/legion_mapping.h

Also to clarify, the shim mapper will just be a class that has virtual methods that match the old mapper interface which will be invoked from new mapper calls with the appropriate translation.  The result being that when we merge the 'newmap' branch into master, you'll just have to inherit from the ShimMapper class instead of the DefaultMapper class in order for your applications to still work.

**Comment by abpoms** [comment]
Where can I see what the new mapping interface looks like?

**Comment by lightsighter** [comment]
Good question.  I've added a link to question description above.  There is also a new default mapper implementation of this interface here so you can see how to use it:

https://github.com/StanfordLegion/legion/blob/newmap/runtime/mappers/default_mapper.cc

The new interface is not quite 1-to-1 with the old interface, but it should be much more intuitive to figure out compared to the old interface.

Just a warning: the newmap branch isn't quite stable yet.  It will be soon.

**Comment by elliottslaughter** [comment]
The Regent PENNANT mapper (from which the majority of Regent mappers are derived) uses the following functions:

```
  virtual void select_task_options(Task *task);
  virtual void select_task_variant(Task *task);
  virtual bool map_task(Task *task);
  virtual bool map_inline(Inline *inline_operation);
  virtual bool map_copy(Copy *copy);
  virtual void notify_mapping_failed(const Mappable *mappable);
  virtual bool map_must_epoch(const std::vector<Task*> &tasks, ...
```

Having said that, I really wouldn't be too upset at having to re-write my mappers from scratch.

**Comment by lightsighter** [comment]
@elliottslaughter Do you know if they actually send messages between mappers?  They've overloaded the 'handle_message' mapper call, but I can't see where they actually invoke it.  Maybe they are using as their call from the application?  Let me know if you know the answer.

**Comment by lightsighter** [comment]
Nevermind, I see they have a call to 'broadcast_message'.

**Comment by lightsighter** [comment]
I don't think I'm going to provide an overload for rank_copy_targets through because the Liszt mapper is not actually doing anything interesting with it (they just invoked the default mapper's version anyway).
