### ISSUE TITLE
Pygion: crashes when running the pygion tests multiple times

### ISSUE THREAD

**Issue by eddy16112** [StanfordLegion/legion#1366]
To reproduce the error, we need to add `for i in range(100):` before this line https://gitlab.com/StanfordLegion/legion/-/blob/master/jupyter_notebook/ci_test.py#L36, and then run
```
legion_python ./ci_test.py -ll:py 1
```
In the 2nd iteration, pygion crashes with the following error:
```
[0 - 7f7cc0c1b800]    2.284031 {6}{python}: python exception occurred within task:
Traceback (most recent call last):
  File "/repo/bindings/python/pygion.py", line 1803, in __call__
    return self.execute_task(*args, **kwargs)
  File "/repo/bindings/python/pygion.py", line 1910, in execute_task
    result = self.body(*args)
  File "/repo/bindings/python/examples/must_epoch.py", line 44, in main
    assert global_var == 4123
AssertionError
```
@elliottslaughter Any ideas?

**Comment by elliottslaughter** [comment]
The failing test has global variables that you'll have to reinitialize if you want to do this:

https://gitlab.com/StanfordLegion/legion/-/blob/master/bindings/python/examples/must_epoch.py#L23

(And make sure to fence to avoid races.)

As it says in the test, "Don't do this at home."

**Comment by elliottslaughter** [comment]
Alternatively, you could just put the offending test outside of the loop and do the repeat-test on the remaining tests.

**Comment by eddy16112** [comment]
Thanks, I was trying to reproduce another bug and accidentally hit this error. If I can not run `must_epoch.py` multiple times, I will just not repeat it.

**Comment by eddy16112** [comment]
Close it as it has been solved.
