### ISSUE TITLE
regent docker image does not work with instructions from project website

### ISSUE THREAD

**Issue by cinterloper** [StanfordLegion/legion#137]
Hey there,
I am trying to follow the first steps on http://regent-lang.org/
I have done the following,
but the first line from the website documentation produces an error:
```
$ sudo docker run -t -i stanfordlegion/regent

Terra -- A low-level counterpart to Lua

Stanford University
zdevito@stanford.edu

> import "regent"
/usr/local/legion/language/src/regent/config.t:58: attempt to index local 'rawargs' (a nil value)
stack traceback:
    /usr/local/legion/language/src/regent/std.t:24: in main chunk
    [C]: in function 'require'
    /usr/local/legion/language/src/regent/builtins.t:17: in main chunk
    [C]: in function 'require'
    /usr/local/legion/language/src/regent.t:17: in main chunk
    [C]: at function: 0x40d9eed0
    [C]: in function 'xpcall'
    src/terralib.lua:4184: in function <src/terralib.lua:4183>
```

**Comment by elliottslaughter** [comment]
Thanks for the bug report! I have pushed a fix to master and (once Docker finishes building it) you should be able to `docker pull stanfordlegion/regent` and try again.

There is one caveat I should note, as it makes the interactive interpreter less pleasant to use. Language imports (your `import "regent"` line above) are scoped to the current statement. This is for the interactive interpreter only; files do not have this issue. This makes it quite a bit more clumsy to write tasks interactively, but you should be able to do something like:

```
Terra -- A low-level counterpart to Lua

Stanford University
zdevito@stanford.edu

> do import "regent" task main() regentlib.c.printf("hello world\n") end regentlib.start(main) end
hello world
```

If you write the above as a `.rg` file you can write this as the much more legible:

```
import "regent"
task main()
  regentlib.c.printf("hello world\n")
end
regentlib.start(main)
```

**Comment by cinterloper** [comment]
ah I see it works now
thanks for the tip!
