### ISSUE TITLE
Regent: type checking error with newsymbol of type ispace, region, or partition

### ISSUE THREAD

**Issue by CharlelieLrt** [StanfordLegion/legion#1373]
Lua metaprogramming of regent symbols of types `ispace`, `region`, or `partition` gives type checking errors at compile time. For example, when compiling the following code:

```
import "regent"
local IS = regentlib.newsymbol(ispace(int1d), "IS")

task main()
  rescape
     remit rquote
        var [IS] = ispace(int1d, 5)
     end
  end
end
regentlib.start(main)
```

I get a rather confusing error message: `type mismatch in var: expected ispace(int1d) but got ispace(int1d)`

**Comment by elliottslaughter** [comment]
If you turn on `-fdebug 1`, you'll get an error message like: `type mismatch in var: expected ispace#1(int1d) but got ispace#2(int1d)`. I.e., these are different index spaces.

Right now, you cannot predeclare the type of an index space, region, or partition. Those types must be inferred. In the small reproducer you've got, you can work around this with:

```
import "regent"
local IS = regentlib.newsymbol("IS")

task main()
  rescape
     remit rquote
        var [IS] = ispace(int1d, 5)
     end
  end
end
regentlib.start(main)
```

It's been a roadmap item for a while to fix this, but I have concerns that a proper fix would make the compiler slower.

**Comment by CharlelieLrt** [comment]
The workaround solved the problem. Issue closed.

**Comment by CharlelieLrt** [comment]
@elliottslaughter I was skimming through the Regent test cases and I realized it might be possible, in some specific occasions, to predeclare the type of an index space, a region, or a partition.
For example [there](https://github.com/StanfordLegion/legion/blob/12f6051c9d75229d00ac0b31d6be1ff2014f7e6a/language/tests/regent/run_pass/quote_task_constraint.rg#L21) it seems to work.
Is it because the region is only used as an argument to the task, and is not actually created like in the error I posted above? I am trying to understand when it is valid to predeclare the types of regions and partitions.

**Comment by elliottslaughter** [comment]
This is correct. The problematic pattern is:

```
var r : some_region_type = region(...)
```

Because `some_region_type` is different from the type generated by `region(...)`. But if you have:

```
task f(r : some_region_type)
```

Then it's fine because there's no conflict.

The type system could potentially be smarter to accommodate this, but that's a much bigger research issue.
