### ISSUE TITLE
Regent: support AOS layout

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1375]
Currently `codegen.t` seems to assume SOA layout:

https://github.com/StanfordLegion/legion/blob/9ed6f4d6b579c4f17e0298462e89548a4f0ed6e5/language/src/regent/codegen.t#L632-L634

And `base_pointer` is an `&elem` so this is not a superfluous check:

https://github.com/StanfordLegion/legion/blob/9ed6f4d6b579c4f17e0298462e89548a4f0ed6e5/language/src/regent/codegen.t#L618-L619

It would be nice to support AOS layout, but we need to make sure that doing so does not cause a performance regression.

**Comment by elliottslaughter** [comment]
I should note that this can be worked around with:

https://github.com/StanfordLegion/legion/blob/9ed6f4d6b579c4f17e0298462e89548a4f0ed6e5/language/tests/regent/run_pass/region_fields_struct_unsliced.rg#L21-L26

But this workaround is not desirable for the target application because it involves Legion C++ code in addition to Regent, so the changes would be nontrivial.

**Comment by magnatelee** [comment]
@elliottslaughter there's some preliminary support for layout constraints on task variants. here's an example to change the primary variant to use AOS instances:

```
import "regent"

fspace fs
{
  x : int;
  y : int;
}

task foo(is: ispace(int2d), r: region(is, fs))
where
  writes(r.{x, y})
do
  for e in r do
    r[e].x = 1
    r[e].y = 1
  end
end

local AOS = true
local primary_variant = foo:get_primary_variant()
if AOS then
  primary_variant:add_layout_constraint(
    regentlib.layout.ordering_constraint(terralib.newlist {
      regentlib.layout.field_constraint(
        "r",
        terralib.newlist {
          regentlib.field_path("x"),
          regentlib.field_path("y"),
        }
      ),
      regentlib.layout.dimx,
      regentlib.layout.dimy,
    })
  )
else
  primary_variant:add_layout_constraint(
    regentlib.layout.ordering_constraint(terralib.newlist {
      regentlib.layout.dimx,
      regentlib.layout.dimy,
      regentlib.layout.field_constraint(
        "r",
        terralib.newlist {
          regentlib.field_path("x"),
          regentlib.field_path("y"),
        }
      ),
    })
  )
end

task toplevel()
  var is = ispace(int2d, {10, 10})
  var r = region(is, fs)
  fill(r.{x, y}, 0)
  foo(is, r)
end

regentlib.start(toplevel)
```

do you need anything more than this?

**Comment by magnatelee** [comment]
I mean, the interface could certainly be improved, but I feel this should give you what you want today.

**Comment by elliottslaughter** [comment]
Is this a test in the test suite? Can we run this now?

**Comment by magnatelee** [comment]
> Is this a test in the test suite?

No, I just wrote it up. Here's the actual test suite for layout constraints (I thought you already knew about this): https://github.com/StanfordLegion/legion/tree/stable/language/tests/regent/layout

> Can we run this now?

Yes.

**Comment by elliottslaughter** [comment]
Ok, I'm confused. I thought the SOA layout was hard-coded in the code generator (and we had no layout tests for AOS), but maybe I misunderstood...

@seemamirch can you test this approach and see if it works for you?

**Comment by seemamirch** [comment]
This approach works - thanks!

**Comment by elliottslaughter** [comment]
Just a note to myself: I missed the `fastest_index` in the first code block I linked at the top of this thread. That's how this code supports AOS. The code defaults to SOA which is why our initial tests failed when we only changed the mapper.
