### ISSUE TITLE
safe control replication false positive in `construct_future_map`

### ISSUE THREAD

**Issue by rohany** [StanfordLegion/legion#1378]
The (deprecated) overload of `construct_future_map` that takes in a domain can raise false control replication violation messages because the dispatch for it looks up a local index space for the domain which can differ across shards. Unfortunately, Legate and the Python interface still rely on the deprecated version, so it might be easier to adjust the error checking instead.

**Comment by rohany** [comment]
cc @lightsighter

**Comment by lightsighter** [comment]
Pull and try again.

**Comment by rohany** [comment]
I'll need to check for sure when it merges into collective but based on the diff this will work.
