### ISSUE TITLE
Realm: possible off-by-one error in compute_covering of sparse compact instances

### ISSUE THREAD

**Issue by mariodirenzo** [StanfordLegion/legion#1387]
`compute_covering` fails to compute a covering for the index space composed of the following 10 rectangles
```
<7,0,0>..<7,6,6>
<8,0,0>..<8,7,8>
<31,0,0>..<31,7,8>
<0,7,0>..<7,8,6>
<0,31,0>..<7,31,8>
<0,0,7>..<7,8,8>
<0,0,31>..<7,8,31>
<8,0,31>..<8,7,31>
<31,0,31>..<31,7,31>
<0,31,31>..<7,31,31>
```
with `max_pieces=10` and `max_overhead=10`.
If `max_pieces` is increased to 11, the computed covering is composed of the original 10 rectangles.
```
inst_layout: Layout(bytes=29424, align=32, fields={123=0+0}, lists=[[<7,0,0>..<7,6,6>->affine(<24,24,168>-168), <8,0,0>..<8,7,8>->affine(<24,24,192>+984), <31,0,0>..<31,7,8>->affine(<24,24,192>+2160), <0,7,0>..<7,8,6>->affine(<24,192,384>+3288), <0,31,0>..<7,31,8>->affine(<24,192,192>+1368), <0,0,7>..<7,8,8>->affine(<24,192,1728>-3048), <0,0,31>..<7,8,31>->affine(<24,192,1728>-41064), <8,0,31>..<8,7,31>->affine(<24,24,192>+8088), <31,0,31>..<31,7,31>->affine(<24,24,192>+7728), <0,31,31>..<7,31,31>->affine(<24,192,192>+2712)]])
```

**Comment by seemamirch** [comment]
@mariodirenzo - which test case is this?

**Comment by seemamirch** [comment]
> `compute_covering` fails to compute a covering for the index space composed of the following 10 rectangles
> 
> ```
> <7,0,0>..<7,6,6>
> <8,0,0>..<8,7,8>
> <31,0,0>..<31,7,8>
> <0,7,0>..<7,8,6>
> <0,31,0>..<7,31,8>
> <0,0,7>..<7,8,8>
> <0,0,31>..<7,8,31>
> <8,0,31>..<8,7,31>
> <31,0,31>..<31,7,31>
> <0,31,31>..<7,31,31>
> ```
> 
> with `max_pieces=10` and `max_overhead=10`. If `max_pieces` is increased to 11, the computed covering is composed of the original 10 rectangles.
> 
> ```
> inst_layout: Layout(bytes=29424, align=32, fields={123=0+0}, lists=[[<7,0,0>..<7,6,6>->affine(<24,24,168>-168), <8,0,0>..<8,7,8>->affine(<24,24,192>+984), <31,0,0>..<31,7,8>->affine(<24,24,192>+2160), <0,7,0>..<7,8,6>->affine(<24,192,384>+3288), <0,31,0>..<7,31,8>->affine(<24,192,192>+1368), <0,0,7>..<7,8,8>->affine(<24,192,1728>-3048), <0,0,31>..<7,8,31>->affine(<24,192,1728>-41064), <8,0,31>..<8,7,31>->affine(<24,24,192>+8088), <31,0,31>..<31,7,31>->affine(<24,24,192>+7728), <0,31,31>..<7,31,31>->affine(<24,192,192>+2712)]])
> ```

This is the expected behavior - the covering produced meets the 2 constraints i.e. # of pieces (10)  <= max_pieces (11) and there is no additional overhead.
The code path taken is https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/realm/deppart/sparsity_impl.cc?ref_type=heads#L654

**Comment by seemamirch** [comment]
> That's not the expected behavior as the `max_pieces=10` should still provide a layout without additional overhead for an instance composed of 10 rectangles, if the inequality that you mentioned `# of pieces (10) <= max_pieces (11) ` holds.

If max_pieces=10 and max_overhead=10 - it produces the same result as max_pieces=11 and max_overhead=10. Is this what you are not seeing or expecting?

**Comment by seemamirch** [comment]
Setting max_pieces=10 in https://gitlab.com/insieme1/htr/htr-solver/-/blob/Develop/src/prometeo_constraints.cc?ref_type=heads#L46, all solverTests passed on lassen. Additional logging added in realm verifies that max_pieces=10, num_pieces=10 does occur in some tests + layout without additional overhead is returned.
