### ISSUE TITLE
Jupyter Notebook: weird behaviors when redirecting sys.stdout

### ISSUE THREAD

**Issue by eddy16112** [StanfordLegion/legion#1393]
Here is the result of running Legate programs with canonical python interpreter on Jupyter Notebook. 
![Screenshot 2023-02-01 at 12 48 25 PM](https://user-images.githubusercontent.com/7025793/216150119-e68c7b2c-957e-42bb-93a0-029f04b72c1a.png)
All prints are stacked ahead. It is due to the following code
```
sys.stdout = LegionOutputStream(sys.stdout)
```
https://gitlab.com/StanfordLegion/legion/-/blob/control_replication/bindings/python/legion_top.py#L116
I have tried to use `sys.__stdout__`, but it does not solve the problem. Since we are not running jupyter notebook on multi-node executions (at least not for now), one possible solution is to modify the code into:
```
if multi-node:
    sys.stdout = LegionOutputStream(sys.stdout)
```

@elliottslaughter @manopapad @lightsighter any thoughts?

**Comment by lightsighter** [comment]
I think Manolis has probably nailed this one.

**Comment by bryevdv** [comment]
I can confirm that manually making that change fixes the issue for me:

![image](https://user-images.githubusercontent.com/1078448/216477635-e771adfd-5435-4561-adb1-e7c83109269e.png)

The generic forwarding seems plausible as well but I'd say merge this small change quickly and open an issue for the wider proposal.

**Comment by eddy16112** [comment]
I can also confirm that adding the `set_parent` does not work for me. Thanks everyone! I will create a PR later.

**Comment by eddy16112** [comment]
The PR has been merged to the control replication branch, so close it.
