### ISSUE TITLE
RFC: Set minimum software versions to GCC 8, CMake 3.16, CUDA 10

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1395]
## Proposal

I propose that we require the following minimum software versions:

  * GCC 8 (soft requirement)
  * CMake 3.16
  * CUDA 10 (soft requirement)

GCC 8 and CUDA 10 are "soft" requirements. We will NOT immediately make any changes that will break GCC <= 7 or CUDA <= 9. But we will remove those older versions from CI, and it is possible that things will break over time for those versions.

(Updating the GCC bound may open the door to increasing the minimum C++ standard in the future, but I am not proposing that here.)

CMake has to be a hard requirement because there are changes we want to make that rely on the minimum version.

## Impact

If accepted, I propose we make the following changes:

  * We remove older GCC/CUDA versions from testing in CI
  * We update CI images to CMake 3.16
  * This should also unblock work on our CMake support to perform modernizations enabled by 3.16
  * Certain optional features of Legion may still require even newer CMake versions. This situation is unchanged by this proposal

## How I Arrived at These Versions

In order to determine appropriate minimum versions for GCC and CMake, I did a survey of the machines that we use (or that I am aware of that someone else uses). If any machines are missing here, please let me know.

|                 | GCC     |         |         | CMake   |         |         |
|-----------------|---------|---------|---------|---------|---------|---------|
| Machine         | Minimum | Maximum | Default | Minimum | Maximum | Default |
| Piz Daint       | 8       | 11      | 11      | 3.17    | 3.17    | 3.17    |
| Summit          | 7       | 12      | 9       | 3.18    | 3.23    | 3.23    |
| Crusher         | 10      | 12      | 11      | 3.21    | 3.23    | 3.23    |
| El Capitan      | 9       | 12      | 12      | 3.14    | 3.24    | 3.24    |
| Perlmutter      | 10      | 12      | 11      | 3.22    | 3.24    | 3.24    |
| Lassen          | 4.9     | 8       | 4.9     | 2.8     | 3.23    | 3.14    |
| Quartz          | 4.8     | 10      | 4.9     | 3.5     | 3.23    | 3.14    |
| Marconi100      | 7       | 12      |         | 3.17    | 3.24    |         |
| Sapling Head    | 4.8     | 8       | 4.8     | 2.8     | 2.8     | 2.8     |
| Sapling Compute | 9       | 9       | 9       | 3.16    | 3.16    | 3.16    |
|  &nbsp;         |         |         |         |         |         |         |
| Ubuntu 18.04    | 7       | 11      | 7       | 3.10  | 3.10  | 3.10  |
| Ubuntu 20.04    | 9       | 11      | 9       | 3.16    | 3.16    | 3.16    |
| Ubuntu 22.04    | 11      | 11      | 11      | 3.22    | 3.22    | 3.22    |
| &nbsp;          |         |         |         |         |         |         |
| Overall min*:   | 7       | 8       | 8       | 3.14    | 3.16    | 3.14    |

\* Excluding Ubuntu 18.04, Sapling Head, and ignoring the default GCC/CMake on Lassen and Quartz

All systems have access to at least these versions of software; the vast majority have these versions (or newer) as default. I am not aware of any machine that would be substantially inconvenienced by these minimum versions.

## CUDA Software Versions

| Machine         | Minimum | Maximum | Default |
|-----------------|---------|---------|---------|
| Piz Daint       | 10.2    | 11.3    | 11.0      |
| Summit          | 10.1    | 11.5    | 11.0      |
| Lassen          | 9.0       | 12      | 10.1    |
| Marconi100 | 10.1 | 11.7 | |
| Sapling Compute | 11.1    | 11.7    | 11.7    |
| Overall min:    | 9.0       | 11.3    | 10.1    |

## Timeline

I've already been soliciting feedback on this informally, so I don't anticipate any show stoppers, but if you are aware of any, please speak up now. (This is particularly true if you are aware of any machines we care about that are old enough to face difficulties with these minimums.)

Once we hear from the major stakeholders, we can move forward with this.

**Comment by lightsighter** [comment]
No concerns from me. @opensdh and @tuxfan to comment on FleCSI cmake requirements.

**Comment by opensdh** [comment]
> No concerns from me. @opensdh and @tuxfan to comment on FleCSI cmake requirements.

We've been using GCC&ge;9 (often 11) for a long time and just took a dependency on CMake 3.19, so this is fine.

**Comment by lightsighter** [comment]
@bryevdv and @trxcllnt to sign off on Legate cmake dependences.

**Comment by bryevdv** [comment]
I will defer to @trxcllnt on cmake versions

**Comment by trxcllnt** [comment]
I just verified `enable_language(CUDA)` is in CMake `v3.16.3`, `find_package(CUDAToolkit)` is in CMake `v3.17`.

+1 for updating to at least CMake `v3.16` for the native CUDA language support and allow dropping the legacy `FindCUDA.cmake` compile macros. Legion can vendor `FindCUDAToolkit.cmake` if needed.

**Comment by elliottslaughter** [comment]
I think we're stuck with CMake 3.16 for the forseeable future, unfortunately. Ubuntu 20.04 won't be EOL for a couple more years, and it's an important enough platform that I don't think we want to break it. (But I will try to make sure Sapling doesn't get stuck on this, at least.)

**Comment by elliottslaughter** [comment]
I have out-of-band confirmations from @streichler @manopapad @mariodirenzo @cmelone.

**Comment by elliottslaughter** [comment]
One open question is whether we want to bump up our CUDA minimum at the same time. Just naively cutting all jobs tied to GCC 7 and below leads us to remove the following configurations:

```
p100_cuda80_gcc5_cxx11_release_cuda_legion
p100_cuda90_gcc6_cxx11_release_cuda_legion
p100_cuda92_gcc7_cxx11_release_cuda_legion
```

Are we ok with this? CUDA 10 was released in 2018, CUDA 9 in 2017 and CUDA 8 in 2016 (from https://developer.nvidia.com/cuda-toolkit-archive). I can't personally think of anywhere we're running with a CUDA older than 10.

**Comment by elliottslaughter** [comment]
Merge request: https://gitlab.com/StanfordLegion/legion/-/merge_requests/663

**Comment by lightsighter** [comment]
> One open question is whether we want to bump up our CUDA minimum at the same time. 

Legate has definitely moved on to CUDA 11 as a minimum. I would not be opposed to bumping the CUDA version. Although if you do decide to go this route, please let @muraj know since he's been playing around with the GPU part of the CI, and we'll need to update the docker container for the GPU runners to reflect the new versions.

**Comment by muraj** [comment]
Having a minimum of CUDA 10.0 is fine, I can remove these from the docker containers later and add 12.0, but this shouldn't block removing 8 and 9.

Can we document this support matrix somewhere in like a github wiki or something so we can keep track of and update these dependencies?

**Comment by streichler** [comment]
>Can we document this support matrix somewhere in like a github wiki or something so we can keep track of and update these dependencies?

I would vote for the matrix being in-tree so that it is easier to find and more likely to stay in sync.

**Comment by elliottslaughter** [comment]
Do you mean the minimum versions, or the table of machines that we care about?

Minimum versions are tracked in the top-level README. I updated that file in the MR. (Though specific compiler versions are currently untracked. I can add that if you like.)

I'm more on the fence about the machine table, because it represents a fundamentally volatile data set. Any of the machines we cited may change their software versions at any time. The set of machines we care about may also change. So I feel like it's better to capture snapshots, like we did here, that are timestamped to specific dates so we know when the data was collected. (And therefore, I don't feel as strongly about versioning / tracking this.) But I'm open to arguments to the contrary.

**Comment by streichler** [comment]
Yes, I was thinking more about the min versions.  I agree the the system table is volatile enough that the wiki is probably the appropriate place for it.  I'd settle to a pointer to it from the README.

**Comment by elliottslaughter** [comment]
I added the CUDA software version table to the top comment in this issue. All machines I have access to are on at least CUDA 10.1 by default.

**Comment by elliottslaughter** [comment]
Last call for comments/concerns/objections. I believe the only CI failures are explained by prior issues, so I intend to merge.

**Comment by elliottslaughter** [comment]
The CUDA 10 minimum has been confirmed by @mariodirenzo.

**Comment by elliottslaughter** [comment]
I haven't heard any objections so I merged https://gitlab.com/StanfordLegion/legion/-/merge_requests/663 . Thanks everyone!
