### ISSUE TITLE
Regent: Issue with reading values into regentlib.arrays within fspaces

### ISSUE THREAD

**Issue by ReadingSteiner122** [StanfordLegion/legion#1397]
I have recently run into an issue with reading values into `regentlib.arrays` within an `fspace`.

```
import "regent"

local c = regentlib.c
local format = require("std/format")

fspace test{
    conn : regentlib.array(int, 6),
    -- conn : int[6],
}

task inputRArray(tests : region(ispace(int1d), test)) where
reads writes (tests)
do
    var file = c.fopen("testinput.dat", "r")
    for testItr in tests do
        var testTemp : test
        for i = 0, 6 do
            var temp : int
            -- c.fscanf(file, "%d", &testTemp.conn[i]) -- works with int[6] but NOT with regentlib.array(int, 20) within an fspace
            c.fscanf(file, "%d", &temp)
             testTemp.conn[i] = temp -- does NOT work with regentlib.array(int, 6) within an fspace either
        end
        tests[testItr] = testTemp
    end
    c.fclose(file)
end

task main()
    var tests = region(ispace(int1d, 1), test)
    inputRArray(tests)
end
regentlib.start(main)
```

The issue here is that whenever a `regentlib.array` is read using fscanf (or using a temporary variable), this error is thrown: 
```
/home/legion/language/terra/src/terralib.lua:1202: Errors reported during typechecking.
/home/legion/language/src/regent/codegen.t:2195: expected an array or pointer but found regent_array(int32, 20)
      `([ref_expr.value][ [index.value] ])`
```
This does not seem like intended behaviour because a `regentlib.array` outside of an `fspace` can be read using fscanf. This leads to the second issue - the values of a `regentlib.array` cannot be assigned to another within an `fspace` but this does not throw an error (I printed the `regentlib.array` within the `fspace` and its values did not match the external `regentlib.array`.  Please find the reproducer for the same here: 

```
import "regent"

local c = regentlib.c
local format = require("std/format")

fspace test{
    conn : regentlib.array(int, 6),
    -- conn : int[6],
}

task inputRArray(tests : region(ispace(int1d), test)) where
reads writes (tests)
do
    var file = c.fopen("testinput.dat", "r")
    for testItr in tests do
        var testTemp : test
        var conn : regentlib.array(int, 6)
        for i = 0, 6 do
            var temp : int
             c.fscanf(file, "%d", &temp)
             conn[i] = temp
        end
        testTemp.conn = conn -- assignment operation does not work (no error thrown)
        tests[testItr] = testTemp
    end
    c.fclose(file)
end

task main()
    var tests = region(ispace(int1d, 1), test)
    inputRArray(tests)
    for testItr in tests do -- for testing whether the input was read correctly
        for i = 0, 6 do
            format.println("{}", tests[testItr].conn[i])
        end
    end
end
regentlib.start(main)
```
In this reproducer, the typechecking error disappears but the program does not work as intended i.e. the values printed do not match the values read.

I am attaching the input file I used for debugging here - [testinput.txt](https://github.com/StanfordLegion/legion/files/10672814/testinput.txt)

Please let me know if anything else is required.

Edit: This is on the latest commit in the stable branch (commit hash: `9ed6f4d6b579c4f17e0298462e89548a4f0ed6e5`).

**Comment by elliottslaughter** [comment]
Thanks for the report. The first is definitely a bug. The compiler should never produce an error in `codegen.t`. I haven't had time to read through the second one yet, I'll try to look at that when I find time.

**Comment by elliottslaughter** [comment]
The fields are indeed misaligned:

```
base pointer for field 101 (type int32[3]) is 0x7f4c9e000000
  after adjustment: 0x7f4c9e000000
base pointer for field 102 (type double) is 0x7f4c9e000024
  after adjustment: 0x7f4c9e000024
base pointer for field 103 (type double) is 0x7f4c9e000040
  after adjustment: 0x7f4c9e000040
[0 - 7f4ced84c780]    0.383070 {6}{gpu}: CUDA error reported on GPU 0: misaligned address (CUDA_ERROR_MISALIGNED_ADDRESS)
terra: /scratch2/eslaught/legion_compute/runtime/realm/cuda/cuda_module.cc:329: bool Realm::Cuda::GPUStream::reap_events(Realm::TimeLimit): Assertion `0' failed.
```

Field 102 is type `double` and is aligned on a 4-byte boundary.

The following workaround is not general, but is sufficient to fix the reproducer (and provide that my diagnosis is correct):

```diff
diff --git a/language/src/regent/std.t b/language/src/regent/std.t
index 9a821eaa84..e48a935cde 100644
--- a/language/src/regent/std.t
+++ b/language/src/regent/std.t
@@ -3843,6 +3843,13 @@ local function make_normal_layout(dim)
     c.legion_layout_constraint_set_add_specialized_constraint(
       layout, c.NORMAL_SPECIALIZE, 0)
 
+    c.legion_layout_constraint_set_add_alignment_constraint(
+      layout, 101, c.LEGION_EQ_EK, 4)
+    c.legion_layout_constraint_set_add_alignment_constraint(
+      layout, 102, c.LEGION_EQ_EK, 8)
+    c.legion_layout_constraint_set_add_alignment_constraint(
+      layout, 103, c.LEGION_EQ_EK, 8)
+
     var [layout_id] = c.legion_layout_constraint_set_preregister(layout, "SOA")
     c.legion_layout_constraint_set_destroy(layout)
   end
```

@lightsighter This is not code that Regent can produce in general. Regent tasks can be called with any (potentially dynamic) field IDs. While we know the field type and its position in a region requirement, we can't name it like this statically. Can we either (a) improve the expressivity of field constraints to support this or (b) make smarter default assumptions in Legion so that we don't need to do this in the first place? (E.g., it seems reasonable to default-align an 8-byte field to 8 bytes.)

**Comment by magnatelee** [comment]
@ReadingSteiner122 this should be fixed as of [8547faec](https://gitlab.com/StanfordLegion/legion/-/commit/8547faecd77733fa61f7733449697d7a31d08f10); the fix is propagated to `control_replication` as well. Please pull and try again.

**Comment by ReadingSteiner122** [comment]
I pulled and confirmed that this is not an issue anymore. Thank you for the fix! @magnatelee 

Should I close this issue?

**Comment by elliottslaughter** [comment]
Assuming the fix carries over to your larger code, please close it.

**Comment by ReadingSteiner122** [comment]
The fix carries over to the larger code so I am closing this issue.
