### ISSUE TITLE
legion_prof_rs: Rust profiler crashes with spy logs

### ISSUE THREAD

**Issue by syamajala** [StanfordLegion/legion#1398]
I'm seeing the following error when trying to run with spy logs:
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ExpectedEnum("Replicate Task 4 2 1")', src/spy/serialize.rs:556:70
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ExpectedEnum("Replicate Shard 2 1 1")', src/spy/serialize.rs:556:70
```

Logs are available here: http://sapling.stanford.edu/~seshu/viz/logs/

**Comment by elliottslaughter** [comment]
Can you confirm that the version of `legion_prof_rs` is exactly identical to the version of Legion used to generate the logs? It must be exactly the same commit.

I'd be surprised to see issues here, we test parsing Spy logs in CI and I would have thought that would catch this.

**Comment by syamajala** [comment]
Yes it is exactly the same commit. I pulled the latest control_replication, rebuilt the runtime, ran s3d, then did cargo install --path legion/tools/legion_prof_rs to update the profiler and it crashed.

**Comment by elliottslaughter** [comment]
What's the commit? I'll try to take a look.

**Comment by elliottslaughter** [comment]
I pushed a partial fix to `control_replication`. However, the code now hits an infinite loop. It seems we may have a cycle in the dependence graph somewhere.

**Comment by syamajala** [comment]
I guess that at least confirms there is something wrong with S3D. I made a change to the code so I'll pull the fix and try again.

**Comment by elliottslaughter** [comment]
Ok, I'll wait for you to confirm before I dig deeper on this.

**Comment by syamajala** [comment]
The profiler is at least working with spy logs now, but I can't seem to get anything out of it with S3D + spy, just too big.
