### ISSUE TITLE
AttachLauncher posix file with LEGION_FILE_CREATE sets executable bit

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1405]
I'm doing some tests and noticed that when I use:

```
AttachLauncher al(LEGION_EXTERNAL_POSIX_FILE, cpy_lr, cpy, false, false);
al.attach_file(file_name.c_str(), fids, LEGION_FILE_CREATE);
```

The resulting file comes with its executable bit set.

```
-rwxr-xr-x  1 root root  24576 Feb 20 06:40 checkpoint.0.lp.0.4_0_0_0.dat
```

When I create the file myself by using:

```
std::ofstream file(file_name, std::ios::binary);
```

And immediately closing the file, it does not have the executable bit.

**Comment by lightsighter** [comment]
Probably need to adjust this line here unless @streichler had some reason to make the file executable.

https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/realm/transfer/lowlevel_disk.cc#L181

**Comment by elliottslaughter** [comment]
I posted a merge request for this here, along with updated error logging:

https://gitlab.com/StanfordLegion/legion/-/merge_requests/699
