### ISSUE TITLE
Legion Spy: log disjointness of pending partitions

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1408]
I've been looking at our canonical C++ Circuit code here:

https://gitlab.com/StanfordLegion/legion/-/tree/control_replication/examples/circuit

And I am really surprised to find that the "privacy" partition (the first-level split between private and shared/ghost) is NOT disjoint, according to Legion Spy. (See screenshot below.)

<img width="452" alt="Screenshot 2023-02-18 at 9 44 16 PM" src="https://user-images.githubusercontent.com/3129/220213373-b63eb3bb-6a6f-4d44-a02d-efaa5bd0175a.png">

As best I can tell, the code computes all_private through a difference operator, so I do not understand how it would be possible for the partition to not be disjoint: https://gitlab.com/StanfordLegion/legion/-/blob/control_replication/examples/circuit/circuit_init.cc#L512-514

If you want to replicate, I am on control_replication commit ee4748a9d7df904c0cdaba9f9976945de25bee5d. Clean build with:

```
make LG_RT_DIR=$PWD/../../runtime CXXFLAGS=-DLEGION_SPY DEBUG=1 -j4
./circuit -p 2 -logfile spy.log
pypy3 ../../tools/legion_spy.py -r spy.log
```

Spy log files: [spy.log](https://github.com/StanfordLegion/legion/files/10788394/spy.log)

Generated index space tree: [index_space_graph.pdf](https://github.com/StanfordLegion/legion/files/10788395/index_space_graph.pdf)

While this does not appear to be a correctness issue (I don't see any failures in Circuit, even with bounds checks), it may potentially be a performance issue and it's particularly concerning because (as best I can tell), the kind of partitioning we're doing shouldn't be aliased. And therefore this may point to a Legion or Realm issue, and not merely an application issue.

**Comment by lightsighter** [comment]
This is just a logging bug in Legion Spy, the runtime thinks the partition is disjoint (otherwise all sorts of things in the logical analysis would fail). Technically even Legion Spy knows that the partition is disjoint as well since it issues a warning:

```
WARNING: privacy partition (7) was labelled aliased but there are no overlapping children. This could lead to a performance bug.
```

The runtime is just forgetting to tell Legion Spy that it went and computed that the partition was disjoint later.

**Comment by elliottslaughter** [comment]
Thanks for the explanation. I updated the title  to be more accurate.

Please consider this the lowest priority of all my recent issues, though it would be good to fix eventually.

**Comment by lightsighter** [comment]
Pull and try again.

**Comment by elliottslaughter** [comment]
Fixed, thanks!

**Comment by elliottslaughter** [comment]
@lightsighter When you changed this, did you also make it so that user queries to `runtime->is_index_partition_disjoint()` return the correct value?

**Comment by lightsighter** [comment]
As I said before, this was a logging bug. The runtime always knew the right answer.
