### ISSUE TITLE
Use of gasnet w/ master branch (Assertion `p.exists()' failed)

### ISSUE THREAD

**Issue by zard49** [StanfordLegion/legion#141]
stable:
I think this is related to the new mapper. As I was seeing this behavior on the
newmap branch, when I tried it.

I'm just running the multiple_partitions example with gasnet. Works fine w/ stable
but fails w/ master or newmap: 

stable:
 08_multiple_partitions]$ amudprun -np 4 ./multiple_partitions
Initializing field 0 for block 2...
Running fast stencil path for point 2...
Initializing field 0 for block 1...
Running fast stencil path for point 1...
Initializing field 0 for block 3...
Running slow stencil path for point 3...
Running stencil computation for 1024 elements...
Partitioning data into 4 sub-regions...
Initializing field 0 for block 0...
Running slow stencil path for point 0...
SUCCESS!

master:
 08_multiple_partitions]$ amudprun -np 4 ./multiple_partitions
WARNING: Using GASNet's udp-conduit, which exists for portability convenience.
WARNING: This system appears to contain recognized network hardware: InfiniBand IBV
WARNING: which is supported by a GASNet native conduit, although
WARNING: it was not detected at configure time (missing drivers?)
WARNING: You should *really* use the high-performance native GASNet conduit
WARNING: if communication performance is at all important in this program run.
Running stencil computation for 1024 elements...
Partitioning data into 4 sub-regions...
multiple_partitions: /home/dpx/workspace/legion-master/runtime/legion/legion_tasks.cc:1542: void Legion::Internal::TaskOp::clone_task_op_from(Legion::Internal::TaskOp*, Legion::Processor, bool, bool): Assertion `p.exists()' failed.
*** Caught a fatal signal: SIGABRT(6) on node 0/4
NOTICE: Before reporting bugs, run with GASNET_BACKTRACE=1 in the environment to generate a backtrace. 
bash: line 1: 32397 Aborted                 env 'AMUDP_SLAVE_ARGS=1,darwin-fe1.lanl.gov:47705,' './multiple_partitions'
[dpx@darwin-fe1 08_multiple_partitions]$ connection to cn53 failed.
sh: line 0: kill: (143632) - No such process
connection to cn55 failed.
connection to cn50 failed.
sh: line 0: kill: (143632) - No such process
connection to cn54 failed.
sh: line 0: kill: (143632) - No such process
sh: line 0: kill: (143632) - No such process

**Comment by lightsighter** [comment]
Pull master and try again.  If it is fixed can you close the bug.  This was actually a default mapper bug, but I've added some better error checking to the runtime so you will get a better error message in the future when the mapper is wrong.

**Comment by zard49** [comment]
Thanks! Fixed by  90ce6031fb87911216b01e964f312572e09758cc
