### ISSUE TITLE
Apparent serialization of attach/copy/detach with application execution

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1421]
I'm observing what appears to be serialization between two phases of my application that should be independent: a sequence of checkpoint operations (attach/copy/detach) and the main application timestep loop. They use different region trees, so their only point of intersection should be a copy-across operation I do to move data from one side to the other.

You can clearly see this in the Legion Spy event graph below. What we've got here is three timesteps of the application with the checkpoint being issued between the second and third timesteps. The attach/copy/detach sequence is visible as a series of red/yellow/indigo boxes. Notably, the only dependencies come in through the copies. These subgraphs are otherwise completely disconnected from the application. Likewise, you can check the instances yourself to see that I'm using a completely disjoint set of instances (once the copy-across completes).

http://sapling.stanford.edu/~eslaught/sapling_circuit_checkpoint/no_tracing_spy_prof/event_graph_toplevel_4.pdf

But the same run in Legion Prof clearly shows a gap in the timeline, corresponding to the second set of copies (not the copy-across, but the copy-to-disk). This is all in the same run so you can cross-reference the instance IDs if you want.

http://sapling.stanford.edu/~eslaught/sapling_circuit_checkpoint/no_tracing_spy_prof/legion_prof

A couple of observations about the profile:

 * The utility processor is empty for most of the copy operation. So we're not blocked on analysis or similar.
 * The CPU is idle for most of this time as well. The main task is blocked *and continues to be blocked  through the rest of the run*. This means that we've issued all of our operations and there are no wait calls that would result in, e.g., operations failing to be launched soon enough for the runtime to analyze them. All of our operations are launched way in advance.

I thought tracing might be issuing fences, so I turned off tracing. It doesn't seem to make any difference in either Legion Prof or Legion Spy. The runs above are without tracing.

At this point, I'm really scratching my head about what could be causing this. I've tried fiddling with, e.g., `-ll:bgwork`, and nothing seems to make a difference. It certainly looks like there is a (spurious) dependency from the copy to the ongoing execution, but Spy doesn't show it. I don't know where else to look.

You can find the raw logs here (again, all from the same run):

* http://sapling.stanford.edu/~eslaught/sapling_circuit_checkpoint/no_tracing_spy_prof/prof_0.gz
* http://sapling.stanford.edu/~eslaught/sapling_circuit_checkpoint/no_tracing_spy_prof/prof_1.gz
* http://sapling.stanford.edu/~eslaught/sapling_circuit_checkpoint/no_tracing_spy_prof/spy_0.log
* http://sapling.stanford.edu/~eslaught/sapling_circuit_checkpoint/no_tracing_spy_prof/spy_1.log

If you want to run it yourself, I've got a DEBUG+Spy build you can try here:

```
srun -n 1 -N 1 -c 40 -p gpu --exclusive --pty bash --login
cd /scratch2/eslaught/resilience3/circuit.run1_spy
mpirun -n 2 -oversubscribe -x LD_LIBRARY_PATH=$PWD -x REALM_FREEZE_ON_ERROR=1 ./circuit.checkpoint -npp 5000 -wpp 20000 -l 1 -p $(( 2 * 10 )) -pps 10 -prune 1 -hl:sched 1024 -ll:io 1 -ll:gpu 1 -ll:fsize 1024 -ll:zsize 1024 -checkpoint:auto_steps 2 -logfile spy_%.log -lg:prof 2 -lg:prof_logfile prof_%.gz
```

If you want to rebuild, make any changes you want and then run:

```
srun -n 1 -N 1 -c 40 -p gpu --exclusive --pty bash --login
cd /scratch2/eslaught/resilience3
./experiment/setup.sh
./experiment/build_circuit.sh circuit.run2
```

All of this is based on a branch forked from control_replication at c9939af2927786ca21cfba832e6b5f26834408c7.

**Comment by lightsighter** [comment]
Pretty sure the issue is 500ms to copy 16B from zero-copy to a file instance. I'm betting you're having contention around locking files either in POSIX or the OS.

**Comment by elliottslaughter** [comment]
What do I do to debug this?

**Comment by lightsighter** [comment]
I would try to write a small Realm benchmark that reproduces the copy pattern to narrow down the problem, and then try to identify the point of contention that's causing the copies not to run in parallel. I'm almost positive it is going to be something to do with the file I/O and lock contention, but it is going to be really hard to say what it is.

**Comment by elliottslaughter** [comment]
I did some digging and observed that there were still `Fence` logging statements in the Legion Spy logs, even after commenting out all application-level fences. Running that through gdb pointed me at the tracing code. I guess even logical traces emit fences?

I tried `-lg:no_tracing` and that was sufficient to get rid of all the fences. New profiles after this look much better:

Shorter run: http://sapling.stanford.edu/~eslaught/sapling_circuit_checkpoint/circuit.run2_spy_no_logical_trace/legion_prof/

Longer run: http://sapling.stanford.edu/~eslaught/sapling_circuit_checkpoint/circuit.run2_spy_no_logical_trace_more/legion_prof/

The remaining blocking in the longer run is clearly attributable to running back-to-back checkpoints, causing copies to back up due to WAR dependencies. But I can keep the disk channel busy basically 100% of the time while maintaining high GPU utilization, which is what I wanted.

So then I guess the remaining question is why the dependencies from the fences didn't show up in the original Legion Spy graphs?

**Comment by lightsighter** [comment]
I'm skeptical that Legion Spy is not showing fences. Legion Spy doesn't have any idea what a "fence" is, it just knows about event dependences. Did you do Legion Spy emulation or do you do detailed Legion Spy?

**Comment by elliottslaughter** [comment]
Here's a reproducible experiment for you:

http://sapling.stanford.edu/~eslaught/sapling_circuit_checkpoint/circuit.run3_spy/

This tests two configurations:

  * `before`: (no extra flags, has physical tracing enabled)
  * `after`: `-lg:no_physical_tracing`

There are no other changes. The application and all flags are identical besides the above.

You can consult my `run.sh` script to confirm I did everything correctly: http://sapling.stanford.edu/~eslaught/sapling_circuit_checkpoint/circuit.run3_spy/run.sh

Legion Prof confirms the behavior appears in `before` but not in `after`:

  * `before`: http://sapling.stanford.edu/~eslaught/sapling_circuit_checkpoint/circuit.run3_spy/before_legion_prof
  * `after`: http://sapling.stanford.edu/~eslaught/sapling_circuit_checkpoint/circuit.run3_spy/after_legion_prof

The Legion Spy logs are a bit harder to compare thanks to Graphviz rearranging things, but you can clearly see the absence of dependencies in `before`, and if you check carefully you can see that `after` is isomorphic.

  * `before`: http://sapling.stanford.edu/~eslaught/sapling_circuit_checkpoint/circuit.run3_spy/before_spy_graphs/event_graph_toplevel_2.pdf
  * `after`: http://sapling.stanford.edu/~eslaught/sapling_circuit_checkpoint/circuit.run3_spy/after_spy_graphs/event_graph_toplevel_2.pdf

Raw logs are here:

  * http://sapling.stanford.edu/~eslaught/sapling_circuit_checkpoint/circuit.run3_spy/before_spy_0.log
  * http://sapling.stanford.edu/~eslaught/sapling_circuit_checkpoint/circuit.run3_spy/before_prof_0.gz
  * http://sapling.stanford.edu/~eslaught/sapling_circuit_checkpoint/circuit.run3_spy/after_spy_0.log
  * http://sapling.stanford.edu/~eslaught/sapling_circuit_checkpoint/circuit.run3_spy/after_prof_0.gz

These are all detailed logging:

```console
$ grep Detailed *_spy_*.log
after_spy_0.log:[0 - 7f79389d6840]   10.264086 {3}{legion_spy}: Legion Spy Detailed Logging
before_spy_0.log:[0 - 7f9f65528840]   10.255249 {3}{legion_spy}: Legion Spy Detailed Logging
```

The logs also include various Realm logging, if you care about that.

A note about logical vs physical tracing: It seems I was half-right about logical tracing. Logical tracing does cause `Fence Operation` logging statements to be issued into the Spy logs. However, as you can see above, those fences somehow do not cause the application to block. When I did a three-way comparison with `-lg:no_tracing`, I did see that main appears to see some sort of blocking behavior due to logical tracing, but since it doesn't seem to have a direct performance impact, I didn't include it above. Maybe it's a mapping fence instead of an execution fence? Otherwise I have no explanation.

**Comment by lightsighter** [comment]
Pull Legion Spy. You can process the same log files without rerunning. You'll see the fences now (at least I see them pretty clearly as all-to-all dependences). In general, if you put operations between physical traces, then Legion will absolutely insert execution fences at the end and beginning of every trace replay. It's only safe to elide those fences if we know that the traces are idempotent and the replays are back-to-back.

> Maybe it's a mapping fence instead of an execution fence?

Logical tracing only needs mapping fences. Why would you need an execution fence for logical tracing that only replays the mapping dependences?

**Comment by elliottslaughter** [comment]
I see the dependencies now. Thanks.

> Logical tracing only needs mapping fences. Why would you need an execution fence for logical tracing that only replays the mapping dependences?

When I'm grepping the Legion Spy logs, I only see:

```console
$ grep -i fence before_spy_0.log 
[0 - 7f9f5c68d840]   10.877050 {3}{legion_spy}: Fence Operation 2 141 77
[0 - 7f9f5c68d840]   10.877108 {3}{legion_spy}: Fence Operation 2 142 78
[0 - 7f9f5c68d840]   10.882891 {3}{legion_spy}: Fence Operation 2 146 82
[0 - 7f9f5c68d840]   10.883004 {3}{legion_spy}: Fence Operation 2 147 83
[0 - 7f9f5c68d840]   10.883064 {3}{legion_spy}: Fence Operation 2 148 84
[0 - 7f9f5c68d840]   10.884309 {3}{legion_spy}: Fence Operation 2 153 88
[0 - 7f9f5c68d840]   11.070638 {3}{legion_spy}: Fence Operation 2 239 109
[0 - 7f9f5c68d840]   11.070691 {3}{legion_spy}: Fence Operation 2 240 110
[0 - 7f9f5c68d840]   11.071897 {3}{legion_spy}: Fence Operation 2 244 114
```

How do I know which of these are execution fences and which are mapping fences?

**Comment by lightsighter** [comment]
> How do I know which of these are execution fences and which are mapping fences?

There's nothing in the logging format that will tell you that right now. Only by looking at the event graph can we tell for sure. Maybe we should have Legion Spy render execution fences in the event graph explicitly. Doing so will require a change to the logging format though (almost certain to make Legion Prof unhappy).

**Comment by elliottslaughter** [comment]
I think it would be a minor improvement in usability to have an visible fence op in the rendered graph. I guess mapping fences would go in the dataflow graph and execution fences would go in the event graph? As it is, it's not too hard to guess when you see the all-to-all dependence pattern, but not everyone has a good grasp of the execution model, particularly when it comes to implicit fences.

I'm willing to do the Legion Prof side changes if you put the Legion changes into a branch.

**Comment by lightsighter** [comment]
> I guess mapping fences would go in the dataflow graph and execution fences would go in the event graph?

All fences are always mapping fences. Execution fences further restrict the execution. They both show up in the dataflow graph. Only execution fences will show up in the event graph.

> I'm willing to do the Legion Prof side changes if you put the Legion changes into a branch.

It's running CI right now: https://gitlab.com/StanfordLegion/legion/-/merge_requests/698
I modified Legion Prof so it at least parses the new statement format for fences correctly. The merge upstream to control replication though will be non-trivial.

**Comment by elliottslaughter** [comment]
I think this is fully merged now.
