### ISSUE TITLE
Legion: Tasks with no dependencies getting blocked

### ISSUE THREAD

**Issue by syamajala** [StanfordLegion/legion#1423]
I have a profile of S3D with spy here: http://sapling.stanford.edu/~seshu/viz/legion_prof/?start=9514878.80059925&end=12343912.92059925&collapseAll=false&resolution=10

The pipeline is render -> composite -> save_image split between cpu 3 and 4. These tasks are using their own instances that aren't shared with the simulation tasks. I don't understand why more tasks on the GPU are not getting overlapped with compositing. The composite task should be able to cross the timestep boundary.

Here is what I see in the spy data flow graph: http://sapling.stanford.edu/~seshu/viz/dataflow.png
The event graph: http://sapling.stanford.edu/~seshu/viz/event_graph.png

**Comment by streichler** [comment]
@syamajala can you compare notes with @elliottslaughter ?  From 10000 feet, this sounds similar to #1421.

**Comment by elliottslaughter** [comment]
We already grepped the Spy logs to confirm there are no fences.

@syamajala can you post the raw logs here so we can triple check?

**Comment by syamajala** [comment]
The logs with `-lg:spy 1 -level event=1,task=2,dma=2,xplan=1" are here: http://sapling.stanford.edu/~seshu/viz/realm_logs/

legion prof is here: http://sapling.stanford.edu/~seshu/viz/realm_logs/legion_prof/?start=0&end=20205930&collapseAll=false&resolution=10

I guess the task to look at is composite_task on cpu 3 of node 0.

**Comment by elliottslaughter** [comment]
Just to confirm:

```console
$ curl -O http://sapling.stanford.edu/~seshu/viz/realm_logs/run_0.log
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  161M  100  161M    0     0  17.7M      0  0:00:09  0:00:09 --:--:-- 18.2M
$ grep -i fence run_0.log 
$ grep -i detailed run_0.log 
[0 - 155555510b40]    5.965336 {3}{legion_spy}: Legion Spy Detailed Logging
$ curl -O http://sapling.stanford.edu/~seshu/viz/realm_logs/run_1.log
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  162M  100  162M    0     0  12.2M      0  0:00:13  0:00:13 --:--:-- 17.6M
$ grep -i fence run_1.log 
$ grep -i detailed run_1.log 
[1 - 155555510b40]    5.965235 {3}{legion_spy}: Legion Spy Detailed Logging
```

**Comment by elliottslaughter** [comment]
About the profile:

The first GPU task that runs after `composite_task <9582>` is `CalcRHSVelTask [cuda] <9914>`. You can confirm in the Legion Prof trace that the instances for the two tasks are disjoint.

I am seeing an error when I run Legion Spy:

```console
$ pypy3 ~/Programming/Legion/legion/tools/legion_spy.py -lpa run_*.log
Reading log file run_0.log...
WARNING: Skipped 1130678 lines when reading run_0.log
Reading log file run_1.log...
WARNING: Skipped 1135947 lines when reading run_1.log
Reducing top-level index space shapes...
 |||||||||||||||||||||||||||||||||||||||||||||||||||| 100.0% 
Done
Computing refinement points...
Dim 3: |||||||||||||||||||||||||||||||||||||||||||||||||||| 100.0% 
Dim 1: |||||||||||||||||||||||||||||||||||||||||||||||||||| 100.0% 
Done
Computing physical reachable...
 |||||||||||||||||||||||||||||||||||||||||||||||||||| 100.0% 
Done
Performing logical analysis...
Performing logical dependence verification for main...
Verifying shard 0...
ERROR: Missing internal fence operation on YDIFFFLUX_X_0 (433) of tree 5 between region requirement 3 of CalcStencilTask (UID 1526) and region requriement 1 of BCFluxes (UID 1534)
Traceback (most recent call last):
  File "/Users/elliott/Programming/Legion/legion/tools/legion_spy.py", line 14462, in <module>
    main(temp_dir)
  File "/Users/elliott/Programming/Legion/legion/tools/legion_spy.py", line 14395, in main
    state.perform_logical_analysis(logical_checks)
  File "/Users/elliott/Programming/Legion/legion/tools/legion_spy.py", line 13515, in perform_logical_analysis
    task.perform_task_logical_verification()
  File "/Users/elliott/Programming/Legion/legion/tools/legion_spy.py", line 9014, in perform_task_logical_verification
    if not op.perform_op_logical_verification(logical_op, previous_deps):
  File "/Users/elliott/Programming/Legion/legion/tools/legion_spy.py", line 7332, in perform_op_logical_verification
    if not point.op.perform_op_logical_verification(logical_op, previous_deps):
  File "/Users/elliott/Programming/Legion/legion/tools/legion_spy.py", line 7345, in perform_op_logical_verification
    if not self.verify_logical_requirement(idx, logical_op, previous_deps):
  File "/Users/elliott/Programming/Legion/legion/tools/legion_spy.py", line 7198, in verify_logical_requirement
    logical_op, previous_deps):
  File "/Users/elliott/Programming/Legion/legion/tools/legion_spy.py", line 3395, in perform_logical_verification
    previous_deps, self.get_point_set())
  File "/Users/elliott/Programming/Legion/legion/tools/legion_spy.py", line 3399, in perform_logical_verification
    logical_op, previous_deps, point_set)
  File "/Users/elliott/Programming/Legion/legion/tools/legion_spy.py", line 3404, in perform_logical_verification
    if not state.perform_logical_verification(op, req, logical_op, previous_deps):
  File "/Users/elliott/Programming/Legion/legion/tools/legion_spy.py", line 3914, in perform_logical_verification
    logical_op, previous_deps)
  File "/Users/elliott/Programming/Legion/legion/tools/legion_spy.py", line 3960, in perform_epoch_analysis
    self.field, need_fence, previous_deps):
  File "/Users/elliott/Programming/Legion/legion/tools/legion_spy.py", line 7437, in has_verification_mapping_dependence
    assert False
AssertionError
```

**Comment by streichler** [comment]
I'm going to hold off on slogging through logs until we resolve whether this legion spy-reported issue is real (and relevant).

**Comment by lightsighter** [comment]
You can ignore the Legion Spy issue it is a known issue and isn't relevant. It does suggest that there are cross-shard dependences though which suggest that the original application isn't purely data-parallel as was originally suggested.

**Comment by lightsighter** [comment]
FWIW, if you're using physical tracing, I'm betting the problem is identical to #1421. If you put non-traced code between physical trace replays then you're going to get execution fences between the non-traced and traced code.

**Comment by syamajala** [comment]
I was seeing fences from tracing, but they disappeared after I turned it off.

**Comment by lightsighter** [comment]
That is also consistent with #1421.

**Comment by elliottslaughter** [comment]
If I understand @syamajala, the problem did *not* go away when tracing was disabled.

You can see me grepping for the fences here: https://github.com/StanfordLegion/legion/issues/1423#issuecomment-1458473661

**Comment by syamajala** [comment]
Yes everything in this issue is with tracing disabled.

**Comment by lightsighter** [comment]
If there is no tracing and you can see in the event graph that there are no unexpected dependences, then the next thing to check is that the launch time of the tasks/copies are well in advance of when the actual execution takes place (look at the profile). If that is true, and you still think that things are not running as earlier as you think they should then it is time to explore other causes.

**Comment by syamajala** [comment]
Here is part of the event graph: http://sapling.stanford.edu/~seshu/viz/event_graph.png Theres no edges coming out of save_image_task. 

The copies for the composite_task should be independent of any other copies. All the image compositor tasks use a separate mapper and make their own instances and are not shared with the S3D mapper.

**Comment by lightsighter** [comment]
Ok, so that is half the checks. The other half are that the runtime is ahead enough for Realm to see the operation in time to re-order it. Need to find the same operation in the profile and check it's `created` and `ready` times.

**Comment by syamajala** [comment]
I looked at the first task that executes after the composite_image_task. The CalcRHSVelTask only has 1 edge going into it in legion_prof with spy. Its a defer task mapping on the utility processor:
http://sapling.stanford.edu/~seshu/viz/legion_prof/?start=13001884.179356484&end=13004462.0750097&collapseAll=false&resolution=10

Any copies that I saw happening for the composite_image_task and the save_image_task happen immediately before those tasks execute and are independent of the other simulation tasks.

**Comment by lightsighter** [comment]
This looks like a pretty standard case of the mapper just not being ahead. Presuming we're talking about `UID 9914` then the task just finishes mapping at 13003052us and and then starts at 13003590. That's ~500us right now between those, but this is a GPU task, so remember you're not actually seeing when the code for the task started running on the host, instead you're seeing the time that kernels were actually running on the GPU task (@seemamirch please correct me if I'm wrong about that). So given that, it probably took some time for the host part of the task to get its arguments together and launch a kernel, and then for that kernel to start running on the GPU, which probably explains a big chunk of that 500us. So as far as I can tell this profile can be pretty easily explained.

Am I looking at the right task (UID:9914)? Is the question about the 500us gap or something else?

Aside: @elliottslaughter did we lose the "ready" time for tasks? Look at UID:9914 and notice that the box has no "ready" time for it.

**Comment by lightsighter** [comment]
Well I can say for certain that it is because UID 9914 isn't mapped yet. The better question is why isn't UID 9914 isn't being mapped. The most likely cause is that the mapper has mapped far enough into the future and decided to stop mapping, specifically there are enough mapped tasks to satisfy the maximum number of mapped tasks set by the `configure_context` for the mapper call. That pauses the mapping process and is possibly preventing UID 9914 from mapping until some other task finishes executing and the mapping process resumes.

**Comment by lightsighter** [comment]
The timing link on that profile is broken (it just shows the whole profile, I don't think that time range actually exists anymore). Looking at that the whole profile though, it just looks runtime limited to me. The runtime is definitely not ahead in its mapping anywhere in the run.

**Comment by syamajala** [comment]
What else can I try?

I went back to running more timesteps: http://sapling.stanford.edu/~seshu/viz/legion_prof.4/?start=18994321.149224967&end=31316299.35024194&collapseAll=false&resolution=10

**Comment by syamajala** [comment]
It is the same chain of events as before: http://sapling.stanford.edu/~seshu/viz/legion_prof.4/?start=33191607.11025281&end=35885272.489717096&collapseAll=false&resolution=10

You see gaps on the GPU when the render (UID: 118892) and composite (UID: 123784) tasks run on the CPU. For some reason CalcRHSVelTask (UID: 124698) is getting blocked.

**Comment by lightsighter** [comment]
This looks to me like two things are happening. First, `composite task` isn't behaving like a leaf task. It's blocking downstream mapping dependences until it is done running. Second, you have a mapping fence (probably a frame), which then propagates mapping dependences to everything in the next frame. As a result nothing in the next frame can even start mapping until the `composite task` finishes running, which is highly problematic. Make a Legion Spy graph and run with `-lg:warn` to confirm.

**Comment by syamajala** [comment]
These tasks do not go through the usual S3D C++ task registration code since they live in a separate library, so they were not getting marked as leaf tasks. We're now seeing the render and composite_tasks perfectly overlap with compute on the GPU. I still need to fix tracing, but I think I know what to do for that.
