### ISSUE TITLE
Fix for collective create_partition_by_rectangles

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1425]
When I use `create_partition_by_rectangles` in collective mode, I hit this error:

```
[0 - 7fee66727800]    0.071893 {5}{runtime}: [error 564] LEGION ERROR: An invalid future size was found in a partition by domain call. All futures must contain Domain objects. (from file /resilience/legion/runtime/legion/region_tree.inl:4535)
```

I think the problem is in this code:

https://github.com/StanfordLegion/legion/blob/91ec83e195c2eecd4ce31d46e4bca5ea4c298adc/runtime/legion/legion.inl#L19694-L19695

`create_partition_by_domain` expects each `Future` to contain a `Domain` but we're passing a `DomainT`.

This patch seems to be sufficient to make it happy:

```diff
diff --git a/runtime/legion/legion.inl b/runtime/legion/legion.inl
index 1e25f9e95..2bb1517bd 100644
--- a/runtime/legion/legion.inl
+++ b/runtime/legion/legion.inl
@@ -19692,7 +19692,7 @@ namespace Legion {
                 rectangles.begin(); it != rectangles.end(); it++)
         {
           const DomainT<DIM,T> domain(it->second);
-          futures[DomainPoint(it->first)] = Future::from_value(domain);
+          futures[DomainPoint(it->first)] = Future::from_value(Domain(domain));
         }
         FutureMap fm = construct_future_map(ctx, IndexSpace(color_space),
                               futures, true/*collective*/, 0/*shard id*/, 
```

Should I commit this?

**Comment by lightsighter** [comment]
But commit it to `master` and then upstream it to `control_replication`.

**Comment by elliottslaughter** [comment]
Hm, I don't think you wrote the collective case at all in master?

https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/legion/legion.inl#L19205-19228

**Comment by lightsighter** [comment]
Ok, then you can commit it just to control replication.

**Comment by elliottslaughter** [comment]
Done.
