### ISSUE TITLE
Restricted attach in control_replication

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1427]
I am hitting this in my checkpointed Regent Stencil code:

```
[0 - 7fde6c821840]    0.432527 {5}{runtime}: [error 604] LEGION ERROR: Attach operations in control replication context main (UID 6) requested a restriction. Restrictions are only permitted for attach operations in non-control-replicated contexts currently. (from file /scratch2/eslaught/resilience3/legion/runtime/legion/legion_context.cc:19020)
```

I can work around this, but I'm just wondering if this is an easy or hard fix to make.

(Relative to my other issues, this is low priority.)

**Comment by lightsighter** [comment]
Is this a singular attach operation or an index attach operation?

**Comment by lightsighter** [comment]
Also, are you sure you really want restricted coherence? Remember that will eagerly flush changes back to the instance(s) which could be expensive in the control replicated case.

**Comment by elliottslaughter** [comment]
It's a singular `AttachLauncher`.

The pattern I'm doing is:

  * Attach
  * Copy
  * Detach

So I think the restriction only helps me here (e.g., it helps the mapper be smarter about where to send the copy).

But the fact that I'm issuing individual attaches may indicate that my covering set algorithm is failing, somehow. I should probably look into this before going any further.

Like I said, please consider this low priority unless it's easy.

**Comment by lightsighter** [comment]
I'm going to wait to see if you really want this before working on it. I'm still pretty skeptical that anyone really wants restricted coherence in a control replicated setting like this.

**Comment by elliottslaughter** [comment]
It turns out that I only hit this if I checkpoint *before* running any timesteps of the main loop, because (surprise) the user has not written any partitions at that point. If I checkpoint after running at least one timestep I go down the `IndexAttachLauncher` path and everything works as intended.

I'm going to close this, because I don't believe it'll impact any of my applications at this point.
