### ISSUE TITLE
Crash in C++ Circuit with GPUs

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1432]
This might be an application bug, but if so it's one that appears in what is arguably our flagship example code.

This was originally from Piz Daint, but I have reproduced the issue on Sapling.

Error looks like:

```
[0 - 7f13ab196840]    0.200166 {6}{gpu}: CUDA error reported on GPU 0: an illegal memory access was encountered (CUDA_ERROR_ILLEGAL_ADDRESS)
[0 - 7f13aae8a840]    0.200188 {6}{gpu}: CUDA error reported on GPU 0: an illegal memory access was encountered (CUDA_ERROR_ILLEGAL_ADDRESS)
circuit: /scratch2/eslaught/resilience1/legion/runtime/realm/cuda/cuda_module.cc:340: bool Realm::Cuda::GPUStream::reap_events(Realm::TimeLimit): Assertion `0' failed.
circuit: /scratch2/eslaught/resilience1/legion/runtime/realm/cuda/cuda_module.cc:340: bool Realm::Cuda::GPUStream::reap_events(Realm::TimeLimit): Assertion `0' failed.
```

It's sort of frustrating to debug because every time this happens, it seems to make the GPU unhappy and I keep needing to reboot the node to bring it back.

WARNING: reproducing this bug may require you to reboot the node.

```
cd /scratch2/eslaught/resilience1/build
n=1; CUDA_VISIBLE_DEVICES=0 ./examples/circuit/circuit -p $n -hl:sched 1024 -ll:gpu 1 -ll:io 1 -ll:util 2 -ll:bgwork 4 -ll:csize 15000 -ll:fsize 15000 -ll:zsize 2048 -ll:rsize 0 -ll:gsize 0 -lg:eager_alloc_percentage 10 -lg:no_tracing -checkpoint:disable
```

You can change `CUDA_VISIBLE_DEVICES` to get some use out of the node's other GPUs before you need to reboot.

This is, strictly speaking, with the checkpointing framework linked in. But as you can see it's disabled on the command line. I'm still working on finding a minimal set of arguments to reproduce because the reboot cycle is so slow.

I'll add more information when I get more time to look at this.

**Comment by lightsighter** [comment]
Have you confirmed that he memory access is out of bounds and not just misaligned? I'm betting this is just a duplicate of #1384

**Comment by lightsighter** [comment]
Also running with `cuda-memcheck` should tell you exactly why the memory access was bad (compile with `-G` on the CUDA files).

**Comment by elliottslaughter** [comment]
No, I have not confirmed that. I suppose I could merge your branch there and see if that fixes it.

**Comment by elliottslaughter** [comment]
I cherry-picked [fixalignment](https://gitlab.com/StanfordLegion/legion/-/tree/fixalignment) into my branch, and it didn't fix it. I guess I'll try `cuda-memcheck` next.

**Comment by elliottslaughter** [comment]
I'm not sure how I never noticed this before, but this only happens when I run `-p 1` (i.e., with only one circuit piece). `cuda-memcheck` pointed me at the following line, which I guess makes sense because the ghost region is not being set up properly when there is only one piece.

https://github.com/StanfordLegion/legion/blob/299e636a0bc982db6b6855ed9f46d0b0a7eab7ed/examples/circuit/circuit_gpu.cu#L49

```
========= Invalid __global__ read of size 4
=========     at 0x000038d8 in /scratch2/eslaught/resilience1/examples/circuit/circuit_gpu.cu:49:calc_new_currents_kernel(Realm::Point<int=1, __int64>, int, float, int, Legion::FieldAccessor<legion_privil
ege_mode_t=1, Realm::Point<int=1, __int64>, int=1, __int64, Realm::AffineAccessor<Realm::Point<int=1, __int64>, int=1, __int64>, bool=0>, Legion::FieldAccessor<legion_privilege_mode_t=1, Realm::Point<int=
1, __int64>, int=1, __int64, Realm::AffineAccessor<Realm::Point<int=1, __int64>, int=1, __int64>, bool=0>, Legion::FieldAccessor<legion_privilege_mode_t, PointerLocation, int=1, __int64, Realm::AffineAcce
ssor<PointerLocation, int=1, __int64>, bool=0>, Legion::FieldAccessor<legion_privilege_mode_t, PointerLocation, int=1, __int64, Realm::AffineAccessor<PointerLocation, int=1, __int64>, bool=0>, Legion::Fie
ldAccessor<legion_privilege_mode_t, float, int=1, __int64, Realm::AffineAccessor<float, int=1, __int64>, bool=0>, Legion::FieldAccessor<legion_privilege_mode_t, float, int=1, __int64, Realm::AffineAccesso
r<float, int=1, __int64>, bool=0>,
=========     by thread (31,0,0) in block (3,0,0)
=========     Address 0x00000000 is out of bounds
```

So it's a little odd that I can't run this code on one node, but it's low priority now that I know to work around it.

**Comment by lightsighter** [comment]
Can you compile the cuda code with `-G` so we can get line numbers?

**Comment by elliottslaughter** [comment]
The line number is in the error above: `circuit_gpu.cu:49`

**Comment by lightsighter** [comment]
The initialization code wasn't handling the case of a single piece correctly. You would have seen bounds check errors on the CPU or the GPU.

**Comment by elliottslaughter** [comment]
Fixed, thanks!
