### ISSUE TITLE
Bad co-location from mapper in C++ Circuit

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1436]
I don't fully understand it yet, but I believe that a bug was introduced into the Circuit code with 1a408cd3b4a2415ae233e877a788a27f165c94d9. It appears on 2 nodes if I run with `-pct 98` or on 4 nodes even if I don't. It appears irrespective of problem size.

(Note that I'm linking my checkpointing framework, but I have it shut off via command-line flag, so I'm pretty sure this is an application bug.)

In debug mode, the error message looks like:

```
[0 - 7f4bb009f840]    0.260524 {5}{runtime}: [error 67] LEGION ERROR: Invalid mapper output from invocation of 'map_task' on mapper circuit_mapper. Mapper specified instance that does not meet region requirement 1 for task update_voltages (ID 198). The index space for the instance has insufficient space for the requested logical region. (from file /scratch2/eslaught/resilience1/legion/runtime/legion/legion_tasks.cc:3178)
```

I tried commenting out the following lines, and that got rid of the mapping error. Of course, then the application fails to construct the co-location accessor. But at least it seems to confirm the hypothesis.

https://github.com/StanfordLegion/legion/blob/d5b7ddcf77368d62e67d5a7c83e616def2226638/examples/circuit/circuit_mapper.cc#L70-L77

I'll try to understand the mapper more deeply in the morning; in the meantime, if @lightsighter has any hints, I'd appreciate it.

To reproduce:

```
srun -n 1 -N 1 -c 40 -p gpu --exclusive --pty bash --login
cd /scratch2/eslaught/resilience1/build
n=2; mpirun -n $n -oversubscribe -bind-to socket ../set_cuda_visible_devices.sh ./examples/circuit/circuit -npp 50 -wpp 200 -pct 98 -p $n -hl:sched 1024 -ll:gpu 1 -ll:io 1 -ll:util 2 -ll:bgwork 4 -ll:csize 150 -ll:fsize 150 -ll:zsize 150 -ll:rsize 0 -ll:gsize 0 -lg:eager_alloc_percentage 10 -lg:no_tracing -checkpoint:disable
```

(You're welcome to run larger problem sizes if you want, just multiply all of npp/wpp/csize/fsize/zsize by 10. It'll be slower to start though.)

Keep in mind that I'm sharing the reproduction directory with #1432. But if you want to rebuild:

```
srun -n 1 -N 1 -c 40 -p gpu --exclusive --pty bash --login
cd /scratch2/eslaught/resilience1
./experiment/setup.sh
```

**Comment by lightsighter** [comment]
The memoization key in the mapper wasn't sufficient. Pull and try again.

**Comment by elliottslaughter** [comment]
Fixed, thanks!
