### ISSUE TITLE
Profiler: Incorrectly visualizing preemption in mapper tasks

### ISSUE THREAD

**Issue by manopapad** [StanfordLegion/legion#1438]
There are multiple boxes showing up on the utility timeline for the same map_task call, and one of them appears to be continuously executing (it has solid color):

[legate_0.prof.zip](https://github.com/StanfordLegion/legion/files/10996340/legate_0.prof.zip)

<img width="1625" alt="Screenshot 2023-03-16 at 3 20 07 PM" src="https://user-images.githubusercontent.com/215728/225765788-2c97301a-7ce1-4373-b0fe-1ade0d53ee97.png">

**Comment by lightsighter** [comment]
Right, it's been like this for YEARS... everyone has been living with it for quite a while. Still needs to be addressed eventually.

**Comment by eddy16112** [comment]
Is it because Legion does not dump the logs correctly or the post processing does not parse the logs correctly?

**Comment by manopapad** [comment]
Dunno, but I included a profiler dump that should have this behavior https://github.com/StanfordLegion/legion/files/10996340/legate_0.prof.zip.

**Comment by lightsighter** [comment]
> Is it because Legion does not dump the logs correctly or the post processing does not parse the logs correctly?

It's because the profiler is not interpreting what Legion is telling it correctly.

**Comment by eddy16112** [comment]
I removed all the `map_task` boxes, and now it becomes more reasonable. If I understand it correctly, the `Mapper Continuation` under the big `map_task` box is the actual `map_task`. 
![Screenshot 2023-03-16 at 6 30 57 PM](https://user-images.githubusercontent.com/7025793/225785344-8f5b1052-cea8-4b2f-b831-28f8bd216a35.png)

**Comment by manopapad** [comment]
@lightsighter Are the "Defer Task Mapping" and "Mapper Continuation" different meta-tasks? Or part of the same meta-task?

**Comment by lightsighter** [comment]
You'll still see the `Defer Task Mapping` running even with a `Mapper Continuation` task because it needs to wait for the mapper call to finish. As I said in the Legion School, I'm planning on removing the `Mapper Continuation` tasks so you can always see the mapper calls in the middle of the actual meta-task that needs them.

**Comment by manopapad** [comment]
Leaving a link to a relevant Legion PR, that will be needed to fix this on the profiler side 
https://gitlab.com/StanfordLegion/legion/-/merge_requests/935.

**Comment by lightsighter** [comment]
The mapper continuation tasks are gone and the profiler now correctly handles waits as of the merge of this merge request:
https://gitlab.com/StanfordLegion/legion/-/merge_requests/935
