### ISSUE TITLE
RFC: Projection Function Survey

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#144]
If you have a non-trivial projection function (e.g. an explicitly registered projection function with an ID greater than 0) that you use for index space task launches, we would like to know about its properties.  We are working on some enhancements to index space launches that will significantly improve their performance and scalability, but will likely add some restrictions to what you can do with a projection function.  To avoid breaking anyone's use cases, we would like to hear about any non-trivial projection functions you have.  If you have or anticipate having a non-trivial projection function, please respond to this issue with answers to the following questions:
1. Is the upper bound for your projection function usually a region or a partition?
2. How many levels down in the region tree are the selected sub-regions from the upper bound region or partition?
3. Are all sub-regions at the same level of the region tree?
4. Can your projection function be described as an affine transformation on the color space for the upper bound region or partition?  Please provide details either way.

As an example, here are the answers for the built-in trivial projection function '0':
1. The upper bound is always a logical partition.
2. The sub-regions are always one level below the upper bound partition.
3. Yes, all sub-regions are always at the same level of the region tree.
4. Yes, this function is an affine function.  It is the identity function mapping the color space back to itself for selecting logical sub-regions.

Thanks for your input and we'll keep you apprised of our progress.

**Comment by Charles-Chao-Chen** [comment]
Below are for the projection function in my app:
1. logical partition
2. two levels below
3. yes
4. yes. It is actually the identity function, but I need to use a projection function because there is another level of partition in the middle between the upper bound region and the second level sub-regions.
