### ISSUE TITLE
Using legion to implement matrix multiplication, its execution time is much longer than that of directly using c++ code

### ISSUE THREAD

**Issue by 97CBR** [StanfordLegion/legion#1446]
I followed legion's usage tutorial. Referring to 8.Partitioning, I wrote a code for matrix multiplication of 4096 sub-matrices 256*256 double precision floats. I found that matrix multiplication using legion is far less efficient than writing code directly in C++.
On my machine, it takes only 2.37s to perform 4096 sub-matrix multiplications, while legion takes 300+s, which is incredible.
I would like to ask, what did I do wrong so that the execution efficiency of legion is so slow, or the scene where I use legion is wrong.

**Comment by elliottslaughter** [comment]
The place to start with almost any performance issue in Legion is Legion Prof, the built-in profiler:

https://legion.stanford.edu/profiling/#legion-prof

Other things you should check while you're at it:

  * Are you in debug or release mode (`DEBUG=1` or `DEBUG=0` if using Make; note that the app template defaults to debug)
  * What version of Legion are you on (branch and specific commit)?
  * What command line flags did you pass (`-ll:cpu ...` etc.)?
  * Did you observe any warnings in the output when running the program?
  * More system details like OS, compiler, hardware, etc.

Without this information we really can't help you.

**Comment by lightsighter** [comment]
I'll also add to the list, did you write a completely custom mapper? If you're relying on the default mapper for performance measurements you're going to have a bad time. Legion has a mapper interface for a reason: if you want performance at the peak of your machine then you need to say exactly how it should be mapped to that machine.

**Comment by lightsighter** [comment]
If you want to see an optimized matrix multiple written in Legion I suggest you consult cuNumeric implementation of `dot`: https://github.com/nv-legate/cunumeric/

**Comment by eddy16112** [comment]
@lightsighter do you think not using a custom mapper could lead to 130x (300/2.37) slow down compared to the c++ implementation? I understand that the default mapper is not optimal, but 300s is about 0.4 gflops, which does not sound reasonable even if running with -ll:cpu 1

**Comment by lightsighter** [comment]
There are likely other problems with the way the code has been written, but writing a tuned mapper is always a requirement for measuring peak performance with Legion, which is why I added it to the list instead of suggesting that it was the sole problem.

**Comment by alexaiken** [comment]
There are also the DISTAL distributed MM implementations:

http://theory.stanford.edu/~aiken/publications/papers/pldi22a.pdf

________________________________

**Comment by rohany** [comment]
> I followed legion's usage tutorial. Referring to 8.Partitioning, I wrote a code for matrix multiplication of 4096 sub-matrices 256*256 double precision floats. I found that matrix multiplication using legion is far less efficient than writing code directly in C++.

Something that would show up in the profiles is that your tasks are probably too small if I am understanding what you are saying. Are you 1) multiplying 4096 separate matrices of size 256 x 256? Decomposing a 4096x4096 matrix into blocks of size 256x256 and doing those multiplications in parallel?

If 1), the 256x256 multiplications are probably resulting in tasks that are too small, exposing the analysis overheads of Legion. If 2), you're partitioning the input matrix into too many pieces. Matrix multiplication is not a problem that benefits from over-decomposition, you want the tiles to be as large as possible. This particular application would do best if you partitioned the matrices into pieces equal to the number of processors you are trying to target.

**Comment by bobqianic** [comment]
> I followed legion's usage tutorial. Referring to 8.Partitioning, I wrote a code for matrix multiplication of 4096 sub-matrices 256*256 double precision floats. I found that matrix multiplication using legion is far less efficient than writing code directly in C++. On my machine, it takes only 2.37s to perform 4096 sub-matrix multiplications, while legion takes 300+s, which is incredible. I would like to ask, what did I do wrong so that the execution efficiency of legion is so slow, or the scene where I use legion is wrong.

No way, how did you achieve that man? I wrote a matrix-multiplication code using C++. With AVX2, 4096 256x256 matrix multiplication took me 42.15s on 12700H (Single Thread).

```C++
#include <iostream>
#include <vector>
#include <random>
#include <chrono>
#include <immintrin.h>
typedef std::vector<double> float_vec;
typedef std::vector<std::vector<double>> matrix;

matrix matrix_mult(matrix &a, matrix &b) {
    int size_a[2] = {static_cast<int>(a.size()), static_cast<int>(a[0].size())};
    int size_b[2] = {static_cast<int>(b.size()), static_cast<int>(b[0].size())};
    if (size_a[0] == size_b[1] and size_a[1] == size_b[0]) {
        matrix c;
        c.reserve(size_b[0]);
        float_vec temp;
        temp.reserve(size_a[1]);
        for (int z = 0; z < size_b[0]; z++) {
            temp.clear();
            for (int y = 0; y < size_a[1]; y++) {
                float sum = 0.0;
                for (int x = 0; x < size_a[0] / 8; x++) {
                    __m256 vec_a = _mm256_set_ps(a[x][y], a[x + 1][y], a[x + 2][y], a[x + 3][y], a[x + 4][y], a[x + 5][y], a[x + 6][y], a[x + 7][y]);
                    __m256 vec_b = _mm256_set_ps(b[z][x], b[z][x+1], b[z][x+2], b[z][x+3], b[z][x+4], b[z][x+5], b[z][x+6], b[z][x+7]);
                    __m256 vec_c = _mm256_mul_ps(vec_a, vec_b);
                    sum += vec_c[0] + vec_c[1] + vec_c[2] + vec_c[3] + vec_c[4] + vec_c[5] + vec_c[6] + vec_c[7];
                }
                for (int x = size_a[0] - size_a[0] % 8; x < size_a[0] % 8; x++) {
                    sum += a[x][y] * b[z][x];
                }
                temp.push_back(sum);
            }
            c.push_back(temp);
        }
        return c;
    }
    std::cout << size_a[0] << " " << size_a[1];
    throw std::logic_error("Invalid Matrix");
}

matrix get_rand_matrix(int x, int y, double min, double max) {
    matrix a;
    a.reserve(x);
    std::random_device rd;
    std::mt19937 mt(rd());
    std::uniform_real_distribution<double> dist(min, max);
    for (int i = 0; i < x; i++) {
        float_vec temp;
        temp.reserve(y);
        for (int j = 0; j < y; j++) {
            temp.push_back(dist(mt));
        }
        a.push_back(temp);
    }
    return a;
}

template <typename T>
void print_matrix(T a) {
    for (int y = 0; y < static_cast<int>(a[0].size()); y++) {
        for (int x = 0; x < static_cast<int>(a.size()); x++) {
            std::cout << a[x][y] << " ";
        }
        std::cout << std::endl;
    }
    std::cout << std::endl;
}

int main() {
    auto out_1 = get_rand_matrix(256, 256, 0, 100);
    auto out_2 = get_rand_matrix(256, 256, 0, 100);
    auto start = std::chrono::high_resolution_clock::now();
    for (int x = 0; x < 4096; x++) {
        matrix_mult(out_1,out_2);
    }
    auto end = std::chrono::high_resolution_clock::now();
    auto duration = std::chrono::duration_cast<std::chrono::microseconds>(end - start);
    if (duration.count() < 1000) {
        std::cout << duration.count() << "us" << std::endl;
    } else if (duration.count() < 1000000){
        std::cout << static_cast<float>(duration.count()) / 1000 << "ms" << std::endl;
    } else {
        std::cout << static_cast<float>(duration.count()) / 1000000 << "s" << std::endl;
    }
}
```

**Comment by rohany** [comment]
> No way, how did you achieve that man?

This is derailing the discussion, but your matrix multiply implementation is likely significantly slower than what you might find in MKL or OpenBLAS. 3.25G FLOPS sounds low.

**Comment by eddy16112** [comment]
@bobqianic "matrix multiplication of 4096 sub-matrices 256*256" means the matrix size is 4096*4096 with tile size 256*256, which is different from your code.

**Comment by 97CBR** [comment]
Thanks to everyone who helped and replied, I read and tried your method，that helped me a lot.
As I said, the reference is the code of 8.Partitioning. I just enlarged the num_elements in the code of 8.Partitioning to 4096*256*256. But the reason for the slow operation after enlarging the data is consistent with the slowness of my matrix multiplication.

After I set num_elements to 1024 * 1024 * 128, I used perf to count the running performance. Since the running time was too long, I terminated the program directly after running for 15s, and calculated the following flame graph.
As shown in the figure below, using FieldAccessor to directly access the field to write data one by one, most of the running time is spent on writing data.

![image](https://user-images.githubusercontent.com/21171109/229971282-2d24e64c-872a-4e94-a166-1c7fb1fb7443.png)

This gave me an inspiration. For a large amount of data to be written into the field, the default FieldAccessor cannot be used. It is necessary to find an accessor that can quickly access the array.
Then I queried the documentation of legion and found the key sentence
**“this code uses an AffineAccessor for the fields. Affine accessors support indexing into regions like arrays”**

Then, I modified the default FieldAccessor in INIT_FIELD_TASK_ID to
FieldAccessor<READ_WRITE,double,1,coord_t ,Realm::AffineAccessor<double,1,coord_t>>, and the FieldAccessor in DAXPY_TASK_ID still uses the default one. At this point, as expected, INIT_FIELD_TASK should have a greater access speed increase, and DAXPY_TASK will have a larger bottleneck because it uses the default FieldAccessor. Due to the relatively long calculation time, I only ran it for about 15s this time.

The result is shown in the figure below, INIT_FIELD_TASK has been completed within 15s, and DAXPY_TASK is already being executed. At this point, you can see that the read data in DAXPY_TASK has become a performance bottleneck.

![image](https://user-images.githubusercontent.com/21171109/229973785-8f701cff-38bd-44c4-a42a-7ea2e210db2c.png)

So, all this is due to my unfamiliarity with legion, but your replies have provided me with great help, thank you very much.

**Comment by rohany** [comment]
Great to hear! The physical instances that your tasks access can be backed by many different data structures, like arrays, or more complicated blocks of contiguous memory pieces. When you know that an instance will be allocated in a specific data structure (as chosen by the mapper), you can use this more specific kind of accessor (the `AffineAccessor`) to specialize the access method to the kind of data structure. `AffineAccessor` access usually compiles into a pointer dereference with all of the normal induction variable and strength reduction optimizations applied.

**Comment by 97CBR** [comment]
@rohany Yes, using AffineAccessor for access to special data structures can effectively improve read and write performance, which is not reflected in https://legion.stanford.edu/tutorial/, can we consider adding it in the tutorial How about an example or code snippet of AffineAccessor?

**Comment by lightsighter** [comment]
Accessors are discussed in more detail in Section 3.1 of the [Legion manual](https://legion.stanford.edu/pdfs/legion-manual.pdf) including the performance penalties of using the `GenericAccessor`.
