### ISSUE TITLE
How can I parallel tasks in pygion？

### ISSUE THREAD

**Issue by z778520016** [StanfordLegion/legion#1455]
I launched four tasks as below，and expected them to run in parallel，but actually the script executed in sequence order。
command:
`legion_python -ll:py 1 -ll:cpu 6 test.py`
python code：
```
from pygion import task, Future
import pygion
import time

@task
def hi(i):
    print("hello %s" % i)
    time.sleep(100)
    return i

@task
def main():
    futures = []
    for i in range(4):
        futures.append(hi(i, point=i))
    time.sleep(3)
    t1 = time.time()
    for i, future in enumerate(futures):
        print(future.get())
        assert future.get() == i
    print('total', time.time() - t1)
main()
```
output:
`total 400.31762409210205`

**Comment by z778520016** [comment]
Is it due to GIL？I expect tasks can be parallelled with the flag “-ll:cpu 6”。

**Comment by elliottslaughter** [comment]
Yes, the GIL prevents parallelism. There are a couple of options:

 1. Run multiple processes (requires GASNet or MPI). Then you do something like `mpirun -n4 legion_python ... -ll:py 1`.
 2. **Experimental**: subprocess support. Then you can do `-ll:py 4`. Note this lives in a branch that is very old. Until control_replication merges it probably won't get updated.
 3. Write leaf tasks in a language other than Python, like Regent. Regent has built in interop with Pygion so you can call Regent from Pygion and Pygion from Regent.

Note that the `-ll:cpu 4` you used didn't control Python processors at all, do that won't have an effect unless you choose route (3).

**Comment by z778520016** [comment]
OK，thank you very much。I think route (1) and route (3) can help me a lot。Route (2) can be a little hard for me as I tried but failed。

**Comment by z778520016** [comment]
experiment：answer a closed issue。
