### ISSUE TITLE
undefined reference to `Realm::ThreadPool::ThreadPool(Realm::Processor, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, unsigned long, Realm::CoreReservationSet&)'

### ISSUE THREAD

**Issue by 1193749292** [StanfordLegion/legion#1456]
Legion cmake command building

cmake .. -S /home/xxx/hpc3/legion/ -D CMAKE_INSTALL_PREFIX=../install -D REALM_USE_OPENMP=ON -D Legion_USE_OpenMP=ON -D REALM_OPENMP_SYSTEM_RUNTIME=ON -D Legion_OpenMP_SYSTEM_RUNTIME=ON -D REALM_USE_MPI=ON -DLegion_NETWORKS=mpi -D Legion_MPI_INTEROP=ON -DLEGION_REDOP_HALF=ON -DLegion_REDOP_COMPLEX=ON -DLegion_BUILD_BINDINGS=ON -DLegion_USE_Python=ON -B ../build

The following error is reported during make compilation:
---
[ 59%] Built target RealmRuntime
[ 92%] Built target LegionRuntime
[ 94%] Linking CXX shared library ../../lib/liblegion_canonical_python.so
[ 93%] Linking CXX executable ../../bin/legion_python
/usr/bin/ld: ../../lib/librealm.a(python_module.cc.o): in function `Realm::PythonThreadTaskScheduler::python_scheduler_loop()':
/home/xxx/hpc3/legion/runtime/realm/python/python_module.cc:376: undefined reference to `Realm::ThreadPool::associate_as_master()'
/usr/bin/ld: ../../lib/librealm.a(python_module.cc.o): in function `Realm::LocalPythonProcessor::LocalPythonProcessor(Realm::Processor, int, Realm::CoreReservationSet&, unsigned long, int, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)':
/home/xxx/hpc3/legion/runtime/realm/python/python_module.cc:705: undefined reference to `Realm::ThreadPool::ThreadPool(Realm::Processor, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, unsigned long, Realm::CoreReservationSet&)'
/usr/bin/ld: ../../lib/librealm.a(python_module.cc.o): in function `Realm::LocalPythonProcessor::~LocalPythonProcessor()':
/home/xxx/hpc3/legion/runtime/realm/python/python_module.cc:720: undefined reference to `Realm::ThreadPool::~ThreadPool()'
/usr/bin/ld: ../../lib/librealm.a(python_module.cc.o): in function `Realm::LocalPythonProcessor::shutdown()':
/home/xxx/hpc3/legion/runtime/realm/python/python_module.cc:738: undefined reference to `Realm::ThreadPool::stop_worker_threads()'
collect2: error: ld returned 1 exit status
make[2]: *** [bindings/python/CMakeFiles/legion_python.dir/build.make:103: bin/legion_python] Error 1
make[1]: *** [CMakeFiles/Makefile2:293: bindings/python/CMakeFiles/legion_python.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 95%] Built target legion_canonical_python
make: *** [Makefile:136: all] Error 2

**Comment by eddy16112** [comment]
@streichler Have we tested the `REALM_OPENMP_SYSTEM_RUNTIME` with `Legion_USE_Python`? The issue here is When  `REALM_OPENMP_SYSTEM_RUNTIME` is enabled, the `openmp_threadpool.cc/h` are excluded from the CMakeList.txt. 
https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/CMakeLists.txt#L129-134

**Comment by 1193749292** [comment]
@eddy16112 I understand what you said. The realm/openmp/ directory implements a set of openmp functions without libgomp.so. When Legion_OpenMP_SYSTEM_RUNTIME is set to OFF, the openmp thread pool provided by Realm is used, but this is not what I want.

**Comment by streichler** [comment]
It looks like @eddy16112 's suspicion is correct, and the python module doesn't understand the use of system openmp runtime.  This should be a relatively quick fix - will try to get it in today.

**Comment by streichler** [comment]
@1193749292 can you try cherry-picking this commit and let me know if it fixes your link issues:
https://gitlab.com/StanfordLegion/legion/-/commit/78c5f3ab9c4ea1393183ca135fbca3c403a3113b
?  Thanks!

**Comment by 1193749292** [comment]
@streichler Thank you very much, this works, the legion problem has been solved, and I'm going to compile Legate after that. (Link to the current legion through the --with-legion parameter) There are also some questions, if you're interested, the link is below.
https://github.com/nv-legate/legate.core/issues/667
