### ISSUE TITLE
examples/full_circuit cannot exit after destroying all regions

### ISSUE THREAD

**Issue by jiazhihao** [StanfordLegion/legion#146]
I tried to run full_circuit example with the up-to-date master branch. It seems the Legion runtime is able to complete top_level_task but unable to exit. I made the following changes in the Makefile:

-DEBUG           ?= 1           # Include debugging symbols
+DEBUG           ?= 0           # Include debugging symbols
 OUTPUT_LEVEL    ?= LEVEL_DEBUG # Compile time logging level
 SHARED_LOWLEVEL ?= 0           # Use shared-memory runtime (not recommended)
-USE_CUDA        ?= 0           # Include CUDA support (requires CUDA)
-USE_GASNET      ?= 0           # Include GASNet support (requires GASNet)
+USE_CUDA        ?= 1           # Include CUDA support (requires CUDA)
+USE_GASNET      ?= 1           # Include GASNet support (requires GASNet)

The command line is:

mpirun -H n0000,n0002 --bind-to none ./ckt_sim -npp 2500 -wpp 10000 -p 14 -l 5 -pct 20 -ll:csize 8192 -ll:cpu 5 -ll:fsize 3192 -ll:gpu 1 -ll:rsize 3192

**Comment by lightsighter** [comment]
Should be fixed in the master branch.  You can confirm and then close the issue.

**Comment by jiazhihao** [comment]
Commit 619d7523 fixed the bug.
