### ISSUE TITLE
Legion spackage does not allow CUDA 12

### ISSUE THREAD

**Issue by rbberger** [StanfordLegion/legion#1465]
Is this a hard restriction or just outdated?
https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/legion/package.py#L51

**Comment by lightsighter** [comment]
@pmccormick to comment.

**Comment by elliottslaughter** [comment]
Has anyone actually tested CUDA 12? We don't have it in our CI:

https://gitlab.com/StanfordLegion/legion/-/blob/master/.gitlab-ci.yml#L513-535

**Comment by lightsighter** [comment]
We use it all the time in cuNumeric/Legate.

**Comment by pmccormick** [comment]
I have used CUDA 12 a few times over the past few of weeks and had no issues.   However, it would seem wise to get it into CI before we land an update in spack.   @elliottslaughter, thoughts on the impact of a change to the current CI?  Do we need/want to test across multiple CUDA releases?

**Comment by elliottslaughter** [comment]
We currently test CUDA 10.2, 11.0 and 11.2 in CI. It runs on a machine at NVIDIA, so upgrading means finding the right person to get it set up. That used to be @streichler but I think someone else may manage it now.

**Comment by muraj** [comment]
I believe @eddy16112 has a change already to remove some really old toolkits and to set up CI to use the newer toolkits.

**Comment by rbberger** [comment]
While updating the Legion spackage, one should also add the new architectures such as `90` for hopper. One way to do this, even if you don't want to inherit from CudaPackage, would be to use:
```python
cuda_arch_list = [a for a in map(int, CudaPackage.cuda_arch_values) if a >= 60]
```
That way you'd also pick up the missing architectures in the 60, 70, and 80 series.

**Comment by elliottslaughter** [comment]
Question for NVIDIA folks @muraj @eddy16112: would you expect that Legion generally works on all new architectures without modification, or is this something we should generally validate?

E.g., for CUDA 12 we recently hit https://github.com/StanfordLegion/legion/issues/1469. That's not a showstopper, but other cases might be.

So I can see an argument for being open and letting anything go, and on the other hand for setting limits according to what we've actively tested.

@rbberger might also be interested in https://github.com/spack/spack/pull/38759 which attempts to bring the Legion spackage up to date.

**Comment by rbberger** [comment]
@elliottslaughter Thx, btw I just pushed my slingshot11 Spack changes here https://github.com/spack/spack/pull/38859

**Comment by eddy16112** [comment]
We have tested Legion against CUDA 12, and everything works.

**Comment by elliottslaughter** [comment]
> We have tested Legion against CUDA 12, and everything works.

I understand. But there's an equivalent question for CUDA architectures. E.g., if some future GPU architecture gets added, should we try to enable it by default (with the small possibility that something might break), or do we want to take the more conservative route of enabling only architectures we've explicitly tested?

**Comment by eddy16112** [comment]
We generate the PTX for the latest GPU arch (e.g. compute_90 for now), and because PTX is forwarding compatible, we should be able to run Legion on a new architecture without adding it to CMake and Makefile. However, it is better to test new architectures before adding them

**Comment by elliottslaughter** [comment]
I thought about this some more, and I think allowing any CUDA arch Spack is willing to build is fine. We'll limit on CUDA version, which already gives us some safety bounds. And Spack is hopefully smart enough to figure out what CUDA toolkits are compatible with what architectures.

I'll close this once https://github.com/spack/spack/pull/38759 merges.
