### ISSUE TITLE
CMake: FindGASNet.cmake doesn't accept ofi-slingshot11

### ISSUE THREAD

**Issue by manopapad** [StanfordLegion/legion#1468]
We are trying to pass `GASNet_CONDUIT=ofi-slingshot11` to select the appropriate specialization under https://github.com/StanfordLegion/gasnet/tree/master/configs, but `FindGASNet.cmake` has not been updated to accept the new "conduit-specialization" format, and complains that:
```
Invalid GASNet_CONDUIT setting ofi-slingshot11.  Valid options are: ofi
```

**Comment by elliottslaughter** [comment]
Are you using the embed option or not?

**Comment by manopapad** [comment]
Yes, running with embed option on.

**Comment by bryevdv** [comment]
@elliottslaughter FYI here is a patch that was needed to get embedded GasNET building with `CONDUIT=ofi-slingshot11` specified:

https://github.com/nv-legate/quickstart/pull/7/files

More or less, part of the build expects full "ofi-slingshot11" and some other part expects only "off" and that patch is a quick and dirty attempt to mediate that.

**Comment by manopapad** [comment]
@bryevdv can you please submit this patch as a merge request on https://gitlab.com/StanfordLegion/legion? Please base it on the Legion "master" branch, and assign Elliott Slaughter as reviewer.

**Comment by bryevdv** [comment]
ref: https://gitlab.com/StanfordLegion/legion/-/merge_requests/778
