### ISSUE TITLE
inlineLauncher and map_locally

### ISSUE THREAD

**Issue by zard49** [StanfordLegion/legion#147]
The following example works correctly if map_locally is true. If it is false and run on multiple
nodes then the inlineLauncher does not seem to get the data from the remote nodes.

This is with the latest from the master branch. 

[maplocal.txt](https://github.com/StanfordLegion/legion/files/348465/maplocal.txt)

**Comment by lightsighter** [comment]
There is a known bug in remote mapping.  I've added an error message if you try to remote map for now.

**Comment by lightsighter** [comment]
Remote mapping is fixed now that the versioning branch is merged into the master branch.
