### ISSUE TITLE
Performance Improvement of Legion + MPI

### ISSUE THREAD

**Issue by 1193749292** [StanfordLegion/legion#1471]
Take mpi_interop as an example to test the running duration of different processes.
```mpirun -np num  mpi_interop```
However, the performance does not seem to improve significantly. I also rewritten a demo with a large amount of computing, and the results are similar.
What are the possible causes of this phenomenon?

aarch64    Ubuntu 20.04

**Comment by elliottslaughter** [comment]
The `mpi_interop` examples doesn't do any work, so it's not obvious to me what you mean by "performance" in this case.

Did you modify the example? If so, you'll need to tell us what you did and what you expect to change with the number of ranks.

**Comment by 1193749292** [comment]
1、Build legion
```
cmake \
    -D CMAKE_INSTALL_PREFIX=../install -D REALM_USE_FFRT=ON -D Legion_USE_OpenMP=ON -D REALM_USE_OPENMP=ON -D Legion_USE_CUDA=OFF \
    -D Legion_BUILD_BINDINGS=ON -D CMAKE_BUILD_TYPE=Release -D REALM_OPENMP_SYSTEM_RUNTIME=ON -D Legion_OpenMP_SYSTEM_RUNTIME=ON \
    -D REALM_USE_MPI=ON -D Legion_NETWORKS=mpi -D Legion_MPI_INTEROP=ON -S../ -B../build;
make 
make install
```
2、demo
[realm_saxpy_cpu.zip](https://github.com/StanfordLegion/legion/files/11507648/realm_saxpy_cpu.zip)
3、outputs
[realm_saxpy_output.txt](https://github.com/StanfordLegion/legion/files/11507742/realm_saxpy_output.txt)
