### ISSUE TITLE
Does Legion support automatic task partation?

### ISSUE THREAD

**Issue by z778520016** [StanfordLegion/legion#1482]
I have runned the example code `tutorial/07_partitioning/partitioning.cc` on the cluster , but it is via manual task partation to run on distributed nodes.
I wonder whether legion supports automatic task partation for cluster nodes? If no, does legion mapper support task partation instead of partationing tasks in main program?

**Comment by rohany** [comment]
Legion will not automatically partition data for you, a higher level system will have to do that. A framework like legate (https://github.com/nv-legate/legate.core) provides a high level version of Legion's API, that includes automatic data partitioning.

**Comment by z778520016** [comment]
Thank you.I get it,i will see legate later.

**Comment by lightsighter** [comment]
It's also worth noting that [Regent has an auto-partitioning system as well](https://legion.stanford.edu/pdfs/parallelizer2019.pdf). Both Legate and Regent provide these capabilities on top of Legion because Legion will not automatically partition data and parallelize compute for you.
