### ISSUE TITLE
The circuit code in the example cannot be executed using default mapper

### ISSUE THREAD

**Issue by AngryBear2** [StanfordLegion/legion#1485]
Hello, when I use the default mapper to execute the circuit's code, I get an error about the virtual example, I don't know why.
`{runtime}: [error 67] LEGION ERROR: Invalid mapper output. Mapper Default Mapper on Processor 1d00000000000001 selected a virtual instance for region requirement 0 of task update_voltages (UID 98), but also selected variant 4 which contains a colocation constraint for this region requirement. It is illegal to request a virtual mapping for a region requirement with a colocation constraint. (from file /home/songsx/legion/legion-stable/runtime/legion/legion_tasks.cc:2550)`

**Comment by elliottslaughter** [comment]
Can you try on master? We fixed some bugs.

**Comment by elliottslaughter** [comment]
Also, as a general note, we will need more information if we're going to reproduce your issues. Usually, we'll want to see:

 * The Legion version (branch and commit ID)
 * The OS (distro and version)
 * The compiler (name and version)
 * Any relevant build settings (e.g., did you build Legion with CUDA?)
 * The command line flags to launch the application

It'll speed up the process of finding an answer if you include this in your initial issue report.

**Comment by AngryBear2** [comment]
Thank you for your help and also let me know how to ask questions.
