### ISSUE TITLE
The CUDA_GENCODE is never passed into the CMakeList.txt of Legion examples

### ISSUE THREAD

**Issue by eddy16112** [StanfordLegion/legion#1487]
I am running into a PTX issue when compiling and running Legion with CUDA 12. The problem is that we set the `CUDA_GENCODE` in the `runtime/CMakeList.txt`, but never pass it to the `CMakeList.txt` of examples, so the cuda kernels in all examples are not compiled with `-gencode`.
https://gitlab.com/StanfordLegion/legion/-/blob/master/examples/circuit/CMakeLists.txt#L32-34
Somehow, I do not know why we never catch this bug with lower version of CUDA.

Here are two ways to fix it:
1. We declare  the `CUDA_GENCODE` as `PARENT_SCOPE`, such that it can be updated in the `runtime/CMakeList.txt`, and retrieved later from other CMakeList.txt files.  This is the easiest fix, but declare a variable as `PARENT_SCOPE` is not a good behavior. 
2. We move the setting of `CUDA_GENCODE` into the top level CMakeList.txt. 

I am wondering which one should we pick? or if there is a better solution?

**Comment by lightsighter** [comment]
@elliottslaughter Can we get your input on this somewhat quickly? If we can upgrade to CUDA 12 then we can deploy the new Turing GPU machines in the CI which should produce a dramatic improvement in GPU CI throughput.

**Comment by eddy16112** [comment]
Another possible fix is this PR https://gitlab.com/StanfordLegion/legion/-/merge_requests/739, but not sure how far it is close to ready.

**Comment by eddy16112** [comment]
Here is the PR of the approach 2 https://gitlab.com/StanfordLegion/legion/-/merge_requests/810

**Comment by eddy16112** [comment]
The issue has been fixed, so close it.
