### ISSUE TITLE
Realm: slow data transposes on GPUs

### ISSUE THREAD

**Issue by mariodirenzo** [StanfordLegion/legion#1494]
In connection to issue #1493, I've been seeing very slow copies between two instances located in the same GPU memory.
These two instances have different layouts (namely XYZ for the source and YXZ for the destination). You can see some examples in the timeline at this link http://sapling2.stanford.edu/~mariodr/3DPer_Pad_GPU_mod.
With the help of @artempriakhin, I've tested the branch https://gitlab.com/StanfordLegion/legion/-/commits/cuda-dma-fix-transpose but we did not see any significant improvement.

If I perform the copies myself in HTR using some deferred buffers (as described in #1493), the application becomes much faster (see this timeline for instance http://sapling2.stanford.edu/~mariodr/3DPer_Dev_GPU).

PS: @elliottslaughter could you please add this issue to #1032 with high priority?

**Comment by streichler** [comment]
@artempriakhin are we able to reproduce this in a standalone realm test?

**Comment by apryakhin** [comment]
Yes, we do. One of the transpose copies HTR is doing involves XYZ to YXZ (63x128x129 approx.) of vec[3] field type which is 24-byte wide. The hand-written transpose cuda kernel is only able to handle up to 16-byte wide field types and for the rest we fallback to the legacy cuda-driver path (and that's what we do in HTR). The legacy path involves looping and invoking cuMemcpy2D which is obviously slow and cuMemcpy3DAsync (which we introduced with cuda-dma) isn't handling this properly (hasn't gotten it working yet). So, for the cuda-dma there are two ways forward on this as I see it: one is to make cuda-transpose kernel handle "large"/arbitrary field sizes and/or two is to figure out whether cuMemcpy3DAsync can replace a set of 2D memcopies here and be in fact faster (Cory and myself are looking into it now).

We have all the realm tests for this now (for which we hit multiple bugs in HTR). The work so far has been done to make it all functionally correct (e.g. no crashes or bad app data)...but obviously the main objective is to speed this case up with cuda-dma and this is something that needs a bit more attention.

**Comment by streichler** [comment]
can we get the current kernel to work if we tell it that the 24-byte elements are actually 8 bytes in size and that there's an additional dimension with an extent of 3 and stride of 8?

**Comment by apryakhin** [comment]
Yes, we can and this something I was in fact trying to get up and running for this exact case with 24-bytes and 8 byte chunks. It's somewhat tricky to get right thought but that's in progress.

**Comment by mariodirenzo** [comment]
@apryakhin I've tested the new version of `cuda-dma-fix-transpose` and the execution is slower than before.
The version of HTR that performs the copies takes about 7s to complete its execution, the execution with the legacy version of Realm GPU copies takes about 43s, and the new version of `cuda-dma-fix-transpose` takes about 51s.
Unfortunately, I can't show any profile timeline with `cuda-dma-fix-transpose` because the profiler is broken on that branch.
Is there anything that I can do to make sure that the code is utilizing your new implementation?

**Comment by apryakhin** [comment]
Thanks! Yes, this is not what I expect as a result. I think the dma should still be falling back to the slow path for some reason. I would need logs with gpudma=1 to verify that. Since sapling1 is deprecated I don't have a preped environment to run it myself and therefore need to set everything up again. Let me build HTR on my workstation to see if I can nail it down.

**Comment by apryakhin** [comment]
Just an update on this. 

There is an edge case that is failing and blocking the release of the patch for cuda-dma. In particular, "complex field types" 24B/40B for shapes that are not multiple to the `tile_size` (x-dim of the shared memory we use in the transpose kernel). 
I am running on sapling2 and get the following (unformatted copy-past below):

prometeo_variables.hpp:183: static void UpdatePrimitiveFromConservedTask::UpdatePrimitive(const Legion::FieldAccessor<(legion_privilege_mode_t)1, MyArray<double, 5>, 3, long long, Realm::AffineAccessor<MyArray<double, 5>, 3, long long>, true> &, const Legion::FieldAccessor<(legion_privilege_mode_t)7, double, 3, long long, Realm::AffineAccessor<double, 3, long long>, true> &, const Legion::FieldAccessor<(legion_privilege_mode_t)268435458, double, 3, long long, Realm::AffineAccessor<double, 3, long long>, true> &, const Legion::FieldAccessor<(legion_privilege_mode_t)268435458, MyArray<double, 1>, 3, long long, Realm::AffineAccessor<MyArray<double, 1>, 3, long long>, true> &, const Legion::FieldAccessor<(legion_privilege_mode_t)268435458, MyArray<double, 3>, 3, long long, Realm::AffineAccessor<MyArray<double, 3>, 3, long long>, true> &, const Realm::Point<3, long long> &, const Mix &): block: [1,1,0], thread: [0,0,0] Assertion `mix.CheckMixture(Yi)` failed.
prometeo_variables.hpp:183: static void UpdatePrimitiveFromConservedTask::UpdatePrimitive(const Legion::FieldAccessor<(legion_privilege_mode_t)1, MyArray<double, 5>, 3, long long, Realm::AffineAccessor<MyArray<double, 5>, 3, long long>, true> &, const Legion::FieldAccessor<(legion_privilege_mode_t)7, double, 3, long long, Realm::AffineAccessor<double, 3, long long>, true> &, const Legion::FieldAccessor<(legion_privilege_mode_t)268435458, double, 3, long long, Realm::AffineAccessor<double, 3, long long>, true> &, const Legion::FieldAccessor<(legion_privilege_mode_t)268435458, MyArray<double, 1>, 3, long long, Realm::AffineAccessor<MyArray<double, 1>, 3, long long>, true> &, const Legion::FieldAccessor<(legion_privilege_mode_t)268435458, MyArray<double, 3>, 3, long long, Realm::AffineAccessor<MyArray<double, 3>, 3, long long>, true> &, const Realm::Point<3, long long> &, const Mix &): block: [0,0,0], thread: [2,0,0] Assertion `mix.CheckMixture(Yi)` failed.

[0 - 7f8b53058840]    1.022266 {6}{gpu}: CUDA error reported on GPU 0: device-side assert triggered (CUDA_ERROR_ASSERT)
prometeo_ConstPropMix.exec: /home/apriakhin/Development/tmp/legion3/runtime/realm/cuda/cuda_module.cc:352: bool Realm::Cuda::GPUStream::reap_events(Realm::TimeLimit): Assertion `0' failed.

I am able to isolate the problem on sapling2/HTR. Unfortunately, the exact cases covered in realm tests are passing (on my workstation) but failing when running HTR on sapling2.

**Comment by mariodirenzo** [comment]
@apryakhin, the assertion `Assertion mix.CheckMixture(Yi) failed.` usually means that something has gone very wrong in the calculation and the code crashed with a `NaN`.
Is there anything I can do to help isolating the copy that goes bad?

**Comment by apryakhin** [comment]
I got it fixed and run a few benchmarks

For example one of them (sapling2):
`solverTests/3DPeriodic xNum:128, yNum:128, zNum:64`

legacy
```
/home/apriakhin/Development/htr3/src/prometeo_ConstPropMix.exec -i base.json -logfile %.log -lg:registration -ll:force_kthreads -logfile ./%.log -lg:safe_ctrlrepl 2 -ll:cpu 1 -ll:ocpu 2 -ll:onuma 1 -ll:othr 9 -ll:ostack 8 -ll:gpu 4 -ll:fsize 14000 -ll:zsize 512 -ll:ib_zsize 512 -ll:util 4 -ll:io 4 -ll:bgwork 4 -ll:cpu_bgwork 100 -ll:util_bgwork 100 -ll:csize 220000 -ll:rsize 512 -ll:ib_rsize 512 -ll:gsize 0 -ll:stacksize 8 -lg:sched -1 -lg:hysteresis 0
Launched: 1 Total time: 24.769 seconds
```

and with cuda-dma
```
/home/apriakhin/Development/htr3/src/prometeo_ConstPropMix.exec -i base.json -logfile %.log -lg:registrationsolverTests/3DPeriodicsolverTests/3DPeriodicsolverTests/3DPeriodicsolverTests/3DPeriodicsolverTests/3DPeriodicsolverTests/3DPeriodicsolverTests/3DPeriodic -ll:force_kthreads -logfile ./%.log -lg:safe_ctrlrepl 2 -ll:cpu 1 -ll:ocpu 2 -ll:onuma 1 -ll:othr 9 -ll:ostack 8 -ll:gpu 4 -ll:fsize 14000 -ll:zsize 512 -ll:ib_zsize 512 -ll:util 4 -ll:io 4 -ll:bgwork 4 -ll:cpu_bgwork 100 -ll:util_bgwork 100 -ll:csize 220000 -ll:rsize 512 -ll:ib_rsize 512 -ll:gsize 0 -ll:stacksize 8 -lg:sched -1 -lg:hysteresis 0
Launched: 1 Total time: 3.447 seconds
```

**Comment by mariodirenzo** [comment]
This issue has been fixed. Thanks for the help!
