### ISSUE TITLE
Legion: hip runtime not found with CMake

### ISSUE THREAD

**Issue by syamajala** [StanfordLegion/legion#1496]
Something has broken in the CMake file in the latest control replication. I am unable to build and see the following error:

```
/lustre/orion/cmb138/scratch/seshuy/legion_s3d_rocm51/legion/runtime/legion/runtime.cc:49:10: fatal error: 'hip/hip_runtime.h' file not found
#include <hip/hip_runtime.h>
```

**Comment by eddy16112** [comment]
Have you set the HIP_PATH? https://gitlab.com/StanfordLegion/legion/-/blob/master/cmake/FindHIP.cmake#L18

**Comment by syamajala** [comment]
Yes this happens in the middle of the build after realm builds. Realm would not build if the hip variables were not set correctly. If I go back to an older commit it builds as well. Something changed in the past few days with CMake.

**Comment by syamajala** [comment]
Here is what I see when I build realm for example:
```
[ 60%] Building CXX object runtime/CMakeFiles/RealmRuntime.dir/realm/hip/hip_hijack.cc.o
cd /lustre/orion/cmb138/scratch/seshuy/legion_s3d_rocm51_trace/legion/language/build/runtime && /opt/cray/pe/craype/2.7.19/bin/CC -DGASNETI_BUG1389_WORKAROUND=1 -DGASNET_PAR -DRealmRuntime_EXPORTS -D_GNU_SOURCE=1 -D_REENTRANT -D__HIP_PLATFORM_AMD__ -I/opt/rocm-5.1.0/hip/include -I/opt/rocm-5.1.0/hip/../include -I/lustre/orion/cmb138/scratch/seshuy/legion_s3d_rocm51_trace/legion/runtime -I/lustre/orion/cmb138/scratch/seshuy/legion_s3d_rocm51_trace/legion/language/build/runtime -isystem /lustre/orion/cmb138/scratch/seshuy/legion_s3d_rocm51_trace/gasnet/release/include -isystem /lustre/orion/cmb138/scratch/seshuy/legion_s3d_rocm51_trace/gasnet/release/include/ofi-conduit -DLEGION_SEPARATE_META_TASKS -march=native -mabi=altivec -O2 -g -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Woverloaded-virtual -MD -MT runtime/CMakeFiles/RealmRuntime.dir/realm/hip/hip_hijack.cc.o -MF CMakeFiles/RealmRuntime.dir/realm/hip/hip_hijack.cc.o.d -o CMakeFiles/RealmRuntime.dir/realm/hip/hip_hijack.cc.o -c /lustre/orion/cmb138/scratch/seshuy/legion_s3d_rocm51_trace/legion/runtime/realm/hip/hip_hijack.cc
```

vs legion:
```
[ 89%] Building CXX object runtime/CMakeFiles/LegionRuntime.dir/legion/runtime.cc.o
cd /lustre/orion/cmb138/scratch/seshuy/legion_s3d_rocm51_trace/legion/language/build/runtime && /opt/cray/pe/craype/2.7.19/bin/CC -DLegionRuntime_EXPORTS -DUSE_HIP -I/lustre/orion/cmb138/scratch/seshuy/legion_s3d_rocm51_trace/legion/runtime -I/lustre/orion/cmb138/scratch/seshuy/legion_s3d_rocm51_trace/legion/language/build/runtime -DLEGION_SEPARATE_META_TASKS -march=native -mabi=altivec -O2 -g -fPIC -MD -MT runtime/CMakeFiles/LegionRuntime.dir/legion/runtime.cc.o -MF CMakeFiles/LegionRuntime.dir/legion/runtime.cc.o.d -o CMakeFiles/LegionRuntime.dir/legion/runtime.cc.o -c /lustre/orion/cmb138/scratch/seshuy/legion_s3d_rocm51_trace/legion/runtime/legion/runtime.cc
```

Its clear that the hip headers arent being added to the include flags for legion for some reason.

**Comment by syamajala** [comment]
We are never going down this path:
https://gitlab.com/StanfordLegion/legion/-/blob/control_replication/runtime/CMakeLists.txt#L842

LEGION_HIP_SRC is only non-empty if you set Legion_GPU_REDUCTIONS:
https://gitlab.com/StanfordLegion/legion/-/blob/control_replication/runtime/CMakeLists.txt#L774-778

**Comment by syamajala** [comment]
@elliottslaughter maybe install.py should turn this on by default if you're building with hip? 

Also could we update setup_env.py to include Thrust? I have been building without complex reductions for a long time now and have a patch that turns it off completely in the CMake file and in the regent compiler, but other people want to start building S3D on Frontier so it would be nice if it just worked out of the box without having to deal with Thrust manually. I myself was never able to figure out how to get thrust to work, which is why I just turn off complex reductions.

**Comment by elliottslaughter** [comment]
Ok, I see the Crusher CI started failing 2 weeks ago and I didn't notice:

  * Last passing CI: https://code.olcf.ornl.gov/ci/csc335/dev/legion/-/pipelines/4808
  * First failing CI: https://code.olcf.ornl.gov/ci/csc335/dev/legion/-/pipelines/4866

The failing commit appears to be: 70e67dfebe80fcb174014132e9b42c83d1ac2178 ([gitlab](https://gitlab.com/StanfordLegion/legion/-/commit/70e67dfebe80fcb174014132e9b42c83d1ac2178))

**Comment by syamajala** [comment]
Any fix for this?

**Comment by eddy16112** [comment]
I think this is a bug in our cmake. The reason why `USE_CUDA` works is because `cuda.h` is installed in `/usr/include or /usr/local/include`. @syamajala can you please try to add `target_include_directories(LegionRuntime PRIVATE ${HIP_INCLUDE_DIRS})` after this line https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/CMakeLists.txt#L535?

**Comment by syamajala** [comment]
I don't think thats the right place for it. I'm seeing this:
```
CMake Error at runtime/CMakeLists.txt:536 (target_include_directories):                                                                                                                                                                                        
  Cannot specify include directories for target "LegionRuntime" which is not                                                                                                                                                                                   
  built by this project.                                                                                                                                                                                                                                       
```

**Comment by syamajala** [comment]
> We are never going down this path: https://gitlab.com/StanfordLegion/legion/-/blob/control_replication/runtime/CMakeLists.txt#L842
> 
> LEGION_HIP_SRC is only non-empty if you set Legion_GPU_REDUCTIONS: https://gitlab.com/StanfordLegion/legion/-/blob/control_replication/runtime/CMakeLists.txt#L774-778

@eddy16112 it is there already: https://gitlab.com/StanfordLegion/legion/-/blob/control_replication/runtime/CMakeLists.txt#L899

But unless you set Legion_GPU_REDUCTIONS you never end up going down that path. Maybe we need to update install.py @elliottslaughter?

**Comment by elliottslaughter** [comment]
I could be wrong but it looks like it's conditional on `Legion_REDOP_COMPLEX`, which we already set (unless you turned it off).

**Comment by syamajala** [comment]
I have never been able to get Thrust to work so I turn off `Legion_REDOP_COMPLEX`.

**Comment by elliottslaughter** [comment]
Oh, sorry, I missed the `else()` on the line above. So this is unrelated to `Legion_REDOP_COMPLEX`.

I think you're right that it's based on `LEGION_HIP_SRC` which depends on `Legion_GPU_REDUCTIONS`. But your compile error is in `runtime.cc`. So clearly, even when we have no GPU reductions, we still need this header.

You could try adding something at this line:

https://gitlab.com/StanfordLegion/legion/-/blob/control_replication/runtime/CMakeLists.txt#L903

Maybe:

```
else()
  if (Legion_HIP_TARGET STREQUAL "ROCM")
    target_include_directories(LegionRuntime PRIVATE ${HIP_INCLUDE_DIRS})
    target_compile_definitions(LegionRuntime PRIVATE __HIP_PLATFORM_AMD__)
  endif()
endif()
```

**Comment by elliottslaughter** [comment]
Ok, can you send a PR to Gitlab?

**Comment by syamajala** [comment]
Pull request is here: https://gitlab.com/StanfordLegion/legion/-/merge_requests/853
