### ISSUE TITLE
Pygion: Region field KeyError in extern task called from Regent

### ISSUE THREAD

**Issue by CharlelieLrt** [StanfordLegion/legion#1498]
I have a top-level task implemented in Regent which calls some external leaf tasks implemented in Pygion. These tasks take as arguments multiple regions (defined in Regent). However, when trying to access the field `time` inside a Pygion task in one of these regions (named `MembersStates`) I am getting the following error:

```
Traceback (most recent call last):
  File "/usr/workspace/laurent3/Codes/LIBRARIES/PYGION_LIBS/LEGION_30012023/bindings/python/pygion.py", line 1803, in __call__
    return self.execute_task(*args, **kwargs)
  File "/usr/workspace/laurent3/Codes/LIBRARIES/PYGION_LIBS/LEGION_30012023/bindings/python/pygion.py", line 1910, in execute_task
    result = self.body(*args)
  File "/p/gpfs1/laurent3/REnFc/07_DEV_INT4D/src/maestro/pyworkers/save_outputs.py", line 68, in PygionSaveProbesToNumpy
    d = getattr(MembersStates, k)
  File "/usr/workspace/laurent3/Codes/LIBRARIES/PYGION_LIBS/LEGION_30012023/bindings/python/pygion.py", line 1175, in __getattr__
    self.instance_wrappers[field_name] = RegionField(
  File "/usr/workspace/laurent3/Codes/LIBRARIES/PYGION_LIBS/LEGION_30012023/bindings/python/pygion.py", line 1186, in __new__
    initializer = RegionField._get_array_initializer(region, field_name, accessor)
  File "/usr/workspace/laurent3/Codes/LIBRARIES/PYGION_LIBS/LEGION_30012023/bindings/python/pygion.py", line 1238, in _get_array_initializer
    field_type = region.fspace.field_types[field_name]
KeyError: 'time'
maestro.exec: /usr/WS1/laurent3/Codes/LIBRARIES/PYGION_LIBS/LEGION_30012023/runtime/realm/python/python_module.cc:996: virtual void Realm::Lo
lPythonProcessor::execute_task(Realm::Processor::TaskFuncID, const Realm::ByteArrayRef&): Assertion `0' failed.
```

This is surprising to me, as adding this line in the Pygion task:

```python
print("MembersStates fields: ", MembersStates.keys(), flush=True)
```

gives `MembersStates fields:  odict_keys(['time', 'dt', 'iteration', 'total_iterations', 'is_running', 'is_Nan', 'nb_resets', 'tile_id'])`, which suggests that the field `time` should exist in this region. The error is the same for all other fields of this region. However, I am able to access fields of other region parameters in this task.

The fspace used in Regent to define this Region is a Terra struct:

```
struct vars_MembersStates {
   time : double;
   dt : double;
   iteration : int32;
   total_iterations : int32;
   is_running : bool;
   is_Nan : bool;
   nb_resets : int32;
   tile_id : int4d;
 }
``` 

The only difference I can find between this specific region causing the bug and other regions is that the Fspace of this region mixes multiple types (double, int32, int4d, bool), whereas field spaces of other regions are either only double or int. I am not sure whether this is a concern or not...

Any insight on this would be more than welcome!

**Comment by CharlelieLrt** [comment]
Here is a small reproducer (I don't think it requires the `int4d` index spaces, so changing everything to `int3d` should be fine as well).
It simply runs with: `regent.py main.rg -ll:py 1 -ll:pyimport python_main`

`main.rg` :

```lua
import 'regent'

struct fs_doubles {
   a : double;
   b : double;
}

struct fs {
   time : double;
   iteration : int;
   is_running : bool;
   tile_id : int4d;
}

__demand(__leaf)
extern task PygionTask(R: region(ispace(int4d), fs_doubles),
                       MembersStates: region(ispace(int4d), fs),
                       S: region(ispace(int4d), int),
                       i: int32)
where
   reads(R),
   reads(MembersStates),
   reads writes(S)
end
PygionTask:set_task_id(9000)


__demand(__cuda, __leaf)
task InitMembersStates(MembersStates: region(ispace(int4d), fs))
where
   writes(MembersStates)
do
   __demand(__openmp)
   for c in MembersStates do
      MembersStates[c].time = 0.0
      MembersStates[c].iteration = 0
      MembersStates[c].is_running = true
      MembersStates[c].tile_id = c
   end
end


__demand(__cuda, __leaf)
task Inc(R: region(ispace(int4d), fs_doubles),
         MembersStates: region(ispace(int4d), fs))
where
   reads writes(R),
   reads writes(MembersStates)
do
   __demand(__openmp)
   for c in R do
      R[c].a += 1.0
      R[c].b *= 1.5
   end

   __demand(__openmp)
   for c in MembersStates do
      MembersStates[c].time += 1.0
      MembersStates[c].iteration += 1
      MembersStates[c].is_running = (MembersStates[c].is_running and
         (MembersStates[c].iteration < 5))
   end
end


__demand(__inner)
__forbid(__replicable)
task main()

   var cells = ispace(int4d, {16, 16, 16, 1})
   var tiles = ispace(int4d, {2, 2, 2, 1})
   var workers = ispace(int4d, {2, 1, 1, 1})
   var R = region(cells, fs_doubles)
   var MembersStates = region(tiles, fs)
   var S = region(workers, int)
   var Tiles_R = partition(equal, R, tiles)
   var Tiles_MembersStates = partition(equal, MembersStates, tiles)
   var Workers_R = partition(equal, R, workers)
   var Workers_MembersStates = partition(equal, MembersStates, workers)
   var Workers_S = partition(equal, S, workers)

   __demand(__index_launch)
   for c in tiles do
      fill((Tiles_R[c]).a, 0.0)
   end
   __demand(__index_launch)
   for c in tiles do
      fill((Tiles_R[c]).b, 0.0)
   end
   __demand(__index_launch)
   for c in workers do
      fill((Workers_S[c]), 0)
   end
   __demand(__index_launch)
   for c in tiles do
      InitMembersStates(Tiles_MembersStates[c])
   end

   var i = 0

   __demand(__index_launch)
   for c in tiles do
      Inc(Tiles_R[c], Tiles_MembersStates[c])
   end

   i += 1

   __demand(__index_launch)
   for c in workers do
      PygionTask(Workers_R[c], Workers_MembersStates[c], Workers_S[c], i)
   end

end

regentlib.start(main)
```

`python_main.py` :

```python
from pygion import task, R, RW, Region, int32, void
import numpy as np


@task(task_id=9000,
      argument_types=[Region, Region, Region, int32],
      privileges=[R, R, RW],
      return_type=void,
      leaf=True,
      calling_convention='regent')
def PygionTask(R, MembersStates, S, i): 
    print(f"Iteration : {i}")
    print("R fields: ", R.keys(), flush=True)
    print("S fields: ", S.keys(), flush=True)
    print("MembersStates fields: ", MembersStates.keys(), flush=True)
    print("R.a sum = ", np.sum(R.a), flush=True)
    print("MembersStates.time sum = ", np.sum(MembersStates.time),
          flush=True)
```

In addition, I tried a few things and I think the error is definitely coming from the `int4d` field `tile_id`. If I change this field to an `int`, everything is working fine. Using `int4d`, `int3d`, etc... for `tile_id` gives the same error.

**Comment by elliottslaughter** [comment]
The issue is literally that `intNd` types are not supported in the interface between Regent and Pygion:

https://github.com/StanfordLegion/legion/blob/5b6f90d900f184d4a060fc4f83e94516328e83e4/bindings/python/pygion.py#L499-L510

I'll work on this.

**Comment by elliottslaughter** [comment]
Testing a fix here: https://gitlab.com/StanfordLegion/legion/-/merge_requests/829

**Comment by CharlelieLrt** [comment]
Maybe a naive question, but I was looking at your commits and I am wondering why the intNd types are redefined twice (but with different C types): [there](https://gitlab.com/StanfordLegion/legion/-/blob/5d628142d4d80de6475d05922537b6e3e7e0c456/bindings/python/pygion.py#L535) and [there](https://gitlab.com/StanfordLegion/legion/-/blob/5d628142d4d80de6475d05922537b6e3e7e0c456/bindings/python/pygion.py#L522-530)

**Comment by elliottslaughter** [comment]
Good catch, thanks.

**Comment by CharlelieLrt** [comment]
I tested the fix and the error is gone.

However, there is a detail that is a little confusing to me.
To access the field `time` (which is a `double`) at the index `[0, 0, 0, 0]` I would simply use: `MembersStates.time[0, 0, 0, 0]`. This works and makes sense to me.

But this does not translate to access the field `tile_id` (which is in this case `int3d`). Using `MembersStates.tile_id[0, 0, 0, 0]` gives a `numpy.void` object with value `([0, 0, 0],)`. To actually access the `int3d` of index  `[0, 0, 0, 0]` I need to use: `MembersStates.tile_id[0, 0, 0, 0][0]`.

So I am wondering what is this additional index `[0]` for? Is it there by design?

**Comment by CharlelieLrt** [comment]
Maybe I went a little too fast. The reproducer above is still giving a similar error, but now because of the field `is_running`, which is a bool.

**Comment by elliottslaughter** [comment]
I merged your MR. Let me know if there is anything else.

**Comment by CharlelieLrt** [comment]
Everything works for me now. I noticed that the rectNd are also missing from the interface, but I am not using those (and I don't think it's a very common use case to have rectNd as fields in a region).
Just to clarify [my comment](https://github.com/StanfordLegion/legion/issues/1498#issuecomment-1617055192) above: is it a bug or by design?

**Comment by elliottslaughter** [comment]
Sorry, right. `int3d` is effectively a `struct { x: int64[3] }` so in NumPy you need to access it as either `value[0]` or `value['x']`. My understanding is that NumPy does not have a way to directly make a `int64[3]` as a value *inside* of an array, so the field `x` is mandatory. (I.e., every NumPy composite data type *must* be a struct.)

**Comment by CharlelieLrt** [comment]
Ok, thanks for the clarification, that makes sense now. I'll close the issue and re-open later if I find something else missing in the interface for my use cases.
