### ISSUE TITLE
DeferredBuffers cannot be created in an implicit top-level task

### ISSUE THREAD

**Issue by magnatelee** [StanfordLegion/legion#1504]
There are currently two problems with deferred buffers in implicit top-level tasks (which should exist for any container types backed by task-local instances):

1) Some of the constructors are querying the target memory using `Realm::Processor::get_executing_processor`, which returns a non-existent handle on implicit top-level tasks.
2) Even after we replace the processor query with `Legion::Runtime::get_executing_processor`, Legion crashes while it's trying to create a task local instance.

Here's a reproducer, a diff to make it pass problem (1), and a stacktrace:

https://gist.github.com/magnatelee/8215f0df4f24566007672d92149cf73f

**Comment by eddy16112** [comment]
The segfault is because Legion tries to call `Realm::Processor::get_current_finish_event()` within the implicit top level task. However, this call should be only called from a real Realm task, because the `ThreadLocal::current_thread` is `NULL` in the main function.

**Comment by lightsighter** [comment]
This is at least the third bug that I've gotten because we haven't done #716. Each time my solutions get more and more esoteric and cause more and more problems inside of Legion. At this point I'm going to insist on having #716 so we can stop experiencing these issues on the Legion side.

**Comment by magnatelee** [comment]
I agree that Realm should provide a mechanism to handle external threads more gracefully, but we also need a fix now, as all deferred containers are broken. let me give this a shot while you're gone.

**Comment by lightsighter** [comment]
@magnatelee What do you expect to happen when you make a deferred buffer on a GPU in an implicit top-level task, call a GPU kernel that you pass that buffer to, and then end the implicit top-level task before synchronizing on the kernel?

**Comment by magnatelee** [comment]
@lightsighter I would expect it to behave the same as a normal GPU task creating a deferred buffer inside; i.e., a task-local instance backing the buffer would be destroyed once all the kernels are done.

**Comment by magnatelee** [comment]
I guess making sure all kernels are done from the realm side would look ugly with an implicit top-level task, as that would need to happen as part of the `wait_for_shutdown` call in the top-level task, right? the boundary of an implicit top-level task seems a bit loosely defined.

**Comment by lightsighter** [comment]
> I guess making sure all kernels are done from the realm side would look ugly with an implicit top-level task, as that would need to happen as part of the wait_for_shutdown call in the top-level task, right? the boundary of an implicit top-level task seems a bit loosely defined.

At a minimum that requires the creation of Realm implicit tasks since Realm is the only thing with knowledge of CUDA and the ability to either track outstanding kernels or do the implicit synchronization for them.

**Comment by magnatelee** [comment]
> At a minimum that requires the creation of Realm implicit tasks since Realm is the only thing with knowledge of CUDA and the ability to either track outstanding kernels or do the implicit synchronization for them.

agreed. realm should add a notion of implicit tasks so legion implicit tasks behave just like normal legion tasks. otherwise, the former will never be able to match the latter in terms of functionality.

that said, at the minimum we should raise errors if clients try to create deferred containers in an implicit task. my preference, which I was planning to create a merge request for, is to support them on CPUs. what do you think is the right course of action?

**Comment by lightsighter** [comment]
This is fixed in Legion with [this merge request](https://gitlab.com/StanfordLegion/legion/-/merge_requests/944#fe9722b875a25ecc83f6ad8d08a966d81fbdb4bd). It does require users to pass in a Realm event for the completion effects of any asynchronous operations that they perform during the implicit top-level task. Getting the Realm event from CUDA streams will still require [this merge request](https://gitlab.com/StanfordLegion/legion/-/merge_requests/943). Assigning to @muraj to finish the second merge request and @magnatelee to confirm.

**Comment by lightsighter** [comment]
Both merge requests for supporting this have been merged so closing.
