### ISSUE TITLE
Failing Regent HDF5 test

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1512]
This test failure appears to be deterministic, because repeatedly rerunning the test does not get around it:

  * https://gitlab.com/StanfordLegion/legion/-/jobs/4718634117
  * https://gitlab.com/StanfordLegion/legion/-/jobs/4718597600
  * https://gitlab.com/StanfordLegion/legion/-/jobs/4718587476

I'm not aware of anything that has changed recently in Regent except eliding future maps. Definitely nothing has changed with respect to HDF5.

@lightsighter do you know what is going on?

CC @eddy16112

**Comment by lightsighter** [comment]
Regent stopped providing a physical region to release operations:

https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/legion.h#L3810

Which is technically allowed, but was untested prior to this. It would have been good if whoever made this change actually tested it in a branch before they merged it.

**Comment by lightsighter** [comment]
Actually that might not be the problem. Legion Spy is validating an execution from a failing run, so something is definitely broken in Realm.

**Comment by lightsighter** [comment]
The fact that it happens in both master and control replication which have completely different physical analyses also suggests that the problem is in Realm.

**Comment by elliottslaughter** [comment]
Sounds like you're on the right track, but just to make this explicit: nothing about how Regent is doing any of this has changed recently. The basic approach to handling attach/detach, whether it's the most desired way of doing it in Legion or not, has been basically constant in the compiler for over 5 years.

**Comment by lightsighter** [comment]
Which is also consistent with the failure being in Realm.

> The basic approach to handling attach/detach

Note that acquire/release is also involved here as well, but I still think the problem is in Realm.

**Comment by lightsighter** [comment]
> This test failure appears to be deterministic, because repeatedly rerunning the test does not get around it:

It's worth noting that this is not true. The failure is non-deterministic because the same tests don't fail every time. Just at least one of them fails every time.

I think @eddy16112 has a lead on the bad commit in Realm that is causing problems.

**Comment by streichler** [comment]
@eddy16112 if we have a bad commit, can we just revert it to get things unblocked?

**Comment by lightsighter** [comment]
@muraj is debugging this now to figure out exactly which commit the problem is. It's not entirely obvious what the source of the problem is: whether it is the caching allocator commit, or a commit that pinned gasnet to particular commit.

**Comment by elliottslaughter** [comment]
> or a commit that pinned gasnet to particular commit.

FYI: The commit I pinned was the most recent, so it should have made no difference to what we were running in CI.

**Comment by lightsighter** [comment]
@eddy16112 did some delta debugging that suggested that was actually the failing commit, but the failures are non-deterministic so it might be a false positive.

**Comment by elliottslaughter** [comment]
The most recent GASNet repo commit was on May 26: https://github.com/StanfordLegion/gasnet. I don't think we've been seeing these failures that long?

The commit to pin only changed our tests to explicitly pick that commit (which was previously pulled in by default): https://gitlab.com/StanfordLegion/legion/-/commit/8f8225d139e586e15e63c1e15be33ca6af573838

I have a really hard time seeing how the pinning mechanism itself would cause this. Since the commit itself wouldn't have changed, I just can't see a way for this to break without causing a build error.

We've definitely seen nondeterministic errors that become nearly impossible to reproduce outside of CI. That seems far easier to believe given the lack of apparent mechanism here.

**Comment by elliottslaughter** [comment]
The caching allocator has been disabled by default in `master`, right? Master still fails, so I think that indicates that the caching allocator isn't the problem, unless the issue is in some other part of the commit not behind the flag.

https://gitlab.com/StanfordLegion/legion/-/jobs/4765619221

I could prepare a branch to test unpinned GASNet, but I wonder if we're just barking up totally the wrong tree at this point?

**Comment by lightsighter** [comment]
I agree, it is probably not GASNet, and it is also definitely not the caching allocator. I confirmed that it happens in both the `master` and `control_replication` branches with the caching allocator disabled. I also confirmed that I can produce Legion Spy logs from failing runs in both branches that are validated by Legion Spy.  Here is the Realm event graph that Legion produced:
[event_graph_main_4.pdf](https://github.com/StanfordLegion/legion/files/12208324/event_graph_main_4.pdf)

@eddy16112 how were you doing your bisect? Were you accounting for the non-determinism of the failures?
@muraj is also debugging this from the Realm side.

**Comment by lightsighter** [comment]
Actually, I think I see the problem. @elliottslaughter how do you make sure that the different sub-tests using the same HDF5 file don't interfere with each other? Legion doesn't track dependences on files, so it's possible for two attaches to the same file to have occurred at the same time. Look at the Realm event graph. If some of the later attaches to the same file happen early, they might still see data that is in the process of being modified. For example, what prevents these two sub-tests from interfering with each other?

https://gitlab.com/StanfordLegion/legion/-/blob/master/language/tests/hdf5/run_pass/attach_hdf5.rg#L110-121
and
https://gitlab.com/StanfordLegion/legion/-/blob/master/language/tests/hdf5/run_pass/attach_hdf5.rg#L123-134

They're attaching and detaching the same file, but nothing stops Legion from running ahead and allowing both tests to attach and use the same file concurrently. If I apply the following diff, then the test passes deterministically:

```
diff --git a/language/tests/hdf5/run_pass/attach_hdf5.rg b/language/tests/hdf5/run_pass/attach_hdf5.rg
index e622524df..e887b0944 100644
--- a/language/tests/hdf5/run_pass/attach_hdf5.rg
+++ b/language/tests/hdf5/run_pass/attach_hdf5.rg
@@ -120,6 +120,8 @@ task main()
     detach(hdf5, r2.{a, b, c})
   end
 
+  regentlib.c.legion_runtime_issue_execution_fence(__runtime(), __context())
+
   -- test 3: write different data and then re-attach - should see old data
   --  (from test 2) use acquire/release this time to allow an implicit copy
   if true then
@@ -133,6 +135,8 @@ task main()
     detach(hdf5, r2.{a, b, c})
   end
 
+  regentlib.c.legion_runtime_issue_execution_fence(__runtime(), __context())
+
   -- test 4: use explicit copies (no acquire/release needed)
   if true then
     regentlib.c.printf("test 4\n")
```

I think we just perturbed the timing with some changes in Realm and that then uncovered this race that was always silently lurking.

**Comment by elliottslaughter** [comment]
The idiomatic way of spelling that is:

```
__fence(__execution)
```

But otherwise, yes, sounds like this is the correct fix.

**Comment by lightsighter** [comment]
I think most of the HDF5 Regent tests suffer from this pathology.

**Comment by eddy16112** [comment]
I tried this commit https://gitlab.com/StanfordLegion/legion/-/commit/e8ea457809795607446a24cc0dbbea193ae31d1a, which is the one before caching allocator, and I can not reproduce the error. Then I tried the caching allocator commit, and the error showed up, so I thought the error comes from caching allocator.

**Comment by eddy16112** [comment]
@lightsighter I think you are right, we need a fence between each test. I created a PR https://gitlab.com/StanfordLegion/legion/-/merge_requests/861. I ran the failure tests 100 times and I did not see the error again.

**Comment by lightsighter** [comment]
To be clear, you don't need a fence everywhere. You just need a fence between tests that are doing attach/detach to the same file with different logical regions. Legion can't detect the aliasing onto the same backing file. I think all the ones that you added the fence to though in the merge request have that property.

**Comment by eddy16112** [comment]
Yes, I only added fence between tests with attach/deatch

**Comment by lightsighter** [comment]
> Yes, I only added fence between tests with attach/deatch

And only between attach/detach of the *same* file... there doesn't need to be any ordering of attach/detach to different files (mostly just making this clear for anyone else who comes here to read this later).

**Comment by eddy16112** [comment]
> > Yes, I only added fence between tests with attach/deatch
> 
> And only between attach/detach of the _same_ file... there doesn't need to be any ordering of attach/detach to different files (mostly just making this clear for anyone else who comes here to read this later).

Yep, that is what is I did in the PR.

**Comment by elliottslaughter** [comment]
Fixed by https://gitlab.com/StanfordLegion/legion/-/merge_requests/861
