### ISSUE TITLE
I'd like to ask some questions about automatic partitioning and DPL

### ISSUE THREAD

**Issue by AngryBear2** [StanfordLegion/legion#1529]
1. In the https://legion.stanford.edu/pdfs/parallelizer2019.pdf paper, a technique to automatically extract partition constraints from a program and generate DPLs through a constraint solver is mentioned. Is this implemented for Regent programs only?
2.  The DPL mentioned in the https://legion.stanford.edu/pdfs/dpl2016.pdf paper seems to refer to both framework and sublanguages. Is there a separate implementation of framework in Regent and Legion Runtime? Linguistically, do DPL programs generated using the constraint solver, for example, mentioned in the previous question, have to rely on the Regent compiler?

**Comment by AngryBear2** [comment]
I don't know much about the connection between DPL and Regent and Legion. I hope I can get some advice. Thank you.

**Comment by lightsighter** [comment]
1. Correct, the auto-parallelizer exists in the Regent compiler and only works on Regent programs.
2. The primitives described in the DPL paper such as partitioning by `image` or `preimage` exist in both the Legion runtime as API calls and as operators in the Regent programming language. They are functionally equivalent and the Regent operators compile down directly to Legion runtime calls. The auto-parallelizer is effectively a Regent-to-Regent transformation that will take a completely sequential Regent program and emit a Regent program using the dependent partitioning operators to express the needed partitions for task parallelism.

**Comment by AngryBear2** [comment]
I see what you mean, the image and preimage ideas in DPL are implemented in Regent and Legion, and autoparallel is the conversion of sequentially executed Regent programs into Regent programs using DPL semantics, thanks for such a quick and detailed response.

**Comment by lightsighter** [comment]
Feel free to ask more questions, and then please close the issue when you're done.
