### ISSUE TITLE
C++20: error: no member named 'atomic_ref' in namespace 'std'

### ISSUE THREAD

**Issue by Jacobfaib** [StanfordLegion/legion#1532]
Building on Apple clang using `-std=c++20` you get
```sh
runtime/legion/legion_redop.inl:527:10: error: no member named 'atomic_ref' in namespace 'std'
    std::atomic_ref<RHS> atomic(lhs);
    ~~~~~^
```
Inspecting `legion_redop.inl` one finds (among other colorful comments ;))
```c++
// We only need this crap if we're using a version of c++ < 20
// Starting with c++20 we can do all this the right way with atomic_ref
...
#if __cplusplus >= 202002L
  std::atomic_ref<RHS> atomic(lhs);
  ...
#else
  // No atomic logical operations so use compare and swap
  ...
```
This is not quite true, what you _actually_ intend to target is [`__cpp_lib_atomic_ref >= 201806L`](https://en.cppreference.com/w/cpp/feature_test#Library_features).

A fix for this is implemented in https://gitlab.com/Jfaibussowitsch/legion/-/commit/d60e7035707ce1334fe089bb729308a751f10cde

**Comment by streichler** [comment]
somewhat unrelated, but this line of code looks wrong:
```
  std::atomic_ref<RHS> atomic(lhs);
```
@lightsighter , shouldn't that be `std::atomic_ref<LHS>`?

**Comment by Jacobfaib** [comment]
> std::atomic_ref<RHS> atomic(lhs);

Perhaps -- until there is a `std` equivalent -- a `legion::make_atomic_ref()` would be useful
```c++
#if LEGION_HAVE_STD_ATOMIC_REF
namespace legion
{

template <typename T>
std::atomic_ref<T> make_atomic_ref(T&& thing)
{
  return std::atomic_ref<T>{std::forward<T>(thing)};
}

} // namespace legion
#endif
```

**Comment by lightsighter** [comment]
The C++ committee can burn in hell. Will try to get to this over the weekend. In general, all C++ test macros should be explicit so people can see all the insanity that the C++ committee foists on users. There should be just one test macro for every single version of C++. No stupid sub test macros for specific features. Either the compiler implements the standard for all the features of the entire version or it doesn't. What a bunch of amateurs.

> shouldn't that be std::atomic_ref<LHS>?

Yes.

> Perhaps -- until there is a std equivalent -- a legion::make_atomic_ref() would be useful

You're still relying on the `std::atomic_ref` class in that implementation. Only uses of `std::atomic` by itself exist before C++ 20 so you have to do type punning memcpys with atomic compare and swap intrinsics as you cannot move or copy `std::atomic` objects.

**Comment by Jacobfaib** [comment]
> Either the compiler implements the standard for all the features of the entire version or it doesn't. What a bunch of amateurs.

IIRC the underlying motivation for adding the feature-test macros was that MSVC infamously always defined `__cplusplus` to `199711L` -- regardless of `/std:c++whatever` -- and so it required a lot of macro wrangling to deduce C++ version from the value of `_MSC_VER`. So we have Mr. Bill Microsoft to thank for that.

Note, if compilers were required to strictly conform, none of them would, since none of them ever implemented C++11 garbage collection 🤔.

**Comment by lightsighter** [comment]
https://gitlab.com/StanfordLegion/legion/-/merge_requests/901

> Note, if compilers were required to strictly conform, none of them would, since none of them ever implemented C++11 garbage collection

Should never have been ratified into the standard in the first place then.

**Comment by lightsighter** [comment]
Merged.
