### ISSUE TITLE
Slow startup with HIP on control_replication

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1541]
As best I can tell, Legion startup appears to be dramatically slower in `control_replication` as opposed to `master`. As a result, I'm seeing repeated CI timeouts on Crusher in `control_replication`, whereas `master` runs to completion successfully.

For example:

  * `master`: Legion finishes in 15 minutes (Make) and 20 minutes (CMake): https://code.olcf.ornl.gov/ci/csc335/dev/legion/-/pipelines/9740
  * `control_replication`: Legion jobs time out after around 2.5 hours in both Make and CMake configurations: https://code.olcf.ornl.gov/ci/csc335/dev/legion/-/pipelines/9756
  * A second test of `control_replication` showing this isn't interference on the machine: https://code.olcf.ornl.gov/ci/csc335/dev/legion/-/pipelines/9702

I thought it might be the link step that had gotten longer. But CMake also times out, and in the CMake configuration we link all executables in advance of running any tests. I checked manually while the test was going, and the link step was done in around the same amount of time as when running `master`. So I think it must be that startup itself is slower.

I haven't gotten into debugging this yet because I just discovered the CI failures, but I'm documenting this here so I remember to come back to it.

Edit: Regent also takes dramatically longer, but I'm not focusing on it here because the Legion C++ tests already demonstrate the issue.

**Comment by lightsighter** [comment]
Must be resolved before #765

**Comment by elliottslaughter** [comment]
Frontier CI seems fine and jobs are finishing in a reasonable amount of time. I'll reopen if I see this again.
