### ISSUE TITLE
Realm: NUMA memory allocation fails on Crusher CI

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1547]
We're seeing failures like this one: https://code.olcf.ornl.gov/ci/csc335/dev/legion/-/jobs/24413

```
mlock failed for memory on node 0: Cannot allocate memory
machine_config: /lustre/orion/csc335/proj-shared/ci/10250_24413/runtime/realm/numa/numa_module.cc:241: virtual void Realm::Numa::NumaModule::initialize(Realm::RuntimeImpl*): Assertion `false' failed.
```

This is happening on `master` commit b95542b230c116c779d74a0d6f7ae927b023a18e.

The last fully passing CI was https://code.olcf.ornl.gov/ci/csc335/dev/legion/-/pipelines/9862 on `master` commit 13d4101cccc75ae67e880068617608e90fb8c3e4.

Because this failure is in the recently added `machine_config` test, I suspect the issue has been there for a while and we possibly just didn't notice before.

@eddy16112 @streichler would appreciate suggestions for debugging.

**Comment by eddy16112** [comment]
The last CI was passed is because we never tested `-ll:nsize`. The error is because we are not able to allocate numa memory on this machine. I think we can just turn off the `-ll:nsize` for hip. Again, it is not an issue of the hip module, but the issue of the `numasysif_alloc_mem` call on this machine.

**Comment by elliottslaughter** [comment]
Right. I think turning off the `-ll:nsize` test when HIP is on isn't quite right, because as you said it's not a HIP issue, it's a Crusher issue. Presumably we would take this to the Crusher/Frontier admins to get it fixed, but I'm not quite sure what to tell them right now because I'm not sure exactly what is wrong.

**Comment by eddy16112** [comment]
From the log of the ci, the `mlock` function failed. https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/realm/numa/numasysif.cc#L421

**Comment by elliottslaughter** [comment]
This was an artifact of a `ulimit` set by the CI, and not a general property of the machine.
