### ISSUE TITLE
Can I use valgrind to check legion memory safety?

### ISSUE THREAD

**Issue by 1193749292** [StanfordLegion/legion#1549]
`cd examples/circuit;make;valgrind -s --tool=memcheck --leak-check=full --show-leak-kinds=all ./circuit`
> ERROR SUMMARY: 32 errors from 3 contexts (suppressed: 0 from 0)

Does valgrind detect too much detail? Must the legion gc tool be used for detection?

**Comment by lightsighter** [comment]
As long as you're not running with software that valgrind can't check (CUDA, GASNet, etc), then you can use valgrind with Legion just fine. You might get some warnings (errors depending on your valgrind flags) about some leaked data (especially from Realm), but in general that is not anything to worry about as they are singleton data structures that will not cause memory leaks for long-running programs.

The better thing to do with Legion programs is to turn on bounds checks by defining the `LEGION_BOUNDS_CHECKS` macro. That will be a stronger check than valgrind in that it will actually check that all your accesses through Legion's `FieldAccessor` class are abiding by the declared privileges for your task (note if you ask for raw pointers from the `FieldAccessor` then the check is no longer sound). Similar to valgrind, you should expect a considerable performance slow-down when turning on these checks as every memory access done through the `FieldAccessor` will involve several branches and memory look-ups.

**Comment by elliottslaughter** [comment]
Just FYI: valgrind (usually) does not support all the instructions on your CPU, so if you want to use it, you'll also need to disable the `-march=native` flag that Legion builds with by default.

But as Mike said, `LEGION_BOUNDS_CHECKS` is easier and more precise, and will catch a lot of issues.

**Comment by lightsighter** [comment]
I also forgot to mention, valgrind is not very good at checking accesses by tasks into physical regions, because Realm usually allocates large chunks of virtual address space for its memories where instances are placed. This means that reads/writes that are out-of-bounds on an instance will look in-bounds to valgrind. Yet another reason that `LEGION_BOUNDS_CHECKS` (or `-fbounds-checks 1` in Regent) is much better at detecting memory errors than valgrind.

**Comment by 1193749292** [comment]
Thank you for your patience. I tried a few simple demos and no errors were detected, including some memory leaks. I may try a more complex example later.
