### ISSUE TITLE
Regression in GPU executions

### ISSUE THREAD

**Issue by cmelone** [StanfordLegion/legion#1550]
Our GPU test suite last succeeded at Legion commit `61a919f8` and failed last night at `da9cefee`. I suspect it's due to [this merge](https://gitlab.com/StanfordLegion/legion/-/merge_requests/882)? 

We're getting errors like:

```
prometeo_ConstPropMix.exec: /home/hpcc/gitlabci/psaap-ci/artifacts/5065111388/legion/runtime/realm/cuda/cuda_module.cc:370: bool Realm::Cuda::GPUStream::reap_events(Realm::TimeLimit): Assertion `0' failed.
prometeo_ConstPropMix.exec: /home/hpcc/gitlabci/psaap-ci/artifacts/5065111388/legion/runtime/realm/cuda/cuda_module.cc:370: bool Realm::Cuda::GPUStream::reap_events(Realm::TimeLimit): Assertion `0' failed.
[0 - 7f55f347ec80]    2.785033 {6}{gpu}: CUDA error reported on GPU 0: device-side assert triggered (CUDA_ERROR_ASSERT)
[0 - 7f55e16f8c80]    2.785032 {6}{gpu}: CUDA error reported on GPU 0: device-side assert triggered (CUDA_ERROR_ASSERT)
[0 - 7f55f348ac80]    2.785078 {6}{gpu}: CUDA error reported on GPU 0: device-side assert triggered (CUDA_ERROR_ASSERT)
```

I can debug further, just let me know.

@elliottslaughter, could you please add this to https://github.com/StanfordLegion/legion/issues/1032?

**Comment by streichler** [comment]
If this is a single-node run, can you try running inside of `cuda-gdb` and see if you get better information about the
device-side asserts?

**Comment by apryakhin** [comment]
I can take a look at this

**Comment by apryakhin** [comment]
@cmelone Can you walk me through the steps to get a repro?

**Comment by cmelone** [comment]
cc: @mariodirenzo

**Comment by mariodirenzo** [comment]
@elliottslaughter, Can you please add this issue to #1032?

**Comment by apryakhin** [comment]
We've got a reproducer. I am going to root cause it as soon as possible

**Comment by apryakhin** [comment]
The fix is out. I am going to be submitting it soon once reviewed.

**Comment by mariodirenzo** [comment]
@streichler, do you have any update regarding the merge of Artem's patch into master?

**Comment by apryakhin** [comment]
Yes, we worked through several comments which have been addressed:
https://gitlab.com/StanfordLegion/legion/-/merge_requests/926

Depending on the available bandwidth I am going to ask few team members to review & approve, so we could submit the patch asap.

**Comment by apryakhin** [comment]
The fix has been merged

**Comment by cmelone** [comment]
Thanks @apryakhin! I'll let our CI run and get back to you

**Comment by mariodirenzo** [comment]
I've run a quick test on sapling2 and it seems that the current version of control_replication still produces the same failures as before.

**Comment by apryakhin** [comment]
We need to make sure that the patch is on control_replication as the merge has been done to `master` branch

**Comment by lightsighter** [comment]
Just responding here, that this commit was merged upstream into control replication as of yesterday:

```
commit d55d7c17c80ad6615be9339a06e87d8de89bedce
Merge: ee49c0001 fac5e48bf
Author: apryakhin <pryakhin.artem@gmail.com>
Date:   Thu Sep 21 18:23:30 2023 +0000

    Merge branch 'realm-fix-htr' into 'master'
    
    Realm: fix detection of transpose use cases
    
    See merge request StanfordLegion/legion!926
    ```

**Comment by cmelone** [comment]
I am on `3a9a37a` and still getting similar errors.

```
CU: CUDA_DRIVER_FNPTR(cuMemcpy3DAsync)(&cuda_copy, stream->get_stream()) = 1 (CUDA_ERROR_INVALID_VALUE): invalid argument
...
prometeo_ConstPropMix.exec: /home/hpcc/gitlabci/psaap-ci/artifacts/5163946925/legion/runtime/realm/cuda/cuda_module.cc:370: bool Realm::Cuda::GPUStream::reap_events(Realm::TimeLimit): Assertion `0' failed.
[0 - 7f3a03bffc80]    0.545906 {6}{gpu}: CUDA error reported on GPU 0: device-side assert triggered (CUDA_ERROR_ASSERT)
...
[0 - 7f9f3ad94c80]    1.620636 {6}{gpu}: CUDA error reported on GPU 0: device-side assert triggered (CUDA_ERROR_ASSERT)
CU: cuLaunchKernel(f, grid_dim.x, grid_dim.y, grid_dim.z, block_dim.x, block_dim.y, block_dim.z, shared_memory, stream, args, NULL) = 710 (CUDA_ERROR_ASSERT): device-side assert triggered
```

(these are all errors I'm seeing across different runs)

**Comment by apryakhin** [comment]
The patch is LGTMd and set for auto-merge once CI passes:
* https://gitlab.com/StanfordLegion/legion/-/merge_requests/941

I did a number of runs on sapling2 along with @mariodirenzo and can confirm that it fixes the issue.

**Comment by mariodirenzo** [comment]
So we have a new problem that I am not sure is related to the cuda-dma.
The code works fine if everything (Legion + HTR) is compiled in debug mode.
As soon as things are compiled in release mode, it starts producing the following errors
```
/home/mariodr/legion3/runtime/realm/inst_layout.inl:1820: FT *Realm::MultiAffineAccessor<FT, N, T>::ptr(const Realm::Point<N, T> &) [with FT = MyArray<double, 3>; int N = 3; T = long long]: block: [0,0,0], thread: [0,7,7] Assertion `i->opcode() == PieceLookup::Opcodes::OP_SPLIT1` failed.
```

I did not catch this problem yesterday because I was testing the code in debug mode.

Any suggestion on how to move forward with the debug?

**Comment by apryakhin** [comment]
Please file another bug for that

**Comment by apryakhin** [comment]
This github issue is actually about the GPU regression, so I think we should still triage it here. Would that be possible to get a backtrace on this? Just by looking at the assert we are hitting I am unable to determine the root cause. I plan to be OOO today by can look as soon as have an online access (hopefully over the weekend)

**Comment by streichler** [comment]
The most common cause for that (admittedly fairly unhelpful) error message is that you are
attempting an access on a point that is outside the bounds of the multi-affine instance.  Can
you try running with bounds checks enabled and/or break in with a debugger to see what
point the unhappy thread is trying to access and then determine whether that point is expected
to be present in the instance?

**Comment by mariodirenzo** [comment]
The executions in debug mode are with bounds checks and I haven't seen any failure on those. Moreover the same version of the code used to work fine on `61a919f8`.
The main option that I see is that some corrupted data is reaching the kernel when things are faster in release mode. Since we compute the stencil point based on one data field, if the field is corrupted, the offset to the stencil point will be wrong

**Comment by streichler** [comment]
That makes sense.  So although there's no specific evidence to suspect this is due to the cuda-dma bug,
there's definitely some chance it has the same root cause.  Did we think we had all of the cuda-dma-related
fixes in this run?

**Comment by mariodirenzo** [comment]
yes. The other day I told Artem that the issue was fixed because I tested the code in debug mode, which works fine. As soon as Caetano ran the CI in release mode the new error message appeared.

**Comment by mariodirenzo** [comment]
@apryakhin has been able to find the root cause of the regression in the cuda-dma changes. The branch https://gitlab.com/StanfordLegion/legion/-/commits/cuda-dma-fix-2 contains the fix.

@cmelone is completing a thorough test of the fix using the https://gitlab.com/StanfordLegion/legion/-/commits/control_replication_staggered_fix?ref_type=heads branch. Preliminary results are promising.

**Comment by elliottslaughter** [comment]
@apryakhin when you find the root cause, are you adding tests to our Realm test suite so we catch issues like these in the future? By all means, merge the fix once everyone here approves, but I'm concerned that these failures demonstrate a hole in our test coverage, and we'll relapse later if we don't improve the tests as well.

**Comment by apryakhin** [comment]
@elliottslaughter Yes, the fix will come with realm tests to make sure we aren't running into this issues in a future. I do agree that we are missing on a test coverage here. I am going to prioritize and address it going forwards before merging any more of cuda-dma changes.

**Comment by cmelone** [comment]
Everything seems to be working now due to the fix. Can you let us know when it's merged into control replication, and I'll close the issue?

Thanks again

**Comment by apryakhin** [comment]
Yes, will update it here as soon as merge the fix in

**Comment by apryakhin** [comment]
The fix has been merged:
- https://gitlab.com/StanfordLegion/legion/-/merge_requests/949

**Comment by mariodirenzo** [comment]
@lightsighter, can you please merge the fix into control replication?

**Comment by cmelone** [comment]
With the newest version of control replication, a smaller subset of our tests failed. Since we previously verified that @apryakhin's branch didn't throw any errors with our tests, another CUDA bug must have been introduced since.

I'm guessing that this [commit](https://gitlab.com/StanfordLegion/legion/-/commit/6a6dd3057f4b182d8efd48cfbd644cf319763c93) could be the cause? 

We're getting errors like

```
/legion/runtime/realm/cuda/cuda_module.cc:370: bool Realm::Cuda::GPUStream::reap_events(Realm::TimeLimit): Assertion `0' failed.
[0 - 7f0e42dd5c80]    4.777734 {6}{gpu}: CUDA error reported on GPU 0: device-side assert triggered (CUDA_ERROR_ASSERT)

**Comment by lightsighter** [comment]
> I'm guessing that this [commit](https://gitlab.com/StanfordLegion/legion/-/commit/6a6dd3057f4b182d8efd48cfbd644cf319763c93) could be the cause?

No, that commit is a stand-alone new feature. It doesn't change any existing Realm functionality. @muraj to confirm, but I feel pretty confident in that assessment.

> With the newest version of control replication, a smaller subset of our tests failed. Since we previously verified that @apryakhin's branch didn't throw any errors with our tests, another CUDA bug must have been introduced since.

Or something changed on the machine or in the way you're testing things. Unfortunately @apryakhin is on vacation next week, so we might need to wait for him to come back to assess. Can you run with the branch again and confirm that it still works without any errors for you?

**Comment by apryakhin** [comment]
@cmelone Can you please confirm whether this branch:
https://gitlab.com/StanfordLegion/legion/-/commits/control_replication_staggered_fix?ref_type=heads

is passing or not? As well as how run and get a reproducer on `control_replication` if possible

**Comment by cmelone** [comment]
Apologies for the false alarm, Cory.

@lightsighter, I did some more testing.

When running Legion @ commit `0cbee456` and cherry-picking Artem's fix in `bb388fa1`, our tests pass.

When I move that same configuration to commit `8ccfc138` (merge of `betterend`), the tests reliably fail. 

Note that this only happens when we run with CUDA. Let me know if you'd like me to move this to another issue

**Comment by lightsighter** [comment]
> When I move that same configuration to commit 8ccfc138 (merge of betterend), the tests reliably fail.

Pull and try again. If it still fails then make me a small reproducer on sapling.

> Let me know if you'd like me to move this to another issue and/or if you need more info.

You can leave it here for now.

**Comment by cmelone** [comment]
```
cd /home/cmelone/gpu-oct
# execute
REBUILD=0 ./run.sh
# re-compile
REBUILD=1 ./run.sh
```

Note: everything is compiled in debug mode. Once the execution is started, the process freezes pretty much immediately.

**Comment by lightsighter** [comment]
This doesn't appear to be hanging to me. There are real tasks running and making progress. It looks like you built with Regent's bounds checks on so the tasks are very slow as all their memory references are having to go through safe casts, but it is definitely not hanging.

**Comment by cmelone** [comment]
Maybe the freezing is more stochastic than I thought. Anyway, here is a frozen process

```
[0 - 7f401fffec80]   36.339152 {6}{gpu}: CUDA error reported on GPU 0: device-side assert triggered (CUDA_ERROR_ASSERT)
prometeo_ConstPropMix.exec: /home/cmelone/gpu-oct/legion/runtime/realm/cuda/cuda_module.cc:370: bool Realm::Cuda::GPUStream::reap_events(Realm::TimeLimit): Assertion `0' failed.
Legion process received signal 6: Aborted
Process 1325936 on node g0004.stanford.edu is frozen!
```

I set the process to run for 24 hours.

**Comment by lightsighter** [comment]
> Maybe the freezing is more stochastic than I thought. Anyway, here is a frozen process

Ok, so it's not actually freezing. It is crashing and you've set `REALM_FREEZE_ON_ERROR`. 

> Anyway, here is a frozen process

So this does look like one of the crashes from before not something related to the merge of `betterend`. The merge of `betterend` probably did perturb the timing though of some things which may have shaken loose some additional issues. This was run with `betterend` and with all of Artem's most recent changes up-streamed?

**Comment by cmelone** [comment]
Thanks for the clarifications. 

Let me outline my testing process:

1. Compile Legion and HTR with [Artem's branch](https://gitlab.com/StanfordLegion/legion/-/commits/control_replication_staggered_fix) (`control_replication_staggered_fix`). This does not pose any issues.
2. Merge `betterend` into `control_replication_staggered_fix` and re-compile. CUDA errors like `device-side assert triggered` reappear. I will say that the original bug affected a majority of our tests, this new error is only triggered for 1/13 of them.

Note: I also tested with the latest version of control replication (including your fix), and the issues persist.

You're right, the merge of this branch may have exposed additional issues that weren't tested before.

Let me know if I can provide more details.

**Comment by lightsighter** [comment]
> You're right, the merge of this branch may have exposed additional issues that weren't tested before.

`betterend` relaxed the timing of some things inside Legion which might have enabled some more parallelism to occur.

> CUDA errors like device-side assert triggered reappear.

If you build all the device side code with with `-lineinfo` (for both application device code and Realm DMA code) then I think it should give you a line number for the device side assert that is being triggered. If it doesn't, then maybe see if it reproduces with cuda-memcheck which should give you a line number for a device side assert.

**Comment by cmelone** [comment]
The code is failing on an assertion of the application that signals that bad data is being produced somewhere. The major difference compared to the previous mode of failure is that data was corrupted everywhere, resulting in all tests failing. However, in this instance, only select configurations are failing. We tried running with Legion Spy and a failing run passes passed the logical and physical analysis

**Comment by lightsighter** [comment]
So that at least rules out the runtime analysis. Do you use futures for passing any data around or doing future reductions?

**Comment by cmelone** [comment]
Yes, we do.On Oct 12, 2023, at 12:32 PM, Mike Bauer ***@***.***> wrote:﻿
So that at least rules out the runtime analysis. Do you use futures for passing any data around or doing future reductions?

**Comment by lightsighter** [comment]
Can you check that some of your future data is the same?

**Comment by lightsighter** [comment]
Ok, I think I pushed a fix for this issue. @cmelone please pull the latest control replication branch and try again.

**Comment by cmelone** [comment]
thank you for the assistance, Mike and Artem!
