### ISSUE TITLE
Hope to get some advice

### ISSUE THREAD

**Issue by AngryBear2** [StanfordLegion/legion#1562]
Hello, I would like to ask how to do a loop task, can the output of the task in the previous timestep as the input of the next timestep? Because I want to iterate many times, I try to use the output region directly as the input, and calculate the output region again, but it doesn't seem possible to do so. Do you have any good suggestions?
![image](https://github.com/StanfordLegion/legion/assets/82449330/799c539c-fb9f-4538-8e69-21f72b480a25)
![image](https://github.com/StanfordLegion/legion/assets/82449330/b7c279b5-611d-4eea-88b2-a32cf9ab63ba)

**Comment by lightsighter** [comment]
What is a backtrace for that crash? Which commit are you on? What command line are you using to launch this program?
