### ISSUE TITLE
Crusher CI times out on control_replication

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1563]
On `master` our Crusher CI is passing: https://code.olcf.ornl.gov/ci/csc335/dev/legion/-/pipelines/12235

On `control_replication`, for basically as long as I can remember, we're seeing some sort of a timeout: https://code.olcf.ornl.gov/ci/csc335/dev/legion/-/jobs/28900

It's not totally obvious to me right now if this is a freeze in one particular application (`ghost_pull`, from the logs) or if something is causing `control_replication` startup time to be dramatically worse. The timeout is an extremely generous 3 hours; the same job on `master` finishes in 15 minutes.

I need to do more local testing to confirm, but this issue tracks the timeout so that we don't forget.

**Comment by lightsighter** [comment]
I suspect it is a real hang. You're going to need to go debug it since I don't have access to Crusher. Get it to hang with `-ll:force_kthreads` and go look at backtraces.

**Comment by lightsighter** [comment]
Required for #765

**Comment by elliottslaughter** [comment]
It seems like we're in some sort of livelock or infinite loop. The backtraces keep changing, so I sampled node 0 at intervals of every couple of minutes. This run has 4 ranks (2 per node, 2 nodes total):

 * Node 0 (ranks 0 and 1):
     * [bt0.log](https://github.com/StanfordLegion/legion/files/13192286/bt0.log)
     * [bt0_2.log](https://github.com/StanfordLegion/legion/files/13192294/bt0_2.log)
     * [bt0_3.log](https://github.com/StanfordLegion/legion/files/13192303/bt0_3.log)
     * [bt0_4.log](https://github.com/StanfordLegion/legion/files/13192304/bt0_4.log)
 * Node 1 (ranks 2 and 3):
     * [bt1.log](https://github.com/StanfordLegion/legion/files/13192305/bt1.log)

**Comment by lightsighter** [comment]
I'll need a reproducer for this. It should happen deterministically on any machine.

**Comment by elliottslaughter** [comment]
Ok, on Sapling, go to `/scratch/eslaught/legion-bug1563/examples/ghost_pull` and run:

```
srun -n 4 -N 1 -c 10 -p gpu --exclusive ./ghost_pull -ll:cpu 4 -ll:force_kthreads
```

If you want to rebuild in this directory, feel free to do so, but *you must be on a compute node* or you'll hit SIGILL.

```
DEBUG=1 REALM_NETWORKS=gasnetex CONDUIT=ibv GASNET=$PWD/gasnet/release LG_RT_DIR=$PWD/../../runtime make -j20
```

**Comment by lightsighter** [comment]
Can you confirm that this bug is already fixed in the `shardrefine` branch?

**Comment by elliottslaughter** [comment]
Indeed, the problem is solved in `shardrefine` on both Sapling and Crusher manual runs.

I'm running the full Crusher CI now and will close once I confirm it's fixed there.

**Comment by lightsighter** [comment]
You can also leave it open until the shardrefine branch merges if you want. This is already tracked as part of #765 so it will get closed when we're ready to wrap up control replication.

**Comment by elliottslaughter** [comment]
Crusher CI is happy now. I set up a schedule to test `shardrefine` regularly. Once `shardrefine` merges to `control_replication`, I'll switch that back to running `control_replication` regularly (and so on until `control_replication` merges to `master`).
