### ISSUE TITLE
Is the data layout AOS/SOA in legion reflected in the memory?

### ISSUE THREAD

**Issue by 1193749292** [StanfordLegion/legion#1564]
In legion/examples/attach_array_daxpy, `acc_z[*pir] = alpha * acc_x[*pir] + acc_y[*pir];`

Output the addresses of acc_x and acc_y elements. It is found that the elements in acc_x are continuous regardless of SOA or AOS, and the elements in acc_y are continuous. In addition, the start address of acc_y elements is always equal to the total number of elements in acc_x multiplied by the acc_x element size add acc_x element start address.

**Comment by eddy16112** [comment]
It is because Legion could make a new region and copy data from the original attached region into the new one. If you compare the addresses of original allocated buffer of xyz with the ones in the task, they are different.

**Comment by lightsighter** [comment]
Slight change of terminology, but in general @eddy16112's response is accurate:

> It is because Legion could make a new region and copy data from the original attached region into the new one

 It is because Legion could make a new *instance* (with a different layout) and copy data from the original attached *instance* into the new one.

**Comment by 1193749292** [comment]
Thank you for your answer. I get it.

After checking different data layouts (AOS/SOA) in the `legion/examples/realm_saxpy/realm_saxpy_cpu.cc` example, the address in `cpu_saxpy_task` meets the expectation.

If I want the addresses in the task to be consistent with the addresses of original allocated buffer, can I only specify it by `create_instance` as in the `realm_saxpy` example?

**Comment by eddy16112** [comment]
`create_instance` is Realm API, which is not supposed to be used by Legion applications. Instead, you can create your own mapper to control whether to allocate instances.

**Comment by 1193749292** [comment]
I see. Thank you for your answer.

**Comment by lightsighter** [comment]
Right, in a Legion program, the mapper can choose to reuse an existing instance or make a new one. It's also worth noting that Legion has a constraint language for describing the layouts of instances, which is hopefully easier to use than the way that Realm requires the creation of instances for different layouts.
