### ISSUE TITLE
How to Deal with the Dependency of Data Transfer Between Nodes in a Cluster

### ISSUE THREAD

**Issue by 97CBR** [StanfordLegion/legion#1569]
I have a cluster of six machines, and I use it to run a demo.
In the cluster, we wrote a daxpy program and ensured that the ata dependencies are interleaved between nodes. For example, data1 depends on 0 and 2, and data2 depends on 1 and 3. Data is transmitted between adjacent nodes.  It's like 0->1<-2, 1->2<-3, 2->3<-4,  3->4<-5, '->' represents the direction of data transfer.
All this works well in the control replication branch (version legion-22.12.0). I output the address_space of the source and target memory of the usage in the process_copy of the legion_profiling process. This data is transmitted in nodes 0, 1, 2, and so on just like the data dependencies mentioned above.
However, the same code is executed and tested in the stable branch(version legion-23.09.0), and the address_space of the memory of the source and target is also output. It is found that the data transmission is different. When node0 sends data to node2, it should be sent to node1. When node3 sends data to node1, it should be sent to node2. It seems that this kind of data transfer dependency is quite different from the branch of control replication.

I would like to ask you a few questions.
1. Why is the data transmission dependency between nodes changed in the stable branch?
2. How to customize the dependency of data transmission between nodes?

**Comment by eddy16112** [comment]
If you are using the daxpy from the tutorial, it is likely that the default mapper of stable branch and control replication branch have different mapping strategy. The data movement depends on where the PhysicalRegion is and where the task is, you can print the processor where a task is executed by `printf("%llx", task. current_proc)`, and compare the results between two branches.

**Comment by elliottslaughter** [comment]
The `control_replication` branch supports control replication, as the name suggestions. Control replication supports a different set of mapping options that can also lead to different mappings. Therefore, one would not expect those two to map in the same way, at least not without going to substantial effort to make sure that they're doing so.

In general, `control_replication` is the way to go for all serious performance experiments with Legion.

**Comment by 97CBR** [comment]
> If you are using the daxpy from the tutorial, it is likely that the default mapper of stable branch and control replication branch have different mapping strategy. The data movement depends on where the PhysicalRegion is and where the task is, you can print the processor where a task is executed by `printf("%llx", task. current_proc)`, and compare the results between two branches.

@eddy16112 Thank you. I'd like to know how the specific mapping strategy for control_replication and stable branches differ, and where to find these differences.

**Comment by lightsighter** [comment]
> I'd like to know how the specific mapping strategy for control_replication and stable branches differ, and where to find these differences.

A simple way to do this might be just to diff the `runtime/mappers/default_mapper.cc` file between the two branches. In practice, the default mapper in the control replication branch will assume that the top-level task is control replicated across all the nodes in the machine when deciding how to map sub-tasks.

**Comment by 97CBR** [comment]
I have no more questions. Thank you for your patient replies. Thank you very much.
