### ISSUE TITLE
Legion: mixing user-defined and Legion-generated layout constraint IDs

### ISSUE THREAD

**Issue by mariodirenzo** [StanfordLegion/legion#1570]
Right now, if an application is registering layout constraints both with user-defined and Legion-generated IDs, two constraints may be defined with the same ID. To avoid this situation, it would be useful to distinguish the pool of values that a user can pick for the constraint IDs from the values that Legion can automatically generate.

@elliottslaughter, please add this issue to #1032

**Comment by lightsighter** [comment]
@mariodirenzo Pull and try again with either the master or control replication branches.

**Comment by mariodirenzo** [comment]
It works! Thank you for the quick merge of the feature.
