### ISSUE TITLE
legion profiler crash (both python and rust)

### ISSUE THREAD

**Issue by rohany** [StanfordLegion/legion#1571]
I'm seeing a crash in the profiler:

```
(lelapack) rohany@g0001:/scratch2/rohany/nvidia/lelapack$ LD_LIBRARY_PATH=$CONDA_PREFIX/lib/:$LD_LIBRARY_PATH ../legate.core/_skbuild/linux-x86_64-3.10/cmake-install/bin/legion_prof legate_0.prof -o ~/public_html/lelapack/testing-manual-map/
Reading log file "legate_0.prof"...
Matched 30499 objects
No Legion Spy data, skipping postprocess step
Sorting time ranges
Generating interactive visualization files in directory "/home/rohany/public_html/lelapack/testing-manual-map.1"
thread '<unnamed>' panicked at src/backend/common.rs:915:21:
Error: Copy can not find src_inst:0x8000001002100039
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at src/backend/common.rs:915:21:
Error: Copy can not find src_inst:0x8000001004200072
thread '<unnamed>' panicked at src/backend/common.rs:915:21:
Error: Copy can not find src_inst:0x8000001002200058
```

I'm on commit `7dd59b15bfc2db6f35178a07daf8e1a288c4ff89` of Legion.

The profile is attached.
[crashing-prof.gz](https://github.com/StanfordLegion/legion/files/13059682/crashing-prof.gz)

**Comment by syamajala** [comment]
I've been hitting this too. As a work around try the archive mode: `legion_prof --archive`

**Comment by eddy16112** [comment]
The error means the insts like `0x8000001004200072` and `0x8000001002200058` are not logged correctly. They are used by some copies, but the instance itself is not logged. I am almost sure it is a bug in Legion.

**Comment by lightsighter** [comment]
Make me a reproducer if you think it is the runtime's fault.

**Comment by rohany** [comment]
For a legion reproducer, log onto sapling as me, get a gpu node, do `conda activate lelapack`, go to `/scratch2/rohany/nvidia/lelapack` and run ` LEGATE_FIELD_REUSE_FREQ=1 legate --profile --gpus 4 --fbmem 14000 --eager-alloc-percentage 1 examples/chol/test.py --n 32768 --blocksize 4096 --iterations 1 --matrix random --backend lelapack --uplo lower --variant 3 --cntl-batched --verify -cunumeric:preload-cudalibs`. The resulting profile will be in `legate_0.prof`.

**Comment by lightsighter** [comment]
Pull and try again. If that doesn't fix it rebuild the core in debug mode.

**Comment by rohany** [comment]
works now
