### ISSUE TITLE
What is the affinity strategy of numa in legion?

### ISSUE THREAD

**Issue by 1193749292** [StanfordLegion/legion#1574]
`numactl --hardware : `
```
available: 2 nodes (0-1)
node 0 cpus: 0 1 2 3 4 5 12 13 14 15 16 17
node 0 size: 64010 MB
node 0 free: 13548 MB
node 1 cpus: 6 7 8 9 10 11 18 19 20 21 22 23
node 1 size: 64508 MB
node 1 free: 18409 MB
node distances:
node   0   1 
  0:  10  21 
  1:  21  10
```
The preceding figure shows the NUMA information of the test machine. It is found that multiple CPU cores cannot be specified to a NUMA node.

The number of NUMA nodes is specified in `-ll:cpu`, `-ll:ncpu` mode(The legion branch is stable). It is found that the NUMA nodes always run on two NUMA nodes.  For example, if there are four cores, 0, 1, 6, 7 are used. Why not 0, 1, 2, 3?

**Comment by elliottslaughter** [comment]
The best way to figure out how Legion (really, Realm) views the machine is by passing `-ll:show_rsrv`. That will tell you:

 1. How Realm thinks the machine is laid out (NUMA nodes, threads that share a physical core).
 2. What Realm processors are assigned to what cores.

Note that if you pass `-ll:ncpu` and do not pass `-ll:cpu 0`, you will get a default value of `-ll:cpu 1`, which will reserve a core. You would want to pass `-ll:cpu 0 -ll:ncpu ...` if you want NUMA cores and no regular CPU core.

**Comment by 1193749292** [comment]
I tried, but still can't run on one numa core, if only 4 cores will still run on 0,1,6,7.

**Comment by elliottslaughter** [comment]
Please post the output of `-ll:show_rsrv` on your machine, and include the full command line.

**Comment by 1193749292** [comment]
I'm sorry it took so long to get back to you.
```
core map {
  domain 0 {
    core 0 { ids=<0> alu=<12> fpu=<12> ldst=<12> }
    core 1 { ids=<1> alu=<13> fpu=<13> ldst=<13> }
    core 2 { ids=<2> alu=<14> fpu=<14> ldst=<14> }
    core 3 { ids=<3> alu=<15> fpu=<15> ldst=<15> }
    core 4 { ids=<4> alu=<16> fpu=<16> ldst=<16> }
    core 5 { ids=<5> alu=<17> fpu=<17> ldst=<17> }
    core 12 { ids=<12> alu=<0> fpu=<0> ldst=<0> }
    core 13 { ids=<13> alu=<1> fpu=<1> ldst=<1> }
    core 14 { ids=<14> alu=<2> fpu=<2> ldst=<2> }
    core 15 { ids=<15> alu=<3> fpu=<3> ldst=<3> }
    core 16 { ids=<16> alu=<4> fpu=<4> ldst=<4> }
    core 17 { ids=<17> alu=<5> fpu=<5> ldst=<5> }
  }
  domain 1 {
    core 6 { ids=<6> alu=<18> fpu=<18> ldst=<18> }
    core 7 { ids=<7> alu=<19> fpu=<19> ldst=<19> }
    core 8 { ids=<8> alu=<20> fpu=<20> ldst=<20> }
    core 9 { ids=<9> alu=<21> fpu=<21> ldst=<21> }
    core 10 { ids=<10> alu=<22> fpu=<22> ldst=<22> }
    core 11 { ids=<11> alu=<23> fpu=<23> ldst=<23> }
    core 18 { ids=<18> alu=<6> fpu=<6> ldst=<6> }
    core 19 { ids=<19> alu=<7> fpu=<7> ldst=<7> }
    core 20 { ids=<20> alu=<8> fpu=<8> ldst=<8> }
    core 21 { ids=<21> alu=<9> fpu=<9> ldst=<9> }
    core 22 { ids=<22> alu=<10> fpu=<10> ldst=<10> }
    core 23 { ids=<23> alu=<11> fpu=<11> ldst=<11> }
  }
}
CPU proc 1d00000000000001: allocated <0>
CPU proc 1d00000000000003: allocated <6>
utility proc 1d00000000000000: allocated <2,3,4,5,8,9,10,11,14,15,16,17,20,21,22,23>
dedicated worker (generic) #2: allocated <2,3,4,5,8,9,10,11,14,15,16,17,20,21,22,23>
CPU proc 1d00000000000004: allocated <1>
CPU proc 1d00000000000002: allocated <7>
dedicated worker (generic) #1: allocated <2,3,4,5,8,9,10,11,14,15,16,17,20,21,22,23>
Running daxpy for 102400 elements...
Running daxpy parallel on  4 nodes...
Running daxpy parallel on  1 threads for one node...
Running daxpy on 2 iterations...
Running daxpy for 2 loops...
ELAPSED TIME =  1.8521 s
AVERAGE TIME =  0.9260 s
```
In addition, is there any way to obtain the ID of the physical CPU core from Mapper? So I can know which numa domain he belongs to.

I read that it should be available from the `LocalCPUProcessor` core_rsrv of `runtime/realm/proc_impl.cc`, but it still cannot output proc_ids.

**Comment by elliottslaughter** [comment]
@eddy16112 or someone on the Realm team will need to speak to how to map Realm core numbers to physical CPU IDs.

But what this is saying is that you've got 2 NUMA nodes, covering cores 0-5,12-17 (where 12-17 are the hyperthreads for 0-5) and 6-11,18-23.

The reason why `-ll:cpu 4` gets assigned to 0,1,6,7 is because Realm alternates assigning cores between NUMA nodes. I think the theory is that this maximizes memory bandwidth.

Is there something specific you're trying to accomplish?

**Comment by 1193749292** [comment]
![image](https://github.com/StanfordLegion/legion/assets/128877897/aa9386e3-6195-4fe2-aa14-0b797ba93799)
As shown in the following figure, `create_equal_partition` is divided into four tasks. Each task uses a CPU core.
If I want to change the allocation of tasks and cores to improve performance, I need to obtain the physical CPU core ID corresponding to the processor and implement the change in the customized mapper.

Then, run the `-ll:show_rsrv` command to obtain the CPU core allocation information. After optimization (temporarily used, the allocation information changes at intervals), the performance is not improved. It is suspected that the problem may be caused by the memory. Is there any way to know whether the memory in each task region is on numa0 or numa1?

**Comment by lightsighter** [comment]
> If I want to change the allocation of tasks and cores to improve performance, I need to obtain the physical CPU core ID corresponding to the processor and implement the change in the customized mapper.

No, you should use the affinity between processors and memories exposed in the machine query interface. See section 7.1.3 of the [Legion Manual](https://legion.stanford.edu/pdfs/legion-manual.pdf).

**Comment by elliottslaughter** [comment]
Broadly speaking there are two ways to go about this.

Option 1 is to follow @lightsighter's suggestion and consult the Legion machine model. If you enable NUMA memories, then the runtime will tell you the affinity of each NUMA memory to each processor. (If you just use system memory, we don't guarantee a binding into any particular NUMA domain and the memory may even span NUMA domains.)

Option 2 is to build Legion for multiple nodes (e.g., with GASNet) and then create 1 Legion process per NUMA domain. You will need to get the core binding right. But if you do so, then cores in each process will be assigned to a single NUMA domain only. OS first-touch policies will cause the memory allocated by each process to live in its own NUMA domain.

My experience is that option 2 is usually easier and often gives higher performance, but you're free to pursue any route you want.

**Comment by 1193749292** [comment]
Thank you very much for your patient answer.

In fact, the main problem is whether cross-NUMA memory access increases overhead for two NUMA nodes on a single machine.

Option 1 you mentioned that the system memory is not guaranteed to bind to a specific numa domain, which is not what I wanted.
Option 2 is two nodes for two numas. Will there be communication overhead between them due to gasnet and thus affect the results?

I was thinking maybe a tool like Linux Perf, etc.
I'll try to see.

**Comment by elliottslaughter** [comment]
Yes, there can be overhead. GASNet uses a shared-memory bypass so it is very inexpensive. But it is not zero.

In practice, as I said, I have found option 2 to be a win. But the only measure of performance is your own application.

To start, I would just code it up to handle either scenario, then run both. End-to-end performance is enough for a baseline comparison. You can use other profilers if you want to dig in further, but I'd start by getting an overall picture first.
