### ISSUE TITLE
Some questions about overlap

### ISSUE THREAD

**Issue by 97CBR** [StanfordLegion/legion#1575]
I recently developed a demo, which is a daxpy program. It is a program that iterates hierarchically. That is, the input of the next layer of tasks depends on the output of the previous layer of tasks.
I'm running this demo on a 6-node cluster
>I want to know whether legion can perform communication and transmission results while computing tasks.
If can do this, What are the principles and core components  of realizing this ability?

If running this demo on single machine, can this demo overlap some calculations?

**Comment by elliottslaughter** [comment]
The answer depends on the specific details of your program. In general, yes, Legion can overlap.

The best way to determine what parallelism exists in a specific program is to generate an event graph. That should make it quite clear what overlap you can expect to achieve in your specific case.

Instructions here: https://legion.stanford.edu/debugging/#legion-spy

**Comment by 97CBR** [comment]
Thank you very much, according to your guidance I generated the event graph, analyzed the code overlap situation.
