### ISSUE TITLE
RFC: C++ 17 minimum standard version

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1576]
We previously set our minimum GCC to 8 (#1395). Several developers are considering features that could use C++ 17 (https://github.com/StanfordLegion/legion/issues/1545#issuecomment-1782092942, https://gitlab.com/StanfordLegion/legion/-/merge_requests/957#note_1607543828).

Since GCC 8 appears to support C++ 17 (https://gcc.gnu.org/projects/cxx-status.html#cxx17), should we consider that as a minimum?

I don't see downsides unless users are using compilers other than GCC that lack proper C++ 17 support.

Please post here if you foresee any complications.

**Comment by cmelone** [comment]
We are using GCC>8 in our CI with no issues.

**Comment by lightsighter** [comment]
At a minimum we also need sign-off from @pmccormick, @gshipman, @jiazhihao, and @mpokorny.

**Comment by pmccormick** [comment]
No concerns on my part -- 9 is probably also not an unreasonable target based on the use cases I'm aware of.

**Comment by mpokorny** [comment]
C++17 is the minimum standard any of my code depends on.

**Comment by jiazhihao** [comment]
We have switched to c++17 for the FlexFlow project a few months ago (due to external dependencies on some other libraries). So no concerns from us.

**Comment by elliottslaughter** [comment]
I also got offline confirmation from @syamajala.

Rather than belabor this in another Legion meeting, I suggest we move forward since it sounds like a non-issue for everyone. I'll put together an MR.

**Comment by elliottslaughter** [comment]
MR: https://gitlab.com/StanfordLegion/legion/-/merge_requests/982

**Comment by elliottslaughter** [comment]
I plan to merge this immediately after the March release:

https://gitlab.com/StanfordLegion/legion/-/merge_requests/982

If there are any objections, let me know as soon as possible.

**Comment by elliottslaughter** [comment]
We merged the C++ 17 minimum standard.
