### ISSUE TITLE
Some questions about overlap of dependent tasks

### ISSUE THREAD

**Issue by 97CBR** [StanfordLegion/legion#1578]
### first question
I have compiled a demo. There are two tasks. The regions of the two tasks are dependent. That is, the output of the previous task is used as the input of the next task.
For example:
The indexspace of a region ranges from 0 to 19. When partitioning is not passed, can the second task automatically start the calculation of 0 to 9 after the first task completes the calculation of 0 to 9? At the same time, the first task still calculates 10-19 data, and when it is finished, the second task automatically starts.

### second question
Based on the preceding demo, I use the partition method to process regions. When the partition is divided into eight parts, you can see that the generated profile information shows the overlap calculation described above.
However, in terms of execution time, it is found that the overall execution time becomes longer after the partition operation is performed. You can also observe that the utility proc in the profile information generates a lot of overhead. How can we do overlap without this overhead?

**Comment by elliottslaughter** [comment]
If your subregions have literally 10 elements each, then your tasks are likely to be tiny. There's no way for Legion to be efficient with such tiny tasks&mdash;but you probably also don't care because any real problem would have much more data.

The easiest way to address this is to just use a larger problem size with more data. E.g., millions of elements instead of tens.

Your first part question asks about a task that takes a region and starts before all of it is ready. It is *possible* to do this, but it is not idiomatic Legion. It is also likely to be very inefficient due to the way Legion works. It is usually better to launch two tasks, one for each part of the data that gets generated, and partition your regions appropriately. You still need to pick an appropriate problem size (as noted above) but this is the best way to get performance out of Legion because Legion can plan all of the data movement in advance.

**Comment by lightsighter** [comment]
I'd also recommend reading the [task bench paper](https://legion.stanford.edu/pdfs/taskbench2020.pdf) and understanding the concept of minimum effective task granularity (METG). Legion's METG is around 1ms, meaning you should be creating tasks that require at least 1ms of execution time before trying to use Legion. Note that if you use tracing, then Legion's METG will come down to around 100us.

**Comment by 97CBR** [comment]
@elliottslaughter @lightsighter 
The two screenshots here are the profile results that I calculated using the same data scale.
The number of elements is 2048000, -ll: cpu 2 

![image](https://github.com/StanfordLegion/legion/assets/21171109/037ae077-ff60-46cb-8c54-87c82181ef01)

The figure on the left shows the profile information without partitioning the region.
In the figure on the right, create_equal_partition is used to split 8  profile information.
As shown in the figure on the right, the overlap effect exists. However, the overall execution time increases from 1.884s to 2.541s.
**I want to ask why after slicing, the calculation time of each part is longer, and the overall time is longer.**

**Comment by elliottslaughter** [comment]
It's a bit hard to tell without a link to the actual profile, but as best I can tell from your screenshots, the tasks just take longer. This has nothing really to do with Legion and is a property of the kernels you've written. Without knowing what those kernels are doing, it's impossible to say why they would run slower after partitioning.

**Comment by 97CBR** [comment]
@elliottslaughter 
When the computing element size is 10240000, I gradually increase the number of partitions from 2, 4, 8, 16, 32, and 64. The execution efficiency increases until the number of partitions is 32. Then, the performance starts to deteriorate. In this case, the number of default task perform mappings is increasing. 
Maybe it's a low-level question, but I still want to ask why? How to calculate the optimal number of partitions?

![image](https://github.com/StanfordLegion/legion/assets/21171109/459ba4b2-8f79-4c0b-aa85-369fc54b6cd6)

**Comment by elliottslaughter** [comment]
It would help to see the profiles for 16, 32 and 64 partitions. Based on your one screenshot, it may be simply that the tasks are getting too small, but it's hard to say without actually seeing the profile.

**Comment by elliottslaughter** [comment]
@97CBR do you have any further questions?

**Comment by 97CBR** [comment]
@elliottslaughter @lightsighter I have no more questions. Thank you for your patient replies. Thank you very much.
