### ISSUE TITLE
Is legion mapping and dependence analysis dynamic?

### ISSUE THREAD

**Issue by Vincent-Xiao** [StanfordLegion/legion#1582]
I mean, if there are six sequential operations in a task,
1. the task graph (dependence graph and mapping) of the whole task is generated in advance before executing the first operation? This is static I guess.
2. Or the task graph of the 3rd operation is generated at runtime after finishing the 2nd operation.

I want to use Legion in a dynamic environment (such as the available hardware resource (eg. number of nodes) or dependence relationship of a certain operation are changing at runtime),  I guess dynamic mapping and dependence analysis can better utilize the hardware resources and provide optimal performance.

**Comment by rohany** [comment]
Legion is completely dynamic in the dependencies that tasks may have, and in the structure of the task graph. The task graph is created at runtime by the application and is constructed on the fly as operations are issued into the system.

Legion currently is not going to be able to handle the number of resources changing, but will handle the dependence operations changing between operations at runtime well.

**Comment by Vincent-Xiao** [comment]
That sounds great. Thanks a lot
