### ISSUE TITLE
Realm: compile time error in `shm.cc`

### ISSUE THREAD

**Issue by mariodirenzo** [StanfordLegion/legion#1589]
Hello, the latest version of control replication fails to compile on one of the computers that use for CI of HTR with the following error:

```
/home/gitlab-runner/legion/runtime/realm/shm.cc: In static member function 'static bool Realm::SharedMemoryInfo::create(Realm::SharedMemoryInfo&, size_t, const char*, int)':
/home/gitlab-runner/legion/runtime/realm/shm.cc:104:42: error: 'MFD_CLOEXEC' was not declared in this scope; did you mean 'FD_CLOEXEC'?
  104 |       fd = syscall(SYS_memfd_create, "", MFD_CLOEXEC);
      |                                          ^~~~~~~~~~~
      |                                          FD_CLOEXEC
make[2]: *** [runtime/CMakeFiles/RealmRuntime.dir/realm/shm.cc.o] Error 1
make[1]: *** [runtime/CMakeFiles/RealmRuntime.dir/all] Error 2
make: *** [all] Error 2
```

At a first look, this seems related to the latest changes to the shared memory management

@elliottslaughter, can you please add this issue to #1032 with high priority?

**Comment by elliottslaughter** [comment]
@muraj is this yours?

**Comment by cmelone** [comment]
I will add that this is the [second](https://legion.zulipchat.com/#narrow/stream/187787-general/topic/.60runtime.2Emk.3A1439.3A.20missing.20separator.60) compilation error uncovered by our CI in the past few days.

**Comment by muraj** [comment]
Yeah, this is actually older and related to the first one in that conda compilers seem to have a weird libc implementation.  I pushed a change to master to fix this, should be okay now.

**Comment by mariodirenzo** [comment]
Thanks for working on a fix. The issue is solved.
