### ISSUE TITLE
test disabled until legionspy mismatches are resolved

### ISSUE THREAD

**Issue by streichler** [StanfordLegion/legion#159]
Change ffc98c2 disables the `parallelize_tasks7` test, which is causing failures in both CI testing flows due to an error reported by legion spy.  Efforts are already under way to fix legion spy, but this will hopefully allow Travis/Gitlab to tell us if anything else breaks in the meantime.  When legion spy is fixed, commit ffc98c2 should be reverted.

**Comment by lightsighter** [comment]
If you want to keep the test running for now you can add the '-hl:inorder' flag to the test, which should resolve the out-of-order mapping issues that are confusing Legion Spy.

**Comment by elliottslaughter** [comment]
Unfortunately, something else breaks when we run with `-hl:inorder`. (Wonchan and I already tested this.)

**Comment by lightsighter** [comment]
Did you determine whether the missing copy was the result of a runtime bug or a Legion Spy bug?

**Comment by lightsighter** [comment]
This test passes Legion Spy validation reliably for me now in the master branch after the versioning merge.  Can one of you make the appropriate reversion and close the issue?

**Comment by elliottslaughter** [comment]
Should be fixed in master.
