### ISSUE TITLE
legion_prof_rs: multiple nodes merged in archive viewer

### ISSUE THREAD

**Issue by syamajala** [StanfordLegion/legion#1591]
This profile was generated from a 2 node run, but its only showing 1 node with twice as many processors:
https://legion.stanford.edu/prof-viewer/?url=https://sapling2.stanford.edu/~seshu/viz/subranks/legion_prof/

The log files are here: http://sapling2.stanford.edu/~seshu/viz/subranks/

**Comment by elliottslaughter** [comment]
Do you have a local patch that changes the Realm ID format? Legion Prof has to parse the proc/mem/etc. IDs:

https://gitlab.com/StanfordLegion/legion/-/blob/master/tools/legion_prof_rs/src/state.rs#L441-452

https://gitlab.com/StanfordLegion/legion/-/blob/master/tools/legion_prof_rs/src/state.rs#L689-699

**Comment by syamajala** [comment]
Oh yeah I do. I dont think we need that anymore. It was for when we were trying to scale rank/gpu to the full machine. I will remove it.

**Comment by elliottslaughter** [comment]
Either that or change Legion Prof to match. They just need to be in sync.
