### ISSUE TITLE
[Question] Requesting profiling data on "implicit" region copy tasks

### ISSUE THREAD

**Issue by brombaut** [StanfordLegion/legion#1598]
I'm trying to get profiling information on "implicit" copy tasks (by "implicit", I mean that the copy task is generated by Legion when a task needs to access a region that is not mapped to a physical instance in a memory that is viewable from the target processor, and so must issue a copy task).

This is opposed to "explicit" copies, which I've read about in [`legion_mapping.h`](https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/legion/legion_mapping.h#L804-870) and in the "Explicit Copy Operations" section of the [Explicit Ghost Regions](https://legion.stanford.edu/tutorial/ghost.html) tutorial. These are cases where the developer is explicitly issuing copy operations though, rather than the Legion runtime.

The event graph from Legion Spy of a trivial example is below. The copy tasks are what I'm trying to get profiling info on. This is just a super simple example where each task has READ_WRITE privilege's on a region, but each task is assigned to a target processor on a different node than the previous task, making Legion generate the copy task.

![event_graph_top_level-1](https://github.com/StanfordLegion/legion/assets/13170010/28db85f6-4c10-49e6-868a-7f7e614bf46b)

My best guess based on the explanation for `map_task` in `legion_mapping.h`, which says:

> The mapper can also ask for profiling information for the copies generated as part of the mapping of the task through the 'copy_prof_requests' field.

So I tried doing this and added a "copy" profiling request like so:

```cc
void CopyProfilingMapper::map_task(const MapperContext ctx, const Task& task, const MapTaskInput& input, MapTaskOutput& output) {
    DefaultMapper::map_task(ctx, task, input, output);
    output.task_prof_requests.add_measurement<ProfilingMeasurements::OperationStatus>();
    output.task_prof_requests.add_measurement<ProfilingMeasurements::OperationTimeline>();
    output.task_prof_requests.add_measurement<ProfilingMeasurements::RuntimeOverhead>();
    output.task_prof_requests.add_measurement<ProfilingMeasurements::OperationProcessorUsage>();
    // Here
    output.copy_prof_requests.add_measurement<ProfilingMeasurements::OperationCopyInfo>();
} 
```

But I get a logged warning for every map_task call saying
```
[0 - 7f2f1d01dc40]    0.041262 {4}{runtime}: [warning 1013] LEGION WARNING: Mapper Default Mapper on Processor 1d00000000000001 requested a profiling measurement of type 10001 which is not applicable to operation T1 (UID 8) and will be ignored.
```

What is the proper way to use the `copy_prof_requests` field here? It is even the expected way to actually do what I'm trying to do?

Thanks for any help!

**Comment by brombaut** [comment]
Thanks @rohany, what would be the proper way to use the `copy_prof_requests` field then? Like what measurement is it expecting?

Also just curious - what's the status of AutoMap? I see there is [your paper](https://legion.stanford.edu/pdfs/automap2023.pdf) that describes it, is there also any implementation materials (i.e., has automap been implemented on it's own branch in the Legion Gitlab repo)?

**Comment by rohany** [comment]
Perhaps I misspoke, I think I was thinking about the separate profiling that you can add to copies for `map_copy`. I'm not sure how `copy_prof_requests` is to be used.

> Also just curious - what's the status of AutoMap? I see there is [your paper](https://legion.stanford.edu/pdfs/automap2023.pdf) that describes it, is there also any implementation materials (i.e., has automap been implemented on it's own branch in the Legion Gitlab repo)?

@thiagotei is the leader of this project right now. I'm not sure where exactly it lives on github. but it's in a separate repository that he can point you to / give instructions on how to use it.

**Comment by thiagotei** [comment]
Hi @brombaut, the AutoMap repo is at https://gitlab.com/thiagotei/automap
I'd be glad to help you use it!
Let me know if you want to try it

**Comment by lightsighter** [comment]
> But I get a logged warning for every map_task call saying

I think this might just be an off-by-one bug in the runtime. I will check it tomorrow. Note the warning is about the `task_prof_requests` and not the `copy_prof_requests`.

> @lightsighter if you remember this discussion more.

If you're just interested in the performance of the copies then this is the right interface. The information that you won't get from this interface are things like the copy domain which might tell you which subsets of points are going to be moved by each copy because there is no good way to provide that kind of feedback to the mapper at the moment.

**Comment by brombaut** [comment]
@rohany Ok thanks for clarifying and thanks for sharing @thiagotei, I'll definitely have a look at it and see if I can get it running locally and let you know if I run into any issues!

@lightsighter Ok thanks for the heads up! Yea I'm interested in the performance of the copies, trying to get some metrics on how data movement is affecting overall app performance. I think I can get at least some of this info from Legion Prof output (e.g., start, end time of copy tasks, size transferred, etc.), but obvi that is all gathered offline after the app has run.

**Comment by lightsighter** [comment]
So I went make and looked at the code again. I think the runtime's warning is accurate. The only way you should be able to get this warning is if you asked for the `ProfilingMeasurements::RuntimeOverhead` in the `copy_prof_requests`, which is not something that is supported. Measuring the runtime overhead can only be done for tasks. I would go double check to see if there is anywhere that you are adding the `RuntimeOverhead` profiling measurement into the `copy_prof_requests`.

**Comment by brombaut** [comment]
I double checked everything, and I realized I mustve copy-pasted the wrong log line in my original message (sorry totally my bad). But I am still seeing a logged warning when trying to request copy information from the `copy_prof_requests` field (only difference from the original log line I posted is that it does say `profiling measurement of type 22` which is the correct profiling measurment type ID for `OperationCopyInfo`. I've included the full barebones mapper I'm using to get this issue as well as the log line.

```cc
#ifndef __COPY_PROFILING_MAPPER_CC__
#define __COPY_PROFILING_MAPPER_CC__

#include "default_mapper.h"
#include "legion.h"

using namespace Legion;
using namespace Legion::Mapping;

Logger log_copy_profiling_mapper("copy_profiling_mapper");

class CopyProfilingMapper : public DefaultMapper {
public:
    CopyProfilingMapper(Machine m, Runtime *rt, Processor p) : DefaultMapper(rt->get_mapper_runtime(), m, p) {} ;
    ~CopyProfilingMapper(void) { };

public:
    void map_task(const MapperContext ctx, const Task &task, const MapTaskInput &input, MapTaskOutput &output) {
        DefaultMapper::map_task(ctx, task, input, output);
        log_copy_profiling_mapper.print("[map_task]");
        output.copy_prof_requests.add_measurement<ProfilingMeasurements::OperationCopyInfo>();
    }
    void report_profiling(const MapperContext ctx, const Task &task, const TaskProfilingInfo &input) {
        // Don't do anything, just catch this call because DefaultMapper has an assert(false)
        log_copy_profiling_mapper.print("[report_profiling_task]");
    }
};

#endif // __COPY_PROFILING_MAPPER_CC__
```

Logs snipped:
```
[0 - 7ffb7d6afc40]    0.019236 {3}{copy_profiling_mapper}: [map_task]
[0 - 7ffb7d6afc40]    0.019271 {4}{runtime}: [warning 1013] LEGION WARNING: Mapper Default Mapper on Processor 1d00000000000001 requested a profiling measurement of type 22 which is not applicable to operation top_level (UID 2) and will be ignored. (from file /home/ben/work/legion/legion_repo/runtime/legion/legion_ops.cc:853)
For more information see:
http://legion.stanford.edu/messages/warning_code.html#warning_code_1013

[0 - 7ffb7d6afc40]    0.029054 {3}{copy_profiling_mapper}: [map_task]
[0 - 7ffb7d6afc40]    0.029079 {4}{runtime}: [warning 1013] LEGION WARNING: Mapper Default Mapper on Processor 1d00000000000001 requested a profiling measurement of type 22 which is not applicable to operation T1 (UID 4) and will be ignored. (from file /home/ben/work/legion/legion_repo/runtime/legion/legion_ops.cc:853)
For more information see:
http://legion.stanford.edu/messages/warning_code.html#warning_code_1013

[0 - 7ffb7d6a3c40]    0.029184 {3}{app}: [FAST_TASK] START
[0 - 7ffb7d6afc40]    0.029194 {3}{copy_profiling_mapper}: [map_task]
[0 - 7ffb7d6afc40]    0.029202 {4}{runtime}: [warning 1013] LEGION WARNING: Mapper Default Mapper on Processor 1d00000000000001 requested a profiling measurement of type 22 which is not applicable to operation T2 (UID 5) and will be ignored. (from file /home/ben/work/legion/legion_repo/runtime/legion/legion_ops.cc:853)
For more information see:
http://legion.stanford.edu/messages/warning_code.html#warning_code_1013

[0 - 7ffb7d6afc40]    0.029225 {3}{copy_profiling_mapper}: [map_task]
[0 - 7ffb7d6afc40]    0.029230 {4}{runtime}: [warning 1013] LEGION WARNING: Mapper Default Mapper on Processor 1d00000000000001 requested a profiling measurement of type 22 which is not applicable to operation T3 (UID 6) and will be ignored. (from file /home/ben/work/legion/legion_repo/runtime/legion/legion_ops.cc:853)
For more information see:
http://legion.stanford.edu/messages/warning_code.html#warning_code_1013

```
The logs continue like that for every `map_task` call.


From where this warning is logged from (`legion_ops.cc:853`), it doesn't look like `PMID_OP_COPY_INFO` is handled in the `filter_copy_request_kinds` case statement (see [here](https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/legion/legion_ops.cc#L831). I've also done a full grep of the legion repo for `PMID_OP_COPY_INFO` and it doesn't look like it is used anywhere except for where it is defined in `profiling.h` (see [here](https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/realm/profiling.h?ref_type=heads#L59) and [here](https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/realm/profiling.h?ref_type=heads#L186)).

**Comment by lightsighter** [comment]
Yup, the tests for profiling kinds in Legion were out of date with respect to some of the newer profiling requests that Realm offers. I've updated them for now, but we probably need to find a better way to keep them in sync.

**Comment by brombaut** [comment]
Retested this with the update, looks like it's working as expended. Thanks for your help!
