### ISSUE TITLE
Need get_index_subspace<3> fixes applied to s3d branch

### ISSUE THREAD

**Issue by streichler** [StanfordLegion/legion#16]
S3D uses 3-D "colors" for index subspaces.  This was broken with the merge of the
new partitioning API code and fixed fairly recently in the master branch.  Unfortunately,
the master branch contains other issues that break S3D.  To help with that debug, the
fixes for this issue need to be manually applied (they do not merge cleanly) to the s3d
branch.  Without them, the failure looks like this:

s3d.x: /autofs/nccs-svm1_home1/seant/s3d/legion_s3d/legion/runtime/lowlevel.h:82
1: LegionRuntime::Arrays::Point<DIM> LegionRuntime::LowLevel::DomainPoint::get_p
oint() const [with int DIM = 3]: Assertion `dim == DIM' failed.
*** Caught a fatal signal: SIGABRT(6) on node 0/1
[0] 6: /lib64/libc.so.6(__assert_fail+0xf0) [0x2aaaadd56740] 
[0] 7: ../bin/librhsf.so(_ZN13LegionRuntime9HighLevel16RegionTreeForest22create_
index_partitionENS0_14IndexPartitionENS0_10IndexSpaceENS0_10ColorPointERKSt3mapI
NS_8LowLevel11DomainPointENS6_6DomainESt4lessIS7_ESaISt4pairIKS7_S8_EEERKS8_23le
gion_partition_kind_t22legion_allocate_mode_t+0x562) [0x2aaaab02f0f2] 
[0] 8: ../bin/librhsf.so(_ZN13LegionRuntime9HighLevel7Runtime22create_index_part
itionEPNS0_10SingleTaskENS0_10IndexSpaceENS_8LowLevel6DomainERKSt3mapIjS6_St4les
sIjESaISt4pairIKjS6_EEEbi+0x3d5) [0x2aaaab0927a5] 
[0] 9: ../bin/librhsf.so(_ZN13LegionRuntime9HighLevel16HighLevelRuntime22create_
index_partitionEPNS0_10SingleTaskENS0_10IndexSpaceENS_8LowLevel6DomainERKSt3mapI
jS6_St4lessIjESaISt4pairIKjS6_EEEbi+0x91) [0x2aaaaaf6d5c1] 
[0] 10: ../bin/librhsf.so(_ZN13LegionRuntime9HighLevel16HighLevelRuntime22create
_index_partitionINS_6Arrays8BlockifyILj3EEEEENS0_14IndexPartitionEPNS0_10SingleT
askENS0_10IndexSpaceERKT_i+0x49c) [0x2aaaaae676fc] 
[0] 11: ../bin/librhsf.so(_Z14top_level_taskPKN13LegionRuntime9HighLevel4TaskERK
St6vectorINS0_14PhysicalRegionESaIS5_EEPNS0_10SingleTaskEPNS0_16HighLevelRuntime
E+0x431) [0x2aaaaae5d049]

**Comment by streichler** [comment]
Doesn't seem to build for me.  Were any changes required on the S3D side?

/autofs/nccs-svm1_home1/seant/s3d/legion_s3d/build/prf/rhsf_init.o: In function `LegionRuntime::HighLevel::IndexSpace LegionRuntime::HighLevel::HighLevelRuntime::get_index_subspace<3u>(LegionRuntime::HighLevel::SingleTask*, LegionRuntime::HighLevel::IndexPartition, LegionRuntime::Arrays::Point<3u>)':
rhsf_init.cc:(.text._ZN13LegionRuntime9HighLevel16HighLevelRuntime18get_index_subspaceILj3EEENS0_10IndexSpaceEPNS0_10SingleTaskENS0_14IndexPartitionENS_6Arrays5PointIXT_EEE[_ZN13LegionRuntime9HighLevel16HighLevelRuntime18get_index_subspaceILj3EEENS0_10IndexSpaceEPNS0_10SingleTaskENS0_14IndexPartitionENS_6Arrays5PointIXT_EEE]+0x4f): undefined reference to `LegionRuntime::HighLevel::HighLevelRuntime::get_index_subspace(LegionRuntime::HighLevel::SingleTask*, LegionRuntime::HighLevel::IndexPartition, LegionRuntime::LowLevel::DomainPoint const&)'

**Comment by lightsighter** [comment]
Try again.  For some reason I was not getting a link error when just building and running the library.

**Comment by streichler** [comment]
This branch is no longer interesting - closing.
