### ISSUE TITLE
new mapper API does not allow changing target processor in map_task

### ISSUE THREAD

**Issue by streichler** [StanfordLegion/legion#160]
The new mapper API changed the interface of `map_task()` to make the `task` argument (and its `target_proc` field) const, and renamed the `additional_procs` field in the output to `target_procs`.  However, it still behaves like "additional procs" - any processors put there are combined with the incoming value of `task.target_proc`, instead of replacing it.  This is annoying if you're trying not to send more work to that processor, and it's fatal if you're trying to send work to a processor of a different kind than `task.target_proc`, as the old requirement that all processors kinds must match still exists between the two fields.

**Comment by elliottslaughter** [comment]
Honestly, I thought this was how `output.target_procs` already worked. I'm pretty sure my existing mappers are written with this assumption already.

**Comment by lightsighter** [comment]
You're right that it should work.  I think the problem that Sean has discovered is that it doesn't work if 'target_proc' is currently a CPU and he puts one or more GPU processors in 'target_procs' and then the runtime complains that it can't make a processor group containing both CPUs and GPUs.

**Comment by streichler** [comment]
@lightsighter Did this get fixed some time in the last year?

**Comment by lightsighter** [comment]
This is not fixed yet. I want to make sure I still understand the use case that you are going for. It's only possible for 'output.target_procs' to still refer to the processors that are on the same node as the current processor (e.g. where the task is being mapped). There is no machinery to move a task to another node if 'output.target_procs' specifies processors that are not local to the current node. I think we can handle the switching of processor types (e.g. going from a CPU processor onto a GPU processor).  Does that cover the important use cases or not?

**Comment by streichler** [comment]
Yes, switching from CPU<->GPU on the same node would cover the use case I'm concerned about, and the limitation of not switching nodes again seems acceptable, but would probably need an explicit check and useful error message.

**Comment by lightsighter** [comment]
I'm going to close this issue since we already support this functionality and the appropriate check exists when mapper output checks are enabled. Here is the error message that is reported if you try to map the the task to a target processor not on the local node:
https://github.com/StanfordLegion/legion/blob/stable/runtime/legion/legion_tasks.cc#L3312-L3320

**Comment by streichler** [comment]
@lightsighter Is the original request covered?  i.e. is `task.target_proc` now ignored (or copied into `target_procs` as the default value)?

**Comment by lightsighter** [comment]
If the `target_procs` is left empty then the runtime will implicitly copy `task.target_proc` into it.
