### ISSUE TITLE
HTR correctness failure at 1 node with GPUs

### ISSUE THREAD

**Issue by cmelone** [StanfordLegion/legion#1600]
Something in this commit is causing most of our GPU tests to fail their correctness tests.

https://gitlab.com/StanfordLegion/legion/-/commit/238b827428d2dfa40f4b47262895c18997fc0702

Running in debug node and will report more details as I receive them.

**Comment by lightsighter** [comment]
@artempriakhin

**Comment by apryakhin** [comment]
Yes, we did merge GPU transposes which would likely be the cause. For those I run all the previously failing HTR unit tests manually though.

**Comment by apryakhin** [comment]
@cmelone please provide details on exact tests you are running and configurations

**Comment by cmelone** [comment]
Our unit tests are passing, these are our correctness/integration tests. So far, running in debug mode I don't see any assertions that are hit

**Comment by apryakhin** [comment]
@cmelone any updates on this? Could you please provide details on how to run correctness/integration tests? I would need a reproducer to get it root caused

**Comment by cmelone** [comment]
@apryakhin, apologies. I have been at SC this week. I will try to get you a reproducer by Monday.

**Comment by apryakhin** [comment]
Thanks, please take care and just ping me when you get a chance

**Comment by cmelone** [comment]
the reproducer is available on sapling at `/home/cmelone/gpu-nov`. You can rebuild Legion with `REBUILD=1 ./run.sh` and run the execution of HTR with `REBUILD=0 ./run.sh`.

the invocation of HTR is done through a python script that submits slurm jobs and verifies that the results have not regressed. So the application execution itself will never fail, only the correctness checks will not pass. The job outputs are available at `gpu-nov/htr/solverTests/RecycleBoundary`.


For instance, here is some simulation output showing incorrect data:

```
cmelone@sapling2:~/gpu-nov/htr/solverTests/RecycleBoundary$ tail -f 1x1x1/sample0/console.txt 
      Iter       Sim Time       Wall t     Delta Time      Avg Press       Avg Temp         Avg KE     Avg TotalE
         0  0.0000000e+00        0.586  0.0000000e+00  1.0000000e+00  1.0621641e+00  2.4235644e+00  4.9235644e+00
         1  7.0383784e-03        4.749  7.0383784e-03           -nan           -nan           -nan           -nan
```

let me know if there's anything I can help clarify.

**Comment by apryakhin** [comment]
I have it root-caused and patch is ready to be out for review:
```
apriakhin@sapling2:~/gpu-nov$ tail -f sample0/console.txt
        12  8.6347216e-02       52.228  7.2513578e-03  9.9988775e-01  1.0621618e+00  2.4231863e+00  4.9229057e+00
        13  9.3600774e-02       56.470  7.2535586e-03  9.9987838e-01  1.0621615e+00  2.4231546e+00  4.9228506e+00
        14  1.0085602e-01       60.657  7.2552474e-03  9.9986903e-01  1.0621612e+00  2.4231228e+00  4.9227954e+00
        15  1.0811187e-01       64.851  7.2558511e-03  9.9985969e-01  1.0621609e+00  2.4230911e+00  4.9227403e+00
        16  1.1536821e-01       69.072  7.2563365e-03  9.9985037e-01  1.0621606e+00  2.4230593e+00  4.9226852e+00
        17  1.2262469e-01       73.218  7.2564797e-03  9.9984106e-01  1.0621603e+00  2.4230275e+00  4.9226302e+00
        18  1.2988141e-01       77.469  7.2567239e-03  9.9983176e-01  1.0621600e+00  2.4229957e+00  4.9225751e+00
        19  1.3713848e-01       81.727  7.2570653e-03  9.9982247e-01  1.0621597e+00  2.4229639e+00  4.9225201e+00
        20  1.4439589e-01       85.965  7.2574104e-03  9.9981319e-01  1.0621594e+00  2.4229321e+00  4.9224651e+00
```

**Comment by lightsighter** [comment]
Can we add a test for this failure mode to the Realm test suite?

**Comment by cmelone** [comment]
Test cases pass, thank you Artem! I'll close once this gets merged.

**Comment by apryakhin** [comment]
Fix has been merged:

- https://gitlab.com/StanfordLegion/legion/-/merge_requests/1011

**Comment by apryakhin** [comment]
Once it's on control_replication please verify and close the issue

**Comment by lightsighter** [comment]
I did an upstream from master to the control replication branch so the fix should be there.

**Comment by cmelone** [comment]
thanks all!
