### ISSUE TITLE
About Performance Issues Using Accessors

### ISSUE THREAD

**Issue by AngryBear2** [StanfordLegion/legion#1601]
I found that it was slower when using accessors than when using arrays directly.For example,
`z[i][j] += x[i][k] * y[k][j];` is faster than `acc_out[Point<2>(j,i)]+=acc_x[Point<2>(k,i)]*acc_y[Point<2>(j,k)];`.
This problem is particularly obvious when I try to write GEMM, by creating a two-dimensional array, reading matrices A and B into the two-dimensional array through the value of acc in the accessor, calculating it, and then writing it back to the output region. It is much faster than using the accessor directly for matrix multiplication calculations. Because if I use a two-dimensional matrix, acc_A, acc_B, and acc_C each only needs to be accessed N\*N times, and when I use accessors directly for matrix budgeting, each accessor needs to be accessed N\*N*N times.When I try a matrix multiplication of 256 * 256, it slows me down by more than ten times.
What's the reason for the slower accessors, and is it a good idea to read into an array and recalculate?
By the way, why is the performance of 
`const FieldAccessor<READ_ONLY,double,1,coord_t,Realm::AffineAccessor<double,1,coord_t>>acc_x(regions[0], FID_X);`
 far greater than that of
`const FieldAccessor<READ_ONLY,double,1> acc_x(regions[0], FID_X);`

**Comment by rohany** [comment]
> Because if I use a two-dimensional matrix, acc_A, acc_B, and acc_C each only needs to be accessed N*N times, and when I use accessors directly for matrix budgeting, each accessor needs to be accessed N*N*N times.When I try a matrix multiplication of 256 * 256, it slows me down by more than ten times.

I don't understand this. Can you explain again? Using an accessor in the way that you've described should compile down to the same code as the direct array access.

One difference I see with your accessor statement is that you are accessing the arrays with different strides than in the non-accessor case, which greatly affects the locality that you are getting on your accesses (i.e. `acc_out` is being accessed (j, i), while `z` is being accessed (i, j), and others...)

`AffineAccessor` is much faster than a generic accessor as it is heavily templated to make sure that affine accessor accesses compile down into direct memory accesses.

**Comment by AngryBear2** [comment]
@rohany 
Here's the thing, sir.
![image](https://github.com/StanfordLegion/legion/assets/82449330/4ad47f3a-8270-4ae9-ad33-c1b3d6d8cd50)
It seems that you can get better performance by taking the data out of the Accessor, calculating it, and then saving it back, than by using more Accessors.
![image](https://github.com/StanfordLegion/legion/assets/82449330/9846591d-6fd9-4a6b-b03b-279737490b3c)
I want to know what overhead the accessor adds compared to direct array access.

**Comment by eddy16112** [comment]
Even though the AffineAccessor is heavily templated, I am curious wether the compiler can vectorize the access, while using the raw pointer, the compiler could easier apply the vectorization optimization.

**Comment by rohany** [comment]
May I see the entire code you’re comparing, in particular the instantiation of the accessors? 

There could be a few things wrong — you might have bounds checks on for accessors, or you might be mapping an instance that isn’t laid out the way you expect (the default mapper allocates instances in column major).

the best thing to do here though is to just look at the assembly of your loops — if everything is working as expected, the assembly should look nearly the same between accessor and no accessor.

**Comment by AngryBear2** [comment]
@eddy16112 I don't think the compiler is vectorizing the raw pointer, I'm using g++, and I'm using -O0 optimizations.

**Comment by AngryBear2** [comment]
@rohany 
`void gemm_task(const Task *task,
                const std::vector<PhysicalRegion> &regions,
                Context ctx, Runtime *runtime)
{
  assert(regions.size() == 3);
  assert(task->regions.size() == 3);
  const int point = task->index_point.point_data[0];
    const int row = *((const int*)task->args);

  const FieldAccessor<
    LEGION_READ_ONLY,double,2,coord_t,
    Realm::AffineAccessor<double,2,coord_t>>
    acc_x(regions[0], FID_X);
  const FieldAccessor<
    LEGION_READ_ONLY,double,2,coord_t,
    Realm::AffineAccessor<double,2,coord_t>>
    acc_y(regions[1], FID_Y);

  const FieldAccessor<
    LEGION_WRITE_DISCARD,double,2,coord_t,
    Realm::AffineAccessor<double,2,coord_t>>
    acc_out(regions[2], FID_Z);
      Rect<2> rect = runtime->get_index_space_domain(ctx,
                  task->regions[2].region.get_index_space());       
    for(int i=0;i<row;i++){
      for(int j=0;j<row;j++){
        for(int k=0;k<row;k++){
          acc_out[Point<2>(j,i)]+=acc_x[Point<2>(k,i)]*acc_y[Point<2>(j,k)];
        }
      }
    }
}`
`    IndexLauncher gemm_launcher(GEMM_TASK_ID, color_is, 
                              TaskArgument(&num_elements, sizeof(num_elements)), arg_map);
    gemm_launcher.add_region_requirement(
        RegionRequirement(input_lp, 0/*projection ID*/,
                          READ_ONLY, EXCLUSIVE, input_lr));
    gemm_launcher.region_requirements[0].add_field(FID_X);
    gemm_launcher.add_region_requirement(
        RegionRequirement(input_lp_y, 0/*projection ID*/,
                          READ_ONLY, EXCLUSIVE, input_lr_y));
    gemm_launcher.region_requirements[1].add_field(FID_Y);
    gemm_launcher.add_region_requirement(
        RegionRequirement(output_lp, 0/*projection ID*/,
                          WRITE_DISCARD, EXCLUSIVE, output_lr));
    gemm_launcher.region_requirements[2].add_field(FID_Z);`
The code looks like this, by contrast, just fetching the data from the accessor in gemm_task and calculating it.

**Comment by rohany** [comment]
What about the performance with O2 or O3? Accessors only get optimizes away if you turn on optimizations

**Comment by rohany** [comment]
As I mentioned before, these two codes aren’t exactly comparable either — you’re making accesses of different strides / in different index orders between the accessor version and the non accessor version

**Comment by AngryBear2** [comment]
I'm going to try O2 or O3, acc_out[Point<2>(j, i)] I think it's going to be out[i][j], because when I try the pointer pir++ of a two-dimensional array, From acc_out[Point<2>(j, i)] to acc_out[Point<2>(j+1, i)]

**Comment by AngryBear2** [comment]
@rohany yes! When I use O2 optimization, I can already get a huge performance boost, very close to direct array computing, although still a little slower.

**Comment by rohany** [comment]
> I'm going to try O2 or O3, acc_out[Point<2>(j, i)] I think it's going to be out[i][j], because when I try the pointer pir++ of a two-dimensional array, From acc_out[Point<2>(j, i)] to acc_out[Point<2>(j+1, i)]

As i mentioned above, the default mapper (which I assume you're using) allocates instances in fortran order,  or column major order. If you change line https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/mappers/default_mapper.cc?ref_type=heads#L2253 to be reversed, like https://github.com/rohany/taco/blob/DISTAL/DISTAL/runtime/taco_mapper.cpp#L391, then the instance will be allocated in row-major order, where doing `acc_out[Point<2>(i, j)]` will give you the memory location you expect.

**Comment by AngryBear2** [comment]
@rohany Well, I know this thing, my benefactor, I wish you health and happiness every day.
