### ISSUE TITLE
Reservation Acquire Poisoning

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#1610]
There are calls to `has_triggered` in the Realm reservation acquisition code that don't handle poison correctly. An example backtrace is the following:

[4] = /leonardo/home/userexternal/mdirenzo/htr/bin/prometeo.exec(Realm::Event::has_triggered() const+0x118) [0x3d681a8]
  [5] = /leonardo/home/userexternal/mdirenzo/htr/bin/prometeo.exec(Realm::Reservation::acquire(unsigned int, bool, Realm::Event) const+0x27) [0x3df5507]

Originally reported by @mariodr. Also adding @apryakhin since I think he volunteered to help with this one.

**Comment by mariodirenzo** [comment]
@elliottslaughter, can you add this issue to #1032?

**Comment by apryakhin** [comment]
I will be looking at this shortly today

**Comment by apryakhin** [comment]
I will be submitting the patch to fix this for review today

**Comment by apryakhin** [comment]
The patch has been merged

**Comment by lightsighter** [comment]
Assigning back to @mariodirenzo to confirm.

**Comment by mariodirenzo** [comment]
I can't reproduce the bug anymore. Thanks for fixing the issue
