### ISSUE TITLE
Modernize MiniAero test

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1611]
The MiniAero test that we run here:

https://github.com/StanfordLegion/legion/blob/6825fed8a40d52871d67c3fe27565f10f655546b/test.py#L538-L550

Uses old Legion interfaces. You can see an example of failure here: https://gitlab.com/StanfordLegion/legion/-/jobs/5718029852

Note that the failures require C++ 14 or newer to show up, which is why our CI did not previously expose them.

I went to look at updating the code, but getting all the accessors is going to require a bit of work. (It's not just updating the syntax, it's deducing the correct privileges for each accessor.)

Making this as a note to myself to get back to this, or else we'll have to delete the test at some point. Happy to have help if anyone wants to work on it.

**Comment by lightsighter** [comment]
Just a note that the only reason it shows up with c++14 is that c++ didn't add support for deprecated annotations until c++14. Legion has a deprecated macro that has no effect for versions of c++ less than c++14.

**Comment by lightsighter** [comment]
I've created a merge request for this that fixes all warnings up to c++17 and also removes all dependences on deprecated functionality.

https://github.com/magnatelee/miniaero-spmd/pull/1

**Comment by elliottslaughter** [comment]
We ultimately decided to resurrect the Regent version of MiniAero, which is compatible with DCR and therefore does not require must epoch launches.
