### ISSUE TITLE
legion_prof_rs: archive viewer search not working

### ISSUE THREAD

**Issue by syamajala** [StanfordLegion/legion#1616]
It seems like search is not working in the archive viewer.

https://legion.stanford.edu/prof-viewer/?url=https://sapling2.stanford.edu/~seshu/s3d_tdb/legion_prof.1/

When I try to search for HandoffToMPITask for example without zooming it says no results found, if I zoom into an interval where I think the task might be then it finds the task.

**Comment by lightsighter** [comment]
This is a duplicate of https://github.com/StanfordLegion/prof-viewer/issues/42

**Comment by lightsighter** [comment]
@syamajala Can you confirm that the behavior is the same as described in that prof-viewer issue?

**Comment by syamajala** [comment]
Yes it is.
