### ISSUE TITLE
Hang with Phase Barrier Migration

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#165]
The MPI interop example (examples/mpi_interop) currently will deterministically hang with phase barrier migration enabled. To reproduce: remove the -DDISABLE_BARRIER_MIGRATION flag from the Makefile and then run the following on sapling:

mpirun -n 4 -H n0000,n0001,n0002,n0003 ./mpi_interop

The run should hang every time in the same place.

**Comment by streichler** [comment]
Fixed with 04457a1.
