### ISSUE TITLE
Importlib error from legion_top.py

### ISSUE THREAD

**Issue by shriram-jagan** [StanfordLegion/legion#1654]
I get an error that gets resolved if I revert [this](https://gitlab.com/StanfordLegion/legion/-/commit/8a69f0b0c2fef6f1263403a222a20182bfea9b3c) commit.

Run command:
`legate  ${CONDA_PREFIX}/bin/pyminiweather`

I'm running the application from [here](https://github.com/shriram-jagan/pyminiweather). I haven't completely ruled out the possibility that the application hasn't been properly, so if you suspect that there is something wrong with `setup.py` or `setup.cfg` in pyminiweather, please let me know. Otherwise, it could just be related to the recent changes in `legion_top.py`

Error:

```
Traceback (most recent call last):
  File "/Users/sjagannathan/git/nv-legate/legion/bindings/python/build/lib/legion_top.py", line 477, in legion_python_main
    run_path(args[start], '__main__')
  File "/Users/sjagannathan/git/nv-legate/legion/bindings/python/build/lib/legion_top.py", line 282, in run_path
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 568, in module_from_spec
AttributeError: 'NoneType' object has no attribute 'loader'
```

**Comment by lightsighter** [comment]
Which version of Python are you using? I'm trying to find a line number that aligns here:

https://github.com/python/cpython/blob/3.9/Lib/importlib/_bootstrap.py

But it doesn't seem like 3.9, 3.10, 3.11, 3.12 match.

**Comment by shriram-jagan** [comment]
I'm using python 3.10.13 on my Mac and I can reproduce this error there too.

**Comment by lightsighter** [comment]
Ok, so that suggests that something is not installed quite right because we're not finding the file for the module on this line:

https://gitlab.com/StanfordLegion/legion/-/blob/master/bindings/python/legion_top.py?ref_type=heads#L281

and as a result this method is returning `None`:

https://docs.python.org/3/library/importlib.html#importlib.util.spec_from_file_location

So most likely whatever you passed to the `-m` option is not right for some reason... Does the module you passed in have a `__main__` definition?

**Comment by shriram-jagan** [comment]
yes, the module has `__main__` definition. Let me dig a little deeper into how this works and then I'll update the issue here.

**Comment by lightsighter** [comment]
For some reason we're probably either not finding the file or the definition for whatever reason.

**Comment by shriram-jagan** [comment]
I tried to reproduce this with the latest changes but I don't see the issue anymore. It looks like Marcin/Elliott might have fixed this issue while I was on vacation. Marking this as closed.
