### ISSUE TITLE
Legion Prof: CI diff failure

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1670]
Thanks to https://gitlab.com/StanfordLegion/legion/-/merge_requests/1184 we are now capturing the output of failed Legion Prof CI jobs.

That means we got the log files for this job:

https://gitlab.com/StanfordLegion/legion/-/jobs/6506637488

Here: [gcc9_cxx17_release_prof_regent.zip](https://github.com/StanfordLegion/legion/files/14799171/gcc9_cxx17_release_prof_regent.zip)

CC @eddy16112

**Comment by elliottslaughter** [comment]
Another failure: [clang12_cxx17_release_prof_regent.zip](https://github.com/StanfordLegion/legion/files/14860902/clang12_cxx17_release_prof_regent.zip)

**Comment by elliottslaughter** [comment]
Another one: [gcc9_cxx17_release_mpi_prof_regent.zip](https://github.com/StanfordLegion/legion/files/15138722/gcc9_cxx17_release_mpi_prof_regent.zip)


From job: https://gitlab.com/StanfordLegion/legion/-/jobs/6730137063

**Comment by lightsighter** [comment]
Another one: [gcc9_cxx17_release_mpi_prof_regent.zip](https://github.com/StanfordLegion/legion/files/15284586/gcc9_cxx17_release_mpi_prof_regent.zip)

From job: https://gitlab.com/StanfordLegion/legion/-/jobs/6829536497

**Comment by elliottslaughter** [comment]
Well this is irrelevant now that Python has been removed.
