### ISSUE TITLE
Resource exhaustion in S3D

### ISSUE THREAD

**Issue by streichler** [StanfordLegion/legion#17]
With stencils enabled, something is going wrong with reuse and/or collection of
unused instances and S3D runs out of FB memory after running for a while.
(In the case of PRF with 48^3 per node, "a while" is "3 time steps.")  The bug was
introduced some time after 7b73e229f83ae0a87c6240d9e35393201c1a4733, and
is suspected to be related to the changes to the handling of restricted instances.

**Comment by lightsighter** [comment]
Can you try modifying the mapper to not create persistent regions for stencil computations?

**Comment by lightsighter** [comment]
Actually, nevermind, this doesn't work for me either.

**Comment by streichler** [comment]
This branch is no longer interesting - closing.
