### ISSUE TITLE
cmake complains that gcc 12.2.0 doesn't support C++17

### ISSUE THREAD

**Issue by jpietarilagraham** [StanfordLegion/legion#1700]
Cmake identifies the compiler is gcc 12.2.0 but then erroneously claims the compiler doesn't support c++17. 

[spack-build-out.txt](https://github.com/user-attachments/files/15674478/spack-build-out.txt)

**Comment by elliottslaughter** [comment]
You are explicitly passing C++ 11 to the CMake command line:

```
-DCMAKE_CXX_STANDARD:STRING=11
```

**Comment by jpietarilagraham** [comment]
This is off the master branch.  24.03.0 is fine.

**Comment by elliottslaughter** [comment]
This is a bug in the Legion Spack package, which apparently has not been updated. Legion now requires C++ 17.

Until the Spack package gets updated you would need to build with the variant `cxxstd=17`. Otherwise Spack explicitly builds for C++ 11 and Legion of course objects.

**Comment by elliottslaughter** [comment]
Potential posted to https://github.com/spack/spack/pull/44596

@jpietarilagraham If you'd like to test, I think you can clone my Spack fork (assuming you have no other local changes you need).

**Comment by elliottslaughter** [comment]
Fixed by https://github.com/spack/spack/pull/44596.
