### ISSUE TITLE
Regent: ROCm 5.1 retiring from Frontier

### ISSUE THREAD

**Issue by syamajala** [StanfordLegion/legion#1702]
OLCF is planning on removing ROCm 4.5.2, 5.1.0, and 5.2.0 from Frontier on July 9th. We can either complain or bump the minimum version to 5.4.0.

**Comment by elliottslaughter** [comment]
Regent supports ROCm 5.4.3, so that is fine as far as that goes. However, if I recall correctly, every version newer than 5.1.0 results in the HSA out of resources error we've been tracking with OLCF. Therefore, until we have a fix for that it would probably be best to avoid removing 5.1.0.

**Comment by elliottslaughter** [comment]
We addressed this by moving to ROCm 6.0.0 and LLVM 18. So I don't think we have any remaining reason to object to old versions being removed.
