### ISSUE TITLE
common.h should not be installing in /include directly

### ISSUE THREAD

**Issue by junghans** [StanfordLegion/legion#172]
The low-level runtime headers, e.g. `common.h`, get installed in `/include` directly without a subdirectory, that calls from problems.

/cc @tuxfan

**Comment by tuxfan** [comment]
Really, the legion structure should be changed to something like:

legion/
           headers (common.h, etc)
           highlevel/ (this would replace the current 'legion' directory)
           realm/
           mappers/

**Comment by streichler** [comment]
@junghans Can you propose a change to the cmake build that implements this?  I'll learn how to use cmake one of these days...

The one stylistic change I'd make compared to @tuxfan's suggestion is to keep the legion headers just in legion/ instead of legion/highlevel/.  Most applications will only use those headers, so the "highlevel" part would be superfluous.

**Comment by junghans** [comment]
Sure, assign the issue to me!

**Comment by junghans** [comment]
This is now a [Gentoo bug](https://bugs.gentoo.org/show_bug.cgi?id=617266).

**Comment by elliottslaughter** [comment]
I pushed an initial workaround for this in 5a3a9c0471a1929a342fd86015ff065a4ff932e8. The longer-term answer is that all header files should belong to either legion or realm and moved into one of those two subdirectories. (I.e. there should not be any need for a hierarchical directory structure for headers.)

**Comment by junghans** [comment]
@elliottslaughter: Nice, can you guys make a new release, so that I can push the fix into Gentoo.

**Comment by elliottslaughter** [comment]
@junghans 17.05.0 has been released.

**Comment by junghans** [comment]
> @junghans 17.05.0 has been released.

I got an email from [Redhat's bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1456066), too ;-)
