### ISSUE TITLE
Realm: Crashes on WSL

### ISSUE THREAD

**Issue by RAMitchell** [StanfordLegion/legion#1720]
When attempting to run a legate program with GPU on windows subsystem for linux I get the following crash

```
[0 - 7f7923ad5000]    0.000000 {5}{gpu}: /tmp/conda-croot/legate_core/work/arch-conda/_skbuild/linux-x86_64-3.12/cmake-build/_deps/legion-src/runtime/realm/cuda/cuda_module.cc(4426):NVML_FNPTR(nvmlDeviceGetMemoryAffinity)( info->nvml_dev, info->MAX_NUMA_NODE_LEN, info->numa_node_affinity, NVML_AFFINITY_SCOPE_NODE) = 3
```

Return code 3 corresponds to NVML_ERROR_NOT_SUPPORTED = 3 The requested operation is not available on target device. The function `nvmlDeviceGetMemoryAffinity` is not supported for Windows.

When running legate with CPU only the program completes without issue.

The workaround would be to provide a fallback when this API function is not supported. There also may be other linux only functions in use, this was just the first one I hit.

**Comment by muraj** [comment]
https://gitlab.com/StanfordLegion/legion/-/merge_requests/1396 out for review, should resolve the WSL issues as tested locally.

**Comment by RAMitchell** [comment]
Thank you!

**Comment by muraj** [comment]
e386769bebe322d223cda0b59a34d7bf0e04e2f9 was merged in, moving to close.  Please verify and reopen if this is still an issue.  Thank you!
