### ISSUE TITLE
Fuzzer: incorrect application of reductions

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1728]
I have one fuzzer seed that is generating three different behaviors non-deterministically. Here are the Spy logs for the three cases:

 * Case 1: fuzzer reports bad data - [case1_bad_data.log](https://github.com/user-attachments/files/16386265/case1_bad_data.log)
 * Case 2: Legion reports reuse of a reduction instance - [case2_reuse_error.log](https://github.com/user-attachments/files/16386273/case2_reuse_error.log)
 * Case 3: passes, no fuzzer or Legion errors - [case3_pass.log](https://github.com/user-attachments/files/16386275/case3_pass.log)

Running Legion Spy on the case 1 log produces:

```
ERROR: Missing reduction from field Field 2 of instance Instance 0x4000000000000011 of region requirement 0 of Mapping Op 65
```

A case 2 error message looks like:

```
[0 - 7f603deddc00]    0.194312 {6}{runtime}: [fatal 2015] LEGION FATAL: Unsafe re-use of reduction instance detected due to alternating un-flushed reduction operations 1048644 and 1048674. Please report this 
use case to the Legion developer's mailing list so that we can help you address it. (from file /scratch/eslaught/fuzzer-experiment/legion/runtime/legion/legion_analysis.cc:16218)
```

It's possible that the case 2 behavior is entirely unrelated, but we'll revisit once case 1 is fixed.

Fuzzer version: https://github.com/StanfordLegion/fuzzer/commit/c88654f9c270bfff6cd7acc1d01709d914cd90d7

Legion version: 13ad3c2e2738dc5224408a22405bcabf612a6d97

Command line to generate logs:

```
./build_spy_single/src/fuzzer -fuzz:seed 3986 -fuzz:ops 12 -ll:util 1 -ll:cpu 3 -level 4,legion_spy=2 -logfile spy_%.log
```

**Comment by lightsighter** [comment]
Fixed with: https://gitlab.com/StanfordLegion/legion/-/merge_requests/1401

**Comment by elliottslaughter** [comment]
I had a longer comment I was typing up, but in the process of debugging it I think I found a flaw in the fuzzer's disjointness analysis.

**Comment by elliottslaughter** [comment]
Fuzzer bug fixed here: https://github.com/StanfordLegion/fuzzer/commit/4b526ebb7c02a8c5ca1f7bd6e46972ae12f44ed1
