### ISSUE TITLE
Add online hang detection in Realm

### ISSUE THREAD

**Issue by eddy16112** [StanfordLegion/legion#1741]
We plan to add hang detection support for Realm. We will first focus on the dead lock. We may explore the live lock in the future.  
Some thoughts from @apryakhin 

https://docs.google.com/document/d/1z799DnEhgXq4XJ5CQoc6x78JbyinLaXhlUqVttXXx38/edit

**Comment by lightsighter** [comment]
Isn't this a duplicate of #1037?

**Comment by eddy16112** [comment]
Ah, I did not realize it. I will close this one.
