### ISSUE TITLE
Fuzzer crash in `InstanceBuilder::handle_profiling_response`

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1764]
I'm seeing a new, low-probability failure mode in the fuzzer in all configurations: debug/release, single- and multi-node.

No assert, it's just a straight crash:

```
#4  <signal handler called>
#5  Legion::Internal::InstanceBuilder::handle_profiling_response (this=0x7fd5988bffe0, 
    response=..., orig=<optimized out>, orig_length=<optimized out>, fevent=...)
    at /scratch/eslaught/fuzzer-experiment-7/legion/runtime/legion/legion_instances.cc:3947
#6  0x00007fd5c1de1df3 in Legion::Internal::Runtime::profiling_runtime_task (args=0x7fd58400eb30, 
    arglen=48, userdata=<optimized out>, userlen=<optimized out>, p=...)
    at /scratch/eslaught/fuzzer-experiment-7/legion/runtime/legion/runtime.cc:33019
#7  0x00007fd5c0b78a35 in Realm::LocalTaskProcessor::execute_task (this=0x559c142e7f90, func_id=5, 
    task_args=...) at /scratch/eslaught/fuzzer-experiment-7/legion/runtime/realm/bytearray.inl:150
#8  0x00007fd5c0bca8a3 in Realm::Task::execute_on_processor (this=0x7fd58400e9b0, p=...)
    at /scratch/eslaught/fuzzer-experiment-7/legion/runtime/realm/bytearray.inl:39
#9  0x00007fd5c0bca95a in Realm::UserThreadTaskScheduler::execute_task (this=<optimized out>, 
    task=<optimized out>)
    at /scratch/eslaught/fuzzer-experiment-7/legion/runtime/realm/tasks.cc:1687
#10 0x00007fd5c0bc8de4 in Realm::ThreadedTaskScheduler::scheduler_loop (this=0x559c142e8330)
    at /scratch/eslaught/fuzzer-experiment-7/legion/runtime/realm/tasks.cc:1158
```

The failure of probability is very low, something on the order of 1 in 2000 runs (or even worse). Therefore, the only way to hit this is to run the full fuzzer suite. Fortunately you can reproduce in a single-node debug mode configuration.

Note: this is an `-g -O2` debug mode run. I am retrying on pure `-g` debug mode, but haven't hit a failure so far. I will post a follow-up comment if I get reproduction in `-g` debug mode.

Also note that I regularly run the fuzzer out to 100k trials on single node, so I am confident this is a **new** failure mode, not merely one we've missed in previous testing.

To reproduce:

```
cd /scratch/eslaught/fuzzer-experiment-7
./experiment/do_all.sh sapling
```

I've hacked the `do_all.sh` script so it should do exactly what is require to reproduce and no more.

Note that this uses `REALM_FREEZE_ON_ERROR` to catch failures. Therefore, the job is *expected* to hang. Once you launch the job, wait about 30 minutes (or an hour if you want to be safe) and then SSH directly to the node to find frozen processes. Typically you'll do something like:

```
ps aux | grep fuzzer
```

What you're looking for is the lowest seed number. If all the seeds are clumped together, that means nothing has frozen yet. If one sticks out (e.g., because it's several thousands lower than all the other values) then that's the frozen one. Attach to it with `gdb` and look for the thread running `nanosleep`.

To rebuild:

```
srun -n 1 -N 1 -c 40 -p all --exclusive --pty bash --login
cd /scratch/eslaught/fuzzer-experiment-7/legion/build_debug_single
make clean && make install -j20
cd ../../build_debug_single
make clean && make -j20
```

Fuzzer version: https://github.com/StanfordLegion/fuzzer/commit/3ef4c19266907eee6c5df86d9dc25b79b47f2d4b

Legion version: ba6d63b6431ba4370f432639f153725781542b27

**Comment by lightsighter** [comment]
Try with: https://gitlab.com/StanfordLegion/legion/-/merge_requests/1473

**Comment by elliottslaughter** [comment]
I've completed about 80k runs so far and this appears to be resolved. We can close this once the MR merges.
