### ISSUE TITLE
CMake build breaks on AIO

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#187]
When I try to build the examples with CMake on default settings, I get a failure to link against Posix AIO. Is there a flag that controls this? (And why wouldn't it auto-detect properly?)

```
$ mkdir build
$ cd build/
$ cmake -DLegion_BUILD_EXAMPLES=ON ..
...
$ make
...
[ 65%] Linking CXX executable ../../bin/dynamic_registration
../../lib/librealm.a(lowlevel_dma.cc.o): In function `LegionRuntime::LowLevel::PosixAIOWrite::launch()':
/home/elliott/legion/runtime/lowlevel_dma.cc:2034: undefined reference to `aio_write'
...
```

Also, more generally, is there documentation for the flags supported by the current CMake build---or could we add some? Does CMake respect environment variables at all, particularly the ones we had set up in the old build system?

Thanks.

CC: @chuckatkins @junghans

**Comment by elliottslaughter** [comment]
Should have mentioned before: This is on Ubuntu 14.04 with the Ubuntu packaged versions of CMake, build-essentials, etc.

**Comment by junghans** [comment]
Can you post the same line when build verbose (i.e. `make VERBOSE=1`)? I guess there is a `-lrt` missing on the link line.

**Comment by chuckatkins** [comment]
i was able to reproduce the error.  It doesn't show up when using GASNet because GASNet is pulling in the dependency already.  I've got a branch to fix another CMake issue so I'll fix this and submit the PR shortly.

**Comment by junghans** [comment]
`aio_write()` is used directly in `lowlevel_dma.cc` and hence librealm should be linked again librt on `UNIX`, right?

**Comment by chuckatkins** [comment]
Yes.  See https://github.com/StanfordLegion/legion/pull/188/commits/a56953a3cbbdd91bf54ea5ca60cb37d58055de6f

**Comment by junghans** [comment]
I had the same idea ;-)

**Comment by chuckatkins** [comment]
Fixed by #188

**Comment by chuckatkins** [comment]
@elliottslaughter now fixed in master

**Comment by elliottslaughter** [comment]
Thanks. The new `./test.py` script in the top-level directory has some half-baked support for cmake. E.g.:

`./test.py --test=tutorial --use=cmake`

Right now this builds with cmake and rebuilds with make since it hasn't yet been taught how to find the binaries that cmake builds, but we'll get to a fully functional version eventually.
