### ISSUE TITLE
Performance degradation with runtime tracing

### ISSUE THREAD

**Issue by magnatelee** [StanfordLegion/legion#190]
I found the runtime tracing significantly slows down the logical analysis. I got this timeline from the circuit example with 20 pieces on a single node:

![image](https://cloud.githubusercontent.com/assets/331175/18967592/a58c95b2-863a-11e6-8f04-45130cf52d97.png)

You can see that the logical analysis for each instance of task 'update_voltages' took 19s after the first iteration.

Here is the vtune profile of the same run. It clearly shows that most of cpu time was spent in TraceCloseOp::record_trace_dependece where the captured trace is replayed.

![image](https://cloud.githubusercontent.com/assets/331175/18968060/64c09d88-863c-11e6-9c1f-37dcbf6e94a5.png)

Until this issue is fixed, it's better not to enable the runtime tracing, especially in the apps that use indexspace launches with >20 point tasks. However, this issue isn't reproduced in the versioning branch.

**Comment by lightsighter** [comment]
Closing this now that versioning is merged into master.
