### ISSUE TITLE
improve Accessor debug messages

### ISSUE THREAD

**Issue by jpietarilagraham** [StanfordLegion/legion#192]
Give better debug messages when
1) calling uninitialized Accessor currently segfaults
2) Accessor type does not match Allocator type

**Comment by lightsighter** [comment]
As of the deppart branch it is impossible to create an uninitialized field accessor and almost all field accessors (with the exception of reduction ones where LHS type != RHS type) checks that the size of the field being requested of the accessor matches the size of the allocated field being requested. Field size isn't great for checking that the type of the accessor matches the type of the field but in the absence of runtime type information it will be our proxy for now. Closing this issue.
