### ISSUE TITLE
Dynamic task registration causing crash in Realm

### ISSUE THREAD

**Issue by sidelnik** [StanfordLegion/legion#193]
I've encountered a problem where Realm is crashing when trying to dynamically register the same task more than once. 

This problem only occurs when the following conditions are met: 
1) Enable the NDEBUG macro to disable assertions in the runtime. Oddly enough, assertions don't get thrown normally. This problem only occured when adding the NDEBUG macro to the Makefile.
2) Must be using GASNET. Doesn't seem to occur on single node.
3) The problem occurs depending on the number of processes being launched (e.g. "-np 2" and "ll:cpu 2")

I've attached a simple test case that demonstrates the failure on my machine. Take note of the for loop inside the top level task. Varying the trip count of this loop causes the bug to appear.

```
#include <cstdio>
#include <cassert>
#include <cstdlib>
#include "legion.h"
using namespace Legion;

#define N 3

enum TaskIDs {
  TOP_LEVEL_TASK_ID,
};

int func(const Task *task,
             const std::vector<PhysicalRegion> &regions,
             Context ctx, Runtime *runtime) {
    return 123;
}

void top_level_task(const Task *task,
                    const std::vector<PhysicalRegion> &regions,
                    Context ctx, Runtime *runtime) {

    for (int i = 0; i < N; i++) {
        size_t APPLY_LEAF_TASK_ID = runtime->generate_dynamic_task_id();
        TaskVariantRegistrar registrar(APPLY_LEAF_TASK_ID, "apply_leaf_variant", true /* global */);

        registrar.set_leaf(true);
        registrar.global_registration = true;
        registrar.add_constraint(ProcessorConstraint(Processor::LOC_PROC));

        runtime->register_task_variant<int, func>(registrar);
        TaskLauncher launcher(APPLY_LEAF_TASK_ID, TaskArgument(&i, sizeof(i)));

        Future f = runtime->execute_task(ctx, launcher);
        int result = f.get_result<int>();
        std::cout << "result = " << result << "\n" << std::flush;
    }
}

int main(int argc, char **argv) {
  Runtime::set_top_level_task_id(TOP_LEVEL_TASK_ID);
  Runtime::register_legion_task<top_level_task>(TOP_LEVEL_TASK_ID,
      Processor::LOC_PROC, true/*single*/, false/*index*/,
      AUTO_GENERATE_ID, TaskConfigOptions(), "top_level");

  return Runtime::start(argc, argv);
}
```

The command used to run this is:
$GASNET/bin/amudprun -np 2 -spawn L ./tasks_and_futures -ll:cpu 2

A stack trace to this has been attached.

[Makefile.txt](https://github.com/StanfordLegion/legion/files/512089/Makefile.txt)
[backtrace.txt](https://github.com/StanfordLegion/legion/files/512077/backtrace.txt)
[tasks_and_futures.txt](https://github.com/StanfordLegion/legion/files/512085/tasks_and_futures.txt)

**Comment by streichler** [comment]
@sidelnik Are there any error messages printed before the crash?

**Comment by sidelnik** [comment]
@streichler Nope, no errors thrown (just the SIGSEGV message). In the example I've included above, the only program output occurs from std::cout statement at the end of the for loop.

**Comment by sidelnik** [comment]
I should add that this bug occurs both in the stable and master branches.

**Comment by streichler** [comment]
You're not seeing
```
[1 - 7f5515bb0700] {6}{taskreg}: attempt to register a task function of improper type: INVALIDTYPE
```
?  Realm is complaining that it is getting garbage input, but you've disabled the "assert fail because there's no way to make useful progress from this point on" via NDEBUG.  :)

I'm digging into why the CodeDescriptor that Realm is getting is garbage now.

**Comment by sidelnik** [comment]
@streichler Sorry, you're right. I am seeing the same taskreg message above. It appears when I enable GASNET_BACKTRACE=1.

**Comment by streichler** [comment]
@sidelnik Please pick up a18c32d and try again.  We have a bunch of warning scrubbing to do for the NDEBUG build, but hopefully there aren't too many more functional bugs.

**Comment by sidelnik** [comment]
Perfect, the fix seems to be working. Closing the bug.
