### ISSUE TITLE
Regent SPMD Phase Barrier Cycle

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#194]
Regent's SPMD transformation non-deterministically generates phase barrier cycles for the test parallelize_task_with_spmd3.rg.  I was seeing it about 1 in every 10 runs.  An easy way to detect it is to also run with the -hl:inorder flag and user-level threads disabled.  When it hangs, you can then inspect the launchers for the two offending operations and confirm that they come from different shards.  I was only able to make it reproduce with multi-node runs.  Here is my command line:

LAUNCHER='mpirun -H n0002,n0003 -n 2 -npernode 1 --bind-to none -x TERRA_PATH -x LD_LIBRARY_PATH -x INCLUDE_PATH -x LG_RT_DIR -x USE_RDIR' ./regent.py tests/regent/run_pass/parallelize_tasks_with_spmd3.rg -ll:cpu 3 -fbounds-checks 1 -fparallelize-dop 9 -fflow-spmd 1 -fflow-spmd-shardsize 3

In one particular example, I saw the following case:

Copy Launcher:
Arrive Barrier: 0x7000000001600001
Wait Barrier: 0x7000000001f00002

Task Launcher:
Arrive Barrier: 0x7000000001f00001
Wait Barrier: 0x7000000001600002

That is a phase barrier cycle straight from the application because waits always occur on the previous generation.  Since these came straight from the launchers I know that the runtime hasn't been able to mess anything up.

**Comment by lightsighter** [comment]
One known complicating factor that was just discovered is that the compiler's auto-parallelization analysis is possibly not generating the same code on multiple nodes (which may explain why this only reproduces with multiple nodes) and maybe responsible for this issue too.  @magnatelee will tell us when this previous bug has been resolved.

**Comment by elliottslaughter** [comment]
If that's true you can check it by using saveobj to dump a binary and then
launching that. There will only be one binary so there will only be one
copy of the code even if compilation is nondeterministic.

**Comment by magnatelee** [comment]
A fix for the auto-parallelizer has been pushed, so the previous bug shouldn't interfere with this one anymore.

**Comment by lightsighter** [comment]
Looks like the bug persists after the fix for the auto-parallelizer.

**Comment by lightsighter** [comment]
With Wonchan's help I pretty printed the code from each node in a separate file and then ran the job. On a job that hung, I see the following diff between the two codes.  Looks like the barrier names just got reversed.

76c76
<   writes($shallow_$intersection_$shard_$__t8_$shard_$__t15.f), writes($shard_$__t15.f), writes($shallow_$intersection_$shard_$__t8_$shard_$__t11.f), writes($shard_$__t8.h), writes($shard_$__t8.g), writes($shard_$__t8.f), writes($shard_$__t11.f), writes($shard_$__t8.f), writes($shallow_$intersection_$shard_$__t8_$shard_$__t11.f), writes($shard_$__t8.g), writes($shard_$__t8.h), writes($shard_$__t11.f), writes($shallow_$intersection_$shard_$__t8_$shard_$__t15.f), writes($shard_$__t15.f), simultaneous($shard_$__t8.h), simultaneous($shard_$__t8.g), simultaneous($shard_$__t8.f), simultaneous($shallow_$intersection_$shard_$__t8_$shard_$__t11.f), simultaneous($shard_$__t15.f), simultaneous($shard_$__t11.f), simultaneous($shallow_$intersection_$shard_$__t8_$shard_$__t15.f), no_access_flag($shallow_$intersection_$shard_$__t8_$shard_$__t11.f), no_access_flag($shallow_$intersection_$shard_$__t8_$shard_$__t15.f)
---
>   writes($shard_$__t11.f), writes($shallow_$intersection_$shard_$__t8_$shard_$__t11.f), writes($shallow_$intersection_$shard_$__t8_$shard_$__t15.f), writes($shard_$__t8.h), writes($shard_$__t8.g), writes($shard_$__t8.f), writes($shard_$__t15.f), writes($shard_$__t8.g), writes($shard_$__t8.h), writes($shard_$__t11.f), writes($shallow_$intersection_$shard_$__t8_$shard_$__t15.f), writes($shallow_$intersection_$shard_$__t8_$shard_$__t11.f), writes($shard_$__t15.f), writes($shard_$__t8.f), simultaneous($shard_$__t11.f), simultaneous($shallow_$intersection_$shard_$__t8_$shard_$__t15.f), simultaneous($shallow_$intersection_$shard_$__t8_$shard_$__t11.f), simultaneous($shard_$__t8.h), simultaneous($shard_$__t8.g), simultaneous($shard_$__t8.f), simultaneous($shard_$__t15.f), no_access_flag($shallow_$intersection_$shard_$__t8_$shard_$__t15.f), no_access_flag($shallow_$intersection_$shard_$__t8_$shard_$__t11.f)
79d78
<     var $intersection_$shard_$__t8_$shard_$__t15 : list(list(region(ispace(int3d), fs()))) = list_cross_product_complete($shard_$__t8, $shallow_$intersection_$shard_$__t8_$shard_$__t15)
80a80
>     var $intersection_$shard_$__t8_$shard_$__t15 : list(list(region(ispace(int3d), fs()))) = list_cross_product_complete($shard_$__t8, $shallow_$intersection_$shard_$__t8_$shard_$__t15)
87,88c87,88
<       $empty_out_$shard_$__t11_<f> = advance($empty_out_$shard_$__t11_<f>)
<       $full_in_$shard_$__t15_<f> = advance($full_in_$shard_$__t15_<f>)
---
>       $empty_out_$shard_$__t15_<f> = advance($empty_out_$shard_$__t15_<f>)
>       $full_in_$shard_$__t11_<f> = advance($full_in_$shard_$__t11_<f>)
91c91
<         stencil1.parallelized($shard_$__t8[$local_index], $shard_$__t11[$local_index], $__t7, $__t18, awaits($full_in_$shard_$__t11_<f>[$local_index]), arrives($empty_in_$shard_$__t11_<f>[$local_index]))
---
>         stencil1.parallelized($shard_$__t8[$local_index], $shard_$__t15[$local_index], $__t7, $__t18, awaits($full_in_$shard_$__t15_<f>[$local_index]), arrives($empty_in_$shard_$__t15_<f>[$local_index]))
93,94c93,94
<       $empty_in_$shard_$__t11_<f> = advance($empty_in_$shard_$__t11_<f>)
<       $full_in_$shard_$__t11_<f> = advance($full_in_$shard_$__t11_<f>)
---
>       $empty_in_$shard_$__t15_<f> = advance($empty_in_$shard_$__t15_<f>)
>       $full_in_$shard_$__t15_<f> = advance($full_in_$shard_$__t15_<f>)
99,100c99,101
<       copy($shard_$__t8.f, $intersection_$shard_$__t8_$shard_$__t15.f, arrives($full_out_$shard_$__t15_<f>), awaits($empty_out_$shard_$__t15_<f>))
<       $empty_out_$shard_$__t15_<f> = advance($empty_out_$shard_$__t15_<f>)
---
>       copy($shard_$__t8.f, $intersection_$shard_$__t8_$shard_$__t11.f, arrives($full_out_$shard_$__t11_<f>), awaits($empty_out_$shard_$__t11_<f>))
>       $full_out_$shard_$__t11_<f> = advance($full_out_$shard_$__t11_<f>)
>       $empty_out_$shard_$__t11_<f> = advance($empty_out_$shard_$__t11_<f>)
103c104
<         stencil2.parallelized($shard_$__t8[$local_index], $shard_$__t15[$local_index], $__t7, $__t20, awaits($full_in_$shard_$__t15_<f>[$local_index]), arrives($empty_in_$shard_$__t15_<f>[$local_index]))
---
>         stencil2.parallelized($shard_$__t8[$local_index], $shard_$__t11[$local_index], $__t7, $__t20, awaits($full_in_$shard_$__t11_<f>[$local_index]), arrives($empty_in_$shard_$__t11_<f>[$local_index]))
105c106,107
<       $empty_in_$shard_$__t15_<f> = advance($empty_in_$shard_$__t15_<f>)
---
>       $empty_in_$shard_$__t11_<f> = advance($empty_in_$shard_$__t11_<f>)
>       copy($shard_$__t8.f, $intersection_$shard_$__t8_$shard_$__t15.f, arrives($full_out_$shard_$__t15_<f>), awaits($empty_out_$shard_$__t15_<f>))
107,108d108
<       copy($shard_$__t8.f, $intersection_$shard_$__t8_$shard_$__t11.f, arrives($full_out_$shard_$__t11_<f>), awaits($empty_out_$shard_$__t11_<f>))
<       $full_out_$shard_$__t11_<f> = advance($full_out_$shard_$__t11_<f>)
122c122
<     var $__t13 : rect3d = {(($__t8[$__t10].bounds.lo+{-1, 0, 0})%$__t7), (($__t8[$__t10].bounds.hi+{-1, 0, 0})%$__t7)}
---
>     var $__t13 : rect3d = {(($__t8[$__t10].bounds.lo+{1, 0, 0})%$__t7), (($__t8[$__t10].bounds.hi+{1, 0, 0})%$__t7)}
124c124
<     var $205 : rect3d = anon (/local/home/mebauer/legion_versioning/language/src/regent/parallelize_tasks.t:164)($primary_region.bounds, $197.bounds, $__t13, {-1, 0, 0})
---
>     var $205 : rect3d = anon (/local/home/mebauer/legion_versioning/language/src/regent/parallelize_tasks.t:164)($primary_region.bounds, $197.bounds, $__t13, {1, 0, 0})
131c131
<     var $__t17 : rect3d = {(($__t8[$__t14].bounds.lo+{1, 0, 0})%$__t7), (($__t8[$__t14].bounds.hi+{1, 0, 0})%$__t7)}
---
>     var $__t17 : rect3d = {(($__t8[$__t14].bounds.lo+{-1, 0, 0})%$__t7), (($__t8[$__t14].bounds.hi+{-1, 0, 0})%$__t7)}
133c133
<     var $215 : rect3d = anon (/local/home/mebauer/legion_versioning/language/src/regent/parallelize_tasks.t:164)($primary_region.bounds, $207.bounds, $__t17, {1, 0, 0})
---
>     var $215 : rect3d = anon (/local/home/mebauer/legion_versioning/language/src/regent/parallelize_tasks.t:164)($primary_region.bounds, $207.bounds, $__t17, {-1, 0, 0})
172c172
<       copy($parent_$shard_$__t11[$index].f, $__t11[$part_indices[$index]].f)
---
>       copy($parent_$shard_$__t15[$index].f, $__t15[$part_indices[$index]].f)
178c178
<       copy($parent_$shard_$__t15[$index].f, $__t15[$part_indices[$index]].f)
---
>       copy($parent_$shard_$__t11[$index].f, $__t11[$part_indices[$index]].f)

**Comment by elliottslaughter** [comment]
Yup, that's the problem. The parallelized code is still non-deterministic; it's just non-deterministic in the names of the variables. SPMD sorts the variable names lexicographically in order to ensure a consistent order. (There is no task on my end to use as a baseline, so if I didn't do this, I'd have non-determinism too.)

You don't need to make sure the names are identical, but you need to make sure they can be lexicographically sorted in a consistent way. Or else you can suggest to me a different way of ensuring that SPMD maintains consistency in this regard.

https://github.com/StanfordLegion/rdir/blob/master/plugin/src/regent/flow_outline_task.t#L141

**Comment by lightsighter** [comment]
I'm confused.  Did you make that change to fix the issue?  It doesn't look like it.  What is preventing the compiler from lexicographically sorting the variable names in a consistent way?  This seems like it should be a pretty straight-forward thing to do.

**Comment by elliottslaughter** [comment]
So you seem to have edited the code snippet, but my impression was that the variable names coming out of the parallelized code were themselves non-deterministic. Maybe I'm wrong about that? But if it's true, then there obviously won't be a way to sort them consistently.

**Comment by lightsighter** [comment]
I didn't edit the code snippet.  The variable names are deterministic.  It's their use that is non-deterministic.  In the cases that I see both nodes always use the same variable names, but sometimes they will swap which barrier is the arrive barrier and which ones i the wait barrier.  When that happens we get the deadlock.

**Comment by elliottslaughter** [comment]
Ok, I'll have to look at this more to see where the non-determinism is coming in.

**Comment by lightsighter** [comment]
Bug fixed with https://github.com/StanfordLegion/legion/commit/1d5319b67a3be7d8b4d298db418c84f74a1ef376
