### ISSUE TITLE
Realm naming/API tweaks

### ISSUE THREAD

**Issue by streichler** [StanfordLegion/legion#200]
It's funny how when you go to write down how to use something, you find all sorts of silly choices you made long ago and just learned to deal with instead of fixing them...

What follows is a list of changes I intend to make to various bits of the Realm public API in the next couple weeks.  Ideally all of them will continue to support the old name/interface so that no code will break immediately - I'll flag any known exceptions.

Please feel free to comment, argue that the new way is just as silly, and/or suggest additional things to clean up.  I'll edit the list as I write as well.
1. Processor kind names (`LOC_PROC` -> `HOST_PROC`, `TOC_PROC` -> `CUDA_PROC`)
2. Accessor creation: deprecate untyped, generic, full-structure `get_accessor` call and replace with:
   `RegionAccessor<AT, T> RegionInstance::get_field_accessor<T, AT=Generic>(off_t offset /* eventually field ID */);`
3. ~~Correct deferred instance creation returning an `Event`.~~
4. Reductions working properly with accessors.
5. Removal of payload associated with `Reservation`s.
6. Removal of `mode` from `Reservation::acquire` - there will just be exclusive and not (i.e. shared).
7. Deferred destruction of `Reservation`s.
8. Change machine query subscriptions to use task invocation for callbacks.
9. ~~Change `ProfilingResponse::get_measurement<T>` to avoid dynamic allocation.~~
10. Add `ReservationContention` profiling measurement.
11. ~~Add `InstanceStatus` profiling measurement.~~
12. Add `-realm:portable_fp` option.
13. Allow replacement of tasks in task registration.
14. Asynchronous `CodeTranslator::translate` interface.

**Comment by elliottslaughter** [comment]
Can we make field accessors work with reductions while we're at it?

**Comment by streichler** [comment]
> Can we make field accessors work with reductions while we're at it?

That'll probably want to happen as part of the index space changes with dependent partitioning, but I'll keep it on the list here so I don't forget.

**Comment by streichler** [comment]
Wow, kitchen-sink bugs really don't work.  In ~3 years, only 3 items actually got fixed.  The rest of these will be opened as individual issues to be tracked and then I'll close this as a "duplicate".

**Comment by streichler** [comment]
Ok, this issue has been exploded as follows:
#592 Processor kind names (LOC_PROC -> HOST_PROC, TOC_PROC -> CUDA_PROC)
#593 Accessor creation: deprecate untyped, generic, full-structure get_accessor call and replace with:
RegionAccessor<AT, T> RegionInstance::get_field_accessor<T, AT=Generic>(off_t offset /* eventually field ID */);
\+ Reductions working properly with accessors.
#594 Removal of payload associated with Reservations.
\+ Removal of mode from Reservation::acquire - there will just be exclusive and not (i.e. shared).
\+ Deferred destruction of Reservations.
#595 Change machine query subscriptions to use task invocation for callbacks.
#596 Add ReservationContention profiling measurement.
#597 Add -realm:portable_fp option.
#598 Allow replacement of tasks in task registration.
#599 Asynchronous CodeTranslator::translate interface.
