### ISSUE TITLE
Affine raw_rect_ptr failure with non-origin based rectangles

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#214]
Calls to the affine version of raw_rect_ptr can fail for rectangles which are non-origin based.  As example, consider the 2-D index space (1,0) - (1,1).  Calls to get a raw_rect_ptr for this instance will not return a pointer that can be indexed directly by points in the index space due to errors in pointer arithmetic inside of raw_rect_ptr.

**Comment by lightsighter** [comment]
I've added a macro to the SNAP mini-app that reproduces the issue.  Compile with -DLEGION_ISSUE_214_FIX to reproduce the problem.  The application will get undefined results because it is accessing invalid memory.

**Comment by streichler** [comment]
@lightsighter Can you re-test this on the deppart branch?  I would expect it to work properly there.

**Comment by lightsighter** [comment]
I see this error message when I try SNAP on the deppart branch with the assumed fix:

[0 - 12deca000] {6}{accessor}: lower bound of raw_rect_ptr request for [(0),(2147483647)] not contained in any piece of instance 6000000000000005: [<1>..<1>->affine(<8>+18446744073709551608)]
Assertion failed: (0), function raw_rect_ptr, file /Users/mebauer/legion/runtime//lowlevel.cc, line 1642.

Some of those numbers don't look right, but I know SNAP is passing the correct inputs in...

**Comment by streichler** [comment]
The deppart branch has a fix for this error (commit e9f0de6).  We've determined that SNAP prefers the relative addressing that comes from the three-argument version (i.e. where the desired rectangle actually is specified), so it's going to back out the LEGION_ISSUE_214_FIX changes at some point.

Master will not get a fix for this, as it will be superceded by deppart code shortly.
