### ISSUE TITLE
Duplicate Application of Reductions

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#215]
In some cases Legion will incorrectly issue duplicate reductions to certain points in an index space. This can occur for example if a set of reductions are applied to one partition of a logical region, and then another set of tasks read from a different aliased partition.  If some of the readers map to the same physical instance of the parent logical region, the result is that Legion will inadvertently apply duplicate reductions to the overlapping parts of the aliased subregions.

The attached Regent program will reproduce the bug.
[bug.zip](https://github.com/StanfordLegion/legion/files/694939/bug.zip)

**Comment by lightsighter** [comment]
I realized today that we've actually made some progress on this bug in the nopaint branch. We actually have the information to deduplicate the reductions from the same reduction instance to a specific target instance. The case that we have yet to handle however, is knowing the difference between the case where we did a write to update the instance first (potentially overwriting previous reductions) versus the case where we are doing reductions to a physical instance that already was valid. The first case requires no deduplication, whereas the second case does. We might be able to figure this out from the write masks that the nopaint branch tracks, but I need to dig in some more to figure it out.

**Comment by lightsighter** [comment]
This bug has been fixed in the nocomp branch and this issue can be closed once nocomp merges back into master.

**Comment by elliottslaughter** [comment]
Do we have test coverage to ensure that it stays fixed?

**Comment by lightsighter** [comment]
This test is now in the nopaint branch and has been passing for a long time. When nopaint merges into master we can close this issue.

**Comment by lightsighter** [comment]
The nopaint branch has merged into master and this example is now in the test suite so we know it won't break going forwards. Closing the issue.
