### ISSUE TITLE
Assertion `thread->scheduler != 0' failed

### ISSUE THREAD

**Issue by jiazhihao** [StanfordLegion/legion#219]
I got the following assertion failure in the dma branch. The bug can be reproduced as follows:
LAUNCHER='mpirun -H n0000,n0001 --bind-to none -x INCLUDE_PATH -x TERRA_PATH -x LD_LIBRARY_PATH -x CUDA_HOME' ./regent.py -mg tests/regent/run_pass/optimize_index_launch_num.rg

terra: /builds/StanfordLegion/legion/runtime/realm/threads.inl:236: static void Realm::Thread::wait_for_condition(const CONDTYPE&, bool&) [with CONDTYPE = Realm::EventTriggeredCondition]: Assertion `thread->scheduler != 0' failed. BACKTRACE (0, 7f3c4fc7f700) ---------- /builds/StanfordLegion/legion/bindings/terra/liblegion_terra.so : Realm::RuntimeImpl::realm_backtrace(int)+0x71 /lib/x86_64-linux-gnu/libc.so.6 : ()+0x36cb0 /lib/x86_64-linux-gnu/libc.so.6 : gsignal()+0x37 /lib/x86_64-linux-gnu/libc.so.6 : abort()+0x148 /lib/x86_64-linux-gnu/libc.so.6 : ()+0x2fbf6 /lib/x86_64-linux-gnu/libc.so.6 : ()+0x2fca2 /builds/StanfordLegion/legion/bindings/terra/liblegion_terra.so : void Realm::Thread::wait_for_condition<Realm::EventTriggeredCondition>(Realm::EventTriggeredCondition const&, bool&)+0x98 /builds/StanfordLegion/legion/bindings/terra/liblegion_terra.so : Realm::Event::wait_faultaware(bool&) const+0x192 /builds/StanfordLegion/legion/bindings/terra/liblegion_terra.so : Realm::Event::wait() const+0x26 /builds/StanfordLegion/legion/bindings/terra/liblegion_terra.so : Realm::StaticAccess<Realm::IndexSpaceImpl>::StaticAccess(Realm::IndexSpaceImpl*, bool)+0xbe /builds/StanfordLegion/legion/bindings/terra/liblegion_terra.so : Realm::IndexSpaceImpl::request_valid_mask()+0x27 /builds/StanfordLegion/legion/bindings/terra/liblegion_terra.so : Realm::IndexSpace::get_valid_mask() const+0x67 /builds/StanfordLegion/legion/bindings/terra/liblegion_terra.so : Realm::Domain::get_volume() const+0x51 /builds/StanfordLegion/legion/bindings/terra/liblegion_terra.so : void LegionRuntime::LowLevel::create_xfer_des<0u>(LegionRuntime::LowLevel::DmaRequest*, unsigned int, unsigned long long, unsigned long long, unsigned long long, bool, LegionRuntime::LowLevel::Buffer const&, LegionRuntime::LowLevel::Buffer const&, Realm::Domain const&, std::vector<LegionRuntime::LowLevel::OffsetsAndSize, std::allocator<LegionRuntime::LowLevel::OffsetsAndSize> > const&, unsigned long, long, int, LegionRuntime::LowLevel::XferOrder::Type, LegionRuntime::LowLevel::XferDes::XferKind, LegionRuntime::LowLevel::XferDesFence*, Realm::RegionInstance)+0xb0 /builds/StanfordLegion/legion/bindings/terra/liblegion_terra.so : LegionRuntime::LowLevel::XferDesCreateMessage::handle_request(LegionRuntime::LowLevel::XferDesCreateMessage::RequestArgs, void const*, unsigned long)+0x282 /builds/StanfordLegion/legion/bindings/terra/liblegion_terra.so : IncomingMediumMessage<LegionRuntime::LowLevel::XferDesCreateMessage::RequestArgs, 179, &LegionRuntime::LowLevel::XferDesCreateMessage::handle_request, 12>::run_handler()+0x6c /builds/StanfordLegion/legion/bindings/terra/liblegion_terra.so : IncomingMessageManager::handler_thread_loop()+0x6e /builds/StanfordLegion/legion/bindings/terra/liblegion_terra.so : void Realm::Thread::thread_entry_wrapper<IncomingMessageManager, &IncomingMessageManager::handler_thread_loop>(void*)+0x18 /builds/StanfordLegion/legion/bindings/terra/liblegion_terra.so : Realm::KernelThread::pthread_entry(void*)+0xde /lib/x86_64-linux-gnu/libpthread.so.0 : ()+0x8184 /lib/x86_64-linux-gnu/libc.so.6 : clone()+0x6d

**Comment by streichler** [comment]
@jiazhihao Yeah, you can't wait on an event in a runtime thread.  This is why the DMA code "prefetches" all the index spaces before performing the actual copy.  Is this happening on the source node for the copy, or on some intermediate node?

**Comment by jiazhihao** [comment]
It happens on some intermediate node, which performs a memcpy to the destination memory. The source node has all metadata but the destination node doesn't.

**Comment by streichler** [comment]
Ok - you'll need to either make sure that the intermediate/destination nodes have a chance to prefetch the metadata as well, or send it along with the request from the source node.

**Comment by jiazhihao** [comment]
Commit 3236ce in the dma branch should fix the issue --- the dma system will ask all intermediate/destination nodes to prefetch metadata for unstructured copies. @streichler can you review the commit and close the issue?

**Comment by elliottslaughter** [comment]
This appears to be fixed in master.
