### ISSUE TITLE
Slow copies with the new dma

### ISSUE THREAD

**Issue by magnatelee** [StanfordLegion/legion#231]
I've been seeing suspiciously slow copies with the new dma system in several apps I've been testing. Attached is the simplest app that exhibits such behavior:

[parallelize_tasks.rg.zip](https://github.com/StanfordLegion/legion/files/852776/parallelize_tasks.rg.zip)

You can run this code on sapling with the following command (a command for other systems will be similar):

LAUNCHER='mpirun -H n0000 -np 2 --map-by numa:pe=6 -x LD_LIBRARY_PATH -x TERRA_PATH -x INCLUDE_PATH' regent.py parallelize_tasks.rg -ll:cpu 4 -fparallelize-dop 2,4 -ll:csize 4096

Here are the Legion Prof traces from the old and new dma systems:

- old dma: http://legion.stanford.edu/~wclee/olddma
- new dma: http://legion.stanford.edu/~wclee/newdma

If you unfold the copy channels, you will find the copies in the second trace are noticeably bigger than those in the first one.

**Comment by magnatelee** [comment]
Here are another two Legion Prof traces from Soleil-X with particles:
- old dma: http://legion.stanford.edu/~wclee/sapling/soleil-particles/olddma/2node/
- new dma: http://legion.stanford.edu/~wclee/sapling/soleil-particles/newdma/2node/

**Comment by jiazhihao** [comment]
The commit c40ddd should improve the memcpy performance. I tried to rerun the parallel_task tests and all of the copies take less than 1ms.

**Comment by magnatelee** [comment]
@jiazhihao I don't think that commit improved the memcpy performance a lot. Your timeline has only two iterations that I think were simply lucky enough to avoid the issue. I re-run with the commit you mentioned and got this timeline where there are really bad copies at the six iteration (I recommend you run the code a little bit longer to reach a steady state):

http://legion.stanford.edu/~wclee/newdma_1node

Also, it's getting worse if I start running things on multiple nodes. Here are the traces from 2 nodes:

- new dma on 2 nodes: http://legion.stanford.edu/~wclee/newdma_2nodes
- old dma on 2 nodes: http://legion.stanford.edu/~wclee/olddma_2nodes

FYI, you can run the same program on multi-node by changing the value for -fparallelize-dop, which basically describes the number of subregions on x and y dimension. For example, this is the command to run on 2 nodes (changes are highlighted with bold face):

LAUNCHER='mpirun -H **n0000,n0001** -np **4** --map-by numa:pe=6 -x LD_LIBRARY_PATH -x TERRA_PATH -x INCLUDE_PATH' regent.py parallelize_tasks.rg -ll:cpu 4 -fparallelize-dop **4,4** -ll:csize 4096

**Comment by jiazhihao** [comment]
I think the commits f91ce & f4e0a should fix the performance issue. I have tested the executions with 1~4 nodes and all copies took reasonable times. 

@magnatelee as we discussed during the bootcamp, by default the dma system creates a single dma thread and pins one physical core for that dma thread. You can control the number of dma threads via ``-ll:dma'' flag. You can also unpin the dma threads by setting the ``-ll:unpin_dma'' flag.

**Comment by streichler** [comment]
@magnatelee How does this look with Zhihao's latest commits?

**Comment by magnatelee** [comment]
@streichler @jiazhihao The latest commits at least made the test case perform well, so I'll close this issue.
