### ISSUE TITLE
running cholesky in legion/language/examples

### ISSUE THREAD

**Issue by Rabab53** [StanfordLegion/legion#237]
Hello,

I am trying to complie cholesky from legion/language/examples, but I am getting this error, Could you please advice?

./regent.py examples/cholesky.rg 
In file included from <buffer>:1:
In file included from /home/runtime_systems/legion/runtime/legion/legion_c.h:31:
In file included from /home/runtime_systems/legion/runtime/legion/legion_config.h:21:
/usr/include/limits.h:123:16: fatal error: 'limits.h' file not found
# include_next <limits.h>
               ^
compilation of included c code failed

stack traceback:
	src/terralib.lua:3386: in function 'includecstring'
	...rm/runtime_systems/legion/language/src/regent/std_base.t:26: in main chunk
	[C]: in function 'require'
	...mairyrm/runtime_systems/legion/language/src/regent/std.t:18: in main chunk
	[C]: in function 'require'
	...rm/runtime_systems/legion/language/src/regent/builtins.t:17: in main chunk
	[C]: in function 'require'
	/home/runtime_systems/legion/language/src/regent.t:17: in main chunk
	[C]: at function: 0x413c1f10
	[C]: in function 'xpcall'
	src/terralib.lua:4220: in function <src/terralib.lua:4219>

**Comment by elliottslaughter** [comment]
Hi there,

Thanks for trying Regent!

This looks like Regent is having trouble finding some of the system header files, but it's a bit hard to tell without more information.

Could you please tell us:

  * What version of Legion you're on? (Which release, branch, and/or Git commit?)
  * What LLVM version?
  * What C compiler and version?
  * What OS and version?

Thanks.

**Comment by Rabab53** [comment]
Hi,

I really appreciate your quick reply. This is what I have 

What version of Legion you're on? (Which release, branch, and/or Git commit?) I am using the last release of it.
https://github.com/StanfordLegion/legion.git

What LLVM version? llvm-3.5

What C compiler and version?  gcc (Ubuntu 4.8.5-2ubuntu1~14.04.1) 4.8.5

What OS and version? 3.13.0-46-generic GNU/Linux

**Comment by elliottslaughter** [comment]
A couple of follow-up questions:

Can you show me the value of `git branch` on the Legion repo? I'm guessing you're on the `stable` branch (this is the default) but I just want to be sure.

Can you show me the contents of `/etc/lsb-release`?

There may be issues if you're on Ubuntu 16.04. (Unfortunately I don't remember exactly what this looks like.) However, if you're on 14.04 I'm surprised that this wouldn't just work out of the box. We've been using 14.04 quite extensively.

Thanks.

**Comment by Rabab53** [comment]
Hello,

Thank you for help
>>Can you show me the value of git branch on the Legion repo? I'm guessing you're on the stable branch (this is the default) but I just want to be sure.
* stable

>>Can you show me the contents of /etc/lsb-release?

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"

Thanks

**Comment by Rabab53** [comment]
Any help?

**Comment by streichler** [comment]
@Rabab53 I think this may be related to the way that terra's build scripts do include path detection.
If you do:
```
cd language/terra
make test
```
are most/all tests passing?  (I have two failing in a recent-ish tree, but if terra is having trouble with external compilation, I bet a lot more will fail.)

**Comment by Rabab53** [comment]
By installing terra manually, the problem is fixed.

Thank you for such help.
