### ISSUE TITLE
Hang with commit 5753ae2

### ISSUE THREAD

**Issue by magnatelee** [StanfordLegion/legion#241]
The runtime hangs for optimize_spmd10.rg (https://gitlab.com/StanfordLegion/legion/builds/15037861) and I found the commit 5753ae2 is causing this hang. I confirmed that the hang goes away if I revert the commit. Here is the command to reproduce the bug on sapling:

LAUNCHER='mpirun -H n0000,n0001 --bind-to none -x INCLUDE_PATH -x LD_LIBRARY_PATH -x TERRA_PATH' regent.py tests/regent/run_pass/optimize_spmd10.rg -ll:cpu 2

**Comment by elliottslaughter** [comment]
It's worth noting that this reproduces without RDIR. (Test with `-fflow 0` at the end of that command line.)

**Comment by lightsighter** [comment]
This issue should be fixed by db83657.  Assigning back to @magnatelee to confirm.

**Comment by magnatelee** [comment]
The issue has been fixed, so closing it.
