### ISSUE TITLE
Indirect Copies

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#242]
Provide support for indirect copies that will translate a point in one index space through a field to another point as part of performing a copy operation.  This will require work to modify Legion, Realm, and the DMA system.

**Comment by streichler** [comment]
Adding @elliottslaughter to this discussion - have we scoped out what is needed on the Regent side for scatter/gather copies?

**Comment by lightsighter** [comment]
Are we going to include the affine indirection as part of this issue or make it into a separate issue? I'm fine including it on this issue. It's a pretty minimal amount of work for me to pipe through the affine mapping to realm for the indirection. It's more a matter of whether we want to implement that in Realm for this milestone or move it to a later one.

**Comment by streichler** [comment]
Affine/structured isn't ready on the Realm side, so I think we'll split that out into a separate issue.  However, it would be really nice to get Regent support in for the unstructured stuff.  @elliottslaughter , any chance of that in the next couple weeks?

**Comment by lightsighter** [comment]
Ok, I asked because @elliottslaughter has another use case for affine in addition to the Legate one that I have.

**Comment by elliottslaughter** [comment]
Let's split Regent support into a separate issue.

**Comment by streichler** [comment]
Legion and Realm support for unstructured scatter and/or gather is just about done.  Remaining work has been carved off into two separate issues:
#705 - structured (~affine) scatter/gather in Legion and Realm
#704 - Regent language support

**Comment by streichler** [comment]
Unstructured scatter/gather has been merged in with commit d9d370e.
