### ISSUE TITLE
Option to specify HDF5 library path as an environment variable

### ISSUE THREAD

**Issue by akshaysubr** [StanfordLegion/legion#249]
Would it be possible to add support for a custom HDF5 library path through an environment variable say `HDF_ROOT`?

Right now, I do this by manually changing the HDF5 related lines in `runtime/runtime.mk` (https://github.com/StanfordLegion/legion/blob/stable/runtime/runtime.mk#L289-L295) to 
```
# Realm doesn't use HDF by default
USE_HDF ?= 0
HDF_LIBNAME ?= hdf5
ifeq ($(strip $(USE_HDF)), 1)
  CC_FLAGS      += -DUSE_HDF
  LEGION_LD_FLAGS      += -l$(HDF_LIBNAME)
  ifdef HDF_ROOT
       CC_FLAGS    += -I$(HDF_ROOT)/include
       LD_FLAGS    += -L$(HDF_ROOT)/lib
  else
    CC_FLAGS      += -I/usr/include/hdf5/serial
  endif
endif
```
similar to a fix in one of the other branches.

Don't know if this would break anything else, but such an option would be very useful and would not require me changing these lines after every pull.

**Comment by elliottslaughter** [comment]
This seems completely reasonable to me. Would be happy to accept a pull request if you have time.
