### ISSUE TITLE
CMake: detect when GASNet is built with MPI interop

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#251]
Right now, if you use CMake to build Legion using a GASNet configured with MPI interop, you also need to link applications with MPI even if the applications themselves don't use it. Right now, we only add MPI link flags on the MPI conduit itself. We need to either:

 1. Detect when GASNet is built with MPI interop, so we can add the right link flags.
 2. Just add the link flags unconditionally.

Currently we do this for the MPI conduit only: https://github.com/StanfordLegion/legion/blob/stable/cmake/FindGASNet.cmake#L160

While the test suite is ok because it uses the MPI conduit, our manual builds we nearly always configure GASNet to use MPI interop because it allows us to launch Legion apps with `mpirun`, so this means the actual GASNet configurations we use in practice fail out of the box.

Would appreciate feedback from @junghans @chuckatkins @streichler on the best way to fix this.

Here is a sample failing build. This is using GASNet's IBV conduit with `--enable-mpi-compat`.

```
$ cmake .. -DLegion_BUILD_EXAMPLES=ON -DLegion_USE_GASNet=ON
...
-- Found GASNet: /usr/local/gasnet-1.22.4-openmpi/include
-- Found GASNet Conduits: ibv;smp
-- Found GASNet Threading models: parsync;par;seq
-- GASNet: Using ibv-par
...
-- Found MPI_C: /usr/local/openmpi-1.8.2/lib/libmpi.so
-- Found MPI_CXX: /usr/local/openmpi-1.8.2/lib/libmpi_cxx.so;/usr/local/openmpi-1.8.2/lib/libmpi.so
...

$ make
Linking CXX executable ../../bin/attach_file
/usr/local/gasnet-1.22.4-openmpi/lib/libgasnet-ibv-par.a(gasnet_bootstrap_mpi-PAR.o): In function `gasneti_bootstrapInit_mpi':
...
gasnet_bootstrap_mpi.c:(.text+0x2cf): undefined reference to `MPI_Initialized'
gasnet_bootstrap_mpi.c:(.text+0x2ff): undefined reference to `MPI_Init'
...
```

**Comment by junghans** [comment]
If only gasnet would support (shared libraries)[https://bitbucket.org/berkeleylab/gasnet/pull-requests/36], its dependency would be linked in automatically. 

Anyhow, isn't https://github.com/StanfordLegion/legion/blob/stable/cmake/FindGASNet.cmake#L177 suppose to link in all of Gasnet's dependencies? But if I recall correctly `libmpi` isn't listed in `LIBS` and hence we had to do some trickery (see #205, #206 for details). I guess, we could do something like:
```cmake
if(_GASNet_LD MATCHES "(^|.*/)mpi.*" AND NOT (_GASNet_LD STREQUAL CMAKE_C_COMPILER))
    set(MPI_C_COMPILER ${_GASNet_LD})
    find_package(MPI REQUIRED COMPONENTS C)
    list(APPEND COMPONENT_DEPS ${MPI_C_LIBRARIES})
  endif()
```
which would help for all conduits.

**Comment by elliottslaughter** [comment]
I've confirmed that would fix my build issue. If you're happy with that solution, I can push the change.

**Comment by elliottslaughter** [comment]
Workaround is in pull request #252.

**Comment by elliottslaughter** [comment]
I'm going with the workaround for now. If someone finds a better solution in the future then we can revisit.
