### ISSUE TITLE
named tasks are being called "unnamed_task" running multi-node on sapling

### ISSUE THREAD

**Issue by aheirich** [StanfordLegion/legion#253]
Here is output from examples/visualization/prototype1
All of the tasks have had names assigned to them via runtime->attach_name
running on a single node, all the tasks are named in the output
running on multiple nodes, some of the tasks are called "unnamed_task"
displayed result is returned from task->get_task_name()

---> Linking objects into one binary: prototype1
mpicxx -o prototype1 prototype1.o   -L. -llegion -lrealm -lrt -lpthread -ldl -rdynamic -L/usr/local/gasnet-1.28.
0-openmpi/lib -lrt -lm -lgasnet-ibv-par -libverbs -L/lib -lmpi 
=== RUNNING WITH NUM_FRAGMENTS_PER_LAYER=1 ===
render_task 812 (0,0,0): 0.029314 sec 29314.092000 usec = 29314.092000 usec * 1 sample
unnamed_task_1 7 (0,0,3): 0.024594 sec 24593.815000 usec = 24593.815000 usec * 1 sample
render_task 5 (0,0,1): 0.027385 sec 27384.716000 usec = 27384.716000 usec * 1 sample
unnamed_task_1 6 (0,0,2): 0.028069 sec 28069.226000 usec = 28069.226000 usec * 1 sample
composite leaf task 16 (0,0,0) leaf: 0.001281 sec 1281.116000 usec = 1281.116000 usec * 1 sample
composite leaf task 104 (0,0,0) leaf: 0.002949 sec 2949.281000 usec = 2949.281000 usec * 1 sample
composite leaf task 48 (0,0,0) leaf: 0.001515 sec 1514.857000 usec = 1514.857000 usec * 1 sample
composite leaf task 68 (0,0,0) leaf: 0.002041 sec 2041.039000 usec = 2041.039000 usec * 1 sample
composite leaf task 32 (0,0,0) leaf: 0.001531 sec 1531.147000 usec = 1531.147000 usec * 1 sample
composite leaf task 13 (0,0,0) leaf: 0.003531 sec 3530.877000 usec = 3530.877000 usec * 1 sample
composite leaf task 88 (0,0,0) leaf: 0.003356 sec 3355.815000 usec = 3355.815000 usec * 1 sample
unnamed_task_1048573 30 (0,0,0) leaf: 0.005163 sec 5162.751000 usec = 5162.751000 usec * 1 sample
composite leaf task 204 (0,0,0) leaf: 0.001568 sec 1567.514000 usec = 1567.514000 usec * 1 sample
unnamed_task_1048573 18 (0,0,0) leaf: 0.001836 sec 1835.584000 usec = 1835.584000 usec * 1 sample
composite leaf task 120 (0,0,0) leaf: 0.003924 sec 3923.716000 usec = 3923.716000 usec * 1 sample
composite leaf task 17 (0,0,0) leaf: 0.004609 sec 4609.004000 usec = 4609.004000 usec * 1 sample
composite leaf task 136 (0,0,0) leaf: 0.002732 sec 2732.143000 usec = 2732.143000 usec * 1 sample
unnamed_task_1048573 34 (0,0,0) leaf: 0.005674 sec 5674.480000 usec = 5674.480000 usec * 1 sample
composite leaf task 160 (0,0,0) leaf: 0.001674 sec 1673.945000 usec = 1673.945000 usec * 1 sample
composite leaf task 21 (0,0,0) leaf: 0.004353 sec 4352.782000 usec = 4352.782000 usec * 1 sample
unnamed_task_1048573 14 (0,0,0) leaf: 0.001607 sec 1607.170000 usec = 1607.170000 usec * 1 sample

**Comment by lightsighter** [comment]
Where is the code for this?  I don't see any composite leaf tasks in examples/visualization/prototype1.cc in the visualization branch.

**Comment by lightsighter** [comment]
@aheirich See if the commit above makes things any better.

**Comment by elliottslaughter** [comment]
That commit is causing all the multi-node tests to freeze; we'd better roll it back.

**Comment by lightsighter** [comment]
@elliottslaughter Can you give me an example test that freezes?

**Comment by elliottslaughter** [comment]
`examples/dynamic_registration` is one:

```
mpirun -n 2 ./dynamic_registration
```

**Comment by lightsighter** [comment]
@elliottslaughter All the hangs should be gone.

**Comment by magnatelee** [comment]
@lightsighter the change you made today seems to make apps crash when legion prof is enabled. The easiest way to reproduce the crash is running this command: `regent.py examples/circuit.rg -hl:prof 1`.

**Comment by aheirich** [comment]
sorry I didn't notice this thread
examples/visualization/prototype1 was still showing the behavior yesterday when I ran on sapling with 4 nodes
I made changes to the code today that affect how the tasks are registered so that may change things

**Comment by lightsighter** [comment]
@magnatelee The issue should be resolved with b9a201d

@aheirich Can you give me a command line to reproduce the issue?

**Comment by aheirich** [comment]
@lightsighter to reproduce, go to branch visualization at this commit

commit 008f46a9c441288b0a69529535ef4f34c3e0fe61
Merge: 7d9416c a71591e
Author: Alan Heirich <aheirich@sapling.stanford.edu>
Date:   Thu May 18 16:51:51 2017 -0700

    Merge branch 'visualization' of https://github.com/StanfordLegion/legion into visualization

on Sapling cd to legion/examples/visualization/viz_perf and issue this command
./RUN_ONE.bash NUM_FRAGMENTS_PER_LAYER=8

when I do this I see a lot of "unnamed task" in the output like this

compositeInternalTask 2956 (0,0,0) internal: 0.010021 sec 10020.763000 usec = 10020.763000 usec * 1 sample
unnamed_task_1048584 387 (0,0,0) internal: 0.015555 sec 15554.980000 usec = 15554.980000 usec * 1 sample
unnamed_task_1048584 386 (0,0,0) internal: 0.010981 sec 10980.826000 usec = 10980.826000 usec * 1 sample
unnamed_task_1048584 389 (0,0,0) internal: 0.012964 sec 12963.954000 usec = 12963.954000 usec * 1 sample
unnamed_task_1048584 390 (0,0,0) internal: 0.011709 sec 11708.534000 usec = 11708.534000 usec * 1 sample
unnamed_task_1048584 385 (0,0,0) internal: 0.010749 sec 10749.141000 usec = 10749.141000 usec * 1 sample

**Comment by lightsighter** [comment]
@aheirich Same problem here with the other issue: you need the visualization branch to be upstream of master and not of the stable branch to see any changes that I push.  All my earlier fixes are in the master branch, but not yet the stable branch.  Please merge the master branch into visualization such that you see the most recent version of the runtime.

**Comment by lightsighter** [comment]
@aheirich Can you restore this application to a point where I can run this test again?

**Comment by streichler** [comment]
@aheirich Please update this bug with current repro instructions or close it out if it's been fixed.  Thanks!

**Comment by aheirich** [comment]
problem appears to be solved, closing
