### ISSUE TITLE
register_region_function() compilation failure

### ISSUE THREAD

**Issue by krivenko** [StanfordLegion/legion#266]
Dear Legion developers,

I am trying to register a region projection function like this
```c++
LogicalRegion causal_region_proj(LogicalRegion lr, const DomainPoint &pt, Runtime * runtime) {
  /// ...
}

HighLevelRuntime::register_region_function<causal_region_proj>(CAUSAL_PROJECTION_ID);
```
The compilation fails with the following error message,
```
/usr/include/legion/legion.inl:1964:46: error: invalid new-expression of abstract class type ‘Legion::Internal::RegionProjectionWrapper<causal_region_proj>’
       Runtime::preregister_projection_functor(handle,
                                              ^
/usr/include/legion/legion.inl:1932:13: note:   because the following virtual functions are pure within ‘Legion::Internal::RegionProjectionWrapper<causal_region_proj>’:
       class RegionProjectionWrapper : public ProjectionFunctor {
/usr/include/legion/legion.h:2583:24: note:     virtual unsigned int Legion::ProjectionFunctor::get_depth() const
       virtual unsigned get_depth(void) const = 0;
```

The problem is likely to be caused by https://github.com/StanfordLegion/legion/commit/745aebab01a79676e462e119d25fb24631784002.

Is `register_region_function()` considered deprecated at this point? Should I use `register_projection_functor()` instead?

Regards,
Igor

**Comment by lightsighter** [comment]
Yes, you do need to provide an implementation of the get_depth method now for all projection functors as the runtime will use it as part of its analysis.  If you're unsure how to figure out the depth of your projection function from the documentation you can post the code here for you projection function and we'll help you figure it out.

**Comment by krivenko** [comment]
>  If you're unsure how to figure out the depth of your projection function from the documentation you can post the code here for you projection function and we'll help you figure it out.

Thank you, I think I have figure out how to define `get_depth()`, it must return 0 in my case.

Still, it would be good to mention somewhere in the docs that `register_region_function()` is deprecated. Or should I say 'removed'?

**Comment by lightsighter** [comment]
Ah yes, good catch.  I will add the `LEGION_DEPRECATED` annotation, which currently will only show up with a compiler warning if you build with c++14, but will still make it clear that we're moving in the direction of using projection functors.

**Comment by lightsighter** [comment]
I added the missing deprecated annotations with 3ed1eec.  Closing this issue.
