### ISSUE TITLE
Construction of sparse domains

### ISSUE THREAD

**Issue by krivenko** [StanfordLegion/legion#269]
In the tutorial 'Index Space Tasks' I read the following:

`Rect` objects can be converted to `Domain` objects. `Domain` objects are a more general type for representing sets of points regardless of whether the sets are sparse or dense and independent of the number of dimensions.

So how do I construct a sparse `Domain`?
Let's say I have an index partition `ip` derived from a sparse coloring with one color 0.
```c++
IndexSpace is = runtime->get_index_subspace(ctx, ip, 0);
Domain d = runtime->get_index_space_domain(ctx, is);
```
Is `d` supposed to be a sparse `Domain`?
In my case `d.get_dim()` returns 2, so I guess `d` is not sparse.

In case it is actually possible to construct sparse domains, can I use them to launch index space tasks?

**Comment by krivenko** [comment]
I have been trying to do the following
```c++
int N = 10;
int dim0[] = {0, 0};
int dim1[] = {N - 1, N - 1};
Rect<2> full_rect(dim0, dim1);

// Initial index space is an NxN square
IndexSpace is = runtime->create_index_space(ctx, Domain::from_rect<2>(full_rect));

// Partition 'is' into upper and lower triangles
// The main diagonal is in the upper part
enum {Lower, Upper};

// Use a coloring made of 1x1 domains
IndexPartition ip;
{
    Domain colors = Domain::from_rect<1>(Rect<1>(Lower, Upper));
    MultiDomainColoring coloring;
    for(int i = 0; i < N; ++i) {
        for(int j = 0; j < N; ++j) {
            int p[] = {i, j};
            coloring[(i > j ? Lower : Upper)].insert(Domain::from_point<2>(p));
        }
    }
    ip = runtime->create_index_partition(*ctx_ptr, is, colors, coloring, true);
}
IndexSpace is_upper = runtime->get_index_subspace(ip, Upper);
Domain d_upper = runtime->get_index_space_domain(ctx, is_upper);

for(Domain::DomainPointIterator it(d_upper); it; it++) {
    std::cout << it.p << std::endl;
}
```
This prints all 100 2-d points instead of 55 in the upper triangle.

**Comment by lightsighter** [comment]
So there are actually two answers to this problem.  Currently, if you would like to make a top-level index space that is sparse, the best way to do this is to make an index space that consists of multiple domains that describe the set of rectangles for your index space:
https://github.com/StanfordLegion/legion/blob/master/runtime/legion/legion.h#L2641-L2648

In immediately pending future (the next month or so), we're going to merge the deppart branch into the master branch and a lot of the interface for how index spaces will be made will change.  We'll provide backwards compatibility with the existing interface, so you won't need to worry about your code breaking. 

I'm actually surprised that this prints out the points of the upper triangle properly.  If you use the multi-domain coloring to create the partition, then I think you'll need to get all the domains for the upper sub-region using this call:
https://github.com/StanfordLegion/legion/blob/master/runtime/legion/legion.h#L3338-L3351

Obviously describing triangles with rectangles is hard.  I actually think it would be better if you can describe the triangles with as few large rectangles as possible.  Right now it is yours (the users) responsibility to do this.  I think that once we merge the dependent partitioning branch in a few weeks, you'll be able to do a partition by field, and we'll automatically aggregate the points from each of the triangles into as few of rectangles as possible for you.  @streichler can say if I'm making things up or not. :)

**Comment by krivenko** [comment]
Thank you for the answer, Mike.
Unfortunately, it leaves me with even more questions than I had before...

>  Currently, if you would like to make a top-level index space that is sparse, the best way to do this is to make an index space that consists of multiple domains that describe the set of rectangles for your index space:
https://github.com/StanfordLegion/legion/blob/master/runtime/legion/legion.h#L2641-L2648

Okay, that function allows me to construct a top-level index space made of a number of rectangular domains. But my question was about a sparse **domain**, rather than about a sparse **index space**. I emphasize the difference because constructor of `IndexTaskLauncher`, which I want to use, takes a `Domain` object as an argument (see my second question).

> I'm actually surprised that this prints out the points of the upper triangle properly.

Sorry, I must have been unclear. It does **not** print out the upper triangle, which is the very point of my problem. I cannot use `get_index_space_domains()` as it returns a vector of domains, and I need a single sparse domain to pass it to  `IndexTaskLauncher`.

> If you use the multi-domain coloring to create the partition, then I think you'll need to get all the domains for the upper sub-region using this call:
https://github.com/StanfordLegion/legion/blob/master/runtime/legion/legion.h#L3338-L3351

How would you create that partition to make sure that only 55 point from the upper triangle are printed out? 

From what you are saying, I get an impression that sparse (non-rectangular) domains, while being advertised in the tutorial, are actually not a thing. Sparse index spaces made of a set of rectangular domains do exists, but they are not what I need...

> Obviously describing triangles with rectangles is hard. I actually think it would be better if you can describe the triangles with as few large rectangles as possible.

This sounds reasonable but irrelevant to my ultimate goal. I used those triangles as an example but eventually I want to partition my square into diagonals, and construct `IndexTaskLauncher` for each diagonal.

**Comment by krivenko** [comment]
I think I have found a way to achieve my goal. One has to use a `Coloring` object and an unstructured top-level index space.
```c++
int N = 10;

// Initial index space is an NxN square
IndexSpace is = runtime->create_index_space(ctx, N*N);
{
    IndexAllocator allocator = runtime->create_index_allocator(ctx, is);
    allocator.alloc(N*N);
}

// Partition 'is' into upper and lower triangles
// The main diagonal is in the upper part
enum {Lower, Upper};

// Use IndexIterator and a Coloring object
IndexPartition ip;
{
    Coloring coloring;

    IndexIterator itr(runtime, ctx, is);
    for(int i = 0; i < N; ++i) {
        for(int j = 0; j < N; ++j) {
            assert(itr.has_next());
            coloring[(i > j ? Lower : Upper)].points.insert(itr.next());
        }
    }
    ip = runtime->create_index_partition(ctx, is, coloring, true);
}
IndexSpace is_upper = runtime->get_index_subspace(ip, Upper);
Domain d_upper = runtime->get_index_space_domain(ctx, is_upper);

for(Domain::DomainPointIterator it(d_upper); it; it++) {
    std::cout << it.p << std::endl;
}
```

Could you please confirm this is actually the proper way to partition?

**Comment by lightsighter** [comment]
Yes, I think this is probably the best way for you to go currently.  Unstructured index spaces will definitely be able to handle your case.

For future reference this distinction between "structured" and "unstructured" index spaces will soon disappear when we merge the dependent partitioning branch.  Your code though will still work and be backwards compatible.

@streichler and I also discussed today ways to handle triangular shaped index spaces better going forward and we have some ideas that we'll need to work through.  Certainly triangular matrices play in important part in solvers and other similar codes so we'll want to have a better story for them going forward than what you're currently doing, but for now what you're doing should be fine.

Let's leave this issue open and you can continue post any future problems that you have here.

**Comment by krivenko** [comment]
> For future reference this distinction between "structured" and "unstructured" index spaces will soon disappear when we merge the dependent partitioning branch. Your code though will still work and be backwards compatible.

This is interesting. Where can I read about this upcoming feature? My Legion-based code is at a very early stage of development, so for me it's not too late to make design decisions.

**Comment by lightsighter** [comment]
Here's two useful resources.  First I would recommend taking a look at this paper on dependent partitioning as it explains the important concepts:
http://legion.stanford.edu/pdfs/dpl2016.pdf

Then I would take a look at the extended partitioning interface in the 'deppart' branch.  
https://github.com/StanfordLegion/legion/blob/deppart/runtime/legion/legion.h#L3221-L3741

When you have questions please go ahead and ask them. :)

**Comment by streichler** [comment]
@krivenko We're getting pretty close to merging the deppart branch back into master, so if you happen to have any feedback related to deppart, now would be a really good time.  :)

**Comment by streichler** [comment]
@krivenko I'm going to go ahead and close this issue, but please feel free to pester us with any questions/comments/concerns you still have.  Thanks!
