### ISSUE TITLE
documentation: memory requirements for legion under vm

### ISSUE THREAD

**Issue by aheirich** [StanfordLegion/legion#276]
recently we found that soleil-x could not complete compilation running on Ubuntu 16.10 under VMWare Fusion with the default memory settings of 1GB.  The result was a silent crash of the compiler.  The problem was fixed by raising the memory of the VM to 3 GB.

It seems that it would be nice to warn about this somewhere in the regent documentation, maybe the notes section of here https://github.com/StanfordLegion/legion/blob/master/language/README.md

**Comment by elliottslaughter** [comment]
I feel like this should go into the README of Soleil-X (https://github.com/stanfordhpccenter/soleil-x) since the memory requirements are going to be application-specific. Just like how GCC or Clang might require different amounts of memory for different files---I would expect those requirements to be documented under the specific project, not GCC or Clang.

@magnatelee Weren't you going to update the Soleil-X instructions?

**Comment by aheirich** [comment]
For me the issue is that Regent will die silently if you run out of memory.  And the memory defaults on VMWare Fusion is unreasonably small.  If you want to use Regent safely under a VM be sure to increase the memory above the default amount.



On Jun 29, 2017, at 9:51 AM, Elliott Slaughter <notifications@github.com<mailto:notifications@github.com>> wrote:


I feel like this should go into the README of Soleil-X (https://github.com/stanfordhpccenter/soleil-x) since the memory requirements are going to be application-specific. Just like how GCC or Clang might require different amounts of memory for different files---I would expect those requirements to be documented under the specific project, not GCC or Clang.

@magnatelee<https://github.com/magnatelee> Weren't you going to update the Soleil-X instructions?

**Comment by streichler** [comment]
@elliottslaughter @magnatelee Do we understand why Regent dies without printing "out of memory" or the like?

**Comment by elliottslaughter** [comment]
@streichler No, it doesn't make any sense to me. I also don't currently have VMWare Fusion installed, so don't have a great way to reproduce. If it reproduces in VirtualBox maybe we could take a look.

**Comment by elliottslaughter** [comment]
@aheirich Assuming this is still an issue, would it be possible to get concrete repro steps (ideally with confirmation that the bug does still reproduce)? At the moment there isn't any way for anyone else to even look at the issue.

**Comment by aheirich** [comment]
repro steps:
install vmware fusion with default settings on Mac OS X
install legion, soleil-x
try to compile soleil-x

what I expect you will see:
the compilation exits silently after several minutes without completing.  The reason is out-of-memory.

**Comment by streichler** [comment]
It might be worth trying to trigger it by messing with `ulimit -v` for less complicated regent programs.

**Comment by elliottslaughter** [comment]
@aheirich Is this still an issue?

**Comment by aheirich** [comment]
closing

**Comment by aheirich** [comment]
I don’t think this is an important issue.  I will close it.


On Sep 13, 2019, at 1:29 PM, Elliott Slaughter <notifications@github.com<mailto:notifications@github.com>> wrote:


@aheirich<https://github.com/aheirich> Is this still an issue?
