### ISSUE TITLE
HDF5 instances broken in deppart

### ISSUE THREAD

**Issue by streichler** [StanfordLegion/legion#277]
CI testing of HDF5 cases has (hopefully) been disabled for (hopefully) just deppart in d61813e.

**Comment by lightsighter** [comment]
@streichler I'm also disabling the realm_saxpy example since it is also broken in deppart

**Comment by lightsighter** [comment]
To undo the changes, you should just have to uncomment these lines:
https://github.com/StanfordLegion/legion/blob/deppart/test.py#L54
https://github.com/StanfordLegion/legion/blob/deppart/examples/CMakeLists.txt#L28-L29

**Comment by lightsighter** [comment]
I had to disable the attach_file_mini test too because it dies on instances.inl:153. When it's fixed we should revert e7229f6

**Comment by streichler** [comment]
All three of these issues are fixed in deppart.
