### ISSUE TITLE
Legion documentation for GASNet

### ISSUE THREAD

**Issue by bonachea** [StanfordLegion/legion#281]
As requested in today's meeting, below is my list of comments/suggestions for updating the Legion GASNet page at http://legion.stanford.edu/gasnet/

This is a cut-and-paste of the email thread from March 30, 2017.

Let me know if I can offer any further clarification on any points.

Hope this helps..
-D

---------------------------------------------------------------------------------
*** Sec: Building GASNet

* Para 1: "BE SURE THE CONFIGURE SCRIPT BUILDS THE CORRECT CONDUIT." - Suggest adding some text like "The GASNet configure script finishes by printing a summary of detected conduits that will be built."

* Para 2: Suggest adding a note like "The full list of configure arguments can be seen with `configure --help`"

* Para 2: On the configure args described:

--enable-par : this is enabled by default whenever pthreads are detected (all modern systems), so there's really no reason to ever specify it explicitly

--enable-segment-fast : this is the default, no reason to ever specify it explicitly

"--with-segment-mmap-max=<#>GB ... Default is 1MB"
The default is actually 2GB, and there's rarely any direct motivation to change this aside from wanting to allow for a larger FAST segment by default (and the environment variable can override this default at runtime).

"... which results in GASNet start-up times of several MINUTES with large (e.g. 48 GB) address spaces."
The startup-time issue is specific to ibv-conduit (which defaults to attempting to pin up to 2/3 or physical memory), and setting a low --with-segment-mmap-max actually no longer affects the behavior of that probe (if it ever did). All it does is artificially limit the segment size of all conduits (and that truncation happens AFTER the expensive probe in the case of ibv-conduit). The appropriate workaround for the ibv-specific startup issue is to set GASNET_PHYSMEM_MAX (and possibly GASNET_PHYSMEM_PROBE) in the environment at job run time (see ibv-conduit/README for details). There is not currently a configure-time mechanism to tune the default values for those settings, but we may look into adding one since that seems valuable (UPDATE: GASNet 1.30.0 is expected to contain a configure-time mechanism for tuning this)

--enable-cross-compile: this is a "semi-documented" flag which is automatically added by all the cross-configure scripts. There's no reason for a user to ever type this (especially since cross-compilation won't work without all the other settings provided by the cross-configure script).

*** Sec: Configuring GASNet for Performance

* On the Keeneland example configure command:
--enable-segment-fast : this is the default, so has no effect
--enable-par --enable-pthreads : this is probed and enabled by default, so this "force" option has no effect unless pthreads are broken on this system (in which case it errors out, a useful behavior but probably irrelevant in this context)
--disable-portals : this conduit no longer exists, unless perhaps you meant to type --disable-portals4 (although those drivers are unlikely to be in your environment)
--with-segment-mmap-max=4GB : see above
--disable-pshm : The performance cost for PSHM support is actually very small (especially when not used at runtime). Conversely, the performance cost to running more than process per node without PSHM support is very significant, and that's the likely mode of operation in hybrid MPI apps. So I'd advocate removing --disable-pshm as a general recommendation (in which case you can also remove --disable-aligned-segments, which is implied in all current conduits by the default --enable-pshm).
Text below referring to these options should probably also be deleted.

* "We instruct GASNet that it should pin 4 GB of memory on each node to be used for its fast active message segment using the --enable-segment-fast --with-segment-mmap-max=4GB flags." - the phrase "fast active message segment" is misleading, it's just the "GASNet memory segment" (ie used by all GASNet ops, not just AM).

* "The --disable-pshm and --disable-fca flags disable shared memory and fast atomic operations which are unnecessary for Legion and can sometimes degrade performance."
--disable-fca has nothing to do with atomics - it controls support for using Fabric Collective Accelerator drivers from Mellanox. These drivers are unlikely to be installed on your system (in which case it's automatically disabled), but even if support is detected it should not degrade general performance (unless the drivers are broken, I guess). So that argument can probably be removed as well.

* On the Titan example configure command:
"cross-configure-crayxe-linux" has been renamed in the latest GASNet release to "cross-configure-cray-gemini-{alps,slurm}"
--enable-gemini : Automatically added by the cross-configure script, so this is arg redundant and has no effect
--disable-portals --enable-par --enable-pthreads : See above
--with-target-cxx : GASNet does not use CXX anywhere except udp-conduit, which the script disables for this platform - so this argument has no effect. On the related body text it would probably be better to say something like "The cross-configure script is human-readable and can easily be edited to change things like the location of the compute node C compiler if it's not in a standard location".
Other text below referring to these options should also be updated.

* If we are looking to show examples for some other configure options that users might want situationally, here's a few of the more interesting ones cut-and-paste from the GASNet/README:

  For example to build 32-bit code when your gcc and g++ default to 64-bit:
    configure CC='gcc -m32' CXX='g++ -m32' MPI_CC='mpicc -m32'
  or similarly, if you want libgasnet to contain debugging symbols:
    configure CC='gcc -g' CXX='g++ -g'   (however also see --enable-debug, below)
 
    Some of the useful configure options:
 
      --enable-debug - build GASNet in a debugging mode. This turns on C-level
        debugger options and also enables extensive error and sanity checking
        system-wide, which is highly recommended for developing and debugging
        GASNet clients (but should NEVER be used for performance testing).
        --enable-debug also implies --enable-{trace,stats,debug-malloc},
        but these can still be selectively --disable'd.
      --enable-trace - turn on GASNet tracing (see usage info below)
      --enable-stats - turn on GASNet statistical collection (see usage info below)
      --enable-debug-malloc - use GASNet debugging malloc (see usage info below)
   
There are also variables for helping configure find conduit drivers if they are installed in a non-standard place, eg:
    --with-ibvhome=/path/to/ibv/drivers 

** Sec: GASNet Performance Environment Variables

* I would add a sentence somewhere mentioning GASNET_VERBOSEENV=1, which enables GASNet's environment variable readout at runtime, and is often a good starting place to see which variables might be relevant to this run (and confirming they were set as the user expected). GASNET_BACKTRACE=1 is also very helpful when debugging. The full list is of course in the top-level GASNet README and *-conduit/README

* GASNET_AMRDMA_MAX_PEERS:  Delete everything after "In some cases we have found.." (based on the findings earlier in our email thread)

* GASNET_GNI_MEMREG "Most often needed when running applications without the -ll:rsize flag (see below)." - This is a broken reference - there is no "below".

As a general point, one thing that seems to be missing from this page is instructions on how to link up a build of the Legion tree with the copy of GASNet the user has just successfully installed (ie how does the user tell Legion the GASNet install prefix and conduit to use). This might be covered somewhere else in the Legion documentation (although I could not find it on the Getting Started page or in README.md). It may be worthwhile to either explain that here or link that other documentation.

**Comment by streichler** [comment]
@bonachea Thanks again for writing this up.  I did a bit of documentation cleanup this morning.  When you get a moment, can you look over the updated page and see if I missed anything major?  (Regarding your last suggestion, the "Getting Started" page now tells users about the `GASNET_ROOT` Makefile variable for pointing at the right GASNet install location.)

**Comment by bonachea** [comment]
@streichler Looks much improved - thanks for your attention on this!

A few places still reference obsolete or redundant configure arguments, but I believe those remaining cases should all be harmless.

The only remaining non-trivial inconsistency I noticed was in the instructions for Titan that reference:

    ln -s other/contrib/cross-configure-crayxe-linux cross-configure

these scripts were recently renamed, I believe the correct script for Titan is now:

    ln -s other/contrib/cross-configure-cray-gemini-alps cross-configure

CC: @phhargrove

**Comment by streichler** [comment]
Yeah, I waffled a little on the "historical" examples there because they were correct for that particular system, GASNet and system software versions, and if I change things, I have no way of testing that they still worked on that config.  My inclination is to just remove that section and instead find a way to point at a primary source that shows how we currently configure things for our dev systems.
