### ISSUE TITLE
Slow logical tracing for pathological cases

### ISSUE THREAD

**Issue by magnatelee** [StanfordLegion/legion#285]
Attached is a test app that exhibits the issue. The app creates P partitions and launches index tasks on them, which are being traced (all the projection requirements request read-write privilege). The body of the leaf task is made empty, so the execution time of this app is quite close to the runtime overhead. When P gets bigger, the execution time with tracing increases rapidly, while it does slowly without tracing; the time gets more than 100 times bigger with 10 partitions when the tracing is used and only 1.4 times when tracing is not used. Here are commands to reproduce the issue:

- with tracing:
`for p in $(seq 5 10); do time ./analysis_perf -p "$p" -level 5 -T; done`
- without tracing:
`for p in $(seq 5 10); do time ./analysis_perf -p "$p" -level 5; done`

The root cause is that dependence records in a logical trace are kept in vectors and thus allow duplicate entries to exist:

https://github.com/StanfordLegion/legion/blob/master/runtime/legion/legion_trace.h#L213-L219

An obvious fix is to deduplicate the dependence records, which I tried in this commit:

https://github.com/StanfordLegion/legion/commit/2a428241cf3e1b7ff4565f2e4ac300a23f567f13

Although the fix solves the explosion of logical analysis overhead, it is still not able to make the tracing bring any benefit.

I was initially going to make the tracing calls ignored in the master branch, as we discussed in the meeting, but now I don't think that is necessary because the performance degradation on usual use cases (when P < 5) turned out to be somewhat negligible, although the overhead does not get any better either.

[analysis_perf.zip](https://github.com/StanfordLegion/legion/files/1213146/analysis_perf.zip)

**Comment by lightsighter** [comment]
I pushed a fix for this in master in 2232033. I opted to keep the data structures simple and just do a little bit of extra computation to deduplicate the entries when creating the trace with the assumption that the additional computation will be easily ammortized by the many replays of the trace that will occur later.  I confirmed that I got equivalent performance with the benchmark both with and without tracing.  I think we'll need more tasks in the trace with field-based task parallelism to really see a performance benefit for tracing.
