### ISSUE TITLE
Missing optimizations for 2d copies in the dma system

### ISSUE THREAD

**Issue by jiazhihao** [StanfordLegion/legion#291]
The optimizations for batching 2d copies are currently missing in the deppart branch. The issue can be reproduced by using the following commands.

export LG_RT_DIR=/home/zhihao/legion/runtime/
cd /home/zhihao/legion/apps/cnn/
make -j 12
./cnn -ll:gpu 2 -ll:fsize 4000 -level request=2

You should be able to observe that the dma system launches a large number of 1d requests for a potential 2d copy.

**Comment by streichler** [comment]
@jiazhihao did this performance issue show up in the dma branch as well?

**Comment by jiazhihao** [comment]
I am using the deppart API for creating partitions (e.g., create_partition_by_restriction). So it may not be easy to know if we can reproduce the issue in the dma branch.

**Comment by streichler** [comment]
Yeah, don't worry about it then.  I didn't realize this app only existed in the deppart branch.

**Comment by streichler** [comment]
Commit 60d0e80 adds a test that exercises 2d and 3d copies and reproduces the performance regression for 2d copies in the dma branch.  (The 3d copies are bad even in master, but that's a
problem for another day.)  Working on a fix now.

**Comment by streichler** [comment]
@jiazhihao I believe that both the dma and deppart branches have fixes for 2d and 3d copies for channels that support them (only memcpy supports 3d at the moment).  Can you try your app again and let me know if the performance is sufficiently improved?

**Comment by jiazhihao** [comment]
The performance looks much better after the fix. I will close this issue for now and reopen it if I observe other related issue.
