### ISSUE TITLE
Multi-Hop Copy Profiling Responses

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#293]
There is an assumption in Legion right now that for each ProfilingRequest passed to a Realm call we will get exactly one ProfilingResponse.  This is necessary for Legion to be able to determine when it is safe to actually shutdown the Realm runtime.  However, multi-hop copies right now return multiple profiling responses for a single profiling request, which is problematic and could lead to premature shutdowns (and all the things that go wrong with premature shutdowns like segfaults).  We need a way to figure out how to return a single profiling response for a multi-hop copy.

As a prerequisite for fixing this bug, @jiazhihao can you provide an example program that requires a multi-hop copy to serve as a test?

**Comment by jiazhihao** [comment]
I can provide an example that triggers multi-hop copy.  Should we delay the fix after the deppart merge, so that there won't be conflicts between Sean's changes and mine?

**Comment by streichler** [comment]
If this repros in master, I'd like to get it fixed there before the merge.  Do you have a suspicious about where the problem lies?

**Comment by streichler** [comment]
@lightsighter I have a test that is doing multi-hop copies between two nodes and I see no evidence of profiling data being sent more than once for any operation.  Can you attempt to reproduce the problem on your side?

**Comment by streichler** [comment]
Commit 96a5f06 fixes a double-free of an Operation object that might be to blame for this behavior.  Ideally I'd like to see a repro of the issue on a tree without this commit and then attempts to repro with the change.

**Comment by lightsighter** [comment]
I thought it was the case that there were always multiple profiling responses for multi-hop copies currently?  If not how does Realm return the timeline for the copy?

**Comment by jiazhihao** [comment]
The dma system mark the start time of a multi-hop copy when the first request of the first copy is launched and mark the finish time when the last request of the last copy is completed. Therefore, a multi-hop copy could perform bad when different copies within a multi-hop copy don't start simultaneously.

**Comment by lightsighter** [comment]
@jiazhihao it's alright if it performs badly, the invariant we want to confirm that is being maintained is that there will be exactly one ProfilingResponse generated regardless of how many hops there are in the copy. It used to be the case that there would be one ProfilingResponse generated for each hop. Is that no longer the case?

**Comment by streichler** [comment]
Closing this since #295 appears to better describe the issue.
