### ISSUE TITLE
Crash while receiving profiling responses

### ISSUE THREAD

**Issue by magnatelee** [StanfordLegion/legion#295]
Realm can send more than one profiling responses for one copy request from Legion when the request has multiple source-destination instance pairs, which makes the code crash with Legion Prof turned on. Here is a command that reproduces such scenario (needs access to the [Regent MiniAero repository](https://github.com/magnatelee/miniaero)):

`regent.py miniaero/rdir_1ghost.rg -lg:prof 1 -lg:serializer ascii`

Running this in debug mode will raise the following assertion:

`legion/runtime/legion/legion_profiling.cc:1185: void Legion::Internal::LegionProfiler::decrement_total_outstanding_requests(unsigned int): Assertion 'prev >= cnt' failed.`

I pushed a workaround (d344855) for the issue, which turns off the grouping in DMA and makes Legion Prof expect one response per source-destination instance pair. This commit must be reverted once the one-request-one-response policy for copies is reinstated.

**Comment by lightsighter** [comment]
This is a duplicate of #293 so please close both issues when it is fixed

**Comment by streichler** [comment]
The deppart branch's version of the workaround (which should also be reverted eventually) is 7634eea.

**Comment by elliottslaughter** [comment]
I'm seeing a freeze on master at certain node counts that @magnatelee tells me is likely to be caused by this. Do we have a plan to get to a full fix for this?

**Comment by lightsighter** [comment]
@elliottslaughter Did you confirm that it only happens when you request profiling information?

**Comment by streichler** [comment]
@elliottslaughter Any update on this?  If it still fails, do you have a command line I can try?

**Comment by lightsighter** [comment]
@elliottslaughter Given that we tagged this with the Soleil tag, I'm going to guess that the application was Soleil. Do you still want to keep the issue open or can we close it?

**Comment by elliottslaughter** [comment]
Well there's still the original report from @magnatelee. Unless the issue is confirmed fixed for that app we should still keep it open.

**Comment by magnatelee** [comment]
The original issue with MiniAero seems fixed in the master branch. Closing this issue for now.
