### ISSUE TITLE
Re-Enable Regent Auto-Vectorization with Dependent Partitioning

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#296]
As part of our incorporation of dependent partitioning, we required that Regent represent point types as a single field and not break each dimension index of the point into a separate field. This causes issues for Regent's auto-vectorization optimization which has difficulty dealing with compound data types such as multi-dimensional points. Consequently vectorization had to be disabled for many Regent applications which causes performance regressions. An easily reproducible case is from the circuit_sparse.rg application which sees the calculate_new_currents tasks take 4X longer when vectorization is disabled on both the master and deppart branches:

Master: http://legion.stanford.edu/~mebauer/circuit_sparse/master/index.html
Master (no vectorization): http://legion.stanford.edu/~mebauer/circuit_sparse/master_novec/index.html
Deppart (no vectorization): http://legion.stanford.edu/~mebauer/circuit_sparse/deppart/index.html

Run with the following command line:
./regent.py examples/circuit_sparse.rg -l 10 -p 10 -npp 2500 -wpp 10000 -ll:cpu 10 -fflow-spmd-shardsize 10

**Comment by elliottslaughter** [comment]
Why was vectorization disabled in Circuit? Circuit doesn't use multi-dimensional points.

Circuit does use tagged pointers (`ptr(T, ra, rb, rc)`), but I don't think Regent should be exposing the tags to Legion anyway---they're purely a Regent implementation detail to amortize the cost of dynamic `safe_cast` calls. Is the problem that we've turned even tagged pointers into a single field (when probably they shouldn't be)? Or is the vectorizer just overly conservative now?

**Comment by magnatelee** [comment]
The vectorizer is overly conservative now. The vector code generation assumes every (nested) struct type, including index and bounded types, is flattened all the way down to fields with primitive types and this has conflict with the change we pushed not to flatten index types.

**Comment by elliottslaughter** [comment]
@magnatelee This has been fixed, right?

**Comment by magnatelee** [comment]
@elliottslaughter I think so.
