### ISSUE TITLE
HDF crash with int3d-type fields

### ISSUE THREAD

**Issue by manopapad** [StanfordLegion/legion#302]
The attached Regent code [hdf_int3d_field.txt](https://github.com/StanfordLegion/legion/files/1342713/hdf_int3d_field.txt) crashes on my local machine with:

```
HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 140582309787392:
  #000: ../../../src/H5D.c line 358 in H5Dopen2(): not found
    major: Dataset
    minor: Object not found
  #001: ../../../src/H5Gloc.c line 430 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #002: ../../../src/H5Gtraverse.c line 861 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #003: ../../../src/H5Gtraverse.c line 641 in H5G_traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #004: ../../../src/H5Gloc.c line 385 in H5G_loc_find_cb(): object 'cell' doesn't exist
    major: Symbol table
    minor: Object not found
HDF5 error on dset_id = H5Dopen2(info->file_id, hdf5_info.dsetname->c_str(), H5P_DEFAULT):
HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 140582309787392:
  #000: ../../../src/H5D.c line 358 in H5Dopen2(): not found
    major: Dataset
    minor: Object not found
  #001: ../../../src/H5Gloc.c line 430 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #002: ../../../src/H5Gtraverse.c line 861 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #003: ../../../src/H5Gtraverse.c line 641 in H5G_traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #004: ../../../src/H5Gloc.c line 385 in H5G_loc_find_cb(): object 'cell' doesn't exist
    major: Symbol table
    minor: Object not found
a.out: /home/manolis/sw/legion/runtime/realm/transfer/channel.cc:1527: virtual long int Realm::HDFXferDes::get_requests(Realm::Request**, long int): Assertion `0' failed.
Aborted
```

**Comment by streichler** [comment]
It looks like the attached code is expecting an int3d field named `cell` to be blasted out into 3 separate fields called `cell.__ptr.x`, `cell.__ptr.y`, and `cell.__ptr.z`, but I think this has been recently changed in regent (in order to make dependent partitioning operations work properly).  @elliottslaughter , can you confirm that the field fusing (un-splitting?) we did is intended for hdf5 attachment as well?

**Comment by manopapad** [comment]
Also note that this example has been minimized as far as it can go. In particular, dumping the region only once (rather than twice, as this example does) does not cause a crash. The code also works if you skip the for-loop before the dumping.

**Comment by streichler** [comment]
Yes, you'll need a minimum set of things to occur before the Legion runtime admits that it actually has to write data to the HDF5 file on disk, which is when the mismatch between the field name provided by regent during the attach operation and the dataset names in the HDF5 created by the app becomes apparent.

**Comment by elliottslaughter** [comment]
@streichler is right, the fields were fused in deppart and the fusion applies everywhere (we can't fuse the field for runtime calls and then unfuse it for HDF5). HDF5 does support compound data types, so this means you'll need to tweak the code that generates the HDF5 files to define the type of the the struct before first use. E.g.:

https://support.hdfgroup.org/HDF5/Tutor/compound.html

**Comment by elliottslaughter** [comment]
@manopapad Were you able to get past this issue?

**Comment by manopapad** [comment]
I haven't had the time to try this yet. I'll update the issue when I have. Or you can close it right now if you prefer, and I'll reopen if it's still not working.

**Comment by manopapad** [comment]
I got this working by creating a compound HDF datatype. For posterity, here's how to properly set that up:

```
struct Foo {
  bar : int3d;
}
terra hdf5create(filename : &int8) : {}
  var fid = HDF5.H5Fcreate(filename, HDF5.H5F_ACC_TRUNC,
                           HDF5.H5P_DEFAULT, HDF5.H5P_DEFAULT)
  var sizes : uint64[1]
  sizes[0] = INDEX_SPACE_SIZE
  var int3dType = HDF5.H5Tcreate(HDF5.H5T_COMPOUND, 24)
  HDF5.H5Tinsert(int3dType, "x", 0, HDF5.H5T_STD_I64LE_g)
  HDF5.H5Tinsert(int3dType, "y", 8, HDF5.H5T_STD_I64LE_g)
  HDF5.H5Tinsert(int3dType, "z", 16, HDF5.H5T_STD_I64LE_g)
  var dataSpace = HDF5.H5Screate_simple(1, sizes, [&uint64](0))
  var dataSet = HDF5.H5Dcreate2(fid, "bar", int3dType, dataSpace,
                                HDF5.H5P_DEFAULT, HDF5.H5P_DEFAULT, HDF5.H5P_DEFAULT)
  HDF5.H5Dclose(dataSet)
  HDF5.H5Sclose(dataSpace)
  HDF5.H5Tclose(ptrType)
  HDF5.H5Fclose(fid)
end
```
