### ISSUE TITLE
Return profiling response on instance allocation failure

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#304]
Ever since I upgraded to master-post-deppart, I've been seeing the following assert when I fail to allocate an instance:

```
realm/inst_impl.cc:344: void Realm::RegionInstanceImpl::notify_allocation(bool, size_t): Assertion `success' failed.
```

I believe that this is supposed to return a profiling response to the high-level runtime so that this can be caught and dealt with (or not) in the mapper.

**Comment by lightsighter** [comment]
Yes, calls to RegionInstance::create_instance that fail need to return a profiling request with a NO_INSTANCE so we can give the mapper the option to try mapping the instance somewhere else if it wants.

**Comment by streichler** [comment]
This is on the top of my list for next week.  As a point of clarification though, you are not necessarily going to get a NO_INSTANCE result on an allocation failure.  You may get a valid handle, in which case you should destroy it once you get the profiling response indicating failure.  Also, depending on which processor is making the call to create_instance, which processor is handling profiling responses, and various bits of non-determinism, the profiling response may occur before the call to create_instance completes, so watch out for race conditions there.

**Comment by lightsighter** [comment]
Ok, so what is the profiling response that we should use to detect that the instance creation failed?

**Comment by streichler** [comment]
I'm waffling a bit.  The "orthogonal" way to do it is to add an `InstanceStatus` measurement that is similar to `OperationStatus`, and I can use the same rule that unless you ask for that measurement, an allocation failure is fatal.

An alternative is to add a 'successful' field to the `InstanceMemoryUsage` measurement.  That way, a failing response still gives the useful information of how much space you needed for the instance.  However, that information is likely already available to the requestor since they have to construct the instance layout now.

**Comment by elliottslaughter** [comment]
I learned today that the high-level runtime waits for an allocation failure to trigger the GC, so at the moment it's not even possible to deallocate instances without this code path in place. That basically makes this a hard blocker for me at the moment because even with the mapper setting `GC_FIRST_PRIORITY` on all instances, nothing will be deleted. The good news though is that my other issue where instances weren't being deleted will likely be fixed once this code path is added.

**Comment by lightsighter** [comment]
Right, garbage collection is a lazy process so we wait for an allocation failure to trigger the collection of any instances in the target memory (even then we only delete enough instances to try and make a space for the instance allocation so we don't fully collect the memory).

**Comment by streichler** [comment]
Instance allocation failures in Realm are reported via the `InstanceStatus` profiling measurement as of commit c6e7ac3.  Assigning to @lightsighter to connect things up on the Legion side.

**Comment by lightsighter** [comment]
Alright, this is in the Legion runtime with 110048a. Assigning back to @elliottslaughter to see if it works.

**Comment by elliottslaughter** [comment]
This appears to be working.
