### ISSUE TITLE
legion_prof results cannot render in browser

### ISSUE THREAD

**Issue by aheirich** [StanfordLegion/legion#308]
after a 256 node run on piz daint legion_prof runs for a long time (half hour?) to process the results.  then the results cannot be displayed in the browser.  
tar file is 170 MB, ask Alan for "pizDaint256.tar.gz" when you work on this

**Comment by aheirich** [comment]
if it is still online you can try here: 

http://sapling.stanford.edu/~aheirich/soleil-x/Job_256/legion_prof/?start=0&end=243885339.82049608&collapseAll=false&resolution=10

**Comment by magnatelee** [comment]
I can see the timeline without any problem:

![image](https://user-images.githubusercontent.com/331175/31143189-5a4cbab8-a831-11e7-8db3-44a2af9fa297.png)

If you are not on the Stanford network, it may take really long to fetch the timeline data. Could you try excluding node 0 from the timeline and see if it still does not render on your browser?

**Comment by aheirich** [comment]
true, the 256 node case is coming up for me this morning, yesterday it would not
would you mind trying the 512 node case? see if it works also.
http://sapling.stanford.edu/~aheirich/soleil-x/Job_512/legion_prof/?start=0&end=247003678.23107052&collapseAll=false&resolution=10

**Comment by magnatelee** [comment]
The 512 node timeline also works for me, but only on Safari:

![image](https://user-images.githubusercontent.com/331175/31144003-2373847e-a834-11e7-9a55-878dffce1b8c.png)

I remember there was a memory limit that one javascript program can use on Chrome and this might prevent you from rendering it (the size of the data the page loaded was 2.3GB).

**Comment by aheirich** [comment]
yes, it seems if I use Safari it works
closing this
