### ISSUE TITLE
Segmentation Fault when running "tester_io" across more than one process 

### ISSUE THREAD

**Issue by gshipman** [StanfordLegion/legion#31]
This test uses “tester_io” (updated in the DMA branch under tests/hdf_attach_subregion_parallel)
A partial fix was to change the index used to access the hdf_metadata_vec structure. There is still an issue in that the wrong HDFMemory is chosen from: machine.get_all_memories in realm/idx_impl.cc. A fix for this is to choose the HDFMemory whose kind is MemoryImpl::MKIND_HDF and not choose MemoryImpl::MKIND_REMOTE as follows below. I'll submit a pull request for master and dma branches in just a bit. 

diff --git a/runtime/realm/idx_impl.cc b/runtime/realm/idx_impl.cc
index a29d408..b631b90 100644
--- a/runtime/realm/idx_impl.cc
+++ b/runtime/realm/idx_impl.cc
@@ -485,14 +485,26 @@ namespace Realm {
       Machine machine = Machine::get_machine();
       std::set<Memory> mem;
       machine.get_all_memories(mem);
+      std::cout << "Node: " << gasnet_mynode() << " mem.size() is: " << mem.size() << std::endl;
       for(std::set<Memory>::iterator it = mem.begin(); it != mem.end(); it++) {
+        std::cout << "Node: " << gasnet_mynode() << " in Domain::create_hdf5_instance, looking at memory: "
+                  << &(*it) << " kind is : " << it->kind() << std::endl;
         if (it->kind() == Memory::HDF_MEM) {
           memory = *it;
+          HDFMemory* hdf_mem = (HDFMemory*) get_runtime()->get_memory_impl(memory);
+          std::cout << "Node: " << gasnet_mynode() << " found matching HDFMemory: " << hdf_mem
+                    << " kind is: " << it->kind() << " HDFMemory.kind is: "
+                    << hdf_mem->kind << std::endl;
+          
+          if(hdf_mem->kind == MemoryImpl::MKIND_HDF)
+            break; /* this is usable, take it */ 
         }

(lldb) thread backtrace all 
  thread #1: tid = 0xec9ca, 0x00007fff8cbe848a libsystem_kernel.dylib`__semwait_signal + 10, queue = 'com.apple.main-thread'
    frame #0: 0x00007fff8cbe848a libsystem_kernel.dylib`__semwait_signal + 10
    frame #1: 0x00007fff8d39af5d libsystem_c.dylib`nanosleep + 199
    frame #2: 0x00007fff8d39adbd libsystem_c.dylib`sleep + 42
    frame #3: 0x0000000107cf9bba tester_io`LegionRuntime::LowLevel::RuntimeImpl::run(this=0x00007fda8bc053a0, task_id=0, style=ONE_TASK_ONLY, args=0x0000000000000000, arglen=0, background=false) + 3930 at lowlevel.cc:10789
    frame #4: 0x0000000107cf8c50 tester_io`Realm::Runtime::run(this=0x00007fff57f67428, task_id=0, style=ONE_TASK_ONLY, args=0x0000000000000000, arglen=0, background=false) + 80 at lowlevel.cc:9807
    frame #5: 0x00000001083ab635 tester_io`LegionRuntime::HighLevel::Runtime::start(argc=2, argv=0x00007fff57f67d38, background=false) + 7797 at runtime.cc:15687
    frame #6: 0x0000000107e4adfa tester_io`LegionRuntime::HighLevel::HighLevelRuntime::start(argc=4, argv=0x00007fff57f67d28, background=false) + 42 at legion.cc:3671
    frame #7: 0x0000000107cb9816 tester_io`main(argc=4, argv=0x00007fff57f67d28) + 374 at tester_io.cc:244
    frame #8: 0x00007fff93b0b5c9 libdyld.dylib`start + 1

  thread #2: tid = 0xec9d5, 0x00007fff8cbe7c22 libsystem_kernel.dylib`__ioctl + 10
    frame #0: 0x00007fff8cbe7c22 libsystem_kernel.dylib`__ioctl + 10
    frame #1: 0x00007fff8cbe59b7 libsystem_kernel.dylib`ioctl + 159
    frame #2: 0x00000001085a545f tester_io`AMUDP_DrainNetwork(amudp_ep*) + 63
    frame #3: 0x00000001085a40a1 tester_io`AM_Poll + 97
    frame #4: 0x000000010853b4e2 tester_io`gasnetc_AMPoll + 50
    frame #5: 0x0000000107dacab4 tester_io`do_some_polling() [inlined] gasneti_AMPoll + 5 at gasnet_help.h:597
    frame #6: 0x0000000107dacaaf tester_io`do_some_polling() [inlined] gasnet_AMPoll at gasnet_help.h:712
    frame #7: 0x0000000107dacaaf tester_io`do_some_polling() + 31 at activemsg.cc:2057
    frame #8: 0x0000000107daced6 tester_io`gasnet_poll_thread_loop(data=0x0000000000000000) + 38 at activemsg.cc:2073
    frame #9: 0x00007fff98cfb268 libsystem_pthread.dylib`_pthread_body + 131
    frame #10: 0x00007fff98cfb1e5 libsystem_pthread.dylib`_pthread_start + 176
    frame #11: 0x00007fff98cf941d libsystem_pthread.dylib`thread_start + 13

  thread #3: tid = 0xec9d7, 0x00007fff8cbe8136 libsystem_kernel.dylib`__psynch_cvwait + 10
    frame #0: 0x00007fff8cbe8136 libsystem_kernel.dylib`__psynch_cvwait + 10
    frame #1: 0x00007fff98cfbe0c libsystem_pthread.dylib`_pthread_cond_wait + 693
    frame #2: 0x0000000107dab843 tester_io`IncomingMessageManager::get_messages(this=0x00007fda8bd00a30, sender=0x0000000109120ea4, wait=true) + 131 at activemsg.cc:686
    frame #3: 0x0000000107dab9c1 tester_io`LegionRuntime::LowLevel::HandlerThread::thread_main(this=0x00007fda8bd00b00) + 49 at activemsg.cc:725
    frame #4: 0x0000000107ce5d1d tester_io`LegionRuntime::LowLevel::PreemptableThread::thread_entry(data=0x00007fda8bd00b00) + 173 at lowlevel.cc:6392
    frame #5: 0x00007fff98cfb268 libsystem_pthread.dylib`_pthread_body + 131
    frame #6: 0x00007fff98cfb1e5 libsystem_pthread.dylib`_pthread_start + 176
    frame #7: 0x00007fff98cf941d libsystem_pthread.dylib`thread_start + 13

  thread #4: tid = 0xec9d8, 0x00007fff8cbe8166 libsystem_kernel.dylib`__psynch_mutexwait + 10
    frame #0: 0x00007fff8cbe8166 libsystem_kernel.dylib`__psynch_mutexwait + 10
    frame #1: 0x00007fff98cf978a libsystem_pthread.dylib`_pthread_mutex_lock + 480
    frame #2: 0x0000000107d97e2b tester_io`LegionRuntime::LowLevel::XferDesQueue::dequeue_xferDes(this=0x00007fda8bd00e60, dma_thread=0x00007fda8bd00f10, wait_on_empty=false) + 2587 at channel.h:1101
    frame #3: 0x0000000107d886a8 tester_io`LegionRuntime::LowLevel::DMAThread::dma_thread_loop(this=0x00007fda8bd00f10) + 1192 at channel.cc:1453
    frame #4: 0x0000000107dde54d tester_io`LegionRuntime::LowLevel::DMAThread::start(arg=0x00007fda8bd00f10) + 29 at channel.h:980
    frame #5: 0x00007fff98cfb268 libsystem_pthread.dylib`_pthread_body + 131
    frame #6: 0x00007fff98cfb1e5 libsystem_pthread.dylib`_pthread_start + 176
    frame #7: 0x00007fff98cf941d libsystem_pthread.dylib`thread_start + 13

  thread #5: tid = 0xec9d9, 0x00007fff8cbe8166 libsystem_kernel.dylib`__psynch_mutexwait + 10
    frame #0: 0x00007fff8cbe8166 libsystem_kernel.dylib`__psynch_mutexwait + 10
    frame #1: 0x00007fff98cf978a libsystem_pthread.dylib`_pthread_mutex_lock + 480
    frame #2: 0x0000000107d886cb tester_io`LegionRuntime::LowLevel::DMAThread::dma_thread_loop(this=0x00007fda8bd01330) + 1227 at channel.cc:1455
    frame #3: 0x0000000107dde54d tester_io`LegionRuntime::LowLevel::DMAThread::start(arg=0x00007fda8bd01330) + 29 at channel.h:980
    frame #4: 0x00007fff98cfb268 libsystem_pthread.dylib`_pthread_body + 131
    frame #5: 0x00007fff98cfb1e5 libsystem_pthread.dylib`_pthread_start + 176
    frame #6: 0x00007fff98cf941d libsystem_pthread.dylib`thread_start + 13

  thread #6: tid = 0xec9da, 0x00007fff8cbe8166 libsystem_kernel.dylib`__psynch_mutexwait + 10
    frame #0: 0x00007fff8cbe8166 libsystem_kernel.dylib`__psynch_mutexwait + 10
    frame #1: 0x00007fff98cf978a libsystem_pthread.dylib`_pthread_mutex_lock + 480
    frame #2: 0x0000000107d97e2b tester_io`LegionRuntime::LowLevel::XferDesQueue::dequeue_xferDes(this=0x00007fda8bd00e60, dma_thread=0x00007fda8bd01700, wait_on_empty=false) + 2587 at channel.h:1101
    frame #3: 0x0000000107d886a8 tester_io`LegionRuntime::LowLevel::DMAThread::dma_thread_loop(this=0x00007fda8bd01700) + 1192 at channel.cc:1453
    frame #4: 0x0000000107dde54d tester_io`LegionRuntime::LowLevel::DMAThread::start(arg=0x00007fda8bd01700) + 29 at channel.h:980
    frame #5: 0x00007fff98cfb268 libsystem_pthread.dylib`_pthread_body + 131
    frame #6: 0x00007fff98cfb1e5 libsystem_pthread.dylib`_pthread_start + 176
    frame #7: 0x00007fff98cf941d libsystem_pthread.dylib`thread_start + 13

* thread #7: tid = 0xec9dc, 0x0000000107d8288c tester_io`LegionRuntime::LowLevel::HDFMemory::create_instance(Realm::IndexSpace, int const*, unsigned long, unsigned long, unsigned long, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, int, long long, Realm::ProfilingRequestSet const&, Realm::RegionInstance, char const*, std::__1::vector<char const*, std::__1::allocator<char const*> > const&, Realm::Domain, bool) [inlined] std::__1::__vector_base<LegionRuntime::LowLevel::HDFMemory::HDFMetadata*, std::__1::allocator<LegionRuntime::LowLevel::HDFMemory::HDFMetadata*> >::__alloc(this=0x00007fda8bd00d30, __a=0x00007fda8bd00d40, __p=0x0000000000000008, __a0=0x00000001298b19f8) + 50 at memory:1462, stop reason = EXC_BAD_ACCESS (code=1, address=0x8)
  * frame #0: 0x0000000107d8288c tester_io`LegionRuntime::LowLevel::HDFMemory::create_instance(Realm::IndexSpace, int const*, unsigned long, unsigned long, unsigned long, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, int, long long, Realm::ProfilingRequestSet const&, Realm::RegionInstance, char const*, std::__1::vector<char const*, std::__1::allocator<char const*> > const&, Realm::Domain, bool) [inlined] std::__1::__vector_base<LegionRuntime::LowLevel::HDFMemory::HDFMetadata*, std::__1::allocator<LegionRuntime::LowLevel::HDFMemory::HDFMetadata*> >::__alloc(this=0x00007fda8bd00d30, __a=0x00007fda8bd00d40, __p=0x0000000000000008, __a0=0x00000001298b19f8) + 50 at memory:1462
    frame #1: 0x0000000107d8285a tester_io`LegionRuntime::LowLevel::HDFMemory::create_instance(Realm::IndexSpace, int const*, unsigned long, unsigned long, unsigned long, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, int, long long, Realm::ProfilingRequestSet const&, Realm::RegionInstance, char const*, std::__1::vector<char const*, std::__1::allocator<char const*> > const&, Realm::Domain, bool) [inlined] std::__1::vector<LegionRuntime::LowLevel::HDFMemory::HDFMetadata*, std::__1::allocator<LegionRuntime::LowLevel::HDFMemory::HDFMetadata*> >::push_back(this=0x00007fda8bd00d30, __x=0x00000001298b19f8) + 180 at vector:1538
    frame #2: 0x0000000107d827a6 tester_io`LegionRuntime::LowLevel::HDFMemory::create_instance(this=0x00007fda8bd00c90, is=(id = 0), linearization_bits=0x00000001298b2340, bytes_needed=128, block_size=16, element_size=8, field_sizes=0x00000001298b27d0, redopid=0, list_size=-1, reqs=0x00000001298b1f10, parent_inst=(id = 0), file=0x00007fda8be5e6a0, path_names=0x00000001298b2430, domain=<unavailable>, read_only=false) + 2550 at lowlevel_disk.cc:216
    frame #3: 0x0000000107ced9d2 tester_io`Realm::Domain::create_hdf5_instance(this=0x00007fda8be0a0e8, file_name=0x00007fda8be5e6a0, field_sizes=0x00000001298b27d0, field_files=0x00000001298b2430, read_only=false) const + 3570 at lowlevel.cc:7467
    frame #4: 0x0000000107eb5a7a tester_io`LegionRuntime::HighLevel::AttachOp::create_instance(this=0x00007fda8be6a6e0, dom=0x00007fda8be0a0e8, sizes=0x00000001298b27d0) + 1418 at legion_ops.cc:8987
    frame #5: 0x00000001080b5bbf tester_io`LegionRuntime::HighLevel::FieldSpaceNode::create_file_instance(this=0x00007fda8be04ec0, create_fields=0x00007fda8be6a808, attach_mask=0x00000001298b2a20, node=0x00007fda8d91e6a0, attach_op=0x00007fda8be6a6e0) + 223 at region_tree.cc:9228
    frame #6: 0x000000010807509c tester_io`LegionRuntime::HighLevel::RegionNode::attach_file(this=0x00007fda8d91e6a0, ctx=35, attach_mask=0x00000001298b2a20, req=0x00007fda8be6a7e8, attach_op=0x00007fda8be6a6e0) + 204 at region_tree.cc:17454
    frame #7: 0x0000000108074f79 tester_io`LegionRuntime::HighLevel::RegionTreeForest::attach_file(this=0x00007fda8be002e0, ctx=(ctx = 35), req=0x00007fda8be6a7e8, attach_op=0x00007fda8be6a6e0) + 313 at region_tree.cc:2572
    frame #8: 0x0000000107eb53e7 tester_io`LegionRuntime::HighLevel::AttachOp::trigger_execution(this=0x00007fda8be6a6e0) + 391 at legion_ops.cc:8952
    frame #9: 0x00000001083b175f tester_io`LegionRuntime::HighLevel::Runtime::high_level_runtime_task(args=0x00007fda8d824260, arglen=20, p=(id = 2147483648)) + 911 at runtime.cc:16672
    frame #10: 0x0000000107ce53f7 tester_io`LegionRuntime::LowLevel::PreemptableThread::run_task(this=0x00007fda8bf00650, task=0x00007fda8d8006e0, actual_proc=(id = 2147483648)) + 231 at lowlevel.cc:6344
    frame #11: 0x0000000107ce623d tester_io`LegionRuntime::LowLevel::GreenletTask::run(this=0x00007fda8bc36380, arg=0x00007fda8bf00650) + 61 at lowlevel.cc:6441
    frame #12: 0x0000000107e1adc9 tester_io`greenlet::_run(arg=0x00007fda8bf00650) + 57 at greenlet-cc.cc:158
    frame #13: 0x0000000107e1a84e tester_io`_greenlet_start(arg=0x00007fda8bc28460) + 110 at greenlet.cc:122

  thread #8: tid = 0xec9df, 0x00007fff8cbe8136 libsystem_kernel.dylib`__psynch_cvwait + 10
    frame #0: 0x00007fff8cbe8136 libsystem_kernel.dylib`__psynch_cvwait + 10
    frame #1: 0x00007fff98cfbe0c libsystem_pthread.dylib`_pthread_cond_wait + 693
    frame #2: 0x0000000107cfda1d tester_io`GASNetCondVar::wait(this=0x00007fda8bf002e0) + 45 at activemsg.h:124
    frame #3: 0x0000000107ce688b tester_io`LegionRuntime::LowLevel::GreenletProcessor::execute_task(this=0x00007fda8bf00270) + 411 at lowlevel.cc:6650
    frame #4: 0x0000000107ce66b7 tester_io`LegionRuntime::LowLevel::GreenletThread::thread_main(this=0x00007fda8d900000) + 55 at lowlevel.cc:6467
    frame #5: 0x0000000107ce5d1d tester_io`LegionRuntime::LowLevel::PreemptableThread::thread_entry(data=0x00007fda8d900000) + 173 at lowlevel.cc:6392
    frame #6: 0x00007fff98cfb268 libsystem_pthread.dylib`_pthread_body + 131
    frame #7: 0x00007fff98cfb1e5 libsystem_pthread.dylib`_pthread_start + 176
    frame #8: 0x00007fff98cf941d libsystem_pthread.dylib`thread_start + 13

Here is a bit of info from the debugger, note that the HDFMemory thinks it is “remote” 
frame #2: 0x0000000107d827a6 tester_io`LegionRuntime::LowLevel::HDFMemory::create_instance(this=0x00007fda8bd00c90, is=(id = 0), linearization_bits=0x00000001298b2340, bytes_needed=128, block_size=16, element_size=8, field_sizes=0x00000001298b27d0, redopid=0, list_size=-1, reqs=0x00000001298b1f10, parent_inst=(id = 0), file=0x00007fda8be5e6a0, path_names=0x00000001298b2430, domain=<unavailable>, read_only=false) + 2550 at lowlevel_disk.cc:216
   213 
      pthread_rwlock_unlock(&this->rwlock);
   214 
      return inst;
   215 
    }
-> 216 
   217 
    void HDFMemory::destroy_instance(RegionInstance i,
   218 
    bool local_destroy)
   219 
    {
(lldb) p this 
(LegionRuntime::LowLevel::HDFMemory *) $3 = 0x00007fda8bd00c90
(lldb) p *this 
(LegionRuntime::LowLevel::HDFMemory) $4 = {
  LegionRuntime::LowLevel::MemoryImpl = {
    me = (id = 1619066880)
    size = 0
    kind = 
    alignment = 0
    lowlevel_kind = HDF_MEM
    mutex = {
      mutex = {
        lock = (__sig = 1297437784, __opaque = "")
      }
    }
    instances = size=2 {
      [0] = 0x00007fda8bd7e280
      [1] = 0x00007fda8d83ba80
    }
    free_blocks = size=0 {}
  }
  hdf_metadata_vec = size=0 {}
  rwlock = (__sig = 4294967396, __opaque = "")
}

**Comment by gshipman** [comment]
Okay, I've added the fix to select the right type of HDFMemory in commit e6f532c6607d94794a3527ee9bc0f6aaa2b0471f on the dma-set-comparitor branch. Seems to correct things on both single process and multiple process testing. Would like to get Noah's testing results as well.

**Comment by streichler** [comment]
Assigning to Galen for a status update.  Pass the buck as necessary...

**Comment by gshipman** [comment]
Fixed.
