### ISSUE TITLE
Task reprioritization on resumption

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#312]
Currently, when a blocked task becomes ready for execution, it is implicitly prioritized above all other tasks in the ready queue. Under certain conditions, this can result in poor performance if it expected that the new tasks will only issue subtasks and immediately block. It would be nice to have some sort of ability (ideally in the mapper, but anywhere initially would be fine) to choose the priority with which a task is reinserted into the ready queue when it is resumed.

**Comment by lightsighter** [comment]
Can you give an example of wanting a different priority under wake-up than what was initially assigned to that task?

**Comment by elliottslaughter** [comment]
In the psana use case, I have a stream of tasks that are going to immediately issue subtasks and block, and then perform a computation upon continuation. Under the current scheme, this causes me to see this pattern:

(Warning: large trace) http://legion.stanford.edu/~eslaught/psana/rax_run37_eager_knl_bb/limit_none/prof_n16/

Basically, as soon as any I/O tasks complete, the Python processor will prioritize the continuation of those tasks rather than launching more tasks to issue I/O. Eventually, the queue drains, and the I/O processors become empty, and only then does the Python processor free up to issue more tasks.

**Comment by streichler** [comment]
Ball is in my court to provide a way to change the priority of a running task and fix Realm's prioritization code to favor higher-priority new tasks over lower-priority resumable tasks.  Then I'll hand it over to Mike to do the Legion half.

**Comment by streichler** [comment]
The new branch task_priority has a first shot at the Realm changes for this.  Assigning to Mike to work on the Legion side of it.

**Comment by lightsighter** [comment]
A design decision for us @elliottslaughter @streichler to make: how should we allow the application to change the priority of a running task?

Option 1: There is an application-facing call into the runtime to change the priority, but no priority is directly passed. Instead when the runtime receives the call from the application, it turns around and invokes a new mapper call on the mapper for the task to ask the mapper to select the new priority for the task.

Option 2: Same as option one, but the application can directly pass in a new priority. It is then up to the application as to whether it knows the new priority ahead of time, or would like to ask the mapper to pick a new priority via a mapper call to pick a tunable value.

Either one is fine with me. They both have a way to invoke the mapper to pick the priority which in my mind is the important part. Really we're just deciding whether this decision has to come from the mapper or it could come from somewhere else.

**Comment by streichler** [comment]
I'd like to consider a third option in which the application code is completely oblivious:  When mapping a child operation (e.g. task launch, inline mapping), the mapper would be able to request a change to the parent task's priority.  This should match PSANA's needs pretty well (i.e. lower the parent task's priority when mapping the I/O subtask), but it does mean my current Realm interface may be insufficient.

The current API only allows a running task to change its own priority, but I think in this case you'd need to be able to change the priority of another task, perhaps even after it has suspended.  I think it's straightforward to support this in Realm, but in the interest of keeping the API small, I'll only add it if needed.

**Comment by lightsighter** [comment]
Two questions:
1. How are we going to name Realm tasks for setting the priority?
2. Are you going to support this ability from a remote node, e.g. when the child is mapping on a remote node and asks to change its parent's priority?

**Comment by streichler** [comment]
It'd basically use the same machinery as for task cancellation:
1. You refer to a Realm task by its completion `Event` (see: https://github.com/StanfordLegion/legion/blob/master/runtime/realm/event.h#L61).
2. The Realm `OperationTable` knows where things are and can forward cancellation (and now potentially reprioritization) requests.

**Comment by lightsighter** [comment]
I'm also a little worried about the "security" (if that is the right word for this) because now a mapper for a child task can change the priority for the parent task which may be owned by a different mapper. So now we can have two different mappers silently fighting with each other over the priority of a task.

**Comment by streichler** [comment]
How is that different from two mappers "arguing" over where data for a region should be placed?  In either case, it'll be functionally correct in all cases, and have good performance when the mapper(s) are making good and consistent policy decisions.

**Comment by elliottslaughter** [comment]
So I'd personally be fine with a more limited version of this where a task has two priorities that are both chosen up front: the initial priority, and the priority with which to resume the task when it blocks. I realize this doesn't allow the same range of functionality, but from an implementation perspective it seems much easier, and I don't expect to need the full expressiveness provided by what you describe above.

**Comment by lightsighter** [comment]
I've pushed my changes. First, your mapper needs to override the configure_context mapper call and enable child operations to mutate the priority of the parent task:

https://github.com/StanfordLegion/legion/blob/task_priority/runtime/legion/legion_mapping.h#L1352

If you don't set this the runtime will not allow child tasks to mutate the priority of the parent task. If they try the runtime will issue a warning. Next your mapper needs to override select_task_options to change the priority for the parent task for the subtasks that are launched off that should adjust the priority:

https://github.com/StanfordLegion/legion/blob/task_priority/runtime/legion/legion_mapping.h#L312

If you don't change this field then the runtime will not update the parent task priority.

Assigning back to @elliottslaughter to test it out.

**Comment by elliottslaughter** [comment]
I can confirm that this is working, and I recommend merging the branch into master.

**Comment by lightsighter** [comment]
Pull request #329 merged this into the master branch so I am closing the issue.
