### ISSUE TITLE
fix inter-node GPU->GPU copies

### ISSUE THREAD

**Issue by streichler** [StanfordLegion/legion#321]
Changes to hide intermediate buffers from the Realm machine model have broken path finding
for inter-node GPU->GPU copies.  This needs to be cleaned up before the 17.10 release.

**Comment by streichler** [comment]
Commit 4d1119e should have the fix for this.  @jiazhihao, can you try it in the multi-GPU/multi-node configurations where you were seeing problems before?

**Comment by streichler** [comment]
@jiazhihao another ping on this...

**Comment by lightsighter** [comment]
@jiazhihao Any luck confirming that this is fixed?

**Comment by jiazhihao** [comment]
I have tried quite a few multi-GPU/multi-node benchmarks recently and haven't seen any crashes. I think the issue should have been fixed.
