### ISSUE TITLE
Regent: add ability to call Regent tasks from C/C++

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#322]
For interoperability, it would be useful to have the ability to call Regent tasks from a C or C++ program. This requires the following features:

 - [x] dump a Regent object (`.o` or `.so`) without generating a corresponding `main()`
 - [x] generate registration functions in object file along with a corresponding header to make it callable from C
 - [x] generate a wrapper to perform the task launch from C (again with corresponding header)
 - [x] add an example code to demonstrate this use case
 - [ ] support for passing future arguments
 - [ ] support for index launches

CC @ipdemes

**Comment by streichler** [comment]
I see Mike's already tagged this with the S3D label.  I'll give it a try there as soon as it's ready.  S3D will want to add its own "domain-specific" goo around both the task body and the launch wrapper, which I think will be straightforward if we have the right metaprogramming hooks.

**Comment by lightsighter** [comment]
This maybe should be discussed more in the context of issue #296 but at least for S3D one of the important parts of vectorization for at least several important S3D kernels is the cache blocking when the inputs and outputs of a computation are over all the species in a cell.  Keeping all the species values in cache is important and there are enough of them that the way we would normally write the loop in regent probably won't accomplish this without transforming the code.

**Comment by elliottslaughter** [comment]
We probably want to discuss the DSL aspect with @magnatelee. It may be that the Regent auto-parallelizer can be make powerful enough to handle these cases, avoiding the need for application scientists to be maintaining their own DSL.

**Comment by lightsighter** [comment]
Well, I think S3D will always need something like Singe to handle the mechanism-specific kernels. However, the kernels I referenced above are not mechanism-specific, they just need to be cache-blocked.

**Comment by streichler** [comment]
As I think more about it, the goo I'm anticipating is more "application-specific" than domain-specific.  Ideally we'd want to have the leaf tasks we generate for S3D use the app's existing data structures rather than have to put a wrapper around the wrapper.  A straightforward way to do this would be to have the task launch wrappers be generated as terra blobs that could inlined into other terra stuff before the .o/.so is generated.

**Comment by elliottslaughter** [comment]
Initial support for this has landed. At the moment the only abstraction layer that is exposed is the C and C++ APIs. The intention is that as the internals get cleaned up, there would be a way to extend this at the Terra level to allow applications to generate their own C and C++ API wrappers.

**Comment by elliottslaughter** [comment]
Closing this issue to split the remaining items into their own individual issues.
