### ISSUE TITLE
regent crash - assert line 2702 flow_spmd.t

### ISSUE THREAD

**Issue by aheirich** [StanfordLegion/legion#324]
...
FIXME: Skipping update of region which is not read
FIXME: Skipping update of region which is not read
...P/legion/language/src/rdir/plugin/src/regent/flow_spmd.t:2702: assertion failed!
stack traceback:
	[C]: in function 'assert'
	...P/legion/language/src/rdir/plugin/src/regent/flow_spmd.t:2702: in function 'rewrite_copies_subgraph'
	...P/legion/language/src/rdir/plugin/src/regent/flow_spmd.t:2875: in function 'fn'
	.../PSAAP/legion/language/src/rdir/plugin/src/regent/flow.t:383: in function 'traverse_nodes_recursive'
	.../PSAAP/legion/language/src/rdir/plugin/src/regent/flow.t:378: in function 'traverse_nodes_recursive'
	...P/legion/language/src/rdir/plugin/src/regent/flow_spmd.t:2871: in function 'rewrite_communication'
	...P/legion/language/src/rdir/plugin/src/regent/flow_spmd.t:6432: in function 'spmdize'
	...P/legion/language/src/rdir/plugin/src/regent/flow_spmd.t:6499: in function 'spmdize_eligible_loop'
	...P/legion/language/src/rdir/plugin/src/regent/flow_spmd.t:6515: in function 'spmdize_eligible_loops'
	...P/legion/language/src/rdir/plugin/src/regent/flow_spmd.t:6523: in function 'graph'
	...P/legion/language/src/rdir/plugin/src/regent/flow_spmd.t:6534: in function 'fn'
	.../PSAAP/legion/language/src/rdir/plugin/src/regent/flow.t:404: in function 'map_nodes_recursive'
	...P/legion/language/src/rdir/plugin/src/regent/flow_spmd.t:6531: in function <...P/legion/language/src/rdir/plugin/src/regent/flow_spmd.t:6527>
	...aheirich/PSAAP/legion/language/src/regent/passes_hooks.t:41: in function 'optimize'
	/users/aheirich/PSAAP/legion/language/src/regent/passes.t:54: in function </users/aheirich/PSAAP/legion/language/src/regent/passes.t:46>
	/users/aheirich/PSAAP/liszt-legion/include/admiral.t:2519: in function </users/aheirich/PSAAP/liszt-legion/include/admiral.t:2395>
	/users/aheirich/PSAAP/soleil-x-6/src/soleil-x.t:3397: in main chunk

**Comment by aheirich** [comment]
To compile the test program you will need to set up a soleil-x environment from the branch soleil_viz_regent_crash
The source program is soleil-x.t modified at a single line, commenting out the call to Render inside the simulation loop.

**Comment by aheirich** [comment]
[regent_compiler_crash.log](https://github.com/StanfordLegion/legion/files/1412531/regent_compiler_crash.log)
attaching slurm log that shows all of the compiler switches

**Comment by elliottslaughter** [comment]
@manopapad Does Soleil even compile with SCR any more? If not I'm inclined to close this.

**Comment by manopapad** [comment]
We haven't been compiling Soleil with SCR for a while now.

**Comment by elliottslaughter** [comment]
Considering the branch does not seem to exist any more, I'm going to close this issue.
