### ISSUE TITLE
Realm Registered Memory Failure at Start-up Without GASNet

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#33]
Asking Realm for registered memory without GASNet results in a start-up assertion.  Here is the relevant part of backtrace.  The problem is that 'prealloc_base' is NULL, but that is only allowed if the '_register' parameter is false, which it is not in this case.

#7  0x00007f9db18bcb22 in __GI___assert_fail (assertion=0x7f9db1475d64 "!_registered", file=0x7f9db1475b00 "/home/mebauer/extern_legion/legion/runtime//realm/mem_impl.cc", line=467, 
    function=0x7f9db1476c20 <Realm::LocalCPUMemory::LocalCPUMemory(Realm::Memory, unsigned long, void*, bool)::__PRETTY_FUNCTION__> "Realm::LocalCPUMemory::LocalCPUMemory(Realm::Memory, size_t, void*, bool)")
    at assert.c:101
#8  0x00007f9db1189810 in Realm::LocalCPUMemory::LocalCPUMemory (this=0x681fa50, _me=..., _size=8589934592, prealloc_base=0x0, _registered=true)
    at /home/mebauer/extern_legion/legion/runtime//realm/mem_impl.cc:467
#9  0x00007f9db11a2fec in Realm::RuntimeImpl::init (this=0x5d55df0, argc=0x7fff7e561b2c, argv=0x7fff7e561b20) at /home/mebauer/extern_legion/legion/runtime//realm/runtime_impl.cc:636
#10 0x00007f9db11a134b in Realm::Runtime::init (this=0x7fff7e561b40, argc=0x7fff7e561b2c, argv=0x7fff7e561b20) at /home/mebauer/extern_legion/legion/runtime//realm/runtime_impl.cc:108

**Comment by streichler** [comment]
Should be fixed in master with 3f942ae.  Assigning back to Mike to verify/close.
