### ISSUE TITLE
Update website tutorials to remove deprecated namespaces

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#330]
The tutorials and other code samples on the website currently use deprecated namespaces and APIs. These should be updated to be more modern.

http://legion.stanford.edu/tutorial/hello_world.html

**Comment by elliottslaughter** [comment]
Updated tutorial 0. Only 9 more to go...

**Comment by lightsighter** [comment]
Are you just updating the code or the text as well? Do you need help with this?

Side question: can you think of an easy way to couple the text with the code, something like the literate programming that they use in [PBRT](http://www.pbrt.org/) Maybe something like [this](https://github.com/gokyle/literate)?

**Comment by elliottslaughter** [comment]
Yes, I'm updating the text, which is why this isn't just a quick fix. If you want to help, just post in this issue when you finish a tutorial.

You can do "literate" programming easily enough in Markdown. Just write something like:

    This is a hello world example. The first line is needed to import
    the standard C library for input and output.
    
    ```
    #include <stdio.h>
    ```
    
    Next we need to define main....

This is just Markdown, so for the website you can just copy-and-paste. The problem is you need to post-process it to get a C++ file that you can compile. So that means we'd either force the users to download and run Pandoc prior to being able to actually run anything (bad), or we'd have to do it for them and check the files into the repository (doable, but still not great).

I suppose you could do the same thing in the opposite direction by writing the text in C++ comments, but then I'm not sure how you'd parse it.

Keep in mind also that there are Regent versions of the tutorials, and that those need different text. Though I suppose we could always do something like `.cc.md` goes to `.cc` and `.rg.md` goes to `.rg`.

If this seems worthwhile, I guess I could take a shot at writing the script. We'll still end up duplicating the files everywhere, but at least in theory we'll have one authoritative copy which is capable of generating all the others.

**Comment by elliottslaughter** [comment]
Updated tutorial 1...

**Comment by elliottslaughter** [comment]
Updated tutorial 2...

**Comment by elliottslaughter** [comment]
Updated tutorial 3...

**Comment by elliottslaughter** [comment]
Updated tutorial 4...

**Comment by elliottslaughter** [comment]
Tutorial 5 is in progress, but I'm out of time so I'll have to pick up the rest of it later. The progress so far is checked in to git.

**Comment by lightsighter** [comment]
I'm proof read through tutorial 4. Let me know as you finish others and I will proof read more.

**Comment by elliottslaughter** [comment]
Finished updating tutorial 5.

**Comment by elliottslaughter** [comment]
Updated tutorial 6.

**Comment by elliottslaughter** [comment]
Updated tutorial 7.

**Comment by elliottslaughter** [comment]
Updated tutorial 8.

**Comment by elliottslaughter** [comment]
This was done some time ago.
