### ISSUE TITLE
Missing Regent Native Language Features for Dynamic Control Replication Analysis

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#331]
I've been writing a static analysis for Regent that attempts to figure out when a task is dynamically control replicable. Right now we look for external function calls (e.g. anything that might contain a random number generator call in it) and use that to disqualify tasks from being 'replicable'. The problem with this is that it disqualifies a bunch of Regent programs that use one of the following features in the top-level task:

- Legion C API calls
- Print statements
- Assertions
- Timing calls

After talking with @elliottslaughter we agreed that it would be good to make some of these into Regent native features so that the compiler can reason about them and know that they don't impact the ability of the program to be control replicated. We can use this issue to track the features that we think will be necessary to be native in Regent in order to help out program analyses like the one for determining when a task is dynamically control replicable.

For completeness we also discussed things not to support. Right now the only thing on this list is deprecated partitioning APIs. They will remain in the C interface and will automatically disqualify tasks from being dynamically control replicated.

**Comment by elliottslaughter** [comment]
Everything above is now permitted except for print statements. We'd have to add a print() statement to Regent if we wanted to make that work. In principle that's fine, I'm just not 100% sure that we want to bake printf semantics into the language.

I'm fine with closing this as print statements can be worked around easily enough by launching a task.

**Comment by lightsighter** [comment]
Alright, I'm going to go ahead and close this since I think we've satisfied it enough for the moment.
