### ISSUE TITLE
Regent "Insist" Annotations

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#332]
Ideally Regent should have an "insist" annotation on a task implementation to say what properties the task implementation has, even if the compiler cannot statically prove it. Specifically we should be able to annotate tasks as being leaf/inner/idempotent/replicable and have that be communicated to the runtime.

**Comment by lightsighter** [comment]
I added the Soleil tag since issue #338 might need this as well.

**Comment by elliottslaughter** [comment]
A while back @magnatelee and I made an ideological decision not to do this, and to instead on a case-by-case basis add flags to override certain `__demand` annotations in the presence of certain features. In this way, as the compiler becomes more expressive it is possible to remove these flags over time, and hopefully limit the growth of `__insist` in code bases.

Closing for now, let me know if you want to revisit this discussion.
