### ISSUE TITLE
Assertion failure in the DMA system

### ISSUE THREAD

**Issue by jiazhihao** [StanfordLegion/legion#335]
I got the following assertion failure when I try to run an application with 4 P100 GPUs on Sherlock.

[0 - 7f7d840b2700] {6}{dma}: kind mismatch: 7 != 8: src=1e00000000000004 dst=1e00000000000001 serdez=0,0 redop=0
cnn: /home/users/zhihao/legion/runtime/realm/transfer/lowlevel_dma.cc:1489: Realm::XferDes::XferKind Realm::get_xfer_des(Realm::Memory, Realm::Memory, Realm::CustomSerdezID, Realm::CustomSerdezID, Realm::ReductionOpID): Assertion `0' failed.

I believe what happened here is that the new `get_xfer_des` function thinks this is a `XFER_GPU_IN_FB` transfer though the source and destination are in different memories. 

I am not sure if this is a side effect of NVLink --- the Sherlock node has NVLink between GPUs.

**Comment by streichler** [comment]
@jiazhihao I think this should be fixed with commit fff725a.  Please give it another try on Sherlock and let me know how it goes.

**Comment by lightsighter** [comment]
@jiazhihao Any progress on confirming that this is fixed?

**Comment by jiazhihao** [comment]
Confirming that the bug has been fixed by commit fff725a.
