### ISSUE TITLE
Race Condition with Waits on Migrating Barriers

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#342]
This bug manifests non-deterministically with the following assertion:

in Realm::BarrierImpl::add_waiter (this=0x2aaab5e013e0, needed_gen=4, 
    waiter=0x2aaab5dbefb0) at /home/mbauer/legion/runtime/realm/event_impl.cc:2265
2265          assert((owner == my_node_id) || (gen_subscribed >= needed_gen));

It occurs when the following chain of events happens in this order:
1. A task decides to wait on a barrier
2. In the process of invoking Event::wait, the task first calls has_triggered while its node owns the barrier
3. Realm decides to migrate the barrier and begins the migration changing the owner node of the barrier
4. The task doing the wait then tries to register an event waiter on the barrier and hits the assertion because it hasn't subscribed to the most recent generation of the barrier and its node is no longer the owner

I've observed this in about 1 in 10 runs of a dynamically control replicated version of Pennant on the haswell nodes of the PSG cluster with optimizations on.  Running with -DDISABLE_BARRIER_MIGRATION causes the race to never occur.

**Comment by streichler** [comment]
@lightsighter did you get a chance to check if this bug was still occurring?

**Comment by lightsighter** [comment]
250 runs on the PSG cluster haswell nodes without incident. Closing the issue.
