### ISSUE TITLE
CUDA failure with Regent generated kernel

### ISSUE THREAD

**Issue by jiazhihao** [StanfordLegion/legion#348]
The following Regent file crashes deterministically with Regent generated CUDA kernel. The crash is reproducible on n0000 by the following steps:

1. install the up-to-date Regent with `./install --cuda --gasnet`
2. zhihao@n0000:~/legion/language$ ./regent.py examples/pagerank/pagerank_mapping_test.rg -graph /home/zhihao/hollywood.gr -nw 2 -ll:gpu 2 -ll:fsize 4000 -ll:zsize 20000
pagerank settings: num_nodes=1139905 num_edges=57515616 iterations=10 workers=2
Load input graph...
graph = /home/zhihao/hollywood_csr.dat
init_score = 0.00000088
Start PageRank computation...
CU: cuLaunchKernel(f, config.grid.x, config.grid.y, config.grid.z, config.block.x, config.block.y, config.block.z, config.shared, raw_stream, NULL, extra) = 1 (CUDA_ERROR_INVALID_VALUE): invalid argument
terra: /home/zhihao/legion/runtime/realm/cuda/cuda_module.cc:1808: void Realm::Cuda::GPUProcessor::launch(const void*): Assertion `0' failed.

If we run the same program on Sherlock with CUDA 8.0, it returns a compile error as follows:
[zhihao@sh-114-02 ~/legion/language]$ ./regent.py examples/pagerank/pagerank_mapping_test.rg -graph examples/pagerank/hollywood.gr -nw 2 -ll:gpu 2 -ll:fsize 5000 -ll:zsize 10000
CU: cuModuleGetFunction(&f, module, func->device_fun) = 500 (CUDA_ERROR_NOT_FOUND): named symbol not found
terra: /home/users/zhihao/legion/runtime/realm/cuda/cuda_module.cc:2101: void Realm::Cuda::GPU::register_function(const Realm::Cuda::RegisteredFunction*): Assertion `0' failed.

**Comment by magnatelee** [comment]
This should be fixed in ca66b36. @jiazhihao please close this issue once you confirm it is fixed.

**Comment by jiazhihao** [comment]
@magnatelee Confirmed that the issue has been fixed on sapling. However, I still observe the same compile error on Sherlock as before. I guess this might be a separate issue on Regent.

**Comment by jiazhihao** [comment]
The issue has been fixed in ca66b36.
