### ISSUE TITLE
Regent: Accidental inline mappings in non-inner tasks

### ISSUE THREAD

**Issue by magnatelee** [StanfordLegion/legion#349]
When a task has both region accesses and task launches, it accidentally inline maps all regions declared in the task even though it actually uses only some of them. To fix the issue, we want to track "inner-ness" of individual regions and inline map only the regions that are not inner.

**Comment by elliottslaughter** [comment]
This should be fixed in 980a64c4080acf8429aa43d357073b59b61c00fd.
