### ISSUE TITLE
Processor Groups Need Memory Affinities to the Same Set of Memories as their Constituent Processors

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#35]
Right now processor groups don't report any affinities for memories which they should be able to see.  As a result the high-level runtime is throwing warnings for tasks which try to map to memories which should be visible from the processor group, but appear to not be visible due to the missing affinities.

**Comment by lightsighter** [comment]
I should comment that in extreme cases this can result in unnecessary failed mappings.  I've put in a work around for now in the high-level runtime, but it eliminates an important safety check to guarantee that mapping decisions have no impact on correctness.

**Comment by streichler** [comment]
This wasn't an oversight - it was a conscious design choice, but one we can change if we choose to.  Processor Groups in their current form are not "discoverable" via the Machine API, and instead behave more like other user-creatable objects in Realm - the way you "discover" it is that some other task tells you about it, and it is presumed that it told you why it told you about it.  For example, it is currently up to the creator of a Processor Group to intersect the affinities of the member Processors and remember that if it chooses to.

The dynamic machine model we're moving to would allow us to treat Processor Groups the same as Processors - i.e. have them show up in Machine::get_all_processors() and have their affinities be queryable.  I'm on the fence as to whether this is desirable and worth the overhead - some amount of broadcasting would need to be added to ensure the machine reaches an (even eventually) consistent state.

Passing the discussion baton back to Mike...

**Comment by streichler** [comment]
Mike, any thoughts on this?

**Comment by lightsighter** [comment]
I'm not sure at the moment.  I'm kind of curious as to what your plan is going to be for a processor group that has a processor go down.  Does that invalidate the processor group or does it change it?  Does Realm report this in some way to the client?  It can't be done with event poisoning the way other things can.

**Comment by streichler** [comment]
With the current treatment of processor groups as application-controlled entities, Realm wouldn't do anything special if a processor that goes down is in a group.  It'd be up to the creator of the group to pay attention to the state changes for any of the processors it put into the group and take a possibly-app-specific action in response.

A task launch to a processor group for which all of the processors are down will be similar to a task launch to a single processor that's down - the task launch will fail, it will be reported via the profiling interface, and the task's finish event will be poisoned.

**Comment by streichler** [comment]
I'd like to close this, keeping the current semantics that processor groups are not part of the machine model.  @lightsighter , are you ok with this?

**Comment by lightsighter** [comment]
Is there a way to get the set of processors in a processor group back from Realm? I feel like I should still not be issuing warnings in this case. I'll need to check that each of the processors has affinity to each of the memories individually.

**Comment by streichler** [comment]
Yes, you can get the members of a group with this method:
https://github.com/StanfordLegion/legion/blob/master/runtime/realm/processor.h#L73
although this currently only works on the node that created the group.  If you need it to work on other nodes, let me know.

**Comment by lightsighter** [comment]
Commit d401afd should fix this and I don't think we will need the group members on a node different from where the group is created.  However, we may make the group on a node that is different from where the processors exist (e.g. remote mapping of a task onto a set of processors on a different node). If that works then we can close the issue. Assigning back to @streichler to confirm this is alright and then close the issue.

**Comment by lightsighter** [comment]
Ok, seems like we cannot create or query processor groups from remote nodes for now, but we will notice it if someone tries to do it. The issue with the views has been resolved so that we will perform the affinity test against the right set of processors.
