### ISSUE TITLE
Question about __demand(__spmd)

### ISSUE THREAD

**Issue by chamsolli** [StanfordLegion/legion#355]
Hi all,

I have a quick question regarding "__demand(__spmd)" in Regent. Attached test code runs fine with parallel run. However, I get wrong result when I run with spmd flag. Did I use wrong flag for __demand(__spmd)? Or should I install legion with special flag?

Thanks,
Jae hwan Choi

------
[spmdTest.rg.gz](https://github.com/StanfordLegion/legion/files/1733452/spmdTest.rg.gz)
./regent.py spmdTest.rg -p 4 -ll:cpu 4
--> OUTPUT
simTime = 0.100000
Done.

./regent.py spmdTest.rg -p 4 -ll:cpu 4 -fflow 1 -fflow-spmd 1 -fflow-spmd-shardsize 1
--> OUTPUT
FIXME: Mapping optimization disabled while outlining task
FIXME: Not copying back scalar result
simTime = 0.000000
Done.

**Comment by elliottslaughter** [comment]
When you say "wrong result", are you talking about the simTime being 0, or something else?

There is a known issue in the SPMD transformation where it doesn't properly update the values of scalars (such as simTime) at the end of the SPMD block. That's why there's a warning being printed:

```
FIXME: Not copying back scalar result
```

In general SPMD should never change the result of your code.

Or is there something else you're talking about?

**Comment by chamsolli** [comment]
I expected that "simTime" should also be 0.1 when I use SPMD transformation. I have one more question now.

Is the value of "simTime" in SPMD block correctly updated while the program runs inside the SPMD block? In turn, is the value returned incorrectly only at the end of the SPMD block? (Indeed, I'm using "simTime" as a condition to terminate SPMD block in my code : break the while loop when "simTime" is larger or equal to certain value). I guess that the value of "simTime" in SPMD block is updated properly based on your last comment..

I appreciate your reply Elliott. Thanks!
Jae hwan Choi

**Comment by elliottslaughter** [comment]
Yes, it's only the update of the value outside the block that is buggy. If you pass simTime into a task inside the block, you will see the correct value.

**Comment by chamsolli** [comment]
Thanks Elliott. Closing the issue.
