### ISSUE TITLE
Bug in Regent Partitioning Routines

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#356]
I fixed a bug in Legion Spy that was causing some safety checks not to be performed. In particular one of the checks that was not always being performed is the one that checks that a sub-region in a partition is dominated by the parent region of the partition.  In the master branch I now see this warning being emitted for the list_cross_product.rg test:

hellbender:language mebauer$ ./regent.py tests/regent/run_pass/list_cross_product.rg -level legion_spy=2 -logfile log.spy
x0 12
x1 3
x2 204
x3 5
product of x0..x4: 36720
hellbender:language mebauer$ pypy ../tools/legion_spy.py log.spy 
Reading log file log.spy...
WARNING: Skipped 1 lines when reading log.spy
Reducing top-level index space shapes...
Done
WARNING: child Index Space 23 is not dominated by parent Index Space 9 in Index Partition: 10. This is definitely an application bug.
Legion Spy analysis complete.  Exiting...

I've confirmed that this is an actual bug. Regent tells Legion that index space 23 contains the rectangle (2,3) while the parent index space contains the points (1) and (3). This means there is a bug somewhere in the Regent partitioning logic. I'm not familiar enough with the partitioning libraries for Regent to be able to fix it.

**Comment by magnatelee** [comment]
I think the bug was introduced by 99837ec which revived the old shallow partitioning code. Reverting it seems to make the bug disappear. Will close this issue once the revert commit passes CI.

**Comment by lightsighter** [comment]
@magnatelee So does that mean this existed in the old version of the partitioning code from before dependent partitioning?

**Comment by magnatelee** [comment]
@lightsighter I'm not sure. If the safety check you recovered didn't exist before the deppart merge, it's possible that this bug had been undiscovered. Otherwise, the bug can be due to the old partitioning code using the deppart API in an inconsistent way. In any case, I feel it's not worth spending time on fixing the old code.

BTW, I just confirmed that we pass all GitLab CI tests as well. Let's close the issue if no one objects.

**Comment by lightsighter** [comment]
Ok, sounds good to me. I'm happy as long as you guys are satisfied with the state of the Regent partitioning code. I'm closing the issue.

**Comment by elliottslaughter** [comment]
I believe we resolved the need for this by using pending partitions in f4249ffe1ad8a250a49726d85775a824dac46826 in the complete cross product. I don't think we actually need to do anything to fix the shallow product (it'll just be slightly less accurate when the index spaces are very sparse). @magnatelee can confirm.

**Comment by magnatelee** [comment]
Yes, we resolve the need for using the old complete cross product code with f4249ff. We now support complete cross product of sparse n-dimensional index spaces.
