### ISSUE TITLE
Non-contiguous partitions seem to break

### ISSUE THREAD

**Issue by hturki** [StanfordLegion/legion#360]
The following code throws a "Assertion failed: (is_id == 0), function operator Rect, file /legion/runtime/legion/legion_domain.inl, line 921" error on both stable and develop:

import "regent"

fspace body {
 sector : int1d,
}

task main()
 
 -- This works
 var bodies = region(ispace(int1d, 3), body)
 bodies[0].sector = 1
 bodies[1].sector = 1
 bodies[2].sector = 0

 var sector_index = ispace(int1d, 2)
 var bodies_by_sector = partition(bodies.sector, sector_index)

 for i in sector_index do
   for body in bodies_by_sector[i] do
     regentlib.c.printf("body %d sector %d\n", int(body), body.sector)
   end
 end

 -- This doesn't
 bodies[0].sector = 0
 bodies[1].sector = 1
 bodies[2].sector = 0

 var bodies_by_sector_2 = partition(bodies.sector, sector_index)

 for i in sector_index do
   for body in bodies_by_sector_2[i] do
     regentlib.c.printf("body %d sector %d\n", int(body), body.sector)
   end
 end
end
regentlib.start(main)

**Comment by lightsighter** [comment]
I can reproduce the issue. It's definitely a compiler bug as the compiler is doing the C API call 'legion_domain_get_rect_1d' on a domain with a non-trivial sparsity map, which it should be checking for before doing the conversion. Assigning @elliottslaughter and @magnatelee to fix it.

**Comment by magnatelee** [comment]
This bug should be fixed now in the master branch. @syamajala Could you confirm the fix and close this issue?

**Comment by magnatelee** [comment]
Oops. I asked a wrong person to confirm the fix. I'll close this issue on behalf of Haithem.
