### ISSUE TITLE
Realm: Deferred Allocations and Deletions

### ISSUE THREAD

**Issue by hturki** [StanfordLegion/legion#362]
import "regent"

task subTask(i : int)
 var test = region(ispace(int1d, 10000000), int)
 test[0] = i
 regentlib.c.printf("%d\n", test[0])
 __delete(test)
end

task main()
 for t=0,100 do
   subTask(t)
 end
end
regentlib.start(main)

Fails with:

[0 - 7fffcc5663c0] {4}{threads}: reservation ('DMA request queue') cannot be satisfied
0
1
2
3
4
5
6
7
8
9
10
11
12
[0 - 700005324000] {5}{default_mapper}: Default mapper failed allocation for region requirement of inline mapping in task main (UID 1) in memory 1e00000000000000for processor 1d00000000000001. This means the working set of your application is too big for the allotted capacity of the given memory under the default mapper's mapping scheme. You have three choices: ask Realm to allocate more memory, write a custom mapper to better manage working sets, or find a bigger machine. Good luck!
Assertion failed: (false), function map_inline, file 
/legion/runtime/mappers/default_mapper.cc, line 2656.

It would separately be nice to document the need to free regions/partitions more explicitly

**Comment by lightsighter** [comment]
@elliottslaughter or @magnatelee does deletion actually tell the runtime to delete the logical region right now or are has that functionality not been implemented yet?

@hturki Which commit of master are you on? I made a change to some of the garbage collection code for physical instances earlier this week which might help this code. It will only help though if Regent is actually deleting the logical region.

**Comment by hturki** [comment]
Hey @lightsighter - I'm on https://github.com/StanfordLegion/legion/commit/6db26c5d95a64625bdb4ce546c043b9feadb8365 (although the latest of stable aka https://github.com/StanfordLegion/legion/commit/57d01885ce18c54b9c8f798d3c4184ae56b794d3 also seems to exhibit the same issue)

**Comment by elliottslaughter** [comment]
I'm pretty sure `__delete` is working as intended, from Regent's perspective. The problem is that the processing of a deletion occurs in a deferred way, and if you map too far ahead, the mapper will receive an allocation failure from which it can't recover. (You can't defer the execution of a task from inside of `map_task`, so there isn't any reasonable way for the mapper to deal with this situation.) As far as I know, the only way to "fix" this is to teach the mapper to limit the number of tasks that can be outstanding. See https://github.com/StanfordLegion/psana-legion/blob/master/psana_legion/simple_mapper.cc as an example of how to do this.

**Comment by lightsighter** [comment]
No there is another way, which is Realm needs to support deferred allocations that are aware of deferred instance deletions. @streichler can say when this will be available.

**Comment by streichler** [comment]
Deferred allocation are performed starting with commit 15b0ccc1.  There should be no impact to any application that ran nefore this commit without any failed allocations.  However, if there is some change in behavior, `-ll:defalloc 0` can be specified on the command line to disable deferred allocations (i.e. allocations will be performed based only on instance destructions whose preconditions have been satisified).
