### ISSUE TITLE
Distinguish tasks & variants in Legion Prof

### ISSUE THREAD

**Issue by manopapad** [StanfordLegion/legion#366]
When I run the following Regent code:

```
import 'regent'
__demand(__cuda)
task foo()
end
task main()
  foo()
end
regentlib.start(main)
```

on sapling's n0000 with `-fcuda 1 -lg:registration`, here's what I see:

```
[0 - 7f285c34f780] {3}{runtime}: Task variant foo of task unnamed_task_10000 (ID 10000) has Realm ID 8
[0 - 7f285c34f780] {3}{runtime}: Task variant foo of task foo (ID 10000) has Realm ID 9
[0 - 7f285c34f780] {3}{runtime}: Task variant foo of task foo (ID 10000) has Realm ID 10
```

I would expect to see something like:
Task variant **foo_VARIANT1** of task **foo** (ID 10000) has Realm ID 8
Task variant **foo_VARIANT2** of task foo (ID 10000) has Realm ID 9
Task variant **foo_VARIANT3** of task foo (ID 10000) has Realm ID 10

I.e. the variants are not tagged with their type, and also the task's name is sometimes missing (although that might be an issue with -lg:registration).

**Comment by lightsighter** [comment]
@manopapad Why do you want the names to be different? It should be perfectly fine for the compiler to give the variants the same name as the original task. If you want to know what the variant can be used for in the mapper that is what the execution constraints are for (which Regent is annotating). Keying off the variant names just seems like a brittle idea.

I'm going to mark this an enhancement for now and @elliottslaughter and @magnatelee can address it if they feel like it would be important.

Does this issue with -lg:registration happen deterministically? For what it's worth, -lg:registration will only report the registered task IDs at start-up, so anything that is done after start-up will not be recorded (including if task names are registered later).

**Comment by elliottslaughter** [comment]
I'm guessing the issue is distinguishing the variants in Legion Prof output. @manopapad can correct me if there's a different use case in mind.

**Comment by manopapad** [comment]
Correct, I'm only suggesting this change to improve debugability.

The -lg:registration issue happens deterministically; the first time a task name is mentioned in the -lg:registration output, it's listed as "unnamed_task_TASKID".

**Comment by lightsighter** [comment]
I fixed the -lg:registration issue in the master branch. We should see the correct task IDs from now on.

I guess it would be nice to distinguish variants in Legion Prof. I'll leave this as an open issue but marked as an enhancement.

**Comment by elliottslaughter** [comment]
This issue needs a new owner if it's really about a Legion Prof enhancement. @magnatelee ?

**Comment by magnatelee** [comment]
Timelines show variant names as of 626df89b. Here is an example:

![image](https://user-images.githubusercontent.com/331175/67819298-d13a0600-fa71-11e9-906e-84ecef4c0603.png)

![image](https://user-images.githubusercontent.com/331175/67819305-d9924100-fa71-11e9-9371-c1084c0d9d91.png)

@manopapad Feel free to close this issue if you are satisfied with the fix.

**Comment by manopapad** [comment]
Very snazzy
