### ISSUE TITLE
-fskip-empty-tasks 0 breaks simulation

### ISSUE THREAD

**Issue by hturki** [StanfordLegion/legion#367]
Repro: Run https://github.com/hturki/barnes-hut/blob/37e410541cc6e5815505978063d25253501a9075/barnes_hut.rg with "-i <path/to> bodies-32768.csv -fskip-empty-tasks 0"
[bodies-32768.csv.zip](https://github.com/StanfordLegion/legion/files/1809309/bodies-32768.csv.zip)

Without the "-fskip-empty-tasks 0" task things run fine. With it, you get:

terra: /home/users/hturki/legion/runtime/realm/deppart/partitions.cc:149: Realm::Event Realm::IndexSpace<N, T>::create_equal_subspaces(size_t, size_t, std::vector<Realm::IndexSpace<N, T> >&, const Realm::ProfilingRequestSet&, Realm::Event) const [with int N = 1; T = long long int; size_t = long unsigned int]: Assertion `0' failed.

https://github.com/StanfordLegion/legion/blob/stable/runtime/realm/deppart/partitions.cc#L148-L149

**Comment by lightsighter** [comment]
@streichler This is unimplemented functionality for a call to create_equal_subspaces with an index space that contains a sparsity map.

**Comment by streichler** [comment]
Equal partitions of sparse index spaces have been around since commit 284a71b.
