### ISSUE TITLE
invalid id type found in get_event_impl 

### ISSUE THREAD

**Issue by noahdesu** [StanfordLegion/legion#37]
In latest `dma` branch I see the periodic failure:

```
Assertion failed: (0), function get_event_impl, file /Users/nwatkins/src/legion/runtime/realm/runtime_impl.cc, line 1256
```
Running
```
Running `GASNET_BACKTRACE=1  GASNET_MASTERIP='127.0.0.1' GASNET_SPAWN=-L SSH_SERVERS="localhost localhost" amudprun -np 2 ./tester_io
```
in `test/hdf_attach_subregion_parallel`

Stack trace is so far evading capture. Will update when possible.

**Comment by streichler** [comment]
Did you get a backtrace from gasnet?

**Comment by noahdesu** [comment]
No backtrace is being produced automatically, and the assertions aren't failing when adding some busy loops for attaching GBD. I'm working on getting a backtrace, will update.

**Comment by streichler** [comment]
Closing this one out too - reopen if/when needed.
