### ISSUE TITLE
GPU/DMA Realm + Legion Prof Enhancements

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#374]
We need to update Realm's profiling interface and Legion Prof in order to handle "effects" for various Realm operations, such as GPU tasks where kernels are launched off, and DMA operations where there might be several copies required as part of a multi-hop copy operation. We want the profiler to see all these separately so it can more accurately visualize what is actually going on in the machine. The motivating use case for this is the profiles generated by S3D.

**Comment by lightsighter** [comment]
@seemamirch @streichler  Do we think that we've fixed this issue, or are there still outstanding things in Realm that are not being accurately profiled? Also, do we have all this information piped through to the profiler so that it is rendered for the user to see?

**Comment by mariodirenzo** [comment]
I think I am observing this issue in this timeline http://sapling.stanford.edu/~mariodr/Patch_X

**Comment by lightsighter** [comment]
Adding a note that this has to include remote dependent partitioning operations as well.

**Comment by streichler** [comment]
@seemamirch I'd suggest closing out this issue and creating new issues specific to any enhancements that are being proposed.  I know you're waiting on me for one of them, but I don't know if there are others.  :)

**Comment by seemamirch** [comment]
Creating multiple issues to better track this
