### ISSUE TITLE
Realm Must Use cuMemset for Filling GPU FB Memories

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#378]
This is a very bad performance bug. Realm fill operations need to use cuMemsetAsync in order to fill GPU FB memories. I've put in a temporary hack that uses the synchronous version of cuMemset for fills for now in some limited but common circumstances (commit 462303f95 should be rolled back after all this is fixed). However, it looks like fills in general need a major overhaul so I've avoided making any kind of major changes.

**Comment by lightsighter** [comment]
Here is the commit in gitlab: https://gitlab.com/StanfordLegion/legion/commit/462303f953d19b5d1ecd9b7c429e255ec2785807

**Comment by streichler** [comment]
Commit 9fd6772a switched this path to use cuMemset*Async calls.  @lightsighter , is the performance of these fills what you expect now?

**Comment by lightsighter** [comment]
Good enough for now. Closing the issue.
