### ISSUE TITLE
Realm DMA System Need to Recognize Alternative Dimension Orders for Copies/Fills

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#379]
The Realm DMA system does not iterate copies and fills for the correct dimension order when it is not the assumed Fortran dimension order. This results in very large slow-downs for copies and fills.

**Comment by streichler** [comment]
This should be fixed in commit 27ab9d5.  Re-assigning to @lightsighter to close this issue and/or complain further.

**Comment by lightsighter** [comment]
Confirmed that this is fixed at least for the current C dimension order case that I care about.
