### ISSUE TITLE
Filling then HDF-dumping triggers an assertion failure in Realm

### ISSUE THREAD

**Issue by manopapad** [StanfordLegion/legion#381]
Download [minus_one_is_bad.tar.gz](https://github.com/StanfordLegion/legion/files/1933883/minus_one_is_bad.tar.gz), unzip and run `./test.sh` on a machine with an HDF installation (you need to `export HDF_ROOT` appropriately). You should see this output:

```
Dumping to out_dir.
terra: <...>/legion/runtime/realm/transfer/transfer.cc:1223: size_t Realm::TransferIteratorIndexSpace<N, T>::step(size_t, Realm::TransferIterator::AddressInfo&, unsigned int, bool) [with int N = 1; T = long long int; size_t = long unsigned int]: Assertion `0 && "no support for non-affine pieces yet"' failed.
```

The output contents are also wrong (they are zeros instead of the fill value of -1).

If you change the fill value to a positive number the assertion is no longer triggered, although the final contents of the HDF files are still wrong (they are all zeros rather the fill value).

**Comment by lightsighter** [comment]
Alright, there are two bugs running around here: one is a Realm bug as evidenced by the assertion above (assigning @streichler and @jiazhihao) and the other is a compiler bug. In some cases (somehow depend on fill value) the compiler is re-ordering the fill around the dump tasks which is unsound (you can see this in Legion Spy outputs from the runtime). If you run with -fflow 0 then the correct order of operations is performed and we see the Realm assertion every time regardless of the choice of fill value. Assigning @elliottslaughter to fix the compiler bug.

**Comment by manopapad** [comment]
Regarding the compiler bug, it might be an issue with the inner-task optimization pass; running with -finner 0 fixes the bug, and that is also sufficient to fix #373.

**Comment by manopapad** [comment]
BTW, on my machine -fflow 0 isn't fixing the bug.

**Comment by elliottslaughter** [comment]
Ok, I think there are at least three bugs: `-fflow 1` definitely does reorder the execution, so that's wrong. But if it's still failing with `-fflow 0` then that points to a bug elsewhere....

**Comment by elliottslaughter** [comment]
I think the `-fflow 1` piece of this bug is related to the Regent inliner. Specifically, in the following scenario, the inliner isn't correctly adding the necessary constraints:

```
var r = region(...)
var p = partition(r)
some_task(r, p)
```

And the body of `some_task` includes:

```
for c in p.colors do
    child_task(p[c])
end
```

If this code had been manually inlined by the user into the parent task, the Regent type checker would have added the constraints `p[c] <= p <= r`, which the RDIR optimization would have used to find the chain of parent tasks. With automatic inlining, these constraints are missed and RDIR can't find the ancestor of `p[c]`.

Adding @magnatelee to look at the inliner.

**Comment by elliottslaughter** [comment]
Here is a reproducer for the RDIR/inliner-specific issue which does not depend on HDF5.

[inliner_reproducer.rg.gz](https://github.com/StanfordLegion/legion/files/1940218/inliner_reproducer.rg.gz)

**Comment by streichler** [comment]
Commit 42e169c1 should provide the necessary support in Realm for doing fills to HDF5 instances.

**Comment by magnatelee** [comment]
Commit 8b9289fb should fix the issue in the task inliner.

**Comment by elliottslaughter** [comment]
@magnatelee Please make sure all of these reproducers get added to the test suite before closing out the issue.

**Comment by magnatelee** [comment]
@elliottslaughter @manopapad @jpietarilagraham I believe commits b07b0cb9 and a0fdd021 fix all issues in the task inliner. @manopapad can we close this issue now?

**Comment by streichler** [comment]
This appears to have been waiting over a year for an ack from @jpietarilagraham .  I'm assuming silence is agreement here and closing the bug.
