### ISSUE TITLE
Realm DMA System Needs to Support Arbitrary Sized Fills to GPU Framebuffer Memory

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#386]
Issuing arbitrary 64-bit fills to instances in a GPU framebuffer will cause the Realm DMA system to assert. The exception is for values with the first four bytes being identical to the last four bytes (e.g. 0.0).

**Comment by streichler** [comment]
This should be fixed by commit 320edea.  Re-assigning to @lightsighter to verify.

**Comment by lightsighter** [comment]
Confirmed that this is fixed for 64-bit values. Changing the scope of the bug to now handle arbitrary sized fills on the GPU and assigning back to @streichler.

**Comment by streichler** [comment]
@lightsighter is there more to do here?  Code for arbitrary-sized fills on the GPU have been in for a while now.

**Comment by lightsighter** [comment]
Noting that this is now functionally fixed, although the implementation is highly likely to cause a performance bug in the future.
