### ISSUE TITLE
Regent Needs Completeness Types on Partitions

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#389]
Users need to be able to specify in Regent whether the partitions they are making are complete or not at compile time. Passing this information through to the runtime will greatly reduce the overhead of runtime program analysis for applications with complicated partitioning trees.

**Comment by elliottslaughter** [comment]
@lightsighter Is this still necessary in the presence of `nopaint`?

**Comment by lightsighter** [comment]
@elliottslaughter Yes

**Comment by syamajala** [comment]
@elliottslaughter i think this issue related as well, right? https://github.com/StanfordLegion/legion/issues/487

For image, preimage, and restrict would this be the equivalent of being able to pass something like DISJOINT_COMPLETE_KIND or ALIASED_INCOMPLETE_KIND for example?

**Comment by elliottslaughter** [comment]
That's orthogonal, but the fix will be similar. I.e. we'll add the ability to say something like `image(disjoint, complete, ...)`.

**Comment by magnatelee** [comment]
Assigning this to me as this will arrive together with the new parallelizer merge.

**Comment by magnatelee** [comment]
PR #763 should address this issue. Will close the issue as soon as #763 is merged to master.

**Comment by elliottslaughter** [comment]
This is merged as of bb90442bcd76cf985c534e77f914a9858d5f1690.
