### ISSUE TITLE
Realm Support for GPU UVM Memory

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#390]
Add support for a UVM memory for GPUs.

**Comment by lightsighter** [comment]
This also needs to support variables decorated with __managed__ which can trigger the __cudaRegisteredManagedVar call from the CUDA compiler.

**Comment by streichler** [comment]
This happened a while ago with commits 2950a156 and 139dd08c.  There is a limitation in the CUDA driver API that only allows `__managed__` variables to work with a single GPU per process.
