### ISSUE TITLE
Regent implicitly downcasts floats to ints in task arguments

### ISSUE THREAD

**Issue by manopapad** [StanfordLegion/legion#392]
The following code snippet prints `2`. It should be giving a type error.

```
import 'regent'
task foo(x : int32)
  regentlib.c.printf('%d\n', x)
end
task main()
  var x : double = 2.1
  foo(x)
end
regentlib.start(main)
```

**Comment by elliottslaughter** [comment]
Does a similar program in Terra produce a different result? Regent should be following the Terra cast rules here.

**Comment by manopapad** [comment]
It produces the same result! The equivalent code is:

```
C = terralib.includec('stdio.h')
terra foo(x : int32)
  C.printf('%d\n', x)
end
terra main()
  var x : double = 2.1
  foo(x)
end
main()
```

So this is a terra bug then. Moving this report to the terra bug tracker.
