### ISSUE TITLE
Assertion failure in tutorial/08_multiple_partitions

### ISSUE THREAD

**Issue by jiazhihao** [StanfordLegion/legion#393]
You should be able to observe the following assertion failure if you run tutorial/08_multiple_partitions.
The template parameter DIM = 1, while the actual dim = 0.

zhihao@n0000:~/legion/tutorial/08_multiple_partitions$ ./multiple_partitions 
Running stencil computation for 1024 elements...
Partitioning data into 4 sub-regions...
multiple_partitions: /home/zhihao/legion/runtime/legion/legion_domain.inl:936: Legion::Domain::operator Legion::DomainT<DIM, T>() const [with int DIM = 1; T = long long int]: Assertion `DIM == dim' failed.
Aborted

**Comment by lightsighter** [comment]
Which branch are you in? I don't see this assertion at all and this test is run in the CI, so if the CI isn't failing then as far as I'm concerned this test is working fine.

**Comment by jiazhihao** [comment]
Close this issue since the failure is not reproduced. An interesting thing is that I was able to deterministically trigger the assertion failure this afternoon. Will reopen the issue if I can get a reproducer.

**Comment by lightsighter** [comment]
Make sure you are on the right commit too. I am on d2102e3 which should be the most recent commit to master.

**Comment by lightsighter** [comment]
It might also be interested to see a backtrace.
