### ISSUE TITLE
Legion Error: Illegal implicit mapping of a virtual mapped region in task init_task

### ISSUE THREAD

**Issue by jiazhihao** [StanfordLegion/legion#396]
I encountered the following Legion error, which seems to be a potential bug in the default mapper. The error can be reproduced as follows on n0001 (with cuda/8.0).
1. cd /home/zhihao/legion/apps/Lux/pagerank/
2. make
3. ./pagerank -ng 1 -ni 1 -file /home/zhihao/hollywood.lux -ll:gpu 1 -ll:fsize 2000 -ll:zsize 2000

[0 - 7fda5159d700] {3}{pagerank}: PageRank settings: numPartitions(1) numIter(1)filename = /home/zhihao/hollywood.lux
[0 - 7fda5159d700] {3}{graph}: Load graph: numNodes(1139905) numEdges(57515616)
[0 - 7fda5159d700] {3}{graph}: left_bound = 0 right_bound = 1139904
[0 - 7fda5159d700] {3}{graph}: Load task: file(/home/zhihao/hollywood.lux) rowLeft(0) rowRight(1139904) colLeft(0) colRight(57515615)
[0 - 7fda5135b700] {5}{runtime}: [error 160] LEGION ERROR: Illegal implicit mapping of a virtual mapped region in task init_task (UID 37) (from file /home/zhihao/legion/runtime//legion/runtime.cc:1713)[error 160] 
For more information see:
http://legion.stanford.edu/messages/error_code.html#error_code_160

**Comment by lightsighter** [comment]
@jiazhihao This is an application bug and not a default mapper bug. It means you are trying to create an accessor for a virtual mapped region. The default mapper choose to virtual map the region (probably because you marked the task inner), but then you tried to make an accessor for it which is not legal. Usually the runtime will try to remap it for you if you originally mapped the region to an actual physical instance, but in the case where the region was virtually mapped then there is nothing that the runtime can do to help you.

**Comment by jiazhihao** [comment]
@lightsighter I was able to figure out the problem: the default mapper uses `RegionRequirement::tag` to store particular mapping decisions: https://gitlab.com/StanfordLegion/legion/blob/master/runtime/mappers/default_mapper.cc#L1614

While the application also uses `tag` to carry mapping decisions, which conflicts with the default mapper. Can I assume that `RegionRequirement::tag` is set by applications and won't be modified by the runtime? If so, I will use higher bits to carry my mapping decisions.

**Comment by lightsighter** [comment]
It is safe to assume that the runtime will not modify mapping tags. The runtime will always pass through mapping tags as-is without any changes. 

However, the default mapper will always try to interpret mapping tags that it sees using its enum for mapper tags. It's up to the application to make sure it's mapping tags don't interfere with default mapper's if it also wants to pass through mapping tags that it uses when extending the default mapper.

**Comment by jiazhihao** [comment]
Looks good to me. I will then fix the mapping tags on the application side.
