### ISSUE TITLE
Barrier Migration Broken in nopaint and control_replication Branches

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#408]
I had to disable barrier migration in the 'nopaint' and 'control_replication' branches because it was causing different tests to fail non-deterministically with the same Realm assertion. For example,

https://gitlab.com/StanfordLegion/legion/-/jobs/81740674
https://gitlab.com/StanfordLegion/legion/-/jobs/81722300

Disabling barrier migration makes the crashes go away. Turning it back on brings them back.

**Comment by streichler** [comment]
Seems to be working now.  Closing.
