### ISSUE TITLE
Legion fails to test on Fedora 28

### ISSUE THREAD

**Issue by junghans** [StanfordLegion/legion#409]
https://bugzilla.redhat.com/show_bug.cgi?id=1604546:

> legion failed to build from source in Fedora rawhide
> 
> https://koji.fedoraproject.org/koji/taskinfo?taskID=28194759
> 
> 
> For details on the mass rebuild see:
> 
> https://fedoraproject.org/wiki/Fedora_29_Mass_Rebuild
> Please fix legion at your earliest convenience and set the bug's status to
ASSIGNED when you start fixing it. If the bug remains in NEW state for 8 weeks,
legion will be orphaned. Before branching of Fedora 30,
legion will be retired, if it still fails to build.
> 
> For more details on the FTBFS policy, please visit:
> https://fedoraproject.org/wiki/Fails_to_build_from_source

**Comment by junghans** [comment]
In https://koji.fedoraproject.org/koji/taskinfo?taskID=28194759 the `circuit` test fails on x86_65 with:
```
      Start  2: circuit
 2/24 Test  #2: circuit ..........................***Exception: Child aborted  0.78 sec
```

In https://koji.fedoraproject.org/koji/taskinfo?taskID=28457810 the `realm_stencil` test fails with:
```
7/25 Test  #7: realm_stencil ....................***Exception: Child aborted  5.36 sec
[0 - f6c5e340] {4}{threads}: reservation ('CPU proc 1d00000000000002') cannot be satisfied
Stencil configuration:
      nx 12
      ny 12
     ntx 2
     nty 2
  tsteps 20
  tprune 5
    init 1000
bad value: got 1250.000000 expected 1000.000000
realm_stencil: /builddir/build/BUILD/legion-legion-18.05.0/examples/realm_stencil/realm_stencil.cc:379: void check_task(const void*, size_t, const void*, size_t, Realm::Processor): Assertion `false' failed.
*** Caught a fatal signal: SIGABRT(6) on node 0/1
NOTICE: Before reporting bugs, run with GASNET_BACKTRACE=1 in the environment to generate a backtrace. 
```

Plus the `circuit` test fails on aarch64 ppc64 ppc64le s390x see #398.

**Comment by junghans** [comment]
So the big question is, should the legion package be retired?

**Comment by lightsighter** [comment]
Is this crash related to this bug?

https://github.com/StanfordLegion/legion/issues/398

If so, the last time I talked to Sean he said that he had a fix for this
and just hadn't managed to get it into our release yet. Sean is on vacation
this week so we'll have to wait until he gets back to figure out what we
want to do.

Mike

**Comment by junghans** [comment]
> Is this crash related to this bug?

Yes, which is why I mentioned #398 at the end, however the failure on x86_64 is new!

And the issue with `realm_stencil` is new, too.

**Comment by streichler** [comment]
@junghans do we still have failures on any flavor of Fedora with more recent versions of Legion?

**Comment by junghans** [comment]
I think this is fixed.
