### ISSUE TITLE
Adding Printfs Cause Bounds Check Failures in Auto-Parallelized Code

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#410]
Attached in is modified version of the parallelize_tests1.rg test from the Regent test suite. The only modifications are to 

- Run the big test only 
- Not do code generation for OpenMP
- Print out some of the values inside the two stencil tasks

The print statements have exactly the same expressions as the inputs and outputs of the computations being performed. However, putting in the print statements causes a bounds check failure:

tests/regent/run_pass/parallelize_tasks1.rg:58: pointer int2d(fs(), $r#86) is out-of-bounds

Reproduce as follows in the master branch:

SAVEOBJ=1 ./regent.py tests/regent/run_pass/parallelize_tasks1.rg -fbounds-checks 1 -fdebug 1 -fparallelize-dop 5 -fjobs 1 -fvectorize 0

mpirun -n 2 --bind-to none -x LD_LIBRARY_PATH ./parallel1 -ll:cpu 4 -dm:map_locally

Already tried disabling the vectorizer (see command line above) so I don't think that is to blame. My suspicion is that we were getting lucky before with the data placement that allowed us to get the right answer while reading data out of bounds. I'm guessing the bounds checks get turned off by the auto-parallelizer in some way.
[parallelize_tasks1.txt](https://github.com/StanfordLegion/legion/files/2237524/parallelize_tasks1.txt)

**Comment by magnatelee** [comment]
This bug doesn't seem to reproduce anymore. @lightsighter Can you try again and see if it still reproduces for you?

**Comment by lightsighter** [comment]
I've confirmed that this bug is now fixed. Closing.
