### ISSUE TITLE
Support for 4-D Index Spaces

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#412]
We've had a few requests now for support for 4-D index spaces both for machine learning and HPC use cases. We'll use this issue to track requests and progress. Right now we anticipate implementing this sometime in the next 1-2 months (probably after the PPoPP deadline). 

Use cases:
- Machine learning: hwdc
- DOM: angular dimension in addition to three spatial dimensions

Work:
- Realm: expose max dimension template configuration parameter
- Legion: expose max dimension template configuration parameter
- Legion: update all switch statements to be parametrized on max number of dimensions configuration

**Comment by streichler** [comment]
@lightsighter is there anything left to do here?

**Comment by elliottslaughter** [comment]
We haven't added CMake support yet.

**Comment by lightsighter** [comment]
As far as I'm concerned there's nothing left to do on the Legion or Realm side, but @jiazhihao needs to finish his testing to confirm that everything is working.

**Comment by jiazhihao** [comment]
I have changed the DNN application to use 4D index space, and it works with the following changes: https://gitlab.com/StanfordLegion/legion/commit/9a6e198016a50ef14837cb321194e1354153fa4d

Note that all applications I have tested directly use Legion C++ API.

**Comment by elliottslaughter** [comment]
CMake support has been added in master. As far as I know CI still doesn't have any test cases for MAX_DIM > 3.

**Comment by elliottslaughter** [comment]
We now have at least one Regent test with MAX_DIM=4 running it Gitlab.

**Comment by lightsighter** [comment]
Ok, do we have anything else we need to do for this issue? I think we're done.
