### ISSUE TITLE
Non-deterministic reductions in Regent-emitted CUDA tasks

### ISSUE THREAD

**Issue by manopapad** [StanfordLegion/legion#415]
Download minimal counterexample [bug-gpu-nd-reduce.tar.gz](https://github.com/StanfordLegion/legion/files/2264582/bug-gpu-nd-reduce.tar.gz) to sapling, unzip, and run `LEGION_DIR=... [HDF_ROOT=...] ./test.sh`. You will see the result of running the same CUDA reduction 4 times (on 1 tile). It should be the same number all 4 times, but it's not.

**Comment by magnatelee** [comment]
Commit f0c76d1d should fix this issue. @manopapad could you try out the fix and close the issue if it works for you?

**Comment by manopapad** [comment]
Bug fixed!
