### ISSUE TITLE
dma: infinite loop scaling df_attach_subregion_parallel (with partial fix)

### ISSUE THREAD

**Issue by noahdesu** [StanfordLegion/legion#42]
I'm working on scaling the `hdf_attach_subregion_parallel` example. It works fine up until 2^19 elements. When moving to 2^20 elements the dma_thread sits in a CPU bound loop. The following patch fixes the problem, but it seems this solution is only a band aid for scaling. Perhaps the completed requests aren't being reclaimed?

```
diff --git a/runtime/lowlevel_dma.cc b/runtime/lowlevel_dma.cc
index 4645c7e..4888ec4 100644
--- a/runtime/lowlevel_dma.cc
+++ b/runtime/lowlevel_dma.cc
@@ -2759,7 +2759,7 @@ namespace LegionRuntime {
             log_dma.info("create mem->hdf xferdes\n");
             XferDes* xd = new HDFXferDes<DIM>(channel_manager->get_hdf_write_channel(), false,
                                               src_buf, dst_buf, src_mem_base, hdf_metadata,
-                                              domain, oasvec, 100/*max_nr*/,
+                                              domain, oasvec, 500/*max_nr*/,
                                               XferOrder::DST_FIFO, XferDes::XFER_HDF_WRITE);
             path.push_back(xd);
             break;
@@ -2970,7 +2970,7 @@ namespace LegionRuntime {
             XferDes* xd = new HDFXferDes<DIM>(channel_manager->get_hdf_read_channel(), false,
                                               src_buf, dst_buf, dst_mem_base, src_hdf_metadata,
                                               domain, oasvec,
-                                              100/*max_nr*/, Layouts::XferOrder::SRC_FIFO, XferDes::XFER_HDF_READ);
+                                              500/*max_nr*/, Layouts::XferOrder::SRC_FIFO, XferDes::XFER_HDF_READ);
             path.push_back(xd);
             break;
           }
diff --git a/runtime/realm/runtime_impl.cc b/runtime/realm/runtime_impl.cc
index ffc4fe0..68eff83 100644
--- a/runtime/realm/runtime_impl.cc
+++ b/runtime/realm/runtime_impl.cc
@@ -989,7 +989,7 @@ namespace Realm {
 
       // start dma system at the very ending of initialization
       // since we need list of local gpus to create channels
-      LegionRuntime::LowLevel::start_dma_system(dma_worker_threads, 100
+      LegionRuntime::LowLevel::start_dma_system(dma_worker_threads, 500
 #ifdef USE_CUDA
                        ,local_gpus
 #endif
```

**Comment by noahdesu** [comment]
ping @jiazhihao

**Comment by noahdesu** [comment]
What I've found so far is that in the dma thread the finish_xferdes data structure is never populated because is_done on the xferdes is returning false. the bytes_write vs bytes_total used for the is_done determine appear to be stuck at bytes writes: 102400 total: 131072. The kind is XFER_HDF_WRITE.

**Comment by noahdesu** [comment]
@jiazhihao pull requests #29 #40 #43 fix up this problem. please merge them if they look ok.

**Comment by jiazhihao** [comment]
Thanks for pointing out the issue, Noah. I have merged them into dma
branch. Can you still observe finish_xferdes data never being populated
case after this fix? If so, I could dig into that.

Sincerely,
Zhihao

**Comment by noahdesu** [comment]
I don't think it is happening any more. The problem was that is_done was always returning false because the xferdes ran out of requests to reach the total_bytes. i didn't specifically verify that finish_xferdes was being populated, but the the experiments are running and scaling, and there are no hangs.
