### ISSUE TITLE
Vectorizer failure in Soleil-X feat/viz/3 branch

### ISSUE THREAD

**Issue by manopapad** [StanfordLegion/legion#420]
See https://github.com/stanfordhpccenter/soleil-x/issues/3. The failure should be reproducible by checking out Soleil-X commit c61f57d0, following the build instructions and running `USE_CUDA=0 USE_HDF=0 make`.

**Comment by streichler** [comment]
@manopapad, is this still an issue?  If so, we should assign it to somebody. :)

**Comment by manopapad** [comment]
This is still an issue, as far as I know, but @aheirich could comment further. @magnatelee was assigned on the original issue, so I assume he's appropriate for this one as well (but I'm a mere mortal and can't assign work to people).

**Comment by aheirich** [comment]
Yes, this issue continues to hit me whenever I compile Soleil without turning off vectorization.

On Oct 3, 2018, at 11:47 AM, Manolis Papadakis <notifications@github.com<mailto:notifications@github.com>> wrote:


This is still an issue, as far as I know, but @aheirich<https://github.com/aheirich> could comment further. @magnatelee<https://github.com/magnatelee> was assigned on the original issue, so I assume he's appropriate for this one as well (but I'm a mere mortal and can't assign work to people).

**Comment by magnatelee** [comment]
I just assigned this to myself and will probably take a look this week.

**Comment by aheirich** [comment]
works fine now
