### ISSUE TITLE
Memory leak related to OpenMP

### ISSUE THREAD

**Issue by manopapad** [StanfordLegion/legion#424]
To reproduce: download [memory-eater.tar.gz](https://github.com/StanfordLegion/legion/files/2358625/memory-eater.tar.gz), unzip and execute `./run.sh`. Open htop on another window and watch your RAM fill up.

This program runs the same OpenMP loop multiple times. Each time the loop runs, the program keeps accumulating RAM.

**Comment by lightsighter** [comment]
This is a compiler bug. Output from Valgrind proving it:

==18363== 19,199,808 bytes in 99,999 blocks are definitely lost in loss record 87 of 87
==18363==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==18363==    by 0x4055EF: UnknownInlinedFun (memory-eater.rg:13)
==18363==    by 0x4055EF: $__regent_task_10000_primary (std_base.t:918)
==18363==    by 0x72EC47B: Realm::LocalTaskProcessor::execute_task(unsigned int, Realm::ByteArrayRef const&) (proc_impl.cc:945)
==18363==    by 0x736DB20: Realm::LocalOpenMPProcessor::execute_task(unsigned int, Realm::ByteArrayRef const&) (openmp_module.cc:149)
==18363==    by 0x6D574E7: Realm::Task::execute_on_processor(Realm::Processor) (tasks.cc:175)
==18363==    by 0x6D599C7: Realm::KernelThreadTaskScheduler::execute_task(Realm::Task*) (tasks.cc:829)
==18363==    by 0x6D58B27: Realm::ThreadedTaskScheduler::scheduler_loop() (tasks.cc:593)
==18363==    by 0x6D58F57: Realm::ThreadedTaskScheduler::scheduler_loop_wlock() (tasks.cc:697)
==18363==    by 0x6D5E4E9: void Realm::Thread::thread_entry_wrapper<Realm::ThreadedTaskScheduler, &Realm::ThreadedTaskScheduler::scheduler_loop_wlock>(void*) (threads.inl:131)
==18363==    by 0x6D385E3: Realm::KernelThread::pthread_entry(void*) (threads.cc:700)
==18363==    by 0x837B183: start_thread (pthread_create.c:312)
==18363==    by 0x7E9FFFC: clone (clone.S:111)

**Comment by magnatelee** [comment]
This should be fixed as of commit 0f4644a0. @manopapad Could you pull and try again?

**Comment by manopapad** [comment]
Fixed!
