### ISSUE TITLE
Realm Poison Provenance

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#425]
For work on resilience it would really help @karthikmurthy if he could be able to tell where poison came from. This would enable us to restart the mapping process without needing to wait for poison to propagate everywhere when restarting execution. One interesting question is what happens if there is a race between two different poisoned events: does Realm need to report both, or is just reporting the first one to arrive sufficient?

**Comment by streichler** [comment]
@karthikmurthy can you comment on the potential benefit (in development time, or maintainability, or runtime performance, or whatever) of having this feature?  Performance tuning of Realm has been driving us toward making event processing leaner rather than more complicated, so I only want to do something here if it'll have a large benefit on the Legion side.

**Comment by streichler** [comment]
@lightsighter @karthikmurthy Another poke on this.  My inclination is to reject this request under the philosophy that it's the (Realm) application's job to keep track of these things if it wants to, but y'all can take another shot at convincing me otherwise before I pull the trigger.

**Comment by lightsighter** [comment]
I think I mostly agree with your assessment in that the thing we were originally thinking this would be valuable for is not really possible currently. I would still like to hear your question about "racy" poison from different sources. I still think it would useful for example to be able to distinguish between poison coming from a fault versus poison coming from mis-predication or some other source. This is especially true for faults raised directly be Realm, e.g. that it detects from the hardware like ECC faults. I'm still thinking that we want some kinds of flavor to poison, but maybe we should start a new github issue for that since it is different than what we were originally requesting.
