### ISSUE TITLE
Logical operator precedence in Regent is wrong

### ISSUE THREAD

**Issue by manopapad** [StanfordLegion/legion#428]
This code fails:

```
import 'regent'
task main()
  regentlib.assert(true or true and false, '')
end
regentlib.start(main)
```

It seems to be grouping as `(true or true) and false`, instead of the correct  `true or (true and false)`.

**Comment by manopapad** [comment]
2 out of 3 languages agree: `true or true and false = true`:

```
import 'regent'
-- Lua
print(true or true and false)
-- Terra
terra foo() : bool
  return true or true and false
end
print(foo())
-- Regent
task main()
  regentlib.c.printf('%d\n', true or true and false)
end
regentlib.start(main)
```

outputs:

```
true
true
0
```

**Comment by elliottslaughter** [comment]
I decided to go ahead and fix this. Although it's a breaking language change, nothing in the test suite appears to have relied on the old behavior, so it seems worth fixing the paper cut now rather than allowing it to fester.

@manopapad Please confirm.

**Comment by manopapad** [comment]
Fixed!
