### ISSUE TITLE
Make GASNet a private dependency in CMake?

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#435]
I'm opening this issue to discuss a slightly questionable change that I needed to get Legion to build at SLAC. Specifically, the problem we have is that we're using an ephemeral build directory which doesn't exist on the machine where Legion is eventually installed. This is problematic because the CMake build currently bakes the GASNet path into the Legion installation. The GASNet build is also emphemeral. So you can't even build against the resulting binaries if you want to use GASNet, because CMake breaks.

I'm not sure why we even need GASNet to be a public dependency. We statically link GASNet, so the build artifacts are irrelevant once Legion has been linked. I suppose that GASNet can change the link flags and so on, but these could be baked into the installed CMake files without breaking if GASNet was moved or deleted prior to use.

For the moment, I've made an expedient patch which just removes GASNet as a public dependency. I'm intentionally putting this into a branch since I'm not sure if it'll break some of our use cases, especially at LANL. Ideally I'd like to get any potentially impacted users to test this branch before it is committed.

https://gitlab.com/StanfordLegion/legion/commit/7249b2ae58d193652d0ecc43c80008c23e08255d

CC: @junghans @ipdemes

**Comment by junghans** [comment]
On Fedora gasnet is build shared, but then the information is baked into the shared legion library.

But for LANL I am not sure if it will break something, we need to test this!

**Comment by elliottslaughter** [comment]
We merged this some time ago.
