### ISSUE TITLE
Auto-detect PyPy in test suite

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#444]
Currently, Legion Spy tests fail if `pypy` isn't available or on `PATH`. Would be good to auto-detect and call Python for machines that don't have PyPy.

**Comment by elliottslaughter** [comment]
@lightsighter Should be fixed in 2a5cac8f9b6c2de25fbfc07af1f5ea6c825bb64e. Can you confirm?

**Comment by lightsighter** [comment]
Fixed. Closing the issue.
