### ISSUE TITLE
Linking error when building legion-18.09 against gasnet-1.32.0

### ISSUE THREAD

**Issue by junghans** [StanfordLegion/legion#445]
On Fedora rawhide, I get the following linking error:
```
[100%] Linking CXX executable ../../bin/ghost
cd /builddir/build/BUILD/legion-legion-18.09.0/openmpi/examples/ghost && /usr/bin/cmake -E cmake_link_script CMakeFiles/ghost.dir/link.txt --verbose=1
/usr/bin/c++  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-strict-aliasing  -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,--as-needed -rdynamic CMakeFiles/ghost.dir/ghost.cc.o  -o ../../bin/ghost -Wl,-rpath,/builddir/build/BUILD/legion-legion-18.09.0/openmpi/lib:/usr/lib64/openmpi/lib ../../lib/liblegion.so.1 ../../lib/librealm.so.1 /usr/lib64/openmpi/lib/libgasnet-mpi-par.so /usr/lib64/openmpi/lib/libgasnet-mpi-par.so /usr/lib64/openmpi/lib/libammpi.so -lpthread -lrt -Wl,-Bstatic -lgcc -Wl,-Bdynamic -lm /usr/lib64/openmpi/lib/libgasnet_tools-par.so /usr/lib64/openmpi/lib/libmpi.so 
make[2]: Leaving directory '/builddir/build/BUILD/legion-legion-18.09.0/openmpi'
/usr/bin/ld: _gasneti_threadkey_val__gasneti_rwlock_list: TLS definition in /usr/lib64/openmpi/lib/libgasnet_tools-par.so section .tbss mismatches non-TLS definition in //usr/lib64/openmpi/lib/libgasnet_tools-seq-1.32.0.so section .bss
/usr/bin/ld: //usr/lib64/openmpi/lib/libgasnet_tools-seq-1.32.0.so: error adding symbols: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [examples/ghost/CMakeFiles/ghost.dir/build.make:98: bin/ghost] Error 1
make[1]: *** [CMakeFiles/Makefile2:483: examples/ghost/CMakeFiles/ghost.dir/all] Error 2
make: *** [Makefile:144: all] Error 2
```

It seems `libgasnet_tools-par` and `libgasnet_tools-par` both define `gasneti_threadkey_val__gasneti_rwlock_list()` but in an mismatching way, so I guess only one of them should be linked.

Could be a gasnet problem as well, so CC'ing @bonachea and @PHHargrove.

**Comment by streichler** [comment]
From the error message, the linker is somehow trying to bring in both the sequential and parallel GASNet libraries, which is definitely not going to work.  @junghans, can you show how the system gasnet was configured/built and what the cmake setup is for Legion?

**Comment by junghans** [comment]
Sure, [here](https://github.com/StanfordLegion/legion/files/2515952/build_rawhide.txt) is the full build log.

**Comment by streichler** [comment]
Hmm...  Nothing is jumping out at me there.  Can you try legion-18.05.0+GASNet-1.32.0 as well as legion-18.09.0+GASNet-1.30.0?  I don't think we changed anything in the legion build in the last few months, but we're still using GASNet 1.30.0 for our CI runs I think, so there could be an incompatibility with 1.32.0 that we didn't notice.

**Comment by junghans** [comment]
I think it worked with gasnet-1.30, but let me do a rebuild!

**Comment by junghans** [comment]
@streichler, it builds with gasnet-1.30

**Comment by junghans** [comment]
Ok Rawhide (gasnet-1.32) and legion-18.05: https://koji.fedoraproject.org/koji/taskinfo?taskID=30458926

**Comment by junghans** [comment]
Same error with legion-18.05.

**Comment by bonachea** [comment]
I agree with @streichler this definitely looks like a build system problem.

`libgasnet_tools-seq.a`,  `libgasnet_tools-par.a`, and `libgasnet-mpi-par.a` are all mutually exclusive - each of the GASNet conduit libraries implement the GASNet comm API for that backend *and* and the GASNet-tools API. The `gasnet_tools-{seq,par}.a` libraries are for clients who want to use the GASNet tools API **without** a conduit. So any given link/executable should include at most **ONE** library matching `*gasnet*`. The symbols in these libraries may 

Note that GASNet does not support shared libraries at all, so it's possible that @junghans 's shared library wrappers around GASNet are also partially responsible. In particular, note that `libammpi.a` is designed to link with **any** *one* of  `*tools-{seq,par}.a`  or a `libgasnet-mpi-{seq,par}.a` library, so it's possible the shared library wrapper for libammpi is pulling in more shared dependencies than it should (in particular, it should NOT require any specific one of those).

**Comment by junghans** [comment]
@bonachea, the [fedora packaging guide](https://fedoraproject.org/wiki/Packaging:Guidelines#Packaging_Static_Libraries) is pretty clear about static libraries, which is why I had to wrap them, if you have a better solution I am happy to push it into fedora.

@streichler Another solution would be, of course, to not build Legion without Gasnet support. Or to drop Legion from Fedora.

**Comment by junghans** [comment]
[Bundling](https://fedoraproject.org/wiki/Packaging:Guidelines#Bundling_and_Duplication_of_system_libraries) is an issue in itself, so let's try the static route.

**Comment by junghans** [comment]
I think, that fixed it!

**Comment by junghans** [comment]
@nmorey, I guess you will have to do the same for OpenSuse.
