### ISSUE TITLE
Optional Subscribe Parameter to 'has_triggered' in Realm

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#447]
Add an optional boolean parameter to request that has_triggered subscribe to event triggering notifications on remote nodes.

**Comment by streichler** [comment]
@lightsighter is this still needed if we have the completion queue thing that I really need to get around to writing up?

**Comment by lightsighter** [comment]
Yes, we still need this for when I do tests for has_triggered on remote nodes. It's unrelated to the completion queue changes.

**Comment by streichler** [comment]
@lightsighter can you describe the use case again please?

**Comment by lightsighter** [comment]
There were two use cases. One is that I could simplify the shutdown algorithm by being able to get rid of comments like this:
https://gitlab.com/StanfordLegion/legion/blob/master/runtime/legion/runtime.cc#L5751-5753
The other is that I can filter events for out-of-order message delivery. I could maybe do this second one with a completion queue, although I need to be able to see message completions out of order to avoid deadlock in some cases which maybe doesn't align with the completion queue semantics.
https://gitlab.com/StanfordLegion/legion/blob/nopaint/runtime/legion/runtime.cc#L6070-6098

**Comment by streichler** [comment]
@lightsighter can you fix the above code references - neither points to the right place anymore, so I don't remember which comments you're referring to.  (If you look at a particular commit rather than just the branch, the URL doesn't go stale.)

**Comment by lightsighter** [comment]
Look for the calls to has_triggered in runtime.cc in this commit:
https://gitlab.com/StanfordLegion/legion/commit/d0f7897b09

**Comment by streichler** [comment]
Commit 7b8c0d24 adds `Event::subscribe` (rather than an argument to `has_triggered`).  Assigning @lightsighter to give it a try and make sure it has the desired impact on the Legion side.

**Comment by lightsighter** [comment]
Do I need to go through and put subscribe calls in all the places where I know that I've got a local event already? How much will the overhead of doing a subscribe call cost me? What happens if I do it repeatedly on the same event?

The bad news is that it looks like the two places where I wanted to use this originally either can't be fixed by this or are better served by completion queues. I still have this problem, and it looks like this doesn't actually solve it because I know the event is local, it's just that the runtime is faster at checking things than a round-trip message latency:
https://gitlab.com/StanfordLegion/legion/blob/master/runtime/legion/runtime.cc#L6135-6138
The other case of the out-of-order message queues is better served with a completion queue, so I'm going to put that in.

**Comment by streichler** [comment]
The only place you _have_ to put `subscribe` calls is where you constantly check `has_triggered` with the expectation that it'll eventually become true all by itself, and for those, I'd recommend doing it even if you know/think the event is local.  (The definition of "local" could theoretically change in a subprocess world.)  The `subscribe` call has a fast path (no memory references, let alone mutexes) for calls made on NO_EVENT or local generational events.

For cases where you're looking for the latency improvement of subscribing before you actually create a dependency on the event, it's fine to only do it when/where you expect the event to be remote.

**Comment by lightsighter** [comment]
Ok, I've added the needed subscribe calls for the shutdown process with 8061a647e. Once it passes the CI I think we can close this issue.
