### ISSUE TITLE
Overzealous malloc result checks in Regent

### ISSUE THREAD

**Issue by streichler** [StanfordLegion/legion#449]
Regent's code is littered with snippets like this:
```
    var [buffer] = c.malloc([size])
    std.assert([buffer] ~= nil, "malloc failed in setup task args")
```
(https://gitlab.com/StanfordLegion/legion/blob/32157fa0001c88640a6a2a9c7f496606be4d85d3/language/src/regent/codegen.t#L2428-2429)

These asserts suffer false positives when used with a malloc implementation that (legally) returns null for zero-sized allocations.

**Comment by elliottslaughter** [comment]
Should be fixed in 7cbc8f2.
