### ISSUE TITLE
Postfix increment in iterators should return value before advancing

### ISSUE THREAD

**Issue by rauteric** [StanfordLegion/legion#451]
In the iterators `DomainPointIterator`, `PointInRectIterator`, `RectInDomainIterator`, and `PointInDomainIterator` (and perhaps others), the postfix increment operator (`operator++(int)`) is implemented as a prefix increment, i.e., by advancing the iterator and then returning. An example for PointInRectIterator is [here](https://github.com/StanfordLegion/legion/blob/be7a87c13275874e3e21995efa52524451b43663/runtime/legion/legion_domain.inl#L1453-L1460).

It seems that the proper thing to do here would be to create a copy of the original iterator, increment the original, and then return the copy, as is typically done for postfix increment.

**Comment by lightsighter** [comment]
Should be fixed in the master branch of Legion on gitlab. Here's the commit:

https://gitlab.com/StanfordLegion/legion/commit/7610005065e7f0092310459197bcf17fd1241207

It'll make it's way here to github after passing CI.

**Comment by lightsighter** [comment]
Closing this issue now that CI has passed.
