### ISSUE TITLE
Spurious "uninitialized data" warnings on Regent-emitted initialization tasks with DCR

### ISSUE THREAD

**Issue by manopapad** [StanfordLegion/legion#458]
In Soleil we have a number of initialization tasks that look like this:

```
task Particles_initValidField(Particles : region(ispace(int1d), Particles_columns))
where writes(Particles.__valid) do
  for p in Particles do
    Particles[p].__valid = false
  end
end
```

When we run on the `control_replication` branch, we get a lot of warnings like this:

```
[0 - 20001bd0f0e0] {4}{runtime}: [warning 1071] LEGION WARNING: Region requirement 0 of operation Particles_initValidField.parallelized (UID 765) in parent task workSingle (UID 3) is using uninitialized data for field(s) 117 of logical region (294,3,3) (from file /usr/WS2/mpapadak/legion/runtime/legion/region_tree.cc:12341)[warning 1071] 
For more information see:
http://legion.stanford.edu/messages/warning_code.html#warning_code_1071
```

The reason why we see this is because Regent is conservative with how it propagates privileges to Legion. Here are the current possibilites:

Regent privilege | Can do `x = r[i].f`? | Can do `r[i].f = x`? | What Legion sees
-------|---------|--------|-----------
`reads(r.f)` | yes | no | `reads(r.f)`
`reads writes(r.f)` | yes | yes | `reads writes(r.f)`
`writes(r.f)` | no | yes | `reads writes(r.f)`

The pertinent line is the last one: Regent chooses to propagate `reads writes(r.f)`, because Legion understands `writes(r.f)` to mean that the previous contents of `r.f` are discarded, and not all tasks that do `writes(r.f)` will necessarily want to override every element of `r.f`.

The problem now is that Legion's privilege analysis has evolved to the point where it can detect that our initialization functions are called with Legion-level `reads writes` privileges, but have uninitialized data.

On thing we could do to fix this is to add support for `writes discards` privileges to Regent, i.e. grow the table above to:

Regent privilege | Can do `x = r[i].f`? | Can do `r[i].f = x`? | What Legion sees
-------|---------|--------|-----------
`reads(r.f)` | yes | no | `reads(r.f)`
`reads writes(r.f)` | yes | yes | `reads writes(r.f)`
`writes(r.f)` | no | yes | `reads writes(r.f)`
`writes discards(r.f)` | no | yes | `writes(r.f)`

Two issues I can see immediately with this feature:
* We might want to warn the programmer that, unless they set the entire discarded region, they will have undefined behavior. I bet we could even statically discharge this warning on 95% of cases by doing a simple check against the pattern `for r in region do r.f = ... end`.
* It's unclear how to handle array-typed fields that are set index-by-index, i.e. `r.f[0] = 0.0; r.f[1] = 0.0` instead of `r.f = array(0.0,0.0)` (also see #436).

**Comment by elliottslaughter** [comment]
My understanding was that Legion never issues warnings for READ_WRITE privilege, only for READ_ONLY privilege, in part to avoid false positives like this. @lightsighter can you confirm?

**Comment by lightsighter** [comment]
@elliottslaughter We issue warnings for READ_WRITE privileges and we issue errors for READ_ONLY privileges.

**Comment by lightsighter** [comment]
It's worth noting this doesn't have anything to do with control replication. @manopapad would have this same problem if he ran this code in nopaint too (soon to be master). It is an effect of the decision we made at a weekly meeting a few months ago that read-write privileges on uninitialized data would result in a warning from the runtime. We can revisit it if we want, but we collectively as a group decided that this is the behavior that we wanted.

**Comment by elliottslaughter** [comment]
I'm going to close this issue in favor of #721, which I've created to track progress on `discard`.
