### ISSUE TITLE
bad values printed by C.printf from Regent code

### ISSUE THREAD

**Issue by aheirich** [StanfordLegion/legion#459]
Here is sample output from this program:
Grid_xBnum 1
Grid_xOrigin 0 + (Grid_xWidth 6.28319 / Grid_xNum 64) * (c.x -0.0490874 - Grid_xBnum 0 + 0.5) = -0.0490874
Grid_xBnum 1 c.x 6.28319 Grid_xNum 0 Grid_xWidth 0 Grid_xOrigin 0
--- Grid_xBnum 1 result -0.0490874
--- cxyz -0.0490874 0 0

Notice that this reports various values, for example Grid_xBnum is report as 0 and 1, c.x is reported as -0.0490874 and 6.28319.  The offending code is here

C.printf("Grid_xOrigin %lg + (Grid_xWidth %lg / Grid_xNum %d) * (c.x %lg - Grid_xBnum %d + 0.5) = %lg\n",
Grid_xOrigin, Grid_xWidth, Grid_xNum, c.x, Grid_xBnum, centerCoordinates[0])
C.printf("Grid_xBnum %d c.x %lg Grid_xNum %d Grid_xWidth %lg Grid_xOrigin %lg\n",
Grid_xBnum, c.x, Grid_xNum, Grid_xWidth, Grid_xOrigin)
C.printf("--- Grid_xBnum %d result %lg\n", Grid_xBnum, centerCoordinates[0]);
C.printf("--- cxyz %lg %lg %lg\n", c.x, c.y, c.z)

You can see that there is a bug in the C.printf invocations.

bug.rg is the source program
bugr.cpp is a stub
Here is the corresponding Makefile content

bug.exec: bug.o config_schema.o json.o bugr.o
	$(CXX) -o $@ $^ $(LINK_FLAGS)

bug.o:	bug-desugared.rg
	$(REGENT) bug-desugared.rg $(REGENT_FLAGS)

bugr.o:	bugr.cpp
	$(CXX) -c -o $@ $^

use runbug.bash to run the program

**Comment by aheirich** [comment]
source files have been put in a soleil-x branch
https://github.com/stanfordhpccenter/soleil-x/tree/github_issues_459/src

**Comment by elliottslaughter** [comment]
I'm getting this error when I build:

```
g++ -o bug.exec bug.o config_schema.o json.o bugr.o -L/home/elliott/legion/bindings/regent -lregent -lhdf5_serial -lm -L/src -lImageCompositor
/usr/bin/ld: cannot find -lImageCompositor
collect2: error: ld returned 1 exit status
```

**Comment by elliottslaughter** [comment]
Update on the fix for this issue:

There were two bugs in the printf format specifiers in the code:

  * The code used `%lg` (`long double`) but the argument was a `double`. Fix was to change to `%g`.
  * The code used `%lg` for `c.x`, which had type `int64`. Fix was to change to `%ld`.

I've made a bug here to track the addition of checks that would have caught these bugs: https://github.com/StanfordLegion/legion/issues/460

**Comment by elliottslaughter** [comment]
Minor correction: `%lg` is actually the same as `%g`; both use type `double`. I made a mistake reading the man page and only `%Lg` is `long double`.
