### ISSUE TITLE
Statically check type arguments to printf calls in Regent

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#460]
Currently Regent does not check the types of arguments to printf calls, even when the format string is known at compile time. If the user makes a mistake in the format specifiers, bad values will be printed out. Modern C++ compilers have some checking for this, and it would be good to add it to Regent as well.

**Comment by manopapad** [comment]
Here's some code I wrote today that would have benefited from this check:

```
local task printValues(rakes : region(ispace(int1d),double))
where
  reads(rakes)
do
  for v in rakes do
    regentlib.c.printf('%lf\n', v)
  end
end
```

In this case I was assuming that `v` would get replaced automatically with `rakes[v]`, but `printf` doesn't contain enough type information for the compiler to realize it should do this. Instead `v` here is `int64`, and this gets printed wrong with `%lf`.

**Comment by elliottslaughter** [comment]
Regent's native `format.println` is now complete enough that I'm just going to say people should use that instead. If there are any specific limitations of `format.println` or new feature requests, those can be added as new issues.
