### ISSUE TITLE
Regent: Support for index fills

### ISSUE THREAD

**Issue by manopapad** [StanfordLegion/legion#470]
Regent currently only supports full-region fills, which cause a lot of metadata movement in DCR. The compiler should recognize this code pattern:
```
for c in tiles do
  fill(p[c].foo, 42)
end
```
and emit index fills.

**Comment by elliottslaughter** [comment]
Assigning @magnatelee to confirm completion of fix.

**Comment by magnatelee** [comment]
My initial attempt to clean up regions and other handles when the task exits did not go through well. A cursory look at the issue seems to suggest that some of the handles are being deleted directly by the runtime. I'll open a separate issue for that and close this one.
