### ISSUE TITLE
Regent: build failure with cmake and llvm

### ISSUE THREAD

**Issue by mpokorny** [StanfordLegion/legion#475]
Building Regent using with "--cmake --llvm" flags results in an unusable version of Regent. The resulting Regent fails as follows, for example:
``` shell
$ ./regent.py examples/circuit.rg
terra: CommandLine Error: Option 'asan-instrument-assembly' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```
I built Terra separately from Regent from its github master branch using cmake, and am using that for the Regent build. The Terra build passes all its tests. I'm also using the github master branch of Legion. Without the "--llvm" flag, the build is successful in this configuration.

**Comment by streichler** [comment]
@mpokorny, by default, Terra only includes the few pieces of LLVM it needs, which is not sufficient for Regent.  As a result, the linker brings in another whole copy of LLVM and you get errors like this.  If you build Terra separately from Regent, adding `REEXPORT_LLVM_COMPONENTS='irreader mcjit x86'` to the Terra build command should do the trick.

**Comment by elliottslaughter** [comment]
I don't believe the CMake build of Terra currently supports `REEXPORT_LLVM_COMPONENTS` so at the moment you would need to build Terra with Make to get this to work.

**Comment by mpokorny** [comment]
Thanks for the hint, @streichler. @elliottslaughter, yes, I had noticed that. I
initially was having trouble with the Make build of Terra, so I tried the CMake
build, and that worked. I have now worked around my Terra Make build issue
(libcurses linking issue) so I ought to be able to use that with Regent.
Unfortunately, the end result for Regent is unchanged. I fell back to letting
Regent build Terra, but I still encounter the same problem. For reference, I'm
using llvm 6.0.1. At the moment, llvm isn't critical for me, so I can continue
to make progress on my application without it.

**Comment by ProfFan** [comment]
@streichler @elliottslaughter I've encounter the same issue with Opt that I solved by building Terra with dynamically-linked LLVM. Could Regent be built with dynamic linking as well?

**Comment by elliottslaughter** [comment]
Regent could use a Terra that is dynamically linked, and we could probably get Legion to link the same LLVM. I'm not sure whether Legion itself supports dynamic linking of LLVM at the moment, but it could probably be done with some effort. (Regent itself doesn't link LLVM except through Terra/Legion.)

**Comment by streichler** [comment]
Commit 000fbd4 should take care of this.  @mpokorny when you have a moment, can you give this another try?

**Comment by mpokorny** [comment]
Your commit has fixed this issue for me.

I do have one question, though. If I wanted to build a shared library version of librealm.so for use both from Regent or my own C++ application, would your changes support that? Although I'm a bit unclear on the details, it seems that without Terra (which has the "missing" LLVM libraries), if I built a C++ application that depended on LLVM against librealm.so, it might fail unless the application explicitly linked the missing libraries. My question is purely hypothetical, as I don't have such C++ code at present. It's OK with me for you to close this issue; I can mull over the hypothetical case some other time and open a new issue if it's needed.

**Comment by streichler** [comment]
The cases you describe should work.  What we're doing in the regent+llvm case is that Realm is not linking in llvm libraries directly.  Instead, it does dynamic symbol lookup at runtime to find the copy of the llvm libraries that some other component has loaded in (either via linking or dynamic loading itself).  As long as that other component has linked in enough of llvm (currently we require the mcjit, irreader, and the appropriate native processor backend (e.g. x86) components), that's good enough for Realm.

**Comment by elliottslaughter** [comment]
I would also point out that Terra can be made to dynamically link LLVM (though you currently have to build Terra yourself to get this).

**Comment by streichler** [comment]
@mpokorny I am going to go ahead and close this bug, but if you run into any new build issues in this area, please let us know.  Thanks!
