### ISSUE TITLE
Regent Type Checker Should Disallow Passing Contexts By-Value Between Tasks

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#478]
The Regent type checker should not allow objects with context types to be passed by value between tasks which can cause correctness issues with the runtime. Here is an example test case that I had to fix which demonstrates the problem.

https://gitlab.com/StanfordLegion/legion/commit/47ee22c47ecc44caf93eca23b9ff5cdbb2bfd810

I suppose it would be ok to do this if you force inlining of the called task, but otherwise it is unsafe and can lead to things like hangs in the runtime.

**Comment by lightsighter** [comment]
Actually passing the runtime by value is also bad since the task could be moved to a different node and then we'll get a segfault. I'll fix the test case so it doesn't do that, but it would be good if the compiler type checker prohibited that case as well.

**Comment by elliottslaughter** [comment]
There is no reason to explicitly pass a runtime or context to a task, even if it's inlined, because you can always request it again by calling `__runtime()` or `__context()`. Let's just disallow this. (Though note, the compiler cannot possibly catch every possible instance of this, there will still be ways to work around it.)

**Comment by magnatelee** [comment]
The test meant to use a terra function (just like the other import tests), but somehow was doing it in a task. I'll add a simple check for this to the type checker.

**Comment by magnatelee** [comment]
I pushed commits baf63c6c and eaeaf6e8 for the check. The type checker will now reject a task if it gets either runtime or context object as argument, and raise a warning if any of the parameters has a raw pointer type. @lightsighter Feel free to close the issue if you're satisfied with these changes.

**Comment by lightsighter** [comment]
Works for me.
