### ISSUE TITLE
legion-18.05.0 : /.../threads.cc:1413:5: error: hwloc_linux_parse_cpumap_file was not declared in this scope

### ISSUE THREAD

**Issue by junghans** [StanfordLegion/legion#479]
```
/var/tmp/portage/sys-cluster/legion-18.05.0/work/legion-legion-18.05.0/runtime/realm/threads.cc: In function ‘bool Realm::get_bd_sibling_id(int, int, std::set<int>&)’:
/var/tmp/portage/sys-cluster/legion-18.05.0/work/legion-legion-18.05.0/runtime/realm/threads.cc:1413:5: error: ‘hwloc_linux_parse_cpumap_file’ was not declared in this scope
     hwloc_linux_parse_cpumap_file(f, set);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/portage/sys-cluster/legion-18.05.0/work/legion-legion-18.05.0/runtime/realm/threads.cc:1413:5: note: suggested alternative: ‘hwloc_linux_set_tid_cpubind’
```

Details here: https://bugs.gentoo.org/677616

**Comment by streichler** [comment]
@junghans what version of hwloc is this build attempting to use?  The realm code here hasn't changed in a very long time.

**Comment by junghans** [comment]
hwloc-2.0.2

**Comment by junghans** [comment]
A version bump to 18.12.0 might fix the issue!

**Comment by streichler** [comment]
I doubt changing the Legion version will help.  As I mentioned, the code in question hasn't changed in a long time.  However, what has changed is the hwloc API.  Version 2.x appears to have a number of backwards-incompatible changes compared to 1.x.  Can you build Legion against a 1.x version of hwloc instead?

**Comment by junghans** [comment]
Well, Gentoo is in the process of rolling out hwloc-2! So, we could disable the support for hwloc or drop legion from Gentoo completely.

However, Fedora and others will roll out hwloc-2 in not too long as well.

**Comment by junghans** [comment]
Ok, I required `<hwloc-2` in Gentoo now:
https://github.com/gentoo/gentoo/commit/f3f448a49d7354b32e32005308fbaad34bb72404

So I leave this issue for a future release to be fixed!
