### ISSUE TITLE
Regent: stop field-splicing complex

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#480]
Currently the `complex` type in Regent is being field sliced into its `real` and `imag` components. This makes it impossible to implement reductions correctly for `*` and `/`. In order to fix these reductions it is necessary to stop field slicing the complex type.

**Comment by elliottslaughter** [comment]
Assigning @magnatelee because I need help figuring out if the vectorizer needs to be changed to deal with this.

**Comment by magnatelee** [comment]
This should be fixed as of 271b6774. Field slicing is now turned off for any structs having `__no_field_slicing` true, including the complex type. (Vectorization is also temporarily turned off for complex types, which I will fix later.) @elliottslaughter Feel free to close this issue once you confirm the fix.
