### ISSUE TITLE
Regent: variable has incorrect value in inlined task

### ISSUE THREAD

**Issue by sparkasaurusRex** [StanfordLegion/legion#489]
I ran into some unexpected behavior when adding ``__demand(__inline)`` to a task. I was able to write a minimal regent program that shows the bug.

```
import "regent"

__demand(__inline)
task foo()
  var result : double
  if true then
    var x : double = 1234 -- A fix is to declare `x` outside the if statement
    result = x
    regentlib.c.printf("x = %f (should be 1234)\n", x)
  end
  return result
end

task toplevel()
  var result : double = foo()
  regentlib.c.printf("foo() = %f\n", result)
end

regentlib.start(toplevel)
```

I ran it with
```
docker run -ti -v $PWD:/bug stanfordlegion/regent regent /bug/bug.rg
```
And this was the output
```
x = 0.000000 (should be 1234)
foo() = 1234.000000
```

Without ``__demand(__inline)`` the task works perfectly. It also works if your replace ``double`` with ``int`` or if you declare ``x`` outside the if statement.

**Comment by magnatelee** [comment]
This bug doesn't seem to reproduce even on the stable branch. Which commit are you on? Could you pull and try again?

**Comment by sparkasaurusRex** [comment]
I have been working on the version used by Docker. It seems like there are several issues with that version...
I've updated to the latest version of Regent and every thing is working. Thanks!

**Comment by elliottslaughter** [comment]
It looks like our automated Docker builds started failing silently about 9 months ago. I manually pushed an updated build, but given that we didn't even get a notification that the build was failing, perhaps we should remove mentions of Docker from the Regent website completely until we can find a better solution for automated builds.

**Comment by sparkasaurusRex** [comment]
Using Docker was super convenient for getting starting on my project. I would recommend keeping it available and maybe adding a warning that it may be a broken version.
