### ISSUE TITLE
Compilation issue with -DLEGION_IDS_ARE_64BIT

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#49]
I see some compilation issues with the general low-level runtime due to active message arguments being larger than 64 bytes when compiling with the -DLEGION_IDS_ARE_64BIT.  It should happen when trying to compile any program with GASNet enabled.  The active message arguments need 18 4-byte words, but a maximum of 16 are supported by GASNet.  Here is an example error message:

In file included from /home/mebauer/extern_legion/legion/runtime/activemsg.h:22:0,
                 from /home/mebauer/extern_legion/legion/runtime//realm/runtime_impl.h:24,
                 from /home/mebauer/extern_legion/legion/runtime//realm/runtime_impl.cc:18:
/home/mebauer/extern_legion/legion/runtime/activemsg.h: In instantiation of ‘static int ActiveMessageMediumNoReply<MSGID, MSGTYPE, FNPTR>::add_handler_entries(gasnet_handlerentry_t*, const char*) [with int MSGID = 201; MSGTYPE = LegionRuntime::LowLevel::RemoteFillArgs; void (* FNPTR)(MSGTYPE, const void*, size_t) = LegionRuntime::LowLevel::handle_remote_fill; gasnet_handlerentry_t = gasneti_handlerentry_s]’:
/home/mebauer/extern_legion/legion/runtime//realm/runtime_impl.cc:421:36:   required from here
/home/mebauer/extern_legion/legion/runtime/activemsg.h:615:18: error: invalid application of ‘sizeof’ to incomplete type ‘ActiveMessageMediumNoReply<201, LegionRuntime::LowLevel::RemoteFillArgs, LegionRuntime::LowLevel::handle_remote_fill>::MessageRawArgsType {aka MessageRawArgs<LegionRuntime::LowLevel::RemoteFillArgs, 201, dummy_short_handler<LegionRuntime::LowLevel::RemoteFillArgs>, LegionRuntime::LowLevel::handle_remote_fill, 18>}’
     assert(sizeof(MessageRawArgsType) <= 64);  // max of 16 4-byte args
                  ^
In file included from /home/mebauer/extern_legion/legion/runtime//realm/runtime_impl.h:24:0,
                 from /home/mebauer/extern_legion/legion/runtime//realm/runtime_impl.cc:18:
/home/mebauer/extern_legion/legion/runtime/activemsg.h:617:22: error: incomplete type ‘ActiveMessageMediumNoReply<201, LegionRuntime::LowLevel::RemoteFillArgs, LegionRuntime::LowLevel::handle_remote_fill>::MessageRawArgsType {aka MessageRawArgs<LegionRuntime::LowLevel::RemoteFillArgs, 201, dummy_short_handler<LegionRuntime::LowLevel::RemoteFillArgs>, LegionRuntime::LowLevel::handle_remote_fill, 18>}’ used in nested name specifier
     entries[0].fnptr = (void (*)()) (MessageRawArgsType::handler_medium);

**Comment by streichler** [comment]
Fixed with 3aee202.
