### ISSUE TITLE
Legion: Check the value of flags in the environment, don't just check if they're defined

### ISSUE THREAD

**Issue by manopapad** [StanfordLegion/legion#490]
It is confusing if I run this and actually do get a Realm backtrace:

```
REALM_BACKTRACE=0 ./myapp
```

This particular example is also incosistent with the behavior of `GASNET_BACKTRACE`.

This issue also applies to (at least) `LEGION_FREEZE_ON_ERROR`.

**Comment by lightsighter** [comment]
Should be fixed with 1cc59d526

**Comment by manopapad** [comment]
Fixed
