### ISSUE TITLE
Realm Needs Support for OpenMP Thread Single and Barrier

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#492]
The following call to parallel sort causes link errors with Realm's implementation of OpenMP:

#include <parallel/algorithm>

{
   ...
   __gnu_parallel::sort(ptr, ptr+volume);
   ...
}

/gpfs/sw/software/GCCcore/5.4.0/include/c++/5.4.0/parallel/multiway_mergesort.h:421: error: undefined reference to 'GOMP_single_start'
/gpfs/sw/software/GCCcore/5.4.0/include/c++/5.4.0/parallel/multiway_mergesort.h:421: error: undefined reference to 'GOMP_barrier'

**Comment by streichler** [comment]
This should hopefully work with commit 047b2f2.  Assigned to @lightsighter to verify that things work as expected.

**Comment by lightsighter** [comment]
Seems to work, so closing this for now.
