### ISSUE TITLE
Regent: Better error message when CUDA is disabled

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#495]
Currently if you `__demand(__cuda)` without having CUDA enabled you get an error message like:

```
examples/stencil_fast.rg:420: ignoring demand pragma at examples/stencil_fast.rg:420 since the CUDA compiler is unavailable
```

The problem with this message is you can't tell *why* CUDA is disabled. There are several options and you have to manually check which is the case:

  * Terra could have been compiled without CUDA support (e.g. `CUDA_HOME` not set at build time, or `CUDA_HOME` does not exist on the filesystem).
  * Terra could fail to find `libnvvm.so` at runtime (note: results in `terralib.cudaloaderror` being set, see: https://github.com/zdevito/terra/blob/master/src/tcuda.cpp#L325).
  * The `-fcuda 1` flag may be missing.
  * The `cuInit` symbol may be missing, for whatever reason.
  * `cuInit` is defined but calling `cuInit(0)` fails.

We should add a more detailed message so the user can determine which of these is the case when CUDA is disabled.

**Comment by magnatelee** [comment]
I agree, and I believe OpenMP has the same issue of not telling why it is disabled. I'll try to improve both of them.

**Comment by elliottslaughter** [comment]
I added a note about an additional failure mode for Terra.

**Comment by magnatelee** [comment]
Commit d444f10e should address this issue. Now the compiler reports the following failure modes for CUDA and OpenMP:

CUDA
- `Terra is built without CUDA support`
- `CUDA code generation is turned off (-fcuda 0)`
- `calling cuInit(0) failed for some reason (CUDA devices might not exist)`
- `the cuInit function is missing (Regent might have been installed without CUDA support)`

OpenMP
- `OpenMP code generation is turned off (-fopenmp 0)`
- `Regent is installed without OpenMP support`

I didn't handle the case when Terra failed to find NVVM, as the Regent compiler doesn't seem to have control when that happens. 

@elliottslaughter Feel free to close the issue if you think this is good enough.

**Comment by elliottslaughter** [comment]
Sounds good, thanks.
