### ISSUE TITLE
Automatic generation of defines under all build systems

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#496]
Currently users of Legion have no way to detect the set of defines that have been used to build Legion. Because certain defines impact Legion's public interface, this means that users such as Regent or Python that include `legion.h` dynamically are forced to reverse engineer Legion's build settings in order to be able to safely include `legion.h`.

The most noticeable case where this exists today is when using support for > 3 dimensions (#412, #467), but the problem is more general than that and occurs for the `DEBUG` flags and any other variables that impact the public API.

I propose that the most consistent way to solve this problem is to unconditionally generate `legion_defines.h`/`realm_defines.h` and to include them from `legion_config.h`/`realm_config.h`, which should result in it being transitively included by all headers. The good news is that this is already the case for CMake, so the only thing we need to do here is to add it to the traditional Makefile build system. At that point we'll have parity across both builds and we can make the include of `legion_defines.h` unconditional. At that point we can remove the defines from `CC_FLAGS` (as they'll be redundant) and users should notice no difference, except that Regent and Python will automatically pick up the right set of flags.

A couple points that require some care:

 1. We should be careful to generate `legion_defines.h` out of tree. We already get into enough trouble with in-tree object files, we shouldn't be generating in-tree source files as well.

 2. We probably want to tweak the CI so that it prints the contents of `legion_defines.h` at the start of the build. Right now we can check the defines by scanning the commands generated by Make, but we won't be able to do that once the defines are put into a file. This is a sanity check to make sure we don't accidentally collapse our build matrix by forgetting to set the right flags.

**Comment by mariodirenzo** [comment]
For the specific case of the maximum number of dimensions, it would be good to say on the legion and regent websites to export the variables `REALM_MAX_DIM` `LEGION_MAX_DIM` in the environment where the regent code and its mapper are compiled.
It is a temporary solution but would avoid a lot of pain to the users.
Personally, I did not see this issue and I have spent, together with Mike, two days to figure out what was happening in my code.

**Comment by lightsighter** [comment]
We now have a way to do this in the Makefile build system and the files are generated out of tree, so each application will get its own. One downside is that file generation requires lots of file open/close operations currently and all those system calls take forever in the CI containers. The CMake build system already generates the define files, but does so in-tree. @elliottslaughter what do you think the next step is?

**Comment by elliottslaughter** [comment]
We'll want to make it efficient enough that we're happy turning it on by default, and then (to be sure it's working) we'll need to disable adding any such flags to `CC_FLAGS`. At that point, assuming everything is still working, this problem should just go away for all of our users.

**Comment by lightsighter** [comment]
What about the issue of cmake generating the files in the tree?

**Comment by lightsighter** [comment]
I think it was only very inefficient when we were running in docker containers for CI. I wasn't seeing any real issues on my laptop or native linux systems. But the system call overhead of all the line by line writes in docker containers was causing most of our jobs in the CI to timeout. I'm not particularly excited about figuring out how best to fix this. I also didn't spend much time trying to get make to build the files more efficiently though. It's likely there is some simple workaround.

**Comment by elliottslaughter** [comment]
Ok, I'm not sure when I'll get around to this, but assigning back to myself for now.

**Comment by elliottslaughter** [comment]
An improved version is sitting in branch `makefile-defines`. If people are happy with it we can merge and close this issue.

**Comment by elliottslaughter** [comment]
This has been merged in ff00fb898db725ec0abb6ce804ff1efb9461e161.

**Comment by mariodirenzo** [comment]
Is it possible to keep the flag `-flegion-dim` among the possible options or Regent for a couple of months (at least for the `parallelizer-dcr` branch)?
I have submitted a version of my solver for publication before this change was applied and now that version produces the error `language/src/common/config.t:112: unknown option -flegion-dim`
