### ISSUE TITLE
Realm: Better error checking in -DTRACE_MESSAGES

### ISSUE THREAD

**Issue by manopapad** [StanfordLegion/legion#498]
E.g. check that file opening succeeded: https://gitlab.com/StanfordLegion/legion/blob/c4d119d2249b9d5811f6982789e5bdbf95182e5f/runtime/realm/activemsg.cc#L2232

**Comment by streichler** [comment]
Commit d8d4a2b7 should clean this up.  @manopapad feel free to check this your self and/or close the bug based on your trust level.  :)

**Comment by manopapad** [comment]
I trust you :)
