### ISSUE TITLE
RFC: Deprecate multi-field expansion in Regent

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#501]
This RFC proposes to deprecate the multi-field expansion syntax in Regent, so that it can lead to more natural usage of region-based operators like fills and copies, and potentially in the eventual future, field projection and renaming in task calls.

## Multi-field expansion

Regent currently supports the following syntax (which is what we're proposing to deprecate):

```
x.{a, b, c} = y.{d, e, f} * z
```

Which expands into three statements:

```
x.a = y.d * z
x.b = y.e * z
x.c = y.f * z
```

This syntax has been around for a while, but it's rarely used, and the main use case I'm aware of (MiniAero) has been changed to use field arrays instead.

## Region-based operators

At the moment, the presence of multi-field expansion causes the syntax of certain region-based operators (namely fills and copies) to be suboptimal. For example:

```
fill((p[i]).{a, b, c}, 0)
```

The parens around `(p[i])` are mandatory because otherwise there would be ambiguity in the grammar between these and multi-field expansion. The above syntax may look superficially similar, but they have different capabilities: in fills, it's possible (and sometimes necessary) to name nested fields (i.e., `fill(r.{a.{b, c}, d.{e, f}}, 0)` which results in four fills to `a.b`, `a.c`, `d.e` and `d.f`) whereas multi-field expansion supports cross-product expansion (i.e. `x.{a, b, c}.{d, e, f} = ...` will issue assignments to a total of 9 fields: `a.d`, `b.d`, `c.d`, `a.e`, and so on).

Given that multi-field expansion is rarely used anyway, by far the easiest solution is to deprecate it, allowing region-based operators to be used straightforwardly with no ambiguity. As a bonus, this would open the door to the possibility that we could use a similar syntax with tasks (e.g. for field projection and/or renaming), which is currently outright impossible.

This will have an increasing impact going forward, because Regent will soon support index fills (and possibly index copies). Having a syntax which essentially mandates the use of parentheses seems like poor usability in general.

## Deprecation plan

We're not expecting much impact from the deprecation of this feature, as most users are not even aware that it exists. However, out of an abundance of caution, we're taking a staged approach to deprecation.

Stage 1. This RFC will be publicly posted prior to any code changes being made. During this phase we'll audit all major, publicly available Regent programs to make sure they're not impacted. We may add an opt-in warning at the point just to make it easier to check if applications are impacted.

Stage 2. We'll add an error to the Regent compiler, with an optional flag to downgrade it to a warning. There are two main reasons for going straight to an error. First, warnings are easy to ignore, and there's a risk that with just a warning we might not be notified of a potentially impacted user until the feature was removed outright. The error ensures that any active Regent user who uses this feature is forced to deal with it, and we can tailor the error message to encourage them to notify us if they are impacted. Second, as an issue of pragmatics, Regent errors have better location reporting, so it'll be quicker for users to find any offending statements if they do have them.

Stage 3. Removal of the feature, after some reasonable amount of time.

In the past we haven't really followed a formal process for deprecation of Regent features, so this is a bit of an experiment and depending on how it goes we may tweak the process either in flight or for future instances.

**Comment by magnatelee** [comment]
Sure, I'll make a change for this.

**Comment by magnatelee** [comment]
I just pushed a change for the stage 2: https://gitlab.com/StanfordLegion/legion/commit/a4800e44408fb3acd59d36fc55fb76700d38fed2. There is now a flag `allow-multi-field-expansion` that allows the multi-field expansion, which is now used only by the tests designed to test the multi-field expansion. Otherwise, multi-field expansions in the tests were manually unrolled. Tests for the multi-field expansion should be removed at stage 3.

**Comment by elliottslaughter** [comment]
The deprecation was announced in https://github.com/StanfordLegion/legion/releases/tag/legion-19.09.0 and we will move to stage 3 at some point in the future (yet to be determined which release).

**Comment by elliottslaughter** [comment]
The error has been in two releases now, 19.09.0 and 19.12.0. The branch for final deletion is at `no-multi-field-expansion`. I will merge after CI passes.

**Comment by elliottslaughter** [comment]
CI passed and I have merged this into master. With this, multi-field expansion has been removed. There may still be some lingering dead code, however.
