### ISSUE TITLE
Regent: RDIR breaks on cross product accesses

### ISSUE THREAD

**Issue by magnatelee** [StanfordLegion/legion#503]
This test case hits a validator assertion with RDIR (RDIR is turned off for this test at the moment):

https://gitlab.com/StanfordLegion/legion/blob/master/language/tests/regent/run_pass/region_partition_access_cross_product.rg

RDIR seems to emit the exact same declaration for every cross product access `cp[c]` when `c` is constant. Also, commenting out this line reproduces another bug, which may or may not be due to the same cause:

https://gitlab.com/StanfordLegion/legion/blob/master/language/tests/regent/run_pass/region_partition_access_cross_product.rg#L35

**Comment by elliottslaughter** [comment]
SCR is gone now.
