### ISSUE TITLE
Errors embedding Terra code in C using llvm 6

### ISSUE THREAD

**Issue by amaleewilson** [StanfordLegion/legion#504]
On branch master, os centos7, building terra/regent with llvm 6 using setup_env.py works fine, but when trying to embed terra-lua in C code, getting this error: 

../terra/release/lib/libterra.a(Compression.cpp.o): In function `llvm::zlib::compress(llvm::StringRef, llvm::SmallVectorImpl<char>&, llvm::zlib::CompressionLevel)':
Compression.cpp:(.text._ZN4llvm4zlib8compressENS_9StringRefERNS_15SmallVectorImplIcEENS0_16CompressionLevelE+0x1f): undefined reference to `compressBound'
Compression.cpp:(.text._ZN4llvm4zlib8compressENS_9StringRefERNS_15SmallVectorImplIcEENS0_16CompressionLevelE+0xb3): undefined reference to `compress2'
../terra/release/lib/libterra.a(Compression.cpp.o): In function `llvm::zlib::uncompress(llvm::StringRef, char*, unsigned long&)':
Compression.cpp:(.text._ZN4llvm4zlib10uncompressENS_9StringRefEPcRm+0x1a): undefined reference to `uncompress'
../terra/release/lib/libterra.a(Compression.cpp.o): In function `llvm::zlib::crc32(llvm::StringRef)':
Compression.cpp:(.text._ZN4llvm4zlib5crc32ENS_9StringRefE+0xc): undefined reference to `crc32'
collect2: error: ld returned 1 exit status

**Comment by amaleewilson** [comment]
Added -lz when compiling the C code, which fixed things, but there is something going on in the build scripts that is not disabling zlib.

**Comment by streichler** [comment]
@amaleewilson are you building llvm from source, or using centos' pre-built llvm 6 packages?

**Comment by amaleewilson** [comment]
I think setup_env.py is downloading llvm and building from source.

**Comment by streichler** [comment]
This should hopefully be fixed with commit d15aa6f.
