### ISSUE TITLE
Legion: AUTO_GENERATE_ID and VariantID are different types

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#508]
Currently, `AUTO_GENERATE_ID` is defined to be an `unsigned int` while `VariantID` is defined to be an `unsigned long`. This can cause issues, like casting `-1` to `VariantID` does sign extension and produces a value which is `!= AUTO_GENERATE_ID`. This happens in Regent because Terra's parser can't extract `AUTO_GENERATE_ID` from `legion.h` automatically.

In Regent I've worked around this by explicitly casting to `uint32` in https://gitlab.com/StanfordLegion/legion/commit/0347291f4961a1d944e02d3cd44213cb585d3881 . This patch will need to be tweaked if `AUTO_GENERATE_ID` is upgraded to be the same type as `VariantID`.

**Comment by lightsighter** [comment]
@elliottslaughter Are we done with this one? VariantID has been demoted to 32 bits.

**Comment by elliottslaughter** [comment]
I reverted the hacky portions of my commit in 7a138c2aa62571955e5a171a61d388554614f4d8 and now consider this resolved.
