### ISSUE TITLE
Regent: set_variant_id() sets variant for both LOC_PROC and IO_PROC tasks

### ISSUE THREAD

**Issue by syamajala** [StanfordLegion/legion#513]
Setting the variant id for a task by doing `task:get_primary_variant():set_variant_id(1)` currently sets the id for both the LOC_PROC variant and the IO_PROC variant when it should only be done for the LOC_PROC one. Setting the same variant id for both types causes the runtime to lose track of the LOC_PROC variant.

**Comment by elliottslaughter** [comment]
Should be fixed by 6f4e80a6b00384f7c7816f8ba584fa163dd059ef.
