### ISSUE TITLE
is_identity should be __CUDA_HD__

### ISSUE THREAD

**Issue by scothalverson** [StanfordLegion/legion#519]
Compiling under Clang CUDA, I needed to mark the following function \_\_CUDA_HD\_\_ in order to compile.

https://github.com/StanfordLegion/legion/blob/6732fb6f61a631348c2ed7cd1317af444779b3b7/runtime/legion/legion_domain.inl#L441

**Comment by lightsighter** [comment]
Also a typo and should be fixed in fefaf45 on gitlab in the master branch. Will be over here on github in the master branch in a little bit. Let me know if you find other typos. Not all of these templates have been instantiated before.
