### ISSUE TITLE
Regent: Image returns unexpected result for subregions with sparse index spaces

### ISSUE THREAD

**Issue by syamajala** [StanfordLegion/legion#523]
```
import "regent"

local c = regentlib.c

fspace Entry {
  idx:int2d,
  val:double
}

task main()

  var entries = region(ispace(int2d, {4, 1}), Entry)

  entries[{0, 0}].idx = {1, 0}
  entries[{0, 0}].val = 1

  entries[{1, 0}].idx = {2, 0}
  entries[{1, 0}].val = 1

  entries[{2, 0}].idx = {3, 3}
  entries[{2, 0}].val = 4

  entries[{3, 0}].idx = {12, 4}
  entries[{3, 0}].val = 5

  var epart = partition(equal, entries, ispace(int2d, {1, 1}))
  var part = image(entries, epart, entries.idx)

  for color in part.colors do
    var r = part[color]
    for i in r.ispace do
      c.printf("Color: %d %d I: %d %d\n", color.x, color.y, i.x, i.y)
    end
  end

end

regentlib.start(main)
```

The above example prints the following:
```
Color: 0 0 I: 1 0
Color: 0 0 I: 2 0
```

I expected the subregion {0, 0} to contain all the points from the original region. However, it appears the points {3, 3} and {12, 4} are missing and are not contained in the partition at all.

**Comment by lightsighter** [comment]
This is not a bug. The runtime automatically prunes points that fall outside the destination index space being partitioned for image. (3,3) and (12,4) are points that are not contained in the 'entries' index space which ranges from (0,0) to (4,1) and so they are automatically pruned.

**Comment by lightsighter** [comment]
It's worth noting that the same pruning also occurs for preimage and partition by field dependent partitioning operations also.

**Comment by syamajala** [comment]
I see what to do. Thanks!
