### ISSUE TITLE
Regent: install.py should automatically rebuild terra with CUDA support

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#526]
If terra wasn't build with CUDA support and a user passes --cuda to install.py then it should automatically rebuild terra with CUDA support or tell the user why it can't and not silently let the user think that CUDA support was successfully installed.

**Comment by elliottslaughter** [comment]
This is fair, but we should do some auto-detect style check like #495 to actually make sure Terra needs a rebuild, not just blindly do it.

Note to self: need to check if `make clean && make` is enough, or whether we need `make purge && make`.

**Comment by elliottslaughter** [comment]
I'm seriously considering moving `install.py` and `setup_env.py` to build Terra with CMake by default, which I think would also fix.

**Comment by elliottslaughter** [comment]
Both scripts now use CMake by default to build Terra, which I think resolves this issue. Please reopen if you have any further issues.
