### ISSUE TITLE
Realm: Better error message if -ll:Xsize is too big

### ISSUE THREAD

**Issue by manopapad** [StanfordLegion/legion#527]
For example, currently if you pass a value to `-ll:fsize` that is too large for the device's framebuffer (including any memory that Realm/Legion reserves on top of that), you will get a generic error like `std::bad_alloc`, or a CUDA error that device memory was exhausted. It would be nice if the message was more informative ("it looks like you're trying to allocate more framebuffer memory than what is available, would you like some help?").

**Comment by streichler** [comment]
Commit 15dde423 tries to be a little more user-friendly here.  As a side benefit, commit 1b68f55a lets you write things like `-ll:fsize 10g` (or `-ll:fsize 1t` if you want to test the out-of-memory errors :).  @manopapad can you take a look at let me know if you're satisified?

**Comment by manopapad** [comment]
Love it! 2 things to note:

It looks like a parenthesis is at the wrong place in the error message:
```
[0 - 7f0e3b51e800] {6}{gpu}: insufficient memory on gpu 0: 52428800000 bytes needed (from -ll:fsize), 6309478400 (out of 6361120768 available)
```
should probably be:
```
[0 - 7f0e3b51e800] {6}{gpu}: insufficient memory on gpu 0: 52428800000 bytes needed (from -ll:fsize), 6309478400 (out of 6361120768) available
```

Also, asking for more RAM than is available (e.g. using `-ll:csize`) still results in a `std::bad_alloc`.

**Comment by streichler** [comment]
So demanding...  Typo is fixed, and ll:csize-too-large gets a nice error message as of commit 72d493d.

**Comment by manopapad** [comment]
Looks good!
