### ISSUE TITLE
Utilization not shown in single-node Legion Prof plots

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#528]
For some reason, utilization bars for the processors do not seem to appear on single-node Legion Prof plots. I'm not sure whether this was intentional or not, but it seems like we should show them, because this is a very useful feature.

**Comment by lightsighter** [comment]
@elliottslaughter Are you still seeing this or did we fix it? I can't remember. If not, can @seemamirch look at it?

**Comment by elliottslaughter** [comment]
Seems to be fixed now. Closing.
