### ISSUE TITLE
Update Profiler to Record Multiple Logical Regions for Physical Instances

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#540]
In the nopaint branch and later, physical instances can be the result of the union of multiple logical regions so the profiler should record them as such. @seemamirch will update the master branch so the profiler can record multiple logical regions for a physical instance. @lightsighter will then propagate the changes to the nopaint branch.

**Comment by lightsighter** [comment]
@seemamirch Just pinging you on this. Wonchan is still the bottleneck on merging nopaint into master since he has to finish the updates to tracing, but once he's done this will be the only remaining issue blocking the merge of nopaint into master.

**Comment by seemamirch** [comment]
https://gitlab.com/StanfordLegion/legion/commit/cd91d237d5b6309cce9a6ce3797ed21cc510052e
https://gitlab.com/StanfordLegion/legion/commit/f59aa302a814f875a8a83a5e59af5da6170e8b80
fixes this
