### ISSUE TITLE
Phase Barrier Generation Overflow

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#541]
We need a better way to deal with overflow of phase barrier generations. At a minimum Realm needs to at least have a better error message when a barrier's generations have been exhausted. A better option would be for Legion to detect such cases and automatically make a new phase barrier to fill in for the old one.

Our test case for this is from @mariodirenzo. He should comment on here to say whether the temporary fix we gave him works.

**Comment by mariodirenzo** [comment]
This change in Legion 
```
diff --git a/runtime/realm/id.h b/runtime/realm/id.h
index d775ce5aa..923d701b0 100644
--- a/runtime/realm/id.h
+++ b/runtime/realm/id.h
@@ -56,7 +56,7 @@ namespace Realm {
 
       static const int NODE_FIELD_WIDTH = 16;
       static const unsigned MAX_NODE_ID = (1U << NODE_FIELD_WIDTH) - 2; // reserve all 1's for special cases
-      static const int EVENT_GENERATION_WIDTH = 20;
+      static const int EVENT_GENERATION_WIDTH = 15;
       static const int INSTANCE_INDEX_WIDTH = 16;
 
 #define ACCESSOR(structname, name, field) \
@@ -84,7 +84,7 @@ namespace Realm {
        typedef bitfield<4, 60> type_tag;
        typedef bitfield<NODE_FIELD_WIDTH,
                         60-NODE_FIELD_WIDTH> creator_node;
-       typedef bitfield<24,
+       typedef bitfield<29,
                         EVENT_GENERATION_WIDTH> barrier_idx;
        typedef bitfield<EVENT_GENERATION_WIDTH, 0> generation;  // MUST MATCH FMT_Event::generation size
```
triggered the assertion ``prometeo.exec: legion/runtime/realm/runtime_impl.cc:2301: Realm::GenEventImpl* Realm::RuntimeImpl::get_genevent_impl(Realm::Event): Assertion `id.is_event()' failed.`` 32 times faster than the default version of the library.

**Comment by lightsighter** [comment]
This issue should be fixed by commit 0432ba7. @mariodirenzo can you confirm that it has been fixed?

**Comment by mariodirenzo** [comment]
All the jobs that were crashing because of this issue seem to work now.
I'll give an update in the next few days to confirm that the bug has been fixed.

**Comment by mariodirenzo** [comment]
I've been running other calculations in the last week and I did not experience other crash related to this issue. For me, it can be declared solved.

Thank you for your help!

**Comment by lightsighter** [comment]
I agree I think it's fixed.
