### ISSUE TITLE
Missing LockRequest constructor

### ISSUE THREAD

**Issue by mpokorny** [StanfordLegion/legion#542]
The LockRequest constructor declared in the following
https://github.com/StanfordLegion/legion/blob/8fab48829bb0db6a0cdcd62def8d4c0509241c37/runtime/legion.h#L788
appears to be missing its definition.

**Comment by lightsighter** [comment]
I intentionally left this unimplemented so we could find out why we need it. @mpokorny what are you planning on using this for?

**Comment by mpokorny** [comment]
I was attempting to use a `Grant` to serialize access from tasks to a library that is not thread-safe when doing some debugging. I've since fixed the issue I was debugging, and I no longer require instantiating a `LockRequest`. So my use was a real corner case, I guess, and it doesn't reflect an approach that I'd take in production code.

**Comment by lightsighter** [comment]
Ok that was a reasonable reason to use it. I've added the missing definition with d7cad2b. Closing the issue.
