### ISSUE TITLE
Attach HDF5 does not support nested groups

### ISSUE THREAD

**Issue by eddy16112** [StanfordLegion/legion#543]
@streichler 
I have a hdf5 file which is:
HDF5 “checkpoint.dat0” {
GROUP “/” {
 GROUP “input_lr_1” {
    DATASET “FID_X” {
       DATATYPE  H5T_IEEE_F64LE
       DATASPACE  SIMPLE { ( 32 ) / ( 32 ) }
       DATA {
       (0): 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       (21): 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
       }
    }
The attach operation can not find the FID_X, the error message is:
#000: H5D.c line 292 in H5Dopen2(): unable to open dataset

If the GROUP “input_lr_1”  is removed, then it works.

**Comment by streichler** [comment]
Commit f7a67b2 should do the trick for users of the C++ api.  As with most HDF5 tools, the leading slash in a path name is optional (i.e. either "/input_lr_1/FID_X" or "input_lr_1/FID_X" would work for the example above).  Adding @elliottslaughter to comment on how hard it'd be to have regent accept custom dataset names (it looks like it generates them automatically from the names of the fields in the regent source right now).

**Comment by elliottslaughter** [comment]
Do you want the dataset names to be dynamic? (Or is there any plausible use case where you'd want them to be?)

The answer to this question will determine what we'll need the API on the Regent side to be. If you need them to be dynamic then I need an array of strings passed as an argument (as opposed to having them added to e.g. the field access syntax).

**Comment by streichler** [comment]
They are dynamic in the C++ API, and I think that's probably a good thing.  For example, you might have an HDF5 file with multiple datasets and use a command-line parameter to decide which one your app will actually use.

**Comment by elliottslaughter** [comment]
Ok, so if I just add an optional `char **` argument for the datasets is that enough to do what you want?

**Comment by eddy16112** [comment]
@streichler If I understand correctly, the "field_map" for nested group will be "group_name/field_id", right?

**Comment by streichler** [comment]
@eddy16112 yes, and it'll work with or without the leading slash

**Comment by elliottslaughter** [comment]
Regent now has an optional argument you can use to manually specify a field map.

**Comment by streichler** [comment]
And commit b779249 adds a test to the Regent test suite that demonstrates/tests said capability.
