### ISSUE TITLE
Use HDF5 Sync Operations

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#548]
We want to use HDF5 sync operations to flush effects out to the file system instead of having to rely on a separate file open/close operations on every Realm DMA operation.

**Comment by streichler** [comment]
This is now an _optional_ behavior as of commit 561f2c4.  A nonzero value for the `-hdf5:openfiles` variable will allow up to the specified number of HDF5 files to be left open after a DMA transfer is complete.  If left open, a call to `H5Fflush` is performed to make sure the transferred data is seen by any other process accessing the same file.
Unfortunately, there is a limitation in libhdf5 with respect to having the same file open in both read-only and read-write modes.  This limitation makes it dangerous to keep HDF5 files open by default, as errors will occur if a file is first read from (e.g. a copy from disk to memory) and then later written to (a copy from memory back to disk).  If *all* HDF5 files accessed by a process are writeable on disk, `-hdf5:forcerw` can be specified on the command line to force all files to be opened in read-write mode.
