### ISSUE TITLE
Realm Control File Open/Close Process with File Name

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#549]
Add a new convention for file naming that allows users to control which process performs file open/close operations for a given external file that is attached to a region.

@gshipman and @eddy16112 to comment on current file naming standards.

**Comment by streichler** [comment]
In the absence of external suggestions/constraints, I'll probably do something like this:
"rank=432:/file/path/to/open/from/rank/432/..." or
"{rank=432}/file/path/to/open/from/rank/432/..."
with the intent that other prefixes might be added in the future (e.g. a specific hostname).  Anybody with
a preference between those two and/or alternative suggestions should speak up soon.  :)

**Comment by streichler** [comment]
Poking @gshipman and @eddy16112 to comment soon (or not at all).

**Comment by streichler** [comment]
The goal is just to cover the things that might be part of a URL (e.g. figuring out which server/mount-point/whatever the file is on and what the name of the file is on that location).  Other parameters (e.g. read only or cache size or what have you) do not change which "file" you're talking to and are currently specified via a more well-structured API.  :)

**Comment by gshipman** [comment]
@streichler I don't have a strong preference on either, I slightly prefer the first. 
One question, what is the definition of rank in this context? A single process on a node in the distributed system? 
If we do a copy from LR1 on rank 0 to LR2 on rank 1 where LR2 is attached to file1, will the DMA system handle movement of all data (and writes to the file) as we expect? Thx

**Comment by streichler** [comment]
@gshipman a "rank" is a separate process spawned by the job launcher (mpirun, jsrun, etc.).  We've typically called that a "node" in Legion-land, but I wanted to avoid confusion with choosing particular nodes in the cluster, which might also be desirable for this interface (e.g. attaching to a file that exists on a particular cluster node's local disk).

And yes, if you do a copy from LR1 that has its physical instance on rank 0 to LR2 that is attached to "rank=1:/some/file/path", the DMA system will take care of streaming data from rank 0 to rank 1 over GASNet messages and having rank 1 issue all the necessary libhdf5 API calls.

**Comment by streichler** [comment]
I've got Realm changes to support the first syntax (i.e.
"rank=432:/file/path/to/open/from/rank/432/..."
), but we're running into an assert in the Legion code, which #555 is tracking.

**Comment by streichler** [comment]
Support for this appeared in the master branch with commit 8e39825.
