### ISSUE TITLE
Add File I/O Functor to Legion for Computing Attach File Names Over Partitions

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#550]
Create a new kind of functor that is registered with the runtime that is able to compute the names of files for doing an attach to a logical region over a partition. 

@gshipman and @eddy16112 to comment on the kinds of arguments that need to be passed to these functors.

**Comment by eddy16112** [comment]
I think it can be done like this:
AttachLauncher(LogicalPartition, LogicalRegion)
attach_hdf5(std::vector<const char *>file_name_vector,
                      const std::map<FieldID,const char*> &field_map,
                      LegionFileMode mode)
Each element within the file_name_vector can be used for the filename of each subregion.

**Comment by lightsighter** [comment]
That's not quite what we mean here. @gshipman should be able to explain to you tomorrow.

**Comment by gshipman** [comment]
I chatted with Wei. Here is my understanding of the approach: 
We will be able to register a functor that is able to maps colors in a partition to filenames and groups.
We (FleCSI) will be responsible for generating a set of M files (say pressure_0.h5, pressure_1.h5) with the group and datasets we wish to use in the attach operation. 
Given a logical region Dest with a disjoint partitioning of 4 colors, we will register a functor that maps colors 0,1 to pressure_0.h5 and colors 2,3 to pressure_1.h5. We will use the standard field map to map to groups and datasets. 
From the top level task? we can then issue an "index space attach" with the functor and field map. We can then issue index copies from our logical region Source (with same partitioning as Dest) to save the data to the HDF files. We then issue an "index space detach". 
Does this capture (at a very high level) the proposed solution?

**Comment by lightsighter** [comment]
Per @gshipman permission we are moving this issue to the 20.06 milestone.

**Comment by lightsighter** [comment]
@gshipman @eddy16112 please look at the proposed API and offer feedback on my three questions below. Anybody can comment on other aspects of the API design as well.

The first extension is we have new 'IndexAttachLauncher' which should not be too surprising to anyone:

https://gitlab.com/StanfordLegion/legion/-/blob/indexattach/runtime/legion.h#L2011-2060

Note that attach launchers specify a projection function to use just like normal index space operations. The one difference is that I've extended the ProjectionFunctor interface to support performing projections that generate file names as well as pointers for external allocations:

https://gitlab.com/StanfordLegion/legion/-/blob/indexattach/runtime/legion.h#L3702-3723

I like associating these calls with the projection functor interface since it seems like we want the logic that decides which file to use to be in the same place as the logic that decides which region each point is going to be associated with. The runtime will invoke the same projection functor object to both pick the logical region and file name/pointer for external resources.

IndexAttachLaunchers are used the same way that we do for normal AttachLaunchers today.

https://gitlab.com/StanfordLegion/legion/-/blob/indexattach/runtime/legion.h#L6282-6290

The one difference though is that it returns a new 'PhysicalRegionMap' object which is a collection of PhysicalRegion objects:

https://gitlab.com/StanfordLegion/legion/-/blob/indexattach/runtime/legion.h#L2333-2359

This stores all the PhysicalRegion objects that are created as part of the attach operation. It also gives us a name for all the physical regions for performing the detach operations which have always been implicit.

https://gitlab.com/StanfordLegion/legion/-/blob/indexattach/runtime/legion.h#L6305-6316

I think there are three major outstanding questions I would like to have feedback on:

1. What do we think about associating the projection of file names and pointers for external resources with projection functors? Do we prefer that or do we want a separate functor interface for external resources?
2. How do we feel about adding the new PhysicalRegionMap type for describing groups of PhysicalRegion objects? It feels a little ugly to me to have this for just this one kind of operation so we can have a name for the resources we're going to do a detach on, but it's not so ugly that I think it's a bad idea. I can imagine one other potential use case of a PhysicalRegionMap in the future, but it does feel like a one-off type only used in a specialized case right now. One alternative that I considered was to have a std::map<DomainPoint,PhysicalRegion> output, but that's really unfortunate in a control replication context where you only want to lazily get PhysicalRegion objects for your shard if you actually need them.
3. For control replication, I've put the choice of a sharding functor directly on the launcher instead of allowing the mapper to pick it like we do for all other kinds of operations.
https://gitlab.com/StanfordLegion/legion/-/blob/indexattach/runtime/legion.h#L2046
The reason for this is that sharding of index attach operations need to align with where those external resources are existing outside of the Legion program, and therefore it's likely a matter of correctness what the sharding functor is. Does everyone agree with that logic or does someone want to quibble?

**Comment by elliottslaughter** [comment]
Copying my comment from elsewhere:

I feel a little strange putting external pointers in the projection functor interface. In general, external pointers are only going to be valid in one node. Unless the user does something to explicitly exchange them, one would not normally even have the addresses available on the other nodes.

My current conceptual model of a projection functor is that it should be something that should be equivalent on every node. If you have a projection functor registered on nodes 0 and 1 with the same ID, it shouldn't matter which node you call it from, the result should always be the same. There is some weirdness with dynamic registration, but as far as I'm aware that's an issue of availability (is the projection functor available on a given node) not one of consistency (will it produce the same answer on every node). But now we'll have projection functors where you can only project certain values on certain nodes.

I'm not sure what the alternative is exactly, but I guess my feeling is that this should be part of the attach operation. The data is local to the node that's issuing the operation (or in this case, a given shard of the operation), and so it should be represented at point in the code where it's obvious that it's associated with a given node. To me this does not seem to naturally fit the semantics of a projection functor---or if we do want to go that way, it's a pretty radical departure from what projection functors do today.

**Comment by eddy16112** [comment]
I have followed the email in the legiondevelopers. Regarding the second question, I think PhysicalRegionMap is better than std::map<DomainPoint,PhysicalRegion> because in the detaching operation, I think we want users to detach all PhysicalRegions together. If using std::map<>, it gives a chance for users not to detach all PhysicalRegions, so I think it is better to limit the controls of users to avoid any bugs because of not using correctly.

**Comment by lightsighter** [comment]
Work on new equivalence sets has delayed this to the next milestone.

**Comment by lightsighter** [comment]
There is now support in the master and control replication branches for both index space attach and detach operations. There is a launcher for index space attach operations. Instead of returning a PhysicalRegion like normal attach operations, index space attach operations return an ExternalResources object which can be indexed like a vector to return the associated PhysicalRegion objects for each of the logical regions that were attached in the same order they were put in the launcher. Index space detaches are performed on these ExternalResource objects. There is an example for this which is included in the CI test suite and works both with and without control replication. The C API has also been updated with support for index attach/detach operations and external resources. Legion Spy supports index attach/detach operations as well.

The other major impact of this change is that it is now possible for tasks to discover that they are running in a control-replicated execution mode. This is necessary because index space/attach detach operate as collective operations across the shards, so the shards need some way of knowing what they are so they can coordinate their attach operations. To facilitate this, I've now exposed API calls for a task to discover its shard ID and how many shards are in the execution. This can open a can of worms for abuse, so we will need to be diligent about looking for bad use cases.

In addition to the index/space attach detach operations which behave collectively, I have added one other collective operation which felt very natural to add and should make a bunch of things easier. I've added support for collectively constructing FutureMap objects from the shards. Both the construct_future_map calls now take two optional parameters: one is a boolean flag indicating whether this will be a collective construction of the FutureMap (e.g. is each shard passing in a different subset of points), and the second is a sharding function ID that describes which shards are passing in which points. In non-control-replicated execution, both flags are always ignored. In control-replicated settings, the application can choose to pass in all the same points and values across all shards and set 'collective=false' or pass in different subsets of points on each shard and set 'collective=true'. If 'collective=true' the runtime will verify that the sharding function matches the passed in points. Neither collective nor non-collective FutureMap construction requires any communication.

The value of providing collective FutureMap construction is that you can do lots of things with those collectively constructed FutureMap objects once you have them. For example, you can create a partition from a FutureMap, or create an ArgumentMap to pass to an index space task launch, or you can do a (all-)reduction of it down to a single Future. This seems like a minimal way to allow shards to collectively pass things into Legion, but then get back into normal control-replicated behavior where all the shards are back to running the same program. I'm open to other suggestions of places where we might want to expose collective behavior, but I think this should cover the vast majority of cases.

I'm now going to close Issue #550 as I believe we have satisfied its functional requirements, even though we did it in a different way than we originally thought we would.
