### ISSUE TITLE
Add -lg:error flag

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#552]
Currently `-lg:warn` prints warnings which may be difficult to associate with source code locations. If we had a mode to actually assert on a warning (e.g. with a flag like `-lg:error`) you could at least get your app to freeze and get a backtrace. Fancier integration is also certainly possible, but it's not obvious if it's worth the effort.

(For reference, I'm talking about C++ codes here; in Regent the compiler can automatically add source code locations to the call sites.)

**Comment by streichler** [comment]
What about something like `-lg:warn_backtrace` that prints the backtrace for each warning without killing the application?  That way you don't have to peel them one at a time.

**Comment by elliottslaughter** [comment]
That would be fine too.

**Comment by lightsighter** [comment]
@streichler Do you want to give me a backtrace utility in Realm or should I role my own?

**Comment by streichler** [comment]
Realm backtraces: https://gitlab.com/StanfordLegion/legion/blob/master/runtime/realm/faults.h#L55-93
Example usage: https://gitlab.com/StanfordLegion/legion/blob/master/runtime/realm/threads.cc#L552-555

**Comment by lightsighter** [comment]
@elliottslaughter Are we done with this now?

**Comment by elliottslaughter** [comment]
Confirmed that this works.
