### ISSUE TITLE
New parallelizer makes combined ghost instance for all stencil directions

### ISSUE THREAD

**Issue by manopapad** [StanfordLegion/legion#554]
Consider the following logs (from a simulation by @mariodirenzo): [4nodes_inst-prof.tar.gz](https://github.com/StanfordLegion/legion/files/3312293/4nodes_inst-prof.tar.gz).

This simulation runs on a 258x202x192 grid, split only on x, as follows: 0..64, 65..128, 129..192, 193..257. The `velocity` field is accessed on the x dimension using the following stencils: -2, -1, +1, +2, +3. Here are the instances created by the parallelizer for ghost accesses on the `velocity` field:

```
node 0: [0 - 200073cef0d0] {1}{inst}: instance layout: inst=6000000000010012 layout=Layout(bytes=179647488, align=32, fields={135=0+0}, lists=[[<65,0,0>..<257,201,191>->affine(<24,4632,935664>+18446744073709550056)]])
node 1: [1 - 20005ff6f0d0] {1}{inst}: instance layout: inst=6000100010010011 layout=Layout(bytes=64226304,  align=32, fields={135=0+0}, lists=[[<63,0,0>..<131,201,191>->affine(<24,1656,334512>+18446744073709550104)]])
node 2: [2 - 20005ff1f0d0] {1}{inst}: instance layout: inst=6000200020010011 layout=Layout(bytes=64226304,  align=32, fields={135=0+0}, lists=[[<127,0,0>..<195,201,191>->affine(<24,1656,334512>+18446744073709548568)]])
node 3: [3 - 20005ff1f0d0] {1}{inst}: instance layout: inst=6000300030010012 layout=Layout(bytes=179647488, align=32, fields={135=0+0}, lists=[[<0,0,0>..<192,201,191>->affine(<24,4632,935664>+0)]])
```

It looks like the parallelizer is trying to make a single instance for all stencil accesses, and the runtime is returning a dense instance, which ends up including all the cells in-between. E.g. for tile 1, which covers x values 65..128, instead of getting 2 regions (for 63..64 and 129..131), we get a single one covering the full range 63..131. This is even worse for the boundary tiles, e.g. tile 0: Instead of getting 256..257 (for -2 and -1, wrapping around) and 65..67 (for +1, +2 and +3), you get almost the full region (65..257).

**Comment by mariodirenzo** [comment]
Do you have any update on this issue?

**Comment by magnatelee** [comment]
This is fixed in the `parallelizer-dcr` branch.
