### ISSUE TITLE
Realm: 2D Scatter-Strided Copies

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#560]
CPU-only control replication Legion S3D exercises this assertion in Realm:
https://gitlab.com/StanfordLegion/legion/blob/control_replication/runtime/realm/transfer/channel.cc#L2845
The cause seems to be related to this comment here:
https://gitlab.com/StanfordLegion/legion/blob/control_replication/runtime/realm/transfer/channel.cc#L1470-1471
I was able to cause this to happen deterministically with a 3x2x2 processor grid and 16^3 cells per rank using the PRF mechanism, with RHST_FUSE=8.

**Comment by streichler** [comment]
@lightsighter can you give this another try with commit 7f2e759a?

**Comment by lightsighter** [comment]
It's much better now.
