### ISSUE TITLE
Clean up 'rendering' test to eliminate use of deprecated API bits

### ISSUE THREAD

**Issue by streichler** [StanfordLegion/legion#563]
Lots of renaming to do.  That should hopefully be it.

**Comment by streichler** [comment]
Turns out some of the deprecated things don't have convenient new replacements (e.g. partitioning via small DomainColoring objects).  Re-taking ownership to debate the right plan with @lightsighter .

**Comment by elliottslaughter** [comment]
Well, our deprecated APIs are gone nos so either we fixed this or it's no longer relevant.
