### ISSUE TITLE
Regent: Support for print_once

### ISSUE THREAD

**Issue by manopapad** [StanfordLegion/legion#566]
Legion's `print_once` is useful when writing control-replicated apps. I suggest we add it to the Legion C interface, and add it to the compiler's exceptions for the __replicable check.

**Comment by elliottslaughter** [comment]
Done: https://gitlab.com/StanfordLegion/legion/commit/7caf53bfb00506d59d512b642517eaf25058ff99

And the whitelist is actually a blacklist, so we should be good on that front.
