### ISSUE TITLE
Regent: Add support for building Terra with CMake

### ISSUE THREAD

**Issue by gaofan83** [StanfordLegion/legion#567]
Need help with the installation.

I used the following script to install legion on ubuntu 19.04
`sudo apt-get install clang libclang-dev llvm-dev`
`git clone -b master https://github.com/StanfordLegion/legion.git`
`cd legion/language`
`./install.py --debug`

Installation failed with the following error message:
Already up to date.
Traceback (most recent call last):
  File "./install.py", line 437, in <module>
    driver()
  File "./install.py", line 434, in driver
    install(**vars(args))
  File "./install.py", line 340, in install
    thread_count, llvm)
  File "./install.py", line 183, in install_terra
    build_terra(terra_dir, terra_branch, thread_count, llvm)
  File "./install.py", line 137, in build_terra
    cwd=terra_dir)
  File "/usr/lib/python2.7/subprocess.py", line 185, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by elliottslaughter** [comment]
I'm going to need the full build output in order to debug this.

Can you tell me what the version of Clang/LLVM is? It is best to use LLVM 6 if you can.

**Comment by gaofan83** [comment]
clang version 8.0.0-3 (tags/RELEASE_800/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

**Comment by elliottslaughter** [comment]
Right, we definitely do not support LLVM 8. Can you install 6, `rm -rf terra` and try again? (And if it still fails, attach the full output.)

**Comment by gaofan83** [comment]
`sudo apt-get install clang-6.0 libclang-6.0-dev llvm-6.0-dev`
`cd legion/language`
`rm -rf terra`
`./install.py --debug`
Traceback (most recent call last):
  File "./install.py", line 437, in <module>
    driver()
  File "./install.py", line 434, in driver
    install(**vars(args))
  File "./install.py", line 340, in install
    thread_count, llvm)
  File "./install.py", line 183, in install_terra
    build_terra(terra_dir, terra_branch, thread_count, llvm)
  File "./install.py", line 137, in build_terra
    cwd=terra_dir)
  File "/usr/lib/python2.7/subprocess.py", line 185, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by elliottslaughter** [comment]
Just as a sanity check:

```
sudo apt-get install build-essential
```

and rerun.

And is that really all of the output?

**Comment by gaofan83** [comment]
Thanks. Forgot `sudo apt-get install build-essential` 
now different error message (see attached).
[error.txt](https://github.com/StanfordLegion/legion/files/3394065/error.txt)

**Comment by elliottslaughter** [comment]
Looks like this is a bug in the Terra Makefile. As a workaround, can you try the following? If this works I can try to update `install.py` to do this automatically.

```
sudo apt-get install zlib1g-dev libedit-dev
mv terra terra.build
ln -s terra.build terra
cd terra.build
git clean -fxd
cd build
cmake -DCMAKE_INSTALL_PREFIX=$PWD/../release -DCMAKE_PREFIX_PATH=/usr/lib/llvm-6.0 ..
make install -j4
cd ../..
./install.py --debug
```

**Comment by gaofan83** [comment]
Seems working. Thanks a lot!
fgao@cbrc:~/software/legion/language$ ./regent.py examples/circuit.rg
examples/circuit.rg:565: WARNING: using old style partition API with legion_coloring_t, please consider upgrading to legion_point_coloring_t
examples/circuit.rg:568: WARNING: using old style partition API with legion_coloring_t, please consider upgrading to legion_point_coloring_t
examples/circuit.rg:569: WARNING: using old style partition API with legion_coloring_t, please consider upgrading to legion_point_coloring_t
examples/circuit.rg:570: WARNING: using old style partition API with legion_coloring_t, please consider upgrading to legion_point_coloring_t
examples/circuit.rg:572: WARNING: using old style partition API with legion_coloring_t, please consider upgrading to legion_point_coloring_t
circuit settings: loops=5 pieces=4 nodes/piece=4 wires/piece=8 pct_in_piece=80 seed=12345
Circuit memory usage:
  Nodes :        16 *   16 bytes =         256 bytes
  Wires :        32 *  120 bytes =        3840 bytes
  Total                                   4096 bytes
Starting main simulation loop
SUCCESS!
ELAPSED TIME =   0.281 s
GFLOPS =   0.546 GFLOPS
simulation complete - destroying regions

**Comment by elliottslaughter** [comment]
Ok, good. You should be able to re-run `install.py` without breaking anything (and without needing to re-do the Terra build), but I will try to fix it so that it works from scratch without needing to do any of this manually.

**Comment by elliottslaughter** [comment]
I changed the title to help me remember what needs to done.

**Comment by elliottslaughter** [comment]
Now submitted issue at https://github.com/zdevito/terra/issues/393

**Comment by elliottslaughter** [comment]
There is now a flag `--terra-cmake` that can be used to make `install.py` build Terra with CMake. At some point in the future we will likely make this the default.

I'm closing this issue, but the issue linked above tracks the Ubuntu 19.04 build failure that prompted this issue. Thanks!
