### ISSUE TITLE
Build error when using 64bit IDs: -DLEGION_IDS_ARE_64BIT on DMA branch

### ISSUE THREAD

**Issue by gshipman** [StanfordLegion/legion#57]
I'm getting a build error on the DMA branch when building with -DLEGION_IDS_ARE_64BIT

make DEBUG_FLAGS="-DTESTERIO_TIMERS -DHDF_LOCKS -DLEGION_IDS_ARE_64BIT"
mpicxx -o tester_io.o -c tester_io.cc -I/opt/local/include/  -I../../runtime/ -I../../runtime//realm -I../../runtime//greenlet -I/users/gshipman/local/include -I/users/gshipman/local/include/ibv-condui\
t -g -Wno-array-bounds -DTESTERIO_TIMERS -DHDF_LOCKS -DLEGION_IDS_ARE_64BIT -DUSE_DISK  -march=native -DUSE_GASNET -DGASNETI_BUG1389_WORKAROUND=1 -DGASNET_CONDUIT_IBV -DUSE_HDF -DDEBUG_LOW_LEVEL -DDEBU\
G_HIGH_LEVEL -ggdb  -DCOMPILE_TIME_MIN_LEVEL=LEVEL_DEBUG   -Wall -Werror -Wno-format  -Wno-sign-compare
mpicxx -o ../../runtime//lowlevel_disk.o -c ../../runtime//lowlevel_disk.cc -I/opt/local/include/  -I../../runtime/ -I../../runtime//realm -I../../runtime//greenlet -I/users/gshipman/local/include -I/u\
sers/gshipman/local/include/ibv-conduit -g -Wno-array-bounds -DTESTERIO_TIMERS -DHDF_LOCKS -DLEGION_IDS_ARE_64BIT -DUSE_DISK  -march=native -DUSE_GASNET -DGASNETI_BUG1389_WORKAROUND=1 -DGASNET_CONDUIT_\
IBV -DUSE_HDF -DDEBUG_LOW_LEVEL -DDEBUG_HIGH_LEVEL -ggdb  -DCOMPILE_TIME_MIN_LEVEL=LEVEL_DEBUG   -Wall -Werror -Wno-format  -Wno-sign-compare
mpicxx -o ../../runtime//realm/runtime_impl.o -c ../../runtime//realm/runtime_impl.cc -I/opt/local/include/  -I../../runtime/ -I../../runtime//realm -I../../runtime//greenlet -I/users/gshipman/local/in\
clude -I/users/gshipman/local/include/ibv-conduit -g -Wno-array-bounds -DTESTERIO_TIMERS -DHDF_LOCKS -DLEGION_IDS_ARE_64BIT -DUSE_DISK  -march=native -DUSE_GASNET -DGASNETI_BUG1389_WORKAROUND=1 -DGASNE\
T_CONDUIT_IBV -DUSE_HDF -DDEBUG_LOW_LEVEL -DDEBUG_HIGH_LEVEL -ggdb  -DCOMPILE_TIME_MIN_LEVEL=LEVEL_DEBUG   -Wall -Werror -Wno-format  -Wno-sign-compare
In file included from ../../runtime//realm/runtime_impl.h:24,
                 from ../../runtime//realm/runtime_impl.cc:18:
../../runtime/activemsg.h: In static member function ‘static int ActiveMessageMediumNoReply<MSGID, MSGTYPE, FNPTR>::add_handler_entries(gasnet_handlerentry_t*, const char*) [with int MSGID = 201, MSGTY\
PE = LegionRuntime::LowLevel::RemoteFillArgs, void (* FNPTR)(MSGTYPE, const void*, size_t) = LegionRuntime::LowLevel::handle_remote_fill]’:
../../runtime//realm/runtime_impl.cc:436:   instantiated from here
../../runtime/activemsg.h:620: error: invalid application of ‘sizeof’ to incomplete type ‘MessageRawArgs<LegionRuntime::LowLevel::RemoteFillArgs, 201, dummy_short_handler [with MSGTYPE = LegionRuntime:\
:LowLevel::RemoteFillArgs], LegionRuntime::LowLevel::handle_remote_fill, 18>’
../../runtime/activemsg.h:622: error: incomplete type ‘MessageRawArgs<LegionRuntime::LowLevel::RemoteFillArgs, 201, dummy_short_handler [with MSGTYPE = LegionRuntime::LowLevel::RemoteFillArgs], LegionR\
untime::LowLevel::handle_remote_fill, 18>’ used in nested name specifier
make: *** [../../runtime//realm/runtime_impl.o] Error 1

**Comment by streichler** [comment]
This was fixed in the master branch with 3aee202, but it looks like that hasn't been merged into dma yet.  Assigning to Zhihao to either do the merge or cherry-pick this change if needed.

**Comment by jiazhihao** [comment]
I will merge the update-to-date master branch into dma branch in a few days. As a temporary fix, I have included  commit 3aee202 into dma branch, which should make it compile now.
