### ISSUE TITLE
map_inline with layout constraint

### ISSUE THREAD

**Issue by mpokorny** [StanfordLegion/legion#573]
I was trying an inline mapping with a layout constraint that required GLOBAL_MEM, and my code kept hitting the assertion 

.../runtime/realm/runtime_impl.cc:2439: Realm::MemoryImpl* Realm::RuntimeImpl::get_memory_impl(Realm::ID): Assertion `0 && "invalid memory handle"' failed.

It looks like there's a variable declaration for `target_memory` here
https://github.com/StanfordLegion/legion/blob/1c8ebca1fef222615f68f0d9aebd9d4484780f2d/runtime/mappers/default_mapper.cc#L2589
that is shadowing the one a few lines above it. After removing the second declaration, my code ran as I expected.

**Comment by lightsighter** [comment]
Thanks Martin! I've pushed a fix to the master branch. It will be in
upstream branches sometime tomorrow.

https://gitlab.com/StanfordLegion/legion/commit/60928d38ec55a00fb845c8721a08e1cdf1f681e1

Mike

**Comment by streichler** [comment]
@mpokorny can you confirm that this issue is fixed with @lightsighter 's change?

**Comment by mpokorny** [comment]
Yes, this issue was fixed by those changes.
