### ISSUE TITLE
zlib link error

### ISSUE THREAD

**Issue by mpokorny** [StanfordLegion/legion#577]
Since the addition of the `Legion_USE_ZLIB` CMake configuration option, my Legion build has been failing. Best I can tell, the problem arises when I build Legion with HDF5, my *libhdf5* is dynamically linked to *libz*, and I set `Legion_USE_ZLIB=ON`. In that configuration *liblegion.so* is built, but anything else that tries to link to it (for instance *libregent.so*) fails to link. Building with `Legion_USE_ZLIB=OFF` is successful, but I have not tried `Legion_USE_ZLIB=ON` together with `Legion_USE_HDF5=OFF`. Although I don't know that it is correct or optimal to do so, changing `PRIVATE` here
https://github.com/StanfordLegion/legion/blob/ca1437716819f48daaacc42bb41a04472c6e410b/runtime/CMakeLists.txt#L278
to `PUBLIC` solves the issue for me.

**Comment by streichler** [comment]
@mpokorny can you grab commit af2c1ce (should be in master shortly) and give this another try?  It's basically what you suggested above, and it seems to work for me.

**Comment by mpokorny** [comment]
Your commit works for me. Thanks
