### ISSUE TITLE
Realm Phase Barrier Recycling

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#581]
It would be nice if there was an opt-in way to have phase barriers recycle their generations once they have gone through all of them. This is an obviously unsafe thing to do as some barrier generations could have escaped and could still be "live" in the system somewhere, so it's up to the user to assert that it is safe to do this. However, if the user does opt-in to this behavior, then they don't need to worry about phase barriers running out of generations.

In the meantime, to help deal with this case today it would be helpful to just have a way to query how many generations a barrier has so the client can plan on when it will need to do something rather than just running out of barrier generations.

**Comment by streichler** [comment]
Adding the generations-per-barrier query is a short-term TODO.  Any sort of automated recycling of barriers is longer term.

**Comment by streichler** [comment]
`Realm::Event::MAX_PHASES` exists as of commit 861316c.  Reassigning to @lightsighter to use it on the Legion side.

**Comment by lightsighter** [comment]
Legion now uses this in the control replication branch with e26ee895a to detect when we're out of generations in a sharded trace template. When we detect barrier generation exhaustion we refresh all the phase barriers in the template so we can continue replaying.

Assigning this issue back to @streichler for the second part.

**Comment by streichler** [comment]
Issue #672 tracks possible future enhancements along these lines, but this part is now done.
