### ISSUE TITLE
Hotfix for the task inliner

### ISSUE THREAD

**Issue by magnatelee** [StanfordLegion/legion#582]
I found and fixed a bug in the task inliner in the `stable` branch. There was a bug in the check that determines whether the inliner can directly replace the parameter with the argument, which should have been sound but wasn't. The issue could affect inlined tasks that take arrays 
 or structs with array members as arguments and then mutate them inside. The fix is now in the `stable-inliner-patch`: https://gitlab.com/StanfordLegion/legion/tree/stable-inliner-patch

**Comment by streichler** [comment]
Commit dd1fb16 has made it into the stable branch and is part of the legion-19.09.1 release.
