### ISSUE TITLE
Writing to an element of an array-typed field does not require a write privilege

### ISSUE THREAD

**Issue by ldr709** [StanfordLegion/legion#586]
Writing to an array-typed field does not require a write privilege, only a read one. This makes the type system unsound. Related: https://github.com/StanfordLegion/legion/issues/436

Test [case](https://github.com/StanfordLegion/legion/blob/38b0bf61a58d1c7da492f061b509506a1a4ccd5e/language/tests/regent/compile_fail/array_write_privileges.rg)

**Comment by magnatelee** [comment]
This issue has been fixed as of 9b0bee33.
