### ISSUE TITLE
Writing to a complex typed field does not require any privilege

### ISSUE THREAD

**Issue by ldr709** [StanfordLegion/legion#587]
This is a soundness hole in the type system.

The test [case](https://github.com/StanfordLegion/legion/blob/38b0bf61a58d1c7da492f061b509506a1a4ccd5e/language/tests/regent/compile_fail/complex_write_privileges.rg) ought to fail in the type checker, but instead it type checks and then hits an assertion failure in code generation.

**Comment by magnatelee** [comment]
This issue has been fixed as of 9b0bee33.
