### ISSUE TITLE
Legion Prof: Regression - Missing Profiler Output

### ISSUE THREAD

**Issue by samuelkgutierrez** [StanfordLegion/legion#59]
Looks like we are missing profiler output. The profiling preamble containing metadata gets printed, the application executes and terminates normally, but no profiling info is actually provided. Tested with cgsolver example on master.

```
./cgsolver -hl:prof 1 -cat legion_prof -level 2
```

**Comment by lightsighter** [comment]
The problem is the Realm TASK_ID_PROCESSOR_SHUTDOWN tasks are not being called on all the Realm processors before Realm exits.

**Comment by lightsighter** [comment]
Actually it looks like the problem is that they are only being called on utility processors.  It would probably be best if they were still called on all processors, especially for the case where there are no utility processors.

**Comment by samuelkgutierrez** [comment]
Looks like b14f957129b4f8a9547c8195994a7b5a31247691 fixed it. Thanks!
