### ISSUE TITLE
Realm: incorporate MPI-based active message implementation as option

### ISSUE THREAD

**Issue by streichler** [StanfordLegion/legion#605]
This'll require some restructuring on my part to make the activemsg implementation somewhat pluggable, and then probably somebody else's work to dust off the code in gitlab PR 151 (https://gitlab.com/StanfordLegion/legion/merge_requests/151) to make the peg's shape fit the hole.

**Comment by streichler** [comment]
The first part of this (the modularization of the network backend) is there with commit d607d30.  Next up is making an MPI network module as an alternative to the current GASNet-1 module.

**Comment by streichler** [comment]
The MPI network layer is merged in as of commit 05a66970.  Thanks to @hzhou for doing most of the work on this.  This network layer is enabled by setting `REALM_NETWORKS=mpi` for the make-based build or `Legion_NETWORKS=mpi` for the cmake build.

The existing "gasnet1" (i.e. GASNet-1 or GASNet-EX using its GASNet-1 compatibility API) network layer is requested either by the new settings: `REALM_NETWORKS=gasnet1` and `Legion_NETWORKS=gasnet1` or the existing `USE_GASNET=1` (for make) and `Legion_USE_GASNet=ON` (for cmake) for backwards-compatibility.

**Comment by lightsighter** [comment]
How does the performance compare?

**Comment by streichler** [comment]
> How does the performance compare?

Unknown.  Please try it out on applications of interest and report back.  Let's open new issues for
any performance-related concerns though.

**Comment by lightsighter** [comment]
I'm seeing undelivered messages with this network. I'm running the `mpi_with_ctrl_repl` example in the `control_replication` branch with `mpirun -n 2 ./mpi_with_ctrl_repl -ll:force_kthreads` so both processes are running on the same node and intentionally leaving off the `--bind-to none` option to force as much randomness on the thread scheduling as I can. If you crank it up to `-n 16` you'll get a hang every time at least on sapling.

**Comment by lightsighter** [comment]
Worth noting that I'm also running in debug mode. The "interesting" backtraces show no evidence of a virtual channel hang, only messages with no preconditions on unordered virtual channels that haven't been delivered.

**Comment by hzhou** [comment]
@lightsighter I'll investigate.

**Comment by hzhou** [comment]
@lightsighter I am trying to reproduce what you described. Is this supposed to run on a single node with the command line:
```
mpirun -n 16 ./mpi_with_ctrl_repl -ll:force_kthreads
```
and you were seeing it hangs?

I am trying it on a ubuntu work station and it seems to complete ok. Were you running it in docker? Which mpi library were you using?

**Comment by lightsighter** [comment]
Yes, two processes on a single node. I'm seeing it hang in lots of different ways. The common theme seems to be a user event that is created and waited on in one process and then sent to another process where it is triggered. I can see that the event is being triggered on the remote node, but the event trigger and corresponding wake-up of the thread that waited on the event is not happening on the first node.

I'm using OpenMPI 3.1.3. I'm not running it inside docker, just standard Ubuntu Linux (although a very old machine).

**Comment by hzhou** [comment]
I just tried with OpenMPI 4.0 -- one just happened to be available on my machine -- and it seems to run ok. I'll try 3.1.3 later.

A difference I noticed that with OpenMPI, it shows following warnings:
```
[0 - 7f0bab898e80] {4}{threads}: reservation ('DMA request queue') cannot be satisfied
[1 - 7f001e1bbe80] {4}{threads}: reservation ('DMA request queue') cannot be satisfied
```
I am not sure whether this is relevant. I recall this might due to mpi-processes being bound-to certain cores -- probably OpenMPI's mpirun does that by default.

**Comment by hzhou** [comment]
OpenMPI 3.1.3 is ok on my side as well. I am using a self-compiled version.

**Comment by eddy16112** [comment]
I tried to compile Legion into both debug and release mode with Open MPI 3.1.3, and I did not see any issues when running the following in single node:

> mpirun -n 16 ./mpi_with_ctrl_repl -ll:force_kthreads

The default process binding of Open MPI is `-bind-to core`, I tried `-bind-to none`, and I still can not reproduce the bug. One way to check the installation of Open MPI is `ompi_info`, which tells configurations of Open MPI, although I do not think our MPIs will have significant differences.

**Comment by lightsighter** [comment]
I still see it 1 in 1000 runs. If I run the Legion test suite in the background it comes down to 1 in 100 runs. If you have access to `sapling` I can point you at a pair of frozen processes.

> A difference I noticed that with OpenMPI, it shows following warnings:

You should be getting those warnings. I intentionally said when I first reported the issue that you should be using `--bind-to core` (the default MPI setting) in order to force as much random thread scheduling as possible.

**Comment by hzhou** [comment]
@lightsighter I just repeated 10000 runs. I don't have access to `sapling`. Do you think you could reproduce it in docker and share with me the docker file (or image)?

**Comment by streichler** [comment]
@lightsighter can you try a few thousand runs with `--mca btl ^vader` on the mpirun command line?  Best I can tell, these packets are getting lost inside of the ompi implementation.

**Comment by lightsighter** [comment]
10K runs and no hangs with that flag. @streichler care to enlighten us as to why that makes the problem go away?

**Comment by streichler** [comment]
Closing this tracking issue.  Any new functional or performance concerns go into new issues.
