### ISSUE TITLE
Conversion Operator Inconsistency

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#613]
Legion has always supported an implicit conversion between the DomainT type into a Rect type when the index space is dense. Realm does not support and equivalent conversion between Realm IndexSpace and Rect types. When codes are compiled with c++11 or later this can create an issue because DomainT is just a type alias of Realm::IndexSpace and a conversion that used to work, no longer works.

**Comment by streichler** [comment]
I have convinced @lightsighter that the right way to fix this is to remove the implicit conversion from Legion's c++98 wrapper class.  It means that application code that was using it will have to replace occurrences of:
```
rect = domain;
```
with
```
assert(domain.is_dense());
rect = domain.bounds;
```
but I consider this preferable to having Legion and/or Realm have to assert-fail on application bugs (e.g. accidentally coercing a non-dense index space to a rectangle).

**Comment by streichler** [comment]
These changes are part of the master branch as of commit 67b7ba2.
