### ISSUE TITLE
realm: avoid eager fnptr->dso conversion for every code descriptor

### ISSUE THREAD

**Issue by streichler** [StanfordLegion/legion#615]
If you, hypothetically, had a Legion application that was over 3GB in size and had over 1M dynamic symbols and it registered thousands of tasks, this could get pretty slow...

**Comment by lightsighter** [comment]
Indeed.

**Comment by streichler** [comment]
This is hopefully much improved with commit 95d008a.  @lightsighter can you see if it speeds up your case?

**Comment by lightsighter** [comment]
I've confirmed that this is now much better. You can close the issue if you think we don't need to do any more work for it.
