### ISSUE TITLE
Legion: Attach names to fields

### ISSUE THREAD

**Issue by syamajala** [StanfordLegion/legion#617]
It would be nice if you could attach a name to a field and have tools like legion spy use that instead of an enum value. Additionally, maybe it would be useful if when you allocate a field you can give it an optional name?

**Comment by streichler** [comment]
The runtime allows you to attach a name to a field: https://github.com/StanfordLegion/legion/blob/stable/runtime/legion.h#L6189-L6200
but that's only part of the story.  You'd need the app (or regent) to actually do the attaching (regent doesn't appear to right now - @elliottslaughter ?) and you'd need legion spy to use the info (which it doesn't seem to from a quick grep - @lightsighter ?).

**Comment by syamajala** [comment]
Is there a way for me to get the attached name as well?

**Comment by streichler** [comment]
Yep.  And this is the tag you should use if you want to hopefully inter-operate with things like legion_spy: https://github.com/StanfordLegion/legion/blob/stable/runtime/legion/legion_config.h#L1294

**Comment by syamajala** [comment]
It seems to be working with legion spy as well. I guess this is sort of good enough for now. Although it would be nice to do it when you allocate a field, its not really necessary. 

Closing this.
