### ISSUE TITLE
Realm: DMA Engine Sparsity Gather/Scatter Optimization

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#622]
Realm should automatically infer when it is profitable to do gathers for bulk transfers of data and then scatters at the destination for sparse data movement. This is often more efficient than moving the sparse data in pieces as hardware is optimized for bulk data movement. The Realm path planner will have to figure this out and allocate the needed intermediate buffers for performing this optimization.

**Comment by lightsighter** [comment]
@amaleewilson Is doing the initial investigations into how to determine when it is good to perform this optimization for various kinds of transfers.

**Comment by streichler** [comment]
@lightsighter it would be great if we could identify/create a small app or two that uses this pattern in a performance-sensitive way to provide the necessary apples for comparison purposes.  Got any suggestions?

Theoretically, the implementation of this transformation should be straightforward in the DMA system.  The open question is the heuristic for when to use it.

**Comment by lightsighter** [comment]
Adding the S3D tag. :) Ghost cell exchanges in the Y and Z dimensions should gather, bulk copy, and then scattter. Pennant should do the same thing but for unstructured, although it's unclear if there is as much of a performance win.

**Comment by lightsighter** [comment]
We have concrete evidence that Soleil-X encounters this now as well. Ghost cell exchanges become very slow once we have to partition in the (fastest changing) X dimension (Fortran order for Regent) and we get copies that look like this:

120ms to move 2MB of data
63ms to move 7KB
102ms to move 715KB

This is affecting weak scaling of Soleil-X application performance as the DMA channels become the bottleneck on execution once we have to partition on the X dimension.

**Comment by streichler** [comment]
Can we do a run for just 2-3 iterations with `-level dma=2,inst=1` and put the logs somewhere I can look at them (they'll probably be too big to attach here).

**Comment by lightsighter** [comment]
@manopapad See above ^^^^^

**Comment by manopapad** [comment]
4 node run (no ghost cell exchanges on x): http://sapling.stanford.edu/~manolis/742031/
8 node run (ghost cell exchanges on all dimensions): http://sapling.stanford.edu/~manolis/742032/

**Comment by streichler** [comment]
The specific change requested here (local packing/unpacking of sparse data) was added with commit 7d12a8ed.  Other issues are tracking other improvements to scatter/gather (unstructured, affine, or both).

**Comment by lightsighter** [comment]
Do we need a separate issue for tracking packing/unpacking being done on GPUs or do you feel like other current issues handle that sufficiently?

**Comment by streichler** [comment]
Issue #621 is the umbrella issue for using kernels rather than cuMemcpy* to do GPU data movement.

**Comment by apryakhin** [comment]
What's the priority of this issue among the list of outstanding work items for Realm? Is there any context/data which is missing in order to make a decision with respect to this issue?

I would be interested to pick this up if the priority is appropriate in our roadmap

**Comment by apryakhin** [comment]
Ah, didn't notice that this has been done
