### ISSUE TITLE
GASNet-EX Integration

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#628]
We need to officially migrate Legion to using GASNet-EX so we can take advantage of some of its new performance features like active message sends that don't block but return if they don't have control flow credits. Migrating officially to GASNet-EX will also be a pre-requisite for getting access to memory kinds which we will need to for managing multi-rail NUMA-ness of NICs in machines like DGX boxes and also for getting access to GPUDirect once it lands in GASNet-EX.

**Comment by streichler** [comment]
This is dependent on #605 (assuming we don't want to just co-opt the GASNet-1 implementation, which I don't).

**Comment by pmccormick** [comment]
For ECP we can't loose track of #605.  In fact I'd encourage us to consider this more than just an enhancement when it comes to ECP's expectations of Legion.  Both GASNet-Ex and MPI are related to our risk mitigation and platform performance/portability strategy.

**Comment by streichler** [comment]
The preliminary pieces are in place for this and I've had enough discussions with the GASNet
folks that I think I have a plan.  The next step is to write it down that plan and have people 
review it, but I'm going to be optimistic and shoot for getting this done early next year.

**Comment by thompsonbry** [comment]
Supporting GPUDirect would be a big thing for us.  We are just starting the process of looking at realm binding onto GASNet over AWS libfabric.  We could definitely iterate with you on evaluation of performance for CPU/GPU compute over GASNet-Ex

**Comment by streichler** [comment]
@thompsonbry Yes, let's definitely talk.  It may actually be easier to do an initial exploration of the benefits of GPUDirect with the GASNet-1 interface, as I'm more familiar with its implementation and have already formed some ideas of how to tweak it to allow for GPUDirect transfers, but either way, we'll need a baseline implementation that does not use GPUDirect to test functionality and compare against.

**Comment by thompsonbry** [comment]
Sean, let’s try to pick up this thread next week. Hopefully schedules will
be a little less hectic.

Bryan

**Comment by streichler** [comment]
An initial implementation that's has held up under moderate testing so far is in master with commit 4d02198.
Closing this issue and tracking further updates/problems/suggestions in #986.
