### ISSUE TITLE
Reusable Pinned Message Buffers

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#631]
It would be nice if we could allocate buffers from Realm in pinned memory that Legion could directly pack data into and Realm can pass straight down to GASNet without needing to make copies of the data to be sent every time we cross through a level of abstraction.

**Comment by streichler** [comment]
@lightsighter does #693 meet this need, or were you hoping to hold onto buffers for longer periods of time?

**Comment by lightsighter** [comment]
Yes, I think #693 supersedes this issue so I'll close it.
