### ISSUE TITLE
Separate Compilation for Regent

### ISSUE THREAD

**Issue by alexaiken** [StanfordLegion/legion#637]
Regent compilation time is a problem, and what we really need to address it in a permanent way is separate compilation.

**Comment by elliottslaughter** [comment]
I have partial support for this in a branch. I believe it's gated on Bishop being smart enough to use dynamic task IDs. @magnatelee how much work is this?

**Comment by magnatelee** [comment]
My plan to fix this was to make Bishop use task names and memoize task IDs dynamically, instead of relying on global variables holding dynamic task IDs, which only works with Regent. Breaking this Regent dependency in Bishop is also a prerequisite for #604. This fix shouldn't take more than two days.

**Comment by elliottslaughter** [comment]
It's not quite ready to be merged, but I have a branch `separate-compilation-rebase-and-update` that can be tested. There is a new flag `-fseparate 1` which is required in order to use separate compilation. This is currently incompatible with Bishop.

**Comment by elliottslaughter** [comment]
Ok, this has been merged to master. There are some caveats, but this basic functionality works, so I'm going to close this for now.

 * Cannot currently be used with Bishop.

 * If `regentlib.start` is used, then the user must *also* use one of
   the following:

   * Incremental compilation (`-fincr-comp 1`)
   * Parallel compilation (`-fjobs 2` or higher)

   (Does not apply to `regentlib.saveobj` or `regentlib.save_tasks`.)
