### ISSUE TITLE
Field Polymorphism in Regent.

### ISSUE THREAD

**Issue by alexaiken** [StanfordLegion/legion#643]
Implement the proposal for field polymorphism in Regent.  There are a number of design issues, and so we will do something simple first and then extend it if it seems warranted.

**Comment by magnatelee** [comment]
An initial implementation of field polymorphism is available in the master branch as of 21744c92. This implementation contains support for the named and unnamed region projection that we discussed in the meeting, but does not have the renaming operator, which can be added later if we find a compelling use case. You can learn about how to use region projections and field polymorphic tasks using these test cases:

- `tests/regent/run_pass/call_task_polymorphic*.rg`
- `tests/regent/run_pass/region_projection.rg`
- `tests/regent/compile_fail/type_mismatch_call_polymorphic*.rg`
- `tests/regent/compile_fail/invalid_projection*.rg`
- `tests/regent/compile_fail/privilege_call_polymorphic*.rg`

@syamajala Can you pull and see if what is in the master branch matches your expectation?

**Comment by syamajala** [comment]
This seems to do what I want. Thanks!
