### ISSUE TITLE
Regent port of S3D

### ISSUE THREAD

**Issue by alexaiken** [StanfordLegion/legion#644]
Port the Legion version of S3D to Regent so that Jackie's group can write code more easily.  The principle outstanding issue at this point is the port of the main task, including

- [ ] wrapping the MPI-interop and any other functionality that Regent does not support directly so that we can continue to call the C++ implementations of these aspects of S3D

- [ ] Incorporating field polymporhism into the stencil kernels.  Depends on #643.

**Comment by syamajala** [comment]
This issue is also relevant for S3D:
https://github.com/StanfordLegion/legion/issues/603

**Comment by alexaiken** [comment]
I added the S3D tag.

**Comment by syamajala** [comment]
What exactly is the goal for this issue?

Is it considered done, when the 0d DME case runs and is correct? What about the 1d case?

The regent main task is now running, but the output is not correct.

**Comment by streichler** [comment]
@syamajala Can we get an update on the status of this?

**Comment by syamajala** [comment]
We ran and validated 5 cases. However, we changed the constants in the middle of the validation and should go back revalidate them. There were some issues that came up when trying to run on multiple nodes, but I believe they have been fixed now.

There is one issue with index spacing launching field polymorphic tasks:
https://github.com/StanfordLegion/legion/issues/783

Aside from that, the two other things to do are get subrank tasks working on multiple nodes and get cuda versions of all the tasks.

**Comment by syamajala** [comment]
This needs to be bumped to the next milestone. The outstanding issues are writing a Regent stencil (currently using C++ one), GPU versions of CalcSpeciesTask and CalcEnthalpyTask, a bug with running CalcViscosityTask on gpu for DME mechanism, subranks, tracing, startup time on large node counts. Integration of image-compositor with paraview, integration of flexflow.

**Comment by elliottslaughter** [comment]
S3D has been in Regent for a long time now.
