### ISSUE TITLE
Legion-Fortran interoperation

### ISSUE THREAD

**Issue by alexaiken** [StanfordLegion/legion#646]
We want to be able to call Fortran kernels from Legion.  Some work has already been done; what remains is:

Check that Fortran compilers can vectorize as we expect
A Fortran to Legion transformation using FLANG

**Comment by eddy16112** [comment]
@alexaiken I do not have permission to assign myself.

**Comment by lightsighter** [comment]
We've got a pull request for me to review. Adding this to the 20.03 milestone and assigning myself since I need to do a code review.
https://gitlab.com/StanfordLegion/legion/merge_requests/169

**Comment by lightsighter** [comment]
@eddy16112 Have you checked that the fortran compilers are still vectorizing fortran leaf tasks using the interop? I'm also inclined to break out the fortran-to-legion-with-flang thing here to a separate issue.

**Comment by eddy16112** [comment]
@lightsighter What do you mean by vectorizing fortran leaf tasks? If you mean vectorize data accessing of Accessor, the Fortran accessors are bind to the accessors of C API.

**Comment by lightsighter** [comment]
@eddy16112 We need to make sure the code for loops in leaf tasks compiled by fortran compilers still vectorizes the same way that it would if it were accessing normal fortran arrays.

**Comment by lightsighter** [comment]
This merge request is now finished https://gitlab.com/StanfordLegion/legion/-/merge_requests/178
