### ISSUE TITLE
realm: generic background worker threads

### ISSUE THREAD

**Issue by streichler** [StanfordLegion/legion#662]
The goal is to move away from subsystem-specific worker threads in Realm (e.g. dma threads, JIT threads, active message threads) and instead have a fixed number of threads (that can ideally be pinned to cores just like application threads) that collectively work on whatever background work that needs doing.  In addition to avoiding oversubscription of the "background cores" and the resulting uncertainties in latencies, this allows many more things to be foisted off to a background worker instead of having to be done by a thread that calls into Realm.

The `bgwork` branch has a partial implementation of this.  There is work to move the remaining dedicated threads' work into the new framework, let dedicated threads (optionally) help out when they are bored, and add some profiling support.

**Comment by lightsighter** [comment]
On which side of the line will the utility processor threads fall?

**Comment by streichler** [comment]
The current thinking (which is not set in stone) is that utility processors would retain their dedicated thread, but those threads might be much more willing to help with background work when the corresponding utility processor is idle.

IO processors are likely to remain in their current state as threads without an assigned core that do not help with background work, because the whole point of IO processors is that we don't have the hooks to know when an IO thread is idle (or if it's just "idle" because the thread is in the kernel doing stuff).

Another funny one is the threads that GPU processor tasks run in.  This will likely need to be configurable.  We'd like them to be like IO processors, but if an application does any serious CPU-side work in them, we'll probably want them to be more like the utility procs.

**Comment by streichler** [comment]
The first wave of changes is likely to land in the master branch in the next few days (you can look at them right now in the `bgwork` branch if you want), so I want to summarize the externally-visible changes for folks:

At a high level, most of the job-specific (e.g. "DMA thread" or "active message handler thread") non-processor-related threads go away (at least by default) and are replaced with a pool of "background worker" threads that can work on any non-task-body activity needed in the Realm runtime.  Additionally, utility processors can be configured to add their resources to the background worker pool when they are idle.  The result should be fewer total threads presented to the OS, fewer kernel thread context switches required to perform mixed background workloads, and a better ability to handle bursts in activity of any particular type.

The number of dedicated background work threads is set by the following parameters:
* `-ll:bgwork` (default = 1) threads are created in a NUMA-agnostic way, and can be optionally pinned to dedicated cores with `-ll:bgworkpin 1`.
* `-ll:bgnuma` (default = 0) threads are created in each NUMA domain, and can be optionally pinned with `-ll:bgnumapin 1`.  These workers know not to take work that has affinity to a different NUMA domain, but no work is flagged that way right now.  (Intra-NUMA-domain memcpys will be the first to use this.)

Background workers will sleep on condition variables by default when the work queues run dry, but response time can be improved by telling them to spin for a while first (`-ll:bgspin`, units are nanoseconds).

Breaking it down by Realm subsystem:
1. The default number of deppart workers (`-dp:workers`) changes from 1 to 0.  All deppart microops can be performed (concurrently) on any generic background work threads.
2. Triggering of events with a wide fanout can be offloaded to background workers, improving the responsiveness of the triggering thread.
3. The default number of dedicated GASNet polling threads (`-ll:amsg`) changes from 1 to 0.  Polling can be performed by any background work thread instead.
4. The dedicated active message handler threads (`-ll:ahandlers`) are gone.  Handlers can be called in any/all background work threads, with the current limitation that messages from a given source node are still handled sequentially (due to known (and probably unknown) message ordering requirements in Realm).
5. Both utility processors and normal CPU processors can be configured to pitch in and do background work when idle.  The amount of time they spend doing work (and therefore a rough upper bound on the hit on response time) is controlled via the `-ll:util_bgwork` (default = 100 microseconds) and `-ll:cpu_bgwork` (default = disabled) configuration parameters.  (There is a mechanism to shorten the timeslice if a task becomes ready, but not all background work items can
be interrupted.)
6. All of the "new dma" (`-ll:dma`) threads go away.  Many channels (in particular, the memcpy channel) can spread their work over all available background workers.  (Note: the "legacy" dma thread that does fills and reductions is untouched, but will vanish as soon as fills and reductions are moved to the "new" (i.e. 2015) dma paths.) 
7. The dedicated GPU worker thread (the ones that queued up DMAs and reaped events, not the one running actual GPU tasks) goes away by default but can be re-enabled with `-ll:gpuworkthread 1`.

If anything here is confusing or you know of an omission, let me know and I'll fix it.  Suggestions are welcome too.  In particular, I can easily be convinced that the default number of background worker threads should be larger than 1.

**Comment by streichler** [comment]
My plan is to merge this into the master branch right after the 20.06 stable snapshot, so adjusting the milestone accordingly.

**Comment by streichler** [comment]
This has been in master for a while.  Closing.
