### ISSUE TITLE
Regent: regions not filled when launched from C++

### ISSUE THREAD

**Issue by sparkasaurusRex** [StanfordLegion/legion#669]
I've been following `language/examples/embed.rg` to figure out how to launch Regent tasks from C++. My code worked until after commit `482f7e656`. After that commit, my regions inside of the Regent task are filled with zeros instead of the data I filled them with. If I run my code from Regent instead of C++ then everything works fine. I'm using `AttachLauncher::attach_array_aos()` to fill my regions and I'm guessing that is what is broken. Let me know if you need more information.

**Comment by lightsighter** [comment]
If you're also running your code with Regent then you're never using `AttachLauncher::attach_array_aos`. The C API that Regent relies on uses `AttachLauncher::attach_array_soa`. Are you sure your data is actually laid out in AOS format?

**Comment by sparkasaurusRex** [comment]
Yeah, I'm pretty sure everything is in AOS format and it appears to be working on the older commit.

**Comment by sparkasaurusRex** [comment]
But I could be wrong since I don't know much about the internal layout of regions.

**Comment by streichler** [comment]
@sparkasaurusRex is the code small enough (or can be trimmed down while still reproducing the issue) to paste here?  How are you creating/filling the area before attaching to it?  And can you confirm that exact commit is where things changed?  (It doesn't seem like it should be related.)

**Comment by streichler** [comment]
Well, as the author of the apparently-offending commit and the person who can see the repro case, I think @magnatelee has been volunteered as the initial owner of this.  Ask for help if you need it.  :)

**Comment by lightsighter** [comment]
I think we've tracked this down to a Realm bug that occurred after the merge of the defalloc branch.

**Comment by sparkasaurusRex** [comment]
Let me know when you push a fix and I'll test it.

**Comment by streichler** [comment]
@sparkasaurusRex please try again with commit c4ba14c in master.

**Comment by sparkasaurusRex** [comment]
Appears to work. Thanks!
