### ISSUE TITLE
Regent: Uninitialized data warning produced for internal Regent operation "Mapping"

### ISSUE THREAD

**Issue by manopapad** [StanfordLegion/legion#671]
The following code snippet:

```
import 'regent'
task main()
  var r = region(ispace(int1d,10), double)
  fill(r, 1.0)
  for i in r do
    regentlib.c.printf('%lf\n', r[i])
  end
end
regentlib.start(main)
```

produces the output:

```
[0 - 7f38ac3b7700] {4}{runtime}: [warning 1071] LEGION WARNING: Region requirement 0 of operation Mapping (UID 3) in parent task main (UID 1) is using uninitialized data for field(s) ,101 of logical region (1,1,1) (from file /home/manolis/sw/legion/runtime/legion/legion_ops.cc:539)[warning 1071] 
For more information see:
http://legion.stanford.edu/messages/warning_code.html#warning_code_1071

1.000000
1.000000
1.000000
1.000000
1.000000
1.000000
1.000000
1.000000
1.000000
1.000000
```

**Comment by elliottslaughter** [comment]
I think this is somewhat related to #349. Because we eagerly map, it actually happens before the fill. If we were to delay the mapping, this ought to go away. (Note this is more sophisticated than the easiest fix for #349, so it may get fixed later than that bug.)

**Comment by manopapad** [comment]
Note that this happens even for inner tasks (which shouldn't inline-map anything?). The following snippet produces the same error as above:

```
import 'regent'
task foo(r : region(ispace(int1d), double))
where writes(r) do
  for i in r do
    r[i] = 1.0
  end
end
task bar(r : region(ispace(int1d), double))
where reads(r) do
  for i in r do
    regentlib.c.printf('%lf\n', r[i])
  end
end
__demand(__inner)
task main()
  var r = region(ispace(int1d,10), double)
  foo(r)
  bar(r)
end
regentlib.start(main)
```
```
[0 - 7f59156ea700] {4}{runtime}: [warning 1071] LEGION WARNING: Region requirement 0 of operation foo (UID 3) in parent task main (UID 1) is using uninitialized data for field(s) ,101 of logical region (1,1,1) (from file /home/manolis/sw/legion/runtime/legion/legion_ops.cc:539)[warning 1071] 
For more information see:
http://legion.stanford.edu/messages/warning_code.html#warning_code_1071

1.000000
1.000000
1.000000
1.000000
1.000000
1.000000
1.000000
1.000000
1.000000
1.000000
```

**Comment by streichler** [comment]
Once this issue is cleaned up, we should try to set `LEGION_WARNINGS_FATAL=1` for regent in CI as well and scrub individual regent tests of other uninitialized data (or other) warnings.

**Comment by elliottslaughter** [comment]
It just occurred to me that there is an easier fix to this issue that doesn't require either general support for `discard` or a fix for #349, because we can just make codegen issue WD for this particular region requirement and it's always safe because it is by definition the first mapping of this region.

**Comment by elliottslaughter** [comment]
This should be fixed in d237068fb31fd711085140205850fc35f8ce9230.

**Comment by manopapad** [comment]
The first testcase is fixed, but the second one still fails with the same message.

**Comment by elliottslaughter** [comment]
Right, the second test case requires proper support for discard, since no inline mapping is created at all in that case. I'm going to open #721 to track this (since it's been mentioned in multiple issues now) and close this one.
