### ISSUE TITLE
Legion spy and legion disagree on cases where partition disjointness can be detected dynamically

### ISSUE THREAD

**Issue by dillonhuff** [StanfordLegion/legion#68]
I re-ran the randomized tests with the restriction that all region requirements have exclusive coherence and read write access. The number of errors reported by legion spy actually increased slightly over the tests with random privileges and coherences.

After looking through the tests for a simple case and presenting it to Sean, Wonchan, and Elliot it seems that the problem is that legion can dynamically detect when 2 partitions of an index space are disjoint, but legion spy does not realize this. I have attached a simple case that legion spy reports an error on when 2 partitions of the top level index space are disjoint, but which legion spy and legion agree on when the 2 partitions are overlapping.

Below is a link to a gist containing a (somewhat) simple test case and a fixed version of the same case:

https://gist.github.com/dillonhuff/19c4f57a73b1fc4a8c02

**Comment by streichler** [comment]
Assigning to Mike first.  The consensus here was that Mike should add a legion spy logging call for when
dynamic disjointness is detected, and then Wonchan should make legion spy do the right thing with that info.

**Comment by lightsighter** [comment]
Dynamic independence tests should be off when the runtime is compiled for Legion Spy:

https://github.com/StanfordLegion/legion/blob/master/runtime/legion/runtime.cc#L14778-L14784

Can you confirm that the dynamic tests are actually happening?  Once we understand how that is occurring, then I'll be happy to add in the logging calls later.  @magnatelee do you have any preferences for what they look like since you'll have to parse them?

**Comment by streichler** [comment]
We were able to change whether not the HLR reported a dependence between the two tasks by only changing the ranges that were colored in the two separate partitions of the parent region, so it seems like that boolean there isn't controlling everything it should be?

**Comment by lightsighter** [comment]
There are only two places where dynamic disjointness tests are performed.  Here they are and they are both guarded by the proper flag:

https://github.com/StanfordLegion/legion/blob/master/runtime/legion/region_tree.cc#L5683-L5684
https://github.com/StanfordLegion/legion/blob/master/runtime/legion/region_tree.cc#L6914-L6915

Can you guys run in a debugger and see if you are hitting either of those cases?  The only way that we could not be setting this flag properly would be if there was a race of the static initializer with the value being set when the runtime starts.

**Comment by magnatelee** [comment]
I don't have any preference but you can just print logs like 'Mapping Independence <ctx> <prev_op_id> <next_op_id>', assuming that the independence is implied by no dependence between any pairs of region requirements of the two tasks.

**Comment by magnatelee** [comment]
actually, sean and I just agree that the independence statement should be between two regions, not between two tasks. So, the syntax would be something like 'Mapping Independence [ctx] [prev_op_id] [prev_idx] [next_op_id] [next_idx]'.

**Comment by lightsighter** [comment]
When I run case7.cc on my local machine it passes just fine.  When I run in a debugger I'm not hitting either of the dynamic independence tests as long as I compile with -DLEGION_SPY.  My guess is that the start-up race with the static initializer and setting the value to false in the start-up of the runtime is going to be source of the problem, but it would be good for you guys to confirm that.

In terms of the logging statements, I was thinking more along the lines of reporting the actual results of the dynamic non-interference tests, so something along the lines of 

'Dynamic Region Independence [index_space_name1] [index_space_name2]'
'Dynamic Partition Independence [index_partition_name1] [index_partition_name2]'

And then letting Legion Spy use that information as part of its analysis.

**Comment by streichler** [comment]
Dillon, can you double-check which branch/commit you're on, and if it's not a very recent version of master, try again with that?

**Comment by dillonhuff** [comment]
This was my bad. The failure occurs on stable, not master. I just re-ran
the tests (with only READ_WRITE permissions and EXCLUSIVE coherence) and
the error does not occur with the version of master from Tuesday.

**Comment by lightsighter** [comment]
Keep the bug open so we know we still need to add dynamic independence check support for Legion Spy.

**Comment by lightsighter** [comment]
I added support for logging the results of the dynamic independence tests here:

https://github.com/StanfordLegion/legion/blob/master/runtime/legion/legion_spy.h#L108-L120

Reassigning to Dillon and Wonchan to update Legion Spy to use the results of the dynamic independence tests in Legion Spy.  Once you guys have added support to Legion Spy, you can remove the switch that disables the dynamic independence tests for Legion Spy (below) and close the issue.

https://github.com/StanfordLegion/legion/blob/master/runtime/legion/runtime.cc#L14778-L14784
