### ISSUE TITLE
Enabling bounds checks with NVCC results in errors (and issues)

### ISSUE THREAD

**Issue by marcinz** [StanfordLegion/legion#685]
I am using CUDA 10.2 and the `control replication` branch of Legion (f604a1b). Enabling bounds checks with NVCC (`NVCC_FLAGS="-DBOUNDS_CHECKS`) causes plenty of warnings and some error messages (see attachments).

[output.log](https://github.com/StanfordLegion/legion/files/3826584/output.log)

**Comment by lightsighter** [comment]
@marcinz I believe I've fixed this bug in the master and control_replication branches. It won't be in the legate_stable branch quite yet since I only want to push to that occasionally. I'm assigning it back to you to confirm that it is fixed.

**Comment by marcinz** [comment]
I am still getting:

```
legion/runtime/legion/legion.inl(1601): error: cannot use an entity undefined in device code
```

I'll take a look at it.

**Comment by marcinz** [comment]
a1045c665bab5543f0c106803bf0025d39ed0bdd fixed the remaining issues.
