### ISSUE TITLE
Tracing for Index Space Launches with Postconditions

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#688]
Support for tracing with index space launches with postconditions is incomplete.

https://gitlab.com/StanfordLegion/legion/blob/master/runtime/legion/legion_tasks.cc#L7618-7627

**Comment by magnatelee** [comment]
This should be fixed by commit 152886f4.

**Comment by magnatelee** [comment]
The CI seems happy now. Closing the issue.
