### ISSUE TITLE
Prof: Utilization does not take into account entirely idle processors

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#691]
See e.g. this profile:

http://sapling.stanford.edu/~eslaught/circuit.run1_no_cr/prof_2x1_r0

The GPU utilization plot shows 100% utilization, when in fact the GPU on node 1 is never used at all (and so it doesn't show up in the plot at all). Utilization should be 50% for this plot.

**Comment by seemamirch** [comment]
Commit 990ad63a547a913b6c7df6b31ce1ca9f80b642a5 closes #691
