### ISSUE TITLE
Regent: associate tasks with mappers

### ISSUE THREAD

**Issue by manopapad** [StanfordLegion/legion#696]
Currently every task launch in a Regent application gets passed to the same mapper (the one with ID 0). This is problematic if we want to combine two different libraries into the same application, each with their own mapper (e.g. @aheirich's visualization framework inside Soleil-X). Also, the user's custom mapper currently has to handle internal Regent tasks, which should really be handled by a custom Regent mapper.

Instead, Regent should support setting the mapper ID on task launches. One way to do this is per launch, similar to the suggested syntax for attaching mapper tags from https://github.com/StanfordLegion/legion/issues/438:

```
__demand(__mapper(42))
foo()
```

However, I think it is generally sufficient (and way less noisy) to associate mapper IDs "in bulk", e.g. once per module/file, or once per task, to be used on every launch of that task:

```
__demand(__mappper(42))
task foo() ... end
```

or

```
task foo() ... end
foo:attach_mapper_id(42)
```

As a second step, we could support overriding this default on a per-site basis.

**Comment by elliottslaughter** [comment]
This is supported in 429a17fb8553c828384996b24cebef2738919413 via the syntax `foo:set_mapper_id(42)`.
