### ISSUE TITLE
Legion: `install.py` does not handle cmake flags correctly when passed as options

### ISSUE THREAD

**Issue by sparkasaurusRex** [StanfordLegion/legion#700]
I need to pass a flag to cmake, but I get the following error.
```bash
$ ./install.py --extra -DLegion_HIJACK_CUDART=OFF
...
install.py: error: argument --extra: expected one argument
```
The problem is that `argparse` thinks that the next `-` means I'm giving another argument. I think we need another option like `--cmake-flag` that appends `-D` to every flag that is passed.

**Comment by elliottslaughter** [comment]
Can you try `--extra=-DLegion_HIJACK_CUDART=OFF`?

**Comment by sparkasaurusRex** [comment]
I think that actually works. I'll close this once I confirm.
