### ISSUE TITLE
Accessors for Multiple Region Requirements

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#703]
Tasks can specify constraints that region requirements are allocated in the same physical instance. Often these tasks want to access the data in these different region requirements with the same accessor. In these cases we need the ability to create accessors for multiple region requirements.

@ipdemes for visibility.

**Comment by ipdemes** [comment]
@lightsighter : you will also need to add logic for correct bounds checking for aggregated Physical Instance

**Comment by lightsighter** [comment]
Yes, the aggregated accessors will still perform sound and precise privilege and bounds checks when enabled.

**Comment by lightsighter** [comment]
@ipdemes Will the region requirements for this accessor all have the same privilege level or were you envisioning cases with mixed privileges on the different region requirements?

**Comment by ipdemes** [comment]
They will have different privileges

**Comment by lightsighter** [comment]
That means that we'll no longer be able to enforce type safety for these kinds of accessors, e.g. you might be able to write something that you only have read-privileges on. We could add dynamic checks for that, but it would incur overhead. You would no longer be able to guarantee full safety of privileges at compile time.

**Comment by ipdemes** [comment]
We are currently using `UnsafeFieldAccessor`  which doesn't do any checks as well, so it wouldn't be any worse

**Comment by lightsighter** [comment]
There is now support in the `master` and `control_replication` branches for a `MultiRegionAccessor`:

https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/legion.h#L2436-2543

@ipdemes Do you want to propose any changes or try it out before we close this issue?

**Comment by ipdemes** [comment]
@lightsighter : I will try it today.
Does this accessor assumes that these regions were mapped to 1 physical instance, or this is not required?

**Comment by lightsighter** [comment]
In order to use this accessor it is required that all the region requirements were mapped to the same physical instance. The accessor constructor will verify that this is the case.

**Comment by ipdemes** [comment]
OK, thanks. And it will work within Kokkos kernel?

**Comment by streichler** [comment]
@irina It looks like the Legion `MultiRegionAccessor` has a single Realm accessor named `accessor` inside it, so yes, it should work with Kokkos kernels the same way.

**Comment by lightsighter** [comment]
Support for this is in the master branch and has a FleCSI test to confirm that it works.
