### ISSUE TITLE
Realm Check for Catchup Assertion

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#71]
Saw this assertion tonight.  In the process of handling a remote trigger active message, Realm first has to get the event implementation.  When it does this, it checks for catch-up, but inside the catch-up check there is an assertion that it is only happening for a remote event.  However, in this case, the event was remote, but it's not anymore.  I'm pretty sure it is safe to remove the assertion, but you should check.

#6  0x00007f2d02659a76 in __assert_fail_base (
    fmt=0x7f2d027ab370 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0xe4f050 "owner != (((void)0), (gasnet_node_t)gasneti_mynode)", 
    file=file@entry=0xe4eec0 "/home/mebauer/extern_legion/legion/runtime//realm/event_impl.cc", 
    line=line@entry=531, 
    function=function@entry=0xe501e0 <Realm::GenEventImpl::check_for_catchup(unsigned int)::__PRETTY_FUNCTION__> "void Realm::GenEventImpl::check_for_catchup(Realm::Event::gen_t)") at assert.c:92
#7  0x00007f2d02659b22 in __GI___assert_fail (
    assertion=0xe4f050 "owner != (((void)0), (gasnet_node_t)gasneti_mynode)", 
    file=0xe4eec0 "/home/mebauer/extern_legion/legion/runtime//realm/event_impl.cc", line=531, 
    function=0xe501e0 <Realm::GenEventImpl::check_for_catchup(unsigned int)::__PRETTY_FUNCTION__> "void Realm::GenEventImpl::check_for_catchup(Realm::Event::gen_t)") at assert.c:101
#8  0x0000000000d140c0 in Realm::GenEventImpl::check_for_catchup (this=0x7f2c8407bdb0, 
    implied_trigger_gen=8) at /home/mebauer/extern_legion/legion/runtime//realm/event_impl.cc:531
#9  0x0000000000ca3d9c in Realm::RuntimeImpl::get_genevent_impl (this=0x28049c0, e=...)
    at /home/mebauer/extern_legion/legion/runtime//realm/runtime_impl.cc:1262
#10 0x0000000000d14774 in Realm::EventTriggerMessage::handle_request (args=...)
    at /home/mebauer/extern_legion/legion/runtime//realm/event_impl.cc:700
#11 0x0000000000cba94d in IncomingShortMessage<Realm::EventTriggerMessage::RequestArgs, 147, &Realm::EventTriggerMessage::handle_request, 6>::run_handler (this=0x7f2c94007580)
    at /home/mebauer/extern_legion/legion/runtime/activemsg.h:336
#12 0x0000000000d40c9d in IncomingMessageManager::handler_thread_loop (this=0x55e4860)
    at /home/mebauer/extern_legion/legion/runtime//activemsg.cc:770
#13 0x0000000000d48e20 in Realm::Thread::thread_entry_wrapper<IncomingMessageManager, &IncomingMessageManager::handler_thread_loop> (obj=0x55e4860)
    at /home/mebauer/extern_legion/legion/runtime//realm/threads.inl:127
#14 0x0000000000cee0b9 in Realm::KernelThread::pthread_entry (data=0x55e4ac0)
    at /home/mebauer/extern_legion/legion/runtime//realm/threads.cc:555
#15 0x00007f2d03700182 in start_thread (arg=0x7f2cfcfd2700) at pthread_create.c:312
#16 0x00007f2d02724fbd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

The event itself looks like a normal event (0x20001000000000be,0x9) and this assertion happened on node 1 out of a 2 node run.

**Comment by streichler** [comment]
This code has been deleted, so it doesn't matter any more...
