### ISSUE TITLE
realm/legion: pad instances (by default?) to avoid power-of-2 strides between fields/instances

### ISSUE THREAD

**Issue by streichler** [StanfordLegion/legion#710]
It's fairly common for applications to use index spaces that are a power of 2 in size.  When multiple instances are created (or multiple fields in the same instance), the address offset between different fields/instances then ends up being a power of 2 as well (Realm memories do not put heap-management metadata in the same place, so instances appear back to back), which can dramatically decrease the effective size of processor caches.  We should probably add and/or advertise a way for mappers to control this padding, but then also make the default be to add a small amount of padding when instance sizes are multiples of large powers of 2.

**Comment by lightsighter** [comment]
Legion already has support for [offset constraints](https://gitlab.com/StanfordLegion/legion/blob/master/runtime/legion/legion_constraint.h#L569-591) in the layout constraints that are specified when creating an instance. Users should be able to use these constraints to pad instances with some extra bytes. I've hooked these constraints up to the realm layout creation logic with 019850d80. @streichler will have to say whether or not Realm will actually honor them correctly or not.

**Comment by streichler** [comment]
Offset constraints don't help for SOA or for fields in separate instances I don't think? @lightsighter can we address this entirely in the instance layouts you're building (e.g. by making sure the `bytes_used` field in an instance layout is never a multiple of common L1 cache sizes)?

**Comment by lightsighter** [comment]
Legion offsets will still help even with SOA and fields in separate instances. They will put padding before the data is stored. If the mapper puts offsets on some instances and not others then we'll get the effect that we want.

**Comment by streichler** [comment]
Now that Legion is building its own instance layout constraints, Realm no longer has any control over how things are aligned.

**Comment by lightsighter** [comment]
I'm going to close this issue tomorrow unless someone speaks up because the offset constraints in Legion allow users to pad their instances themselves now. @ipdemes @jpietarilagraham @gshipman @tuxfan @pmccormick

**Comment by streichler** [comment]
Can you include (or point at) an example here of what the code looks like to arrange for fields in different instances to have different starting alignments?  For example, I don't think it's clear to everyone what the offset here is relative to:
https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/legion/legion_constraint.h#L580

**Comment by lightsighter** [comment]
The offset is relative to either the beginning of the instance or the previous field depending on the ordering of the fields in the field constraints. If your instance only has one field, then you give an offset of N bytes and thereby get an extra N bytes of padding in your instance. Then it's just a matter of picking values of N for different instances to avoid conflict misses in the cache.

**Comment by elliottslaughter** [comment]
Are you promised a certain default starting alignment? Because otherwise picking an offset against an unspecified alignment seems like it doesn't accomplish anything.

**Comment by lightsighter** [comment]
Well that's what the alignment constraints are for. So if you set both alignment and offset constraints then you will have total control. If you only set offset, then you're operating on runtime's preferred alignment for the machine (probably 16 byte).

**Comment by jpietarilagraham** [comment]
Here is an example of how we did it for FleCSI:

```
        static size_t offset = 0;
        for(auto fid : task.regions[indx].privilege_fields) {
          Legion::OffsetConstraint offset_constraint(fid, offset);
          layout_constraints.add_constraint(offset_constraint);
          offset += 64;
        } // for fid
```

I agree that this issue has been addressed.

**Comment by lightsighter** [comment]
Thanks for the code. We'll point anyone who has a similar problem to this issue as it will remain searchable in the future.
