### ISSUE TITLE
Regent: deterministic NaN only on sapling GPUs

### ISSUE THREAD

**Issue by mariodirenzo** [StanfordLegion/legion#712]
One of the unit tests that I have written to check the correctness of my solver fails deterministically with a NaN when executed on the GPUs of Sapling.
On the other hand, it succeeds if:
- run on CPUs on my workstation
- run on GPUs on Lassen
- run on CPUs on Lassen
- run on CPUs on sapling
- run on GPUs on sapling deactivating the auto-parallelizer

I can provide all the instruction to reproduce the issue

**Comment by lightsighter** [comment]
This sounds a little bit like a cuda launch error that is being silently ignored. I'm inclined to chalk it up to the very old GPUs/software stack on sapling. Assigning to @magnatelee to decide what he wants to do about it.

**Comment by mariodirenzo** [comment]
Procedure on how to reproduce the NaN on sapling:
- source my `~/.bashrc` in your session
- go into the directory `~/prometeo/solverTests` of my account on sapling.
- execute the test using `USE_CUDA=1 python ./test.py -v solverTest.test_BoundaryLayer`
- the solver will fail with a message like `test_BoundaryLayer (__main__.solverTest) ... assertion failed: NaN detected! Debug fields dumped in debugOut` and will dump a series of debug files `BoundaryLayer/1x2x1/sample0/debug[ID]_iter[iteration_number]_[RK_substep]` containing a few fields computed in the calculation that can be used to check where the NaN was produced. The ID of the debug are sequentially positioned in the algorithm of the solver and can be identified by looking at the file `~/prometeo/src/prometeo.rg`
- to inspect these files you can use `python ../../whereIsNaN.py BoundaryLayer/1x2x1/sample0/[debug_output_folder]`

if a new version of the solver needs to be compiled the command is `AVERAGES=0 DEBUG_OUTPUT=1 make -j -C ~/prometeo/src/ &`

**Comment by mariodirenzo** [comment]
I forgot to write that the failing run is validated by the logical and physical analysis of legion_spy and that the code passes the bound checks (on CPUs)

**Comment by elliottslaughter** [comment]
@mariodirenzo Is this still relevant?

**Comment by mariodirenzo** [comment]
This issue is very old. I lost track of the version of HTR that was producing the errors. Most likely this was a version of the code that was fully implemented in Regent and was using the auto-parallelizer. That version is not been operational since 2020.
I think that we can close this
