### ISSUE TITLE
DefaultMapper::slice_task allocates P^D memory

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#717]
The slice_task implementation in the default mapper allocates a vector of size `P^D` where `P` is the number of processors in the system and `D` is the number of dimensions in the launch. For larger numbers of dimensions, and larger numbers of processors, this can easily exceed available memory. E.g. an 8D launch with `-ll:cpu 16` will result in 16^8 elements being allocated.

The offending line is: https://github.com/StanfordLegion/legion/blob/ec885f8105dc0d779bf658c6a0cc5c498c477650/runtime/mappers/default_mapper.cc#L1311

The solution is probably to switch back to using `default_select_num_blocks` to select the block sizes, but that's currently blocked on unrelated template errors in template instantiation for `Point`.

**Comment by elliottslaughter** [comment]
Tentative fix pushed to the branch `default-mapper-fix-slice-task`, will merge once we sort out the template issues.

**Comment by lightsighter** [comment]
I like the new mappers tag, there should be more mapper issues.

**Comment by elliottslaughter** [comment]
This has been merged as of 6227da359ce148edfe429bc5c9678c30c745ba40.
