### ISSUE TITLE
Generic Python Script for Legion

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#726]
I think we need to come up with a generic script for running Python programs in Legion. I feel like we are reinventing the wheel again and again across Pygion, Legate, and FlexFlow. The script should support Python scripts as files, running interactively with an interpreter, and with a Jupyter notebook. Someone tell me if they think this is a bad idea, otherwise we should do it soon.

**Comment by streichler** [comment]
Do we need a script at all?  Wouldn't it be nicer to just `import legion` from any old python script and have the right thing happen?  (This is how mpi4py works.)

**Comment by lightsighter** [comment]
That's actually not what I'm talking about here. I want something that starts running a Python program inside a top-level task running on a Python processor, so you need all the infrastructure to start-up Legion first (not the Python interpreter), and then execute whatever the Python interpreter/Jupyter notebook code would have done.

**Comment by lightsighter** [comment]
In particular I completely want to avoid the mpi4py model so that we can have multiple python interpreters associated with a single Legion runtime using subprocesses eventually.

**Comment by streichler** [comment]
I don't think these things are mutually exclusive.  With the `import legion` approach, you'd be using the existing python interpreter as the first python processor (probably via an implicit top level task), and then a choice to spin up additional python interpreters in subprocesses ought to be possible.  (The potential complications would come from trying to reinitialize the python interpreter in the subprocess, but in the worst case we could move to a full fork+exec spawning of subprocesses.)

**Comment by lightsighter** [comment]
How are we going to prevent the python interpreter from polluting the address space with all its global variables for any python interpreters we want to ultimately create in subprocesses?

**Comment by elliottslaughter** [comment]
I think the only option guaranteed to work would be to fork+exec, though perhaps you could just fork and reuse the original interpreter (since you're in a new process anyway, you don't care about the GIL, but you will inherit some dirty state from the execution in the original interpreter).

Otherwise I'd ask what's wrong with the existing `legion_python` binary? It's a bit tied to Pygion at the moment, but it wouldn't be hard to generalize it, especially if we pull out a common set of CFFI bindings.

**Comment by lightsighter** [comment]
> Otherwise I'd ask what's wrong with the existing legion_python binary?
No support for command line interpreter, juypter notebooks, or control replication (including support for hijacking print deduplication).

**Comment by elliottslaughter** [comment]
> command line interpreter

What does that mean?

> control replication (including support for hijacking print deduplication)

Ok, we're missing the print deduplication, but otherwise we already support this via "script mode": `legion_python a/b/c/script.py -ll:py N`.

**Comment by lightsighter** [comment]
> What does that mean?

It means you can type in commands to run in the top-level task. :)

> Ok, we're missing the print deduplication, but otherwise we already support this via "script mode"

Does it work distributed?

**Comment by elliottslaughter** [comment]
> It means you can type in commands to run in the top-level task. :)

That's called a REPL. :-)

> Does it work distributed?

Under control replication, yes.

**Comment by elliottslaughter** [comment]
By the way, about the REPL, how would you expect stdin to get replicated? Are you expecting Python to launch a task per entry in the user's input, and have the mapper set to map those all to the node that is attached to stdin? Is there even a portable way to figure out what node that is?

**Comment by pmccormick** [comment]
I agree that we should do this once and the in the right way.   I think this also relates to an aspect Mike and I talked about recently in terms of how you would actually manage REPL (or other mechanisms) injecting code/tasks into an already running application.   I was going to open a new issue (feature request) about adding this to the runtime ("precise exceptions").  I presume at one level they are separable concerns but it would  be nice to make sure one path here supports the other w/out too much refactoring, etc.

**Comment by lightsighter** [comment]
> By the way, about the REPL, how would you expect stdin to get replicated?

I don't think we need to do control replication with REPL. Just having typing in the loop should be enough to hide latency to pretty much any scale of machine. Legate today does REPL without control replication on distributed machines and it seems to work fine.

> I presume at one level they are separable concerns but it would be nice to make sure one path here supports the other w/out too much refactoring, etc.

I would still make a separate issue @pmccormick. REPL operates above the runtime and doesn't need any support from Legion itself. What you want with "precise exceptions" for tasks requires some non-trivial support inside the runtime.

**Comment by elliottslaughter** [comment]
> I don't think we need to do control replication with REPL.

You need it when you're defining tasks in Python. E.g. if you enter at the REPL:

```@task
def asdf():
    pass
```

You need to control replicate execution to get this defined on all Python processors. Or else we would need Realm to support [cloudpickle](https://github.com/cloudpipe/cloudpickle) or something similar.

**Comment by lightsighter** [comment]
Yeah, I only think of all this as applying to the top-level task. I can't think of a good reason to start a REPL inside of a task that is not the top-level task unless you are debugging and in that case I suggest we deal with it separately.

**Comment by elliottslaughter** [comment]
Oh, I guess I was assuming that the top-level task could define other tasks. This is actually a use case today with Pygion when you run in script mode (the script becomes the top-level task, so it actually makes sense to define tasks inside of it). But otherwise, yes, I agree the REPL is only needed at top-level.

**Comment by elliottslaughter** [comment]
I have a partial solution to factoring out some of the Pygion internals so we can start to do this, but it's not yet passing CI. After I get it to pass, I'll move on to generalizing the other bits to make this work.

**Comment by elliottslaughter** [comment]
The first part of this in master as of 161442623283c39ec31ae0767353728247b99971. Once we resolve the naming issue around Pygion bindings, I'd like to suggest we declare `legion_python` to be the official executable runner, and the `legion_cffi` to be the official low-level bindings.

Please let me know what else is missing in the current setup. My list currently has:

  * Factor out `legion_top` from the Pygion bindings to handle running the top-level task as a script.
  * REPL
  * Jupyter notebooks

Anything else?

**Comment by lightsighter** [comment]
What is our plan for having people build C extension modules in Python that rely on Legion? Can we link against the `legion_python` binary or do we need to have some other strategy? Hint: someone at NVIDIA (not me) is working on C extension library built on top of Legion that has to work with Legate.

**Comment by lightsighter** [comment]
One other complication here: looks like some people from NVIDIA might be contributing some Cython bindings for the C++ API as well. Not sure what we're going to do with those yet...

**Comment by elliottslaughter** [comment]
You can't link against an executable, which is exactly why I wasn't able to use CFFI's "API mode" (which uses a C compiler, rather than dlsym and libffi). So if you need to do this, you need to use CMake, and you have to set `-DBUILD_SHARED_LIBS=ON` so that the build generates `liblegion.so`. Alternatively, we could teach the Makefile to do this.

Who's going to maintain the Cython bindings? Unless I'm mistaken, that's going to force us to accept a bunch of code duplication, which is going to have a non-trivial maintenance cost. The whole point of CFFI is to minimize maintenance at the level of the bindings module.

**Comment by lightsighter** [comment]
> So if you need to do this, you need to use CMake, and you have to set -DBUILD_SHARED_LIBS=ON so that the build generates liblegion.so. Alternatively, we could teach the Makefile to do this.

I think we want to do this. I want to get away from building a monolithic Legate binary where we have to build support for NumPy and Pandas and Dask all into a single binary. I'd rather build them as separate .so objects that link against liblegion and then have a binary that loads them all on demand as they are loaded as Python modules from application code.

> Who's going to maintain the Cython bindings?
These will be maintained by NVIDIA people and I think should be considered a separate set of bindings from the ones we're designing with CFFI. We should just have a plan for where they go and how we incorporate them into the repository.

**Comment by elliottslaughter** [comment]
Ok, the next part of this is in branch `python-top`. Will push it to master once it passes CI.

**Comment by elliottslaughter** [comment]
This is merged as of f61fd1ad2f5fed5c78d50d5b44b77b95537ea8a9, and the next bit is in `pygion-rename`.

**Comment by elliottslaughter** [comment]
Ok, merged with e4e2cb72a0f5bd4ea1508953b88376838aa5803d. At this point, I think I've done my part of what was in this issue:

  * Split `legion_cffi` into its own module
  * Split `legion_top` into its own module and made `legion_python` independent of Pygion
  * Rename Pygion to `pygion.py`

At this point I'm assigning to @lightsighter to add the REPL and Jupyter notebook capability.

**Comment by lightsighter** [comment]
I've update this code so that `legion_python` handles running scripts, modules, and a REPL the same as normal CPython. I've also updated it so that it uses support from #740 to remove Legion and Realm arguments from the command line before we get into Python. I'm not sure if Realm is doing it's full parsing of command line arguments yet though, so I've left the pruning code on the Python side in place for now.

**Comment by lightsighter** [comment]
Do we want to add support for deduplicating stdout in control replication contexts?

**Comment by elliottslaughter** [comment]
Yes, I think that would be good, but I'd suggest splitting this into multiple issues for the remaining pieces (Jupyter, deduplicate stdout, REPL DCR integration) unless you believe they'll all be completed soon.

**Comment by lightsighter** [comment]
I added support for deduplicating stdout when running with control replication.

Is this the right way to go about implementing a Jupyter kernel or do we think there is a better way?
https://jupyter-client.readthedocs.io/en/stable/wrapperkernels.html

**Comment by lightsighter** [comment]
I don't think I'm ever going to do REPL DCR integration. If someone else wants to do that then they can make a separate issue. Everything else belongs here.

**Comment by lightsighter** [comment]
The only thing left to do for this was Jupyter notebook support so I've created a new issue for that. Everything else is done and in the master branch.
