### ISSUE TITLE
realm: bulk calls to transfer iterators

### ISSUE THREAD

**Issue by streichler** [StanfordLegion/legion#730]
Performance fix (and enabler for device-side copies/reductions): a call to a TransferIterator should return as many AddressInfo objects as the caller can take to amortize the instance layout analysis.

**Comment by streichler** [comment]
This is getting close, but is too disruptive to go in right before a release.

**Comment by streichler** [comment]
This has been in master for a while now.  Not all channels are using it yet, but the key ones (memcpy and rdma) are.

**Comment by lightsighter** [comment]
What about GPU-to-GPU? Is that covered under "memcpy"?
