### ISSUE TITLE
Teach CMake to Compile Runtime GPU Objects

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#735]
Commit 48813c828 started adding support Legion to provide GPU reduction kernels for folding and applying reduction instances. This included the addition of a new file `legion_redop.cu` which is a runtime CUDA file and has to be built differently than other runtime objects that are only C++. Additionally, the build system must pass `-DLEGION_GPU_REDUCTIONS` to `CC_FLAGS` and `NVCC_FLAGS` when compiling runtime code for GPU builds. Support for this has been added to the Makefile build system already and needs to be added to the CMake build. The runtime will continue to work correctly so this can be viewed as an enhancement since you need to actually set the `-DLEGION_GPU_REDUCTIONS` macro to enable to the support.

**Comment by elliottslaughter** [comment]
Pushed some initial work to `cmake-legion-redop`. Currently fails with:

```
CMake Error at runtime/CMakeLists.txt:356 (target_link_libraries):
  The plain signature for target_link_libraries has already been used with
  the target "LegionRuntime".  All uses of target_link_libraries with a
  target must be either all-keyword or all-plain.

  The uses of the plain signature are here:

   * cmake/newcmake/FindCUDA.cmake:1674 (target_link_libraries)
```

Which seems to be pointing into our custom FindCUDA, which I'm honestly not sure why we even have in the first place. Will debug when I get a chance, but help would be appreciated.

**Comment by streichler** [comment]
I took another shot at this, and things work fine for me locally now.  Let's see what CI thinks.

**Comment by streichler** [comment]
After a few bug fixes, CI likes the current state of things.  @elliottslaughter can you take a look before I merge into master?

**Comment by elliottslaughter** [comment]
Looks good to me, as long as CI passes I'm happy with this.

**Comment by streichler** [comment]
These changes made it into master with commit 6191b43.
