### ISSUE TITLE
Inner Tasks Should Not Block Waiting on Futures

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#736]
Generalize the inner task optimization so that it applies to futures and not just regions, thereby allowing sub-tasks to be launched before futures have been completed.

**Comment by elliottslaughter** [comment]
Do you mean future arguments? Because otherwise I don't see how it's safe to not block at a `Future::get_result()` call.

**Comment by lightsighter** [comment]
Yes, that's what I mean.

**Comment by lightsighter** [comment]
Pushed this update with 8cff1c93d. Will close the issue once it passes CI.
