### ISSUE TITLE
Regent: Interoperability with the CUDA runtime

### ISSUE THREAD

**Issue by magnatelee** [StanfordLegion/legion#738]
The Regent compiler produces PTX registration code in the assumption that the PTX will be consumed by the Realm hijack. The registration code is not quite compatible with the default CUDA runtime, which was causing issue #713. This interoperability is useful in scenarios where the Realm hijack needs to be disabled, typically arising when the Regent code is integrated with legacy code directly using CUDA. While what integration strategies we should encourage is an interesting question in the long run, at least for the short term we need to fix the Regent compiler so that it generates a CUDA-compatible registration preamble.

**Comment by elliottslaughter** [comment]
I thought we fixed compatibility with the hijack being disabled?

**Comment by elliottslaughter** [comment]
Regent use of the hijack was truly and finally removed in #1059, so this is now resolved.
