### ISSUE TITLE
Legion: reduction operation on array type field space

### ISSUE THREAD

**Issue by bandokihiro** [StanfordLegion/legion#739]
# Context
I am writing a CFD solver using Legion. Typically, for each element, we have an array of degrees of freedom `double* U` and a time-update can be written as `U[i] += dt*R[i]` where `R` is the residual. 

My index domain are:
1. `I1` of size `nElem`
2. `I2` of size `nFace`

My regions are:
1. a mesh-element region on `I1`
2. a mesh-face region on `I2`
3. a solution region on `I1` with two fields of size `nDOF*sizeof(double)`, one for the DOF and one for the residual.

In order to compute the residual, a required step is to loop over faces, each face contributing to the residual of its adjacent elements. Therefore, my partitionings (all of the same size) are:

1. one partition `P11` of `I1` given by metis
2. one partition `P2` of `I2` as the pre-image of the left element ID (left and right are arbitrary for each face)
3. a second partition `P12` of `I1` which is the union of the image via left and right elements of a temporary partitioning of faces, each partition containing all faces adjacent to at least one element of the partition in `P11` (`P12` is basically `P11` with the halo elements)

# Problem
For the task that computes the face contribution, I loop over faces in each partition of `P2`. Since partitions in `P12` are not disjoint I need to use reduction privileges. For each face, I get the left and right element as `Point<1>` and add the contribution of the face on the residual field `R[i] += face_contribution[i]`. Therfore I need to define an array type summation reduction operator. For now I am doing something like
```
template <int n>
class ReductionSum {
  public:
    typedef struct LHS {
        rtype value[n];

        LHS() {
            for (int i=0; i<n; i++) {
                value[i] = 0.;
            }
        }

        LHS(std::vector<rtype> vec) {
            for (int i=0; i<n; i++) {
                value[i] = vec[i];
            }
        }

        LHS& operator= (const LHS &lhs) {
            for (int i=0; i<n; i++) {
                value[i] = lhs.value[i];
            }
            return *this;
        }
    } LHS;

    typedef LHS RHS;

    static const LHS identity;

    template<bool EXCLUSIVE> void static apply(LHS &lhs, RHS rhs);
    template<bool EXCLUSIVE> void static fold(RHS &rhs1, RHS rhs2);
};
```
The annoying thing is that `nDOF` depends on the shape, order of accuracy and type of equations we are solving. Currently I need to instantiate the correct version of this class inside the class to get the accessor which requires providing a compile-time known template parameter.

# Need
I would like to have something that allows me to define reduction operators with dynamic selection of the size of the residual field in each element.

**Comment by streichler** [comment]
I'm considering augmenting Realm's reduction op registration to accept an object of the "reduction op" type that has non-static apply/fold methods, which I think would be expressive enough to handle this.  I need to think through it a little more to make sure it won't get in the way of doing reductions on GPUs, and we need @lightsighter to let us know if there's any complications with passing these things through Legion into Realm.

**Comment by lightsighter** [comment]
I just pass through reduction operator objects to Realm and get them back from Realm so I don't think there is any issue on my side. Getting it work with GPUs seems challenging unless you put it in the zero-copy or UVM memory.

**Comment by streichler** [comment]
I'd probably ask that the reduction object itself be trivially copyable so that it can be shipped to the GPU by value in this case.

**Comment by lightsighter** [comment]
Who's going to do that shipping?

**Comment by streichler** [comment]
Realm will.  At registration time, you will pass a reference to an object of the reduction op type and Realm will make copies of it for performing CPU and GPU reductions.

**Comment by streichler** [comment]
Regent now has a working implementation of array reduction ops that I think match @bandokihiro 's needs.  Kihiro, can you check out the code here:
https://gitlab.com/StanfordLegion/legion/-/blob/master/bindings/regent/regent_redop.h (declarations)
https://gitlab.com/StanfordLegion/legion/-/blob/master/bindings/regent/regent.cc (registration for CPU-only case)
https://gitlab.com/StanfordLegion/legion/-/blob/master/bindings/regent/regent_cuda.cu (registration for CPU+CUDA case)
and see if it makes sense?

**Comment by bandokihiro** [comment]
I am not sure I understand everything but from what I can tell, it makes sense. Also, maybe I should have closed this issue but I completely removed reductions from my code so this is not a current need.

**Comment by streichler** [comment]
Ok, I'll close the issue out then, but hopefully a neuron or two remembers this thread in case you find yourself needing array reductions in the future.  :)
