### ISSUE TITLE
Regent: "missed work counter wakeup?" 

### ISSUE THREAD

**Issue by rupanshusoi** [StanfordLegion/legion#744]
I have the latest version of Legion and Regent from master. This error did not occur a few days ago. In essence I have the following loop structure from where the code does not behave as expected.
```
for i = 1, iter do
    func_delta(...)
    for rk = 1, 4 do
        q_var(...)
        flux_res(...)
        state_update(...)
    end
end
```
I get the above mentioned error multiple times until finally I get 
`
[0 - 7f710cd6c700] {4}{task}: missed work counter wakeup? - suppressing further messages
`
The code does not seem to do anything after this, although it continues to use system resources.
Any help will be really appreciated!

**Comment by lightsighter** [comment]
Can you provide a command line for compiling and running this program? Also, tell us a little bit about the system that you are running on if possible.

**Comment by Nischay-Pro** [comment]
We ran the `install.py` inside `language` with the default flags. We did not provide any extra flags.

The system it's running on uses CentOS 8 
We used gcc 8.3.1 with clang 9.0.0

@rupanshusoi

**Comment by streichler** [comment]
What arguments are you passing to the regent command line?

That warning message was intended to catch memory synchronization errors inside of Realm, but what it's mostly good at is complaining when the system has become very unresponsive (i.e. threads taking more than 1 second to start once being awakened).  That seems consistent with "continues to use system resources", but it doesn't directly tell us what's maxing out the cpus.

Can you run it again, wait until you've gotten those messages, and then break in with a debugger and see what the various threads are doing?  Please also use `top` or some equivalent tool to check memory usage and see if you're possible thrashing in/out of swap space.

**Comment by rupanshusoi** [comment]
I just use the `-level runtime=5` flag to suppress some warnings (#719). Interestingly, on the latest version from master, I don't see the warnings even without passing this flag. The behaviour is same in both cases, though, as described above. 

I'm seeing continuous allocation of RAM during runs, even though memory should just be allocated once. We also don't have swap enabled. I will further investigate with a debugger and update you in a day or so.

**Comment by jiazhihao** [comment]
I have seen similar warning messages in FlexFlow by using the up-to-date control replication branch. The warning can be deterministically replayed.

**Comment by lightsighter** [comment]
Two reproducers is enough for me to label this a bug.

I still think the increasing memory usage is likely a separate issue. 

> The code does not seem to do anything after this, although it continues to use system resources.

It would probably help to see some backtraces. Run with `-ll:force_kthreads` on your command line if you plan to use a debugger.

**Comment by rupanshusoi** [comment]
@lightsighter Okay so after giving these warning messages, I found the code to be executing normally but much slower than usual, which I why I initially thought it wasn't doing anything at all.

**Comment by lightsighter** [comment]
Can you say how much slower? If you can give us a commit where things changed that would be very useful. At a minimum some Legion Prof pictures from before and after would go a long way to suggesting the source of the problem.

**Comment by rupanshusoi** [comment]
666bb15 is the first commit where the problem appears.

**Comment by streichler** [comment]
@rupanshusoi Thanks, that narrows it down significantly.  Here's a few more questions and something to try:
1) What compiler are you using and what c++ standard (e.g. `-std=c++11` or something similar)?
2) Are you enabling openmp support in Legion?
3) Breaking in with the debugger and getting backtraces after the slowdown begins would still be useful.

And please try removing the #ifndef/#endif pair that were added here:
https://github.com/StanfordLegion/legion/commit/666bb1542b4f5c1f4180aa9975e2bd0c1610b177#diff-33c5efd317bdea53974bd8aeed5491d7R541-R543

**Comment by streichler** [comment]
I'm able to reproduce this message with c++11 and above (i.e. cases where the `__sync_synchronize` is elided by that commit), and removing the ifndef/endif pair seems to make it happier, so @rupanshusoi and @jiazhihao , please try to confirm that works for your applications as well.

I'm going to spend a bit of time trying to fix this properly this morning, but if I can't, I'll back out the change for now.

**Comment by streichler** [comment]
@rupanshusoi @jiazhihao please grab the following commit and give it another try:
https://gitlab.com/StanfordLegion/legion/commit/9d70cb91b3e8e1d63d1b23dd83bcf988d34564c1

**Comment by rupanshusoi** [comment]
Yes, it looks like it's fixed for my code. Thanks.

**Comment by rupanshusoi** [comment]
@streichler Unfortunately, I'm still experiencing significant slowdown as compared to an older build of Legion and Regent. The first time I experienced this slowdown was when I got the above mentioned warning for the first time. If you think this is due to something else, I can try to find the commit which first caused it.

**Comment by lightsighter** [comment]
If you can give us a commit where the slow down occurred that would be great. Even a range of commits would be helpful, but a specific commit would be the best.

**Comment by rupanshusoi** [comment]
I'm hesitant to find this commit since the slowdown might just be due to my task tree (#745). I can report back once I've incorporated parallelism sufficiently.

**Comment by elliottslaughter** [comment]
Just FYI, I saw the `missed work counter wakeup?` message today in Legion Task Bench with commit c3a61afb45c20d1d668257f87ab625eb3a05d7af. It's non-deterministic, happened once at 32 nodes (out of ~70 runs) and once at 128 nodes (out of ~6 runs).

**Comment by lightsighter** [comment]
Just out of curiosity, do you think it is possible that you have lots of stacks accumulating somewhere? Legion Prof might help with visualizing that.

**Comment by streichler** [comment]
@rupanshusoi what's the status of this issue?  Are you still seeing performance issues?

**Comment by rupanshusoi** [comment]
@streichler No, turns out I had written very bad Regent code the first time around. (Too many fine-grained task launches.)

So the issue is fixed for me, thanks.
