### ISSUE TITLE
Regent: inlining task gives incorrect result

### ISSUE THREAD

**Issue by rupanshusoi** [StanfordLegion/legion#750]
The following
```
import "regent"

__demand(__inline)
task foo()

	var sum_delx_sqr : double = 0
    	var sum_dely_sqr : double = 0
    	var sum_delx_dely : double = 0

	var nx = 1.0
	var ny = 1.0
	var tx = 1.0
	var ty = 1.0

	var delx = 1.0
	var dely = 1.0

	var dels = delx*tx + dely*ty
	var deln = delx*nx + dely*ny
	var dels_weights = dels
	var deln_weights = deln

	sum_delx_sqr = sum_delx_sqr + dels*dels_weights
	sum_dely_sqr = sum_dely_sqr + deln*deln_weights

	regentlib.c.printf("Sums %0.13lf %0.13lf\n", sum_delx_sqr, sum_dely_sqr)
end

task main()
	foo()
end
regentlib.start(main)
```
outputs 
```
Sums 0.0000000000000 0.0000000000000
``` 
On commenting out the inline request at the top, we get 
```
Sums 4.0000000000000 4.0000000000000
``` 
as output. Surprisingly, changing the first 3 declarations to use `0.0` instead of `0` (for example `var sum_delx_sqr : double = 0.0`) gives the correct result even with the inline request.

**Comment by magnatelee** [comment]
This should be fixed by 522329e5. @rupanshusoi Can you pull and try again?

**Comment by rupanshusoi** [comment]
Yes, looks like it's fixed. Just curious, do you have any idea why changing `0` in the initialisations to `0.0` was masking the error?

**Comment by magnatelee** [comment]
There were two thing that were contributing to the issue. 1) the task inliner was "forgetting" the type of variables `sum_delx_sqr` and `sum_dely_sqr`, which later pick up the type of their literals, int32. 2) unlike in C, printf in Regent (more precisely in Terra) is more strict about argument types. your code with the inliner bug was putting a 32-bit integer variable in a place where the printf was expecting a 64-bit float, which made it read off from a wrong address and end up printing 0.

**Comment by magnatelee** [comment]
@rupanshusoi Can you close the issue if you confirmed the fix?
