### ISSUE TITLE
legion prof: GPU task times not rendered accurately

### ISSUE THREAD

**Issue by seemamirch** [StanfordLegion/legion#755]
here is an example of this - http://sapling.stanford.edu/~mariodr/Patch_X

**Comment by elliottslaughter** [comment]
Is this still relevant?

**Comment by lightsighter** [comment]
This is partially resolved, although as I noted in the Legion meeting last week, there are still some infidelities in how we are profiling what is actually happening on the GPU. Not sure if you want to repurpose this issue or start a new one.

**Comment by elliottslaughter** [comment]
I'd be inclined to start a new issue with a description of what exactly is still imprecise at this point.

**Comment by lightsighter** [comment]
Forgot I already started the issue: #1645.
