### ISSUE TITLE
Feature request: legion prof should support layout constraints

### ISSUE THREAD

**Issue by MatthiasKohl** [StanfordLegion/legion#757]
It would be very helpful to know in the legion profile, in the memory views, for each instance, what the expected constraints on the layout are (including ordering, alignment etc.)

Possibly, it would be good to know other constraints as well, such as ColocationConstraint for each instance and LaunchConstraint for GPU tasks.

**Comment by lightsighter** [comment]
@seemamirch Let's just do dimension ordering and alignment constraints on the instances for now. If we need additional ones to be added later we can pipe them through on demand as the path will already have been established. Just have some of these layout constraints pop-up in the window when we hover over instances. Might also be good to have the name(s) of the logical regions that represent the instances as well. If you have trouble getting that info out of the runtime let me know. You can just making profiling API calls inside the runtime and ask me to invoke them in the right place.

**Comment by seemamirch** [comment]
@MatthiasKohl - alignment and dimension ordering have been added (branch prof-updates). Please try it out. A simple example is 
http://sapling.stanford.edu/~seemah/legion_prof.7/?start=5057917.518911611&end=5092676.418056799&collapseAll=false&resolution=10

**Comment by MatthiasKohl** [comment]
Sorry I still couldn't check this out. Your example looks great though, I'll reproduce this on my side as soon as I get to it!

**Comment by lightsighter** [comment]
@seemamirch I think if you believe we've done enough to handle this then we can close out this issue in preparation for the 20.03 release. @MatthiasKohl can ping me if he has questions about what he's seeing in the profiler.

**Comment by MatthiasKohl** [comment]
Yes, I'm closing this now, it works as expected on my side, too! Thank you very much!
