### ISSUE TITLE
cmake: Build breaks when statically linking Legion with GASNet enabled

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#758]
My understanding is the following conditions are required to reproduce this:

  * CMake
  * `BUILD_SHARED_LIBS=OFF`
  * GASNet
  * `make install` and link the application against the installed copy

The application fails to link; it can't find GASNet symbols.

**Comment by elliottslaughter** [comment]
Reproduction steps:

```
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=$PWD/../install -DBUILD_SHARED_LIBS=OFF -DLegion_USE_GASNet=ON -DGASNet_ROOT_DIR=$HOME/sw/gasnet/release ..
make -j20
make install
cd ../examples/circuit
mkdir build
cd build
cmake -DCMAKE_PREFIX_PATH=$PWD/../../../install ..
```

Results in:

```
CMake Error at CMakeLists.txt:36 (add_executable):
  Target "circuit" links to target "GASNet::GASNet" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:36 (add_executable):
  Target "circuit" links to target "ZLIB::ZLIB" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
```

**Comment by elliottslaughter** [comment]
Fixed in 95f999da3e03042e56aa5ff7588ca8866e2bf4fb. Turns out it was also a problem for ZLIB.

**Comment by elliottslaughter** [comment]
This isn't quite fully resolved, the application which originally motivated this is still failing to link (lots of "undefined reference to ...").

**Comment by streichler** [comment]
I'm assuming whatever app was failing nearly a year ago has learned to work around or cope with this, so I'm closing this out in favor of a more general need to test against installed versions, captured in #987.
