### ISSUE TITLE
mRuntime->create_partition_by_image_range documentation

### ISSUE THREAD

**Issue by aheirich** [StanfordLegion/legion#759]
There is no online documentation for 
mRuntime->create_partition_by_image_range

Please remember to use simple sentences with one subject/object per sentence.

**Comment by lightsighter** [comment]
It's identical to create_partition_by_image except with a range field instead of a point field. I don't think it needs any additional documentation as it should be self-explanatory.

**Comment by aheirich** [comment]
this is what the documentation shows:


emplate<int DIM1, typename COORD_T1 , int DIM2, typename COORD_T2 , int COLOR_DIM, typename COLOR_COORD_T >
--
IndexPartitionT< DIM2, COORD_T2 > | create_partition_by_image (Context ctx, IndexSpaceT< DIM2, COORD_T2 > handle, LogicalPartitionT< DIM1, COORD_T1 > projection, LogicalRegionT< DIM1, COORD_T1 > parent, FieldID fid, IndexSpaceT< COLOR_DIM, COLOR_COORD_T > color_space, PartitionKind part_kind=COMPUTE_KIND, Color color=AUTO_GENERATE_ID, MapperID id=0, MappingTagID tag=0)
 
IndexPartition | create_partition_by_image_range (Context ctx, IndexSpace handle, LogicalPartition projection, LogicalRegion parent, FieldID fid, IndexSpace color_space, PartitionKind part_kind=COMPUTE_KIND, Color color=AUTO_GENERATE_ID, MapperID id=0, MappingTagID tag=0)


there is no information whatsoever about how this works or what it does, nor how it is related to create_partition_by_image

**Comment by syamajala** [comment]
Maybe the dependent partitioning operators would be a good candidate to document on the wiki? I feel like a lot of them all we really need are a simple example with a picture to show they work. 

I wouldn't mind doing this at some point.
