### ISSUE TITLE
Thrust v1.8.0 interop

### ISSUE THREAD

**Issue by sdalton1** [StanfordLegion/legion#76]
Compile error on Ubuntu 14.04 with NVCC release 7.0, V7.0.17 for thrust_interop example starting with Thrust v1.8.0 and above.

Runtime functions referenced:
cudaEventDestroy
cudaEventCreateWithFlags
cudaEventRecord
cudaDeviceGetAttribute
cudaStreamWaitEvent

Top-level files referenced:

thrust/system/cuda/detail/bulk/detail/cuda_launcher/runtime_introspection.inl (lines 43-47)
thrust/system/cuda/detail/bulk/detail/async.inl (lines 39 & 70)

**Comment by streichler** [comment]
Steven, can you try this on a recent pull of the master branch?  All of these symbols should be defined as of a week ago or so.  (e.g. event-related calls are here: https://github.com/StanfordLegion/legion/blob/master/runtime/realm/cuda/cudart_hijack.cc#L129-L163)

**Comment by sdalton1** [comment]
Pulling from master fixed the error, thanks!
