### ISSUE TITLE
cmake: FindGASNet initializes from ENV{GASNET_ROOT}

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#760]
This isn't a problem per se, except that its inconsistent with everything else we do with CMake. Currently we don't read any variables from the environment, except `GASNET_ROOT`. This one variable doesn't seem to be worth an exception.

Any objections to removing it? You can still configure with `-DGASNet_ROOT_DIR` as we've always allowed.

**Comment by streichler** [comment]
There's tons of examples of CMake modules that are found with the help of environment variables with nonstandardized names.  CUDA and Kokkos both come to mind.

**Comment by elliottslaughter** [comment]
Ok, I'm fine with keeping it if it has a reason to be there. Closing for now.
