### ISSUE TITLE
Legion Spy: check for partition completeness

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#769]
Currently, Legion Spy checks that partitions are disjoint, but not that they are complete. It would be nice to add this so that we have a uniform way for users to verify that their partitions match the properties they specify.

**Comment by lightsighter** [comment]
There is now support for the `-lg:partcheck` flag which will verify (in order) the containment, disjointness, and completeness of partitions. Don't say I didn't tell you it was expensive.
