### ISSUE TITLE
Regent: Assign task point and domain for individual tasks

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#772]
One nice thing about an index launch is you can figure out which task you are by the point the task is assigned in the launch domain. But if you have a loop that fails to index launch, you can't do this. One way to shrink the gap between individual and index launches would be to automatically assign every individual task the point and domain of the innermost surrounding loop. So e.g. in the following code:

```
__forbid(__index_launch)
for i = 0, 10 do
  f(...)
end
```

The first task launched will have point 0 and domain \[0,9], in spite of the fact that its not an index launch.

Note: This will set `index_point` and `sharding_space` on the task launch, which you can then use in the `ShardingFunctor` or pull out of the `Task` object.

**Comment by syamajala** [comment]
I would like this.

**Comment by elliottslaughter** [comment]
This has been merged as of 4b23bce0c8aae26db3fa6474aad7e29ff53c332c.
