### ISSUE TITLE
Deprecate span iterator?

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#774]
While chasing a Regent vectorizer regression recently @magnatelee pointed out to me that the span iterator is now obsolete, being backed by the rect in domain iterator. Since this involves strictly more indirection, and since spans are one of the remaining places there is still some dim == 0 vs dim == 1 cruft, maybe it's worth deprecating them?

Even if we can't remove it (soon) from the C++ API, we've typically been more aggressive about the C API. **Are there any C API users who are still using the span iterator today?** If not I propose we just go ahead and remove it.

**Comment by lightsighter** [comment]
Yes please! :) It's marked deprecated in the C++ API and will be removed at some day in the future.

**Comment by elliottslaughter** [comment]
I've received no response, so I'll remove this right after we issue the release.

**Comment by elliottslaughter** [comment]
Removed in a22fe6f4fa8decf5455e00d81716f7ee4ef6772c.
