### ISSUE TITLE
legion prof: Rendering gather/scatter copies

### ISSUE THREAD

**Issue by magnatelee** [StanfordLegion/legion#778]
Currently, gather/scatter copies are not rendered correctly in the timeline, because their source/target instances are not logged by Realm. @streichler proposed to add the following fields to `OpreationMemoryUsage`:

```
struct IndirectSrcTgt { Memory memory; size_t size; };
std::vector<IndirectSrcTgt> indirect_sources, indirect_targets;
```

There is a bigger question of how to render gather/scatter copies with multiple indirect sources/target instances. Our current timeline associates each copy with only one memory-to-memory channel and this isn't quite compatible with gather/scatter copies whose dataflow is not one-to-one. I'd like to brainstorm with the group to decide how to visualize gather/scatter copies.

**Comment by elliottslaughter** [comment]
This was fixed by @eddy16112 a long time ago.
