### ISSUE TITLE
Legion: hang with control replication

### ISSUE THREAD

**Issue by bandokihiro** [StanfordLegion/legion#779]
A run in my CFD solver on 2 nodes, 2 processes/node, without tracing, linked with the `control_replication` branch of Legion hangs in the middle of the run. No HDF5 output was used.

**Comment by lightsighter** [comment]
Please run with `-ll:force_kthreads` and report backtraces from all threads in both processes. Also please run in debug mode so we can see line numbers.

**Comment by lightsighter** [comment]
Also report the commit that you are running with.

**Comment by lightsighter** [comment]
If possible reproduce it with the `-lg:inorder` flag first.

**Comment by bandokihiro** [comment]
[commit](https://github.com/StanfordLegion/legion/commit/73a50d6e16756d5a7bf33646d3832dee269a9027)

**Comment by bandokihiro** [comment]
so first run with `-lg:inorder`?

**Comment by lightsighter** [comment]
With everything I said above and `-lg:inorder`

**Comment by bandokihiro** [comment]
when you say report backtrace, is this with `LEGION_BACKTRACE=1`?

**Comment by lightsighter** [comment]
No, I mean attach a debugger to each process and run `thread apply all bt` and then put that in a file that you can upload here.

**Comment by bandokihiro** [comment]
I am not too familiar with attaching debuggers.

**Comment by lightsighter** [comment]
Try using the `print_backtraces.sh` utility in the `tools` directory. You'll need to run it on each node where the application is running.

**Comment by bandokihiro** [comment]
I am not sure I can access the compute nodes where the application is actually running

**Comment by lightsighter** [comment]
Ok, it's going to be impossible to debug this without getting those backtraces. That means you'll need to reproduce this on a machine where you can get backtraces. Since it happens with only two processes I would imagine it should reproduce on a desktop pretty easily.

**Comment by bandokihiro** [comment]
I tried to install GasNET on my laptop today but failed. I was not able to compile the mpi conduit.

**Comment by lightsighter** [comment]
If you don't have any other machines that you can run on where you can attach a debugger then you need to shrink the application down to as small as possible case that still reproduces the hang so you can sent it to me to look at.

**Comment by lightsighter** [comment]
I would also go back and double check that you have abided by all the restrictions of control replication in any tasks that you are marking as replicable.

**Comment by bandokihiro** [comment]
where can i find those?

**Comment by lightsighter** [comment]
It's impossible to enumerate all such restrictions. The requirement is that you need to guarantee that the runtime sees exactly the same series of calls into the runtime with the same arguments from all shards. That means that you can't have control flow that depends on random number generators, you can't use data structures that are indexed by pointers to launch tasks, etc.

**Comment by bandokihiro** [comment]
it does not hang with `-ll:force_kthreads`

**Comment by bandokihiro** [comment]
it also does not hang with the debug build (at least not before the simulation ends)

**Comment by bandokihiro** [comment]
switched to this [commit](https://github.com/StanfordLegion/legion/commit/d009bd27f350bfee6fd3a6950c51665b108e946d)

**Comment by bandokihiro** [comment]
both `-ll:force_kthreads` and `-lg:inorder` independantly used seem to fix the hang in Release

**Comment by lightsighter** [comment]
Both of those impact performance so they are not viable long term solutions. You need to provide a way for me to reproduce the bug.

**Comment by bandokihiro** [comment]
I know but it only happend with Release

**Comment by bandokihiro** [comment]
I am trying to make it run on sapling

**Comment by magnatelee** [comment]
A fix has been pushed to `control_replication`, @bandokihiro can you pull and try again?

**Comment by bandokihiro** [comment]
The fix for this particular problem was solved.
