### ISSUE TITLE
start_time > end_time for copy profiles

### ISSUE THREAD

**Issue by ahenzinger** [StanfordLegion/legion#780]
When I run stencil_fast.rg with the following command line, and I add in copy profile operations for tasks stencil() and increment(), I see start_time > end_time for some of the copies:

USE_FOREIGN=0 ./regent.py examples/stencil_fast.rg -foverride-demand-cuda 1 -nx 2000 -ny 2000 -ntx 2 -nty 5 -ll:csize 1000 -ll:fsize 1000 -ll:zsize 1000 -ll:rsize 1000 -ll:gpu 2 -ll:cpu 8

(running on 1 node, on Sapling)

**Comment by elliottslaughter** [comment]
We'd need a reproducer, which I'm guessing we won't get on this issue.
