### ISSUE TITLE
Legion&Realm: Extending partition-by-weights to 64-bit weights

### ISSUE THREAD

**Issue by magnatelee** [StanfordLegion/legion#791]
One of the common cases to use partition-by-weights is when the sum of the weights is the same as the volume of the index space. The API currently only allows weights to be 32-bit integers, which makes the call not usable when one of the subregions has more than 2 billion entries.

**Comment by streichler** [comment]
Commit 4beae8b6 adds the following method:
```
    Event IndexSpace<N,T>::create_weighted_subspaces(
                                    size_t count, size_t granularity,
				    const std::vector<size_t>& weights,
				    std::vector<IndexSpace<N,T> >& subspaces,
				    const ProfilingRequestSet &reqs,
				    Event wait_on = Event::NO_EVENT) const;
```

Passing the baton to @lightsighter to add the Legion API exposure.

**Comment by lightsighter** [comment]
Added with 373c6833c

@streichler Is there are a reason the 32-bit version uses signed integers and the 64-bit version uses unsigned integers?

**Comment by streichler** [comment]
> Added with 373c6833c
> 
> @streichler Is there are a reason the 32-bit version uses signed integers and the 64-bit version uses unsigned integers?

I don't recall why we used `int` instead of `unsigned` for the original (32-bit) version, but the point of this new version is to get precise control over the sizes of the subregions that result from a weighted partition, so it must be large enough to describe any memory allocation in the system.

**Comment by lightsighter** [comment]
We can close this now right?
