### ISSUE TITLE
Regent: bug in atomic reduction in OpenMP loops

### ISSUE THREAD

**Issue by mariodirenzo** [StanfordLegion/legion#794]
The following script 
```
import "regent"

local C = regentlib.c
local fabs = regentlib.fabs(double)

local Npoint = 100
local Npart = 1

struct point {
   x : double
}

__demand(__leaf)
task AddAvg(r : region(ispace(int2d), point),
            p : region(ispace(int1d), point))
where
   reads(r.x),
   reduces+(p.x)
do
   __demand(__openmp)
   for c in r do
      var cP = int1d(c.x)
      p[cP].x += r[c].x
   end
end

__demand(__leaf)
task CheckAvg(p : region(ispace(int1d), point))
where
   reads(p.x)
do
   for c in p do
      --C.printf("%d %10.5e\n", c, p[c].x)
      regentlib.assert(fabs(p[c].x - 1.0) < 1e-12, "Wrong reduction")
   end
end

task main()
   C.printf("Start\n")
   var is = ispace(int2d, {Npoint, Npoint})
   var r = region(is, point)
   var tiles = ispace(int2d, {Npart, Npart})
   var p_r = partition(equal, r, tiles)

   var p = region(ispace(int1d, Npoint), point)

   var x = 1.0/Npoint
   fill(r.x, x)

   for i=0, 100 do
      fill(p.x, 0.0)
      __demand(__index_launch)
      for c in tiles do
         AddAvg(p_r[c], p)
      end
      CheckAvg(p)
   end

   __fence(__execution, __block)

   C.printf("End\n")
end

regentlib.start(main)
```
fails its execution with nondeterministic results if run with `regent.py testReduction.rg -ll:ocpu 1 -ll:othr 2`.
It instead gives correct results with `-ll:othr 1`.
I think that regent is not using the correct atomic access to `p[cP].x` in `AddAvg` for the OpenMP threads. If such a loop is not compatible with Regent, it should issue an error.

**Comment by streichler** [comment]
Assigning to @magnatelee to take a look at the code that regent is generating, but it's also possible that there's a problem with the Realm omp runtime implementation.

**Comment by magnatelee** [comment]
I haven't closely looked at this issue yet, but I bet the field name `x` is confusing the parallelizability checker, as that name is overloaded (`x`, `y`, `z`. etc. are reserved for coordinates of an index point). @mariodirenzo can you try to change the field name and see if that fixes this issue?

**Comment by mariodirenzo** [comment]
I've renamed `x` as `k` and the issue is still there.

**Comment by magnatelee** [comment]
This should be fixed in master and control_replication. @mariodirenzo Can you pull and try again?

**Comment by mariodirenzo** [comment]
Works for me. Thanks
