### ISSUE TITLE
Regent: bug in regent OpenMP parallelized loops

### ISSUE THREAD

**Issue by mariodirenzo** [StanfordLegion/legion#799]
The following script
```
import "regent"

local C = regentlib.c
local fabs = regentlib.fabs(double)

local Npoint = 100

struct point {
   a : double
}

task main()
   C.printf("Start\n")
   var r = region(ispace(int1d, Npoint), point)

   for c in r do
      r[c].a = double(c)/(Npoint-1)
   end

   var c99 = int1d(r.bounds.hi)
   var Ue = 0.356
   __demand(__openmp)
   for c in r do
      var a = r[c].a
      if (a > Ue) then c99 min= int1d(c) end
   end
   C.printf("%10.5e %10.5e %10.5e\n", r[c99-1].a, Ue, r[c99].a)

   C.printf("End\n")
end

regentlib.start(main)
```
fails to compile if the second loop is optimized with OpenMP.
If `__demand(__openmp)` is commented, the program returns the expected result.

**Comment by magnatelee** [comment]
First of all, you can't put an OpenMP loop in a non-leaf task like in your code. With the change that I just pushed, the compiler will either ignore the pragma or raise an error, depending on what you give to `-fopenmp`. Second, `int1d` is not a valid type for scalar reduction. You should change it to one of the primitive types.

**Comment by mariodirenzo** [comment]
The real problem in my application was the reduction of `int1d`. Maybe you should issue an error saying that the reduction of that type is not supported instead of an `OpenMP code generation failed: found a loop-carried dependence`, as it happens with this script
```
import "regent"

local C = regentlib.c
local fabs = regentlib.fabs(double)

local Npoint = 100

struct point {
   a : double
}

task find(r: region(ispace(int1d), point))
where reads(r) do
   var c99 = int1d(r.bounds.hi)
   var Ue = 0.356
   __demand(__openmp)
   for c in r do
      var a = r[c].a
      if (a > Ue) then c99 min= int1d(c) end
   end
   return c99
end

task main()
   C.printf("Start\n")
   var r = region(ispace(int1d, Npoint), point)

   for c in r do
      r[c].a = double(c)/(Npoint-1)
   end

   var Ue = 0.356
   var c99 = find(r)
   C.printf("%10.5e %10.5e %10.5e\n", r[c99-1].a, Ue, r[c99].a)

   C.printf("End\n")
end

regentlib.start(main)
```

**Comment by magnatelee** [comment]
I agree that the error message is not as friendly as it could be, but it's not entirely inaccurate either and I don't think that's a problem. A reduction with an arbitrary data type like `int1d` is really a syntactic sugar for a read-write, which would introduce a loop-carried dependence, and there is no reason that you could assume that it could be performed atomically.

**Comment by streichler** [comment]
@magnatelee could we change the codegen to turn scalar updates like:
```
lhs op= rhs_expr
```
where `lhs` is a unhandled type and turn it into:
```
val tmp = rhs_expr
#pragma omp atomic
lhs op= tmp
```

it's likely that we (I) would need to make some corresponding changes on the Realm omp implementation, but this seems better than kicking somebody completely off the data-parallelism train.

**Comment by magnatelee** [comment]
@streichler the Regent compiler doesn't depend on any off-the-shelf OpenMP frontend, so we can't use the OpenMP pragma. Even if we could, I don't think the frontend would allow anything other than primitive types. Also, I don't think I kicked Mario completely off in this case, as he can still write the code like this:
```
var c99 = int64(int1d(r.bounds.hi))
 var Ue = 0.356
 __demand(__openmp)
 for c in r do
    var a = r[c].a
    if (a > Ue) then c99 min= int64(int1d(c)) end
 end
 return int1d(c99)
```

**Comment by magnatelee** [comment]
Closing this issue as and tracking the issue of improving error messages in #807.
