### ISSUE TITLE
Regent: support docstrings

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#806]
In order to build reusable libraries in Regent, it would be really nice to support docstrings or comments, ideally with some sort of a tool to parse and generate documentation. I don't know that we want to build our own documentation tool, but perhaps we can integrate something that's pre-existing.

**Comment by rupanshusoi** [comment]
Just a suggestion -- Doxygen can be modified to work new languages. There is a pre-existing Lua filter for it [https://github.com/alecchen/doxygen-lua](url) so shouldn't be too hard to modify this to work for Regent.

**Comment by syamajala** [comment]
I personally prefer sphinx, it also works with lua as well. I'm not a big fan of doxygen.

**Comment by elliottslaughter** [comment]
I don't really have a strong opinion on which tool to use, but I would like to not fork or modify the tool itself in order to add the integration.

Ideally, we'd add a flag like `-fdoc 1` to the Regent compiler itself, so that we can reuse the existing Regent parser and type checker. Then we can split out XML or whatever the tool consumes and run it through the tool to spit out the final documentation.

**Comment by syamajala** [comment]
Another option that I've been playing around with is [ldoc](https://github.com/stevedonovan/ldoc). It seems to work with luajit and actually does something right now when I run it on Regent code (with a hack). 

I've been looking at the code for ldoc. It seems like it should be possible to modify it to add support for Regent. 

Heres an example of the documentation it generates:
https://stevedonovan.github.io/Penlight/api/libraries/pl.data.html

**Comment by syamajala** [comment]
There is a forked version of ldoc here:
https://github.com/syamajala/LDoc

You'll want to do git clone --recursive into the legion/language directory and then do make. Add terra to your path and then you can do ./ldoc.lua. The forked version has been fixed to work with Regent and Terra files, but it doesn't really do anything fancy right now. 

It would be nice if for the generated documentation it split the functions up by language and had a section for Tasks, Terra Functions, and Lua Functions. I think for Regent and Terra we should have it automatically extract types for arguments that are tagged with @param. For region arguments we should probably show privileges, but I'm not sure how that well that would work for metaprogrammed tasks that operate on a lot of fields like in S3D. Its probably a good idea to show task annotations as well?

The html pages ldoc generates currently lack a search feature, we could probably borrow that from sphinx? Having a permalink next to each section header would be nice. 

Any other ideas?

**Comment by elliottslaughter** [comment]
Ok, @syamajala and I have been pushing on LDoc. There is now a fork here: https://github.com/StanfordLegion/LDoc . This seems to be working reasonably well and has patches to support the things we need for at least basic functionality.

I put up some initial documentation for the standard library here: http://regent-lang.org/doc/

I'm going to consider this done for the moment. If there are further improvements to make we can put those in separate issues.
