### ISSUE TITLE
User-level querying of currently mapped (and previously mapped) regions

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#81]
Suppose you want to create a Legion library that requires access to a region passed as an argument. You have two ways to do this: either (1) you could create and launch a task, or (2) you could inline map the region. For the purposes of this discussion, let's assume you want to follow approach (2).

Currently, this won't work, because the region might already be mapped in the context in which the library is running. Or maybe it was previously mapped, and just happens to be currently unmapped. My understanding is that either of these scenarios will result in erroneous or poorly-defined behaviour if the library attempts to map the region a second time.

One way to deal with this might be for the user to query the state of the regions currently (or previously) mapped in this context. It's worth noting that this is in fact what the runtime would do (on behalf of the user) in scenario (1): the runtime has the ability to introspect the context and discover what regions need to be unmapped (and subsequently re-mapped) for any given operation. But there is currently no equivalent user-visible mechanism, which means that approach (2) is effectively infeasible for Legion libraries today.

**Comment by streichler** [comment]
Putting my Legion purist hat on, I'll argue that letting the application (or library) code query this is a "bad" mixing of algorithmic description with implementation details.

If the library code wants an inline mapping, it should be able to just ask for one, and we should have well-defined semantics that allow that to work even if there is already an active inline mapping of the same region.  Just as inline mapping is semantically similar to a subtask launch, a nested inline mapping is similar to a nested task launch, so it seem like the mapper of that nested inline mapping operation should be able to either reuse the existing (and valid) mapping or to pick a different location for the nested mapping, with data moved to/from that second location at the boundaries of the nested mapping.

**Comment by streichler** [comment]
If we go with my proposed "inline mappings behave a lot like tasks" semantics above, the inner inline mapping should "shadow" the outer one.  The implicit unmapping of the outer mapping would happen when the inner one is mapped, and when the inner one is unmapped, the outer one would be implicitly remapped.  Unless both request SIMULTANEOUS coherence, access to the outer inline mapping would be illegal while the inner mapping exists (and SIMULTANEOUS would force the two inline mappings to use the same instance, of course).

**Comment by streichler** [comment]
Assigning back to Elliott to write down the desired semantics.

**Comment by lightsighter** [comment]
So you are assuming proper nesting.  How does the runtime detect the case where they are not properly nested?

**Comment by streichler** [comment]
I was actually assuming we wouldn't bother - there are plenty of other well-formedness checks that we don't do right now.

But if we wanted to, having a context keep a stack of inline-mapped physical regions and verifying that an unmap is always of the newest one doesn't seem so hard.

**Comment by lightsighter** [comment]
Well this isn't well formedness.  This is deadlock.  I take deadlock pretty seriously.  Right now the runtime will either prevent you from deadlocking yourself or tell you why it can't.  I would like to maintain that invariant and not have the potential for unchecked deadlock.

It's about more than just checking unmap calls.  If the runtime is going to go around automatically unmapping and then remapping instances, it needs a way to invalidate existing accessors for those physical instances which is not something we have today.  The invariant I guarantee today is that whatever accessors are valid when you make a runtime call will still be valid by the time that runtime call returns.  You need to propose some way to do something similar or a way invalidate accessors (hopefully in a way that doesn't involve checking if they are still valid before every read/write/reduce).

**Comment by streichler** [comment]
Then treat multiple inline mappings as being in simultaneous mode so that the previous accessor is still valid.  Require an acquire/release around the inner inline mapping if you want to be able to map it somewhere else.

**Comment by lightsighter** [comment]
What if the two inline mappings are for intersecting but non-dominating logical regions from different partitions?

**Comment by streichler** [comment]
What would happen if I tried to do that with simultaneous coherence?

**Comment by lightsighter** [comment]
If these were tasks, we would have to wait for the first task to finish, so we can issue a copy to the new physical instance and then we could start the second task.  If we have to do that here, we have to unmap the first physical instance, issue the copy, and then wait for the copy to be ready before using the second instance.  This is would need to be done regardless of the coherence (modulo relaxed).

The invariant I really want to maintain is that all the accessors that were valid before a runtime call are still valid after a runtime call.  We guarantee that today.  However, even with your properly nested inline mapping approach, we would end up breaking that invariant.  So if we want to go down that path, we need a way to invalidate accessors and do so in a way that doesn't involve constantly needing to check them for validity during all reads/writes/reduces.

**Comment by elliottslaughter** [comment]
The more I think about this the worse it looks to me. Consider the atomic case:

    task f(r) where reads writes atomic(r) do
      -- use r inline...
      unmap(r)
      g(r) -- RWE(r)
      h(r) -- RWE(r)
      map(r)
      -- use r inline again...
    end

If I'm understanding Sean's semantics properly, the scope of the inline mapping ends after the first `unmap`. The `map` thus starts a new conceptual scope. But this means the task isn't atomic any more! The two inner tasks `g` and `h` are exposed the outside context as if the task were not an indivisible unit. That seems like a bigger conceptual issue than even the properly-overlapping issue. You can't use the runtime's support for automatic unmapping here because it'll serialize the inner tasks. And the problem just reappears elsewhere if you try to add rules so that the task continues to be an atomic unit.

Practically speaking, I'm also not sure that the compiler follows the proposed properly-nested semantics for inline mappings. The current span-maximizing approach is at least reasonably straightforward to think about, and I'm not sure that would be true in this properly-nested world.

I think what I would want---if anything, at this point---would be a mechanism for a forceably-inlined task launch. We kind of have this with mapping inline today, but I'm not sure it really gets the job done. (E.g. are you still on the same stack? Will the runtime even realize you want to run inline before something gets deferred?)

But I'm also ok with not having this. Tasks serve as a unit of isolation, and we should use them as such. It's unfortunate that it's so much work to register a task from a library (e.g., how do you choose a task ID safely without knowing anything about the application?), but that's something we ought to work on anyway.

**Comment by streichler** [comment]
No, you've raised a completely separate issue.  There's no inline mapping there - just an explicit unmap and remap of an instance that was mapped before task launch time.  But if you'd prefer not to
tackle this can of worms by the horns right now, it's your issue to maintain or close as you see fit.  :)

**Comment by elliottslaughter** [comment]
You run into the same issue if you inline map an instance with atomic coherence. You can't let the runtime unmap/map the instance automatically, because then any child tasks with be serialized, but you also can't unmap/map the instance yourself, because then you'll lose your mapping (and you won't be atomic anymore with respect to the scope you originally wanted to be atomic).

In order for this to be successful, I think we need to separate the idea of a context scope from the idea of having an instance mapped. Having the two tied together is cause for trouble.

**Comment by lightsighter** [comment]
Just to clarify a few things: for the example above, the atomic coherence applies to the parent task's execution, so all that means is that any effects that take place inside the parent task have to made visible in the mapped instance before the parent task completes.  This means that any arbitrary unmap/remap stuff inside the parent task is all fine because the runtime will flush the effects back to that physical instance (or it will be all fine once I fix the other bug Elliott raised about atomic coherence).

The notion of atomic inline mappings makes sense in the context that it means they might be able to be able to be re-ordered around earlier task launches.  However, once that happens, I'm not sure how the runtime can guarantee there is no deadlock.

As for doing forced inline execution of a task, there is a mechanism in place for that already, but for obvious reasons it is controlled by the mapper.  If you set the 'inline_task' flag in 'select_task_options' the task will be inlined right there and then using the parent task's physical regions.  This hasn't been well tested, but it's there if you want to try it out.

**Comment by elliottslaughter** [comment]
My argument is that that isn't a useful semantics for atomic inline mappings. What I need for atomic to be useful is to have some scope over which I know I am atomic (with respect to sibling operations). If that scope gets sliced up whenever I do a unmap/map call, then I'm no longer atomic over the scope I originally wanted to be atomic over. This can be a cause for invisible latent bugs if people are very careful to not call anything that might launch a task or otherwise require an unmap/mall call.

I think the moral of the story here is that all libraries need to be written as tasks in order to have sane semantics. Inline mappings are asking for trouble if you do not control the calling context, because the system doesn't provide adequate isolation from the parent context. We could try to monkey with the semantics of inlines to provide this isolation, but I'm not convinced we have to. I think we should rather spend our time on making tasks easier to define and call inside libraries.

**Comment by lightsighter** [comment]
I'm a little confused about what you mean when you say the system doesn't provide adequate isolation from the parent context?  I believe the way that high-level runtime is doing atomic coherence right now is consistent with our operational semantics from the type system paper.  So that if the parent task has 'atomic' coherence on region, then all of its side effects on that region must appear atomically.  This means that you do get isolation from siblings of the parent task automatically, and you can reason locally within a task context about relaxed coherence modes.  Does that still cause you problems or not?

**Comment by elliottslaughter** [comment]
Looking at this again, I'm not entirely sure I'd want the behavior that initially motivated this issue. It seems to me that it's actually very bad style for libraries to block the calling task, so in all likelihood the preferred solution would be launch an inner task if that's deemed necessary. I will close this unless feels the semantics discussion itself is important.
