### ISSUE TITLE
Attach source location to regions, etc.

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#819]
I'd like to propose we define a standard way to attach a source location to a region or other Legion object. For objects that already support semantic info, I suggest we just make this a pre-defined semantics info tag. For the moment, I am not proposing any specific semantics for this semantic info, other than that the value is a NUL-terminated C string. In the eventual future, it might be possible to pull this out and report in along with Legion error messages.

Example:

```c++
auto r = runtime->create_logical_region(...);
auto sloc = "my_source_file.cc:123";
runtime->attach_semantic_information(r, SOURCE_LOCATION, sloc, strlen(sloc)+1);
```

For the moment, this might be enough that an enterprising user could go into GDB and get the value of the `SOURCE_LOCATION` semantic info at the point where an error occurs. If Regent and other tools automatically attach this location, then this could help users pinpoint errors.

In the eventual future, we could upgrade error messages to include this. As a strawman example:

```
Error: Task foo does not have a region requirement for region R (1,3,4)
Region R (1,3,4) was created at my_source_file.cc:123
```

For the moment I just propose creating the pre-defined tag type, and then we can decide what to do about the error messages later.

**Comment by lightsighter** [comment]
I've added these tags in 0af167368b and made a note to use them in issue #632. I believe we can close this issue.

**Comment by elliottslaughter** [comment]
Regent is now attaching this information as of 17de7c4c299a39a7569a2e874ea682f64373719b, and I have confirmed that we can retrieve it at a warning callsite.
