### ISSUE TITLE
Regent - Issue with parallelism/partitioning

### ISSUE THREAD

**Issue by LonelyCat124** [StanfordLegion/legion#825]
Hi,

Regent version - latest master as of 16:30 21/4/2020, built with --openmp

I have been working on a regent code for a little bit, and am working on performance enhancement right now. The code is a stencil code, with a variety of loops over different loop bounds for different tasks. I've setup these loop bounds as partitions of the global space, and further partitioned them (and created halos) in the code:
```
  --Create the full partitions
  var full_ispace =  ispace(int2d, {x=1, y=1})
  var full_grid = partition(equal, grid, full_ispace)
  var full_sea_surface = partition(equal, sea_surface, full_ispace)
  var full_sea_bed_to_mean_sea_level = partition(equal, sea_bed_to_mean_sea_level, full_ispace)
  var full_velocity = partition(equal, velocity, full_ispace)

  --loop bounded partitions
   var _1N1M_velocity = image(velocity, full_velocity, calculate_1_to_N_1_to_M)
   var _2N2M_sea_surface = image(sea_surface, full_sea_surface, calculate_2_to_N_2_to_M)
   var _2N2M1_sea_surface = image(sea_surface, full_sea_surface, calculate_2_to_N_2_to_M1)
   var _2N2M1_velocity = image(velocity, full_velocity, calculate_2_to_N_2_to_M1)
   var _2N12M_sea_surface = image(sea_surface, full_sea_surface, calculate_2_to_N1_2_to_M)
   var _2N12M_velocity = image(velocity, full_velocity, calculate_2_to_N1_2_to_M)
   var _FN1M_velocity = image(velocity, full_velocity, calculate_1_to_full_1_to_M)
   var _1NFM_velocity = image(velocity, full_velocity, calculate_1_to_N_1_to_full)

  var tilesize : int = 84 -- 256 -- 128
  --Partition the velocity field as required for the update_velocity launcher
  var local_x : int = setup_data[0].jpiglo / tilesize
  if(local_x < 1) then
    local_x = 1
  end
  var local_y : int = setup_data[0].jpjglo / tilesize
  if(local_y < 1) then
    local_y = 1
  end
  var partition_space = ispace(int2d, {x = local_x, y = local_y})
  var partitioned_2N2M1_velocity = partition(equal, _2N2M1_velocity[int2d({0,0})], partition_space)
  var _2N2M1_velocity_halos = image(velocity, partitioned_2N2M1_velocity, calculate_halo_size)
...
```
More partitions of various of these bounds are created further on, not all of which use the same `partition_space` (some have a tilesize of 128 instead, and some are Nx1 or 1xM instead). All was working correctly until the later tasks which use Nx1 or 1xM partitions. In serial (`-ll:cpu 1`) correctness is preserved, however when I use `ll:cpu 24` (or other values above 1) the code is no longer correct. If I add a fence into the main task loop between these tasks as some previous tasks the error no longer occurs (all tasks have their reads/writes documented). The newly edited task has some weirdness where it reads and writes from the same field in the fspace at neighbouring points, however the partition is created in such a way to ensure the task has control of ordering

To attempt to debug the issue, I looked at `https://legion.stanford.edu/debugging/`, and tried the partition check (the previous tests I didn't work out how to do with regent/skipped the backtrace), and figured I must be doing something wrong, as this returns an error:
```
[0 - 2b6603582700] {5}{runtime}: [error 71] LEGION ERROR: Call to partitioning function create_partition_by_domain in main (UID 1) specified partition was ALIASED_INCOMPLETE_KIND but the partition is disjoint. (from file /lustre/scafellpike/local/HCH028/mjm02/axc67-mjm02/ECP/PSycloneBench/ocean/nemo/nemolite2d/manual_versions/regent/legion/runtime/legion/legion_context.cc:5078)
```

I'm unclear how this can occur - as far as I understand out the only way that the code could reach a `create_partition_by_domain` call would be from an image call in regent (so my halo creation or loop bound partitioning calls), but I took these from one of the regent examples, and halos should never fall off the full grid, , e.g.:
```
task calculate_1_to_N_1_to_full( private_bounds : rect2d) : rect2d

    return rect2d({{1,1}, {private_bounds.hi.x-1, private_bounds.hi.y}})

end

task calculate_halo_size( private_bounds: rect2d) : rect2d
  return rect2d({ private_bounds.lo - {1,1}, private_bounds.hi + {1,1} })
end
```

Any idea what I should look at to try to fix the error given by the partitioning check or otherwise investigate the serial/parallel issue. I looked at a profile of the code with legion_spy to show dependencies and for a short run (12 steps as opposed to 12k) the dependencies looked how I would expect.

**Comment by lightsighter** [comment]
It's worth noting that the partition check that you are using is strict: if you aren't both sound and precise your specification of the partition's disjointness and completeness information then it will give you an error. In this particular case, your description of the partition is sound but not precise. This means that your code at least is safe to run and will behave as expected, but it may incur additional runtime overhead due to imprecision in the disjointness specification of the partition.

I will leave it up to @elliottslaughter to comment on if and/or how you can change this specification.

**Comment by elliottslaughter** [comment]
It's a little bit hard to know exactly which partition we're talking about here because the error message does not include the name of the partition, but it's probably one of the `image` partitions because `equal` is disjoint and complete by definition.

In theory you should be able to either comment our your partitioning code, or else go down it line by line, and mark each one as `disjoint, complete` (as appropriate) until the errors go away.

I should also note that regardless of partitioning, that shouldn't cause your code to be wrong with different values of `-ll:cpu` unless you are accessing the subregions out of bounds. I would recommend running with `-fbounds-checks 1` to determine whether this is the case or not.

**Comment by LonelyCat124** [comment]
The bounds check fixed the parallelism issue.

When you say to label the partitions, how do I do that? I just add the `disjoint, complete` etc. as the type or as the first argument to the `image` call?

Where is the best documentation for Regent now? I'd been relying on the website but I'm not sure if there's a better set of documentation?

**Comment by elliottslaughter** [comment]
I updated the reference, please check again and see if that answers your questions. In general, it's still the best place to look, it just lags sometimes when we add new features. If there is anything that is missing or incomplete feel free to create an issue for it and I'll update the reference.

**Comment by LonelyCat124** [comment]
I'm still looking into this, I was having some issues with it finding some "declared aliased" partitions when i declared all to be disjoint, so I started reinstalling regent but am now hitting a brick wall trying to get it to build terra, just running either ./install.py or `./install.py --terra-branch release-1.0.0-beta1`. Can i double check what the latest version of llvm that is supported (I tried 3.5 3.8 and I think 6 to no success) and if there are requirements on LIBCXX (I'm building on a Redhat machine so will need to check I have a suitable version perhaps). My best attempts all failed on the final link for terra with more ouput that I can possible paste (more than my entire terminal usually), or
```
../lib/terra.a(ConvertUTFWrapper.cpp.o): In function `llvm::convertUTF16ToUTF8String(llvm::ArrayRef<char>, std::string&)':
ConvertUTFWrapper.cpp:(.text._ZN4llvm24convertUTF16ToUTF8StringENS_8ArrayRefIcEERSs+0x4c9): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
../lib/terra.a(SourceMgr.cpp.o): In function `llvm::SMDiagnostic::print(char const*, llvm::raw_ostream&, bool, bool) const':
SourceMgr.cpp:(.text._ZNK4llvm12SMDiagnostic5printEPKcRNS_11raw_ostreamEbb+0xd27): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
../lib/terra.a(StringRef.cpp.o): In function `std::bitset<256ul>::_M_check(unsigned long, char const*) const [clone .isra.16] [clone .part.17]':
StringRef.cpp:(.text.unlikely._ZNKSt6bitsetILm256EE8_M_checkEmPKc.isra.16.part.17+0x13): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
../lib/terra.a(StringMatcher.cpp.o): In function `llvm::StringMatcher::EmitStringMatcherForChar(std::vector<std::pair<std::string, std::string> const*, std::allocator<std:
:pair<std::string, std::string> const*> > const&, unsigned int, unsigned int) const':
StringMatcher.cpp:(.text._ZNK4llvm13StringMatcher24EmitStringMatcherForCharERKSt6vectorIPKSt4pairISsSsESaIS5_EEjj+0x1059): undefined reference to `std::__throw_out_of_rang
e_fmt(char const*, ...)'
../lib/terra.a(AggressiveAntiDepBreaker.cpp.o): In function `llvm::AggressiveAntiDepBreaker::StartBlock(llvm::MachineBasicBlock*)':
AggressiveAntiDepBreaker.cpp:(.text._ZN4llvm24AggressiveAntiDepBreaker10StartBlockEPNS_17MachineBasicBlockE+0x68b): undefined reference to `std::__throw_out_of_range_fmt(c
har const*, ...)'
../lib/terra.a(AggressiveAntiDepBreaker.cpp.o):AggressiveAntiDepBreaker.cpp:(.text._ZN4llvm22AggressiveAntiDepState11UnionGroupsEjj+0x74): more undefined references to `st
d::__throw_out_of_range_fmt(char const*, ...)' follow
clang-3.8: error: linker command failed with exit code 1 (use -v to see invocation)
```
with llvm-3.8 through the install script - can separate this out into a different issue if I'm not doing something completely wrong.

**Comment by LonelyCat124** [comment]
Ok, so right now the partition check tells me that:
```
[0 - 2b275f472700] {5}{runtime}: [error 71] LEGION ERROR: Call to partitioning function create_partition_by_domain in model_init (UID 32) specified partition was ALIASED_INCOMPLETE_KIND but the partition is disjoint. (from file..../regent/legion/runtime/legion/legion_context.cc:5074)

[0 - 2ae277484700] {5}{runtime}: [error 71] LEGION ERROR: Call to partitioning function create_partition_by_domain in main (UID 1) specified partition was ALIASED_INCOMPLETE_KIND but the partition is disjoint.
```

All my image calls are (currently) set to `image(disjoint, incomplete, ...)` at the moment and all my calls to partition are `partition(equal, ...)`
I'm pretty sure that in fact many of my image calls are `aliased`, but I can't eliminate that partition error. In the `model_init` task I have the following calls to create partitions:

```
    var full_partition = partition(equal, grid, ispace(int2d, {1,1}))

    var centre_region = image(disjoint, incomplete, grid, full_partition, calculate_internal_size)
    var west_region = image(disjoint, incomplete, grid, full_partition, calculate_west_boundary)
    var east_region = image(disjoint, incomplete, grid, full_partition, calculate_east_boundary)
    var north_region = image(disjoint, incomplete, grid, full_partition, calculate_north_boundary)
    var south_region = image(disjoint, incomplete, grid, full_partition, calculate_south_boundary)
```

The main task has many more but they all have similar function layouts.

**Comment by lightsighter** [comment]
It's worth noting that the partitioning check is strict, e.g. if you differ from what it actually is in any way then the runtime will complain. It's possible to be sound by over-approximating (e.g. saying that the partition is aliased when it is disjoint), so consider that when reading the error messages from the disjointness check.

**Comment by elliottslaughter** [comment]
This a Regent bug, I'm working on a fix.

**Comment by elliottslaughter** [comment]
Pushed a fix to master in ee7daa8b93d816ef44829d30554acad9d956c02b. @LonelyCat124 please pull and try again.

**Comment by elliottslaughter** [comment]
@LonelyCat124 also, if you were having Terra issues and believe they're not just a matter of the system configuration being weird (particularly, if there's something we could fix on the Terra side to improve things), please submit an issue here about it: https://github.com/terralang/terra/issues/new

**Comment by LonelyCat124** [comment]
That fixed the issues with the partition check 👍 
The terra issues I think were all due to old versions of glibc++ (where the higher version was GLIBCXX_3.4.20) and since that release is probably ~2015 it shouldn't be an issue, once I found an appropriate GLIBCXX (3.4.22 +) I had no issues.

**Comment by elliottslaughter** [comment]
Closing for now, feel free to open a new issue if you find anything else.
