### ISSUE TITLE
cmake: add legion dependency on cudart if hijack is disabled

### ISSUE THREAD

**Issue by aheirich** [StanfordLegion/legion#826]
comment out these lines: https://gitlab.com/StanfordLegion/legion/-/blob/control_replication____hijack_registration_hack/runtime/CMakeLists.txt#L422-424
8:53
and this line: https://gitlab.com/StanfordLegion/legion/-/blob/control_replication____hijack_registration_hack/CMakeLists.txt#L216
8:54

**Comment by streichler** [comment]
This might also be an issue with shared libraries from the makefile flow.  Basically, now that legion has CUDA code in it, it needs to depend on cuda libs rather than assuming it'll get them transitively from realm.  I'll look at both make and cmake for this.

**Comment by streichler** [comment]
I believe this should be fixed (for both build systems) with commit 0660a5ae.  @aheirich can you try cherry-picking this change into your tree (after backing out the workaround) to see if it works in your specific case?

**Comment by aheirich** [comment]
confirmed works
