### ISSUE TITLE
Legion: Display ids with consistent radix

### ISSUE THREAD

**Issue by mpokorny** [StanfordLegion/legion#833]
There's some inconsistency when various id values are written to stdout. For example, when I write an `IndexSpace` to `std::cout`, it is displayed using decimal values, say `IndexSpace(17,17)`. However, if the runtime reports a warning associated with that `IndexSpace`, it might refer to it as "index space 11". Whereas the spelling of "IndexSpace" is inconsistent, that doesn't bother me as much as always needing a moment to recall that the printed values have different radices.

**Comment by lightsighter** [comment]
It used to be important to look at index space IDs in hex and not decimal. Legion hands out index space IDs in a different way now, so the hex representation is antiquated. If you don't mind I'm going to add this as a bullet to #632 and close this issue.

**Comment by mpokorny** [comment]
Fine by me

**Comment by lightsighter** [comment]
Updated #632. Closing this issue.
