### ISSUE TITLE
Regent: error with CUDA enabled

### ISSUE THREAD

**Issue by rupanshusoi** [StanfordLegion/legion#835]
I'm getting the following error on running any Regent program

```
warning: Linking two modules of different data layouts: '/usr/local/cuda/nvvm/libdevice/libdevice.10.bc' is '' whereas 'external' is 'e-m:e-i64:64-f80:128-n8:16:32:64-S128'

/opt/legion/language/terra/src/terralib.lua:770: expected a target object
stack traceback:
	[C]: in function 'assert'
	/opt/legion/language/terra/src/terralib.lua:770: in function 'newcompilationunit'
	/opt/legion/language/terra/src/cudalib.lua:31: in function 'toptx'
	/opt/legion/language/src/regent/cudahelper.t:309: in function 'jit_compile_kernels_and_register'
	/opt/legion/language/src/regent/std.t:4199: in function 'setup'
	/opt/legion/language/src/regent/std.t:4554: in function 'start'
	r.rg:5: in main chunk
```
Legion is built with `python3 ./install.py --no-cmake --cuda` using GCC 8.3.1

The error vanishes on building without CUDA.

**Comment by elliottslaughter** [comment]
This is a symptom of this issue: https://github.com/terralang/terra/pull/299#issuecomment-416673042

It should be harmless, and I think it's probably not worth the effort to fix.

**Comment by elliottslaughter** [comment]
Oops, stopped reading at the warning. The _actual_ error is this and should be fixed if you update Terra: https://github.com/terralang/terra/pull/442

**Comment by rupanshusoi** [comment]
Updating Terra worked, thanks!
