### ISSUE TITLE
InstanceAllocResult Hang Under Deferred Allocation

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#841]
In the case where Realm allocates an instance using deferred allocation, the `InstanceAllocResult` is currently being delayed until the allocation actually is performed rather than responding as soon as Realm knows whether the allocation will succeed or not. This is at a minimum a performance bug, but can also lead to hangs if the client is waiting to see if allocation is going to succeed or not and that is blocking progress of code that actually needs to run to free up the instance for the allocation to succeed.

To reproduce the issue, apply this temporary patch to Legion:

```
diff --git a/runtime/legion/legion_instances.cc b/runtime/legion/legion_instances.cc
index e15641098..4ece66f8f 100644
--- a/runtime/legion/legion_instances.cc
+++ b/runtime/legion/legion_instances.cc
@@ -992,7 +992,10 @@ namespace Legion {
       // have been detached while still holding valid references so they
       // have to go through the full path every time
       if (!is_external_instance() && check_valid_and_increment(source))
+      {
+        add_base_valid_ref(source, mutator);
         return true;
+      }
       // If we're not the owner, we're not going to succeed past this
       // since we aren't on the same node as where the instance lives
       // which is where the point of serialization is for garbage collection
```

and then run one of the following two Regent tests:

```
./regent.py tests/regent/run_pass/parallel_prefix_1d_inplace.rg
./regent.py tests/regent/run_pass/parallel_prefix_1d_large.rg
```

Both tests should hang deterministically.

@magnatelee for visibility since he has observed this case in practice as well.

**Comment by streichler** [comment]
I forgot to update things here, but commit 94e4e3e should hopefully have fixed it.  @lightsighter @magnatelee are there any remaining issues with this?

**Comment by lightsighter** [comment]
Both my examples with the patch above still hang, although they hang in a different way now. We get past the allocation stage, but it seems like the tasks never run because the deferred allocations are never actually being satisfied. It could be because the patch adds an unnecessary reference and keeps previous instances alive too long, but I haven't been able to confirm that yet.

**Comment by streichler** [comment]
Would you like to keep this issue open until you can resolve that, or close it now and reopen if needed?

**Comment by lightsighter** [comment]
I'm fine with closing it, but I would like @magnatelee to sign off as well first.

**Comment by magnatelee** [comment]
I'm also fine with closing it.
