### ISSUE TITLE
Allow Python processors to call OpenMP code

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#842]
My understanding is that there's a short term hack that would enable Python to call OpenMP code. There is also a longer term path to refactoring that would make this more clean.

We would use this for ExaFEL.

**Comment by streichler** [comment]
Issue #680 tracks the longer term path, but in the short term, we could add an option like `-ll:pyomp N` that enables openmp runtime support on a python processor and gives a total of N threads (which can be 1 if you don't actually want data parallelism).  The processor would retain its `PY_PROC` kind, which means you wouldn't be able to spawn arbitrary OMP_PROC Legion tasks on it, but it would handle any python modules that use openmp (assuming we have sufficient omp runtime API coverage).

@elliottslaughter does this still sound useful?
@lightsighter or @magnatelee , does this cover any of your use cases?

**Comment by lightsighter** [comment]
Almost... what I really need is `-ll:pygpu`.

**Comment by elliottslaughter** [comment]
FWIW, we would use `-ll:pygpu` too if it were available.

**Comment by AntoineDujardin** [comment]
Would that mean we would have `-ll:py`, the number of python processors, `-ll:pyomp`, the number of OMP threads per python processor? If it's not too much of a hack, that would certainly be helpful.

**Comment by streichler** [comment]
> Would that mean we would have `-ll:py`, the number of python processors, `-ll:pyomp`, the number of OMP threads per python processor? If it's not too much of a hack, that would certainly be helpful.

Yes, with the caveat that having more than one python proc per rank (i.e. `-ll:py N` with `N > 1`) is highly experimental and only has a chance of working in the `subprocess` branch.

**Comment by elliottslaughter** [comment]
@streichler Any updates on this? We're getting to the point where we would like to actually use this.

**Comment by streichler** [comment]
This is in master with commit 6a8cb06.  @elliottslaughter any issues with the current implementation?

**Comment by elliottslaughter** [comment]
So far we've been using it without any issues, so all good on our end.
