### ISSUE TITLE
Regent: support for two-level projection functors

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#845]
Related to #844, we need support for two-level projection functors. E.g. things like:

```
__demand(__index_launch)
for i in launch_domain do
    my_task(p[i][K])
end
```

I think there are three main cases:

  * `p` is disjoint and is only referenced once. In this case, the value of `K` does not matter, nor does it matter if the second level partition is disjoint.
  * `p` and the second level partition are both disjoint, and `K` is a constant. In this case, it is possible to have multiple of these references as long as they are for different values of `K`.
  * No constraints on `p`, `K` or the second level partition: but can only do read-only, reduce, etc.

**Comment by syamajala** [comment]
We would like to start thinking about porting the stencil to regent to make it easier to debug in the future. How much work is involved in doing this and #844?

**Comment by elliottslaughter** [comment]
This is probably a week or so of work, but the bigger issue is #844 where we don't really have a clear direction for the design of the abstraction right now. (So if you have ideas, please suggest them.)
