### ISSUE TITLE
Create a Legion example demonstrating virtual mapping

### ISSUE THREAD

**Issue by streichler** [StanfordLegion/legion#85]
Idea is to create a very large logical region and launch a subtask that only inline maps a tiny part.  Assigned to me until I can trick somebody else into doing it.  :)

**Comment by chuckatkins** [comment]
Ping?

This would be super useful to have using the new mapper APIs.

**Comment by jiazhihao** [comment]
@chuckatkins It is quite coincidental that I just talked to Sean about this yesterday.:) The idea is to use virtual mapping for graph applications --- every task may potentially need read privilege on the entire graph, but based on the input and partitioning, they may only access a small subset of the graph. This could be an useful case for virtual mapping. I will post an update once we have the example.:)

**Comment by lightsighter** [comment]
Thanks @jiazhihao 

Let's put in the examples directory when you are done.

**Comment by streichler** [comment]
I'm becoming more of the opinion that our examples should be as simple as possible, which generally means they won't actually do anything useful.

**Comment by chuckatkins** [comment]
In this particular case we're really only looking for a bare-bones virtual mapping example.  Something that shows how to pass a region into a task "unmapped" so we can just manually map a subregion determined by code inside the task.  In the past we could literally just set task->regions[i].virtual_map = true inside map_task and then call the default mapper's map_task(task) but that seems to longer be the case.

**Comment by lightsighter** [comment]
The example that @jiazhihao will show how to do this precisely, but essentially what you do is for each of the region requirements, you say that you want a virtual instance to be used for that region requirement.  You can get the name for the virtual instance with this method:

https://github.com/StanfordLegion/legion/blob/master/runtime/legion/legion_mapping.h#L96

and put it in the set of chosen instances:

https://github.com/StanfordLegion/legion/blob/master/runtime/legion/legion_mapping.h#L401

**Comment by chuckatkins** [comment]
>  but essentially what you do is for each of the region requirements, you say that you want a virtual instance to be used for that region requirement.

Do we still do this by setting `task->regions[i].virtual_map = true` inside `map_task` or is it through other means?

**Comment by streichler** [comment]
Example here: https://github.com/StanfordLegion/legion/blob/master/examples/virtual_map/virtual_map.cc

@chuckatkins Please take a look at this and let me know which questions it fails to answer for you?
