### ISSUE TITLE
Passing arguments to Regent apps with GASNet

### ISSUE THREAD

**Issue by LonelyCat124** [StanfordLegion/legion#868]
Not sure if this is the right place to ask this, so apologies if not.

I'm trying to run GASNet with a Regent app (built with saveobj, which I also need to ask a question about here).

I installed GASNet (and tested it), and reinstalled regent with `./install.py --with-gasnet $HOME/.INSTALL/GASNet --conduit ibv --clean -j 8`

The Regent program is built with 
```
  local root_dir = arg[0]:match(".*/") or "./"
  local out_dir = (os.getenv('OBJNAME') and os.getenv('OBJNAME'):match('.*/')) or root_dir
  local link_flags = terralib.newlist({"-L" .. out_dir, "-lm", "-lgfortran", "-lgocean2d_io_mod"})

  local exe = os.getenv('OBJNAME') or "nemolite2D"
  regentlib.saveobj(main, exe, "executable", set_mappers, link_flags)
```
where `set_mappers` is just an empty terra function for now (my assumption being this will just let me use the default mapper).

When I run the app without arguments ( `bsub -q SKL -n 2 -R "span[ptile=1]" -W 01:00 -e error -o output "gasnetrun_ibv -n 2 -N 2 -c 32 -- ./nemolite2D > out"`), I get an error (`gasnetrun: unable to locate a GASNet program in '/../regent/./nemolite2D'`) but the application does seem to run, though I'm unclear if it is running with GASNet or not.

When I add the flags:
```
bsub -q SKL -n 2 -R "span[ptile=1]" -W 01:00 -e error -o output "gasnetrun_ibv -n 2 -N 2 -c 32 -- ./nemolite2D -t1 84 -t2 128 -ll:cpu 28 -ll:util
 4 > out"
```

I get more errors and the program won't run
```
gasnetrun: unable to locate a GASNet program in '/../regent/./nemolite2D -t1 84 -t2 128 -ll:cpu 28 -ll:util 4'
failed to exec ./nemolite2D
```

Am I doing something wrong to run with GASNet?

**Comment by elliottslaughter** [comment]
I do not recommend using the `gasnetrun_*` scripts to launch jobs with Regent. These scripts do some hacks like trying to inspect the binary to determine certain properties, which just doesn't work with Regent. Instead I would use whatever job launcher is recommended in your system.

Since you're using `bsub` I'm guessing your system may use `jsrun`? Or is there some other launcher that your system uses?

**Comment by LonelyCat124** [comment]
We're still on `blaunch` and using that seems to fix it. Thanks! Is my assumption about leaving the 3rd argument to saveobj as an empty function just meaning that I use the default mapper correct?

**Comment by elliottslaughter** [comment]
Yes, that's right.

**Comment by LonelyCat124** [comment]
Another related question if thats ok - I'm trying to get a multinode profile, and on https://legion.stanford.edu/profiling/ it says to use a command like:
`"blaunch ./nemolite2D -ll:cpu 28 -ll:util 4 -ll:csize 16000 -t1 512 -t2 2048 -lg:prof 2 -lg:prof_logfile multinode_prof_%.gz > out2"`
At the end of this I'm only getting a `multinode_prof_0.gz` - does this mean the second node isn't doing anything or am I doing something wrong when trying to get this trace?

**Comment by seemamirch** [comment]
The options to the profiler are ok - it will produce 2 log files if it’s running on multiple nodes.

On Jun 9, 2020, at 2:42 AM, Aidan Chalk <notifications@github.com<mailto:notifications@github.com>> wrote:



Another related question if thats ok - I'm trying to get a multinode profile, and on https://legion.stanford.edu/profiling/ it says to use a command like:
"blaunch ./nemolite2D -ll:cpu 28 -ll:util 4 -ll:csize 16000 -t1 512 -t2 2048 -lg:prof 2 -lg:prof_logfile multinode_prof_%.gz > out2"
At the end of this I'm only getting a multinode_prof_0.gz - does this mean the second node isn't doing anything or am I doing something wrong when trying to get this trace?

**Comment by elliottslaughter** [comment]
Please run with `-level announce=2` and show us the output. That will tell us definitively whether you've successfully compiled for multiple nodes or not.

**Comment by LonelyCat124** [comment]
Based on this output (code is still running) I'm guessing its not worked correctly? The &NAMCTL stuff is output from my code, but for single node runs is only printed once:
```
[0 - 2b4ad9d338c0] {2}{announce}: node 0 has received all of its announcements
[0 - 2b64d18728c0] {2}{announce}: node 0 has received all of its announcements
&NAMCTL
 JPIGLO=4096       ,
 JPJGLO=4096       ,
 JPHGR_MSH=1          ,
 DX=  1000.0000000000000     ,
 DY=  1000.0000000000000     ,
 DEP_CONST=  100.00000000000000     ,
 NIT000=1          ,
 NITEND=3000       ,
 IRECORD=3000       ,
 RDT=  20.000000000000000     ,
 CBFR=  1.4999999999999999E-004,
 VISC= 0.10000000000000001     ,
 /
&NAMCTL
 JPIGLO=4096       ,
 JPJGLO=4096       ,
 JPHGR_MSH=1          ,
 DX=  1000.0000000000000     ,
 DY=  1000.0000000000000     ,
 DEP_CONST=  100.00000000000000     ,
 NIT000=1          ,
 NITEND=3000       ,
 IRECORD=3000       ,
 RDT=  20.000000000000000     ,
 CBFR=  1.4999999999999999E-004,
 VISC= 0.10000000000000001     ,
 /
```

**Comment by elliottslaughter** [comment]
Right, both nodes think they are node 0. This means one of two things is happening:

1. You didn't compile with GASNet.
2. GASNet didn't connect to the job launcher properly.

I think the next things we'd need to know is what GASNet conduit you are using, and what flags it was built with. It may help to get the compile logs so that we can be 100% sure that you are in fact building against GASNet.

**Comment by LonelyCat124** [comment]
I'm recompiling with:
```
./install.py --with-gasnet $HOME/.INSTALL/GASNet --conduit ibv --verbose --clean -j 8 > log
```
at the moment (same arguments as before). I tested GASNet with ibv with the `gasnetrun_ibv` before (with the large test from its own directory), but not with `blaunch` before. 

Is there anything I should look for/how to get the compile logs if the above command isn't capturing them?

**Comment by elliottslaughter** [comment]
@LonelyCat124 are you still hitting issues with this?

**Comment by LonelyCat124** [comment]
I'm not sure, I'm waiting on an OpenMPI installation with gcc9 still (hopefully that happens this week) as when I do `install.py --gasnet ....` the installer relies on mpicc, and Regent won't build on this system with the gcc7 that MPI is built with.

**Comment by elliottslaughter** [comment]
Huh. What's the issue with GCC 7? I'm pretty sure we test that version in our CI.

**Comment by LonelyCat124** [comment]
I'm not entirely clear whats causing my headaches actually. I get different errors if CC=gcc9 or CC=gcc7, with the same mpi built with gcc7.

With gcc9:
```
mpicxx -o regent.cc.o -c regent.cc  -fPIC   -march=native -DGASNETI_BUG1389_WORKAROUND=1 -O2 -fno-strict-aliasing  -Wall -Wno-strict-overflow  -I/lustre/scafellpike/local/HCH028/mjm02/axc67-mjm02/ECP/PSycloneBench/benchmarks/nemo/nemolite2d/manual_versions/regent/legion/bindings/regent -I/lustre/scafellpike/local/HCH028/mjm02/axc67-mjm02/ECP/PSycloneBench/benchmarks/nemo/nemolite2d/manual_versions/regent/legion/runtime -I/lustre/scafellpike/local/HCH028/mjm02/axc67-mjm02/ECP/PSycloneBench/benchmarks/nemo/nemolite2d/manual_versions/regent/legion/runtime/mappers -I/lustre/scafellpike/local/HCH028/mjm02/axc67-mjm02/.INSTALL/GASNet/include -I/lustre/scafellpike/local/HCH028/mjm02/axc67-mjm02/.INSTALL/GASNet/include/ibv-conduit
```
I get 10000 lines of errors which I think are due to the mpicxx compiler hitting the gcc9 headers and not working correctly.

With only gcc7 I get an error at:
```
---> Linking objects into one binary: libregent.so
mpicxx -o libregent.so regent.cc.o regent_partitions.cc.o bishop_mapper.cc.o bishop_c.cc.o murmur_hash3.cc.o    -shared -Wl,--whole-archive -llegion -lrealm -Wl,--no-whole-archive -Wl,-rpath=/lustre/scafellpike/local/HCH028/mjm02/axc67-mjm02/.INSTALL/openmpi4-gcc7/lib -L. -llegion -lrealm -lrt -lpthread -ldl -rdynamic -L/lustre/scafellpike/local/HCH028/mjm02/axc67-mjm02/.INSTALL/GASNet/lib -lrt -lm -lgasnet-ibv-par -libverbs -L/lib -lmpi -lz
```
telling me to recompile GASNet with -fPIC which I'll try now

**Comment by LonelyCat124** [comment]
I think it actually built now - I'm going to set a run going before I sleep and see what happens

**Comment by LonelyCat124** [comment]
Hmm, it fails to run now with a new error message:
```
*** FATAL ERROR (sqg5b45.bullx:5375): Requested spawner "(not set)" is unknown or not supported in this build
*** FATAL ERROR (sqg5b45.bullx:5376): Requested spawner "(not set)" is unknown or not supported in this build
WARNING: Ignoring call to gasneti_print_backtrace_ifenabled before gasneti_backtrace_init
WARNING: Ignoring call to gasneti_print_backtrace_ifenabled before gasneti_backtrace_init
Jun 17 22:39:55 2020 5368 3 10.1 lsb_launch(): Failed while waiting for tasks to finish.
```

with `gasnetrun_ibv` and can still run gasnet tests with this install.

**Comment by elliottslaughter** [comment]
Weren't you going to use the `mpirun` or similar? I really don't recommend `gasnetrun_*` for any real work.

**Comment by LonelyCat124** [comment]
Sorry this was with `blaunch`, I only used `gasnetrun_ibv` to test the gasnet install was working.

I'm going to try to build GASNet and Regent with the MPI launcher for now and see if that works (even if performance may not be as good, working is better than not).

**Comment by elliottslaughter** [comment]
How are you building GASNet? Are you using our build setup here? https://github.com/StanfordLegion/gasnet

**Comment by elliottslaughter** [comment]
I don't think this ought to be necessary, but based on the error message you're getting it might help to set `GASNET_IBV_SPAWNER` to `mpi`. See https://gasnet.lbl.gov/dist-ex/ibv-conduit/README

**Comment by LonelyCat124** [comment]
No, I'd just followed the legion webpage and downloaded GASNet from its own site. I can look at that tomorrow. I'll try the environment variable now, but with ssh spawner not mpi (as I haven't succesfully built GASNet + Regent with mpi yet).

**Comment by LonelyCat124** [comment]
Ok, so I built GASNet from the above repo, and switched to an older version of OpenMPI (I think my OpenMPI4 build isn't working on the machine), and had some success. Regent built with it!

Running with 
`blaunch ./nemolite2D -ll:cpu 28 -ll:util 4 -ll:csize 4096 -t1 256 -t2 1024 -level announce=2 > out`
```
[0 - 7f6767cbd800] {2}{announce}: node 0 has received all of its announcements
[0 - 7fa4181ef800] {2}{announce}: node 0 has received all of its announcements
&NAMCTL
 JPIGLO=1024       ,
 JPJGLO=1024       ,
 JPHGR_MSH=1          ,
 DX=  1000.0000000000000     ,
 DY=  1000.0000000000000     ,
 DEP_CONST=  100.00000000000000     ,
 NIT000=1          ,
 NITEND=3000       ,
 IRECORD=3001       ,
 RDT=  20.000000000000000     ,
 CBFR=  1.4999999999999999E-004,
 VISC= 0.10000000000000001     ,
 /
&NAMCTL
 JPIGLO=1024       ,
 JPJGLO=1024       ,
 JPHGR_MSH=1          ,
 DX=  1000.0000000000000     ,
 DY=  1000.0000000000000     ,
 DEP_CONST=  100.00000000000000     ,
 NIT000=1          ,
 NITEND=3000       ,
 IRECORD=3001       ,
 RDT=  20.000000000000000     ,
 CBFR=  1.4999999999999999E-004,
 VISC= 0.10000000000000001     ,
 /
Tilesize 1: 256
Tilesize 2: 1024
Tilesize 1: 256
Tilesize 2: 1024
Runtime is 66.583472 seconds
Runtime is 67.780684 seconds
```
This looks like before, where its only running on a single node still, and the runtime reflects that (not that i'd necessarily expect this testcase to scale well).I've not run the profiler to test though.

Running with
`mpirun -np 2 ./nemolite2D -ll:cpu 28 -ll:util 4 -ll:csize 4096 -t1 256 -t2 1024 -level announce=2 > out`
```
[0 - 7f4a82ff7800] {4}{threads}: reservation ('CPU proc 1d00000000000005') cannot be satisfied
[1 - 7f11fde0e800] {4}{threads}: reservation ('CPU proc 1d00010000000005') cannot be satisfied
[0 - 7f4a759f9800] {2}{announce}: 0: received announce from 1 (32 procs, 2 memories)

[1 - 7f11f089b800] {2}{announce}: 1: received announce from 0 (32 procs, 2 memories)

[0 - 7f4a82ff7800] {2}{announce}: node 0 has received all of its announcements
[1 - 7f11fde0e800] {2}{announce}: node 1 has received all of its announcements
&NAMCTL
 JPIGLO=1024       ,
 JPJGLO=1024       ,
 JPHGR_MSH=1          ,
 DX=  1000.0000000000000     ,
 DY=  1000.0000000000000     ,
 DEP_CONST=  100.00000000000000     ,
 NIT000=1          ,
 NITEND=3000       ,
 IRECORD=3001       ,
 RDT=  20.000000000000000     ,
 CBFR=  1.4999999999999999E-004,
 VISC= 0.10000000000000001     ,
 /
Tilesize 1: 256
Tilesize 2: 1024
```

The mpirun version then seems to hang at this point (which could maybe be an issue wiht my Regent code? Though I'm not sure what could cause it) before its killled by the queue system after its wall clock time.

**Comment by streichler** [comment]
If you're using OpenMPI, then 'mpirun -n 2' will, by default, give each rank only a single physical core to run on.  This causes these warnings:
```
[0 - 7f4a82ff7800] {4}{threads}: reservation ('CPU proc 1d00000000000005') cannot be satisfied
[1 - 7f11fde0e800] {4}{threads}: reservation ('CPU proc 1d00010000000005') cannot be satisfied
```
but also means that your job could be up to 32x slower if you were using all 32 processors in the single-node run.  If you're trying to get a rank per node, then adding `--bind-to none` to the mpirun command line should remove this restriction, and you can see if that speeds it up.

The other thing to double-check is to run on a smaller dataset (is that controlled by `-t1` and `-t2`?).  If you have something that should run in a second or two, it's much easier to distinguish between "really slow" and "actually hanging".

**Comment by LonelyCat124** [comment]
Ok, that fixes it and it now runs. I tried a small testcase both on a single node (without mpirun) and on multiple nodes, and runtime seems to be much higher than I'd expected.

Single node performance building regent without `--gasnet` is <10 seconds on a single node. If I rebuild with `--gasnet`, the single node performance is around 78 seconds, with no changes to arguments. On two nodes, with `mpirun -np 2 --bind-to none ./nemolite2D -ll:cpu 28 -ll:util 4 -ll:csize 4096 -t1 84 -t2 128 -level announce=2 > out` I get

```
[0 - 7f81351c7800] {2}{announce}: 0: received announce from 1 (32 procs, 2 memories)

[1 - 7fe7720a6800] {2}{announce}: 1: received announce from 0 (32 procs, 2 memories)

[0 - 7f82606c6800] {2}{announce}: node 0 has received all of its announcements
[1 - 7fe89d5f9800] {2}{announce}: node 1 has received all of its announcements
...
Runtime is 59.015602 seconds
```
(and similar runtime without`-level announce=2`)

**Comment by elliottslaughter** [comment]
Could you get profiles from 1 and 2 node runs? Without more information it's a bit hard to say what's going on.

https://legion.stanford.edu/profiling/#legion-prof

Also, one thing to sanity check is just to make sure `mpirun` is actually assigning the two copies of the runtime to different nodes. It would be bad if they were accidentally being assigned to the same node....

**Comment by LonelyCat124** [comment]
From comparing 1 node run compiled with and without gasnet, the CPU and util thread usage seems to vary much more.

Without gasnet:
![image](https://user-images.githubusercontent.com/3043914/85183745-be847380-b284-11ea-8ca9-89e3c7b74206.png)

With gasnet:
![image](https://user-images.githubusercontent.com/3043914/85183751-c2b09100-b284-11ea-935c-20d2e45edb20.png)


I have a multinode profile still being parsed/decoded at the moment, but I'll probably run profiles for 50 steps instead of 3k at the weekend so I can get tasks to be visible more easily.

**Comment by elliottslaughter** [comment]
Ok, so a couple of observations:

1. In both cases your CPU utilization is very low. How big of a problem size is this? How big are the tasks?
2. Is there an iterative loop you could apply tracing to?
3. It would be much easier to see what's going on if you attach either the log files or the rendered profile itself. With these images, I only get the overview of the total execution. I can't answer any of the questions in (1) myself.

**Comment by LonelyCat124** [comment]
1. Yeah, these were still the small problem size where the parallelism is pretty bad. I'm rerunning and analysing a larger run for less timesteps now, and will attach the logs once they're done
2.I think the main timestepping loop is done with
```
  __demand(__trace, __spmd)
  for i = setup_data[0].nit000, setup_data[0].nitend+1 do
  ...all the tasks in here
  end
```

3. I'll attach the logs soon. For this example, single node performance without `--gasnet` was <5s, while with `--gasnet` was ~45s

**Comment by elliottslaughter** [comment]
Yeah, I was referring to the `.gz` files.

Maybe check the output of `-ll:show_rsrv`? I'm wondering if core pinning is off somehow.

**Comment by LonelyCat124** [comment]
I solved the single node performance with gasnet, as I wasn't running with `mpirun` on the single node, and with it the runtime drops to similar as to without gasnet. The multinode performance is still bad, but may be related to how MPI was installed/setup so I'm chasing that down at the moment.

**Comment by LonelyCat124** [comment]
I discussed a variety of things with Elliott off github to do with profiles, and tried a few things to attempt to improve performance on 2 nodes (mostly to this point, to little to no avail).

I plan to (soon) try to control replication branch of Legion, and see if that helps. 

However the main thing Elliott said to post back here about is tracing.
He told me to run with `=dm:memoize 1` to force tracing to happen. On a single node, the runtime (of this short run) increases from 2s to 41s with this.
On two nodes I get this warning:
```
[0 - 7f87243a0780] {4}{runtime}: [warning 1097] LEGION WARNING: WARNING: The runtime has failed to memoize the trace more than 5 times, due to the absence of a replayable template. It is highly likely that trace 1 will not be memoized for the rest of execution. The most recent template was not replayable for the following reason: precondition not subsumed by postcondition. Please change the mapper to stop making memoization requests. (from file /…/regent/legion/runtime/legion/legion_trace.cc:1815)
```
and the code doesn't finish execution in 10 minutes (before the job scheduler kills it).

The traced loop in regent, is simply a timestepping loop:
```
__demand(__trace)
for ... do
  launch the tasks
end
```
There's no changes to the partitions or tasks during the timesteps, so the trace should be reusable as far as I can work out. The only potential thing I could think of is that some partitions are created through `cross_product`, but it still always iterates over the same tasks and index spaces.  Is there anything else that could cause the above error?

**Comment by magnatelee** [comment]
Can you attach a trace dump that you get with `-level tracing=2 -logfile physical_traces_% -lg:dump_physical_traces`? That will tell us why you didn't get any replayable traces.

**Comment by LonelyCat124** [comment]
I don't seem able to run with `-lg:dump_physical_traces` without the code crashing, and the dumps seem to be 0B.

Full command line: `mpirun -np 2 --bind-to none legion/language/regent.py algorithm.rg -ll:cpu 28 -ll:util 4 -ll:csize 4096 -t1 256 -t2 1024 -level tracing=2 -logfile physical_traces_% -dm:memoize 1 -lg:dump_physical_traces` and the only error I'm getting is that there's a seg fault. I'll try running with debugging enabled this afternoon.

**Comment by elliottslaughter** [comment]
@LonelyCat124 are you still hitting this one? I seem to recall you were at least trying to do tracing with your recent efforts.

**Comment by LonelyCat124** [comment]
I hadn't used the code this was failing with in a while, and managed to completely forget.

I actually can't replicate this error any more with a new version of the master. I have some warnings out of GASNet because my build is old but I get the same performance on 2 nodes as 1 node with no crashes

If I use `-dm:memoize 1` I still also get no crashes, but no change in performance.

I think since this is no longer crashing I think at least what causing this has been fixed, and when I use multi-node computations with my current project, if I hit issues then I think its more worth looking into that then.

**Comment by elliottslaughter** [comment]
Ok, let's close this for now and investigate the performance as a separate thread.
