### ISSUE TITLE
RFE: adding markers to profiling timeline from app code

### ISSUE THREAD

**Issue by streichler** [StanfordLegion/legion#87]
Ideally a call to insert a marker in the profiling output, with a name, and maybe a color.  The marker should be placed at the time corresponding to the call (i.e. probably before the actual deferred execution of things launched earlier by that task).
Bonus points if I can then add #label to start the browser on that label, or #label1,label2 to have a
zoomed-in initial range.

**Comment by magnatelee** [comment]
The initial support for this has been made in commit 84234a2. To create a user-marker, you should instantiate class 'LegionProfMarker' included in legion_profiling.h. You could either call 'mark_stop' or put it in a separate scope to record the stop time. The color of user markers is gray by default, but you could change it by manually editing data file 'legion_prof_data.tsv'. I'll close this issue at the moment but feel free to reopen if one of bonus points above seems really necessary.
