### ISSUE TITLE
Improved/updated spack support for Legion

### ISSUE THREAD

**Issue by pmccormick** [StanfordLegion/legion#871]
ECP plans to use [spack](https://computing.llnl.gov/projects/spack-hpc-package-manager) for software deployment.  While we have had a contributed spackage for a while it is out of date with the latest feature set (e.g. kokkos, mpi, python?, others?) and we have been told it has configuration issues in the build (configuration) of GASNet(EX) that accompanies it.  

In general, it would be good to make sure we are up to date on all the latest and greatest 'spackaging'.

**Comment by streichler** [comment]
Non-exhaustive list of things that need doing:
- [ ] Take at least partial control over the Legion spack package definition
- [ ] Incorporate GASNet-EX directly into Legion package as a private dependency
- [ ] Export tools (e.g. legion_spy and legion_prof) in addition to headers/libraries
- [ ] Add support for kokkos interop
- [ ] Add support for MPI network backend?
- [ ] Add support for Python

**Comment by streichler** [comment]
@pmccormick can you provide an update of where we are on this?

**Comment by pmccormick** [comment]
@streichler I have a first cut that includes more feature complete [legion](https://github.com/pmccormick/spack/tree/develop/var/spack/repos/builtin/packages/legion) and [gasnetex](https://github.com/pmccormick/spack/tree/develop/var/spack/repos/builtin/packages/gasnetex)  packages.

Waiting on feedback from the gasnet crew.  Will also need to make sure it works for flexflow (spackage work coming there as soon as the cmake config is updated), and also need to work with the flecsi folks as it will break their use of the current builtin spackages for each package.

I'm ready for some others to kick the tires -- given this was my first spackage I'm sure there are improvements to be made and bugs to be squashed.  Probably really needs some testing (and help) on Cray platforms.

**Comment by mpokorny** [comment]
@pmccormick I might want to give your spack package a try after I get past my current development push. No exotic environments or configurations here, just another potential user.

**Comment by pmccormick** [comment]
@mpokorny -- that would be great.  The more testing the better!

**Comment by streichler** [comment]
Status update: an initial version is working in some repo @pmccormick 's got, and will be published in its own repository (like we do for the gasnet build): https://github.com/StanfordLegion/legion-spackages

Although we're planning to do that soon, it won't be this week, so bumping the milestone to 20.12.

**Comment by ipdemes** [comment]
Hi all,
I have tried this spack packaged for our FLeCSI+Kokkos build and have some comments. Where would be a good place to post them?

**Comment by streichler** [comment]
@ipdemes Go ahead and put them here for now at least.

**Comment by ipdemes** [comment]
@streichler OK.
1. this might be specific to Kokkos+Clang+Cuda build, but we need to be able to add  `+pic`  and `std=..`  to kokkos dependencies when building with Legion
2. I think we could have '+cuda_lambda' be added to kokkos dependencies (assuming that Legion users are using c++11 and higher)

**Comment by streichler** [comment]
@pmccormick are you comfortable with declaring this issue "done"?

**Comment by ipdemes** [comment]
I would like to confirm that there is no more issues with legion Spack package

**Comment by pmccormick** [comment]
Thanks @ipdemes.  With your vote, I'll close this issue.  :-) 

For others, the spack package is now upstreamed to the main Spack repo and will be maintained and updated there.
