### ISSUE TITLE
Cmake+Kokkos+hdf5+cuda include directory issues

### ISSUE THREAD

**Issue by stevenrbrill** [StanfordLegion/legion#872]
The cmake build process cannot find hdf5.h when Cuda and Kokkos are used.

> In file included from /home/steven/Documents/Research/legion/kokkos/runtime/realm/cuda/cuda_module.h:32:0,
                 from /home/steven/Documents/Research/legion/kokkos/runtime/realm/cuda/cudart_hijack.cc:22:
/home/steven/Documents/Research/legion/kokkos/runtime/realm/mem_impl.h:33:18: fatal error: hdf5.h: No such file or directory
compilation terminated.
runtime/CMakeFiles/realm_cudarthijack.dir/build.make:82: recipe for target 'runtime/CMakeFiles/realm_cudarthijack.dir/realm/cuda/cudart_hijack.cc.o' failed
make[2]: *** [runtime/CMakeFiles/realm_cudarthijack.dir/realm/cuda/cudart_hijack.cc.o] Error 1
CMakeFiles/Makefile2:198: recipe for target 'runtime/CMakeFiles/realm_cudarthijack.dir/all' failed @

**Comment by stevenrbrill** [comment]
> diff --git a/runtime/CMakeLists.txt b/runtime/CMakeLists.txt
index 79f0add..c387446 100644
--- a/runtime/CMakeLists.txt
+++ b/runtime/CMakeLists.txt
@@ -266,6 +266,9 @@ if(Legion_USE_CUDA)
        ${CMAKE_CURRENT_SOURCE_DIR}
        ${PROJECT_BINARY_DIR}/runtime
        ${CUDA_INCLUDE_DIRS})
+      if(Legion_USE_HDF5)
+        target_include_directories(realm_cudarthijack PRIVATE ${HDF5_INCLUDE_DIRS})
+      endif()
       target_link_libraries(RealmRuntime PRIVATE realm_cudarthijack)
       install(TARGETS realm_cudarthijack EXPORT LegionTargets)
     else()
@@ -344,6 +347,9 @@ if(Legion_USE_Kokkos)
   get_property(kokkos_include_dirs
                TARGET Kokkos::kokkoscore
                PROPERTY INTERFACE_INCLUDE_DIRECTORIES)
+  if(Legion_USE_HDF5)
+    list(APPEND kokkos_include_dirs ${HDF5_INCLUDE_DIRS})
+  endif()
   list(TRANSFORM kokkos_include_dirs PREPEND "-I")
   list(APPEND kokkos_compile_options ${kokkos_include_dirs}
                                      "-I${CMAKE_CURRENT_SOURCE_DIR}"

**Comment by streichler** [comment]
This should be fixed with commit 503a8b3.  @stevenrbrill can you confirm your build is happier?

**Comment by stevenrbrill** [comment]
This commit worked for me.
