### ISSUE TITLE
Bug in deferred unlock request with atomic coherence

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#88]
I'm see an assertion failure when I run a task with atomic coherence. One task, one field, no partitions, RW atomic privileges. I can remove the inline mapping performed by the compiler and it still happens. This is the general LLR on the master branch. (The shared LLR does not repro for me.)

$ ./install.py --debug
$ ./regent.py tests/run_pass/privileges_atomic.rg
realm/rsrv_impl.cc:646: void Realm::ReservationImpl::release(): Assertion `count > ZERO_COUNT' failed.

Initial debugging seems to indicate that this is coming from a deferred unlock request which is attempting to release a reservation which was already released. A grep through the reservation log shows:

    [0 - 7f67dad9f700] {2}{reservation}: reservation created: rsrv=40000045
    [0 - 7f67dad9f700] {2}{reservation}: reservation acquire: rsrv=40000045 finish=0/0
    [0 - 7f67dad9f700] {2}{reservation}: reservation release: rsrv=40000045 wait_on=2000000b/4
    [0 - 7f67dad9b700] {2}{reservation}: reservation release: rsrv=40000045

Those two releases appear to be coming from:

    legion_tasks.cc:5162 (SingleTask::launch_task)
    runtime.cc:1348 (PhysicalRegion::Impl::unmap_region via SingleTask::end_task)

I have confirmed that commenting out the body of the block surrounding the release call in `PhysicalRegion::Impl::unmap_region` seems to get rid of the problem, though I'm not going to commit the change myself since I don't know what else that might mess up.

[Here is the patch.](https://github.com/StanfordLegion/legion/files/21371/fix.txt)

And here's a backtrace at the point of the assertion:

    #4  0x00007ffff6947e61 in Realm::ReservationImpl::release (this=0x7fffcc007048) at /home/elliott/legion/runtime/realm/rsrv_impl.cc:646
    #5  0x00007ffff6948aed in Realm::DeferredUnlockRequest::event_triggered (this=0x7fffcc01e230)
        at /home/elliott/legion/runtime/realm/rsrv_impl.cc:72
    #6  0x00007ffff693ca34 in Realm::GenEventImpl::trigger (this=0x3e905a0, gen_triggered=4, trigger_node=0, wait_on=...)
        at /home/elliott/legion/runtime/realm/event_impl.cc:908
    #7  0x00007ffff693c697 in Realm::GenEventImpl::trigger_current (this=0x3e905a0) at /home/elliott/legion/runtime/realm/event_impl.cc:822
    #8  0x00007ffff693fc58 in Realm::DeferredEventTrigger::event_triggered (this=0x7fffcc021d40)
        at /home/elliott/legion/runtime/realm/event_impl.cc:805
    #9  0x00007ffff693ca34 in Realm::GenEventImpl::trigger (this=0x3e90610, gen_triggered=3, trigger_node=0, wait_on=...)
        at /home/elliott/legion/runtime/realm/event_impl.cc:908
    #10 0x00007ffff6938c8b in Realm::Operation::trigger_finish_event (this=0x7fffcc021bd0)
        at /home/elliott/legion/runtime/realm/operation.cc:76
    #11 0x00007ffff6938c12 in Realm::Operation::mark_completed (this=0x7fffcc021bd0) at /home/elliott/legion/runtime/realm/operation.cc:66
    #12 0x00007ffff69727a7 in Realm::Task::mark_completed (this=0x7fffcc021bd0) at /home/elliott/legion/runtime/realm/tasks.cc:70
    #13 0x00007ffff6938b84 in Realm::Operation::mark_finished (this=0x7fffcc021bd0) at /home/elliott/legion/runtime/realm/operation.cc:50
    #14 0x00007ffff69728d5 in Realm::Task::execute_on_processor (this=0x7fffcc021bd0, p=...)
        at /home/elliott/legion/runtime/realm/tasks.cc:112
    #15 0x00007ffff69752e2 in Realm::UserThreadTaskScheduler::execute_task (this=0x3e4d350, task=0x7fffcc021bd0)
        at /home/elliott/legion/runtime/realm/tasks.cc:923

**Comment by streichler** [comment]
Elliott and I determined that the "workingness" of the shared LLR is just because it doesn't detect underflow of the lock count, so assigning this to Mike to dig into the HLR first.

**Comment by lightsighter** [comment]
A fix has been made to the high-level dynamic table implementation for this bug.  I think we can account for the low-level faults as occurring during shutdown and therefore as something that needs to be dealt with as part of a better shutdown methodology.  If we don't see anything in another month, then I think we can close it.

**Comment by lightsighter** [comment]
Actually the fix is a little more complicated than the one you suggested because you have to deal with atomic inline mappings, so you can't just ignore the release on physical regions.  The main thing you have to do is set up a way to distinguish physical regions as inputs to a task from those created by inline mappings.  The change was not to pass in the reservations to the physical regions created as inputs to a task.

I pushed a fix to the master branch.  Assigning the bug back to Elliott to confirm that it is fixed.

**Comment by elliottslaughter** [comment]
Verified and test enabled on master.
