### ISSUE TITLE
Invalid select_task_options() output

### ISSUE THREAD

**Issue by ahenzinger** [StanfordLegion/legion#883]
There's no error message if the output of select_task_options() in the mapper interface is a utility processor (but the runtime crashes).

**Comment by manopapad** [comment]
What happens if you run with `-lg:safe_mapper` ?

**Comment by lightsighter** [comment]
I don't think `-lg:safe_mapper` is checking for the kind of processor right now, but let's confirm that.

**Comment by lightsighter** [comment]
@ahenzinger Have you been able to confirm that `-lg:safe_mapper` isn't checking this property?

**Comment by ahenzinger** [comment]
Sorry for the delay. No, `-lg:safe_mapper` isn't checking this property.

**Comment by lightsighter** [comment]
This issue has been fixed in the master branch with a122dca9c. Mappers can no longer specify a utility processor for any mapper call that will update the target processor for a task.
