### ISSUE TITLE
legion-20.06.0: ctxswitch fails on s390x

### ISSUE THREAD

**Issue by junghans** [StanfordLegion/legion#886]
On s390x:
```
28/44 Test #28: ctxswitch ........................***Failed    9.09 sec
Realm context switching test - 4 children, 10000 iterations, 20s timeout
testing processor 1d00000000000000 (kind=3)
switch: proc 1d00000000000000 (kind=3) finished: elapsed= 0.05s time/switch=  1152ns
sleep: proc 1d00000000000000 (kind=3) finished: elapsed= 2.01s expected= 2.00s
testing processor 1d00000000000001 (kind=4)
switch: proc 1d00000000000001 (kind=4) finished: elapsed= 0.46s time/switch= 11425ns
sleep: proc 1d00000000000001 (kind=4) finished: elapsed= 2.04s expected= 2.00s
testing processor 1d00000000000002 (kind=2)
switch: proc 1d00000000000002 (kind=2) finished: elapsed= 0.04s time/switch=   879ns
sleep: proc 1d00000000000002 (kind=2) finished: elapsed= 3.05s expected= 2.00s
TOO SLOW!
Exiting with errors
```

[Build log](https://github.com/StanfordLegion/legion/files/4870269/build_s390x.log.txt.zip)

`TOO SLOW!` does that mean I can just exclude the test on s390x?

**Comment by streichler** [comment]
Can you start by just re-running the test?  That test just has threads sleep for a while, so it's likely a false negative due to the test machine probably doing other stuff at the same time?

**Comment by junghans** [comment]
This is inside the whole rpm build on Fedora infrastructure, so I have no control over other processes running at the same time.

**Comment by streichler** [comment]
> This is inside the whole rpm build on Fedora infrastructure, so I have no control over other processes running at the same time.

Understood, which is why the occasional false failure is seen on timing-dependent tests.  The question is how occasional it is.  :)

**Comment by junghans** [comment]
Let me rerun it.

**Comment by junghans** [comment]
Seems sporadic.
