### ISSUE TITLE
PSA: Use Moonjit in Regent for PPC64le

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#888]
I was recently made aware of a LuaJIT fork called [Moonjit](https://github.com/moonjit/moonjit) that supports PPC64le. I have successfully used this fork to test Regent on PPC64le, and it passes all tests.

I would like some users with larger Regent codes to test them on PPC64le using this branch. In order to do this, you will need my fork of Terra here: https://github.com/elliottslaughter/terra with branch `moonjit`.

Assuming this works out I intend to make Moonjit the de-facto way to run Regent on PPC64le.

**Comment by manopapad** [comment]
I'll try running soleil with this on Summit and let you know how it goes.

**Comment by manopapad** [comment]
I was able to build and run Soleil on Summit with moonjit. I built Regent as follows:
```
USE_CMAKE=1 USE_CUDA=1 USE_OPENMP=1 USE_GASNET=1 USE_HDF=1 bsub -W 60 -nnodes 1 -P CSC397 -I scripts/setup_env.py --llvm-version 60 --terra-url https://github.com/elliottslaughter/terra --terra-branch moonjit
```

**Comment by elliottslaughter** [comment]
This merged upstream into Terra master.
