### ISSUE TITLE
Problems with reattaching files multiple times

### ISSUE THREAD

**Issue by streichler** [StanfordLegion/legion#89]
Commit 6a031d7 in the attach-file branch changes test/attach_file_mini to try to do an attach/copy/detach sequence (like S3D is trying to do), and do it multiple times.  It works fine the first time, but the second iteration fails with:
```
test/attach_file_mini$ ./attach_file
0x7fcce0021a00, 0x7fcce4ddb380
0x7fcce0022ca0, 0x7fcce4ddb380
[0 - 7fcd06809700] {5}{runtime}: Multiple valid instances for restricted cohernece! This is almost certainly a runtime bug. Please create a minimal test case and report it.
attach_file: ../../runtime/legion/legion_analysis.cc:2195: bool LegionRuntime::HighLevel::MappingTraverser::map_restricted_physical(LegionRuntime::HighLevel::RegionNode*): Assertion `false' failed.
Aborted
```

**Comment by streichler** [comment]
Trying to get @jiazhihao on the "participants" list...

**Comment by lightsighter** [comment]
Did you make a minimal test case?

**Comment by streichler** [comment]
Yes. tests/attach_file_mini in the attach-file branch.

**Comment by lightsighter** [comment]
I pushed a fix for this bug to the master branch.  I also merged the change into the attach-file branch and confirmed that the test case now passes.  Assigning the bug back to Zhihao to confirm that it is fixed and to close the bug.

**Comment by jiazhihao** [comment]
tests/attach_file_mini works with Mike's fix from master branch.
