### ISSUE TITLE
Legion prof -  profile generation for a subset of processors/memories

### ISSUE THREAD

**Issue by seemamirch** [StanfordLegion/legion#891]
Extend legion prof to generate profiles for a subset of processors/memories.

**Comment by elliottslaughter** [comment]
I think given the initial merge of https://github.com/StanfordLegion/legion/issues/926, we'd be better off building mipmaps or summary utilization charts as the next step? I believe the Legion Prof viewer interface is already smart about avoiding loading any processors that you don't expand, and the bottleneck isn't really in the log processing side at this point.

**Comment by elliottslaughter** [comment]
I don't think we really have issues with this anymore. Rust Legion Prof can typically handle this just fine. Memory can be a limiting factor but we can now distribute the work, and in most practical cases I haven't observed that we need this.
