### ISSUE TITLE
Legion: many fields cause memory overflow when mapping

### ISSUE THREAD

**Issue by bandokihiro** [StanfordLegion/legion#900]
In my application, I initially had fields of size `N * sizeof(double)` where `N` is on the order of O(100-1000). You could interpret the overall data to be of size `N1 * N2 * Ne` where `Ne` is the size of the index space and `N1 * N2 = N`. In order to have a layout like `N1 * N2 * Ne` in row-major order, I need to have fields of plain doubles. The first easy change I made it to split the `N` doubles into `N` different fields. This made the mapping much longer and the node to run out of memory on as little as 32 nodes with `N=135` and `Ne=262144`. 

I put some full Legion Spy logs at `/home/bandokihiro/Public/DebugSplitFields` on sapling before and after I made this change on a smaller case with `N=135` and `Ne=4096`. It uses 12 sub-regions/ranks. The difference was 0.4 vs 9 [s] looking at the time stamps in the log file.

**Comment by lightsighter** [comment]
There are no logs that will be useful for this. I need a minimal reproducer that I can build and compile myself.

**Comment by lightsighter** [comment]
Also please report backtraces for all of the errors that you encountered.

**Comment by bandokihiro** [comment]
Please copy the folder `/home/bandokihiro/Debugging/DG_DebugSplitFields` and run `initial_setup.sh` after modifying the location of your control_replication release and debug build of legion (change the first two variables in the script). This should give you a debug and release installation of 2 branches `debug/before-fs-change` and `debug/after-fs-change`. It will ask you for your ID and password when cloning the solver repo. Then the `Runs` folder is setup for you to run the code. The number of sub-regions can be controlled in the `input.toml` file by modifying `npartitions`.  Those branches are setup to exit the code after launching the dummy task that maps my regions.

**Comment by bandokihiro** [comment]
If you already know when you are going to look at this, please tell me regardless of the time of the day. I prefer being able to answer your questions in real time than going back and forth and making this a pain to solve.

**Comment by bandokihiro** [comment]
> Also please report backtraces for all of the errors that you encountered.

I don't have any errors related to this issue. The node just runs out of memory for larger problem sizes than those I prepared here and the job is killed.

**Comment by elliottslaughter** [comment]
Just to be clear, @alexaiken is the person to talk to if this prioritization is preventing you from getting your work done.

**Comment by bandokihiro** [comment]
Closing because my application moved away from using this many fields.
