### ISSUE TITLE
CUDA error leads to misleading error message

### ISSUE THREAD

**Issue by fdouglis** [StanfordLegion/legion#911]
I believe that if there is a CUDA error "no GPU found" the code falls through with the comment that it should still process `-ll:gpu` properly, but if the error is something else, it returns immediately and then reports that `-ll:gpu` isn't a valid option.  Either way, it should report the underlying error without complaining about the option being illegal...

**Comment by streichler** [comment]
This should be fixed with commit 85eaad1e.  If Realm is compiled with CUDA support, `-ll:gpu` will always be a recognized command line option, and if gpus are requested but the CUDA driver cannot be initialized, a hopefully-much-more-comprehensible message will result:
```
log_gpu.fatal() << "gpus requested, but cuInit(0) returned " << ret << " (" << err_name << "): " << err_str;
```
