### ISSUE TITLE
Regent: cycle in toposort

### ISSUE THREAD

**Issue by chaitanyaupp18** [StanfordLegion/legion#912]
I have been getting this error which I have attached below. Please let me know how to solve this issue?

.../local/legion/language/src/rdir/plugin/src/regent/flow.t:815: cycle in toposort at 85
stack traceback:
	[C]: in function 'error'
	.../local/legion/language/src/rdir/plugin/src/regent/flow.t:815: in function 'toposort_node'
	.../local/legion/language/src/rdir/plugin/src/regent/flow.t:820: in function 'toposort_node'
	.../local/legion/language/src/rdir/plugin/src/regent/flow.t:820: in function 'toposort_node'
	.../local/legion/language/src/rdir/plugin/src/regent/flow.t:820: in function 'toposort_node'
	.../local/legion/language/src/rdir/plugin/src/regent/flow.t:820: in function 'toposort_node'
	.../local/legion/language/src/rdir/plugin/src/regent/flow.t:820: in function 'toposort_node'
	.../local/legion/language/src/rdir/plugin/src/regent/flow.t:820: in function 'toposort_node'
	.../local/legion/language/src/rdir/plugin/src/regent/flow.t:820: in function 'toposort_node'
	.../local/legion/language/src/rdir/plugin/src/regent/flow.t:820: in function 'toposort_node'
	...
	.../local/legion/language/src/rdir/plugin/src/regent/flow.t:856: in function 'fn'
	.../local/legion/language/src/rdir/plugin/src/regent/flow.t:344: in function 'traverse_nodes'
	.../local/legion/language/src/rdir/plugin/src/regent/flow.t:854: in function 'toposort'
	...legion/language/src/rdir/plugin/src/regent/flow_to_ast.t:1257: in function 'graph'
	...legion/language/src/rdir/plugin/src/regent/flow_to_ast.t:1047: in function 'node'
	...legion/language/src/rdir/plugin/src/regent/flow_to_ast.t:1260: in function 'graph'
	...legion/language/src/rdir/plugin/src/regent/flow_to_ast.t:1270: in function <...legion/language/src/rdir/plugin/src/regent/flow_to_ast.t:1269>
	/usr/local/legion/language/src/regent/passes_hooks.t:41: in function 'optimize'
	/usr/local/legion/language/src/regent/passes.t:52: in function </usr/local/legion/language/src/regent/passes.t:48>
	main.rg:18: in main chunk

**Comment by rupanshusoi** [comment]
Try running with `-fflow 0`. Looks like an RDIR issue.

**Comment by chaitanyaupp18** [comment]
> Try running with `-fflow 0`. Looks like an RDIR issue.

Thanks. It worked.

**Comment by elliottslaughter** [comment]
@chaitanyaupp18 If you still hit the original issue (when not using that flag), can you share a (hopefully small) program that causes it?

**Comment by elliottslaughter** [comment]
SCR is gone, this is no longer relevant.
