### ISSUE TITLE
Python loses all output on non-zero runtimes when control replication is enabled

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#913]
We currently use this hack to silence output on the non-zero runtimes involved in a control-replicated top-level task:

https://github.com/StanfordLegion/legion/blob/9b1f24282d43277d59145eed58184b39f95efa00/bindings/python/legion_top.py#L325-L328

This is a bit of a heavy hammer. Because `sys.stdout` is global, we also eliminate all output from other tasks that run on runtimes other than runtime zero, even if they are not the main task, and even if they are not control replicated. I've been working with a user who thought their tasks were not running because a task running on a runtime other than zero was not getting output displayed.

I'm not sure we can make the value of sys.stdout thread-local, but that would really be the best option here. Other than that I'm not sure what we can do about this except provide a flag or option to shut it off entirely.

**Comment by lightsighter** [comment]
I'm mostly ambivalent about this issue other than the part where I want to maintain this ability for the top-level task for Legate programs since it certainly relies on this feature. 

@manopapad for visibility too since this could affect Legate Dask sub-tasks, although probably not too much right now since we mostly don't run Legate Dask with control replication at the moment.

**Comment by elliottslaughter** [comment]
We hit this today with ExaFEL, so it's definitely something we see come up in practice. At the moment the team has to work around by commenting out the lines linked in the original post.

**Comment by manopapad** [comment]
Can you have `LegionOutputStream` check on every output whether we're executing in a control replicated context?

**Comment by lightsighter** [comment]
> Can you have LegionOutputStream check on every output whether we're executing in a control replicated context?

I think it would not be terribly hard to do that. It adds a bunch of extra checking to each print statement, but print statements are already very slow, so I don't object to it. If @elliottslaughter  signs off then I can add it.

**Comment by elliottslaughter** [comment]
You could at least cache the check in a thread-local. It's still not great, but at least you only have to go through the C API once per task.

Overall it sounds fine and certainly better than today's situation.

**Comment by lightsighter** [comment]
> You could at least cache the check in a thread-local. It's still not great, but at least you only have to go through the C API once per task.

I'm don't think that is sound. Realm can definitely re-use the same thread for multiple tasks, e.g. task A finishes and then then thread starts running task B, and task A might be replicated but task B is not. So you would need a hook to update the console object at the start of every task, which we don't have.

Printing is so slow that I really don't care how much slower we make it. :)

**Comment by elliottslaughter** [comment]
In Pygion we remove the thread local at the end of the task. I guess if we can't do that here then we could attempt to use some sort a cache key (maybe the task UID?), but I realize we're replacing C API calls with more C API calls, so maybe it's not worth it at this point.

I agree that getting output is better than losing all output, even if it makes slow.

**Comment by lightsighter** [comment]
Fix is running CI: https://gitlab.com/StanfordLegion/legion/-/commit/1618266a689d63f719a0550fe39227a02f923248

**Comment by lightsighter** [comment]
The fix passed CI. Once @elliottslaughter blesses the fix then I think we can close the issue.

**Comment by elliottslaughter** [comment]
Looks good to me. Thanks.
