### ISSUE TITLE
Segfault in HLR when switching between traces

### ISSUE THREAD

**Issue by streichler** [StanfordLegion/legion#92]
Small test case attached.  Interestingly, the failure only occurs if you run the first trace twice (i.e. once
to record and once to play back) before switching to the second.  So the pattern `A B` works, but `A A B` fails.  Weirdly, `A B B A` is fine.

[traces.cc.txt](https://github.com/StanfordLegion/legion/files/22987/traces.cc.txt)

**Comment by lightsighter** [comment]
Fix pushed to master.  I tested the following patterns with no trouble:

A B
A A B
A B B
A B B A
A A B B
A B A B

Assigning back to Sean to confirm that it works for S3D.

**Comment by streichler** [comment]
S3D is still unhappy:
```
s3d.x: /local/home/sean/s3dnew/legion_s3d/legion/runtime/legion/legion_trace.cc:217: void LegionRuntime::HighLevel::LegionTrace::record_dependence(LegionRuntime::HighLevel::Operation*, LegionRuntime::HighLevel::GenerationID, LegionRuntime::HighLevel::Operation*, LegionRuntime::HighLevel::GenerationID): Assertion `operations.back().first == source' failed.
```
I can provide a node/pid for debugging on demand, and I'll fiddle with the little test to see if it can be made to fail again.

**Comment by lightsighter** [comment]
Sent it to me when you get a chance.  You could also start with a backtrace.

**Comment by streichler** [comment]
Sent.  Also, it does seem to be intermittent.  I've had it work 2 times this evening (out of about 10).

**Comment by lightsighter** [comment]
I pushed a fix for this assertion to the master branch.  I still don't understand how it was non-deterministic.  If you see future anomalous behavior it would be good to try and characterize whether it fails in the same way every time or in different ways.
