### ISSUE TITLE
realm assertion issue

### ISSUE THREAD

**Issue by chaitanyaupp18** [StanfordLegion/legion#924]
I am getting the below error when I try to write the output into a hdf5 format.

terra: /usr/local/legion/runtime/realm/transfer/transfer.cc:2835: Realm::Event Realm::IndexSpace<3, long long>::copy(const std::vector<CopySrcDstField> &, const std::vector<CopySrcDstField> &, const std::vector<const typename CopyIndirection<N, T>::Base *> &, const Realm::ProfilingRequestSet &, Realm::Event) const [N = 3, T = long long]: Assertion `srcs.size() == dsts.size()' failed.

**Comment by streichler** [comment]
Which commit are you using for legion?  Is this an explicit copy requested by the application?  If so, can you confirm you've got the same number of fields listed in the src and dst region requirements?

**Comment by chaitanyaupp18** [comment]
> Which commit are you using for legion? Is this an explicit copy requested by the application? If so, can you confirm you've got the same number of fields listed in the src and dst region requirements?

I am using Docker Version of Regent. 
Yes. I am trying to write the partitioned region into .hdf5 file.

**Comment by streichler** [comment]
> I am using Docker Version of Regent.

@elliottslaughter can you help me translate this back to a commit hash?

> Yes. I am trying to write the partitioned region into .hdf5 file.

@chaitanyaupp18 can you paste the code you're using to request the copy?

**Comment by chaitanyaupp18** [comment]
I am using the code in this format. https://github.com/StanfordLegion/legion/blob/stable/language/tests/hdf5/run_pass/attach_hdf5_subregion.rg

**Comment by streichler** [comment]
Does that test run correctly in your build?

**Comment by chaitanyaupp18** [comment]
Yes it does run correctly.

**Comment by streichler** [comment]
Ok, then we need to understand how your code differs from that example.  Are you able to share a pointer to your code?

**Comment by chaitanyaupp18** [comment]
Had some issues with extents provided. It's working now.

**Comment by elliottslaughter** [comment]
@chaitanyaupp18 Is this issue resolved? Can it be closed?

**Comment by streichler** [comment]
@chaitanyaupp18 I'm going to close this issue, but please don't be shy about reopening it if you are still seeing problems.
