### ISSUE TITLE
Non-determinstic behavior with OpenMP task

### ISSUE THREAD

**Issue by bandokihiro** [StanfordLegion/legion#928]
I am experiencing a non-deterministic failure with one of my OpenMP task. At this point I don't know where the bug comes from but as far as I can tell, I wasn't able to reproduce with `-ll:othr 1` and I was able to reproduce with `-ll:othr 2` on one rank with a single sub-region. This task uses a library that heavily relies on eigen. I compiled with `-DEIGEN_DONT_PARALLELIZE` (to disable multi-threading with eigen) but this did not solve the issue.

The failure mode is always a failure when the task is run for the first time. The library fails and produces nans.

The task implementation can be found here: https://github.com/IhmeGroup/DG-Legion/blob/9dd72964527f21ef6eb18038c57f327e16632434/tasks/solution_tasks_omp.cpp#L1036. Everything inside the parallel region should be run on a per-thread basis.

**Comment by streichler** [comment]
@bandokihiro which compiler are you using?  There are actually two different omp runtime implementations (gomp and kmp) behind the scenes, and it would be interesting to know if it only shows up in one of them.

**Comment by bandokihiro** [comment]
that is a good question. actually i tried to use the CMake interface `OpenMP::OpenMP_CXX` using `target_link_libraries`. for static libraries, it adds the flag `-fopenmp` but for my executable, at link time, it tried to link directly to `libgomp` and `libpthreads`. this did not work at runtime (did not seem to use multiple threads) so i am currently forcing `-fopenmp` at link time for my executable. i was able to reproduce the issue on sapling with GNU-8.

**Comment by elliottslaughter** [comment]
Just FYI, I think you would have to switch to Clang if you wanted to try out the KMP interface. GCC only uses GOMP.

**Comment by bandokihiro** [comment]
how can I switch between those two?

**Comment by elliottslaughter** [comment]
You can choose the C++ compiler with `-DCMAKE_CXX_COMPILER=...` (it may require a fresh build).

**Comment by bandokihiro** [comment]
does sapling has clang?

**Comment by elliottslaughter** [comment]
Looks like we've got clang-3.8. I don't know if that is new enough for you. Or you could get binaries from llvm.org.

**Comment by bandokihiro** [comment]
do you build it from source? I am trying the pre-built binaries of LLVM 10.0.0 (Ubuntu 18.04) but then it fails when I try to build something from that

**Comment by elliottslaughter** [comment]
I have an LLVM 10 installation here that you could try using if you want: /scratch2/eslaught/sw/llvm-10/install

However, this does *not* include KMP. You'd have to build that yourself, e.g. instructions here: https://github.com/llvm/llvm-project/tree/master/openmp

**Comment by elliottslaughter** [comment]
Clang may know how to target both GOMP and KMP. You may want to check what your binary was compiled against. `nm` may be able to do this, I'm not 100% sure... You might try `nm exe_file | grep -i gomp` and `nm exe_file | grep -i kmp` and see what you get from each of the commands.

**Comment by bandokihiro** [comment]
although the `nm solver | grep -i gomp` gives `0000000000930f60 B .gomp_critical_user_.reduction.var` and the same with `komp` gives
```
                 U __kmpc_end_reduce_nowait
                 U __kmpc_fork_call
                 U __kmpc_for_static_fini
                 U __kmpc_for_static_init_8
                 U __kmpc_reduce_nowait
```

**Comment by bandokihiro** [comment]
@streichler found the issue. One eigen call was not thread safe (the `blueNorm_impl` function in `StableNorm.h`). Changing `bool initialized` to `std::atomic<bool> initialized` fixed the issue.
