### ISSUE TITLE
Regent: error 298 from privileges of subtask

### ISSUE THREAD

**Issue by LonelyCat124** [StanfordLegion/legion#931]
Hi,
I have some generated tasks (from rexpr) with (for the real code) generated privileges.

For this dummy case, the rexpr in question is created with this function
```
function symmetric_interaction_count_kernel(part1, part2, r2)
local kernel = rquote
  var nonfield = part2.i2
  part1.interactions = part1.interactions + 1
  part2.interactions = part2.interactions + 1
  if(part1.core_part_space.mass > 0.01) then
    part1.i2 = part1.i2 - 1
    part1.i3 = part1.i3 + 2
    part1.i4 = false
    part1.i5 = int1d(83)
    part1.i6 = part1.interactions * 2 + part1.i6
--    nonfield = nonfield + 3
--    part1.i3 = nonfield
  end
end
return kernel
end
```

The code computes the following privileges:
```
reads(part1.{interactions,i2,i3,i4,i5,i6,core_part_space}, part2.{i2,interactions}
writes(part1.{interactions,i2,i3,i4,i5,i6}, part2.{interactions})

```
The tasks are generated are run over some (disjoint) partition of the main region, as an optimised version of:
```
local task run_symmetric_pairwise_task_code( particles: region(ispace(int1d), part), cell_space : partition(disjoint, particles , ispace(int3d)), config : region(ispace(int1d), config_type))
where ... do
  for cell1 in cell_space.colors do
    for cefll2 in cell_space.colors do
      if(cell1 ~= cell2) then
        do_task(cell_space[cell1], cell_space[cell2], config)
      end
    end
  end
end

```
The parent task's privileges for this rexpr case are:
```
where reads(particles.{interactions,i2,i3,i4,i5,i6,core_part_space}, particles.core_part_space, config), writes(particles.{interactions,i2,i3,i4,i5,i6}) do
```

The `do_task` code loops over all of `cell1` and performs the rexpr with "all "of `cell2`. I know for sure that cell1 and cell2 are never the same, so the same region is never passed to `do_task` (which would be illegal).

When I run the code with the computed privileges, it fails and gives this error:
```
[0 - 7f80f8a9a780]    0.036590 {5}{runtime}: [error 298] LEGION ERROR: Parent task run_symmetric_pairwise_task_code (ID 57) of task pairwise_task (ID 61) does not have a region requirement for region (1,1,1) as a parent of child task's region requirement index 2 (from file /home/aidan/Legion/legion/runtime/legion/legion_tasks.cc:1872)
For more information see:
http://legion.stanford.edu/messages/error_code.html#error_code_298
```
I can remove the error in one of two ways, both which allow the code to run correctly:
Change the parent task's privileges to 
```
where reads(particles, config), writes(particles) do
```
Alternatively, I can do `do_task`'s privileges to include
<pre>
writes(part2.{interactions, <b>i2</b>})
</pre>

Now from the rexpr its clear to me that the write to `i2` is not needed, and Regent doesn't believe it should be either for its own checking.

Is there something I'm missing in my understanding of the privileges/region accesses required here? I'll try to create a mini example code in the mean time that reproduces the problem.

**Comment by LonelyCat124** [comment]
I created a mini case (I assume smaller is possible but I wanted to duplicate the syntax as much as possible in case it was needed) showing the problem. It can be fixed by uncommenting the end of line 37 (even though that shouldn't be required, as `parts2.i2`
 is not written to by the task) and attached it here:

[replica.txt](https://github.com/StanfordLegion/legion/files/5196158/replica.txt)

**Comment by elliottslaughter** [comment]
I haven't read the code too deeply, but this is probably an instance of https://github.com/StanfordLegion/legion/issues/289. Please read that issue and see if it makes sense of what you're seeing.

If it doesn't prevent any parallelism, the easy thing to do here is to over-approximate the privileges so they don't get split at the parent task.

**Comment by LonelyCat124** [comment]
Yeah I think it is the same issue - I think if I understand that correctly I can do the following with the generated priveleges (at least it worked for the replica code).

If I have 
```
child_task( parts1, parts2)
where
reads(parts1.[read1]), reads(parts2.[read2]), writes(parts1.[write1]), writes(parts2.[write2]) do
...
end
```

Then I just need to apply all 4 clauses in the parent task too right? Which then shouldn't need over-approximating, just potentially repeated subclauses on the parent, i.e.:
```
task parent(particles, partition_name) where
reads(particles.[read1]), reads(particles.[read2]), writes(particles.[write1]), writes(particles.[write2]) then
...
end
```

At least my understanding is the parent task needs to have greater or equal privileges to the child task anyway - does that make sense for the context of #289?

**Comment by elliottslaughter** [comment]
If the parent task is `inner` then it probably isn't an issue for it to require more privileges than strictly necessary. Legion will permit it to execute before the data is ready (because of `inner`) and, assuming you have virtual instances, will need to perform an analysis of the child tasks regardless.

I think your new case still looks like #289 to me. Fundamentally it's about getting to a point where the child privileges overlap the parent in some way where a field is read-write in the parent but read-only in the child in such a way that the grouping of one isn't a subset of the other.

Let me know if you're still having issues with this.

**Comment by LonelyCat124** [comment]
I'll have a look into `inner` tasks at some point, for now I'd worked around this by changing the parent tasks into `rquote` and embedding them in the main task, but not clear if this may present scalability issues in the future.

**Comment by elliottslaughter** [comment]
If your parent tasks are issuing index launches across the whole machine, then this is actually the recommended way to do it. Generally speaking `inner` tasks are a programming convenience but not necessarily better for performance.

**Comment by LonelyCat124** [comment]
I'm not sure they will be index launches entirely, probably i should do an index launch and the conditional launch in separate loops which I'll bear in mind.

**Comment by elliottslaughter** [comment]
@LonelyCat124 is this still an issue for you? I think part of this was a duplicate, so if the practical consequences are resolved, I'm inclined to close this.

**Comment by LonelyCat124** [comment]
No longer an issue- I just don't use `inner` tasks and generate rquotes instead.
