### ISSUE TITLE
Regent: Metaprogrammed privileges failing with subfields.

### ISSUE THREAD

**Issue by LonelyCat124** [StanfordLegion/legion#932]
I think this is distinct enough from #931 to be a separate issue.

I've enhanced my code (to fix some bugs) that generates the privileges such that for write privileges it generates full field names when subfields are inbuilt, i.e. for
```
fspace temp1{
  hello : int
}

fspace temp2{
  temp1_space : temp1,
  value : int
}
```
it can generate `temp1_space.hello`. However, if there are multiple fields in a write (I've not tested with only a single), it seems to be failing in the `type_check` code in regent. For this case it tells me:
```
src/neighbour_search/cell_pair_v2/neighbour_search.rg:361: no field 'cutoff_update_space.redo' in region $parts1
   reads(parts1.[read1]), reads(config),  writes(parts1.[write1]) do
```

(For this kernel, write1 is `{cutoff_update_space.redo,cutoff_update_space.left,cutoff_update_space.right,cutoff_update_space.h_0}`)

If I change the code to manually use
```
writes(parts1.{cutoff_update_space.redo, cutoff_update_space.left, cutoff_update_space.right, cutoff_update_space.h_0}) do
```
instead, then the code is fine (failing for other kernel's with different requirements).

The code also works if I modify the generator code to instead ignore sub-fields and simply return `cutoff_update_space` (overestimating the privileges). For now I can leave it like this, but since this could limit parallelism in some generated tasks.

Am I doing anything wrong with how I'm using `parts1.[write1]`?
I could try looping through `read1` and `write1` and generating the expanded privileges, i.e.
```
reads(parts1.cutoff_update_space), 
reads(parts1.h),
writes(parts1.cutoff_update_space.h_0),
writes(parts1.cutoff_update_space.redo),
...
```
but I'm not sure how this affects the code performance (I wouldn't expect it should but I don't know), nor if I'm allowed to specialize quotes at that point in the declaration.

**Comment by elliottslaughter** [comment]
Hi @LonelyCat124,

If it's possible to get a short reproducer on this, I'd appreciate it.

As far as performance goes, it won't matter. Regent automatically sorts and groups fields to achieve maximum performance. This also means you can't mess it up even if you want to. :-) It should be mostly invisible to you unless you're doing interop with C, or unless of course you're hitting issues like in #931.

Hope that helps.

**Comment by LonelyCat124** [comment]
Hi,

I have attached a sort-of-short reproducer for this. The important code is about 50 lines, but the privilege computation code is ~100 beforehand. From line 103 onwards is the stuff that is breaking I believe.  In particular line 133 fails with this error:
```
/home/aidan/Legion/legion/language/src/regent/type_check.t:113: Errors reported during typechecking.
test2.rg:135: no field 'thing.field1' in region $parts1
  where reads(parts1.[read]), writes(parts1.[write]) do
                                            ^

stack traceback:
        [C]: in function 'error'
        /home/aidan/Legion/legion/language/terra/src/terralib.lua:390: in function 'finishandabortiferrors'
        /home/aidan/Legion/legion/language/src/common/report.t:56: in function 'error'
        /home/aidan/Legion/legion/language/src/regent/type_check.t:113: in function 'region_field'
        /home/aidan/Legion/legion/language/src/regent/type_check.t:129: in function 'region_fields'
        /home/aidan/Legion/legion/language/src/regent/type_check.t:149: in function 'fn'
        /home/aidan/Legion/legion/language/terra/src/terralist.lua:150: in function 'regions'
        /home/aidan/Legion/legion/language/src/regent/type_check.t:216: in function 'privilege'
        /home/aidan/Legion/legion/language/src/regent/type_check.t:225: in function 'privileges'
        /home/aidan/Legion/legion/language/src/regent/type_check.t:4612: in function </home/aidan/Legion/legion/language/src/regent/type_check.t:4590>
        /home/aidan/Legion/legion/language/src/regent/passes.t:69: in function </home/aidan/Legion/legion/language/src/regent/passes.t:57>
        test2.rg:133: in function 'generate_symmetric_task'
        test2.rg:145: in main chunk
```

The code works if line 134 is uncommented instead of 135, and the writes privilege in that line is the output from the print statement in line 131.

[932_reproducer.txt](https://github.com/StanfordLegion/legion/files/5224279/932_reproducer.txt)

**Comment by LonelyCat124** [comment]
This bug might not be specific to privileges - while working on a model for my code's IO attemping to access subfields seems to cause the same error of the field not existing for the type. This code fails to allow access to `s2.space.test1` through metaprogramming, though accessing the field directly is fine. Futhermore from other testing if I detect a prefix string (so for this when constructing `mapping_fields` if I check `v.sub(v, 1, string.len("space."))==space)` and then adapt the code to look in `thing[i].space.[field.field_name]` as appropriate the code works fine.

```
import "regent"
format = require("std/format")
fspace s1{
  test1 : float
}
fspace s2{
  space : s1,
  test2 : float
}
mapping = {}
mapping[1] = "test2"
mapping[2] = "space.test1"

function test_rquote(mapping)
  local mapping_fields = terralib.newlist()
  for k,v in pairs(mapping) do
    mapping_fields:insert({field_name=v})
  end
  local task test_task(thing : region(ispace(int1d), s2)) where reads(thing) do
    for i in thing.ispace do
      [mapping_fields:map(function(field)
        return rquote
          format.println("{}", thing[i].[field.field_name])
        end
      end)]
    end

  end
  return test_task
end

local test_task = test_rquote(mapping)

task main()
  var is = ispace(int1d, 2)
  var thing = region(is, s2)
  fill(s2.test2, 1.0)
  fill(s2.space.test1, 2.0)
  test_task(thing)
end

regentlib.start(main)
```

Error message:
```
DLHRT0063% /home/aidan/Legion/legion/language/regent.py test4.rg
/home/aidan/Legion/legion/language/src/regent/type_check.t:601: Errors reported during typechecking.
test4.rg:23: no field 'space.test1' in type s2()
          format.println("{}", thing[i].[field.field_name])
                                    ^

stack traceback:
        [C]: in function 'error'
        /home/aidan/Legion/legion/language/terra/src/terralib.lua:390: in function 'finishandabortiferrors'
        /home/aidan/Legion/legion/language/src/common/report.t:56: in function 'error'
        /home/aidan/Legion/legion/language/src/regent/type_check.t:601: in function 'fn'
        /home/aidan/Legion/legion/language/terra/src/terralist.lua:150: in function 'map'
        /home/aidan/Legion/legion/language/src/regent/type_check.t:890: in function 'expr'
        /home/aidan/Legion/legion/language/src/regent/type_check.t:4318: in function 'fn'
        /home/aidan/Legion/legion/language/terra/src/terralist.lua:150: in function 'map'
        /home/aidan/Legion/legion/language/src/regent/type_check.t:3930: in function 'block'
        /home/aidan/Legion/legion/language/src/regent/type_check.t:4091: in function 'fn'
        /home/aidan/Legion/legion/language/terra/src/terralist.lua:150: in function 'map'
        /home/aidan/Legion/legion/language/src/regent/type_check.t:3930: in function 'block'
        /home/aidan/Legion/legion/language/src/regent/type_check.t:4657: in function </home/aidan/Legion/legion/language/src/regent/type_check.t:4590>
        /home/aidan/Legion/legion/language/src/regent/passes.t:69: in function </home/aidan/Legion/legion/language/src/regent/passes.t:57>
        test4.rg:19: in function 'test_rquote'
        test4.rg:32: in main chunk
```

**Comment by elliottslaughter** [comment]
Oh, you can't access a field literally with a string `x.["a.b"]`, you have to do `x.["a"].["b"]`. We may have a shorter syntax for this with field paths, but I don't actually remember if that's exposed to the user right now.

**Comment by LonelyCat124** [comment]
Ah ok - is the cause for the priveleges as well? I'll just have to restrict user's from using more than one depth of field spaces if field paths aren't exposed at the moment. Getting one sub field space is doable but an unknown number sounds rough.

**Comment by elliottslaughter** [comment]
I just pushed support for field paths in field access. See: https://gitlab.com/StanfordLegion/legion/-/blob/master/language/tests/regent/run_pass/fspace_field_path.rg

The support should already be there for privileges, see: https://gitlab.com/StanfordLegion/legion/-/blob/master/language/tests/regent/run_pass/quote_task_privilege_field_path.rg

**Comment by LonelyCat124** [comment]
Looks good, I'll give that a go - as far as I can work out it would work for any number of arguments right (I tested 3 and that worked fine and if I found the declaration correctly it looks independent from the number of arguments)

**Comment by elliottslaughter** [comment]
Yes, you should be able to use this for field paths of arbitrary length.
