### ISSUE TITLE
Legion spy: broken options on control_replication?

### ISSUE THREAD

**Issue by bandokihiro** [StanfordLegion/legion#935]
The `-i` option of `legion_spy.py` fails with the following error on control_replication:
```
  File "/home/bandokihiro/Softwares/legion_mod/tools/legion_spy.py", line 13161, in <module>
    main(temp_dir)
  File "/home/bandokihiro/Softwares/legion_mod/tools/legion_spy.py", line 13144, in main
    state.print_instance_descriptions()
  File "/home/bandokihiro/Softwares/legion_mod/tools/legion_spy.py", line 12608, in print_instance_descriptions
    print('  '+str(inst.region))
AttributeError: 'Instance' object has no attribute 'region'
```
The `-x` option does not work on one of my multiple-node run. 

These can be reproduced using the logfiles at `/home/bandokihiro/Public/DebugLegionSpy` on sapling.

**Comment by elliottslaughter** [comment]
The issue with `-i` should be fixed now.

When you talk about `-x`, do you just mean that the output is empty?

**Comment by bandokihiro** [comment]
yes

**Comment by elliottslaughter** [comment]
Just to confirm, were these logs gathered with `-lg:spy` or `-DLEGION_SPY`?

**Comment by bandokihiro** [comment]
with `-lg:spy`

**Comment by lightsighter** [comment]
Pull and try again with `-x`

**Comment by bandokihiro** [comment]
Fixed. Thanks.
