### ISSUE TITLE
Realm: Serialization in P2P transfers

### ISSUE THREAD

**Issue by magnatelee** [StanfordLegion/legion#936]
Realm is currently using a single CUDA stream for all P2P transfers from a given source even when the targets are different, which is causing serialization of otherwise concurrent transfers. We should be able to fix this by using a different stream for each pair of GPUs.

**Comment by lightsighter** [comment]
@lightsighter for visibility.

**Comment by streichler** [comment]
Commit `cf1e8177` (in master) creates a separate CUDA stream for each unique source/dest GPU pair (or at least the ones that are p2p-capable), which should eliminate serialization at the Realm level.
