### ISSUE TITLE
Regent: Link error on PowerPC when using LLVM 9

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#939]
On Summit, after building with:

```
module load gcc cuda cmake
CC=gcc CXX=g++ USE_CMAKE=1 scripts/setup_env.py --llvm-version 90 --terra-url https://github.com/elliottslaughter/terra.git --terra-branch fix-power -j 16
```

(Note: the branch is needed for a Moonjit workaround, hopefully will not be necessary for too much longer.)

`./regent.py examples/saveobj.rg` generates an error, but `./regent.py examples/circuit_sparse.rg` runs fine.

Error looks like:

```
/usr/bin/ld: /tmp/terra-76e630.o: In function `$__regent_task_10001_primary':
terra:(.text+0x319c): call to `legion_task_preamble' lacks nop, can't restore toc; recompile with -fPIC
/usr/bin/ld: terra:(.text+0x319c): unresolvable R_PPC64_REL24 against `legion_task_preamble'
/usr/bin/ld: terra:(.text+0x31ac): call to `malloc@@GLIBC_2.17' lacks nop, can't restore toc; recompile with -fPIC
/usr/bin/ld: terra:(.text+0x31ac): unresolvable R_PPC64_REL24 against `malloc@@GLIBC_2.17'
/usr/bin/ld: terra:(.text+0x31b4): call to `legion_predicate_true' lacks nop, can't restore toc; recompile with -fPIC
/usr/bin/ld: terra:(.text+0x31b4): unresolvable R_PPC64_REL24 against `legion_predicate_true'
```

**Comment by streichler** [comment]
A bit of searching online suggests this might be a code size issue.  See: https://go-review.googlesource.com/c/sys/+/146518/

**Comment by mariodirenzo** [comment]
I am experiencing the same problem on Marconi100 (https://www.hpc.cineca.it/hardware/marconi100) with my solver

**Comment by elliottslaughter** [comment]
Hm, which code size do you think may be the issue? Looks like `libregent.so` is only 31 MB and `terra` is only 123 MB.
 The `terra` executable is smaller with LLVM 6 but only 101 MB.

Also Regent is being compiled by GCC not Clang so I don't think there should be any difference between LLVM 6 and 9.

**Comment by streichler** [comment]
Given that moonjit is the new variable here, I'd bet it's the code that's being generated by it.  The "REL24" in the unhappy relocation makes me suspect the limit is on the order of 16MB (2^24 bytes).

**Comment by elliottslaughter** [comment]
I'm not sure how Moonjit could be responsible since this is an error that happens when we save an executable but not when we JIT directly; I would have expected this to go the other direction. As far as I know, in the executable case there should be no Moonjit code in the binary at all and all compiling and linking should be done by LLVM.

**Comment by mariodirenzo** [comment]
> Given that moonjit is the new variable here, I'd bet it's the code that's being generated by it. The "REL24" in the unhappy relocation makes me suspect the limit is on the order of 16MB (2^24 bytes).

In my case, everything works fine with moonjit and LLVM 6. The error shows up only with LLVM 9

**Comment by streichler** [comment]
More searching:
https://stackoverflow.com/questions/7378376/relocation-value-does-not-fit-in-24-bits
It looks like `-mlongcall` might help - does Terra create a command line for its LLVM context creation or is there
some other way to set that flag?

I haven't found anything suggesting it can be set on a per function basis, but that may be because it's a per-call-site thing.

**Comment by elliottslaughter** [comment]
I am no longer able to reproduce this on Summit with LLVM 13, Legion `master` and Terra `luajit2.1`. Closing.

**Comment by elliottslaughter** [comment]
For posterity, my modules:

```
$ module list

Currently Loaded Modules:
  1) lsf-tools/2.0                4) xalt/1.2.1   7) spectrum-mpi/10.4.0.3-20210112  10) cuda/11.0.3
  2) hsi/5.0.2.p5                 5) DefApps      8) nsight-compute/2021.2.1         11) cmake/3.21.3
  3) darshan-runtime/3.3.0-lite   6) gcc/9.1.0    9) nsight-systems/2021.3.1.54
```

Environment:

```
$ cat env.sh
module load gcc cuda cmake

export CC=gcc
export CXX=g++
```

Setup command:

```
./scripts/setup_env.py --llvm-version 130 -j16
```
