### ISSUE TITLE
Legion: API call to retrieve parent_task info from remote node

### ISSUE THREAD

**Issue by manopapad** [StanfordLegion/legion#940]
Currently inside a mapper the `parent_task` pointer on operations being processed will be `NULL` if the operation was launched on a remote node. It would be nice if there was a method to lazily retrieve the parent task information from the remote node.

**Comment by lightsighter** [comment]
This has been added to the `master` and `control_replication` branches. There is a `get_parent_task` method on the base `Mappable` class. I also added a `has_parent_task` method on the `Task` class. The `parent_task` member variable is still there but it's marked `mutable` now which reflects that its value might initially be `NULL` but could change with calls to `get_parent_task`. Going forward, calling `get_parent_task` will be the preferred way to get the parent `Task*`.
