### ISSUE TITLE
Notes from packaging v20.09.0 for fedora

### ISSUE THREAD

**Issue by junghans** [StanfordLegion/legion#941]
- python scripts use still use unversioned python interpreter - `python2` is dead, so you should just use `python3` everywhere, RHEL8 doesn't even have `/usr/bin/python` anymore by default
- `/usr/bin/` (`CMAKE_INSTALL_BINDIR`) seems an odd place for the `serializer_examples` to be installed
- hwloc2 support still broken (see #575)
- `scatter` test fails on i686 [build log](https://github.com/StanfordLegion/legion/files/5300123/build_i686.txt)
- `proc_group` test fails on ppc64le [build log](https://github.com/StanfordLegion/legion/files/5300189/build_ppc64le.txt)

from https://koji.fedoraproject.org/koji/taskinfo?taskID=52461103

**Comment by streichler** [comment]
> RHEL8 doesn't even have /usr/bin/python anymore by default

There's a package that could be listed as a dependency of the Legion package that would install it though?

> scatter test fails on i686 build log
> proc_group test fails on ppc64le build log

Can you try rerunning these to see if they're repeatable?  The `proc_group` test failure looks like a false negative we get sometimes on heavily loaded systems, and the `scatter` test doesn't seem to have any useful diagnostic info at all?

**Comment by junghans** [comment]
> > RHEL8 doesn't even have /usr/bin/python anymore by default
> 
> There's a package that could be listed as a dependency of the Legion package that would install it though?
I guess you could hack it, but the packaging guide is very clear "Packages in Fedora MUST NOT use /usr/bin/python." (see https://docs.fedoraproject.org/en-US/packaging-guidelines/Python/#_multiple_python_runtimes). Do you have a good reason to keep it unversioned?
> 
> > scatter test fails on i686 build log
> > proc_group test fails on ppc64le build log
> 
> Can you try rerunning these to see if they're repeatable? The `proc_group` test failure looks like a false negative we get sometimes on heavily loaded systems, and the `scatter` test doesn't seem to have any useful diagnostic info at all?

Here you go: https://koji.fedoraproject.org/koji/taskinfo?taskID=52464615

**Comment by elliottslaughter** [comment]
> Do you have a good reason to keep it unversioned?

Do all our supported systems have a `python3`? If not we're going to have exactly the same issue, just for a different system and in a different direction.

**Comment by junghans** [comment]
> > Do you have a good reason to keep it unversioned?
> 
> Do all our supported systems have a `python3`? If not we're going to have exactly the same issue, just for a different system and in a different direction.

I patched it for this release, so there is no hurry. However, python2 was sunsetted 1/1/2020, so I am assuming more systems should have python3 by now.

**Comment by junghans** [comment]
> > > scatter test fails on i686 build log
> > > proc_group test fails on ppc64le build log
> > 
> > 
> > Can you try rerunning these to see if they're repeatable? The `proc_group` test failure looks like a false negative we get sometimes on heavily loaded systems, and the `scatter` test doesn't seem to have any useful diagnostic info at all?
> 
> Here you go: https://koji.fedoraproject.org/koji/taskinfo?taskID=52464615

Seems to pass this time.

**Comment by elliottslaughter** [comment]
It's not so much whether the installed Python is 2 or 3, it's whether the installed Python (even if it always 3) will be placed at `/usr/bin/python3` or `/usr/bin/python`. I'm aware of some systems that have made `/usr/bin/python` point to version 3, but I'm not sure whether that's the only installed path or if it's really a symlink to `/usr/bin/python3`.

Again, it might be fine, but if we're going to change, let's verify first.

**Comment by streichler** [comment]
Hijacking this issue to start a more meta-discussion.  @junghans what are your opinions of the relative merits of standard-linux-distribution-packages vs a spack-based approach to things?  The latter seems to me to be much more compatible with a very configurable-at-build-time system like Legion, and I wonder if it's simpler to stop providing pre-built packages and just point people at spack?

**Comment by junghans** [comment]
I originally packaged legion (and gasnet), so we could use these packages in the CI for Flesci, but we switched to Spack a while ago as well. So I am not sure if anybody is still using Legion in Fedora.

The problem with spack is that it will build the whole stack, which can lead to many not Legion related build issues.
Plus Spack won't give you the same coverage of architectures and build flags as Fedora's build process.

**Comment by streichler** [comment]
I agree that Fedora's testing of a variety of architectures is nice, but I don't think it's worth the liability of folks thinking there's an "official" configuration of Legion for Fedora.  @junghans , can we discontinue the Fedora package unless/until we decide on what that official configuration should be?

**Comment by junghans** [comment]
Done.
