### ISSUE TITLE
Local, equivalent but distinct collective instances

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#944]
Libraries, such as for FFTs, sometimes use a "plan" object to store local data. In the case of FFTW, for example, this is an opaque object which stores instructions about how to execute an FFT, based on the input (and output) size, alignment, stride, aliasing (in-place or out-of-place), etc. FFTW does not provide a way to serialize the plan and thus we're stuck with plans being inherently local objects that cannot move between machines. (And even if FFTW did add this capability, we'd be stuck playing the same game with cuFFT, and then AMD, Intel, etc. for every vendor we want to support.)

@streichler pointed out to me that we could potentially store plans in a collective region instance. Every copy gets initialized independently. The main issue with this approach is that while instances are equivalent (in the sense that you can grab whatever instance is local to the node where your task runs), but not identical. E.g. in a resilient execution, you'd better not attempt to restore such an instance from another node, because that would fail.

Still, it seems like an appealing idea. The other alternative would be some sort of magic global variable lookup with potentially complicated caching, which is very non-Legion-ish and brings its own bucket of complexity.

Thoughts? Is this is plausible path forward?

See also https://github.com/StanfordLegion/legion/issues/832#issuecomment-704603223 for discussion of FFT specific issues.

**Comment by lightsighter** [comment]
If they're not going to be equivalent across nodes (e.g. in the resilience sense), then it seems like collective instances are not the right answer. Why not have a region with an index space contain N rows (one for each node) that you partition so that each node gets a subregion with one entry that they are then free to mutate as they so desire?

**Comment by lightsighter** [comment]
Note also that if the plan object is write-once, read-ever-after then you can also use futures to store them. If you're doing index space launches you can store those futures in a future map and launch very efficiently, especially with control replication.

**Comment by elliottslaughter** [comment]
I think using a single, partitioned instance (for initialization) and then passing the whole thing to every node is a plausible path. For now I'll plan on using this approach.
