### ISSUE TITLE
Preprocessor directives in regent 

### ISSUE THREAD

**Issue by chaitanyaupp18** [StanfordLegion/legion#953]
Is there anyway we can use preprocessor directives in regent?

In C we use something like "#ifdef macro_name", can we do something like this in regent?

**Comment by elliottslaughter** [comment]
The top level of a Regent program is Lua. You can do something like:

```
if macro_name then
  task asdf() ... end
else
  task asdf() ... end
end
```

Or even:

```
function make_asdf_task(some_param, some_other_param)
  local task asdf() ... end
  return asdf
end
local asdf1 = make_asdf_task(a, b)
local asdf2 = make_asdf_task(c, d)
```

You can see the section "Metaprogramming" in the Regent reference for more details. http://regent-lang.org/reference/

**Comment by chaitanyaupp18** [comment]
Okay sir. Thank you.
