### ISSUE TITLE
Default mapper neglects memory constraints

### ISSUE THREAD

**Issue by mariodirenzo** [StanfordLegion/legion#954]
I think that the current version of the default mapper (or at least the one in `control_replication`) neglects the MemoryConstraints when it creates new instances.
I came up with the following workaround which seems to work in my case but I am not sure about potential side effects (feedback would be very appreciated):
```
diff --git a/runtime/mappers/default_mapper.cc b/runtime/mappers/default_mapper.cc
index 7ef3192..f041a0c 100644
--- a/runtime/mappers/default_mapper.cc
+++ b/runtime/mappers/default_mapper.cc
@@ -2095,7 +2095,12 @@ namespace Legion {
                 FieldConstraint(overlapping_fields,
                   index_constraints.field_constraint.contiguous,
                   index_constraints.field_constraint.inorder));
-            if (!default_make_instance(ctx, target_memory, creation_constraints,
+            Memory my_target_memory = target_memory;
+            if (creation_constraints.memory_constraint.is_valid())
+               // Change the target memory according to the constraint
+               my_target_memory = Utilities::MachineQueryInterface::find_memory_kind(machine, target_proc,
+                           creation_constraints.memory_constraint.get_kind());
+            if (!default_make_instance(ctx, my_target_memory, creation_constraints,
                          instances.back(), TASK_MAPPING, force_new_instances,
                          true/*meets*/, req, footprint))
               return false;
```

**Comment by lightsighter** [comment]
Can you provide a backtrace for how we're getting into the `DefaultMapper::create_custom_instances` call? If the `kind` of `target_memory` does not align with the memory constraint then something else has already gone wrong.

**Comment by mariodirenzo** [comment]
I'm getting into `DefaultMapper::create_custom_instances` from `DefaultMapper::map_task` https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/mappers/default_mapper.cc#L1580 . I believe that the main issue is that `DefaultMapper::default_policy_select_target_memory`, called at https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/mappers/default_mapper.cc#L1574, does not take the memory constraint as an argument and therefore always selects the memory with the best affinity to the target processor.
However, it was much easier for me to hack `DefaultMapper::create_custom_instances` which already filters the Layout constraints for each region requirement.

**Comment by lightsighter** [comment]
Yes, I agree that is an issue with the default mapper. The memory constraint needs to be a part of the mappers decision making when selecting a valid instance. What do you think @elliottslaughter @manopapad ?

**Comment by manopapad** [comment]
It looks like `default_policy_select_target_memory` indeed doesn't consider memory constraints from the variant's `TaskLayoutConstraintSet` when selecting a target memory. Then later `default_policy_select_constraints` overrides any memory constraints coming from the variant https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/mappers/default_mapper.cc#L2179. I'll take a crack at fixing this.

**Comment by manopapad** [comment]
https://gitlab.com/StanfordLegion/legion/-/merge_requests/297 fixes this bug, @mariodirenzo could you merge this commit into your legion branch and see if the default mapper works out of the box for you?

**Comment by mariodirenzo** [comment]
Works for me. Thank you very much

**Comment by mariodirenzo** [comment]
I think that this is not quite fixed.
I've got a reproducer on sapling at `/home/mariodr/htr/unitTests/poissonTest`. It needs to run on a GPU of a compute node by using the script `run.sh` in the folder (after sourcing my .bashrc). It will produce the error 
```
[0 - 7f085febb840]   40.765700 {5}{runtime}: [error 67] LEGION ERROR: Invalid mapper output. Mapper Default Mapper on Processor 1d00000000000003 selected variant 70 for task initFFTplans (ID 5376). But instance selected for region requirement 1 fails to satisfy the corresponding Memory layout constraint. (from file /home/mariodr/legion/runtime/legion/legion_tasks.cc:1676)
```

If I apply the patch reported earlier in this issue, the program executes fine.

**Comment by manopapad** [comment]
Can you use the [LoggingWrapper](https://github.com/StanfordLegion/legion/blob/stable/runtime/mappers/logging_wrapper.h) to get some logging output from your mapper? Where you would do `new MyMapper(...)` instead do `new LoggingWrapper(new MyMapper(...))`, and run the final executable with `-level mapper=2`.

**Comment by mariodirenzo** [comment]
The reproducer mentioned in the earlier comment does not have a custom mapper. It just uses the default mapper.
Do you want me to modify the reproducer or to instrument the default mapper?

PS: If I write a custom mapper based on the default mapper and I overwrite `default_policy_select_target_memory`, everything works fine.

**Comment by manopapad** [comment]
Please create a minimal custom mapper that just forwards everything to the default mapper, and add a LoggingWrapper to where that custom mapper is instantiated. I would like to see the output of `-level mapper=2` for a failing execution, and also please add the following logging code to your mapper (I haven't tried to compile this snippet, it likely has syntax errors):
 
```
void MyMapper::map_task(const MapperContext ctx,
                        const Task& task,
                        const MapTaskInput& input,
                        MapTaskOutput& output) {
  DefaultMapper::map_task(ctx, task, input, output);
  if (std::string(task.get_task_name()) == std::string("initFFTplans")) {
    std::cout << "initFFTplans memory constraints:" << std::endl;
    for (unsigned i = 0; i < task.regions.size(); ++i) {
      MemoryConstraint mc = find_memory_constraint(ctx, task, output.chosen_variant, i);
      if (!mc.is_valid()) {
        std::cout << "(none)" << std::endl;
      } else {
        std::cout << mc.get_kind() << std::endl;
      }
    }
  }
}
```

**Comment by mariodirenzo** [comment]
The output of the logging code is 
```
initFFTplans memory constraints:
(none)
4
```
and you can find the log of the failing execution at `/home/mariodr/htr/unitTests/poissonTest/mapper.log` on sapling

**Comment by manopapad** [comment]
It looks like you are asking that the 2nd region requirement of `initFFTplans` be placed on zero-copy memory, is this correct? I can't find anything related to this in the directory of the reproducer.

**Comment by mariodirenzo** [comment]
Tha is correct.
You cannot find the registration in that folder because the function that registers that task is defined in `/home/mariodr/htr/src/Poisson/Poisson.cc`

**Comment by manopapad** [comment]
I think I found what's wrong, and have uploaded a fix to https://gitlab.com/StanfordLegion/legion/-/tree/bug/954b. Could you please try your reproducer on this branch (using the vanilla default mapper)?

**Comment by mariodirenzo** [comment]
Yes, that works for me. Thanks
