### ISSUE TITLE
Regent: fmin= and fmax= operators

### ISSUE THREAD

**Issue by syamajala** [StanfordLegion/legion#957]
Having fmin= and fmax= operators for tasks that return nan would be useful.

**Comment by elliottslaughter** [comment]
Would it be ok to modify the existing semantics? Is there a reason why we want both?

**Comment by syamajala** [comment]
It would be fine with me. Would it be possible to do this sooner rather than later?

**Comment by elliottslaughter** [comment]
Should be fixed by 7c9849007f29a9dcdd73b7133d2124d4dd16b6cb.

To be clear, the new semantics match `fmax` and `fmin`, i.e., `NaN` values are **NOT** propogated.

**Comment by elliottslaughter** [comment]
It looks like we have a similar semantic issue in Legion. @lightsighter do you have any issue with unifying the semantics here? (So that both Legion's and Regent's semantics are like `fmax`.)

**Comment by lightsighter** [comment]
Do you need to change anything other than the what is in `legion_redop.inl`? If not, then go ahead and make a pull request and I'll review it.

**Comment by syamajala** [comment]
I think this is good for now.
