### ISSUE TITLE
Legion: Assertion failure on region-init > fill > destroy in replicated toplevel task

### ISSUE THREAD

**Issue by manopapad** [StanfordLegion/legion#963]
The attached program [bug963.tar.gz](https://github.com/StanfordLegion/legion/files/5491696/bug963.tar.gz) when run on 2 nodes crashes with:

```
bug963: /home/manolis/legion/runtime//legion/legion_analysis.cc:2498: void Legion::Internal::LogicalState::check_init(): Assertion `curr_epoch_users.empty()' failed.
```

**Comment by lightsighter** [comment]
Should be fixed, both when you add the field and with the original test. Pull and try again.

**Comment by manopapad** [comment]
I get the same assertion failure on the original testcase (fill with no fields), and I don't see the "Ignoring fill request with no fields" warning.

**Comment by lightsighter** [comment]
Pull and try again.

**Comment by manopapad** [comment]
Fixed
