### ISSUE TITLE
Pygion: Installation issues

### ISSUE THREAD

**Issue by LonelyCat124** [StanfordLegion/legion#966]
I was hoping to try a few simple things out with Pygion, but am having difficulties installing with the current master.

My route to attempt is:
Build Legion:
```
mkdir build
cmake .. -DLegion_BUILD_BINDINGS=ON -DLegion_USE_Python=ON
make -j 2
sudo make install
cd $LG_RT_DIR
```
Install Pygion:
```
cd bindings/python
pip3 install .
```

Test
```
python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygion
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aidan/Legion/legion/bindings/python/pygion.py", line 75, in <module>
    assert _max_dim is not None, 'Unable to detect LEGION_MAX_DIM'
AssertionError: Unable to detect LEGION_MAX_DIM
```

If I do 
```
python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import legion_top
>>> from legion_cffi import ffi, lib as c
>>> c.legion_domain_get_rect_1d()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aidan/.local/lib/python3.6/site-packages/cffi/api.py", line 912, in __getattr__
    make_accessor(name)
  File "/home/aidan/.local/lib/python3.6/site-packages/cffi/api.py", line 908, in make_accessor
    accessors[name](name)
  File "/home/aidan/.local/lib/python3.6/site-packages/cffi/api.py", line 838, in accessor_function
    value = backendlib.load_function(BType, name)
AttributeError: function/symbol 'legion_domain_get_rect_1d' not found in library '<None>': python3: undefined symbol: legion_domain_get_rect_1d
```

which looks like I've not installed the legion library correctly.

I also thought that this might not be the correct way to run pygion, so I tried:
```
DLHRT0063% /home/aidan/Legion/legion/build/bin/python_bindings test_image.py -ll:py 1
[0 - 7f5db5450c80]    0.000000 {4}{threads}: can't open /sys/devices/system/node
[0 - 7f5db5450c80]    0.000298 {4}{threads}: reservation ('Python-1 proc 1d00000000000002') cannot be satisfied
[0 - 7f5d8cc627c0]    0.095635 {6}{python}: unable to import Python module python_bindings
Traceback (most recent call last):
  File "/usr/local/share/Legion/python/tests/python_bindings.py", line 20, in <module>
    import pygion
ImportError: No module named pygion
python_bindings: /home/aidan/Legion/legion/runtime/realm/python/python_module.cc:266: void Realm::PythonInterpreter::import_module(const string&): Assertion `0' failed.
zsh: abort (core dumped)  /home/aidan/Legion/legion/build/bin/python_bindings test_image.py -ll:py 1
```

This looks like legion using python2 instead of python3 (which I thought I had specified with `ccmake`), but I then reinstall pygion for python2, and tried:
```
DLHRT0063% /home/aidan/Legion/legion/build/bin/python_bindings test_image.py -ll:py 1
[0 - 7fb030620c80]    0.000000 {4}{threads}: can't open /sys/devices/system/node
[0 - 7fb030620c80]    0.000894 {4}{threads}: reservation ('Python-1 proc 1d00000000000002') cannot be satisfied
[0 - 7fb003de27c0]    0.628518 {6}{python}: unable to import Python module python_bindings
Traceback (most recent call last):
  File "/usr/local/share/Legion/python/tests/python_bindings.py", line 20, in <module>
    import pygion
  File "/home/aidan/.local/lib/python2.7/site-packages/pygion.py", line 75, in <module>
    assert _max_dim is not None, 'Unable to detect LEGION_MAX_DIM'
AssertionError: Unable to detect LEGION_MAX_DIM
python_bindings: /home/aidan/Legion/legion/runtime/realm/python/python_module.cc:266: void Realm::PythonInterpreter::import_module(const string&): Assertion `0' failed.
zsh: abort (core dumped)  /home/aidan/Legion/legion/build/bin/python_bindings test_image.py -ll:py 1
```

I'm happy to use the system default (python2) for now to test things - but have I missed a step to install pygion (or are there instructions somewhere?)

Edit: I tried to look at the links in the paper but they seem to have dissapeared also.
Edit 2: From what I understand the Cmake should build and install it - but make test also fails:
```
      Start  1: legion_python
 1/24 Test  #1: legion_python ....................***Exception: Child aborted  0.61 sec
      Start  2: attach_file_mini
 2/24 Test  #2: attach_file_mini .................***Exception: Child aborted  0.09 sec
```

**Comment by streichler** [comment]
We'll need the experts (@elliottslaughter @lightsighter ) to chime in, but it's possible that this is related to changes I put in a few days ago to prefer python3 over python2.  Can you try backing up to commit 48544ae34c and see if it works there?  (Ideally try both with letting the build choose whatever it wants and then also try with trying to ask for python3 explicitly.)

**Comment by elliottslaughter** [comment]
> `pip3 install .`

That's not right. We should already be doing the Python installation from inside of CMake, there is no step 2.

If you're not finding the installation it probably means that you're not passing the correct Python installation to CMake, which would mean that even if you did get the module import to work it still wouldn't do what you want.

Also, Pygion is not tested with being used from a `python` frontend (whether 2 or 3), you have to do everything with `legion_python`.

**Comment by elliottslaughter** [comment]
We use FindPython to locate the Python installation so if you need to know how to configure it see the docs: https://cmake.org/cmake/help/v3.12/module/FindPython.html

**Comment by LonelyCat124** [comment]
I'll try installing on another machine tomorrow in a clean env - should it work with virtual environments if I don't have root, provided FindPython uses the correctiong installation?

**Comment by LonelyCat124** [comment]
Ok, so I moved to the production HPC machine (for a clean environment) over my own laptop, and am still having issues.

Setup:
```
module load python3
python3 -m venv pygion_test
source pygion_test/bin/activate
git clone ....legion...
module load gcc9
cd legion
mkdir build
cd build
ccmake ..
```

In ccmake I set
```
Legion_BUILD_BINDINGS ON
Legion_BUILD_TESTS ON
Legion_ENABLE_TESTING ON
Legion_REDOP_COMPLEX ON
CMAKE_INSTALL_PREFIX /lustre/path/to/my/home/.INSTALL/legion
PYTHON_EXECUTABLE /lustre/path/to/home/pygion_test/bin/python3
PYTHON_INCLUDE_DIR  /lustre/scafellpike/local/apps/python3/3.6.2/include/python3.6m
PYTHON_LIBRARY /lustre/scafellpike/local/apps/python3/3.6.2/lib/libpython3.6m.so
```
The value for PYTHON_INCLUDE_DIR and PYTHON_LIBRARY were taken from 
```
python -c "import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('LIBDIR'))
python -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())"
```
as FindPython wanted to use the system default for those (Python2) even with my venv.

I then ran make & make install, and created a `pygion` module, which sets bin/lib/lib64/include & pythonpath appropriately for the install directory.

Running `make test` at this point results in every test succeeding except for `legion_python` and `python_bindings`.

I created a simple script to try to run with the bindings:
```
import pygion
from pygion import index_launch, task, Domain, ID, IndexLaunch, R, Region, Partition

@task(privileges=[W])
def init(R):
    for i in range(len(R.x)):
        R.x[i] = i

@task
def main():
    R = Region([10], {'x': pygion.float64})
    pygion.fill(R, 'x', 0)
    init(R)
#    graph(R)


if __name__ == '__main__':
    main()
```

This doesn't seem to work as `pygion` isn't known to whichever python the python bindings seems to be using:
```
(pygion_test) -bash-4.2$ ./python_bindings pygion_test.py -ll:py 1
[0 - 7f455882e7c0]    0.000774 {4}{threads}: reservation ('Python-1 proc 1d00000000000002') cannot be satisfied
[0 - 7f452bffe7c0]    0.191527 {6}{python}: unable to import Python module python_bindings
Traceback (most recent call last):
  File "/lustre/scafellpike/local/HT03020/lxm18/axc67-lxm18/.INSTALL/legion/share/Legion/python/tests/python_bindings.py", line 20, in <module>
    import pygion
ModuleNotFoundError: No module named 'pygion'
python_bindings: /lustre/scafellpike/local/HT03020/lxm18/axc67-lxm18/legion/runtime/realm/python/python_module.cc:266: void Realm::PythonInterpreter::import_module(const string&): Assertion `0' failed.
Aborted
```

However, the current python knows `pygion` exists as expected (though as Elliott pointed out that doesn't work as expected)
```
(pygion_test) -bash-4.2$ python
Python 3.6.2 (default, Aug 30 2017, 13:52:10)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygion
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lustre/scafellpike/local/HT03020/lxm18/axc67-lxm18/.INSTALL/legion/lib/python3.6/site-packages/pygion.py", line 75, in <module>
    assert _max_dim is not None, 'Unable to detect LEGION_MAX_DIM'
AssertionError: Unable to detect LEGION_MAX_DIM
```

I also tried with `legion_python` (as I'm not sure what the difference is between bindings and legion_python) which gave a different error:
```
(pygion_test) -bash-4.2$ ./legion_python pygion_test.py -ll:py 1
[0 - 7f129a7627c0]    0.000829 {4}{threads}: reservation ('Python-1 proc 1d00000000000002') cannot be satisfied
[0 - 7f12720bf7c0]    1.028468 {6}{python}: python exception occurred within task:
Traceback (most recent call last):
  File "/lustre/scafellpike/local/HT03020/lxm18/axc67-lxm18/.INSTALL/legion/lib/python3.6/site-packages/legion_top.py", line 287, in legion_python_main
    c.legion_task_preamble(
  File "/lustre/scafellpike/local/HT03020/lxm18/axc67-lxm18/pygion_test/lib/python3.6/site-packages/cffi/api.py", line 912, in __getattr__
    make_accessor(name)
  File "/lustre/scafellpike/local/HT03020/lxm18/axc67-lxm18/pygion_test/lib/python3.6/site-packages/cffi/api.py", line 908, in make_accessor
    accessors[name](name)
  File "/lustre/scafellpike/local/HT03020/lxm18/axc67-lxm18/pygion_test/lib/python3.6/site-packages/cffi/api.py", line 838, in accessor_function
    value = backendlib.load_function(BType, name)
AttributeError: function/symbol 'legion_task_preamble' not found in library '<None>': ./legion_python: undefined symbol: legion_task_preamble
legion_python: /lustre/scafellpike/local/HT03020/lxm18/axc67-lxm18/legion/runtime/realm/python/python_module.cc:977: virtual void Realm::LocalPythonProcessor::execute_task(Realm::Processor::TaskFuncID, const Realm::ByteArrayRef&): Assertion `0' failed.
Aborted
```

Have I missed a parameter/env variable to control the python used inside Legion?

**Comment by elliottslaughter** [comment]
Ok, a couple things.

1. I think `python_bindings` is just a test. I'm actually confused why that's being installed. Use `legion_python` instead.
2. If I remember correctly, you need to add `-DBUILD_SHARED_LIBS=ON`. Otherwise the binary will get statically linked and I'm not sure we have the necessary magic to make sure all the symbols still get exported.
3. The `ffi.dlopen(None)` just means it expects the Legion symbols to be available in the current address space, either via the executed binary or via some dependency that gets pulled in. So I think (2) should fix this.

**Comment by LonelyCat124** [comment]
Ok step 2 worked, however I had to disable `-DLegion_BUILD_TESTS=OFF` as `taskreg` failed with this error:
```
[ 95%] Linking CXX executable ../../bin/taskreg
/usr/bin/ld: CMakeFiles/taskreg.dir/taskreg.cc.o: undefined reference to symbol 'dlsym@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```
I tested a couple of different machines (different OS/compiler etc.) and had this error on both - I also tried then disabling `-D Legion_USE_LIBDL=OFF` but then libregent failed to compile. Not critical from my pov but happy to test any suggestions to fix it.

**Comment by LonelyCat124** [comment]
While not totally related - can I ask a quick question here about calling python tasks from Regent?
I have a simple task in python:
```
@task(task_id = 123, privileges=[RW])
def graph(R):
    R.x[1] = R.x[1] + 1.0
```

which I define from Regent:
```
fspace thing{
  x : double
}

extern task graph(R: region(ispace(int1d), thing)) where reads(R) end
graph:set_task_id(123)

task main()
  var x = ispace(int1d, 10)
  var r = region(ispace(int1d, 10), thing)
  for i in r.ispace do
    r[i].x =  double(i)
  end
  graph(r)
end
```

When I run this with `regent test_pygion.rg -ll:cpu 4 -ll:py 1 -ll:pyimport test_pygion` I get a python exception:
```
Traceback (most recent call last):
  File "/lustre/scafellpike/local/HT03020/lxm18/axc67-lxm18/.INSTALL/legion/lib/python3.6/site-packages/pygion.py", line 1714, in __call__
    return self.execute_task(*args, **kwargs)
  File "/lustre/scafellpike/local/HT03020/lxm18/axc67-lxm18/.INSTALL/legion/lib/python3.6/site-packages/pygion.py", line 1745, in execute_task
    args = pickle.loads(ffi.unpack(arg_ptr, arg_size))
_pickle.UnpicklingError: invalid load key, '\x00'.
```

Am I messing something up with my declaration in Regent or do I need to do something more in Python to tell it about the field space etc.? The only example of python interop I could find just used a task with no arguments.

**Comment by elliottslaughter** [comment]
Right, for now we've implemented the ability to call from Python to Regent but not the other way around. Going the other direction only works in a very limited set of circumstances; and probably a task with no arguments is the only case I can guarantee that works right now.

**Comment by elliottslaughter** [comment]
@LonelyCat124 are you still interested in this, and if so are you still hitting the issues above?

**Comment by LonelyCat124** [comment]
I'm not actively working on this stuff at the moment. Its something I might potentially use in the future (e.g. in-situ visualisation or similar) but probably safe to close this issue for now.

**Comment by elliottslaughter** [comment]
Closing for now, let's reopen if you start to look at this again.
