### ISSUE TITLE
Can't directly assign between FieldAccessors with array syntax

### ISSUE THREAD

**Issue by dzhang314** [StanfordLegion/legion#974]
Consider this task which copies a field from one region to another. (In my case, `T = double` and `DIM = 1`.)
```c++
template <typename T, int DIM>
void copy_task(const Legion::Task *task,
               const std::vector<Legion::PhysicalRegion> &regions,
               Legion::Context ctx, Legion::Runtime *runtime) {
    const auto &dst_region = regions[0];
    const auto &src_region = regions[1];
    FieldAccessor<LEGION_WRITE_DISCARD, T, DIM> dst_writer{dst_region, FID_DST};
    FieldAccessor<LEGION_READ_ONLY, T, DIM> src_reader{src_region, FID_SRC};
    for (PointInDomainIterator<DIM> it{dst_region}; it(); ++it) {
        dst_writer[*it] = +src_reader[*it]; // BREAKS IF + REMOVED
    }
}
```
Notice the unary + operator in the line `dst_writer[*it] = +src_reader[*it];` -- if I remove the +, it fails to compile with the following error:
```
/usr/local/include/legion/legion.inl:400:26: error: 'Realm::AccessorRefHelper<double> Legion::ArraySyntax::AccessorRefHelper<double, LEGION_READ_PRIV>::helper' is protected within this context
  400 |           { helper = rhs.helper; return *this; }
      |                      ~~~~^~~~~~
/usr/local/include/legion/legion.inl:417:38: note: declared protected here
  417 |         Realm::AccessorRefHelper<FT> helper;
      |                                      ^~~~~~
```

**Comment by dzhang314** [comment]
@streichler said in Slack:
> @lightsighter I think we need a friend declaration here so that the P != P2 case is legal?
> https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/legion/legion.inl#L399-401
> but actually, doesn't doing an assignment of the helper mean the value isn't actually read from one and written to the other? nvm - it's just falling through an an assignment of the realm helpers (edited)

**Comment by lightsighter** [comment]
https://gitlab.com/StanfordLegion/legion/-/commit/c605731384c6ec85f2dee22d13e7b506110406f6

**Comment by lightsighter** [comment]
This should be fixed now. Assigning @dzhang314 to confirm and close.

**Comment by dzhang314** [comment]
@lightsighter Looks good to me. Thanks for the quick fix!
