### ISSUE TITLE
Incorrect assignment instead of comparison in an assert in Python module code

### ISSUE THREAD

**Issue by marcinz** [StanfordLegion/legion#975]
An assignment is used instead of a comparison in [this assert](https://github.com/StanfordLegion/legion/blob/e07e9ebc612839ff4f5b33385a7e05113c5c3e90/runtime/realm/python/python_module.cc#L746). I tried to change it to comparison as I think was intended, but then the assert fails for me.

**Comment by streichler** [comment]
@marcinz I've got a proposed change here: https://gitlab.com/StanfordLegion/legion/-/commits/pyfix
Can you give it a try at some point at confirm that it doesn't cause any weird behavior?  This isn't super-urgent,
as I don't want to merge it into master until after we do the 2020.12 release.

**Comment by streichler** [comment]
Fixed with commit 5191273.
