### ISSUE TITLE
Included file causing runtime error

### ISSUE THREAD

**Issue by cmelone** [StanfordLegion/legion#977]
Hello,

I am using the latest version of the `control_replication` branch for [HTR Solver](https://github.com/stanfordhpccenter/htr-solver), but our latest CI build indicates an issue with how the macros in `runtime/mathtypes` were updated.

```
/home/hpcc/cmelone/insieme/builds/885127806/legion/language/regent.py process_schema.rg config_schema.lua -fflow 0 -finner 1 -fcuda 1 -fcuda-offline 1 -fopenmp 1
Solver version HTR-1.2.3 committed on 2020-11-25
Legion version legion-20.09.0-2313-g011b000 committed on 2020-12-01
In file included from /home/hpcc/cmelone/insieme/builds/885127806/legion/runtime/legion/legion_redop.h:25:0,
                 from /home/hpcc/cmelone/insieme/builds/885127806/legion/runtime/legion.h:55,
                 from prometeo_variables.h:33,
                 from prometeo_registrar.h:34,
                 from prometeo_registrar.cc:30:
/home/hpcc/cmelone/insieme/builds/885127806/legion/runtime/mathtypes/complex.h:34:10: fatal error: thrust/complex.h: No such file or directory
 #include <thrust/complex.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```

As far as I'm aware `thrust/complex.h` can't be compiled with GCC. Is this a non-issue/are we expected to compile programs with nvcc going forward?

Thanks

**Comment by lightsighter** [comment]
You're actually wrong: thrust can be compiled by gcc. The problem here is that you don't have thrust installed in a normal location. Which version of CUDA are you using and where is it installed? Which commit of which branch are you on? Are you using the make or the cmake build system?

**Comment by lightsighter** [comment]
This works just fine for me:

```
echo "#include <thrust/complex.h>" | g++ -x c++ -I /usr/local/cuda/include -c -o out.o -
```

**Comment by cmelone** [comment]
I'm currently on commit `011b0008` of `control_replication`. I'm using CUDA version 10.2.89 and using the make build system. I went back and checked our logs, the build worked last on commit `9fecb52f` of `control_replication`, just a day or two ago. The environment hasn't changed (CUDA is available and I checked that  `/usr/local/cuda-10.2/include/thrust/complex.h` is available on the machine) and we are running the same exact commands, so I'm not really sure why it would error out.

**Comment by lightsighter** [comment]
Are you passing `-I /usr/local/cuda-10.2/include` to your dynamic invocation of gcc in your Regent application? Are you even using complex support?

**Comment by elliottslaughter** [comment]
Where is the code that invokes `gcc`? I might have some comments on how that's being done.

**Comment by lightsighter** [comment]
Just based on the command line and the error message it looks like it's coming from inside the Regent application itself.

**Comment by mariodirenzo** [comment]
The issue is generated by a missing include path in the HTR's Makefile that is required in the new version of `control_replication` (probably on `master` as well). I've fixed the problem in the development branch of HTR, so it will build without problems.

> Where is the code that invokes gcc? I might have some comments on how that's being done.

`gcc` is invoked directly from the Makefile with a command line that looks like https://github.com/stanfordhpccenter/HTR-solver/blob/master/src/Makefile#L185-L187 .

> Just based on the command line and the error message it looks like it's coming from inside the Regent application itself.

You are seeing the error below a regent command line because I guess that @cmelone is compiling the solver in parallel and the command line for `prometeo_registrar.cc` is printed just a few line above what was pasted in this issue.

I think that the issue can be closed, if @cmelone confirms that the solver builds on his system.

**Comment by lightsighter** [comment]
@mariodirenzo Does HTR even need complex number support? Complex number support is opt-in in Legion, but opt-out in Regent.

@elliottslaughter How can regent users disable complex number support?

**Comment by mariodirenzo** [comment]
> @mariodirenzo Does HTR even need complex number support? Complex number support is opt-in in Legion, but opt-out in Regent.

Currently it does not but It will need it soon

**Comment by elliottslaughter** [comment]
I think if you're willing to include Legion's `runtime.mk` in that Makefile, you should be able to get the flags automatically. Then you don't need to know or hard-code all the paths yourself. (On the other hand, I don't know what all the interactions would be, so you do need to be a bit careful as well to make sure you don't mess up your configuration in the process.)

Regent complex support is currently mandatory.

**Comment by cmelone** [comment]
Can confirm that compile succeeds with the solver's latest build. Thank you @lightsighter @elliottslaughter
