### ISSUE TITLE
LegionProf: missing tasks with -s

### ISSUE THREAD

**Issue by bandokihiro** [StanfordLegion/legion#979]
On `control_replication`, doing 
```
legion_prof.py -s /home/bandokihiro/Public/DebugLegionProf/prof_0.gz
```
misses one of my task `iface_residual_task`. For example, reverting back to commit f96e7d2562db0abbeda05f60237e2bf1456004c5 fixed it.

Feel free to use this file on sapling to reproduce.

**Comment by bandokihiro** [comment]
I am using the legion prof summary to measure the performance of my tasks and one task of interest is missing because of this bug. Is there an ETA on a fix?

**Comment by seemamirch** [comment]
I'll look at it today

**Comment by seemamirch** [comment]
pushed a fix in master https://gitlab.com/StanfordLegion/legion/-/commit/343ba085b05e54012df54e6fa4887fa57f92d5ef

**Comment by bandokihiro** [comment]
fixed, thanks
