### ISSUE TITLE
regent: not building on macOS catalina

### ISSUE THREAD

**Issue by fnrizzi** [StanfordLegion/legion#980]
Hello! 
I tried to execute these commands which are on the official website:
```
brew install llvm@3.9
# Consider placing these lines into your .bashrc for future use.
export CLANG="$(brew --prefix)/opt/llvm@3.9/bin/clang"
export LLVM_CONFIG="$(brew --prefix)/opt/llvm@3.9/bin/llvm-config"
export CXX="$(brew --prefix)/opt/llvm@3.9/bin/clang++"
git clone -b master https://github.com/StanfordLegion/legion.git
cd legion/language
./install.py --debug
```
However, the script is looking for `LLVM_DIR` not `LLVM_CONFIG`, so I fixed that. 
But then I get this error: 
```
[  0%] Built target LLVMObjectFiles
[  2%] Generating moonjit/lib/libluajit-5.1.a, moonjit/lib/libluajit-5.1.dylib, moonjit/bin/moonjit-2.3.0-dev, moonjit/include/moonjit-2.3/lua.h, moonjit/include/moonjit-2.3/lualib.h, moonjit/include/moonjit-2.3/lauxlib.h, moonjit/include/moonjit-2.3/luaconf.h
==== Building moonjit 2.3.0-dev ====
HOSTCC    host/minilua.o
HOSTCC    host/buildvm_asm.o
HOSTCC    host/buildvm_peobj.o
HOSTCC    host/buildvm_lib.o
HOSTCC    host/buildvm_fold.o
CC        lj_gc.o
CC        lj_char.o
CC        lj_obj.o
CC        lj_buf.o
CC        lj_str.o
CC        lj_tab.o
CC        lj_func.o
CC        lj_udata.o
CC        lj_meta.o
CC        lj_debug.o
CC        lj_state.o
host/minilua.c:34:10: fatal error: 'math.h' file not found
#include <math.h>
         ^~~~~~~~
In file included from In file included from host/buildvm_lib.chost/buildvm_peobj.c::69:
:
host/buildvm.hhost/buildvm.h::99::1010::  fatal errorfatal error: : 'sys/types.h' file not 'sys/types.h'found file
 not found
#include <sys/types.h>
         ^~~~~~~~~~~~~
In file included from host/buildvm_asm.c:6:
host/buildvm.h:9:10: fatal error: 'sys/types.h' file not found
#include <sys/types.h>
         ^~~~~~~~~~~~~
#include <sys/types.h>
         ^~~~~~~~~~~~~
In file included from host/buildvm_fold.c:6:
host/buildvm.h:9:10: fatal error: 'sys/types.h' file not found
#include <sys/types.h>
         ^~~~~~~~~~~~~
....
``` 
any suggestions please? 
Thanks

**Comment by streichler** [comment]
I'm sure @elliottslaughter has the recipe for this memorized, but I think you need to make sure that you've asked xcode to install the header files (this is no longer the default) and then (since I think you're using cmake here), set the `SDKROOT` environment variable as described here:
https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_SYSROOT.html

**Comment by fnrizzi** [comment]
@streichler thanks Sean :) 
- Regarding the header files, I noticed that it was highlighted in bold in the guidelines but not sure how to do with brew. 
Maybe adding a specific command to do it would be helpful, jsut a thought from a user perspective :) 
- cmake: not explicitly right? does install.py use cmake underneath?

**Comment by elliottslaughter** [comment]
I need to go update the official instructions, but in the mean time, the issue you're hitting is https://github.com/terralang/terra/issues/365 and if you follow the instructions in the [comment here](https://github.com/terralang/terra/issues/365#issuecomment-618512629) then you should be able to get it working. That should be all doable via environment variables (I think).

**Comment by elliottslaughter** [comment]
Ok, for the record, I got the build to work by downloading the LLVM binaries at:

https://github.com/llvm/llvm-project/releases/download/llvmorg-9.0.1/clang+llvm-9.0.1-x86_64-apple-darwin.tar.xz

I set up my environment like:

```
export CMAKE_PREFIX_PATH="$CMAKE_PREFIX_PATH:$PLACE_WHERE_YOU_DOWNLOADED/clang+llvm-9.0.1-x86_64-apple-darwin"
export INCLUDE_PATH="$(xcrun --sdk macosx --show-sdk-path)/usr/include"
```

And then I built with:

```
CXXFLAGS=-std=c++11 ./install.py --debug --no-cmake
```

Right now it looks like that's the best route since Homebrew refuses to build `llvm@9` without a full XCode installation, which I do not want to force users to install.

And then I can run examples with e.g.:

```
CXXFLAGS=-std=c++11 ./regent.py examples/circuit_sparse.rg
```

**Comment by fnrizzi** [comment]
thanks for reply! 
I am not sure I understand where is cmake involved. Is it called by the `./install.py`?

**Comment by elliottslaughter** [comment]
There are two separate projects being built, Terra and Legion. The flags `--cmake` / `--no-cmake` affect Legion, Terra is built with CMake regardless.

But actually, I realized that CMake is not the issue, it's only that C++11 is now mandatory. So the following works as well:

```
CXXFLAGS=-std=c++11 ./install.py --debug
```

**Comment by fnrizzi** [comment]
@elliottslaughter 
I just tried to follow these:
```
curl -O https://github.com/llvm/llvm-project/releases/download/llvmorg-9.0.1/clang+llvm-9.0.1-x86_64-apple-darwin.tar.xz
tar xfJ clang+llvm-9.0.1-x86_64-apple-darwin.tar.xz
export CMAKE_PREFIX_PATH="$CMAKE_PREFIX_PATH:$PWD/clang+llvm-9.0.1-x86_64-apple-darwin"
export INCLUDE_PATH="$(xcrun --sdk macosx --show-sdk-path)/usr/include"
git clone -b master https://github.com/StanfordLegion/legion.git
cd legion/language
CXXFLAGS=-std=c++11 ./install.py --debug
```
but it still does not work for me. It seems it gets farther than before, but still get this error [regent_error.txt](https://github.com/StanfordLegion/legion/files/5672360/regent_error.txt)

**Comment by elliottslaughter** [comment]
What's your CMake version on your workstation? I thought I'd set the minimum version correctly, but maybe something slipped past me.

I don't think you need to set CC/CXX; this is not a compiler issue.

As for your mac issue, I'm a bit confused. I guess I should verify what macOS version you're on, and whether you have XCode or Command Line Tools, since those are the only things I can think of that would matter.

**Comment by fnrizzi** [comment]
thanks for the reply!
(1) re CC/CXX: basically, you are saying that I should NOT set those before doing anything either on linux or mac? 
Those env vars don't matter for regent and terra builds? 

(2) workstation: I have cmake-3.16.3 

(3) mac: catalina, 10.15.6. I do have Xcode and CLT.
```
➤ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.2)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by fnrizzi** [comment]
@elliottslaughter do you have any updates on the items above? thanks

**Comment by elliottslaughter** [comment]
Trying to page this back into memory...

1. I think I was saying that the error `string sub-command REGEX ...` wasn't related to the setting of `CC` / `CXX`. Of course those variables determine what compilers the build use. But this is happening at CMake configure time.

2. That should be new enough so I don't know why you'd hit this. (Unless `REGEX` changed in a backwards incompatible way in recent versions.)

3. I see that you're setting your `CC` to `/Users/fnrizzi/Desktop/work/regent/clang+llvm-9.0.1-x86_64-apple-darwin/bin/clang`. I think that won't work, because Apple changed how things work in recent macOS versions and Clang probably hasn't caught up yet. (I think even the most recent Clang doesn't automatically find the right headers.) This is a really obnoxious situation, but I think the solution is to use the CLT or XCode compilers if you can.

**Comment by elliottslaughter** [comment]
Following up on this.

1. I was looking at a similar issue recently and it was associated with a failure to correctly download the LuaJIT tarball. You might try double checking if you're hitting that or not. (You'd see an empty or corrupt tarball in your `build` directory.) By any chance are you behind any sort of a proxy, or unusual network situation?
2. See above.
3. Terra now observes `SDKROOT`, like Clang does. I think if you set that environment variable (`SDKROOT="$(xcrun --sdk macosx --show-sdk-path)"`) then this will probably go away. I believe what I wrote about the setting of `CC` is also no longer necessary, as it seems to have been fixed either by the `SDKROOT` or by some unrelated fix in either XCode or CLT. You could probably even go back to non-vendor Clang if you wanted to.

@fnrizzi Please let us know if you're able to make progress on this.

**Comment by elliottslaughter** [comment]
@fnrizzi Pinging again to see if this is still impacting you. Thanks.

**Comment by fnrizzi** [comment]
@elliottslaughter sorry! I actually thought I replied... :) 
I got swamped with some things and did not have time to look at it yet! But I am planning to do so by next week.

**Comment by fnrizzi** [comment]
@elliottslaughter hi! 
I am trying again on my mac following directions: https://regent-lang.org/install/#running
here is the error I get 
[err2.txt](https://github.com/StanfordLegion/legion/files/6391620/err2.txt)

where is the build dir where I can check if Lua is corrupted?

**Comment by elliottslaughter** [comment]
I think you need:

```
export SDKROOT="$(xcrun --sdk macosx --show-sdk-path)"
```

Does that fix it?

**Comment by fnrizzi** [comment]
It built! I used the debug flag `--debug`.
But it does not run... I tried this: 
```
./regent.py examples/daxpy.rg
```
And I get this: 
```
[0 - 110973dc0]    0.000000 {4}{bgwork}: rdtsc calibration failed: per_64k_nsec=158686 freq=2.42136 count=116 - timeouts will be based on a 2GHz clock
[0 - 110973dc0]    0.000235 {4}{threads}: reservation ('dedicated worker (generic) #1') cannot be satisfied
Running Daxpy...
Done!
[0 - 70000297e000]    0.037690 {4}{runtime}: [warning 1071] LEGION WARNING: Region requirement 1 of operation daxpy (UID 11) in parent task main (UID 1) is using uninitialized data for field(s) 103 of logical region (3,1,1) (from file /Users/fnrizzi/Desktop/work/regent/legion/runtime/legion/legion_ops.cc:645)
For more information see:
http://legion.stanford.edu/messages/warning_code.html#warning_code_1071

[0 - 70000297e000]    0.038283 {4}{runtime}: [warning 1071] LEGION WARNING: Region requirement 1 of operation daxpy (UID 12) in parent task main (UID 1) is using uninitialized data for field(s) 103 of logical region (4,1,1) (from file /Users/fnrizzi/Desktop/work/regent/legion/runtime/legion/legion_ops.cc:645)
For more information see:
http://legion.stanford.edu/messages/warning_code.html#warning_code_1071

[0 - 70000297e000]    0.038737 {4}{runtime}: [warning 1071] LEGION WARNING: Region requirement 1 of operation daxpy (UID 13) in parent task main (UID 1) is using uninitialized data for field(s) 103 of logical region (5,1,1) (from file /Users/fnrizzi/Desktop/work/regent/legion/runtime/legion/legion_ops.cc:645)
For more information see:
http://legion.stanford.edu/messages/warning_code.html#warning_code_1071

[0 - 70000297e000]    0.039223 {4}{runtime}: [warning 1071] LEGION WARNING: Region requirement 1 of operation daxpy (UID 14) in parent task main (UID 1) is using uninitialized data for field(s) 103 of logical region (6,1,1) (from file /Users/fnrizzi/Desktop/work/regent/legion/runtime/legion/legion_ops.cc:645)
For more information see:
http://legion.stanford.edu/messages/warning_code.html#warning_code_1071
```

**Comment by lightsighter** [comment]
This is actually normal for macOS, which prevents certain system calls from running from user space that are allowed in Linux. It's unfortunate, but Apple restricts us from doing things which are good for performance, but could have security implications if used improperly.

**Comment by elliottslaughter** [comment]
I don't actually see any errors here. There are warnings, like Mike mentioned. But if you check `echo $?` after running, I'm guessing you'll find it exited cleanly.

**Comment by fnrizzi** [comment]
thanks guys! Yes, I was a bit thrown off by the `rdtsc calibration failed`. 
I will try on linux next.

**Comment by streichler** [comment]
We've seen a few other macos systems that complain about the rdtsc calibration as well.  It can have a minor impact on performance for latency-sensitive workloads, so for this and other reasons (e.g. cpu core pinning) definitely use linux for
performance-critical cases if possible.

**Comment by elliottslaughter** [comment]
@fnrizzi are there any remaining problems associated with this issue? I've actually been using Regent quite successfully on macOS in the last few months.

**Comment by fnrizzi** [comment]
@elliottslaughter no other problems so far! thanks!
