### ISSUE TITLE
mapping decision may affect serdez id?

### ISSUE THREAD

**Issue by jiazhihao** [StanfordLegion/legion#99]
I am trying to run graph rendering on 2 nodes by using a custom serdez. You can find the source code of the application at test/rendering in serdez branch. The application's field space only includes a single field, which contains a non-zero serdez_id. So, I am assuming all domain::copy should use the non-zero serdez_id.

However, by using default mapper or the custom mapper, I always saw Domain::Copy(..) was given a srcdstfield with serdez_id = 0, which causes plain data copy.

The magic thing happens by a single line of change: in select_task_options function, if I set task->map_locally = true, then Domain::Copy(...) interface could receive correct serdez_id, but the runtime receives a sigfault. I am pretty sure the sigfault happened somewhere else rather that DMA threads.

I did the experiment on n0000&n0001. You should always be able to reproduce the issue by:
GASNET_BACKTRACE=1 mpirun -n 2 --bind-to none -H n0000,n0001 ./rendering -ll:csize 8192 -ll:gsize 0 -ll:lmbsize 8192

Commenting and uncommenting ``task->map_locally=true'' shows the difference.

**Comment by lightsighter** [comment]
Pull and try again.

**Comment by jiazhihao** [comment]
Fixed
