### ISSUE TITLE
Regent: aggregate reduction privileges in the default calling convention

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#991]
There was a time when (I believe) Legion required all reduction fields to be placed in their own region requirement. As a result, we split those out in Regent (one region requirement per field). I believe this is no longer necessary and that it would be more efficient (and better for some users) to aggregate them.

This is technically a breaking change to the calling convention, though I'm not aware of anyone who relies on it (except one person who is specifically asking for the change).

**Comment by lightsighter** [comment]
That's accurate from a Legion perspective. All fields in the same region requirement though must share the same reduction privileges and there is still no way at the moment to describe a reduction operator that operates on several fields simultaneously.

**Comment by elliottslaughter** [comment]
Pushed to branch `regent-reduction-field-aggregation`. Waiting for CI because my local installation is broken at the moment.

**Comment by elliottslaughter** [comment]
This should be fully functional now, so assuming it passes CI, I will merge it.

**Comment by elliottslaughter** [comment]
This is now merged into `master`.

**Comment by elliottslaughter** [comment]
Just a quick update to note that I changed this slightly, so that reductions are now sorted by the index of the first field that has that reduction op and type. This is intended to be more stable than my previous solution of sorting by reduction op ID, which could be unstable due to reduction ops that get generated dynamically by the Regent compiler.
