### ISSUE TITLE
Regent: Tracing nested loops behaviour

### ISSUE THREAD

**Issue by LonelyCat124** [StanfordLegion/legion#998]
I'm trying to trace some nested loops (non-index launches) which have some criteria on which elements are launched, however the same elements are used every time the code is reached. I was expecting to be able to do:
```
  __demand(__trace)
  for x=0,N do
    for y=0,N do
     if (some_criteria) then
       launch_task(region[int2d(x,y)])
    end
   end
  end
```

however what I found was that if each iteration of the x loop didn't spawn the same task count the trace would be rejected. Instead to do this I needed to do:
```
 __demand(__trace)
  for bogus_loop = 0,1 do
  for x=0,N do
    for y=0,N do
     if (some_criteria) then
       launch_task(region[int2d(x,y)])
    end
   end
  end
  end
```

The bogus loop then gets traced and can be replayed many times no problem. Is this the expected behaviour? Is there an alternative to this "bogus loop" if so? Full example:
```
import "regent"

fspace thing{
  thing1 : int,
  thing2 : int
}

local format = require("std/format")

thing_region = regentlib.newsymbol("things_region")

function create_some_tasks(things_partition)

local __demand(__leaf) task test_task( things : region(ispace(int2d), thing)) where reads(things), writes(things) do
  for thing in things do
    things[thing].thing1 = things[thing].thing1 + things[thing].thing2
  end
end

local quoted = rquote

  __demand(__trace)
--  for a=0, 1 do -- uncomment to work correctly.
  for x=0, 10 do
    for y = 0, 10 do
        if (x - y < 2) and (x - y > -2) then
            var bit : int2d = int2d({x, y})
            test_task([things_partition][bit])
        end
    end
--  end
  end
end
return quoted

end

task main()

  var [thing_region] = region(ispace(int2d, {100, 100}), thing)
  var things_partitioned = partition(equal, [thing_region], ispace(int2d, {10, 10}))
  for thing in [thing_region] do
    [thing_region][thing].thing1 = 1
    [thing_region][thing].thing2 = 2
  end

  for i = 0, 100 do
    [create_some_tasks(things_partitioned)];
    [create_some_tasks(things_partitioned)];
  end

end

regentlib.start(main)
```

(Its metaprogrammed due to my original problem code having metaprogramming and testing to see if that was the cause).

**Comment by elliottslaughter** [comment]
The semantics of `__demand(__trace)` is that it adds the begin/end trace calls immediately *inside* of the loop. That is, a loop like:

```
__demand(__trace)
for i = 0, N do
  ...
end
```

becomes

```
for i = 0, N do
  begin_trace()
  ...
  end_trace()
end
```

I think in that case that means that the iterations of the outer loop really are not equivalent. So this is expected behavior.

You don't need to literally use a bogus loop, you could instead do it with a `do ... end` block:

```
__demand(__trace)
do
  ...
end
```

Does that make sense? Perhaps some clarification in the documentation would help.

**Comment by lightsighter** [comment]
I'm confused: is this trace being rejected by the compiler with a static warning/error or by the runtime complaining that the trace cannot be captured for some reason?

**Comment by elliottslaughter** [comment]
The compiler has no static checks for `__demand(__trace)`. So this has to be a runtime error.

To be clear, I think this is an application bug. It is genuinely using the trace incorrectly.

**Comment by lightsighter** [comment]
Ok, that make sense. I would still like to see exactly which error message is being produced.

**Comment by LonelyCat124** [comment]
Yeah this is an application bug, I will post the error message tomorrow morning.
The syntax was this that I didn't know about is this:
```
__demand(__trace)
do
  ...
end
```

I think a note in the documentation might be helpful on how to trace for non-index launch / nested loops, though I'm not sure if this is a performant strategy either way.

**Comment by LonelyCat124** [comment]
The error was:
```
[0 - 7f55eb792780]    0.060057 {5}{runtime}: [error 363] LEGION ERROR: Trace violation! Recorded 2 operations in trace 1 in task main (UID 1) but 3 operations have now been issued! (from file /lustre/scafellpike/local/HT03020/lxm18/shared/legion/runtime/legion/legion_trace.cc:701)
For more information see:
http://legion.stanford.edu/messages/error_code.html#error_code_3
```

Which I assume just comes from the inner loop being "traced" and not being the same every time.

**Comment by lightsighter** [comment]
Ok good, that is the error message you should receive in this case. Each trace requires that it see the same order of operations on each invocation.

**Comment by elliottslaughter** [comment]
Documentation has been updated. Closing this issue now.
